### ISSUE TITLE
[enhancement] custom filename for lyrics

### ISSUE THREAD

**Issue by holytrousers** [CDrummond/cantata#1001]
good evening !
i'm back again, sorry :p
i suggest adding  the possibility to change the default naming pattern for saved lyrics.
so instead of /artist/title.lyrics one could change it to artist - titles.txt ?
that would help with issue #995 to share downloaded lyrics with other software ( bb010g already suggested a workaround that would solve 50% of the issue )
cheers !

**Comment by CDrummond** [comment]
No.
