### ISSUE TITLE
Korean album artists are not fully shown in library's grid view

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1002]
I'm using lubuntu 16.04 and please refer to the captured screen.
Final consonants are partially shown. (e.g. 모름, 이진아)

![2017-04-13-145614_784x457_scrot](https://cloud.githubusercontent.com/assets/12131158/24992036/02f58740-205a-11e7-81e7-32f5688cc56c.png)

**Comment by CDrummond** [comment]
Sorry, what??? I do not speak Korrean so this means **nothing** to me. The "..." is done by Qt - or rather Cantata asks Qt to create a string that will fit in X pixels, and Qt adds the ellipses if there is not enough space.

What I see is what I would expect.

**Comment by parkmino** [comment]
This happens in both English and Korean.
You mean that it is not Cantata's problem but Qt's and there's nothing you can do.

Then I'll close it.
