### ISSUE TITLE
Synchronization with device: no way to select all or delete files on device

### ISSUE THREAD

**Issue by UnicodeAlt255** [CDrummond/cantata#1003]
I have a lot of songs, and the fact that I have to individually check the box for every artist make the synchronization feature very inconvenient for me. Unless I'm missing something.

Also, is there no way of deleting files on my device? With changed metadata, such as adding a "The" in front of an artist will make the equivalent song on my device appear to be a different song, and no, I do not want to add it to my library. That makes no sense.

**Comment by CDrummond** [comment]
Sync is used for adding only - no files are removed. To remove files use main dialog.

Sorry, it makes no sense to you - I look forward to your work to fix this.

**Comment by UnicodeAlt255** [comment]
Will a feature for "select all" be added any time? That was my main concern. Also off topic - how are you able to be so on top of this project? I really appreciate your work.
