### ISSUE TITLE
kdeconnect

### ISSUE THREAD

**Issue by Svadkos** [CDrummond/cantata#1006]
Maybe smartphones with kdeconnect should be shown in devices menu too?

**Comment by CDrummond** [comment]
AFAIK, kdeconnect uses sshfs for file transfer - if so Cantata can already be compiled to transfer files via file-system mounts, ssh, or samba.

**Comment by Svadkos** [comment]
> AFAIK, kdeconnect uses sshfs for file transfer - if so Cantata can already be compiled to transfer files via file-system mounts, ssh, or samba.

Well, i can link it to music folder, if that is what you mean. But that way i can't use "copy to device" functionality, and thereby can't use audio converter.

**Comment by CDrummond** [comment]
You need to compile Cantata for remote devices - its not supported by default

**Comment by Svadkos** [comment]
Good, now it work. Thanks.
