### ISSUE TITLE
xdotool key not working with Cantata

### ISSUE THREAD

**Issue by Tormen** [CDrummond/cantata#1007]
Hi,

I tried commenting on a closed bug #572 ... but then I was not sure if you will notice my reply and might answer...

And as my issue (see question (2) below) seems actually new (searching for "xdo" in the complete issue history did not show any results), I thought why not file a proper new bug report.

My goal here is:
I would like to be able to skip ahead and skip back. Very useful while listening to audio-books.
And I would like to this while reading the ebook that the audiobook is about. So NOT having cantata window activated and visible.

While trying to achieve this goal I have 3 questions about global shortcuts:

/////////////////////////////////////////////////////////////////////////////////////
(1) This (what was stated in #572) did not change, right ?

I am wondering, because here : https://github.com/CDrummond/cantata/wiki/About-Cantata
it says:
Support for KDE global shortcuts (KDE builds), GNOME media keys (Linux only), and generic media keys (via Qxt support)

But on Archlinux I installed the "Qt5 client for the music player daemon (MPD)" community/cantata 2.0.1-1, which should be a KDE build... and under KDE system-settings shortcuts, global shortcurts, there is no cantata section. Just the media-controller section.

Is there a simple way to verify if my build is actually a KDE build ? (ldd ? ... shows libQt5Core.so.5, libQt5Gui.so.5, libQt5Widgets.so.5.... beside many other libraries...)

/////////////////////////////////////////////////////////////////////////////////////
(2) Now I noticed that there is actually a keyboard shortcut to do that within Cantata (even though it is NOT listed in the Keyboard Shortcut Settings page of cantata (?)): Ctrl + arrow-left / Ctrl + arrow-right

So I wanted to use xdotool to send the keyboard shortcut to cantata. But it does not work. And I don't know why.

Here is what I am trying (I started with ctrl+q because it is very easy to see if it worked ;)):
for win in $(xdotool search --class cantata); do echo "$win"; xdotool key --clearmodifiers --window $win Ctrl+q; done

And I wonder why it does not work, because just the same works fine with gimp:
for win in $(xdotool search --class gimp); do echo "$win"; xdotool key --clearmodifiers --window $win Ctrl+q; done

/////////////////////////////////////////////////////////////////////////////////////
(3) Do you have another idea how one could achieve a global shortcut (meaning a shortcut within KDE, not bound to condition that the Cantata window has to be visible and activated) ?
Can one maybe use the Cantata-remote script [1] to achieve skipping/jumping forward / backwards ?

[1] https://github.com/CDrummond/cantata/blob/master/cantata-remote.cmake

Thanks a lot in advance!!!

Tormen

**Comment by CDrummond** [comment]
Cantata for Qt5 is **not** a KDE app. Only the KDE4 was supported - as of 2.1.0 (the next release) Cantata will be Qt5 only.

You can use shell scripts + mpc to do what you wish to accomplish.

**Comment by CDrummond** [comment]
From 2.1.0 onwards you will be able to trigger all of the configurable actions vis DBUS. See the README for more details. This should allow using the cantata-remote script to provide some support for global shortcuts.

**Comment by Tormen** [comment]
Thanks a lot for all your answers + clarifications + changes !!!

2.1.0 sounds very interesting :))
Any idea of the release timeframe ?

**Comment by CDrummond** [comment]
To be honest, no idea! Hopefully not too long!
