### ISSUE TITLE
3 different skip or jump forward / backward delays with up to 6 different keyboard shortcuts

### ISSUE THREAD

**Issue by Tormen** [CDrummond/cantata#1008]
Related to #566:

I would like to propose to allow adding 3 different delays with up to 3*2 different shortcuts associated to them:

   * short jump      _back_ / _forth_
   * medium jump _back_ / _forth_
   * large jump      _back_ / _forth_

Why ? 

Listening to music / audiobooks and wanting to listen /again/ to something you did not quite hear well a SHORT jump-back is useful:
   +/- 5sec   or    +/-10sec

Then tyring to find something or get to a certain position in an audio file you generally need 2 shortcuts:
+/- 1min  == MEDIUM jump
+/- 10min == LARGE jump

I got to love these 3 different shortcuts in mplayer first:
   * arrow left, right == SHORT jump back / ahead
   * arrow up, down == MEDIUM jump ahead / back
   * page up, down == LARGE jump ahead / back

Then vlc now offers the same possibility.

I propose to offer at least 3 mentioned jump levels "short", "medium", "large" - I think vlc offers "micro" and "extra-large" in addion - and then you offer the possibility to assign keyboard shortcuts to whatever delay you need in the keyboard shortcut settings page.

All useful delays I could think of:
   +/- 1 sek
   +/- 3 sek
   +/- 5 sek
   +/- 10 sek
   +/- 30 sek
   +/- 1min
   +/- 10min
   +/- 30min
   +/- 60min

But having 3 times assigned fix to these 3 jump types should also be totally fine. And you can change them in the code at compile time... ... or make them configurable... or offer all of the above jumps forward / backward and then let the user pick and assign keyboard shortcuts to whatever they like.

What do you think ?

Thanks a lot,

Tormen

**Comment by CDrummond** [comment]
In master, for 2.1.0 release. Skip levels 5seconds, 30seconds, and 60seconds.

**Comment by Tormen** [comment]
Thanks a lot!! - Sounds very good :))

Any chance that these delays are changable without recompiling ?
