### ISSUE TITLE
Jump or Skip keyboard shortcuts are not part of the keyboard shortcut settings page

### ISSUE THREAD

**Issue by Tormen** [CDrummond/cantata#1009]
Hi,

Related to #566 I noticed, that the ctrl+arrow-left, ctrl+arrow-right jump/skip 5sek forward, backward keyboard shortcuts are /not/ part of the keyboard shortcuts settings page.
They are a hidden feature of sort. Which is not so intuitive.

Also I opened #1008 which could be resolved with this one together.
And as a possible workaround I tried xdotool which did not work and so I opened #1007.

It would be great to have all the shortcuts that are available within Cantata also accessible via the KDE system-settings shortcuts dialog as (true) global shortcuts (and/or) have an option with Cantata to state that this shortcut should be GLOBAL (within KDE)...

I would be really grateful for any help. I /know/ that you are doing this in your spare time. And I'd love to try to help... even though I never programmed QT yet ;) 
And/or offer you a coffe or donate if you could help me straighten out these keyboard shortcut issues.

Thanks a lot,

Tormen

**Comment by CDrummond** [comment]
Fixed in master  - for 2.1.0

The **ONLY** global shortcuts are media keys - there will be no others.

**Comment by CDrummond** [comment]
From 2.1.0 onwards you will be able to trigger all of the configurable actions vis DBUS. See the README for more details. This should allow using the cantata-remote script to provide some support for global shortcuts.

**Comment by Tormen** [comment]
OK, super. To what charity should I send the money ? Amnesty international ? or Amnesty for women ?
... or a paypal in your direction ?

**Comment by CDrummond** [comment]
I maintain Cantata purely for fun - which is what I think opensource should be.

So, thanks - but no thanks to any money :-)

As to where to donate, and even how much, I leave that totally up to you :-)
