### ISSUE TITLE
Incorrect D-Bus service name used

### ISSUE THREAD

**Issue by hadess** [CDrummond/cantata#1010]
at https://github.com/CDrummond/cantata/blob/master/dbus/gnomemediakeys.cpp#L34
See https://mail.gnome.org/archives/desktop-devel-list/2017-April/msg00069.html

**Comment by CDrummond** [comment]
Changed in master for 2.1.0 Although, in Ubuntu GNOME 17.04 I don't seem to have either service - but keys work if MPRIS is enabled.

**Comment by Thaodan** [comment]
Just curios but why needs gnome their extra code?
