### ISSUE TITLE
Please add support for "Original year"

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#1012]
Dunno if you want to wait until it's in a released version, but the MPD trunk now supports the "original year" track. It would be great if Cantata supported it. Then you could use "Year" for determining the album year but "Original Year" for tracks (crucial for retrospective compilation albums).

**Comment by CDrummond** [comment]
What is the name of the value from MPD? e.g. MPD uses "Artist:" for the artist tag. I dont have the latest MPD, so cannot determine. If you do, the do the following:

1. Open terminal
2. telnet localhost 6600
3. When connected to MPD, as it to list the info for a directory with MP3 (note the dir is relative to your MPD root) e.g.:

```
$ telnet localhost 6600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.19.0
lsinfo Vangelis/Voices
```

Within the returned info should be the value you need - e.g. OriginalDate: 2017

It is this "OriginalDate" (or whatever it is really called) that I need to know.

**Comment by CDrummond** [comment]
Initial implementation now in git/master (for 2.1.0). Any chance you could checkout and try? My MPD is too old for this.

**Comment by chowbok** [comment]
Works great, thanks! I'm so glad to have this.
I have a related request: let me know if I should open a new issue for it if instead. Can there be an option to display the originaldate next to the song title in the toolbar?

**Comment by CDrummond** [comment]
Done :-)
