### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by PECgeo** [CDrummond/cantata#1016]
Hi
# cmake .. -DENABLE_KDE=ON
-- Set build type to Release
-- Taglib found: -L/usr/local/lib -ltag
-- Taglib-Extras found: -L/usr/local/lib -ltag-extras
-- Found MTP: /usr/local/lib/libmtp.so
qmake: could not exec '/usr/local/lib/qt5/bin/qmake': No such file or directory
CMake Error at /usr/local/share/cmake/Modules/FindQt4.cmake:1302 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:317 (find_package)

-- Configuring incomplete, errors occurred!

/usr/local/include/taglib -DTAGLIB_CAN_SAVE_ID3VER -o CMakeFiles/cmTC_0dd6a.dir/src.cxx.o -c /usr/home/mediaone/cantata-2.10/build/CMakeFiles/CMakeTmp/src.cxx
/usr/home/mediaone/cantata-2.10/build/CMakeFiles/CMakeTmp/src.cxx:1:10: fatal error: 'taglib/mpegfile.h
'taglib/mpegfile.h is installed at /usr/local/include

[CMakeError.log.zip](https://github.com/CDrummond/cantata/files/980064/CMakeError.log.zip)
[CMakeOutput.log.zip](https://github.com/CDrummond/cantata/files/980066/CMakeOutput.log.zip)

As side note I have no qt5 modules installed
Thanks

**Comment by CDrummond** [comment]
Qt4 and KDE4 are no longer supported, Q5 only.

However, this looks like an issue on your system. Sorry, dont have FreeBSD installed - and have no intention of installig.
