### ISSUE TITLE
reload playlist folder configuration

### ISSUE THREAD

**Issue by ki00** [CDrummond/cantata#1017]
sometimes when I reboot the system I need to configure again and again the playlist location in order to play it:
 
> Fallo al enviar la orden a "Personal": no conectado

Also, when I use a live session and come back to system it crashes and show this (and can not access the playlist location original)
https://pastebin.com/aKVNqzpF

**Comment by CDrummond** [comment]
Does this only happen with the 'Personal' MPD instance? What is the MPD folder set to?
 
What version of Cantata 2.0.1? If so, any chance you could checkout git/master? There have been some fixes for this 'Personal' mode.

**Comment by ki00** [comment]
Inded I hay only used one user configuration. Sometimes (not always) the program ask to do manual update in order to play the playlist. It only says Cantata 2.0.1.

**Comment by CDrummond** [comment]
Hmmm... if its asking to reconfigure then this would imply the config file has been corrupted somehow.

Anyway, is it possible for you to try the lastest git version? (You will need to compile this yourself)

**Comment by ki00** [comment]
I am not a programmer. Do not know to do it properly. Sorry. If you need a log or something related, it could be easier to do, however, I had reinstalled the os. Also you said it has been reported, so is useless all these. Thanks.

**Comment by ki00** [comment]
If this issue has been reported, please close this thread. I will report more issues, and if them have been reported, the threads can be closed. Thank you.

**Comment by CDrummond** [comment]
As stated, there has been a few changes. However, this is not a feature I use, so dont have time to support anymore - and will be disabled by default in future builds.
