### ISSUE TITLE
CDParanoia -> GNU libcdio

### ISSUE THREAD

**Issue by kyrios123** [CDrummond/cantata#1021]
CDParanoia seems to be abandoned since it hasn't been updated since 2008 !
[GNU libcdio](https://www.gnu.org/software/libcdio/) is actively maintained and includes cdparanoia library and cdparanoia command (at the time of writing this, the latest available versions is [10.2+0.94+1](https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+0.94+1.tar.gz) released on 2017-03-25).
Could you see if it would be possible to use this wine cantata ? (*)
The goal is to avoid packaging some outdated dependencies - even if they still works very well - when actively maintained forks are available.

Thanks !

(*) I did a test but the cmake script  fails to find what it needs:
```-- Could NOT find Cdparanoia (missing:  CDPARANOIA_LIBRARIES CDPARANOIA_INCLUDE_DIR) ```

**Comment by CDrummond** [comment]
Done, for 2.1.0
