### ISSUE TITLE
fatal error: cdio/paranoia.h: No such file or directory

### ISSUE THREAD

**Issue by gericom-hummer** [CDrummond/cantata#1022]
`gericom@manjaro ~/PPA/Manjaro/cantata $ makepkg
==> Making package: cantata 2.0.50.20170605.r6315.f4d55046-1 (Mon Jun  5 06:42:55 EEST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating cantata git repo...
Fetching origin
==> Validating source files with sha1sums...
    cantata ... Skipped
==> Extracting sources...
  -> Creating working copy of cantata git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 6.3.1
...
-- Performing Test TAGLIB_CAN_SAVE_ID3VER - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libcdio_paranoia'
--   Found libcdio_paranoia, version 10.2+0.94+1
-- Found CDIOPARANOIA: /usr/include  
-- Found CDDB: /usr/include  
...
-- Enabling exceptions
-- Using supplied libebur128
-- Found UDev: /usr/include  
-- Building Solid UDev backend.
-- Building Solid HAL backend.
-- Building Solid UDisks2 backend.

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * TagLib - Tag editor, file organiser, etc.
   * libcdio_paranoia - CD ripping.
   * libcddb - CD info retrieval via CDDB.
   * libmusicbrainz5 - CD info retrieval via MusicBrainz.
   * TagLib-Extras - Tag editor, file organiser, etc.
   * libavcodec/libavutil/libavformat - ReplayGain calculation.
   * libmpg123 - ReplayGain calculation.
   * libmtp - MTP Device Support.
   * UDev - UDev support for Solid
   * media-player-info - Enables identification and querying of portable media players

-----------------------------------------------------------------------------
-- Congratulations! All external packages have been found.
-----------------------------------------------------------------------------

-----------------------------------------------------------------------------
-- The following STANDARD options have been DISABLED.
-----------------------------------------------------------------------------
    * MPD HTTP Streams - Playback MPD HTTP output stream via libVLC.

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_KDE

-- Build files have been written to: /home/gericom/PPA/Manjaro/cantata/src/build
[  1%] Generating moc_qtiocompressor.cpp
Scanning dependencies of target qtiocompressor
[  1%] Building CXX object 3rdparty/qtiocompressor/CMakeFiles/qtiocompressor.dir/qtiocompressor.cpp.o
[  1%] Building CXX object 3rdparty/qtiocompressor/CMakeFiles/qtiocompressor.dir/moc_qtiocompressor.cpp.o
[  1%] Linking CXX static library libqtiocompressor.a
[  1%] Built target qtiocompressor
[  2%] Generating backends/udisks2/dbus/moc_manager.cpp
...
[ 71%] Building CXX object CMakeFiles/cantata.dir/http/httpserver.cpp.o
[ 71%] Building CXX object CMakeFiles/cantata.dir/http/httpsocket.cpp.o
In file included from /home/gericom/PPA/Manjaro/cantata/src/cantata/http/httpsocket.cpp:29:0:
/home/gericom/PPA/Manjaro/cantata/src/cantata/devices/cdparanoia.h:32:27: fatal error: cdio/paranoia.h: No such file or directory
 #include <cdio/paranoia.h>
                           ^
compilation terminated.
make[2]: *** [CMakeFiles/cantata.dir/build.make:4369: CMakeFiles/cantata.dir/http/httpsocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/cantata.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by CDrummond** [comment]
Hmm... odd. The look like CMake found the header. What does `pkg-config --variable=includedir libcdio_paranoia` return?

**Comment by gericom-hummer** [comment]
/usr/include

**Comment by CDrummond** [comment]
And you does /usr/include/cdio/paranoia.h not exist? This looks like an issue on your system. pkg-config is supposed to give info about installed libraries, and where to find there header files.

Do you have "cdio/paranoia.h" anywhere on your system? Do you have the libcdio_paranoia devel package installed?

**Comment by gericom-hummer** [comment]
/usr/include/cdio/paranoia/paranoia.h
/usr/include/cdio/paranoia/cdda.h
/usr/include/cdda_interface.h
/usr/include/cdda_paranoia.h

I am with Manjaro, just in case, and i am building cantata for my repo since many time and the last successful build was on  2017-05-25

**Comment by CDrummond** [comment]
Please update and try again.

**Comment by gericom-hummer** [comment]
It is fixed! Everything is perfectly fine now. Thanks a lot.
