### ISSUE TITLE
Visual studio build and more

### ISSUE THREAD

**Issue by rezodlub** [CDrummond/cantata#1023]
I ran into a few problems, trying to build latest cantata with Visual studio on windows. I did fix them already, but wonder how I could contribute the fixes. Affected issues are:

 empty folders on MPD side (crash inserting/removing to/from model)
 usage of sys/time.h changed to QTime
 no unistd.h in Visual Studio
 if QT was build without SSL support, there is no QSslSocket class (at least in 5.6 and 5.8)
 missing strncasecmp in Visual Studio
 utime.sys is actually sys/utime.h in Visual Studio

 ... also - I noticed that there are a few icons missing - for:
menu, play, play now, append to play, repeat, random, center on current track, save as, clear, folder in folder view and the icon in front of each song ... there might be more, but those are the ones I noticed

**Comment by CDrummond** [comment]
To be honest, I have no real interest in Windows (or macOS). I created the builds just to see - and they seem to work OK for my builds. My Windows builds use MinGW, and work OK. As for Visual Studio - again no real interest from me.

That being said, if you wish to supply a pull request / path that fixes any issues then great - just I will not be able to help much, and have no intention of installing Visual Studio just for this. As I said, MinGW seems to work OK.

**Comment by CDrummond** [comment]
Just wanted to say - thanks for the pull request. It's so much nicer when someone else fixes the issues :-)

I've added a couple of comments to the pull request.

**Comment by CDrummond** [comment]
Closing, as pull request accepted. Missing icons is probably due to Cantata not being run from install folder - it loads font awesome TTF file to obtain icons.
