### ISSUE TITLE
Feature Request - Buffer status

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#1027]
I'm using Cantata with the HTTP audio output. 
Cantata doesn't give much details about the state of this stream. Is it possible to have some visual feedbacks, for example filling the timebar with the buffer current status. Can you get those information from libvlc ?

![](http://s8.postimg.org/jgr75sh2t/VLC.png)
![](https://i.stack.imgur.com/ScJFq.png)

**Comment by CDrummond** [comment]
While I would imagine this is possible - it's not a feature I implemented or used. So, it you want something like this you will need to do yourself.
