### ISSUE TITLE
Album grouping

### ISSUE THREAD

**Issue by sanyarnd** [CDrummond/cantata#1031]
Hi. Cantata looks great, but there's one thing missing.
If you have 2 identical albums, located in different folders, tagged with different year, label etc, Cantata goups them together, leaving you with duplicated songs. in playlist:
```
1. ...
1. ...
2. ... 
2. ...
```

I know that Cantata is looking for Album name, but can you make Cantata look for the year as well?

**Comment by CDrummond** [comment]
No. As different tracks can have different years. The **only** way to differentiate albums of the same name+artist is to use the "music brainz album id" tag. Both MPD and Cantata support this.

**Comment by sanyarnd** [comment]
Well, then I don't understand something.
I have collection of MB tagged albums, and I did check -- album IDs are different. Still, they're combined in both "by artist" and "by album" views.

**Comment by CDrummond** [comment]
You need to configure MPD to use this tag - and then refresh Cantata's cache. Whilst this is not something I personally use (I have no duplicate albums) - I have tested (very recently) by jsut creating a fake music brainz id, and it does work.

**Comment by CDrummond** [comment]
All that being said. MPD now supports the "Original Year" tag. So, I' guessing 'year' should be a album year, and 'original year' for the year of the track. If so, then grouping by year should probably be the default.

Hmmm... OK, what I'll do is  - use musicbrainz id if set, if not use 'album name + year'

**Comment by CDrummond** [comment]
Implemented for 2.1.0

**Comment by CDrummond** [comment]
I have reverted the name+year grouping - causes other issues that I do not have time to fix. Anyway, it would still be possible to have two identically named albums in the same year (e.g. releases in different countries, etc) - therefore music brainz id is more reliable.

**Comment by sanyarnd** [comment]
Any tips for MPD and MB tag? I have local MPD configuration (the second option at initial setup).

**Comment by CDrummond** [comment]
Ah, that probably wont work then. If you are using a Cantata controlled MPD, then by default it only looks for the following tags:

artist,album,title,track,name,genre,date,disc,albumartist,composer

you need to edit ~/.local/share/cantata/mpd/mpd.conf so that 

metadata_to_use	"artist,album,title,track,name,genre,date,disc,albumartist,composer"

is 

metadata_to_use	"artist,album,title,track,name,genre,date,disc,albumartist,composer,musicbrainz_albumid"

...I'll update the supplied template config.
