### ISSUE TITLE
build error on Fedora 25

### ISSUE THREAD

**Issue by dominik96** [CDrummond/cantata#1033]
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
support/CMakeFiles/support.dir/build.make:374: recipe for target 'support/CMakeFiles/support.dir/moc_urllabel.cpp.o' failed
make[2]: *** [support/CMakeFiles/support.dir/moc_urllabel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/data/dokuments/rpmbuild/BUILD/cantata-2.0.50/x86_64-redhat-linux-gnu'
CMakeFiles/Makefile2:396: recipe for target 'support/CMakeFiles/support.dir/all' failed
make[1]: *** [support/CMakeFiles/support.dir/all] Error 2
make[1]: Leaving directory '/data/dokuments/rpmbuild/BUILD/cantata-2.0.50/x86_64-redhat-linux-gnu'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/data/dokuments/rpmbuild/BUILD/cantata-2.0.50/x86_64-redhat-linux-gnu'
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.5RH7EC (%build)

%prep
%setup -q
rm -rfv qtsingleapplication/

%build

export CFLAGS="%{optflags} -Os -fPIE -fuse-ld=gold -fuse-linker-plugin"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie $CFLAGS"
export QTDIR="/usr/lib64/qt5"
export PATH="$QTDIR/bin:$PATH"
mkdir -p %{_target_platform}
pushd %{_target_platform}
cmake \
 -DCMAKE_INSTALL_PREFIX="%{_prefix}" \
 -DCANTATA_TRANSLATIONS="de" \
 -DCMAKE_BUILD_TYPE=Release \
 -DENABLE_QT5=ON \
 -DENABLE_KDE=OFF \
 -DENABLE_EXTERNAL_TAGS=OFF \
 -DENABLE_KWALLET=OFF \
 -DENABLE_HTTP_STREAM_PLAYBACK=OFF \
 -DENABLE_LIBVLC=OFF \
 -DENABLE_HTTP_SERVER=OFF \
 -DENABLE_PROXY_CONFIG=OFF \
 -DENABLE_DEVICES_SUPPORT=OFF \
 -DENABLE_REMOTE_DEVICES=OFF \
 -DENABLE_UDISKS2=OFF \
 -DINSTALL_UBUNTU_ICONS=OFF \
 -DCANTATA_HELPERS_LIB_DIR=/usr/lib64/cantata \
 -DENABLE_SIMPLE_MPD_SUPPORT=ON \
 ..
popd
%{__make} %{?_smp_mflags} -C %{_target_platform}

%install
make install/strip DESTDIR=%{buildroot} -C %{_target_platform}
exit 0

**Comment by CDrummond** [comment]
Don't know what you expect me to do - seeing as there is no explanation as to why the build failed. The following only tells me that a **very** simple class ha failed to build:

`support/CMakeFiles/support.dir/build.make:374: recipe for target 'support/CMakeFiles/support.dir/moc_urllabel.cpp.o' failed
make[2]: *** [support/CMakeFiles/support.dir/moc_urllabel.cpp.o] Error 1`

Sorry, but Cantata is building just fine for me. I can't check every Linux system out there - if you want me to 'fix' this, then I'll need to know why its failing. Try a completely clean build.

**Comment by CDrummond** [comment]
As stated works for me, under Ubuntu 17.04 - even when using your CMake options.

Sorry, but without more info there is nothing I can do.
