### ISSUE TITLE
mpris property 'CanSeek' is always set to true

### ISSUE THREAD

**Issue by eduardosm** [CDrummond/cantata#1034]
The mpris property 'CanSeek' is always set to true (checked using d-feet) even when the seek bar in Cantata is disabled (for example, when playing a radio stream).

**Comment by CDrummond** [comment]
Fixed now.

**Comment by eduardosm** [comment]
Thanks for the quick response. However it does not seem to be fixed. Maybe you should use something
like done in https://github.com/CDrummond/cantata/blob/e22dcf6d8c94d5ae755ba3d89e51b9402b2de585/gui/mainwindow.cpp#L1735

**Comment by CDrummond** [comment]
Good point - I should read the issue description more carefully!!

**Comment by CDrummond** [comment]
Fixed now?

**Comment by eduardosm** [comment]
Yes, it is fixed now. Thank you!
