### ISSUE TITLE
Playing YouTube audio

### ISSUE THREAD

**Issue by rezodlub** [CDrummond/cantata#1036]
Are there any plans on adding Youtube support to Cantata? I'd be willing to do the coding, if you'd include the support. The idea is to add 'Youtube' to the 'Internet' tab, which would display a really simple browser based on QtWebEngine (chromium), and would include 'Back', 'Home', 'Play now' and 'Append to play queue'. Links could be generated by spawning a 'youtube-dl' process. This approach could actually work on most youtube-dl supported sites: https://rg3.github.io/youtube-dl/supportedsites.html

 ... let me know what you think.

**Comment by CDrummond** [comment]
Would you really need to embed a web engine? Seems a bit overkill. Do the sites not support searching?

It's not something that I would personally use. I tried youtube-dl but had long delays before songs would start - almost like it downloaded the complete video, before MPD started to play.

But, if you wish to implement this, then I'll happily accept a merge request - as long as it does not affect much of the rest of the code.

**Comment by rezodlub** [comment]
I also have some delays with youtube-dl, which could be made much shorter with custom c++ implementation, but then we'd have to keep re-fixing it every time youtube changes their coding. That's why I thought of using external tool, which is still being maintained. BTW, quite a bit of delay is actually not due to youtube-dl, but MPD's communication/buffering. Just tried - youtube-dl needed 3sec to get the link, while MPD can take anything from 2 to 13 seconds depending on container/codec and secure/insecure communication (worst being secure mp4a - format 140, while opus/vorbis seem to stay in 2-3 sec delay).

Web engine ... don't really know how else to comfortably select the song(s) I want. Got any better idea? What did you have in mind with 'Do the sites not support searching?'

**Comment by CDrummond** [comment]
There's a plugin for logitech media server that implements youtube search and playback - perhaps you can look at this for inspiration.

As to search, I was hoping youtube at least would have an API that you can call - .e.g. https://youtube.com/api/search?query="Wibble wobble" Then parse the results to get the song links.

**Comment by themasch** [comment]
Theres is indeed some API do deal with youtube content: https://developers.google.com/youtube/v3/
It requires an oauth authentication to be used, though.

**Comment by CDrummond** [comment]
As stated, this is not a feature I wish to personally spend time on. Pull requests welcome. Also, as stated, logitech media server (which is what I now personally use) has a plugin to play youtube tracks. This also needs an API key, and users need to supply their own.

**Comment by CDrummond** [comment]
Almost 2 months since the initial report, and no work. As stated, I'm not opposed to the idea, just don't have the time for this. So, closing - but feel free to work on and create a pull request.

**Comment by bendschs** [comment]
+1
