### ISSUE TITLE
Handle case: socket not yet available

### ISSUE THREAD

**Issue by a-mair** [CDrummond/cantata#1037]
Hi,

I'm running mpd in my user's session and cantata is restored by my desktop environment's session management. Unfortunately mpd's socket file hasn't been created when canata tries to open it.

Now I have to open cantata's settings and simply close it again so that cantata connects to mpd.

I'd suggest that cantata waits for the socket to appear (inotify ...) and then connects to mpd. A "reconnect" button in cantata's main window would be very handy if unconnected.

Best regards,
Andreas

**Comment by CDrummond** [comment]
Which version of Cantata is this? If it's not git/master, can you please checkout and try that? The latest version will attempt to talk to mpd at least once every 5 seconds. This should then detect that the socket is closed, and prompt to reconnect.

**Comment by a-mair** [comment]
I used git/master from 2017-05-27. I've updated now and cantata connected to mpd on login. Sorry for not updating before opening this issue.

**Comment by a-mair** [comment]
Hi,

sorry for reopening that ticket but it doesn't work sometimes.
It had been working better but sometimes it still doesn't connect to mpd.

Regards,
Andreas

**Comment by CDrummond** [comment]
Cantata has a 'basic' mode, in which it starts an instance of MPD itself. Are you using this? (I assume not, just checking).

If you are not using the 'basic' mode, does the MPD socket file not exist? Or does it exist but MPD has not yet opened it?

I've tried configuring Cantata with an MPD socket of "/tmp/test" I then start Cantata, and it complains that it could not connect. I quit Cantata, and create an empty "/tmp/test" - restarting Cantata I get the same error message. This is as expected.

Do you not see an error message when Cantata starts, but cannot connect to the socket file?

**Comment by a-mair** [comment]
MPD isn't started by Cantata but by using ~/.config/autostart/mpd.desktop. Cantata gets started by KDE's session restore (when it has been active at shutdown).

I don't see an error message. After KDE login the pid file exists and MPD is running but Cantata shows no playlist and I have to reconnect manually. I can only see my manual connect in mpd.log.

**Comment by CDrummond** [comment]
To be honest, I'm not sure what to do. The first thing Cantata does on start-up is to connect to MPD. If this fails you should see an error - which is what I'm seeing. If you are not seeing an error, then I'm at a loss as to why.

**Comment by a-mair** [comment]
I've made some tests and can see different results:
1) if Cantata starts directly into systray there's no error message
2) if Canata opens its main window at startup then error messages are shown (cannot connect to ... / error sending command ...)

In my case Cantata always runs in systray so I never see error messages.

In your first comment you said it tries to reconnect every 5 seconds. This never happens here.
There also a difference behavior in Cantata:
* can't connect to MPD at startup: artists are shown
*if it loses connection to MPD: artists aren't shown

**Comment by CDrummond** [comment]
Please try editing gui/mainwindow.cpp and change line 1005 from:

```
void MainWindow::showError(const QString &message, bool showActions)
{
    if (QLatin1String("NO_SONGS")==message) {
        messageWidget->setError(tr("Failed to locate any songs matching the dynamic playlist rules."));
    } else {
        messageWidget->setError(message);
    }
    if (showActions) {
        messageWidget->setActions(QList<QAction*>() << prefAction << connectAction);
    } else {
        messageWidget->removeAllActions();
    }
    if (!message.isEmpty()) {
        expand();
    }
    QApplication::alert(this);
}
```

to:

```
void MainWindow::showError(const QString &message, bool showActions)
{
    if (!message.isEmpty()) {
        if (!isVisible()) {
            show();
        }
        expand();
    }

    if (QLatin1String("NO_SONGS")==message) {
        messageWidget->setError(tr("Failed to locate any songs matching the dynamic playlist rules."));
    } else {
        messageWidget->setError(message);
    }
    if (showActions) {
        messageWidget->setActions(QList<QAction*>() << prefAction << connectAction);
    } else {
        messageWidget->removeAllActions();
    }
    QApplication::alert(this);
}
```

This then resolves the non-showing error for me. What it does is shown the Cantata window if any error is to be displayed.

The 5 second thing is not valid for this bug, sorry. Cantata will only send the messages every 5 seconds if its connected.

Does the above help? It should at least allow you to connect easier by pressing the connect button.

As to

> There also a different behavior in Cantata:
> - can't connect to MPD at startup: artists are shown
> - if it loses connection to MPD: artists aren't shown

Not sure what you mean by the second part. Do you mean Cantata was connected to MPD, it looses the connection some time later, and then the artist list (on the left had side (library view?)) is cleared? Never seen this.

**Comment by a-mair** [comment]
Thanks for the patch. Will try.

> Not sure what you mean by the second part. Do you mean Cantata was connected to MPD, it looses the connection some time later, and then the artist list (on the left had side (library view?)) is cleared? Never seen this.

Yes, I was talking about the main area in library view. If Cantata fails to connect at startup I can see the artist images. If Cantata is connected to MPD and I kill MPD then main area gets cleared.

**Comment by CDrummond** [comment]
Ah, yes - I see what you mean. When the connection is lost the library  playlists, playqueue, etc views are cleared. Clearing these on initial connection failure make sense to - for consistency.

**Comment by a-mair** [comment]
OK, the patch works the way you've written. Thanks.

> The 5 second thing is not valid for this bug, sorry. Cantata will only send the messages every 5 
seconds if its connected.

No way to reconnect for Cantata to receive an event/notification if the socket is available and ready for connecting?

I wonder why I first see a (roughly translated from German translation) "connection to ... failed" message and then a "error sending command to ... - not connected" message. If not connected to MPD: why send a command?

**Comment by CDrummond** [comment]
Can you please checkout git/master and try again? I've updated the code so it will try to reconnect every .5 seconds on start-up.

**Comment by a-mair** [comment]
Thanks for that change. So far it seems to work but I'll keep an eye on it and will report back.

**Comment by CDrummond** [comment]
Closing, as this is the best I think its gonna get.
