### ISSUE TITLE
Cantata loses replay gain setting

### ISSUE THREAD

**Issue by meadowlands** [CDrummond/cantata#1041]
Every time I open Cantata (2.0.1), I've to go to Configure > Playback and set Replay gain to "album".
It seems it can remember my preference if I close the application and start it again, but after a reboot I always find the default setting "none" selected. How to make "album" the new default?

**Comment by CDrummond** [comment]
Looks like MPD does not persist this setting! You can manually update the config file, as a work-around for now.

I'll update Cantata to store this setting in its config file, it can the restore on connect.

**Comment by CDrummond** [comment]
Should be fixed in master for 2.1.0. Any chance you can checkout master, compile, and confirm?

**Comment by meadowlands** [comment]
Successfully compiled on Manjaro KDE, now Cantata (2.0.50) can remember my Replay gain preference. Thank you for the quick fix, and for this great music player overall!

**Comment by CDrummond** [comment]
Thanks for the confirmation. I'm guessing this is really an MPD bug - as it lets clients change the replaygain setting, but does not persist changes. My fix is only a work-around.
