### ISSUE TITLE
don't cache whole library

### ISSUE THREAD

**Issue by azrdev** [CDrummond/cantata#1043]
As I understand it cantata keeps a cache of the whole mpd library -- please correct me if I'm wrong with that.

Since syncing the library can take a long time, I filed https://github.com/MusicPlayerDaemon/MPD/issues/79, which got rejected because full library sync is not deemed acceptable behaviour by MPD:

> Clients like Cantata and MPDroid are shit if they do this. I refuse to even talk about this "use" of the protocol. I can talk to developers about alternatives, but not about downloading the whole library.

**Comment by CDrummond** [comment]
This is the way Canata is, and always has been - even QtMPC (from which I forked Cantata) had this. Want it changed? Then feel free to provide a pull request to do this - but it will need to allow cantata to:

1. Fallback to 'Artist' for **albums** with no album artist
2. Determine track count for albums
3. Determine total duration for albums
4. Provide folder for albums - so as to obtain cover

And, how often do you realistically add new music? I spend more time listening to what I have than addding more. Therefore, the sync time does not occur often - and takes less than 2 seconds for my 10,000 tracks.

Sorry, but I have no time for this.
