### ISSUE TITLE
wrong cover copied (transcoding / audio CD ripping)

### ISSUE THREAD

**Issue by xdarklight** [CDrummond/cantata#1044]
I've observed some strange behavior multiple times now:
* if I only copy one audio CD to my collection (or transcode just one album and copy the result to my mobile phone) then the cover is set correctly
* however, if I copy multiple audio CDs to my collection, the first cover is set correctly - but the cover for the second (and all consecutive) CDs is wrong (it simply re-uses the first cover)
* (I'm pretty sure I've had this when transcoding multiple albums and copying them via MTP to my mobile phone)

can you reproduce this?

I'm running Cantata 2.0.1 from Arch Linux official repos: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cantata

**Comment by CDrummond** [comment]
CD covers should now be fixed - the downloaded cover was not deleted when the disk was removed. Can you please update and confirm?

As to MTP, seems to be working just fine for me. I've tried with copying the cover to AlbumArt.jpg and embedding the cover within the files - all albums had the correct covers.

**Comment by CDrummond** [comment]
There was an issue with MTP, fixed now.
