### ISSUE TITLE
support other 3th parte radio station?

### ISSUE THREAD

**Issue by bodsch** [CDrummond/cantata#1046]
What an expense would it be to support another radio (e.g., http://www.radio.de/) station next to shoutcast?

**Comment by CDrummond** [comment]
Does it have an API for apps to interact with? I could not see anything from a quick look at the website (www.radio.net - as its in English) Without an API Cantata has no way of accessing the station list, or searching. Scraping the web page is not feasible, as this is subject to change.

**Comment by bodsch** [comment]
i will ask the company. ;)

**Comment by CDrummond** [comment]
Any updates?

**Comment by CDrummond** [comment]
Closing. But if you do eventually find the API - feel free to email me (my address is in the README file)
