### ISSUE TITLE
Stream metadata not showing in toolbar Info

### ISSUE THREAD

**Issue by themasch** [CDrummond/cantata#1047]
When playing a song from my library, the popup that opens when you click on the info icon in the systray displays track information and even a cover if possible.
When playing a stream, the track information is available in the cantata gui and when hovering over the cantata icon in the systray (not the info/control one) but it isn't shown in the info area. 

![image](https://user-images.githubusercontent.com/170171/28668237-33c5fa04-72cf-11e7-8f6b-343f5aa519a5.png)
This one even contains the Album name of the last played song from my library. 

The full UI however has the information: 
![image](https://user-images.githubusercontent.com/170171/28668298-5c02e9f0-72cf-11e7-8552-2a472c898bcd.png)

I'm using cantata 2.0.1, installed from gentoo portage on gentoo linux, kernel 4.4.39 (oh, I should update that), x64. MPD is version 0.19.19. The stream is a aac via http from an icecast server. 

If this is indeed a bug (and not something I'm doing worng) and if it's possible I'd be willing to work on fixing this by myself, I'd just need some pointers to code places to get started.

**Comment by themasch** [comment]
Oh, a small addition: when I set the "Show popup messages when changing tracks" flag, the infomation is diplayed correctly, too.

**Comment by CDrummond** [comment]
This would be the MPRIS info. Sorry, I don't have KDE installed - so can't check with that. However, just checked and its working under GNOME shell for me - info is updated when song changes. This is with git/master - can you checkout and try this to see if it is also now working for you?

----------------

Also, if you store your streams in a playlist named `[Radio Streams]` then Cantata will list them under Streams/Favourites. The format in this file should be:

http://stream-url#Stream Name

e.g.

http://network.absoluteradio.co.uk/core/audio/mp3/live.pls?service=acbb&platform=tunein#Absolute Classic Rock

**Comment by themasch** [comment]
Okay, it works with git master. Thanks a lot!
Also, thanks for the hint, will use that!
