### ISSUE TITLE
Feature request: flag to transcode to lossy only if source is lossless

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1049]
In the device properties window there's alredy a flag that allows to not transcode files of the same format, but I think it would be useful to have another flag, to not transcode the source files to any lossy formats if they already are in any lossy format.
If I have some MP3 audio, I prefer to copy them as they are, instead of transcode them to, eg. OGG, because a lossy to lossy conversion will cause even further quality loss; but I'd like to convert my FLAC files to my portable device in OGG format to spare come space.

**Comment by CDrummond** [comment]
Should be easy enough - but will have to wait for 2.2, too late for 2.1

**Comment by CDrummond** [comment]
Done, for 2.2
