### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by Upperholme** [CDrummond/cantata#1050]
I can see that since the last release (v.2.0.1) there's been a lot of changes/improvements. I was wondering whether you have any plans to make a new release?

**Comment by CDrummond** [comment]
Yes - when the other issues are closed, and I get the time.

**Comment by CDrummond** [comment]
2,1.0 ha snow been released.

**Comment by Upperholme** [comment]
Blimey, that was quick! There was me, making a vague suggestion thinking that maybe you'd be in a position to do something in the third or fourth quarter, and before I know it you've gone and done it. Many thanks.
