### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by monetschemist** [CDrummond/cantata#1053]
Wow!  I am very very impressed with Cantata.  I installed it on Ubuntu 17.04 desktop to control a Cubox-i4 running Armbian and mpd, just to get an idea of how it compares to other mpd clients, and I must say, it is really well done.  Things I like very much, in no particular order:

- it's fast - if you blink while updating the mpd database you miss it;
- the Notes sprinkled around the UI are super-informative and make me wonder why I've never seen anyone else do this;
- the default organization album-by-artist pane and playlist pane is great, and the tree views in them are great;
- the icons by default on the leftmost pane to change the view are an excellent organizational device;
- thanks for including SoundCloud, let's hope it survives!
- the settings is well organized and again great to see those Notes.

In fact, Cantata is so well done I'm considering shifting my laptop to Cantata + MPD from its current configuration.

Two things that would be nice to have are 1) level meter and 2) indicator of bit rate or sample rate/word length.  But really these would be the sprinkles on the icing of a cake that is wonderful without them.

Thanks so much for such a great piece of work, CDrummond.  Very well done!

**Comment by CDrummond** [comment]
Thank you for kind comments - makes a pleasant change :-)

As to the two points; Cantata does not access the output stream, this is all played by MPD, so not really possible to have a level meter (not keeping it in sync, etc). The sample rate/word length are available on the song info page - the Lyrics column has a drop down allowing you to show all meta data of the track. Whilst it might be possible to add this to the toolbar (along side the track name, etc) - I think this would add to much visual clutter (and for something I have no need of).
