### ISSUE TITLE
Search in queue

### ISSUE THREAD

**Issue by Scrumplex** [CDrummond/cantata#1056]
I am using this mpd client for a while now and love it.
The only thing that I do not like is, that I can not search for a song in the queue.
At least I did not find any search box or hotkey.

**Comment by Scrumplex** [comment]
My bad! Found the hotkey in the settings. Anyway there should be a button or a menu item to search in the queue

**Comment by bb010g** [comment]
Like this?

![Hightlighted "Find in Play Queue | Ctrl-Shift-F" menu item](https://user-images.githubusercontent.com/340132/29090830-b4839a24-7c35-11e7-90d6-7f2230bec86f.png)

**Comment by Scrumplex** [comment]
Oh. I am sorry.
