### ISSUE TITLE
fatal error: QtMultimedia/QMediaPlayer: No such file or directory

### ISSUE THREAD

**Issue by deragon** [CDrummond/cantata#1057]
First time user, first compilation attempt, got:

```
Scanning dependencies of target cantata
[ 44%] Building CXX object CMakeFiles/cantata.dir/mpd-interface/httpstream.cpp.o
/<somedirectories>/software/nodist/x86_64/cantata/mpd-interface/httpstream.cpp:28:37: fatal error: QtMultimedia/QMediaPlayer: No such file or directory
compilation terminated.
```

Would be nice if that dependency would be part of the `cmake` process.  I have no clue what to do next.

**Comment by CDrummond** [comment]
Ah, this should now be fixed in master. The header was being included even though it was not being used. #1052 should fix this,
