### ISSUE TITLE
Podcast: Stops streaming podcast after pause

### ISSUE THREAD

**Issue by d7rk** [CDrummond/cantata#1058]
Hi Craig,

It is not possible to resume streaming a podcast once paused for some time. 
After pausing Cantata does remember the position and resumes playing, but soon stops after reading the buffered information and does not resume streaming the podcast.
Otherwise, thanks for the awesome work,

**Comment by CDrummond** [comment]
Cantata itself does not play anything - all the playback is handled by MPD. Cantata simply tells MPD the URL of the podcast, and sends it the play and pause commands. If playback is failing after pause, then this is either an issue with the stream or with MPD.
