### ISSUE TITLE
Podcast episodes with an ampersand in title don't appear in feed.

### ISSUE THREAD

**Issue by kentdobias** [CDrummond/cantata#1059]
The description says it all. Try subscribing to [Bullseye](https://www.npr.org/rss/podcast.php?id=510309), which has hundreds of episodes but only 16 appear in Cantata, since most episode titles contain '&'.

**Comment by CDrummond** [comment]
Which version of Cantata? I've just tried with git/master (which is basically 2.1.0) and all titles appear - currently 100

Could it be a locale issue? My locale is en_GB.UTF-8

**Comment by kentdobias** [comment]
Whoops, I was using the latest version in the Archlinux community repo, which was 2.0.1. Upgrading to the latest git release fixes the problem.
