### ISSUE TITLE
Media keys does not work in Cinnamon 

### ISSUE THREAD

**Issue by xhpohanka** [CDrummond/cantata#1060]
After switching to last version of Cantata media keys stopped to work for me in Cinnamon. Version 2.0.1 worked out of the box. 
I checked if I had not missed some build settings but it seems that there is no such configuration.

**Comment by CDrummond** [comment]
Don't use cinnamon, so I can't help. The only change to the media keys in 2.1.0 is to use the correct GNOME dbus name  `org.gnome.SettingsDaemon.MediaKeys` 2.0.1 used the older `org.gnome.SettingsDaemon`

Just checked with Ubuntu 17.04, and MediaKeys appear to work fine under GNOME.

Can you check the service name Cinnamon is using? Use qdbusviewer, in the left hand search field type `org.gnome.SettingsDaemon` Do you see `org.gnome.SettingsDaemon.MediaKeys` ? If not, then that is the issue.

Perhaps I should switch back, as both interfaces should still work. Please edit dbus/gnomemediakeys.cpp and change

```
static const char * constService = "org.gnome.SettingsDaemon.MediaKeys";
```

to 
```
static const char * constService = "org.gnome.SettingsDaemon";
```

And re-build. Does it now work OK?

**Comment by xhpohanka** [comment]
`org.gnome.SettingsDaemon` works...
Unfortunately I do not know what is standard here.

**Comment by CDrummond** [comment]
Can you checkout git/master and see if it now works? I've reverted the 2.1.0 change, so it should be as it was before.
