### ISSUE TITLE
Use en dash (–) instead of hyphen (-) between artist and album title

### ISSUE THREAD

**Issue by whtv** [CDrummond/cantata#1064]
… in the playlist and in the top widget/bar when playing back.
Would you consider this? I think it'd look much better, and it definitely seems more 'right' from a typographic perspective.

**Comment by CDrummond** [comment]
Done, for 2.2.0

**Comment by CDrummond** [comment]
Actually, I've reverted the commit. This had issues with some fonts. There is not a major difference.

**Comment by whtv** [comment]
That commit does output weird stuff instead of an en dash because the '–' is interpreted as a latin1 string. It works fine for me if I put it in the QString instead of the QLatin1String class.

**Comment by CDrummond** [comment]
...actually, that's a good point! I'll re-open and do it properly this time :-)

**Comment by CDrummond** [comment]
Done.
