### ISSUE TITLE
Build error message

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1067]
Please refer to the followings for the error messgae.
Changing from '>>' to '> >' in mpdconnection.cpp:265:42: resolve this issue.
###
[ 37%] Building CXX object CMakeFiles/cantata.dir/mpd-interface/mpdconnection.cpp.o
/home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/mpdconnection.cpp: In constructor ‘MPDConnection::MPDConnection()’:
/home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/mpdconnection.cpp:265:42: error: ‘>>’ should be ‘> >’ within a nested template argument list
     qRegisterMetaType<QMap<qint32, quint8>>("QMap<qint32, quint8>");
                                          ^
CMakeFiles/cantata.dir/build.make:3498: recipe for target 'CMakeFiles/cantata.dir/mpd-interface/mpdconnection.cpp.o' failed
make[2]: *** [CMakeFiles/cantata.dir/mpd-interface/mpdconnection.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CDrummond** [comment]
Fixed, sorry.
