### ISSUE TITLE
Add thanks badge to readme!

### ISSUE THREAD

**Issue by casey** [CDrummond/cantata#1068]
There is no obvious way to thank you for this amazing project, perhaps you should add a thanks badge to your readme?

https://saythanks.io/

Sadly I can't do this myself, since you need to create an inbox for yourself.

I really want to thank you for cantata. I've been trying to switch away from itunes to mpd, but just didn't find the various mpd graphical frontends to be that compelling. Cantata fits the bill perfectly. It looks great and grid view with album art is a really nice way to browse my library. I've been wanting to make the switch from macos to linux for a while, and cantata brings me that much closer to being able to do so. Now to find a laptop with a touchpad that doesn't suck under linux :P

**Comment by CDrummond** [comment]
Add to github README.md 

Not sure I'm 100% convinced of its usefulness, but doesn't hurt :-)
