### ISSUE TITLE
HTTP stream resume impossible 

### ISSUE THREAD

**Issue by DeX77** [CDrummond/cantata#1074]
Using the HTTP stream feature of a remote MPD instance Version `0.19.19` when I stop/pause in Cantata and try to resume later no sound will be played.
When I untick "Play Stream" and retick it Cantata will freeze and consume CPU time.
Killing and restarting it allows to reconnect to the still playing MPD instance.

EDIT: Cantata version 2.1.0

**Comment by CDrummond** [comment]
HTTP streaming is not a feature I use, and was not implemented by myself.

That being said, I have just tried and pausing works. When paused, MPD does not stop the stream, just outputs silence - so Cantata's stream playback just plays this silence. If this is not how your MPD is setup (not sure if this behaviour is configurable), then this could be why.

But, as stated - works for me.
