### ISSUE TITLE
Not enough toolbar height for the current album cover and progress bar

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1076]
Please refer to the following snapshot, I'm using the latest git under lubuntu 16.04

![2017-08-29-192944_940x503_scrot](https://user-images.githubusercontent.com/12131158/29816939-23699f80-8cf1-11e7-959e-a8699df0e544.png)

**Comment by CDrummond** [comment]
Should be fixed now, please update and confirm.

**Comment by parkmino** [comment]
Fixed and thanks!
