### ISSUE TITLE
Scrollbar Width for Touchscreens

### ISSUE THREAD

**Issue by hotwheelzffx2** [CDrummond/cantata#1081]
I have this installed on a RPI3 with a 15" ELO Touchscreen. I would like to see an option to increase the width of the scroll bar when in Library view so that users can scroll down.

**Comment by CDrummond** [comment]
The you would need to install a theme with wider scrollbars. Cantata is not designed for touch screens. You could probably do this using Qt's stylesheets. e.g. 

test.css:
```
QScrollBar:vertical { width: 32px; }
```

`cantata -style fusion -stylesheet test.css`

---

To be honest, with a rpi and a touch screen I think you'd be better of with logitech media server, squeezlite (a headless player), and jivelite (a touch screen UI). Have a look at piCorePlayer - this is a rpi image that runs in memory and has server, player, etc.
