### ISSUE TITLE
Look & feel on Arch (after latest update)

### ISSUE THREAD

**Issue by tarciosaraiva** [CDrummond/cantata#1083]
Hi guys
after the latest update - sometime last week - the look & feel on Arch is looking pretty weird.

![2017-09-12_1920x1080_scrot](https://user-images.githubusercontent.com/893428/30300260-1ad72c7e-9797-11e7-862e-fa1cb066cf5d.png)

All icons are at least double in size.

No loss in functionality.

**Comment by bb010g** [comment]
Is this on the last release, or master? If it's the latest release, try out cantata-git; there have been some high-DPI changes recently.

**Comment by tarciosaraiva** [comment]
Hey @bb010g thanks for the reply. It's on the latest release. Trying `cantata-git` and it fixed it. Hopefully those high-DPI changes will be fixed soon :)

Good work with Cantata BTW: simple and powerful. My fave music player by far.

Cheers
