### ISSUE TITLE
Removing songs from music folders results in improper loading of playlist

### ISSUE THREAD

**Issue by mleko69** [CDrummond/cantata#1087]
As in title: when I try to load a playlist with missing songs I get the information that says: 

> MPD: No such directory

And Cantata stops loading queue on the last non-removed song, ignoring the rest of playlist.

Interesting thing is that all removed songs have 0:00 length, as shown here:
![screenshot_20170930_125119](https://user-images.githubusercontent.com/22177132/31045302-ddbb6802-a5e0-11e7-9899-86eea2cab111.png)

Even simple highlighting of missing songs in playlist would be helpful in cleaning unwanted content from library.

Greetings, Patryk.

**Comment by CDrummond** [comment]
Playlist or play queue? Play queue is the *active* playlist. Anyway, this is MPD loading. If you have missing songs, cleanup your playlists.

Cantata does not really know they are missing - unless I checked every line each time. Not going to happen.
