### ISSUE TITLE
[mpd] empty database and Library

### ISSUE THREAD

**Issue by cinghiopinghio** [CDrummond/cantata#1088]
While I love `cantata` I'm not able to use it as a `mpd` client.

The problem:
If `mpd` is playing something, the Play Queue list the play queue as expected. Anyway the Library is always empty. Checking `~/.local/share/cantata/library/localhost_6600.sql` is always empty. If I delete it, at next restart I found another empty database.

I'm using arch linux with a local mpd started by systemd playing on port 6600. Other clients works as expected.

If I tell `cantata` to refresh the `mpd` database I receive the following error:
```
MPD reported the following error: No such directory
```

Any idea?

**Comment by CDrummond** [comment]
No idea. Cantata is working fine for me. Sorry, but I do not have time to debug all various setups.
