### ISSUE TITLE
Turn off annoying notification: MPD reported the following error: No such directory

### ISSUE THREAD

**Issue by perfect7gentleman** [CDrummond/cantata#1090]
Is it possible to turn off that notification?
it is so annoying.

**Comment by CDrummond** [comment]
Fix you MPD setup? I'm 99.999% sure this is because your playlist directory is not configured correctly.

Anyway, the error message is coming from MPD - so not a Cantata issue.

**Comment by perfect7gentleman** [comment]
yep, I understand that the error message is coming from MPD, but it appears in Cantata.

**Comment by CDrummond** [comment]
And, as stated, fix **your** MPD setup. I cannot suppress all error messages, even with this one I'm not sure if MPD is internationalised or not - if it is then string matching would not always work.

The error is with **your** setup.
