### ISSUE TITLE
Make double-clicking an item in the artist view replace play queue (feature request)

### ISSUE THREAD

**Issue by jarle** [CDrummond/cantata#1091]
(This might be applicable to other views too.)

I think it would be a neat feature to be able to double-click items in the artist view and have that item replace the play queue. It would be the same functionality that is implemented in the button `Replace The Play Queue`, meaning that this button could possibly be replaced with double-click to clear up some UI space/decrease the number of choices to click.

I don't know about others, but double-clicking items like this is already intuitive to me; I think it is a common pattern in most music players I've used.

**Comment by CDrummond** [comment]
On some systems, and some Linux themes, double click 'activates' the item - i.e. on an album this then shows the tracks.

To be honest, I like the way it currently works. Feel free to create a patch or pull request though.
