### ISSUE TITLE
[feature request] add option to choose image size in album and artist views

### ISSUE THREAD

**Issue by stef34280** [CDrummond/cantata#1092]
First of all thank you for the great job you have done.
Cantata is certainly the best mpd client out there.

Like i said in the title, it would be nice to choose the size of images in artist and album views

I run cantata on a small netbook and it displays 9 small images per line.
I'd like it to display 5 or 6 bigger images instead.

Thanks in advance if this is possible
btw, french translation is not complete, some items are still in english, if i can help for this, just tell me what to do.

Cheers from France 

Stéphane

**Comment by CDrummond** [comment]
In master (for 2.2.1) you can scale covers via Ctrl+ and Ctrl-

These shortcuts are not configurable, as I can't make string changes for 2.2.x

**Comment by stef34280** [comment]
Thanks for the answer.
I'll try to build 2.2.1 (now using 2.2.0 from PPA)

I will send you back cantata_fr.ts when I'm done.
