### ISSUE TITLE
Full date support?

### ISSUE THREAD

**Issue by elcste** [CDrummond/cantata#1093]
I have seen more and more music files with a full date tag instead of just the year. At least with the single-user MPD setup, Cantata seems to support the year only. Would it be possible to support the whole date?

(I'm using Canata 2.1.0 from Ubuntu 17.10.)

**Comment by CDrummond** [comment]
Possible, but more work than I have time for. Cantata's tag editor is pretty basic. As for adding full date to dynamic/smart playlists - just not worth the hassle.

**Comment by elcste** [comment]
Fair enough. Keep up the good work!
