### ISSUE TITLE
2.2.0: Only use menubar for macOS builds

### ISSUE THREAD

**Issue by thelounge-zz** [CDrummond/cantata#1095]
why is the menu completly gone under KDE? i don't like that single-qebpage-style at all and since i need to close canntata from the menu another thing to train new -  because which the X most of the UI is destroyed but not finally closing and that even blocks KDE logout until CTRL+ALT+ESC and kill the window fragment

ksystraycmd cantata - without the complete UI disappears but it's not really closed (simple to provide by start it from a konsole that you don't see a UI but need to CTRL+C to close the application finally)

Fedora 26 build:

Summary:           Client for the Music Player Daemon
Name:              cantata
Version:           2.2.0
Release:           2%{?dist}
License:           GPLv2+
URL:               https://www.linux-apps.com/p/1126635/
Source0:           %{name}-%{version}.tar.bz2
Source1:           lyrics_rhsoft.xml
BuildRequires:     gettext
BuildRequires:     qt5-qtwebkit-devel
BuildRequires:     qt5-qtsvg-devel
BuildRequires:     qt5-qttools-devel

%description
Cantata is a client for the music player daemon (MPD)

%prep
%setup -q
rm -rfv qtsingleapplication/

%build
export CFLAGS="%{optflags} -Os -fPIE -fuse-ld=gold -fuse-linker-plugin"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -pie $CFLAGS"
export QTDIR="/usr/lib64/qt5"
export PATH="$QTDIR/bin:$PATH"
mkdir -p %{_target_platform}
pushd %{_target_platform}
cmake \
 -DCMAKE_INSTALL_PREFIX="%{_prefix}" \
 -DENABLE_DEVICES_SUPPORT:BOOL=OFF \
 -DENABLE_HTTP_SERVER:BOOL=OFF \
 -DENABLE_HTTP_STREAM_PLAYBACK:BOOL=OFF \
 -DENABLE_KWALLET:BOOL=OFF \
 -DENABLE_PROXY_CONFIG:BOOL=OFF \
 -DENABLE_REMOTE_DEVICES:BOOL=OFF \
 -DENABLE_SIMPLE_MPD_SUPPORT:BOOL=OFF \
 -DENABLE_TAGLIB:BOOL=OFF \
 -DENABLE_UDISKS2:BOOL=OFF \
 ..
popd
%{__make} %{?_smp_mflags} -C %{_target_platform}

%install
make install/strip DESTDIR=%{buildroot} -C %{_target_platform}
install -m 0644 %{SOURCE1} %{buildroot}/%{_datarootdir}/%{name}/config/
exit 0

%files
%exclude %{_datarootdir}/%{name}/mpd/
%{_bindir}/%{name}
%{_datarootdir}/applications/%{name}.desktop
%{_datarootdir}/icons/hicolor/*/*/*
%{_datarootdir}/%{name}/*

**Comment by CDrummond** [comment]
The **only** change in your scenario is that File>Quit is changed to MenuButton>Quit The rest of your rant, **WTF????**

**Comment by thelounge-zz** [comment]
yeah on a 30" screen it's a pleasue when you have to move the complete screen right while any other application has a menu on the left side

th eother rant: i foun dit out - when "minimize to tray" is enabled but built without KDE support (only QT) that option does not work as desigend and in case the application is already startet tray-minimized it ends in a split brain blocking even logout - so you should ignore that option if the code for it was never compiled and i am pretty sure it was ignored some releases ago

interesting that you call describing problems as "rant"

**Comment by pouar** [comment]
I ended up just patching the code in order to show the menubar, as it was only hidden behind a macro

**Comment by ptitgnu** [comment]
@pouar Can you share your patch ? I'd also like to fix this issue in overlay ebuild (gentoo) and aur package (arch) of cantata for all users disappointed by this feature removal...

**Comment by pouar** [comment]
https://gist.github.com/pouar/23b80cf7ef21b25c92b931da5f677e14

**Comment by pouar** [comment]
This patch basically enables both the old and the new menu
