### ISSUE TITLE
StoredPlaylists

### ISSUE THREAD

**Issue by txhammer68** [CDrummond/cantata#1096]
Strange request, lost my music hard drive over the weekend, but was able to restore from backup
however, i lost my custom playlists which where in a folder called playlists...Cantana still "sees" them, but will not play them, is there a way to retrieve these stored play lists from Cantana or the mpd database?
many of these playlist are several hundred songs...
![screenshot_20171011_020459](https://user-images.githubusercontent.com/9554887/31426398-d386ede8-ae28-11e7-8514-77b22ab49689.png)
also may not bee able to play due to mount points changes...

Thanks

Matt

**Comment by CDrummond** [comment]
The playlists are stored by MPD - Cantata just asks MPD for this list of playlists. Where they are on disk depends on your MPD setup.

If this is a system-wide MPD instance (i.e. not Cantata's *basic* mode) then you need to look at /etc/mpd.conf - and the playlist location will be in there.

If you are using Cantata's *basic* mode (where Cantata starts its own local MPD instance) then playlists will be in `~/.local/share/cantata/mpd/playlists` (I think)
