### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by estshorter** [CDrummond/cantata#1097]
I use cantata in Japanese environment on Windows 10 and found that font is not beautiful in some view.
![cantata](https://user-images.githubusercontent.com/1430311/31529508-af58bcce-b014-11e7-8922-edea306c5cfc.PNG)
Font in the library view is OK, but those in the play-queue view and information over the seek bar is poor.

Would you please add the ability to change fonts, or would you change the poor one to good one?

**Comment by CDrummond** [comment]
Cantata does not explicitly set **any** text font. (The **only** font it ever sets is font-awesome for the mono icons). Not sure why the list on the left has a different font - I'll see if the icon code is affecting this. As to the other font, this is an issue on your system - as stated I don't set a font.

Sorry, but I'm not going to add code to select the font - as this would just be a workaround for your system.

**Comment by estshorter** [comment]
OK.

I used the fusion style to check whether style-setting affects font.
As a result, it does not; font is weird in any style.

**Comment by CDrummond** [comment]
Can you try changing: a) Cantata to use an Latin based locale, and b) your system to a Latin locale? Not sure if these would affect things, but whenever I've run under Windows it would have been with an English language setting. Just trying to eliminate the obvious differences.

**Comment by estshorter** [comment]
I tested, but both cases does not have the impact on the problem.
