### ISSUE TITLE
Transcode only if source type is flac/wav does not work

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1106]
I tried with mp3 files as source and ogg as device destination. Both "transcode if source is different" and "transcode if source is flac/wav" are set, but cantata will transcode the files to ogg on the destination device. What I expect is that mp3 and ogg files are copied, while only flac and wav are transcoded.

**Comment by CDrummond** [comment]
Actually it does work - just that the file extension is being changed when it need not be. Fixed now.
