### ISSUE TITLE
Interface improvement in transcoding options

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1107]
I think it would be clearer to move the flags "Only transcode if source file is of a different format" and "Only transcode if source is FLAC/WAV" into a radio button selection or button menu with thee options:
- Always transcode
- Transcode if source is of a different format
- Transcode if source is FLAC/WAV

**Comment by CDrummond** [comment]
I used a combo for this instead.

**Comment by Tichy** [comment]
Thanks. Much better and less confusing now.
