### ISSUE TITLE
Font is truncated due to narrow height in library view

### ISSUE THREAD

**Issue by estshorter** [CDrummond/cantata#1109]
Tall characters like 'y', 'p' and 'g' including some Japanese characters are truncated as shown in the screenshot.
I surrounded those by the red boxes in the picture: "Deep Purple" and "Family Song".

I haven't changed default font.

Cantata 2.2 on Windows10 in Japanese environment
![artist2](https://user-images.githubusercontent.com/1430311/31922924-cd7c7550-b8b2-11e7-93fa-a591dc8620f9.png)
![yg2](https://user-images.githubusercontent.com/1430311/31922925-d02f5d12-b8b2-11e7-89da-f64cfa9f2b63.png)

**Comment by CDrummond** [comment]
This looks very much related to your previous issue. I will look into both of these the next time I boot into Windows.

However, I see no such issues under Linux (which is my main OS, and the main target for Cantata). 

Please don't open further font related Windows issues - just add them to one of the existing reports (unless I have closed them)

**Comment by estshorter** [comment]
I got it.
I'm sorry for bothering you.

**Comment by CDrummond** [comment]
No, you're not bothering me. And this is a slightly different issue.

It's just that Windows is not a priority for me - hence I haven't got round to doing anything yet. Sorry.

**Comment by CDrummond** [comment]
I manged to recreate the issue, not 100% sure why it was happening. I saw mixed font size - one font was way too small. I also observed this in QtCreator - which leads me to believe its a Qt issue. Anyway, I've implemented a workaround.

Can you please try: [Cantata-2.2.1-Setup.zip](https://www.expirebox.com/download/71b1f94288a847a3f183d24acd575ab6.html)

NOTE: This link will only last 48hrs. Also, its labelled 2.2.1 - but there will be no 2.2.1 release, the next will be 2.3.0

**Comment by estshorter** [comment]
I confirmed the fix. Perfect!
Thank you so much.
