### ISSUE TITLE
Dirble has no entries

### ISSUE THREAD

**Issue by FMuro** [CDrummond/cantata#1111]
The title is self-explanatory. There are 0 Entry(s) in Dirble. It's totally empty. Cantata 2.1.0 in Kubuntu Artful.

**Comment by CDrummond** [comment]
Just tried git/master (which will be 2.3.0 - but there have been no dirble changes for a while) and both listing and searching on Dirble works just fine.

If you run Cantata from a commandline as follows:

`CANTATA_DEBUG=-0x00001000 cantata`

Then Cantata will output network related debug messages. This will show the communication between Cantata and Dirble. e.g.

```
NetworkAccessManager get "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" true
NetworkJob NetworkJob 0x55994760fae0 0x5599471d8770
NetworkJob handleReadyRead 0x55994760fae0 0x5599471d8770
NetworkJob jobFinished 0x55994760fae0 0x5599471d8770
NetworkJob jobFinished "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" QNetworkReply::NetworkError(NoError) "OK"
NetworkJob ~NetworkJob 0x55994760fae0 0x5599471d8770
NetworkJob cancelJob 0x55994760fae0 0x5599471d8770
NetworkAccessManager get "http://api.dirble.com/v2/category/71/stations?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" true
NetworkJob NetworkJob 0x5599471c49f0 0x5599476123c0
NetworkJob handleReadyRead 0x5599471c49f0 0x5599476123c0
NetworkJob handleReadyRead 0x5599471c49f0 0x5599476123c0
NetworkJob jobFinished 0x5599471c49f0 0x5599476123c0
NetworkJob jobFinished "http://api.dirble.com/v2/category/71/stations?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" QNetworkReply::NetworkError(NoError) "OK"
NetworkJob ~NetworkJob 0x5599471c49f0 0x5599476123c0
NetworkJob cancelJob 0x5599471c49f0 0x5599476123c0
NetworkAccessManager get "http://opml.radiotime.com/Search.ashx?query=Rock&locale=en_GB" true
NetworkJob NetworkJob 0x559947553e00 0x7fccec023d60
NetworkAccessManager get "http://api.shoutcast.com/legacy/genrelist?k=fa1669MuiRPorUBw&search=Rock&limit=100" true
NetworkJob NetworkJob 0x5599466deb50 0x559947553e30
NetworkAccessManager get "http://api.dirble.com/v2/search/Rock?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" true
NetworkJob NetworkJob 0x559947556960 0x5599475419c0
NetworkJob handleReadyRead 0x5599466deb50 0x559947553e30
NetworkJob handleReadyRead 0x5599466deb50 0x559947553e30
NetworkJob handleReadyRead 0x5599466deb50 0x559947553e30
NetworkJob handleReadyRead 0x5599466deb50 0x559947553e30
NetworkJob handleReadyRead 0x5599466deb50 0x559947553e30
NetworkJob jobFinished 0x5599466deb50 0x559947553e30
NetworkJob jobFinished "http://api.shoutcast.com/legacy/genrelist?k=fa1669MuiRPorUBw&search=Rock&limit=100" QNetworkReply::NetworkError(NoError) "OK"
```

**Comment by FMuro** [comment]
I get this:

`NetworkAccessManager get "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" true
NetworkJob NetworkJob 0x55d11b0e7ba0 0x55d11b0b4c90
NetworkJob handleReadyRead 0x55d11b0e7ba0 0x55d11b0b4c90
NetworkJob jobFinished 0x55d11b0e7ba0 0x55d11b0b4c90
NetworkJob jobFinished "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" QNetworkReply::NetworkError(NoError) "OK"
NetworkJob ~NetworkJob 0x55d11b0e7ba0 0x55d11b0b4c90
NetworkJob cancelJob 0x55d11b0e7ba0 0x55d11b0b4c90`

**Comment by FMuro** [comment]
Ehhh... it seems to be working now. I swear it wasn't before, and I don't know what I have done. I don't thing it has updated. Well, I'll try to test more and come back it I can reproduce again a failure with Drible.

**Comment by CDrummond** [comment]
Perhaps the Dirble services were offline when you initially had the issues?
