### ISSUE TITLE
Dinamically generated lists not working anymore.

### ISSUE THREAD

**Issue by Aqa-Ib** [CDrummond/cantata#1113]
Hello. I am using Cantata in Debian Unstable  and the dynamic playlists are not working. I have got the package liburi-perl installed into my system. Cantata does not give output when executed from the terminal, I try to start a dynamic playlist and no output at all. In one ocassion it threw this message "QProcess: Destroyed while process ("/usr/share/cantata/scripts/cantata-dynamic") is still running."

My cantata version is 2.1.0.ds1-1 from the Debian unstable repository.
If you wish I can give more information or I could try something that you can think.
Thank you very much.
Regards, Aqa-Ib.

**Comment by CDrummond** [comment]
I have just checked git/master on Ubuntu - and dynamic playlists **do** work. I guess you have a missing perl dependency. I'm no perl expert - this is the largest script I've ever written.

AFAIK, the list of required dependencies is:

```
vars.pm
IO/Socket/UNIX.pm
warnings.pm
IO/Handle.pm
Socket.pm
POSIX.pm
Encode/Alias.pm
threads/shared.pm
bytes.pm
Errno.pm
Carp.pm
attributes.pm
SelectSaver.pm
List/Util.pm
Config.pm
threads.pm
overloading.pm
XSLoader.pm
IO/Socket/INET.pm
constant.pm
File/Basename.pm
warnings/register.pm
strict.pm
Encode/Encoding.pm
File/stat.pm
Class/Struct.pm
Exporter/Heavy.pm
Scalar/Util.pm
overload.pm
URI/Escape.pm
Tie/Hash.pm
Exporter.pm
IO/Socket.pm
Symbol.pm
Encode/Config.pm
IO.pm
Encode.pm
Cwd.pm
Fcntl.pm
```
