### ISSUE TITLE
Save current playlist

### ISSUE THREAD

**Issue by majkinetor** [CDrummond/cantata#1116]
It would be great if Cantata could save the currently loaded playlist. Currently it offers only save as which requires me to know the exact name of the playlist and enter it each time. 

So, if I load the playlist and add few new records to it, it should be possible to just ctrl + s it or something equivalent.

**Comment by CDrummond** [comment]
Sorry, no. Once the playlist is loaded it is not linked anymore - neither Cantata nor MPD know which playlist the playqueue is related to. MPD simply loads all the tracks into the queue.

However, what I can do is make the 'Save As' context menu action into a menu, e.g.

```
Save As >
    New playlist
    Existing playlist A
    Another existing playlist
```

**Comment by majkinetor** [comment]
> Sorry, no. Once the playlist is loaded it is not linked anymore 

Cantata can remember the last playlist loaded tho, so this is not related to mpd features. Playlists have specific file extension. 

> However, what I can do is make the 'Save As' context menu action into a menu, e.g.

This is definitely better but still not practical. It may work well for 5 playlists but once you have more then 10-20 you need to hunt for the list in the contextmenu in which case its simply faster to save as it and keep its name on the clipboard.

**Comment by majkinetor** [comment]
Sure. Thanks.
