### ISSUE TITLE
Mpris2 interface:  mpris:length overflow when the song is too long 

### ISSUE THREAD

**Issue by audoban** [CDrummond/cantata#1119]
Hello regards

When a song is too long the property mpris: length overflows, this problem makes the Mpris2 clients unable to calculate the remaining time.

Steps to reproduce:
1. play a song that lasts more than one hour
2. read property mpris:length

This is the output I got using the qdbusviewer-qt5 tool
note that the value of the mpris:length is negative
```
{"mpris:artUrl" = [Variant(QString): "file:///usr/share/icons/breeze/devices/64/media-optical.svg"]
, "mpris:length" = [Variant(qlonglong): -269967296]
, "mpris:trackid" = [Variant(QString): "/org/mpris/MediaPlayer2/Track/5"]
, "xesam:album" = [Variant(QString): "Desconocido"]
, "xesam:artist" = [Variant(QStringList): {"Desconocido"}]
, "xesam:genre" = [Variant(QStringList): {"Desconocido"}]
, "xesam:title" = [Variant(QString): "Gintama OP 1-17 Full-0PfnhGVPFLM"]
, "xesam:url" = [Variant(QString): "file:///home/_audoban/Music/Gintama OP 1-17 Full-0PfnhGVPFLM.ogg"]}]]
```

**Comment by CDrummond** [comment]
This now seems to be fixed for me. Tried with a track that was 90mins long. Can you checkout git/master and confirm?

**Comment by audoban** [comment]
I will check the master soon

**Comment by audoban** [comment]
It works perfectly, thank you very much.
