### ISSUE TITLE
Display more file information (bitrate, encoder/container,genre,...)

### ISSUE THREAD

**Issue by Utini2000** [CDrummond/cantata#1120]
Hey there,
I wonder if it would be possible to somehow view some more file informartion in the columns (together with artist,album,year,song length) or in the lowest bar (together with total track number, total playtime / song lengths and genre drop-down) ?

I have a lot of songs in my library that are there multiple times but in different formats (flac,mp3 320, mp3 v0,...). I would love to easily/quickly see which of those three files I am currently playing. Also in general I think that information like genre, bitrate and container/encoder should be visible.

Thanks in advance !

**Comment by CDrummond** [comment]
You can already see this information in the song info view. In the right most plane you can switch between lyrics, song info, and meta-data. The meta-data shows bitrate, etc.

I've added a new config option to show technical info in the toolbar. This will show bitrate, sample rate, and file extension. (Don't know of anyway to get the actual format of the track, hence using the file extension)

Genre is not visible in the toolbar, and will never be (would be too crowded). However, if you use table-view for the playqueue you can then show genre. You need to use the context menu in the table's headers to show the genre column,

**Comment by Utini2000** [comment]
@CDrummond ahh thanks. 

The "Metadata" option was kinda hidden :) I kept looking and looking but couldn't find it. Even with your description it wasn't easy to find.

The new option to view some of the metadata (show bitrate, sample rate, and file extension) in the toolbar is awesome ! I guess it will be available with the next update?

How about adding the "genre" to the "grouped album" style? Maybe per album instead of each song?
