### ISSUE TITLE
Global hotkeys on macOS

### ISSUE THREAD

**Issue by pztrn** [CDrummond/cantata#1123]
How to setup global hotkeys on macOS? Hotkeys defined in settings aren't global.

**Comment by CDrummond** [comment]
You cannot configure global hotkey on **any** Cantata 2.x build. The **only** global keys that work are the media keys. These work under Linux, and did the last time that I tested on macOS (which was a while ago)

Sorry, but macOS is not a priority for me - not an OS I use. Cantata's main OS is Linux - the windows/mac ports were just for fun, to see how easy it would be.
