### ISSUE TITLE
touchscreen scrolling broke

### ISSUE THREAD

**Issue by molecular** [CDrummond/cantata#1126]
(I have version 2.1.0-1 as provided by arch linux)

I have a touchscreen and with recent update of my archlinux, being able to scroll the libarary list and play queue list isn't possible any more. Before I could use the touchscreen to scroll the views by touching and sliding (like on a phone). Now the element below the touchpoint is selected and drag & drop activated.

I'm not even sure this is cantata-related, but I think so.

Is there a setting somewhere to re-enable this behaviour?

**Comment by molecular** [comment]
I played with the following settings:

  * touchFriendly
  * contextAutoScroll
  * forceSingleClick
  * playQueueScroll

nothing helped ;|

**Comment by molecular** [comment]
Just noticed using 2 fingers works, but it's very unreliable and goes into "drag & drop" mode accidentally a lot. It seems my 2 fingers need to hit the surface at pretty much exactly the same time. It's not as good as being able to just use the thumb (I have a "convertible", so it's like a pad when I'm on the sofa listening to music)

**Comment by CDrummond** [comment]
No longer supported, it never worked properly for me.
