### ISSUE TITLE
macOS 10.13 advanced config

### ISSUE THREAD

**Issue by cavemandaveman** [CDrummond/cantata#1127]
I manually created the config for changing the volume steps at `~/.config/cantata/cantata.conf`, but it looks like Cantata doesn't pick up the config.

```
[General]
volumeStep=1
```

The README only mentions advanced config for Linux, but I figured I'd try it. Turns out it doesn't work. Not sure if it's just my machine or if this capability just wasn't built out for macOS.

**Comment by padertux** [comment]
Settings are stored in a differnet location under macOS. Maybe the following thread does help you:
https://stackoverflow.com/questions/13624677/where-do-apps-developed-using-qt-saved-its-settings-when-using-qtsettings-in-mac

**Comment by CDrummond** [comment]
For Cantata 2.3.0, there will be **no** advanced config items. I've added a GUI setting for volume step, and added commandline options for the reset.
