### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by peterLaurence** [CDrummond/cantata#1128]
Hi,

My setup is Cantata 2.2.0, Ubuntu 16.04.
I noticed that the memory usage starts at around ~60Mb, and raises to ~90Mb after some music playing. I tried to clear the cache of cd covers in the preferences, and scrolling down my library (thus forcing Cantata to reprocess cd covers), memory usage reached ~400Mb.
What worries me is that is never goes down, like if it was a memory leak. Is it normal?

**Comment by CDrummond** [comment]
I tried to recreate this, and managed to use 700Mb! When cantata loads covers it adds them to a cache - to save constantly reading from disk. When an entry is added to this cache, its supposed to be added with a 'cost' - then the cache will remove older items if this cost is exceeded. Looking at the code, there were 2 areas where this cost was not set correctly - which I have now changed.

Any chance you can checkout git/master - and see if this helps with your issue?

**Comment by peterLaurence** [comment]
I would be happy to do that.
This is the first time i try to compile Cantata from sources, and i get this error after `cmake ..`

```
CMake Error at CMakeLists.txt:224 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
```
I do have Qt5 installed, but i'm not a qt/c++ developer (i'm a java/android)
But i don't want to bother you with this. Unless its simple to fix this compile error, i will wait your next release.

**Comment by CDrummond** [comment]
You need to have the Qt5 development packages installed in order to compile.

**Comment by peterLaurence** [comment]
Ok is compiling now.

**Comment by peterLaurence** [comment]
So this is definitely better now. Cantata uses now 135Mb at most (with my configuration).
Is it me or the memory footprint was smaller in previous releases?

It starts at 27Mb, and it looks like some playlist have some "high" memory cost (like 80Mb). Sometimes the memory taken is not freed when i switch to another playlist, so memory footprint stays above 120Mb. But this is just my use point of view.

**Comment by CDrummond** [comment]
Your main issue is fixed. As to the higher mem usage, I'm 99.99% sure this is due to the undo stack keeping track of old playqueues - at least it appears to be in my quick checks. So, closing for now.

**Comment by peterLaurence** [comment]
Thanks!
