### ISSUE TITLE
Sql executed too early

### ISSUE THREAD

**Issue by ial0** [CDrummond/cantata#1130]
https://github.com/CDrummond/cantata/blob/948026d73bad42885663ca23f1c480f8616c0e47/db/librarydb.cpp#L456

This constructor executes `sql` before any values are bound. This caused a segfault in the QVariant copy constructor.

After substituting below, no segfaults so far. 
```
query = QSqlQuery(db); 
query.prepare(sql);

```

**Comment by CDrummond** [comment]
Odd, I get no crashes. Anyhow, your change is harmless enough and does not seem to have any negative effect - so I have applied. Thanks.

**Comment by shumski** [comment]
The crash is occurring with Qt > 5.10.x, probably you're using 5.9 or older hence no crashes.

**Comment by CDrummond** [comment]
Well, then its really a Qt bug - as the behaviour should not change. Still, as I said, no harm to the change.

**Comment by ff2000** [comment]
Just had this issue and was happy to find out it was fixed already a month ago :)

RE qtsql bug: sqlite doesn't support prepared queries. The QSqlQuery-doc clearly states (and always did), that when passing a non-empty query string it will get executed. Makes no sense for prepared queries, of course.
The issue: There seem to be no naming restrictions for sqlite, naming a column ":name" or "?" (which are the placeholders supported for bound values in qtsql) is just fine as long as you put them in square brackets or double quotation marks.

```
sqlite> CREATE TABLE test (":id", ":name", "?");
sqlite>
```
(no error here).
I can imagine (didn't search for bug reports) that people occasionally had unexpected behaviour when naming columns that way and using this QSqlQuery-constructor: it didn't get executed although the documentation says it should. I think changing behaviour was the right decision and didn't conflict with documented behaviour.
