### ISSUE TITLE
Search for year in Library?

### ISSUE THREAD

**Issue by elcste** [CDrummond/cantata#1131]
As far as I can tell, the Library (and Play Queue) search field only searches the artist and album. I'd like to be able to search for the year too. I know I can search for the date in the Search (via MPD) view, but the results in the Library are much nicer since it's grouped by artist and album. Also, since the year is displayed (in parentheses) after the album name in the Library and Play Queue, it makes sense to for it to appear in the search results. Thanks for your consideration!

**Comment by CDrummond** [comment]
I've added special handling for the library and playqueue search fields. To search for a date enter #date or #from-to e.g.

#2015 Will search/filter for year 2015
#1980-1989 Would be from 1980 to 1989 (inclusive)
Blah #2000-2017 Would search for 'Blah' and filter from 2000 to 2017

**Comment by elcste** [comment]
Thanks! I just donated USD 25 to charity (American Refugee Committee) in gratitude.

The range option is a great idea. In other players I often searched for e.g. "artist 200" to get albums from 2000–2009, but being able to search an arbitrary range is even better.
