### ISSUE TITLE
Weird list in devices libraries.

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1136]
See screenshots
![screenshot_20171203_192046](https://user-images.githubusercontent.com/2348771/33528367-5f074a6a-d85f-11e7-9118-c7ae1b356d31.png)![screenshot_20171203_170650](https://user-images.githubusercontent.com/2348771/33528366-5edb906e-d85f-11e7-87f8-cfe8de9f4ca3.png)

**Comment by CDrummond** [comment]
This should now be fixed. Can you please update and confirm?

**Comment by Tichy** [comment]
I confirm. Now is fixed. Thanks.
