### ISSUE TITLE
Weird window size when starting up cantata on Windows

### ISSUE THREAD

**Issue by estshorter** [CDrummond/cantata#1137]
After the following procedure, window size of cantata is not maximized when starting up; it's too small.

1) Start up cantata 
2) Maximize the window of cantata
3) Close & restart cantata

Screenshot after restart:
![default](https://user-images.githubusercontent.com/1430311/33536510-d0b95f56-d8f8-11e7-8402-a963d42f626f.PNG)

cantata v 2.2.0 on Windows 10 (1709)

**Comment by CDrummond** [comment]
Just tried in Windows 10 - and it's working fine for me.

**Comment by estshorter** [comment]
OK.
This might occur only in my environment.

Would you tell me how to initialize cantata's setting?
It might resolve the issue, but I couldn't find the setting file.

**Comment by CDrummond** [comment]
I use Qt's QSettings class - I assume for windows that it stores it in the registry.

When Cantata is maximised when its closed, it stores the size as -1,-1 When Cantata starts, if the stored size is -1,-1 then it should set the window to be maximised. And this is what I see.

**Comment by estshorter** [comment]
Thank you for the information.
Finally, I could reproduce the bug.

When "Info" appears in the sidebar as shown in the following screenshot, the window is not maximized correctly at startup.

![capture](https://user-images.githubusercontent.com/1430311/34107450-990dc27a-e43f-11e7-9389-dd0a33a4d398.PNG)

cantata v 2.2.0 on Windows 8.1

**Comment by CDrummond** [comment]
Thank you for that invaluable piece of information. I have now recreated, and fixed the issue. Fix will be in 2.3.0
