### ISSUE TITLE
Feature request - another field for track specific info

### ISSUE THREAD

**Issue by vivasteve** [CDrummond/cantata#1138]
a humble request to the mighty cantata devs
(someday) it would be nice to have another track information field (or two)
to record for example, who's playing the horn on that track
cantata is great

**Comment by CDrummond** [comment]
Cantata gets all its song info from MPD - and (AFAIK) MPD does not store this info, although you can ask it to read extra info per track (but this would be slow).

So, sorry not something I am interested in implementing. However, feel free to create a pull requeset.
