### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bgerazov** [CDrummond/cantata#1139]
First let me say - awesome work guys! Definitely the best player out there!
I have ripped a lot of files from audio cassettes and they have the title in the filename and no metadata. Can you add a filename (and maybe path?) column to the playlist so I can now which song it is.
Thanks and keep up the good work!

**Comment by CDrummond** [comment]
Implemented for 2.3.0

**Comment by bgerazov** [comment]
Ok thanks guys!!
