### ISSUE TITLE
Advanced search for any tag in library/search view

### ISSUE THREAD

**Issue by tillschaefer** [CDrummond/cantata#1140]
It would be nice to have a feature to search for any tag content in the library. In Amarok this is solved by typing `tag: search term`. 

This request is somehow related to #1131, where search for the tag year should be possible. However, I would like to see a more general solution, than defining a special symbol to each tag. 

As a second step it would be nice to allow concatenation of searches with _and_ or _or_, e.g., `genre: ambient && year:2000`, `year: 2000  || year:2001` or `genre: ambient && (year:2000 || year:2001)`. 

Third, for numerical fields, durations, dates it would be nice to allow ranges like in #1131.

**Comment by CDrummond** [comment]
All string field are searched in the library view - at least all those that are cached. As for this advanced syntax, sorry too much work, for no real benefit. How likely is a user to perform some complex query like that? I have not time, not desire, to implement such a feature. However, feel free to create a pull request for this.

**Comment by tillschaefer** [comment]
HI, 
the complex part is just a second thought. However, would really like to see the first part (just simple `tag: search term` searches) of the proposal to be realized. 

Example use cases: I want to search an artist and do not want to find any track that is named the same. Or there is a track called 2000 and I only want to find this track and not all tracks from the year 2000. I have a very large collection and this is a common issue for me.

**Comment by CDrummond** [comment]
Then use MPD's search (the search tab). The library view searches a cached SQLite copy of MPDs db. Either way, not something I'm particularly interested in.

The string "2000" will only match text 2000, not year. Hence the need for #year - the year is stored as a number in Cantata's DB.

**Comment by tillschaefer** [comment]
Missed that feature to select the tag in search. Closing then.
