### ISSUE TITLE
Icon theme "cantata" not found

### ISSUE THREAD

**Issue by vanyasem** [CDrummond/cantata#1141]
Updated my Qt to 5.10 on Arch Linux with KDE Plasma 5.11.4

Cantata 2.2.0 crashes with an error:
```
Icon theme "cantata" not found.
Segmentation fault (core dumped)
```

Tried reinstalling from the repos, cleaning orphans in between. No luck

`/usr/share/cantata/fonts/fontawesome-webfont.ttf` is in place and seems okay

**Comment by padertux** [comment]
Did compile cantata against Qt5.10 and can not reproduce this. Can you provide a backtrace?

**Comment by vanyasem** [comment]
I have not rebuilt Cantata myself, I guess that might be an issue there. Will try doing so now

**Comment by vanyasem** [comment]
I built Cantata from source, and now it doesn't crash. But the error is present among with some new errors:
```
Icon theme "cantata" not found.
Failed to compute left/right minimum bearings for ""
Failed to compute left/right minimum bearings for ""
```

Icons are also missing:
![2017-12-15-081113_182x370_scrot](https://user-images.githubusercontent.com/13350458/34027749-9d71f1b0-e156-11e7-93fd-8af3425e6e42.png)

**Comment by vanyasem** [comment]
Here's a strace:
[strace.log](https://github.com/CDrummond/cantata/files/1561663/strace.log)

**Comment by vanyasem** [comment]
I built Cantata from source and can't reproduce this anymore. I guess it's an Arch packaging bug

**Comment by vanyasem** [comment]
I still get the error `Icon theme "cantata" not found.` though, but all icons are present

**Comment by CDrummond** [comment]
I've seen that warning before, not sure why. Cantata has its own 'icon' theme for the message box icons and the preference dialog icons. All are still shown, so for me its a non-issue.

**Comment by vanyasem** [comment]
The issue was that Cantata crashes on Arch Linux after an upgrade to Qt 5.10. And it still does. Recompiling from git fixes that problem, so not sure it it's not an Arch packaging bug

**Comment by CDrummond** [comment]
Seeing as re-compiling fixes the issue, I'm not sure what else you expect me todo. I don't release Linux binaries.

I'm guessing the actual issue is: #1130 - Which would explain why rebuilding from master resolves the issue.

**Comment by vanyasem** [comment]
Will report arch upstream then, thank you for a quick response
