### ISSUE TITLE
Cosmetic: global menu is present, even if there aren't menus.

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1147]
![screenshot_20171223_163327](https://user-images.githubusercontent.com/2348771/34320648-408d7a14-e7ff-11e7-9777-1a447ff6432c.png)

When the global menu in titlebar is enabled, it appears even if there are no menus anymore. Clicking on it, does nothing.

**Comment by CDrummond** [comment]
How is this a Cantata issue? Cantata does not create a menubar, and only sets menubar items for macOS. Looks like a KDE issue.

**Comment by Tichy** [comment]
In data sabato 23 dicembre 2017 18:03:53 CET, CraigD ha scritto:
> How is this a Cantata issue? Cantata does not create a menubar, and only
> sets menubar items for macOS. Looks like a KDE issue.

I thought that it's a Cantata issue because there's no menu icon in the 
titlebar witht other applications that does not have a menu or does not 
support the global menu. eg. spectacle, systemmonitor, cuttlefish

I don't know how your application works, but I imagined that maybe it could be 
that it "advertises" that it has a menu, but it does no populate it.

**Comment by CDrummond** [comment]
Don't use KDE, so can't check. However, I have just made a small hack to remove the menubar. Can you checkout git/master and see if this resolves the issue?

**Comment by Tichy** [comment]
In data domenica 24 dicembre 2017 16:01:07 CET, CraigD ha scritto:
> Don't use KDE, so can't check. However, I have just made a small hack to
> remove the menubar. Can you checkout git/master and see if this resolves
> the issue?

I just compiled with the last commits, but I still see the menu button in the 
titlebar.

**Comment by CDrummond** [comment]
Well, if deleting the menubar does not work - not sure what else can be expected. KDE issue.

**Comment by Thaodan** [comment]
shouldn't menus be shown when globalmenu is used like on OS X?
So that menubar are hidden (unless CTRL+M is pressed) and only shown when visible or globalmenu is used?

**Comment by Tichy** [comment]
@CDrummond I just checked again, and your commit seems to have solved the problem. I don't know why the menu button was still there when I checked the previous time... Maybe I had to restart kwin_x11 or clear some cache... Don't know
