### ISSUE TITLE
cantata-dynamic limited to IPv4

### ISSUE THREAD

**Issue by marschap** [CDrummond/cantata#1148]
Due to the use of `IO::Socket::INET`, `cantata-dynamic` is limited to IPv4 and fails without notice on a pure IPv6 connection.

The regular end-user does not know about the way cantata internally deals with playlists and wonders why the dynamic playlists he/she created do not work.

The issue can be quickly solved by replacing in cantata-dynamic all 3 occurrences of `IO::Socket::INET` with `IO::Socket::IP`

Thanks for cantata & thanks in advance for taking care of this issue
PEter

**Comment by CDrummond** [comment]
Script has been updated, thanks. Changes will be in 2.3.0 - which I'll release in the new year.
