### ISSUE TITLE
Cosmetic: scrollbar background with breeze theme

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1150]
With breeze theme, in some views the scrollbar background does not match with the view background: playlist view, and info panel.

![screenshot_20171224_113430](https://user-images.githubusercontent.com/2348771/34325879-27643f28-e89f-11e7-9a2b-e27a408fd702.png)

**Comment by CDrummond** [comment]
Don't have breeze theme here, don't use KDE and theme seems to want to pull in a lot of KDE dependencies.

However, Adwaita-Qt had similar issues - and I've now resolved these. Can you checkout git/master and confirm if this fixes breeze?

**Comment by Tichy** [comment]
In data domenica 24 dicembre 2017 16:02:08 CET, CraigD ha scritto:
> However, Adwaita-Qt had similar issues - and I've now resolved these. Can
> you checkout git/master and confirm if this fixes breeze?

Scrollbars are fine now. Thanks.

**Comment by CDrummond** [comment]
Thanks for the confirmation.
