### ISSUE TITLE
Not issue: using sshfs for almost year. no problems so far

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1151]
Just to inform that for almost the last year I always compiled Cantata on Arch Linux with -DENABLE_REMOTE_DEVICES=ON using sshfs to upload music to my SailfishOS device.

I don't know if others are testing or using sshfs, or smb. Anyway, in my experience, it looked very reliable and stable, and I was wondering why it's not enabled by default.

**Comment by CDrummond** [comment]
Must admit, its not a feature I have used for a long time. Anyhow, I've enabled this by default for 2.3.0
