### ISSUE TITLE
"Single Tracks" folder feature not working?

### ISSUE THREAD

**Issue by chrober** [CDrummond/cantata#1155]
I did not succeed to get the "Single Tracks" folder working which I have specified via the "Interface Settings" -> "Tweaks" settings dialog.
I tried to following variants:
- just the subfolder name ("_diverse")
- the folder hierarchy as shown in the folder view of Cantata (i.e. "NAS/music/_diverse")
- an absolute path (i.e. prefixed with the "Music folder" setting of the collection)

Whenever I changed this setting, I started the "Refresh Database" operation in Cantata. Unfortunately, I have never found a "Single Tracks" under "Various Artists" but the tracks contained in my "_diverse" folder still showed up under the respective artists.

I am observing this with the provided Windows build of Canata 2.2.0, as well as with a self-compiled Linux build (used only default options).

**Comment by CDrummond** [comment]
Just tried, under Linux, and it is working perfectly.

I have:

1. MPD music folder `/home/craig/Music`
2. Single tracks folder set to `abc`
3. Within `/home/craig/Music/abc` I've placed 3 MP3 files. All show under `Various Artists/Single Tracks`

The folder specified for single tracks needs to be the sub-folder **within** the MPD `music_directory`. To ascertain what this should be, locate a track in the `Library` view that you think should be in single tracks. Hover the mouse over this, and a tooltip should be shown (`Settings/Interface/General/Show song information tooltips` needs to be enabled).  The last line of this tooltip will be the MPD path to the song's file - e.g. `abc/01 Wibble.mp3` The folder part of this is what is needed to be set in Cantata's single tracks setting - in this case just `abc`

**Comment by chrober** [comment]
Hi Craig,

thank you for the quick reply and for your help. I finally succeeded to get the "Single Tracks" album within the Various Artists.However, I still see two issues now:

1. I got two "Single Tracks" albums under Various Artists (instead of just one). A couple of tracks in my "_diverse" folder came from a sampler album (i.e. their album artist tag says "Various Artists") an those tracks are now grouped as an additional "Single Tracks" album.

2. The actual "Single Tracks" album is listed "somewhere" among the other Various Artists albums. The albums are sorted chronologically, in my case the "Single Tracks" says 2004 (not sure, how the year is determined). => Maybe you want to treat the "Single Tracks" album deterministic by either placing it at the beginning or end of the Various Artists albums? By the way: I think it does not really make sense to deal with a release year for the "Single Tracks" album.

3. The "Single Tracks" feature does not recurese into sub-directories of the given folder, i.e. files residing in its subdirectories are still shown with the respective artists. Can you confirm this? Is there a way around it?

Best regards,
Christoph

**Comment by CDrummond** [comment]
The year I have already removed - noticed this after my initial test. As to the 2 'Single Tracks' entries - I'm guessing one or more of your songs has a music brainz album id set. This would cause a duplicate. This should now be fixed. Can you checkout git/master and confirm?

You are correct that the feature does not recurse. However, you can specify a comma separated list of folder names - so `abc, abc/def`

**Comment by chrober** [comment]
I've just tested with a Linux-build of the latest git/master sources and I can confirm the following:

1. The "Single Tracks" album is shown as the first "Various Artists" album (without year)
2. The second "Single Tracks" album in my collection is gone (you were right, I have all my music files tagged with MusicBrainz IDs)

Moreover, the comma-separated list of folder names works as well.

Thanks a lot, Craig!
I now just wonder what is the sort order of the "Single Tracks" album songs... can you please tell me.

**Comment by CDrummond** [comment]
I've updated the code to no longer display track number for single track files - as this does not make much sense here. The sort is then; track title, track artist

**Comment by chrober** [comment]
Well done! I just tested it again with your latest changes and it looks very good now!
Thank you very much!

**Comment by ExtremeSquared** [comment]
This seems to be non-functional in 2.3.1 as well. Tried Various, tried other folder names. Created simple lowercase test folder with test mp3 and "foo/bar" tags. Cannot seem to get this to trigger.

Maybe of note, Library "Group by" setting only shows Genre, Artist, Album. The goal of the "single tracks" tweak is should be similar to grouping by the "Album Artist" tag instead of the "Artist" tag.

**Comment by ExtremeSquared** [comment]
The flow needed to properly group poorly tagged files automatically would be
`A: Group by "Album Artist"
B: If blank "Album Artist" 2 Cases:
  1: Poorly tagged compilation with dissimilar "Artist" tags in same folder -->
     Group in special Various area
  2: Poorly tagged non-compilation with matching "Artist" tags in same folder -->
     Fall back to Album Artist = Artist`

This level of dealing with bad tags may be beyond the scope of cantata.
