### ISSUE TITLE
Some mistakes in the source translation

### ISSUE THREAD

**Issue by scootergrisen** [CDrummond/cantata#1157]
Found a few mistakes in the blank source translation that someone might want to look at and correct.

top - to
`Failed top open package file.`

Seatch - Search
`Seatch For Streams`

elect - select
`Cantata only shows a trimmed down version of wikipedia pages (no images, links, etc). This trimming is not always 100% accurate, which is why Cantata defaults to only showing the introduction. If you elect to show the full article, then there may be parsing errors. You will also need to remove any currently cached articles (using the 'Cache' page).`

prepend - does prepend not mean if something is placed in the beginning? Perhaps "then move this to the end..." would be better.
`If an artist name begins with 'The', then prepend this in the folder name. e.g. 'The Beatles' becomes 'Beatles, The'`

**Comment by CDrummond** [comment]
'elect' is correct - the others I've now fixed.

**Comment by scootergrisen** [comment]
Should this be removed?
`English (en)`

**Comment by CDrummond** [comment]
No. Translations are generated from the Cantata source code. Each string wrapped in `tr()` is marked as translatable.  `English (en)` would be translated as `Inglés (en)` in Spanish.

**Comment by scootergrisen** [comment]
Ok but it is not already translated in the list of languages?

**Comment by CDrummond** [comment]
I'm not sure what you are getting at, or why you are asking.

The .ts files are **generated** from the source code.The only way yo control what is in these, is to mark/unmark strings in the source code. As stated, the english string is a valid string to be translated. The Qt translation framework does not seem to group similar strings, but groups them according to the classes they are used in. Hence `English (en)` may appear more than once (I have no checked).

**Comment by scootergrisen** [comment]
Should "English (en)" then not be in english always?
Like the other languages in the language list are translated to their own language.
"dansk (da)" is in danish.
"polski (pl)" is in polish.

**Comment by scootergrisen** [comment]
There are a lot of strings with stuff like:
`Where the 'Album artist' is the same as 'Artist' and the 'Title' is of the format "TrackArtist - TrackTitle", 'Artist' will be taken from 'Title' and 'Title' itself will be set to just the title. e.g. `

`Revert "Various Artists" Workaround`

Where 'Album artist' and "Various Artists", etc. could be replaced with placeholders (%1, %2, ...).

That way translators don't have to translate 'Album artist' 20 times and make sure its translated the same in all strings.

**Comment by scootergrisen** [comment]
Should this:
`The artist of the album. For most albums, this will be the same as the <i>Track Artist.</i> For compilations, this will often be <i>Various Artists.</i>`

Be this:
`The artist of the album. For most albums, this will be the same as the <i>Track Artist</i>. For compilations, this will often be <i>Various Artists</i>.`

"." have been moved to after the ">" two places.

**Comment by CDrummond** [comment]
Technically speaking, yes. But an italic dot looks the same as a non italic one - so I'm not going to modify the translations just because of this!

**Comment by scootergrisen** [comment]
"send an update commands" should properly be "send an update command" or "send update commands"
`<p>Select this option if your MPD server detects modifications (e.g. newly added files) automatically. If so there is no need for Cantata to send an update commands for certain actions.</p>`

**Comment by scootergrisen** [comment]
Missing "." before "You" i think.
`If you have a lot of artists in your collection that only contain a single track, then it can be cumbersome for each of these to have their own entry in the list of artists. As a work-around for this, if you place these tracks into a separate folder, and enter this folder name below, then Cantata will group these under an album named 'Single Tracks' with an album artist of 'Various Artists' You may enter a comma separated list of folder names (without leading or trailing path separators) below.`

**Comment by scootergrisen** [comment]
What does "bar" mean "(bar those from <i>Exclude</i>)" in these strings?

`<p>Cantata will query your library using all of the rules listed. The list of <i>Include</i> rules will be used to build a set of songs that can be used. The list of <i>Exclude</i> rules will be used to build a set of songs that cannot be used. If there are no <i>Include</i> rules, Cantata will assume that all songs (bar those from <i>Exclude</i>) can be used.</p><p>e.g. to have Cantata look for 'Rock songs by Wibble OR songs by Various Artists', you would need the following: <ul><li>Include AlbumArtist=Wibble Genre=Rock</li><li>Include AlbumArtist=Various Artists</li></ul> To have Cantata look for 'Songs by Wibble but not from album Abc', you would need the following: <ul><li>Include AlbumArtist=Wibble</li><li>Exclude AlbumArtist=Wibble Album=Abc</li></ul>After the set of usable songs has been created, Cantata will randomly select songs to keep the play queue filled with specified number of entries (10 by default). If a range of ratings has been specified, then only songs with a rating within this range will be used. Likewise, if a duration has been set.</p>`

`<p>Cantata will query your library using all of the rules listed. The list of <i>Include</i> rules will be used to build a set of songs that can be used. The list of <i>Exclude</i> rules will be used to build a set of songs that cannot be used. If there are no <i>Include</i> rules, Cantata will assume that all songs (bar those from <i>Exclude</i>) can be used.</p><p>e.g. to have Cantata look for 'Rock songs by Wibble OR songs by Various Artists', you would need the following: <ul><li>Include AlbumArtist=Wibble Genre=Rock</li><li>Include AlbumArtist=Various Artists</li></ul> To have Cantata look for 'Songs by Wibble but not from album Abc', you would need the following: <ul><li>Include AlbumArtist=Wibble</li><li>Exclude AlbumArtist=Wibble Album=Abc</li></ul>After the set of usable songs has been created, Cantata will add the desired number of songs to the play queue. If a range of ratings has been specified, then only songs with a rating within this range will be used. Likewise, if a duration has been set.</p>`

**Comment by scootergrisen** [comment]
Space before " Setting the compression":
`The <a href=http://flac.sourceforge.net/documentation_tools_flac.html>compression level</a> is an integer value between 0 and 8 that represents the tradeoff between file size and compression speed while encoding with <b>FLAC</b>.<br/> Setting the compression level to <b>0</b> yields the shortest compression time but generates a comparably big file.<br/>On the other hand, a compression level of <b>8</b> makes compression quite slow but produces the smallest file.<br/>Note that since FLAC is by definition a lossless codec, the audio quality of the output is exactly the same regardless of the compression level.<br/>Also, levels above <b>5</b> dramatically increase compression time but create an only slightly smaller file, and are not recommended.`

**Comment by scootergrisen** [comment]
This string uses %string% placeholders but i have not seen this in other strings.
Perhaps it should be %1 placeholders or maybe HTML markup.
`<p>Filename (without extension) to save downloaded covers as.<br/>If left blank 'cover' will be used.<br/><br/><i>%artist% will be replaced with album artist of the current song, and %album% will be replaced with the album name.</i></p>`

**Comment by scootergrisen** [comment]
Some links use:
`<a href=url>`
Some use:
`<a href="url">`

**Comment by scootergrisen** [comment]
Both <br> and <br/> exists.

**Comment by scootergrisen** [comment]
Translators don't need all the HTML mark up.
So:
`<html><head/><body><p>Velkommen til Cantata</p></body></html>`
Could be just:
`Velkommen til Cantata`

Same with:
`<html><head/><body><p>Cantata is a feature-rich and user friendly client for Music Player Daemon (MPD). MPD is a flexible, powerful, server-side application for playing music.</p><p>For more information on MPD itself, please refer to the MPD website <a href="http://www.musicpd.org"><span style=" text-decoration: underline; color:#0000ff;">http://www.musicpd.org</span></a></p><p>This 'wizard' will guide you through the basic settings required for Cantata to function correctly.</p></body></html>`
