### ISSUE TITLE
ability to search folder names

### ISSUE THREAD

**Issue by atopia** [CDrummond/cantata#1159]
Since 2.x, searching in the Folders view will jump to Search and search for files only. This way, the ability to search for folder names from within Cantata is lost. Use cases: a) pull all music in a specific folder into the playlist, b) find music where a correctly named directory contains untagged files.
I suggest restoring the behaviour of Cantata 1.5.4 where CTRL-F in the Folders view opens its own search bar, which also matches on folder names.
I consider this not a UX design regression, as it is consistent to the Artists view in Cantata 2.x, which still uses its own search bar.

**Comment by CDrummond** [comment]
The reason why it does not use its own search - is that the folder view is lazy loaded. In Cantata 1.x the **whole** contents of the folder view were loaded the first time the view was shown. Cantata 2.x now only loads the top levels, and sub levels when expanded. Therefore, the 1.x search (which searched the loaded model) cannot work - as it would only search the currently loaded branches.

Searching in the search view when set to `File` does also search for folder names. So, this should still work/

**Comment by atopia** [comment]
Indeed, my bad. I did not notice because the List format omits folders. Is there any way Search could offer the Simple Tree and Detailed Tree display options found in the Folder view?

**Comment by CDrummond** [comment]
Currently only a simple list of songs is supported. I have thought of adding grouping options - e.g. group by genre, artist, album, etc. However, I have no time for this at the moment.

**Comment by atopia** [comment]
Fair enough, anyway thanks for your swift reply (and for making the best music player in the first place)!
