### ISSUE TITLE
Wish: keyboard shortcut for priority

### ISSUE THREAD

**Issue by Fuchs** [CDrummond/cantata#1168]
Hi, 

it would be awesome if it was possible to add a keyboard shortcut for the pre-defined priorities (the ones that are in the context menu) and maybe to add one for "custom" as well, as I use that to create "mini queues" within a queue of songs I'd like to play next, it's a bit cumbersome to do it by GUI for each track. 

Thanks in advance for considering this, kind regards.

**Comment by CDrummond** [comment]
Done, for 2.3.0

**Comment by Fuchs** [comment]
That was super quick, thank you very much and keep up the good work!
