### ISSUE TITLE
Graphical improvements for the albums view

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#1169]
This is a feature request. I'm using a lot the album "grid" view in Cantata and I'd like to know if it's possible to make it "responsive", basically to always have the albums width that fill all the horizontal space in the view (and don't have this blank space on the right then).

Also, would it be possible to have a "dark" background in this view (like for the infos panel) as an option?

**Comment by CDrummond** [comment]
Not keen on adjusting the size of the covers like this, as it means creating *lots* of cached covers. However, I have updated the code to adjust the gap between items - so as to 'fill' the row.

No, I have no intention of making the views darker. For this you need to use a darker colour, or widget style.
