### ISSUE TITLE
Provide simple settings to disable network requests

### ISSUE THREAD

**Issue by guillaume-uH57J9** [CDrummond/cantata#1170]
It's be nice to have a simple settings to disable all network requests made Cantata, except for the mpd connection. Ideally like a chekbox or switch that takes one click. 

By default, Cantata sends requests to various third party to retrieve metadata on music track (lyrics, ...), without asking for prior content. 
There should be either an easy opt out, or an opt-in on first start to ask the user for consent before making this request. 

The lyrics feature can be useful, but there are situations were you wouldn't want to make these requests : 
* You have very little / expense bandwidth and want to play music locally (ie on your local network) without opening outside connections. 
* You do not want your music collection data to be leaked to third parties.

**Comment by guillaume-uH57J9** [comment]
I captured network traffic while listening clicking on the info button in Cantata, using a socket file to connect to mpd, and listening to locally stored music. 

Summary: 
* 10 DNS A queries, 10 DNS AAAA queries
* 5 HTTP requests. There are un-encrypted and show any passive listener on the network which songs I am listening. 
* 5 TLS handshakes. I assume these are 5 HTTPS connections.

**Comment by CDrummond** [comment]
You can disable fetching of covers from last.fm in the settings dialog.The information view should not download anything unless it is visible. Therefore, this should prevent external network access.

For Cantata <2.3 (i.e. released versions) you can disable all network access via a (non-GUI) config item. See https://github.com/CDrummond/cantata/blob/2.1/README. You can also see the URLs accessed using `CANTATA_DEBUG=-0x1000 cantata`

For Cantata 2.3 (not released, git/master) you can disable network access via a commandline option - `cantata --no-network` You can also see he URLs accessed using `cantata --debug=network-access`

Seeing as network access can be disabled by not using Last.fm or the info page (which needs network access) - then I'm not convinced a GUI option is required.

To 100% ensure no network access, there is the non-gui config option, or the commandline option.

**Comment by CDrummond** [comment]
As stated, set 'Download covers from last.fm' to false, and don't use the context view - problem solved.

Disabling network access stops streams from working, and stops fetching covers via http if your MPD is on another machine.

The config item was turned into a commandline argument, as this is easier for macOS and windows users.
