### ISSUE TITLE
HTTP stream no volume button inside of the app

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1173]
I connected cantata to an local mpd/httpd stream and got no volume button.
Is this intented?

**Comment by CDrummond** [comment]
Cantata **only** shows the volume control if MPD tells cantata there is one available. I guess for your HTTP stream there is not. I'll investigate later, as using MPD's HTTP stream is not a feature I use. I guess a work-around would be for the playback code in Cantata to control the volume, if MPD cannot.

**Comment by Thaodan** [comment]
At least there's an audio stream called cantata listed in pulseaudio that belongs to cantata and use the application audio.
So cantata should use the volume of the QMultimedia stream to handle or not?

**Comment by CDrummond** [comment]
Yeah, I already looked - and both QtMultimedia and libVLC provide a way to get/set the volume. The issue is when you have both non-HTTP and HTTP outputs enabled. Then Cantata would need to volume controls. Which might look a little confusing...

**Comment by CDrummond** [comment]
Just to let you know I have started work on this. There will be 2 volume controls - MPD and HTTP, bu tonly one will be visible and active, with a menu to choose which.

**Comment by CDrummond** [comment]
Implemented, for 2.3.0

**Comment by Thaodan** [comment]
thanks.
