### ISSUE TITLE
Build fails with 3rdparty/solid-lite/libsolidlite.a

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1175]
I cannot build cantata 2.2.0 with errors related to `3rdparty/solid-lite/libsolidlite.a` using (on a Devuan Jessie amd64 system):

> $ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_HTTP_STREAM_PLAYBACK=ON -DENABLE_LIBVLC=ON -DENABLE_HTTP_SERVER=ON -DENABLE_PROXY_CONFIG=ON -DENABLE_DEVICES_SUPPORT=ON -DENABLE_REMOTE_DEVICES=OFF -DENABLE_UDISKS2=ON -DINSTALL_UBUNTU_ICONS=OFF -DCANTATA_HELPERS_LIB_DIR= -DENABLE_SIMPLE_MPD_SUPPORT=OFF -DENABLE_AVAHI=OFF -Wno-dev ..

But with `-DENABLE_UDISKS2=OFF` build success.

Is it ok? 
Which are differences?

Here below the error messages:
>[ 29%] Linking CXX executable cantata
3rdparty/solid-lite/libsolidlite.a(udisksopticaldisc.cpp.o): nella funzione "Solid::Backends::UDisks2::OpticalDisc::~OpticalDisc()":
udisksopticaldisc.cpp:(.text+0x156): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksopticaldisc.cpp.o): nella funzione "Solid::Backends::UDisks2::OpticalDisc::~OpticalDisc()":
udisksopticaldisc.cpp:(.text+0x1a5): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksopticaldisc.cpp.o): nella funzione "Solid::Backends::UDisks2::OpticalDisc::isAppendable() const":
udisksopticaldisc.cpp:(.text+0x345): riferimento non definito a "UdevQt::Device::deviceProperty(QString const&) const"
3rdparty/solid-lite/libsolidlite.a(udisksopticaldisc.cpp.o): nella funzione "Solid::Backends::UDisks2::OpticalDisc::OpticalDisc(Solid::Backends::UDisks2::Device*)":
udisksopticaldisc.cpp:(.text+0x5853): riferimento non definito a "UdevQt::Device::Device()"
udisksopticaldisc.cpp:(.text+0x5862): riferimento non definito a "UdevQt::Client::Client(QObject*)"
udisksopticaldisc.cpp:(.text+0x5893): riferimento non definito a "UdevQt::Client::deviceByDeviceFile(QString const&)"
udisksopticaldisc.cpp:(.text+0x589e): riferimento non definito a "UdevQt::Device::operator=(UdevQt::Device const&)"
udisksopticaldisc.cpp:(.text+0x58a6): riferimento non definito a "UdevQt::Device::~Device()"
udisksopticaldisc.cpp:(.text+0x58e0): riferimento non definito a "UdevQt::Device::deviceProperties() const"
udisksopticaldisc.cpp:(.text+0x5a98): riferimento non definito a "UdevQt::Client::~Client()"
udisksopticaldisc.cpp:(.text+0x5c2e): riferimento non definito a "UdevQt::Client::~Client()"
udisksopticaldisc.cpp:(.text+0x5c3a): riferimento non definito a "UdevQt::Device::~Device()"
udisksopticaldisc.cpp:(.text+0x5c79): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksopticaldisc.cpp.o): nella funzione "Solid::Backends::UDisks2::OpticalDisc::OpticalDisc(Solid::Backends::UDisks2::Device*)":
udisksopticaldisc.cpp:(.text+0x5e0c): riferimento non definito a "UdevQt::Device::Device()"
udisksopticaldisc.cpp:(.text+0x5e25): riferimento non definito a "UdevQt::Client::Client(QObject*)"
udisksopticaldisc.cpp:(.text+0x5e4c): riferimento non definito a "UdevQt::Client::deviceByDeviceFile(QString const&)"
udisksopticaldisc.cpp:(.text+0x5e57): riferimento non definito a "UdevQt::Device::operator=(UdevQt::Device const&)"
udisksopticaldisc.cpp:(.text+0x5e5f): riferimento non definito a "UdevQt::Device::~Device()"
udisksopticaldisc.cpp:(.text+0x5e99): riferimento non definito a "UdevQt::Device::deviceProperties() const"
udisksopticaldisc.cpp:(.text+0x603e): riferimento non definito a "UdevQt::Client::~Client()"
udisksopticaldisc.cpp:(.text+0x61fc): riferimento non definito a "UdevQt::Client::~Client()"
udisksopticaldisc.cpp:(.text+0x6208): riferimento non definito a "UdevQt::Device::~Device()"
udisksopticaldisc.cpp:(.text+0x62b4): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksstoragedrive.cpp.o): nella funzione "Solid::Backends::UDisks2::StorageDrive::~StorageDrive()":
udisksstoragedrive.cpp:(.text+0x3f): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksstoragedrive.cpp.o): nella funzione "Solid::Backends::UDisks2::StorageDrive::~StorageDrive()":
udisksstoragedrive.cpp:(.text+0x87): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksstoragedrive.cpp.o): nella funzione "Solid::Backends::UDisks2::StorageDrive::bus() const":
udisksstoragedrive.cpp:(.text+0x437): riferimento non definito a "UdevQt::Device::deviceProperty(QString const&) const"
udisksstoragedrive.cpp:(.text+0x4bf): riferimento non definito a "UdevQt::Device::deviceProperty(QString const&) const"
3rdparty/solid-lite/libsolidlite.a(udisksstoragedrive.cpp.o): nella funzione "Solid::Backends::UDisks2::StorageDrive::StorageDrive(Solid::Backends::UDisks2::Device*)":
udisksstoragedrive.cpp:(.text+0xcc3): riferimento non definito a "UdevQt::Device::Device()"
udisksstoragedrive.cpp:(.text+0xcd3): riferimento non definito a "UdevQt::Client::Client(QObject*)"
udisksstoragedrive.cpp:(.text+0xcf6): riferimento non definito a "UdevQt::Client::deviceByDeviceFile(QString const&)"
udisksstoragedrive.cpp:(.text+0xd01): riferimento non definito a "UdevQt::Device::operator=(UdevQt::Device const&)"
udisksstoragedrive.cpp:(.text+0xd09): riferimento non definito a "UdevQt::Device::~Device()"
udisksstoragedrive.cpp:(.text+0xd34): riferimento non definito a "UdevQt::Device::deviceProperties() const"
udisksstoragedrive.cpp:(.text+0xd7c): riferimento non definito a "UdevQt::Client::~Client()"
udisksstoragedrive.cpp:(.text+0xe1b): riferimento non definito a "UdevQt::Device::~Device()"
udisksstoragedrive.cpp:(.text+0xe36): riferimento non definito a "UdevQt::Client::~Client()"
udisksstoragedrive.cpp:(.text+0xe3e): riferimento non definito a "UdevQt::Device::~Device()"
3rdparty/solid-lite/libsolidlite.a(udisksstoragedrive.cpp.o): nella funzione "Solid::Backends::UDisks2::StorageDrive::StorageDrive(Solid::Backends::UDisks2::Device*)":
udisksstoragedrive.cpp:(.text+0xef3): riferimento non definito a "UdevQt::Device::Device()"
udisksstoragedrive.cpp:(.text+0xf03): riferimento non definito a "UdevQt::Client::Client(QObject*)"
udisksstoragedrive.cpp:(.text+0xf26): riferimento non definito a "UdevQt::Client::deviceByDeviceFile(QString const&)"
udisksstoragedrive.cpp:(.text+0xf31): riferimento non definito a "UdevQt::Device::operator=(UdevQt::Device const&)"
udisksstoragedrive.cpp:(.text+0xf39): riferimento non definito a "UdevQt::Device::~Device()"
udisksstoragedrive.cpp:(.text+0xf64): riferimento non definito a "UdevQt::Device::deviceProperties() const"
udisksstoragedrive.cpp:(.text+0xfac): riferimento non definito a "UdevQt::Client::~Client()"
udisksstoragedrive.cpp:(.text+0x104b): riferimento non definito a "UdevQt::Device::~Device()"
udisksstoragedrive.cpp:(.text+0x1066): riferimento non definito a "UdevQt::Client::~Client()"
udisksstoragedrive.cpp:(.text+0x1071): riferimento non definito a "UdevQt::Device::~Device()"
collect2: error: ld returned 1 exit status
CMakeFiles/cantata.dir/build.make:10383: set di istruzioni per l'obiettivo "cantata" non riuscito
make[2]: *** [cantata] Errore 1
CMakeFiles/Makefile2:102: set di istruzioni per l'obiettivo "CMakeFiles/cantata.dir/all" non riuscito
make[1]: *** [CMakeFiles/cantata.dir/all] Errore 2
Makefile:149: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

Thanks

**Comment by CDrummond** [comment]
Sorry - but this is an issue on your system. UDisks2 support builds find under Ubuntu 17.10 - and UDisks is building for you. Sorry, not much I can do.

**Comment by nousernouser** [comment]
Il giorno Fri, 26 Jan 2018 07:45:36 -0800
CraigD <notifications@github.com> ha scritto:

> Sorry - but this is an issue on your system. UDisks2 support builds find
> under Ubuntu 17.10 - and UDisks is building for you. Sorry, not much I can do.
> 

Indeed, building with UDisks give no errors to me, and (this is what I was not
sure it would be) the binary seems to work well... 

So that is ok.

Tank you very much.

A.

**Comment by CDrummond** [comment]
Re-opening as I've now recreated the issue, and a solution...

**Comment by nousernouser** [comment]
Great! Thank you a lot.
A.
