### ISSUE TITLE
Option to use originaldate as album date

### ISSUE THREAD

**Issue by whtv** [CDrummond/cantata#1177]
When I have an album tagged with the originaldate tag, it’s usually an old record (say, a jazz record from the 60s) which has been re-released on CD. The album will be listed as, say, from 2005, when it’s actually a record from 1965. I understand there are other cases like compilations, but in this case here, the 1965 date is the one I’m primarily interested in when looking at the library. So, ideally, I think there should be an option to make originaldate _the_ album date in case there is such a tag, otherwise fall back to the date tag.

**Comment by CDrummond** [comment]
As you stated, this will break compilations. The date is the date of the album - so in your case 2005 is correct. The whole 'date' thing is broken - as there is no album date. Unless 'date' is album date, and 'orig' is track date. In this case the current behaviour is correct.

To be honest, I don't use the 'orig year' field - so this is a non-issue to me. So, adding an option would be easy enough. (In fact I looked at the change, and it would be trivial) **But** then someone else will complain that it breaks for (e.g.) compilations. So, a lot of hassle for no real benefit.

**Comment by whtv** [comment]
I was thinking of an option (a) to show (and sort by) originaldate if that tag is present, otherwise use the date tag, or (b) the current behaviour. If you don’t think it should be done, I guess I’ll have to set date to originaldate for those albums by hand (which is unfortunate not so much because I care about the reissue date, but rather because you can’t easily auto-tag your collection with a Musicbrainz tagger that will pull both the date and originaldate tag).

**Comment by CDrummond** [comment]
I've updated the code to allow display/sort via 'original year' The setting is in the 'Interface/Tweaks'

Can you please checkout git/master and check?

**Comment by CDrummond** [comment]
? Well I assume all is OK...
