### ISSUE TITLE
Unsupported URI scheme for CUE tracks in the Information view

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1179]
[cantata 2.2.0, mpd 0.20.15, Devuan amd64]

Most of my audio archive is made of non-splitted audio files (one flac file containing entire cd without splitting tracks) + external cue sheets.

Albums and tracks for non-splitted flacs + cue files seems to be correctly listed in the 'Library' and 'Play Queue' views. Tracks are also listed in the 'Info' view.

Problem: following any track's link displayed in the 'Info' view comes to a 'Unsupported URI scheme' error.

Thanks for your work and support.

**Comment by CDrummond** [comment]
I'm going to re-open this, as I _think_ I might be able to work-around the issue and make the links work,.

**Comment by nousernouser** [comment]
Great! Thank you a lot.
A.
