### ISSUE TITLE
cantata prevents logout in plasma when not minimized to tray

### ISSUE THREAD

**Issue by marhkb** [CDrummond/cantata#1183]
```
distro: Arch Linux
cantata: cantata-git build from AUR
Qt: 5.10.0
plasma: 5.11.5
Frameworks: 5.42.0
```
When cantata's application window is visible and not minimized in tray it is impossible to logout from plasma.
A notifications pops up saying saying cantata prevents logout.
This is very annoying because most running programs like dock are already gone and so one have to kill cantata and logout from krunner.

**Comment by CDrummond** [comment]
Yeah, I can see this to under GNOME shell. :-(

**Comment by CDrummond** [comment]
Can you checkout git/master - and see if this is now fixed?

**Comment by marhkb** [comment]
it is fixed now. Thank you very much.

**Comment by CDrummond** [comment]
Thanks for the confirmation.
