### ISSUE TITLE
Edit Track Information shows all tags 'Unkown'

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1194]
I tried to edit tags in Cantata however most tag frames are shown as 'Unknown'.
After editing tags, Cantata shows the songs as 'Unknown - Unknown' in play queue.
Is there any problems on my side?

**Comment by CDrummond** [comment]
What tags? Is this file from MPD? i.e. is it **not** added as a local file via drag'n'drop?

**Comment by parkmino** [comment]
Yes, I mean the normal use in 'Server Folders', regardless of local files.

**Comment by CDrummond** [comment]
'Server Folders' gets its tag info from MPD.

**Comment by parkmino** [comment]
Let me make it clear again, Server Folders > Mouse context menu > Edit Track Information, and then all I can see is unknown tag frames even though they are not unknown.

**Comment by CDrummond** [comment]
I know what you are referring to. But, in the **Library** view, how is the track listed? _Edit track information_ gets all metadata (apart from comments) from MPD. **Only** the comment tag is read from the file. Which is why I'm asking how it is listed in the Library.

**Comment by parkmino** [comment]
Opps, in Library it's OK!

**Comment by CDrummond** [comment]
Most odd. And in the 'Server Folders' view, does it list the track name, or the filename (probably without extension) ?

What is the output of `echo -e "lsinfo FOLDER\n" | nc localhost 6600`  Replace `FOLDER` with the MPD folder containing the file - only the part of the folder within MPD's `music_directory` e.g. if you have `/var/lib/mpd/music/a/b/c/x.flac` and `music_directory=/var/lib/mpd/music'` then use `echo -e "lsinfo a/b/c\n" | nc localhost 6600`

**Comment by parkmino** [comment]
'Server Folders' view lists track name, not file name.

Is this what you want?

$ echo -e "lsinfo 이진아 - Random  진아식당 MENU.2\n" | nc localhost 6600
OK MPD 0.20.0
ACK [2@0] {lsinfo} too many arguments for "lsinfo"
ACK [5@0] {} No command given

**Comment by CDrummond** [comment]
Ah, assuming `이진아 - Random 진아식당 MENU.2` is the folder within `music_directory`, try: ` echo -e 'lsinfo "이진아 - Random 진아식당 MENU.2" \n' | nc localhost 6600`   (I've changed the echo quots, and added double quotes around the path)

**Comment by parkmino** [comment]
My bad and it should be.

$ echo -e 'lsinfo "이진아 - Random 진아식당 MENU.2" \n' | nc localhost 6600
OK MPD 0.20.0
file: 이진아 - Random 진아식당 MENU.2/01. 이진아 - 계단.flac
Last-Modified: 2017-07-21T21:21:05Z
Time: 274
duration: 273.520
file: 이진아 - Random 진아식당 MENU.2/02. 이진아 - RANDOM.flac
Last-Modified: 2018-02-07T01:36:54Z
Time: 203
duration: 203.386
file: 이진아 - Random 진아식당 MENU.2/03. 이진아 - 별것도 아닌 일.flac
Last-Modified: 2017-07-21T21:35:25Z
Time: 245
duration: 244.533
file: 이진아 - Random 진아식당 MENU.2/04. 이진아 - Everyday.flac
Last-Modified: 2017-07-21T21:35:43Z
Time: 231
duration: 230.826
file: 이진아 - Random 진아식당 MENU.2/05. 이진아 - 어디서부터.flac
Last-Modified: 2017-07-21T21:35:59Z
Time: 249
duration: 248.960
file: 이진아 - Random 진아식당 MENU.2/06. 이진아 - 밤,바다,여행.flac
Last-Modified: 2017-07-21T21:36:13Z
Time: 236
duration: 236.146
file: 이진아 - Random 진아식당 MENU.2/07. 이진아 - 오늘을 찾아요.flac
Last-Modified: 2017-07-21T21:36:25Z
Time: 265
duration: 264.840
OK
ACK [5@0] {} No command given

**Comment by CDrummond** [comment]
Well, there you go - as you can see:

```
file: 이진아 - Random 진아식당 MENU.2/02. 이진아 - RANDOM.flac
Last-Modified: 2018-02-07T01:36:54Z
Time: 203
duration: 203.386
```

MPD does not return title, artist., etc. metadata for these files. If MPD does not show it, not much Cantata can do.

With your example file, MPD returns the following for me:

```
file: 02. 이진아 - RANDOM.flac
Last-Modified: 2018-02-07T01:12:54Z
Time: 203
duration: 203.386
Title: RANDOM
Artist: 이진아
Album: Random 진아식당 MENU.2
Date: 2017-07-20
Track: 2
Genre: Jazz
AlbumArtist: 이진아
```

Have you tried refreshing MPD? You can do this in Cantata - `Refresh Database`

**Comment by parkmino** [comment]
No difference after 'mpc update'

**Comment by CDrummond** [comment]
Well, not sure what I can do. The `lsinfo` command you tried, is what Cantata uses. If this does not return the metadata, not much can be done.

**Comment by parkmino** [comment]
Then, how about removing tag editor from 'Folders'? Since there is no problem with 'Library' view.

**Comment by CDrummond** [comment]
Why? This is an issue on **YOUR** system. It works perfectly for me on mine. The Library view **also** uses `lsinfo` - so I'm unsure why it is working for you there. I guess it could be guessing the song tags from the filename.

Try editing `mpd-interface/mpdparseutils.cpp` change line 371 from `if (Loc_Library==location) {` to `if (Loc_Library==location || Loc_Browse==location) {`

**Comment by parkmino** [comment]
I tried but no difference.

**Comment by CDrummond** [comment]
What is the output of  `sqlite3 ~/.local/share/cantata/library/localhost_6600.sql -header -column "select select file,artist,artistId,album,albumId,title,genre1,track,time,year,type from songs where file like '%02. 이진아 - RANDOM.flac%'"`  ? My output is:

```
file                           artist      artistId    album       albumId                     title       genre1      track       time        year        type      
-----------------------------  ----------  ----------  ----------  --------------------------  ----------  ----------  ----------  ----------  ----------  ----------
X/02. 이진아 - RANDOM.flac        이진아         이진아                     Random 진아식당 MENU.2          RANDOM      Jazz        2           203         2017        0 
```
` ~/.local/share/cantata/library/localhost_6600.sql` is Cantata's SQLite cache of the MPD DB. The filename _might_ be different on your system.

**Comment by parkmino** [comment]
The output is as follows, should I install it?

The program 'sqlite3' is currently not installed. You can install it by typing:
sudo apt install sqlite3

**Comment by CDrummond** [comment]
Well, yeah - how else are you going to run the command?  :-)

**Comment by parkmino** [comment]
Error: near "select": syntax error

**Comment by parkmino** [comment]
FYI, I compiled MPD with '--disable-sqlite'.

**Comment by CDrummond** [comment]
This is **Cantata's** SQLite DB - not MPDs. It does not contain all of MPDs... try:

sqlite3 ~/.local/share/cantata/library/localhost_6600.sql -header -column "select select * from songs where file like '%02. 이진아 - RANDOM.flac%'"

**Comment by parkmino** [comment]
Same as

Error: near "select": syntax error

**Comment by CDrummond** [comment]
Ah, oops! Remove the double select! My bad...

```
sqlite3 ~/.local/share/cantata/library/localhost_6600.sql -header -column "select file,artist,artistId,album,albumId,title,genre1,track,time,year,type from songs where file like '%02. 이진아 - RANDOM.flac%'"
```

**Comment by parkmino** [comment]
It works now as,

artistId    album       albumId                     title               genre1      track       time        year        type      
------------------------------------------------------------------  ----------  ----------  ----------  --------------------------  ------------------  ----------  ----------  ----------  ----------  ----------
이진아 - Random 진아식당 MENU.2/02. 이진아 - RANDOM.flac  이진아   이진아               Random 진아식당 MENU.2  이진아 - RANDOM  모름      2           203         0           0

**Comment by CDrummond** [comment]
Please run the command as I asked - that way I can see the headers!  And place 3 back ticks (top right on most keyboards) before and after pasting the response.

**Comment by parkmino** [comment]
As I said, the latest MPD 0.20.16

**Comment by CDrummond** [comment]
No record of this. And the sqlite3 command (in the format requested)?

**Comment by parkmino** [comment]
Please, refresh and see above.

**Comment by CDrummond** [comment]
Output is not correct - as there is no `file` column. However, as you can see there is no genre for this file - implying the tags have been guessed from the filename. So, even library view is not correct - for this specific file.

Looks like your MPD cannot handle the tags in the file.

**Comment by parkmino** [comment]
So sorry for bothering you and it is all my fault.
You just reminded me of disabling metadata in mpd.conf

Once again, really sorry for wasting your time.
