### ISSUE TITLE
Load embedded covers in OGG files

### ISSUE THREAD

**Issue by Strit** [CDrummond/cantata#1195]
Hi.

Just installed Cantata + MPD and found out my .ogg files did not have any covers shown.
I have always embedded covers in my files directly, and the covers work fine for my FLAC files. Just not with my OGG files.

**Comment by Strit** [comment]
yeah.

This one has an embedded cover in it:
https://www.strits.dk/files/BassVoltage.ogg (right click to download).
Cover shows in VLC, but not in Cantata.

**Comment by CDrummond** [comment]
Thanks for the sample file. **really** helped. Fixed in git/master for 2.3.0

**Comment by Strit** [comment]
Very nice. thank you. 🙂
