### ISSUE TITLE
Stream m3u8 playlist in local folders does not work

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1197]
Stream m3u8 play-list in 'Home' and 'Root' under 'Folders' cannot be added to play queue while file m3u8 play-lists work fine.

**Comment by CDrummond** [comment]
An example would be nice. AFAIK. m3u8 is just a UTF-8 m3u. To extract the list of files, Cantata jsut reads the file line-by-line, ignoring lines that start with `#`

e.g. if I have 
/home/user/Music/x.m3u

```
#First track
Wibble.mp3
Track2.mp3
/a/path/track.mp3
relative/file.mp3
```

Then Cantata would attempt to add:
```
/home/user/Music/Wibble.mp3
/home/user/Music/Track2.mp3
/a/path/track.mp3
/home/user/Music/relative/file.mp3
```

**Comment by parkmino** [comment]
Please find the attached file for my internet radio play-list.

[인터넷 라디오.m3u.txt](https://github.com/CDrummond/cantata/files/1706479/m3u.txt)

**Comment by CDrummond** [comment]
Ah! That explains it. The code currently only handles loading local music tracks via the playlist - as this is what I thought the local browse was for. I hadn't even thought about http URLs... I'll modify the code to check for this.

**Comment by parkmino** [comment]
mms and rtmp can be used as well.

**Comment by CDrummond** [comment]
Should be fixed now. Please update and confirm. Note that your example playlist takes a little while to load. MPD does not parse remote playlist, and some of the stations here point to a playlist, which then contains the stream. When Cantata loads a radio stream URL, it checks if it is a playlist (in which case it downloads this and extracts the real url). This all takes a second or so, which adds up when you have multiple entries.

**Comment by parkmino** [comment]
Confirmed and thanks!
