### ISSUE TITLE
[Enhancement] Show toolbar cover tool-tip info in panel.

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1205]
Toolbar cover tool-tip is wonderful and is there any way to have it while mouse is free to move?
IMHO, how about showing the toolbar tool-tip info in left panel when clicking the toolbar cover?
Adding 'Cover' menu in sidebar might be something to consider.
Otherwise, option to show image of the current album cover in left panel should be enough.

**Comment by CDrummond** [comment]
I had a feeling this is where you were headed. No, tooltips are tooltips - and they are momentary.

However, what I propose is to add a 'Stretch Image' option to the album picture in the information/context view. You can then place this view in the sidebar, configure to collapse into a single pane, and then have the image stretched. This should allow you to have a large cover image visible for the current track.

**Comment by parkmino** [comment]
Yes, I fully agree with you and look forward to seeing this feature.
Please consider that the current info covers based on wikipedia are missing in many cases for me.
I think that embedded or external covers should have priority over wikipedia.

**Comment by CDrummond** [comment]
Context view images are all local/embedded - only the text comes from wikipedia/last.fm

**Comment by parkmino** [comment]
Hmm... however I see many cover images missing in info.
No cover in info while it is visible in play-queue and tool-tip.
I do not have a clue.

**Comment by parkmino** [comment]
Never mind my above comment.
I am listening to Android MPD and it seems to take a while to browse cover images.

**Comment by parkmino** [comment]
I have a question.
How about the cover images of local files? Is it visible in info as well?

**Comment by CDrummond** [comment]
No, but you could have easily checked this yourself. Issue raised #1207
