### ISSUE TITLE
Pixelized icon in "Large icons" KDE task switcher

### ISSUE THREAD

**Issue by Mel34** [CDrummond/cantata#1206]
KDE task switcher in X session uses icon defined in _NET_WM_ICON. Unless application has built-in larger icon, "Large icons" task switcher will display pixelized icon.
When using xprop on cantata window it reveals:
```
_NET_WM_ICON(CARDINAL) =        Icon (48 x 48):
                           ░░▒▒▒▒▒▒░░                   
                       ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░               
                     ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░             
                   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░           
                  ░▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒          
                 ▒▒▒▒▒▒▒▒░            ░▒▒▒▒▒▒▒▒         
               ░▒▒▒▒▒▒▒░                ░▒▒▒▒▒▒▒░       
               ▒▒▒▒▒▒░                    ░▒▒▒▒▒▒░      
              ▒▒▒▒▒▒                        ▒▒▒▒▒▒      
             ▒▒▒▒▒▒               ▒░         ▒▒▒▒▒▒     
            ░▒▒▒▒▒               ░▓▓▒         ▒▒▒▒▒▒    
           ░▒▒▒▒▒                ▒▓▓▓▒         ▒▒▒▒▒░   
           ▒▒▒▒▒                 ▒▓▓▓▓▓░        ▒▒▒▒▒   
          ░▒▒▒▒░                 ▒▓▓▓▓▓▓▒       ░▒▒▒▒░  
          ▒▒▒▒▒                  ▒▓▓▓▒▓▓▓▓░      ▒▒▒▒▒  
          ▒▒▒▒░                  ▓▓▓▓ ░▓▓▓▓▒     ░▒▒▒▒░ 
         ░▒▒▒▒                   ▓▓▓▓  ░▓▓▓▓░     ▒▒▒▒░ 
         ▒▒▒▒░                   ▓▓▓▓   ▒▓▓▓▓     ░▒▒▒▒ 
         ▒▒▒▒                    ▓▓▓▓    ▓▓▓▓░     ▒▒▒▒ 
        ░▒▒▒▒                    ▓▓▓▓    ▓▓▓▓▒     ▒▒▒▒░
        ░▒▒▒▒                   ░▓▓▓▓    ▓▓▓▓░     ▒▒▒▒░
        ░▒▒▒░                   ░▓▓▓▒   ░▓▓▓▓      ░▒▒▒▒
        ▒▒▒▒░                   ░▓▓▓▒  ░▓▓▓▓▒      ░▒▒▒▒
        ▒▒▒▒░                   ░▓▓▓▒  ▒▓▓▓▒       ░▒▒▒▒
        ▒▒▒▒░                   ▒▓▓▓▒   ▒▒░        ░▒▒▒▒
        ▒▒▒▒░           ░▒▓▓▓▓▓▒▒▓▓▓▒              ░▒▒▒▒
        ░▒▒▒░         ░▓▓▓▓▓▓▓▓▓▓▓▓▓░              ░▒▒▒▒
        ░▒▒▒▒        ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓░              ▒▒▒▒░
        ░▒▒▒▒       ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░              ▒▒▒▒░
         ▒▒▒▒       ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░              ▒▒▒▒ 
         ▒▒▒▒░      ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓              ░▒▒▒▒ 
         ░▒▒▒▒      ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒              ▒▒▒▒░ 
          ▒▒▒▒░      ▓▓▓▓▓▓▓▓▓▓▓▓▓▓░             ░▒▒▒▒  
          ▒▒▒▒▒      ░▓▓▓▓▓▓▓▓▓▓▓▓░              ▒▒▒▒▒  
           ▒▒▒▒░       ▒▓▓▓▓▓▓▓▓▒░              ░▒▒▒▒░  
           ▒▒▒▒▒         ░░▒▒▒░                 ▒▒▒▒▒   
            ▒▒▒▒▒                              ▒▒▒▒▒    
            ░▒▒▒▒▒                            ▒▒▒▒▒░    
             ▒▒▒▒▒▒                          ▒▒▒▒▒▒     
              ▒▒▒▒▒▒                        ▒▒▒▒▒▒      
               ▒▒▒▒▒▒░                    ░▒▒▒▒▒▒       
                ▒▒▒▒▒▒▒░                ░▒▒▒▒▒▒▒        
                 ░▒▒▒▒▒▒▒░            ░▒▒▒▒▒▒▒▒         
                  ░▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒░          
                    ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒            
                      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒              
                        ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                
                           ░░░░▒▒░░░░
```
Using xprop on unnafected applications reveals they have several embedded icons other than 48 x 48 (128 x 128 or 192 x 192)

Please see related issue: https://github.com/CDrummond/cantata/issues/898

**Comment by CDrummond** [comment]
Looks like a KDE issue to me. Task switcher in GNOME shows a smooth icon. Cantata calls `QMainWindow::setWindowIcon( QIcon::fromTheme("cantata") )` The icon is installed for 16, 22, 24, 32, 48, 64, 128, 256, 512 pixels and an SVG icon is also installed.

If I remove the call to `setWindowIcon` then no icon in shown in the about dialog, so I do not wish to do that.

As to why Qt picks the 48px icon for _NET_WM_ICON I have no idea. Why does the task switcher use _NET_WM_ICON and not the icon as specified in the .desktop file?

**Comment by Mel34** [comment]
You're absolutely right, it is KDE specific. Here is their bug report on it:
https://bugs.kde.org/show_bug.cgi?id=351055
To quote Nate Graham:

> the issue is that instead of using the icon in the .desktop file (which almost always looks good), KWin asks the window itself what icon to display

**Comment by CDrummond** [comment]
Still, what do you expect me to to about it? I install larger sized icons, these work in GNOME, KDE task panel, etc. The window icon is set with Qt code, using the icon name - so no explicit size set. Not sure what I can do. I'm willing to change code to fix this, just no idea how.

**Comment by Mel34** [comment]
Here's how Firefox solved that [problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1371932):
https://hg.mozilla.org/mozilla-central/rev/198b1e4e5438

Here's [mpv's](https://github.com/mpv-player/mpv/pull/4381/commits) take on it.

I'll ask around in KDE community and get back to you on that

**Comment by Pointedstick** [comment]
> Why does the task switcher use `_NET_WM_ICON` and not the icon as specified in the .desktop file?

Currently, this is by design, as @Mel34 pointed out--it's to to allow the app to set its own task switcher icon, when appropriate. For example GIMP uses this feature to display a thumbnail of the current image, instead of its own icon.

A side effect of this feature is that the app needs to set the icon to look like something nice, or else it will inherit the standard 48x48 icon that Qt provides. You'll need to manually set `_NET_WM_ICON` to point to the nice high-res icon.

**Comment by CDrummond** [comment]
And **NONE** of these examples are Qt apps.

**Comment by Mel34** [comment]
Would this help? https://github.com/webcamoid/webcamoid/blob/master/StandAlone/src/main.cpp
It's a qt5 application.
```
   if (QIcon::themeName().isEmpty())
        QIcon::setThemeName("hicolor");

#ifdef Q_OS_OSX
    QIcon fallbackIcon(":/icons/webcamoid.icns");
#elif defined(Q_OS_WIN32)
    QIcon fallbackIcon(":/icons/hicolor/256x256/webcamoid.ico");
#else
    QIcon fallbackIcon(":/icons/hicolor/scalable/webcamoid.svg");
#endif

app.setWindowIcon(QIcon::fromTheme("webcamoid", fallbackIcon));
```

**Comment by CDrummond** [comment]
Not really. Cantata already calls setWindowIcon using QIcon:: fromTheme

**Comment by CDrummond** [comment]
This should now be fixed in git/master. xprop shows multiple icons, 128, 48, and 64 - lists each twice, not sure why.

Can you checkout git/master and confirm the issue is resolved? I have not KDE install to test with.

**Comment by Mel34** [comment]
![screenshot_20180213_233632](https://user-images.githubusercontent.com/13254332/36177701-d597a388-1116-11e8-9931-e4f95388810b.png)
You sir are awesome!

**Comment by Pointedstick** [comment]
@Mel34, what distro are you using that you see such a beautiful un-pixellated Firefox icon? openSUSE?

**Comment by Mel34** [comment]
@Pointedstick Arch

**Comment by glaubersm** [comment]
Both Firefox and Thunderbird have nice icon in "large icons" task switcher on Arch Linux.

**Comment by Pointedstick** [comment]
Wow. It is just Ubuntu that messes this up...?

**Comment by Mel34** [comment]
@Pointedstick Arch installs the additional icon, check out https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/firefox and PKGBUILD in it.
