### ISSUE TITLE
Cantata exits with 'Scale Album Cover' on

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1209]
Thanks for implementing this feature.

However it crashes sometimes on following conditions,
Select Info on side bar > 'Scale Album Cover' > Play songs manually by mouse double clicking or clicking next track.

**Comment by CDrummond** [comment]
Oops! Looks like its updating whilst updating! I'll use a timer to control updates.

**Comment by CDrummond** [comment]
Should now be fixed, can you please update and confirm.

**Comment by parkmino** [comment]
Confirmed and thanks!
