### ISSUE TITLE
[Enhancement] Horizontally center align headers and images in information view.

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1210]
Horizontally centred alignment option would be helpful for better layout.

**Comment by parkmino** [comment]
Now I moved to kvantum appearance which provides transparent background cover in play-queue.
It has more wide and consistent look, I don't want to bother you any more.

**Comment by CDrummond** [comment]
Tried to center images, and headers before, but failed. However I now seem to have this working! Won't make it an option though, just always center the headers and images.

**Comment by CDrummond** [comment]
Implemented now.
