### ISSUE TITLE
[Enhacement] Support embedded lyrics in info

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1211]
Most of Korean lyrics are not found from 'Lyrics Provided'.
I would like embedded 'Lyrics' to be supported in info and have priority over 'Lyrics Provided'.

**Comment by parkmino** [comment]
Hmm... I remember my previous request and close this issue.
Lyrics are visible in meta-data in info though it is not scrolling as in lyrics.

**Comment by CDrummond** [comment]
Ummm... Lyrics **should** be read from embedded files. Which file types? What is the**TAG** used for the lyrics?

Currently the code reads lyrics from mp3, mp4 and vorbis comments

**Comment by CDrummond** [comment]
Should now be fixed, can you please update and confirm.

**Comment by parkmino** [comment]
Confirmed and thanks!
