### ISSUE TITLE
RFE: Icon rotation in sidebar tab-bar mode with only show icons, no text

### ISSUE THREAD

**Issue by Mel34** [CDrummond/cantata#1214]
Would it be possible to rotate the icons displayed 90 degrees right in the sidebar while using tab-bar mode and no text is being displayed?

_Before_
![screenshot_20180216_200500](https://user-images.githubusercontent.com/13254332/36324419-ad9e71e6-1354-11e8-9e8c-b99fcd345b54.png)
_After_
![screenshot_20180216_200500_mockup](https://user-images.githubusercontent.com/13254332/36324770-ce3da506-1355-11e8-8dba-4dba6ec4b1c5.png)
Please, forgive the crude mockup.

**Comment by CDrummond** [comment]
Why not just use the 'small' sidebar mode with no text?

**Comment by Mel34** [comment]
Tabs are swappable using mouse, small sidebar icons aren't

**Comment by CDrummond** [comment]
Ah, I can fix that - adding mouse wheel to change views seems like a good idea.

As to the tab icons, the tabs are drawn by the style - so not sure there is much I can easily do for that.

**Comment by Mel34** [comment]
Actually, I'd be very happy with icons beeing mouse wheel swappable, I was under the impression that you needed tab widget to make it happen.
