### ISSUE TITLE
Request: filter or sort albums on the date they was added to the library

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1215]
What I wish to do is, for example, being able to make a smart or a dynamic playlist that contains all albums added to the library in the last thee months.
Being able to sort the library by "date added", or search it, would be good too.
Do you think that's possible? I don't know if MPD stores that information or if reading the creation date or modified date of the files would be sufficient.

**Comment by CDrummond** [comment]
If you set the library to group by albums, then you can sort on modification date.

I'll add a filter to 'smart' playlists allowing you to specify only files in the the last x days.

**Comment by CDrummond** [comment]
I've now implemented a 'max age' setting for smart playlists. Can you checkout git/master and confirm this is OK?

**Comment by Tichy** [comment]
I tried it and setting a smart playlist without filters, files added in the last 90 days and a very high number of songs (10000) does exactly what I needed. Thanks.
