### ISSUE TITLE
Ignore more diacritics when searching?

### ISSUE THREAD

**Issue by elcste** [CDrummond/cantata#1217]
Right now I can search for many words without diacritics and still get a match:

- **clement** and it will show an artist or title with **Clément**
- **dvorak** will show **Dvořák**
- **roze** will show **Różę**

This is very useful for both lazy typing and foggy memories!

However, I've noticed that if I search for

- **okland** it does *not* show **Økland**
- **pawel** does *not* show **Paweł**

Both of these do work in another music player I use, Quod Libet. (It's a GTK+ app, so likely not directly helpful.)

Thanks!

**Comment by CDrummond** [comment]
Cantata itself does not explicitly handle this diacritic conversion. The title/artist/album are stored in a SQLite [FTS](https://www.sqlite.org/fts3.html) (full text search) database table. Cantata then queries the SQLite DB - and SQLite handles diacritics. Not sure why this is not working for these...

**Comment by CDrummond** [comment]
Looked at QuodLibet's code - and if I'm reading it correct, it creates a regular expression with all diacritics. e.g. `Hello` would become `[hḫȟḩĥⱨḧḣḥɦẖħ][eéĕěȩêḙëėẹȅèẻȇēⱸęᶒɇẽḛ][lĺƚɬľļḽȴḷⱡꝉḻŀɫᶅɭł][lĺƚɬľļḽȴḷⱡꝉḻŀɫᶅɭł][oóŏǒôöȯọőȍòỏơȏꝋꝍⱺōǫøõ]`

Even if I was to change the strings to be regular expressions, SQLite's FTS does not seem to support these. To be honest, I don't know how SQLite's FTS works, or how it decides which diacritics to support, etc. So, I'm not sure what can be done about this. If anything (and assuming Cantata is using FTS correctly), this would be a SQLite issue.

**Comment by elcste** [comment]
That all makes sense. Thanks for the investigation and explanation!
