### ISSUE TITLE
Open in File Manager shouldn't be active only for folders in the Folders view

### ISSUE THREAD

**Issue by cipricus** [CDrummond/cantata#1220]
In _Folders_ view: the option is visible but disabled when selecting files and not folders. (If one has folders or links to folders in the music folder, those can be accessed in this way in the file manager, but not files present as such in the music folder).

It is absent in _Library_ and _Playlists_ view.

Shouldn't it be better to have it **always when selecting files**? Also in _Library_ when selecting albums?

---

Cantata 2.2.0 in Linux Mint 18.3 KDE.

**Comment by CDrummond** [comment]
No. Use a custom action for this.
