### ISSUE TITLE
Folders view should act more like a file manager/viewer (and not require Database refresh)

### ISSUE THREAD

**Issue by cipricus** [CDrummond/cantata#1221]
The Folders view shows the folder structure of the music folder but ignores any changes of the local files until a full rescan of the database is made (Database refresh).

Is it possible to make Folders view act like a folder viewer (like Files view in Clementine and Qmmp)?

That would solve different problems. For example: 

- A simple file that I have just deleted from my music folder `~/Music` is visible in Folders view until I **scan all the database**; maybe the Library view is supposed to act in this way, but for the Folders view this is somehow unexpected.

- I have music in different locations, therefore I have added **links** to those locations into the music folder that the Folders view can display. Some of these locations are on **removable hard disks**. If I make a full database rescan to solve the problem mentioned above (one file deleted but still showing) some of these links will be removed from Folders view if not all removable disks are connected at he moment of the database refresh.

---

Cantata 2.2.0 in Linux Mint 18.3 KDE.

**Comment by CDrummond** [comment]
The 'Folder View' ('Server Folders' for 2.3/master) listing comes from MPD. Therefore, to be updated MPD needs to be updated.

**Comment by CDrummond** [comment]
Version 2.3.0 will allow you to browse local folders (from $HOME and root), and this should react to changes. This listing is independent of MPD, and all files added this wa will be 'served' to MPD via Cantata's inbuilt HTTP server.
