### ISSUE TITLE
[feature request] Albums grouped by labels

### ISSUE THREAD

**Issue by Musikermomo** [CDrummond/cantata#1224]
I wish that the albums could be grouped by labels when you sort them by artist, year or modification date in grid view, as shown below. (or for artists in grid view alphabetically)
Do you think that's possible?

![image](https://user-images.githubusercontent.com/18223993/36793600-1962e180-1c9e-11e8-96c3-f7e1eb5646b4.png)

I love the client, thank you so much!

**Comment by CDrummond** [comment]
Sounds like a great idea. Unfortunately, I have no idea how it would be implemented. Know of any Qt (not KDE) apps that have a similar widget?

**Comment by CDrummond** [comment]
I have started work on this, in the 1224-categorizedview branch. This branch is **not** stable, and nowhere near complete.

**Comment by Musikermomo** [comment]
This looks very promising, I think.

**Comment by CDrummond** [comment]
Merged into master for 2.3.0

**Comment by Musikermomo** [comment]
Works perfectly! Thank you very much!
