### ISSUE TITLE
[feature request] Waveform Seekbar

### ISSUE THREAD

**Issue by Musikermomo** [CDrummond/cantata#1225]
Can a Waveform Seekbar be implemented as seen in DeaDBeeF, or is it impossible due to Cantata being a mpd client?

![2018-03-01_05-40-58](https://user-images.githubusercontent.com/18223993/36827462-f9b6f094-1d13-11e8-95e5-b83306b11141.png)

https://github.com/cboxdoerfer/ddb_waveform_seekbar
http://deadbeef.sourceforge.net/

**Comment by CDrummond** [comment]
Sorry, not something I have any interest in implementing.
