### ISSUE TITLE
journal log with psoition

### ISSUE THREAD

**Issue by rinne13** [CDrummond/cantata#1227]
In my journal logging there a lot of messages:
 kde.dataengine.mpris: "org.mpris.MediaPlayer2.cantata" exports "Position" as D-Bus type "t" but it should be D-Bus type "x"
The message appears every two seconds

**Comment by CDrummond** [comment]
I've updated the code, which should resolve this. Can you checkout and build git/master and confirm?

**Comment by rinne13** [comment]
Yes this works for me now.
