### ISSUE TITLE
[Bug] Segfault on album expansion with Qt 5.10

### ISSUE THREAD

**Issue by qwertys-ru** [CDrummond/cantata#1228]
Cantata segfaults when attempting to show tracks in album. This problem started after one of system updates, presumably, when Qt 5.10 has entered stable repo.

System info:
* KDE Neon stable (Ubuntu 16.04 based)
* Qt 5.10 from KDE Neon repos
* Cantata 2.2.0 from ppa:ubuntuhandbook1/cantata-qt

Syslog entries:
```
Mar  2 13:35:34 pluto kernel: [11627.779166] show_signal_msg: 11 callbacks suppressed
Mar  2 13:35:34 pluto kernel: [11627.779171] cantata[29190]: segfault at 8 ip 00007f28fab21310 sp 00007ffefbe695c8 error 6 in libQt5Core.so.5.10.0[7f28fa854000+4df000]
```

Please, let me know if should address this issue to the repo owner.

**Comment by CDrummond** [comment]
Please, re-try with git/master. If it still crashes:

1. Compile git/master with debug - pass `-DCMAKE_BUILD_TYPE=Debug` to cmake
2. Run Cantata under gdb:
```
> gdb cantata
gdb> run
```
When Cantata crashes, type `where` - post results here.

**Comment by Mel34** [comment]
It has not been recompiled against the latest version of Qt5. This is usually due to use of Qt private headers which means they depend on an exact version of Qt and not just a matching soname.
FWIW, Cantata-git built against qt5 5.10.1 on my machine doesn't crash. @qwertys-ru try contacting ppa maintainer and ask for a rebuild.

**Comment by CDrummond** [comment]
Odd, AFAIK, Cantata does not use any Qt private headers.

**Comment by qwertys-ru** [comment]
Cantata no longer segfaults after recompiling from master. I assume thiss issue is relevant to this build only. I will contact ppa maintainer shortly.
In the meantime, could you please provide more elaborate instructions for installation? An incomplete list of packages I had to install for Ubuntu 16.04 were:

* cmake
* make
* g++
* libudev-dev
* libavcodec-dev
* libcddb2-dev
* libmusicbrainz5-dev
* libmtp-dev
* libvlc-dev
* libvlccore-dev
* libmpg123-dev
* libcdio-paranoia-dev
* libcdparanoia-dev
* libtag-extras-dev
* libqt5svg5-dev
* qtbase5-dev
