### ISSUE TITLE
Cantata is not reloading my music folder

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [CDrummond/cantata#1229]
Hi,

Cantata is not reloading my music folder when I open it. There are new files and I removed other ones, but the app doesn't reload the list.

openSUSE 42.3, Cantata 2.2.0

**Comment by CDrummond** [comment]
Cantata gets its listing from MPD. (Even the 'Personal mode just starts a local MPD instance). To reload music you need to refresh the MPD database - this can be done via Cantata's menu.

AFAIK, MPD can be configured to auto update on changes, but this depends upon how it was compiled.

**Comment by ViniciusBRodrigues** [comment]
I get it! Many thanks.
