### ISSUE TITLE
Duplicate jump list entries in KDE plasma

### ISSUE THREAD

**Issue by Fuchs** [CDrummond/cantata#1233]
KDE plasma shows context menu entries for players that support mpris for play/pause, stop, previous and next tracks. 

As cantata supports these in the .desktop file as jump list actions as well, there are duplicates. 

These four actions should have a  NotShowIn=KDE   in the .desktop entry to avoid that. 
The other entry/entries (such as stop after next track) can be left as is, because KDE plasma doesn't add these. 

Also see: https://bugs.kde.org/show_bug.cgi?id=391713

thanks in advance, kind regards, 

Christian

**Comment by CDrummond** [comment]
I'll just remove all entries - they're a hangover from Unity support. Cant just exclude some, as Cantata can be configured to **not** instantiate the MPRIS interface - in which case you'd see the `stop after` action, and not `play`, etc.

**Comment by Fuchs** [comment]
Perfectly fine with me as well. Thank you very much for the fast reaction as usual and keep making great software.
