### ISSUE TITLE
Dirble token hard-coded, too many requests

### ISSUE THREAD

**Issue by a14a** [CDrummond/cantata#1234]
Same issue as #1111, but unlike the OP, i managed to reproduce it with your debugging routine:

CANTATA_DEBUG=-0x00001000 cantata
$ NetworkAccessManager get "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" true 
NetworkJob NetworkJob 0x1666710 0x19ed890 
NetworkJob handleReadyRead 0x1666710 0x19ed890 
NetworkJob jobFinished 0x1666710 0x19ed890 
NetworkJob jobFinished "http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e" 299 "Error downloading http://api.dirble.com/v2/categories/primary?token=1035d2834bdc7195b8929ad7f70a8410f02c633e - server replied: Too Many Requests" 
NetworkJob ~NetworkJob 0x1666710 0x19ed890 
NetworkJob cancelJob 0x1666710 0x19ed890 

Note that my token is identical to the one in the original report - it's hardcoded in cantata/models/streamsmodel.cpp . Perhaps we could contact Dirble to relax the limitations, but the proper way here would be to implement an unique API token generation process. If that's too much work, perhaps we can at least let the user bring their own API keys via a setting instead of rebuilding the source tree?

**Comment by a14a** [comment]
BTW congratulations on hitting 1500 Dirble requests in a month - that's probably an indication of growth, thanks for all your hard work developing the great app!

**Comment by CDrummond** [comment]
What I'll do is:
1. Alert the user that this error has occured
2. Add a 'API Keys' section to the preferences dialog, allowing custom keys to be set for; Last.fm, TuneIn, Dirble, etc.
