### ISSUE TITLE
[PROPOSAL] Sync podcasts with gpodder.net

### ISSUE THREAD

**Issue by adocampo** [CDrummond/cantata#1237]
Hi there!
I love the work with cantata, is a very useful and nice application! 
I've just hang around to say a pair of tips about podcast that I would find quite useful: 
- Synchronization with gpodder.net, so you can sync your rss bookmarks through several cantata instances. Clementine player does this, perhaps porting its code can be easy.
- If the former is hard to develop, it can be workarounded with a see/export your RSS feed as OPML, so you can do it manually.
Hope you like the ideas ;)

**Comment by adocampo** [comment]
Unfortunately I'm a systems guy, bash and python are fine but C++ is (far) beyond my area... :| Anyway, I can take a look to clementine source files, to see if I have any chance to copy-paste something from there, and see what happens, but last time I tried to do a "hello world" in QT was a frightening experience, so I can't even imagine how to put some buttons and textboxes on the preferences dialog and make them work...

**Comment by CDrummond** [comment]
Open since March, and no-one has stepped forward with any help. Sorry, but this is not a feature I would ever use, so not something I have time to implement.

Closing as wont-fix, but will happily accept a pull request to implement.
