### ISSUE TITLE
covers aren't copied when transcoding to a device

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1239]
It used to work, but I don't know when it stopped, because it's passed some time and some git updates since I transcoded something to a device the last time.

My settings are these
![screenshot_20180401_152710](https://user-images.githubusercontent.com/2348771/38173612-8b99ff7c-35c1-11e8-950c-3ba22db4c340.png)

There's no size limit and all the albums I tried to copy contained a cover.jpg file.

I tried this with a device connected through SSH and another to USB.

**Comment by CDrummond** [comment]
I cannot recreate this. I have tried:

1. SSH folder
2. Local folder
3. USB thumb drive

`cover.jpg` was created/copied each time.

Does the source have embedded covers?

**Comment by Tichy** [comment]
I tried again with different albums, but it happens with some of them. Always the same ones. I don't know what triggers this. I tried to see if could be because of some characters in the artist name (eg. '&') or if it happens when there's an embedded cover AND a cover.jpg file, but that wasn't.

**Comment by CDrummond** [comment]
Just to confirm, and this is what I checked; does it happen for files without an embedded cover and a cover file?

If you set Cantata to **always** transcode, does it still happen? (as this is the setting I used)

**Comment by CDrummond** [comment]
If you update, I've added more debug to indicate when a cover is copied. Start cantata: `cantata --debug=covers`

```
2018-04-02 14:38:57 - Covers "FileThread" copyCover ("albumart.png", "albumart.jpg", "cover.jpg", "cover.png", "AlbumArt.jpg", "AlbumArt.png", "folder.jpg", "folder.png", "Bigger, Better, Faster, More!.jpg", "Bigger, Better, Faster, More!.png", "4 Non Blondes - Bigger, Better, Faster, More!.jpg", "4 Non Blondes - Bigger, Better, Faster, More!.png")
2018-04-02 14:38:57 - Covers "FileThread" copyCover Found cover to copy "/var/lib/mpd/Music/4 Non Blondes - Bigger, Better, Faster, More!/" "albumart.jpg" copying as "cover.jpg"
```

**Comment by Tichy** [comment]
This time I set cantata to always transcode, then copied an album that had embedded covers and a cover.jpg file and another one that had only the cover.jpg file. The first one was copied (at 2018-04-02 16:18:42), but not the second (2018-04-02 16:20:33).

Here's the debug log: https://gist.github.com/Tichy/03335854ce3ca3705215a2351b461bdc

It says that both were copied, but there's no cover.jpg file in the second destination folder.

Transcode was done on an SSH share.

**Comment by CDrummond** [comment]
Can you update, and try again? I've made some slight mods (to ensure correct file type), and added a little more debug.

**Comment by Tichy** [comment]
Ok. Here's the new log: https://gist.github.com/Tichy/98eb80205300d70140979d8b11a6d3c7

Starts at 2018-04-02 17:05:28

**Comment by CDrummond** [comment]
Hmm. I use `QFile::copy(sourceDir+coverFile, destDir+destName)` to copy the files. This is failing - as to why, no idea. Permissions?

Anyhow, I've updated the code to read the source file, and write to dest file if copy fails. Update and try again?

**Comment by Tichy** [comment]
I don't think that the problem lies on permissions, in this case. The source file is world readable and the destination directory should be fine, since the music files are saved without issue.

With the new build the cover was copied. Here's the log: https://gist.github.com/Tichy/be66edc67d57e1371d0f7abf7454f7dd

**Comment by CDrummond** [comment]
Strange, as `QFile::copy()` should work.

Just a thought - can you try  **without** transcoding? As I'm guessing this should also fail - as it too will use `QFile::copy()`

**Comment by Tichy** [comment]
In data lunedì 2 aprile 2018 18:15:00 CEST, CraigD ha scritto:
> Just a thought - can you try  **without** transcoding? As I'm guessing this
> should also fail - as it too will use `QFile::copy()`

I tried now, but the flac files are copied.

**Comment by CDrummond** [comment]
Ah, yeah - just looked at the code, and `QFile::copy` is not used here.

So, closing - as I assume this is now fixed?

**Comment by Tichy** [comment]
Yes, sure. If you are fine with the workaround, I'm fine too. Thanks.
