### ISSUE TITLE
something strange with tracks display and timining (maybe related to CUESHEETs)

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1249]
Hi
I have noticed something strange with tracks display and timining when using CUESHEETs (one FLAC file per album + one CUE file) -- but I do not know if this is related with CUESHEETs or not...

1. **INACCURATE TRACK DURATIONS IN THE LIBRARY VIEW**
Some tracks durations showed in the library view are inaccurate and do not match with the correct durations showed in the play queue. See the image below:
![durationsdontmatch1](https://user-images.githubusercontent.com/35839588/39208109-3ecacd54-4802-11e8-8580-dc38d64bb512.png)

If this issue is related with CUESHEETs, then I imagine something wrong with calculation of track duration during cuesheet parsing...

2. **MISSING TRACKS**
With this CUESHEET :
```
REM DISCID "C511B00F"  
REM CATALOG "0000000000000"  
REM GENRE "Classical"  
REM DATE "1954"  
REM DISC "1"  
REM DISCTOTAL "1"
REM LOCATION "Jesus Christus Church, Dahlem"
REM ORGANIZATION "Deutsche Grammophon GmbH, Hamburg"
REM COMMENT "[ADD] (MONO)"
REM COMPOSER "Giuseppe Verdi"
PERFORMER "Giuseppe Verdi"
TITLE "Messa da Requiem"
FILE "audiocdjoined.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Requiem"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 0:00:00
  TRACK 02 AUDIO
    TITLE "Dies irae: i. Dies irae"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 8:22:00
  TRACK 03 AUDIO
    TITLE "Dies irae: ii. Tuba mirum"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 10:27:28
  TRACK 04 AUDIO
    TITLE "Dies irae: iii. Liber scriptus"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 13:11:50
  TRACK 05 AUDIO
    TITLE "Dies irae: iv. Quid sum miser"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 18:05:50
  TRACK 06 AUDIO
    TITLE "Dies irae: v. Rex tremendae"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 21:41:65
  TRACK 07 AUDIO
    TITLE "Dies irae: vi. Recordare"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 25:21:50
  TRACK 08 AUDIO
    TITLE "Dies irae: vii. Ingemisco"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 29:01:00
  TRACK 09 AUDIO
    TITLE "Dies irae: viii. Confutatis"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 32:14:58
  TRACK 10 AUDIO
    TITLE "Dies irae: ix. Lacrymosa"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 36:48:55
  TRACK 11 AUDIO
    TITLE "Offertorio"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 42:11:00
  TRACK 12 AUDIO
    TITLE "Sanctus"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 51:04:00
  TRACK 13 AUDIO
    TITLE "Agnus Dei"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 53:32:00
  TRACK 14 AUDIO
    TITLE "Lux aeterna"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 57:54:00
  TRACK 15 AUDIO
    TITLE "Libera me"
    REM COMPOSER "Giuseppe Verdi"
    PERFORMER "Maria Stader (soprano), Marianna Radev (mezzo-soprano), Helmut Krebs (tenor), Kim Borg (bass); RIAS-Kammerchor; Chor der St. Hedwigs-Kathedrale; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"
    INDEX 01 63:20:00
```
this is what is showed in the library:
![library](https://user-images.githubusercontent.com/35839588/39208793-349081d8-4804-11e8-860c-197527ee631f.png)

and this is the play queue when adding the entire album from the library:
![queue-from-library](https://user-images.githubusercontent.com/35839588/39209137-49669204-4805-11e8-88e2-c52c84d99a34.png)

The first and second track are missed, either in the library and the queue!!! 
Again, durations in the library view are inaccurate and do not match with the correct durations showed in the play queue.

But if I add the CUESHEET playlist from the folders view:
![folders](https://user-images.githubusercontent.com/35839588/39209557-6116a50a-4806-11e8-9b85-9fd567108826.png)

to the play queue:
![queue-from-folder](https://user-images.githubusercontent.com/35839588/39209565-6659de1a-4806-11e8-8a16-72d61e68d7af.png)

Now all the tracks are present, with the correct durations!!!

Thanks for your work.
Regards

**Comment by CDrummond** [comment]
Both issues should now be fixed. Can you checkout (and compile) git/maser to confirm?

The issue with incorrect times (I think) was due to Cantata always rounding to seconds to early. This should be resolved - but I don't have your files to confirm.

The missing tracks were due to the `INDEX` line not using 2 digits for the first number - you had `INDEX 01 0:00:00` and not `INDEX 01 00:00:00` Cantata should now accept both forms.

**Comment by nousernouser** [comment]
Hi. Just done checkout and compile master.

1. Issue with incorrect times
I have checked track durations for some albums. Now durations in the library view match with those in the play queue; but, with certain albums, the duration of the last track in the library view do not match exactly (+/- 1 second) with the play queue, being this the correct one -- as I have manually calculated.

2. Missing tracks 
You are right. 
Indeed, the official CUESHEET (CDRWIN) specification syntax is:
`INDEX [number] [mm:ss:ff]`
requiring 2 digits for MM SS and FF.
Sorry. My fault. 

Thanks

**Comment by CDrummond** [comment]
Should now be fixed. Can you update and confirm? Thanks.

**Comment by nousernouser** [comment]
Updated. But I cannot confirm.
I have checked again tracks durations for some albums: still, with certain albums, the duration of the last track in the library is not accurate (+/- 1 second) respect to the play queue, which displays the correct duration (as results doing manual calculation). 
For example, with this cuesheet:
```
REM DISCID "850aa60a"
REM CATALOG "5602896026321"
REM GENRE "Folk"
REM DATE "1995"
REM DISCNUMBER "1"
REM DISCTOTAL "2"
REM SOURCEMEDIA "CD"
REM LOCATION "Gravado ao vivo no Coliseu Do Porto em 6 de Maio de 1995"
REM ORGANIZATION "SPA / Movieplay"
REM COPYRIGHT "SPA 1995"
REM DESCRIPTION "Portoguese release"
REM COMMENT "Catalog: PE 51.022 A/B"
REM DISCNUMBER "1"
REM DISCTOTAL "2"
PERFORMER "Dulce Pontes"
TITLE "A Brisa do CoraÃ§Ã£o (CD1)"
FILE "audiocd.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Os Ãndios Da Meia Praia"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Se Voaras Mais Perto"
        INDEX 01 05:35:00
  TRACK 03 AUDIO
    TITLE "Novo Fado Da Severa"
    INDEX 01 09:41:05
  TRACK 04 AUDIO
    TITLE "Povo Que Lavas No Rio"
    INDEX 01 14:59:72
  TRACK 05 AUDIO
    TITLE "LÃ¡grima"
    INDEX 01 20:33:60
  TRACK 06 AUDIO
    TITLE "Fado Da Sina"
    INDEX 01 25:38:10
  TRACK 07 AUDIO
    TITLE "Zanguei-Me Com O Meu Amor"
    INDEX 01 29:10:60
  TRACK 08 AUDIO
    TITLE "As Sete Mulheres Do Minho"
    INDEX 01 32:26:10
  TRACK 09 AUDIO
    TITLE "Instrumental E ApresentaÃ§Ã£o"
    INDEX 01 37:59:72
  TRACK 10 AUDIO
    TITLE "Lusitana PaixÃ£o"
    INDEX 01 41:12:17
```
last track in the library is 4:15
last track in the play queus is 4:16

Anyway, durations in the play queue are correct, and I do not think it's a real issue a difference just for the last track of +/- 1 second in the library (I suppose due to some rounding)...

Since I am very interested in this matter (I am sketching a bash script to concatenate multiple flac files in a single flac + a cue sheet with the adjusted indexes), could I kindly ask you how do you proceed to calculate the durations? Thanks in advance.

Here is the way I made manual (spreadsheet) calculation:
- convert each INDEX to frames: `INDEX(i,ff) = mm*60*75 + ss*75 + ff`
- calculate each track duration (except for the last one) in frames by subtracting the current track INDEX to the next track INDEX: `TRACK(i,ff) = INDEX(i+1,ff) - INDEX(i,ff)`
- calculate the total duration of the flac file dividing the total samples by the sample rate:
`$ metaflac --show-total-samples --show-sample-rate audiocd.flac | tr '\n' ' ' | awk '{print "frames: " 75*$1/$2}' - `
(a better way for coding might be: <https://gist.github.com/lukasklein/8c474782ed66c7115e10904fecbed86a>)
- calculate the last track duration in frames by subtraction (total duration of the flac file minus the sum of previous tracks durations)
- convert all track duration from frames to seconds: `TRACK(i,ss) = TRACK(i,ff)/75`
- convert all track duration from seconds to mm:ss 
    mm: `TRACK(i,mm) = INT(TRACK(i,ss)/60` 
    ss: `TRACK(i,ss) = TRACK(i,ss) - TRACK(i,mm)*60` 

Regards

**Comment by CDrummond** [comment]
First of all  - the miscalculated last track. For this I now use the INDEX time of the penultimate track and subtract this from the total time (in seconds) that MPD informs me of. I'm guessing this total time in seconds is not 100% accurate - as CUE files support sub-second times. But alas, not much more I can do - I have no other info. Cantata does not parse audio files itself, so cannot know the exact duration. So, for me, this issue is now closed - the times are as accurate as they can be.

---

As to your question.  In the example CUE above you have:

```
FILE "audiocd.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Os Ã�ndios Da Meia Praia"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Se Voaras Mais Perto"
    INDEX 01 05:35:00
```

So TRACK 1's duration is `05:35:00-00:00:00` ie duration of track N is `INDEX N+1 - INDEX N`

Now the problem is the last track. As stated, Cantata does not parse audio files, so gets the total FLAC duration from MPD. And this is in seconds, so some accuracy is lost. But the same maths is used - e.g. `last track duration = total falc duration  - penultimate index`

For all bar the last track, I convert MM:SS:FF into seconds (with fractional part) - then do the subtraction. Songs are stored with whole second accuracy, so this is rounded to the nearest second.

**Comment by nousernouser** [comment]
Thanks for your response and clarification.
Thanks for the fixes.
Regards
