### ISSUE TITLE
2 small improvements

### ISSUE THREAD

**Issue by tollerm** [CDrummond/cantata#1253]
Hi,
Very nice music player! May I ask you to make a few changes/improvements?:
1. Last FM button is a little bit confusing for me. When the song is selected as
a "Love song" it is shown dimmed. I would expect the other way round: Full color
- selected as a "Love song", dimmed - not selected. 
2. In Smart playlists option it is impossible to input number larger than 99 in
"files added in last days" field.

**Comment by CDrummond** [comment]
1. When you 'love' a track, the button is disabled until the track is changed. Why would you still want it enabled? You have already 'loved' the track.

2. I forgot to add a defined limit, so I guess Qt chose 99. I've now set this to 10*365 = 10 years.

**Comment by tollerm** [comment]
1. I don't want the button to be enabled. I want a better indication for a track as a "loved" one in Cantata. For me it is a little bit confusing, because on the Last FM site a "loved" track is indicated by a full color "heart" sign while in Cantata this sign means that a track is not a "loved" track.
2. Thanks! 10 years is more than enough for "recent" :)

**Comment by CDrummond** [comment]
But Cantata does not know that a song has been loved. i.e. love track A, play track B, now play track A - love button would be re-enabled. Its disabled to stop you accidentally pressing the button twice. Now I could just leave the button the same colour, and ignore the repeated presses until the song has changed. But then you would have no indication that it was loved (whilst playing).

You seem to think the 'love' button shows you the loved status of a track. But it does not, it simply allows you to love a track. Once it has been loved, no point in allowing it to be loved again - until another song is played, and then that song again.

I guess what you would really like is for there to be a 'loved' indicator somewhere (probably in the toolbar, next to rating) - that would show any existing loved status. This /might/ be possible by querying last.fm when a track is played.

(Would be nice to have 'loved' as one of the smart playlist criteria too - but that would be quite a bit of work).

**Comment by tollerm** [comment]
Indeed, this is a reason for my (and may be other users as well) confusion. Because the indicator of a "love" song is the same as in the Last.fm site, it creates the wrong impression that Cantata shows the "loved" state. May be, it is better  to use a different icon to make a song "loved" to avoid this confusion.
Sure, it would be very nice to show "love" status and import "love" songs to playlists but it requires some work :)
