### ISSUE TITLE
Cantanta Doesn't Load Pre-Existing Playlists?

### ISSUE THREAD

**Issue by vtpoet** [CDrummond/cantata#1256]
Just tried Cantata for the first time and when loading my music library, Cantata appears to overlook all the playlists (m3u). I listen to Classical and have all the albums in respective playlists. No Linux music player that I'm aware of, including Cantata apparently(?), loads playlists (m3u) when loading a music library? This really mystifies me.

Wouldn't it make sense for Cantata to automatically load any playlists in ones music library?

**Comment by CDrummond** [comment]
Cantata is an MPD client - it gets its playlists from MPD. Any existing MPD playlists are displayed. MPD, however, does not store playlists within the music folder, but within a separate folder.

**Comment by vtpoet** [comment]
Hi C, just want to say first that I continue using Cantata, am enjoying it, and really do find it to be an aesthetically well-designed app. That said, none of your responses addressed my OP. My Playlists are m3u files, carried over from when I rescued all my stuff from itunes. I could store my playlists in different formats but that's besides the point. Wouldn't it make sense for Cantata to import any playlists the same way it imports m4a's, mp3's, FLAC and what have you? If you simply don't want to do it, then fine., but pointing out that Cantata is an MPD client is besides the point. I suppose maybe this should be a feature request? Anyway,I know what it's like to put your work out there for free. So, thank you.

**Comment by CDrummond** [comment]
Sorry, I dont think you understand how an MPD client works. Cantata does not list/import MP3/FLACS, etc. Cantata connects to MPD, and asks MPD to list the music collection. MPD then tells Cantata the details of all songs, etc. If your playlists are being ignored, its is MPD that is doing the ignoring and not informing clients of the listing.

Cantata is not the same as Clemtine, Amarok, etc. These apps scan your music files, playlists, etc themselves to build their list of music. Cantata does not. Cantata is simply a GUI front end for MPD. It is MPD that scans your collection,.
