### ISSUE TITLE
Playlist sort order changed with 2.3?

### ISSUE THREAD

**Issue by nommer** [CDrummond/cantata#1258]
Version 2.2 always sorted the tracks in the playlist according to the tracknumber, whereas 2.3 seems to sort albums with multiple artists by artist's name, reshuffling any "concert order" that may have been intended by the creators of the album:

![playlist](https://user-images.githubusercontent.com/8410145/39409761-b9ed9352-4ba1-11e8-8e7f-5906835003bf.jpg)
Is there some way to get the new, improved 2.3 to revert to the behaviour of 2.2?

**Comment by CDrummond** [comment]
Playlist? You mean playqueue. The order of the playqueue is determined by MPD. I assume you mean cantata added them in the wrong order? This would imply an issue with your tags. Perhaps some have musicbrainz tags, and others not?

**Comment by nommer** [comment]
Sorry, I do mean playqueue. I've been using (and loving!) Cantata for years, so was a bit puzzled as to why Cantata 2.3 is displaying the tracks of a multi-artist album correctly sorted (by track number) in Folders view, but when an album is selected and added to the playqueue with Cantata 2.3 tracks appear sorted first by artist's name, then by track number, as in the screenshot in my original post.
 
This is new with 2.3. I manually tag everything with the dogged consistency notoriously attributed to small minds, and haven't seen this behaviour until the current release. 

With the same album (and the same instance of mpd) Cantata. 2.2 does the expected (and, I would think, correct) thing:

![playqueue_cantata-2 2](https://user-images.githubusercontent.com/8410145/39413729-85babf78-4be3-11e8-8631-d830bca7dd71.jpg)

**Comment by CDrummond** [comment]
This is adding from the folders view onto the playqueue. Is this from the 'MPD virtual folders' ? Home folder? Root folder? When adding a folder from Home/Root cantata will sort the _files_ by their name (case insensitive).

I assume you are compiling the code yourself? If so, can you please edit line 745 in `mpd-interface/mpdparseutils.cpp` and change from:

```
    if (Loc_Browse==loc) {
        qSort(songs);
    }
```

to

```
    if (Loc_Browse==loc) {
        QList<Song> sngs;
        QList<Song> playlists;
        for (const auto &s: songs) {
            if (Song::Playlist==s.type) {
                playlists.append(s);
            } else {
                sngs.append(s);
            }
        }
        qSort(playlists);
        songs=sngs;
        songs+=playlists;
    }
```

...rebuild cantata. Then run the newly built version. (Make sure it is this new one, not the previous/installed version - as other have before!)

Does this resolve the issue?

**Comment by nommer** [comment]
It does, thanks so much! Cantata somehow manages to be the bee's knees AND the cat's pyjamas.
