### ISSUE TITLE
Issues with character encoding

### ISSUE THREAD

**Issue by SethosII** [CDrummond/cantata#1261]
I noticed some character encoding issues. Here is a screenshot:

![encoding](https://user-images.githubusercontent.com/4445745/39506837-6f0f4e98-4ddb-11e8-9608-82fb267f0e94.png)

As you can see the songtext isn't displayed correctly and there are replacement characters in the similar artists section. The songtext consists of greek characters and should look like this:

> Κλύθι θεά βασίλεια φαεσφόρε δία Σελήνη ταυροκέρως Μήνη νυκτιδρόμε ηεροφοίτι εννυχία δαιδούχε κόρη ευάστερε Μήνη αυξομένη και λειπομένη θήλυς τε και άρσην αυγάστειρα φίλιππε χρόνου μήτερ φερέκαρπε ηλεκτρίς βαρύθυμε καταυγάστειρα νυχία πανδερκής φιλάγρυπνε καλοίς άστροισι βρύουσα ησυχίηι χαίρουσα και ευφρόνηι ολβιομοίρωι λαμπετίη χαριδώτι τελεσφόρε νυκτός άγαλμα αστράρχη τανύπεπλη ελικοδρόμε πάνσοφε κούρη ελθέ μάκαιρα εύφρων ευάστερε φέγγεϊ τρισσώι λαμπομένη σώζουσα νέους ικέτας σέο κούρη

The greek characters in the artist and album information section from Wikipedia are displayed correctly so I wonder if this is an issue on the side of the data source or in cantata?

OS: Windows 10 1709
Cantata: 2.3.0 with german interface

**Comment by CDrummond** [comment]
Yeah, I can see this now. It initially displays OK, but Cantata caches a copy to disk. This disk copy has the mixed up text. So, the next time Cantata gets the info, it reads its cached copy, and you get what is shown above.

**Comment by CDrummond** [comment]
Fixed for 2.3.1
