### ISSUE TITLE
Cantata as standalone player

### ISSUE THREAD

**Issue by majkinetor** [CDrummond/cantata#1262]
During my home network restructuring I had a few months without MPD and realized that I miss Cantata more then mpd itself, now that I can't use it locally to play music which brings me to question.

Are you 100% against adding local playing capabilities (either via integration with player such as  mpv or  even mpd or using some common audio library internally ) ? Few of the features of Cantata are non-existent on other players (such as dynamic playlists, so far the only other player I know having similar option is [Clementine](https://www.clementine-player.org))  and minimal interface, performance, portability etc all are on much better level IMO then alternatives. Its a damn shame this can be used only with MPD.

I searched the issues and found little mention on it. What is your stance on this ?

Related, one of the tickets I found, #266, was about packaging with mpd, most definitely for the same reason.  This could be made possible on package level, by creating separate cantata+mpd package. I can make this on Chocolatey for Windows, basically a new pakcage referencing both cantata and mpd as dependencies and setting up cantata to use local mpd.

**Comment by Thaodan** [comment]
The issue you describe is mostly a packaging thing. I don't think that's something about cantata or is there something wrong about local mpd setup?
On systems with a package mana you usually end up installing these dependencies

**Comment by majkinetor** [comment]
It may or may not be Cantata thing.

mpd is different thing then local play.

For example, with mpd you reference virtual fs, on local play you reference local fs (for example with playlists). Tags are stored in local fs rather on remote db etc.

You could have other features locally way more easily, for instance integration with `youtube-dl` to provide more streaming capabilities.

**Comment by CDrummond** [comment]
Cantata can be configured to start/stop a per-user instance of MPD. In this way it can act like most other music players.

However, I have no intention of making cantata playback the music itself. Why would I want to? MPD handles stuff like replaygain, gapless, etc. Having to do all that work in Cantata just so that MPD is not required is just not worth the effort.

**Comment by Thaodan** [comment]
@majkinetor what you describe is rather an issue with the inconsistency of mpd. I
Fil a bug there?

**Comment by majkinetor** [comment]
> Having to do all that work in Cantata just so that MPD is not required is just not worth the effort.

Fair enough. I will experiment a bit with local mpd then. Thanks
