### ISSUE TITLE
Searching doesn't return all results ?

### ISSUE THREAD

**Issue by trmdi** [CDrummond/cantata#1264]
Look at these pictures, only 1 song is found ?

![image](https://user-images.githubusercontent.com/11857205/39558324-de4da28c-4eb7-11e8-9e90-d88777b02836.png)
![image](https://user-images.githubusercontent.com/11857205/39558336-f2e5410a-4eb7-11e8-8578-6bc11e8753a6.png)

**Comment by CDrummond** [comment]
OK. I see the issue now. Search on 'any' with MPD does not search filenames/paths - it only searches tags. I'll update Cantata to work-around this.

**Comment by CDrummond** [comment]
Should now be fixed - can you update and confirm?

**Comment by trmdi** [comment]
Works perfectly !

**Comment by CDrummond** [comment]
Thanks for the confirmation.
