### ISSUE TITLE
cannot register existing type 'GdkDisplayManager'

### ISSUE THREAD

**Issue by mokman** [CDrummond/cantata#1266]
hello and thanks for cantata, i use it a long time and love it!
since version 2.3 i cannot run cantata, it tells me to open up a issue here with the following:

/usr/lib/libc.so.6 : ()+0x34f80
/usr/lib/libgdk-x11-2.0.so.0 : gdk_display_open()+0x62
/usr/lib/libgdk-x11-2.0.so.0 : gdk_display_open_default_libgtk_only()+0x52
/usr/lib/libgtk-x11-2.0.so.0 : gtk_init()+0x13
/usr/lib/qt/plugins/styles/libqgtk2style.so : ()+0x24bcb
/usr/lib/qt/plugins/styles/libqgtk2style.so : ()+0x2638e
/usr/lib/libQt5Widgets.so.5 : QStyleFactory::create(QString const&)+0x133
/usr/lib/libQt5Widgets.so.5 : QApplication::setStyle(QString const&)+0x7
cantata : Application::init()+0x5b
cantata : main()+0x1d5b
/usr/lib/libc.so.6 : __libc_start_main()+0xe7
cantata : _start()+0x2a

**Comment by CDrummond** [comment]
This is an issue with the 'gtk2' Qt5 style that you are using. I've installed this, and **all** Qt5 applications crash when using it.
