### ISSUE TITLE
Feature request: select server when starting up

### ISSUE THREAD

**Issue by kalsan** [CDrummond/cantata#1268]
Depending on where I am with my laptop, there are different MPD servers around:

- At home it's 192.168.1.123
- At my parents' it's 192.168.2.123
- Every where else I use earphones and therefore it's 127.0.0.1

Every time I switch places, I need to go to the cantata settings and change the server. Since the local server is always available, server autodetection on startup would not help.

It would be great to have a command line option `cantata --server='home'` allowing to start up cantata with the right server. This way I could map keyboard shortcuts to the different locations.

**Comment by CDrummond** [comment]
Reasonable idea.

For now, you could just write a bash script to change `currentConnection` in `~/.config/cantata/cantata.conf` before starting Cantata.

**Comment by kalsan** [comment]
A switch like the one you proposed is my current workaround. Still, a command line option would be much appreciated! :-)

**Comment by kalsan** [comment]
Works perfectly. Thanks a lot, much appreciated!
