### ISSUE TITLE
Double-click to play from playlist view

### ISSUE THREAD

**Issue by ReaperX** [CDrummond/cantata#1270]
When I want to prune a large playlist, I go through each file, play it, and then decide whether to keep or delete it. Cantata does not currently allow double-click to play in the Playlists view, the way it does in the Play Queue. CTRL-R is a convenient shortcut, but still, it would be nice to be able to just play via double-click.

**Comment by CDrummond** [comment]
If you mean double click to play the whole playlist - then no, this is not supported (and is too much hassle for now).

However, you **can** play songs from the playlist by double clicking. Set `Enforce single-click activation of  items` in `Preferences / Interface / General` This is not required for all styles, but is for some (e.g. kvantum).
