### ISSUE TITLE
Identifying and removing invalid files

### ISSUE THREAD

**Issue by ReaperX** [CDrummond/cantata#1271]
When you change the storage location of files, the corresponding files in playlists become invalid.  When you load a corresponding playlist, cantata shows an MPD error "No such directory", but it does not say which one the offending file is. 

Most of the time, one can identify missing files in playlists by the missing icon, but that only works if all files have a built-in icon. 

Could you add a right-click option to the playlist context menu to "remove invalid entries" or such?

**Comment by CDrummond** [comment]
Implemented in 2.4 branch
