### ISSUE TITLE
cantata crashes when using qt5ct under compiz to configure gui

### ISSUE THREAD

**Issue by psykotik1** [CDrummond/cantata#1272]
traceback:

 /usr/lib/libc.so.6 : ()+0x368f0
  /usr/lib/libQt5Core.so.5 : QObject::property(char const*) const+0x1a
  cantata : MainWindow::controlView(bool)+0x3d
  /usr/lib/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0xdd2
  /usr/lib/libQt5Widgets.so.5 : QMainWindow::event(QEvent*)+0x61
  /usr/lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x9c
  /usr/lib/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x2a6
  /usr/lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x120
  /usr/lib/libQt5Widgets.so.5 : QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool)+0x1ad
  /usr/lib/libQt5Widgets.so.5 : QWidgetPrivate::show_helper()+0x34
  /usr/lib/libQt5Widgets.so.5 : QWidget::setVisible(bool)+0x1f9
  cantata : MainWindow::MainWindow(QWidget*)+0x16d
  cantata : main()+0x1d0e
  /usr/lib/libc.so.6 : __libc_start_main()+0xeb
  cantata : _start()+0x2a

**Comment by CDrummond** [comment]
Which version of Cantata is this? Can you try git/master (which will be 2.3.1)?

**Comment by psykotik1** [comment]
version 2.2.0.r38.g2945e2da-1 builded from arch user repository, cantata from the official repos works fine, will try the new version, 2.3.1

**Comment by Thaodan** [comment]
I build from git yesterday (arch user too) and it works fine for me.
My build lies here if you want to use it:
https://thaodan.de/home/bidar/home-thaodan/x86_64

**Comment by CDrummond** [comment]
What? Why report an issue with 2.2.0 if the released 2.3.0 works!!

**Comment by psykotik1** [comment]
still crashing with version 2.3.1

**Comment by Thaodan** [comment]
Tried my build too?

**Comment by CDrummond** [comment]
Please try git/master again.

**Comment by Thaodan** [comment]
Rebuild my version from latest master, grab it if needed.

**Comment by Thaodan** [comment]
rebuilded an hour ago.

**Comment by psykotik1** [comment]
works now
