### ISSUE TITLE
Hearth icon cropped

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1273]
As the title says the new hearth icon is a bit cropped in the last release.
A screenshot to show the issue is attached.
<img width="991" alt="screenshot_20180509_213809" src="https://user-images.githubusercontent.com/1747359/39835795-a0088996-53d1-11e8-947e-e88f6d12ec96.png">

**Comment by CDrummond** [comment]
Not actually released yet :-) But, thanks for reporting before I make the release. Can you checkout git/master, and try again?

What style are you using? And what font + size?

**Comment by Thaodan** [comment]
Breeze.
Fontsize 10
DPI 144

**Comment by Thaodan** [comment]
Smaller in comparsion, but looks better now.

**Comment by CDrummond** [comment]
Well, ifs OK - I'll close.
