### ISSUE TITLE
FR: Permanent Cover art

### ISSUE THREAD

**Issue by gerroon** [CDrummond/cantata#1274]
Hi

It woud be nice if this app can show a permanent individual resizable cover art window that stays on top, even when the actual app is in the background.

thanks

**Comment by CDrummond** [comment]
Sorry, doesn't interest me. Why would I want that, and the app not in focus.

**Comment by gerroon** [comment]
Well maybe I do not  want app to cover the screen and I still would like to see the cover?

**Comment by CDrummond** [comment]
Show 'info' view, configure it for single pane, show album pane, and set album cover to stretch. This will still show the main toolbar, but is pretty close to what you are asking for.
