### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by nazar-pc** [CDrummond/cantata#1276]
Latest Ubuntu version 18.04 shipped with Font Awesome 5 and icons are not showing correctly just like in #903:
![2018-05-13 06-29-49](https://user-images.githubusercontent.com/928965/39963556-2c9c1218-5677-11e8-9405-99554aafd2ea.png)

Maybe you can consider bundling icons with app itself or use SVG icons from Font Awesome directly or something like that?

**Comment by CDrummond** [comment]
The font **IS** bundled with Cantata - it should be in `/usr/share/cantata/fonts` I'm on 18.04, and Cantata is working fine.

**Comment by CDrummond** [comment]
On my system `fonts-font-awesome` is 4.7

I've modified the name of Cantata's copy of font-awesome to `Cantata-FontAwesome`, so Cantata should only be loading its own version.

Can you checkout git/master and confirm if this fixes the issue for you?

**Comment by nazar-pc** [comment]
Doesn't seem to change anything unfortunately. I think font name is included in font file itself, so it doesn't really matter how you name font file.

This seems to be 18.10's issue indeed, from changelog:
```
fonts-font-awesome (5.0.10-1) unstable; urgency=medium

  * Fix the upstream URL in watch file.
  * New upstream release.
    Closes: bug#895947. Thanks to Daniel Bauman.
  * debian/control:
    + Use new fonts-team mailing list address in Maintainers field.
    + Mark package compliance with Debian Policy 4.1.4.
    + Use Salsa URL in Vcs-* fields.
  * debian/copyright:
    + Update the copyright information as per new paths.
    + Extend my copyright period on debian folder.
  * debian/install updated to use new paths from new release.
  * Add NEWS.Debian mentioning changes made by upstream which might be
    intrusive for existing users.
  * Add lintian-overrides for "source-is-missing", js files shipped by
    package are actual source and not minified versions as claimed by
    lintian.

 -- Vasudev Kamath <vasudev@copyninja.info>  Sat, 12 May 2018 14:27:27 +0530
```

**Comment by CDrummond** [comment]
I changed the name **within** the font file, not just the filename. Look at the TTF in GNOME's (or KDE's) font-viewer and you should see its now named `Cantata-FontAwesome`

**Comment by nazar-pc** [comment]
If I didn't install it globally, just `make && ./cantata`, should it still work properly?

**Comment by CDrummond** [comment]
No, you **must** install it - Cantata looks for its TTF file within the **install** folder.

**Comment by CDrummond** [comment]
Try passing `-DENABLE_REMOTE_DEVICES=OFF` to cmake. The remote device code installs a system dbus service, so needs to place a file in `/etc`

**Comment by nazar-pc** [comment]
I'm having difficulty with `/usr`, not `/etc`:
```
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:49 (file):
  file cannot create directory: /usr/local/share/cantata/scripts.  Maybe need
  administrative privileges.


Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by nazar-pc** [comment]
UPD: Cleaned `build` directory, recompiled and now it seems to work properly:
![2018-05-13 13-41-00](https://user-images.githubusercontent.com/928965/39966363-4ac1800c-56b3-11e8-89a2-7afbcf125ac3.png)

I think the issue is solved, thanks for quick fix!

I'll submit an issue on launchpad for cantata package in Ubuntu to drop dependency on `fonts-font-awesome`

**Comment by CDrummond** [comment]
Glad its now resolved. Odd that font-awesome 5 should break older releases. And, as Cantata has always shipped its own version, there has never been a need for a dependency.

**Comment by nazar-pc** [comment]
Apparently Font Awesome 5 has different code points for icons. Vote for issue linked above if not difficult.
