### ISSUE TITLE
Icon theme "cantata" not found

### ISSUE THREAD

**Issue by fabastrid** [CDrummond/cantata#1277]
When I start the app, it doen't open.
If I kill it and start from terminal, I receive the "Icon theme "cantata" not found" warning and cantata doesn't open.
On Antergos Arch Linux) KDE 5.12.5, Qt. 5.10.1.

**Comment by CDrummond** [comment]
Ignore this warning message - not sure why it happens, but the icons are still found and used. This will **not** be the reason its failing to start. As to why its not starting for you, no idea - must be an issue on your system.

**Comment by CDrummond** [comment]
Again, no idea why its not starting from you. Not much I can do to help.

No longer using own icon theme - so this warning will now not happen.

**Comment by fabastrid** [comment]
Thank you for helping.
I love cantata.

Il lun 14 mag 2018, 23:25 CraigD <notifications@github.com> ha scritto:
