### ISSUE TITLE
"Center on current track" and "Save as" missing when cantata is autostarted from saved session in Plasma (maybe before mpd is started)

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1279]
I have a standalone mpd configuration and Cantata is connected to that. My mpd server is launched by systemd when the user logs in.
My KDE Plasma is set to save the session at logout and restore it at login. Usually, I leave Cantata open but minimized in the notification area, when I'm logging out, so it will be reloaded in the same state at login. When that happens, two buttons are missing in the bottom toolbar: the one to center the playlist on the current playing track and the one to save the playlist.
If I quit Cantata and open it again, they appear.

I can reproduce it anytime even in this way:
- Open Cantata, set it to minimize in the notification area and to restore the previous state when started.
- Close Cantata, so it will be put in the notification area as icon
- Stop mpd service (in my arch linux config: systemctl --user stop mpd.service)
- Quit cantata by clicking on its icon the notification area and selecting Exit from the menu.
- Launch Cantata. It will compain about not being able to connect to mpd. You will also see the two buttons missing.
- Start mpd service again. Cantata will connect to it, but the buttons will still be missing.
- Quit and restart Cantata. The buttons will appear.

![screenshot_20180516_202553](https://user-images.githubusercontent.com/2348771/40137037-c2ff56b4-5949-11e8-824e-e711cdb17061.png)
![screenshot_20180516_202611](https://user-images.githubusercontent.com/2348771/40137043-c5870d00-5949-11e8-8c44-b7f70717ca74.png)

**Comment by CDrummond** [comment]
Don't have plasma installed, so cannot test. However, I'm guessing this is the code to adapt the shown widgets due to window size that is failing. I've udated the code so that these are configured when the window is shown. Can you update git/master (which will be 2.3.1) and see if this fixes the issue?

**Comment by CDrummond** [comment]
Thanks for the confirmation.

**Comment by CDrummond** [comment]
Ah! Now the're not showing at startup for me!!!

**Comment by Tichy** [comment]
That's quite strange! O_o
