### ISSUE TITLE
Request: monochrome tray icon

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1285]
![screenshot_20180519_134639](https://user-images.githubusercontent.com/2348771/40268302-32565f12-5b6b-11e8-93cf-b6e788bc240e.png)

The old monochrome icon looked better on the plasma notification area, because it was consistent wit the other ones. Is it possible to have it back? As an option if not as default choice?

**Comment by CDrummond** [comment]
Cantata, as of 2.3.1, no longer supplies its own icon theme. Therefore, tray icons need to be part of the theme. Sorry, but I can't supply icons for all themes.
