### ISSUE TITLE
Add genius.com as lyrics provider

### ISSUE THREAD

**Issue by aqua36** [CDrummond/cantata#1286]
From my experience genius.com provides much more accurate lyrics in a lot of cases so I would like it to be included as a lyrics provider.
I tried to do this myself but stopped half way because of my limited (practicaly non-existant) understanding of html.
I found an article that describes how to scrape lyrics from genius with python. The code for that is:
```python
from bs4 import BeautifulSoup
import requests
URL = 'https://genius.com/ARTIST-TITLE-lyrics'
page = requests.get(URL)    
html = BeautifulSoup(page.text, "html.parser")
lyrics = html.find("div", class_="lyrics").get_text()
```

I then tried to modify the lyrics_providers.xml file. What I came up with is this:
```xml
<provider name="genius.com" charset="utf-8" url="https://www.genius.com/{artist}-{title}-lyrics">
      <urlFormat replace="_@!;\/&quot;'()[]" with=""/>
      <urlFormat replace=" " with="-"/>
      <urlFormat replace="ä" with="a"/>
      <urlFormat replace="ö" with="o"/>
      <urlFormat replace="ū" with="u"/>
      <extract>
          <item tag="&lt;div class=&quot;lyrics&quot;&gt;"/>
      </extract>
</provider>
```
This works fine(and even catches some edge cases like german letters) but it has a major fault. The class "lyrics" has also quite a lot of html code along with the lyrics. The python code above gets rid of that with the function ``get_text()``. From looking at the rest of lyrics_providers.xml I assume that an ``<exclude>`` field is needed but I cannot do that myself with my current level of knowledge, so I would like some help with this

**Comment by CDrummond** [comment]
I've added this now, seems to work for the quick test case I used. Can you update and confirm?

**Comment by aqua36** [comment]
Works fine for me too, thank you!

PS: Is it possible to place a regex in the <urlFormat replace...> ?
There are two cases where that could be useful that I can think of now, removing "[feat. ARTISTNAME]"or"(feat. ARTISTNAME)" from the end of songnames and replacing " / " with a "-"
A simple yes or no answer will suffice, and if it's positive I'll look into it myself

**Comment by CDrummond** [comment]
urlFormat is treated as a regex - Cantata prefixes this with `[` and append `]`. So, don't think it will work the way you want.

However, in `song.cpp` there is a `basicArtist()` function that is intended to remove these `featuring` artists. Is this not working for you?

**Comment by CDrummond** [comment]
Yeah, adding a pull request to clementine would be a great idea. As stated, this XML file (and its parsing code) originates from there.

---

I've updated the code to remove these from the artist too.

Is this now working for you? Shall I close this?

**Comment by aqua36** [comment]
works correctly, made another pr #1288 because I didn't take care of comma and period chars

**Comment by aqua36** [comment]
>  **works correctly**, made another pr #1288 because I didn't take care of comma and period chars
I already answered to that :), it works exactly as I wanted it. With
