### ISSUE TITLE
Request: Please add an option to disable all the "are you sure?" pop ups in the Podcasts section

### ISSUE THREAD

**Issue by chrlsnchrg** [CDrummond/cantata#1289]
Having to constantly click the "yes, I'm sure I'm sure" pop-ups for standard actions (deleting downloaded data, marking podcasts as listened etc.) in the podcast plugin is annoying. I understand many users feel that they need their hands held through the process but I personally have grown to hate pop-ups. Please add the ability to turn them off. Deleting a podcast isn't like deleting a song etc, it can always easily be redownloaded or marked as unlistened etc etc.

**Comment by CDrummond** [comment]
Some prompts removed, not all, but some. Not going to add an option for this. Perhaps in future a "Don't ask again", perhaps...
