### ISSUE TITLE
Cantata hangs with QT_QPA_PLATFORMTHEME=qt5ct but cantata --platformtheme qt5ct works just fine

### ISSUE THREAD

**Issue by chrlsnchrg** [CDrummond/cantata#1291]
Build type: Arch Linux package 2.3.0-2 and git clone as of noon yesterday

I upgraded my QT version from the 5.10.1-8 version to 5.11.0-1 version and cantata stopped working.
When I start up cantata I just get this pattern repeated in the error logs:

```
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
```

`Empty filename passed to function`
^ this line repeats about a thousand times and then stops ^

```
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::save: Painter not active
QPainter::save: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::save: Painter not active
QPainter::save: Painter not active
```

^ these lines then start and repeat without end ^

The Cantata window doesn't draw. A quick search online for similar error logs to leads me to believe there was a minor update in how QT is used and something is leading to something not being drawn.

When I delete the .config/cantata/cantata.config file, and start a new setup etc. Cantata strangely enough opens and works fine the first run if I tell it to use a "Basic single user setup" but fails to draw the window and prints the same error message the _second_ time I open the newly-configured instance. Telling it to use a "Standard multi-user/server setup" yields the same error messages and no window the first time. I've connected to the mpd server on my machine just fine with gmpc so I don't think it's an mpd-side issue.

**Comment by padertux** [comment]
Can not reproduce this. Tried Arch Linux package 2.3.0-2 and git clone (45aace) with Qt 5.11.0-1. Both worked as expected.

**Comment by chrlsnchrg** [comment]
Do you have a multiple monitor setup? Some people's comments seemed to have implied they only got this kind of an error with multiple monitors. I'm using i3 so there are multiple "virtual" monitors.

**Comment by chrlsnchrg** [comment]
Ok I seem to have made progress on this issue. As I use a WM/DM other than the KDE environment, I use the "qt5ct" plugin to allow QT-based applications all the normal bells and whistles as is recommenced on the [arch wiki](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma). The issue seems to be either in the working of the plugin or how cantata interacts with it, as when I run `QT_QPA_PLATFORMTHEME="" cantata`, cantata works just fine. Even strangely enough, when I unset the envornment variable "QT_QPA_PLATFORMTHEME" (which tells applications to run qt5ct to give them their extra bells and whistles) and then run `cantata --platformtheme qt5ct`, which tells cantata to use "qt5ct" as is plugin and _should_ have the exact same functionality as `QT_QPA_PLATFORMTHEME="qt5ct" cantata`, cantata runs just fine. As my other programs that use qt5ct play with it just fine, I'm still convinced this is a cantata bug. I've updated the title of the thread to reflect this new info.

**Comment by CDrummond** [comment]
Cantata has a workaround if `QT_QPA_PLATFORMTHEME=qt5ct` due to the fact that qt5ct sets its palette after a window is shown. Cantata does not handle palette changes, so if `QT_QPA_PLATFORMTHEME=qt5ct` cantata initialises the main window after a slight delay. This is quite a hacky work-around, and appears to break things for you.

If you use `cantata --platformtheme qt5ct` - are the colours OK? Even for dark themes?

**Comment by chrlsnchrg** [comment]
Yes, I can confirm `QT_QPA_PLATFORMTHEME="" cantata --platformtheme qt5ct` works great, even with dark themes. Perhaps we should ask qt5ct to set the palette before the window is shown?

**Comment by CDrummond** [comment]
Well, if things are OK - perhaps it has already been fixed? The real fix (for palette issues) would be for Cantata to respect palette changes - but that's more work than I have time for.

Please checkout git/master (for 2.3.1) - is it OK now?

**Comment by chrlsnchrg** [comment]
Can confirm the latest git version works great with `QT_QPA_PLATFORMTHEME="" ./cantata --platformtheme qt5ct`. 

I'm marking the problem as fixed and will contact the developers of qt5ct - in my opinion _requiring_ programs to support post-initialization palette changes is a bit ridiculous. 

Thank you for you help CDrummond and padertux.
