### ISSUE TITLE
No files appear in the library

### ISSUE THREAD

**Issue by foxy123** [CDrummond/cantata#1292]
Got Cantata installed on Ubuntu 18.04. In the File view I can see all my music library but the Library tab is empty. I've got all my music files tagged.

**Comment by CDrummond** [comment]
Which version of Cantata? Which fileview? MPD folder list, home folder, root folder? How does Cantata connect to MPD???

Cantata gets its listing from MPD, so if no music is shown - its likely you have not configured MPD correctly.

**Comment by CDrummond** [comment]
Asked for more info, none given. Library view is working as expected for me, and others.
