### ISSUE TITLE
Slight issue with saved filenames of downloaded podcasts, leads to defaulting back to streams

### ISSUE THREAD

**Issue by chrlsnchrg** [CDrummond/cantata#1293]
The podcast plugin, when asked to download a stream, often keeps the additional information added at the end of urls with a '?' to give additional information to a server when a link is followed. For example, when asked to download Planet Money episode 843, the name-on-disk of the file should be `20180525_pmoney_pmpod843.mp3` but instead was saved as `20180525_pmoney_pmpod843.mp3?orgId=1&d=1772&p=510289&story=613720973&t=podcast&e=613720973&ft=pod&f=510289`. Thus, the podcast plugin "thinks" the podcast has been downloaded (as it has) but mpd never "finds" the actual file and reverts to the stream, which causes skipping, pauses, interruptions etc. as streams are inferior. 

This is more the fault of poor configuration on the part of people publishing podcasts, but as they're, almost without exception, "creatives" rather "technicals", almost all podcasts are configured such that the `?destid=blahblahblah` etc are published with the urls that let one download the sound file.

**Comment by CDrummond** [comment]
What was the podcast? Or it's RSS URL? Then I can test any solution.

**Comment by chrlsnchrg** [comment]
On further investigation, it seems that __ALL__ downloaded podcasts are defaulting to the stream instead of the local file, including podcast episodes that are part of the MPD library. This isn't really that much of an issue for those that are part of the library as the proper file can just be played from the "Library" view, but unfortunately MPD doesn't recognize files that end in "?info=value" etc. as being music files and doesn't add them to the library.

The podcasts I've noticed it does this on are the following:
Planet Money
Beef and Dairy Network
Revolutions

I've also noticed that the following podcasts DON'T have the "?info=value" at the ends of their filenames (instead end in .mp3 .wav etc):
This American Life
Shakespeare on 3

**Comment by CDrummond** [comment]
For the non `?=xxx` case, can you try git/master? I noticed (a few days ago) that Podcasts were downloaded, but the downloaded track  was never played.

**Comment by chrlsnchrg** [comment]
Getting the following error message: `Failed to load. MPD can only play local files if connected via a local socket.` when trying to play a downloaded podcast from the latest master branch in the "Podcasts" view, including from "Shakespeare on 3" and "This American Life". The filenames are being saved properly though, and thus at least showing in the "Library" view and the files playable from there.

**Comment by CDrummond** [comment]
You need to enable "Local file playback: Via in-built HTTP server" in the collection settings.

**Comment by chrlsnchrg** [comment]
Can confirm, both bugs have been squashed in the most recent version of master. I'm closing the thread. 

Thanks CDrummond!
