### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by BurekzFinezt** [CDrummond/cantata#1297]
I don't know where is the best place to ask this but, it looks like soundcloud search inside of cantata doesn't give full results and displays just few tracks in the search query. How can  this be configured or fixed?

**Comment by BurekzFinezt** [comment]
Maybe a 100 or so, but yeah, that would be awesome, I would really like too see bigger search results. Thanks for responding so fast!

**Comment by CDrummond** [comment]
Re-opening for now, 250 seems to be to much - as no results are returned! Will try other values...
