### ISSUE TITLE
[BUG] Cantata doesn't show pre-existing mpd playlists on first start

### ISSUE THREAD

**Issue by zovt** [CDrummond/cantata#1299]
MPD config:
```
music_directory "~/m/files/Music"
db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/mpd.pid"
state_file "~/.config/mpd/mpd.state"
playlist_directory "~/m/files/Playlists"
```
(where directory `m` is mounted via sshfs)
There are existing MPD playlists (created via NCMPCPP) in the playlist dir, which ncmpcpp shows properly

This happens on both Linux and macOS

Steps to reproduce:
Open cantata after fresh install
Navigate to playlists
See no playlists, even though playlists exist

Workaround:
Create a random playlist in Cantata
Existing playlists appear

Let me know if you need any more information

**Comment by CDrummond** [comment]
Ah, you are correct! Will fix for 2.3.1
