### ISSUE TITLE
Cantata 2.3.0 gives QWidget/QPainter errors on Manjaro Linux with Qt 5.11

### ISSUE THREAD

**Issue by 111MilesToGo** [CDrummond/cantata#1301]
After my Manjaro Linux got updated to incorporate Qt 5.11 instead of 5.10 (their 2018-06-01 Stable Update), Cantata 2.3.0 does no longer function properly. Calling Cantata from a terminal yields the following error messages (abridged, it goes on and on):

`cantata
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::fillPath: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::save: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawRects: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::save: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
`

I am sure it worked at the time when Manjaro had Qt 5.10. I am of course not sure at all whether the strange behavior is due to a failed implementation of Qt 5.11 in Manjaro, a failed Cantata in the Manjaro repository, or an issue with Qt 5.11 in Cantata itself. Thus I am submitting this issue report here.

I have posted this issue on the Manjaro Forum and asked for help, but to no avail yet. Links:
[Post 1](https://forum.manjaro.org/t/plasma-shell-crashed-after-update-2018-06-01-stable/48803/6)
[Post 2](https://forum.manjaro.org/t/plasma-shell-crashed-after-update-2018-06-01-stable/48803/4)
[Post 3](https://forum.manjaro.org/t/plasma-shell-crashed-after-update-2018-06-01-stable/48803/9)
[Post 4](https://forum.manjaro.org/t/plasma-shell-crashed-after-update-2018-06-01-stable/48803/10)
[Post 5](https://forum.manjaro.org/t/plasma-shell-crashed-after-update-2018-06-01-stable/48803/11)
These posts describe what I see. In short, Cantata's main window is not displayed, it is just a shadowy outline. But the tooltips show up for action buttons and songs in the playlist, I can hit those places on the "empty/transparent" window and invoke menus as well as play songs.

I would be very grateful for feedback regarding the potential source of the issue.

Manjaro is a Linux distro based on Arch Linux.

BTW: A heart-felt THANK YOU for Cantata, my go-to client for MPD !!!

Please excuse me for not having figured out yet how GitHub wants code inserts to be formatted - the paste was copied from the Linux terminal and looked okay during "Write" here.

**Comment by CDrummond** [comment]
Looks the same as https://github.com/CDrummond/cantata/issues/1291  Can you update to git/master (which will be 2.3.1), and see if this fixes the issue?

If you can't update please try launching Cantata from the commandline as follows:

```
QT_QPA_PLATFORMTHEME=  cantata
```

Note there is a space after `=` and before `cantata`

Does this resolve the issue? If so, then it is fixed for 2.3.1

**Comment by 111MilesToGo** [comment]
Since I am not adept enough to follow route 1 (compile myself), I follow route 2 (QT_QPA_PLATFORMTHEME=  cantata). Yes, this does resolve the issue, Cantata's main window display is back to normal.

Thanks, Craig, for responding so quickly, great service for a great program. Will see how fast 2.3.1 propagates to Arch Linux and then to Manjaro (Xfce) Stable Branch.

**Comment by CDrummond** [comment]
Thanks for the confirmation.

I've not released 2.3.1 yet - was waiting to close all known bugs. Will try to get the release out this week.
