### ISSUE TITLE
Add easy "Like" UI

### ISSUE THREAD

**Issue by glensc** [CDrummond/cantata#1303]
In GMPC I pretty much liked the :heart: button, easily to add current song to "Favourites" stored playlist.

Please add similar functionality to Cantata as well.

thanks

**Comment by rn2208** [comment]
A five-star system with a half-star step is much better at this task.

**Comment by glensc** [comment]
and how do you get playlist out of star system?

**Comment by CDrummond** [comment]
You could use a smart playlist, and order by rating. which, to be host, is probably a better idea.

I'm not to sure about adding yet another 'favourites' feature; as there is already ratings and last.fm love

**Comment by CDrummond** [comment]
Actually, I'm not in favour of adding yet another 'favourite' feature. As stated, use a smart playlist.
