### ISSUE TITLE
Missing "Organize files" feature functionality

### ISSUE THREAD

**Issue by artyom-smushkov** [CDrummond/cantata#1305]
There are a couple of issues in "Organize files" feature that appear when Cantata moves music files to new directory:

1. Cover arts saved in directory with music files aren't moved to new directory
2. For hybrid wavpack *.wvc correction files are ignored.

For example, when I try to organize files that are named like this:
```
album
|--01.wv
|--01.wvc
|--02.wv
|--02.wvc
`--cover.jpg
```
Instead of this something like this:
```
2000 - Album
|--01 - First Track.wv
|--01 - First Track.wvc
|--02 - Second Track.wv
|--02 - Second Track.wvc
`--cover.jpg
```
I'm getting this:
```
album
|--01.wvc
|--02.wvc
`--cover.jpg
2000 - Album
|--01 - First Track.wv
`--02 - Second Track.wv
```

**Comment by CDrummond** [comment]
Never heard of these files before. What I propose is:

1. When renaming a music file, if there exists another file with the same basename (but different extension), then also rename this. This should fix the .wvc case
2. After moving all files, if destination folder is different to source, move any remaining files. This should fix the moving of covers.

**Comment by CDrummond** [comment]
The code in master (for 2.3.2) will now resolve your issues. I've added the moving of the similarly named files. Cover moving was already implemented, but as a non-standard file was found no files were moved (apart from the renamed files).

I'm debating moving all other files or not. Hence not closing this yet.
