### ISSUE TITLE
Blank tranparent screen on Manjaro XFCE

### ISSUE THREAD

**Issue by TheScrawl** [CDrummond/cantata#1307]
I was trying to install catata, however when I try to use it, i get a blank window that seems to show a clone of whatever it was opened over top of (sorry for the bad explaination [heres a screenshot](https://imgur.com/jZPDrtY))

Im running XFCE on Manjaro, I installed cantata using pacaur. 

If theres any other questions that you have to help figure out whats going on I'd be glad to answer.

Thanks.

**Comment by CDrummond** [comment]
Which version of Cantata? 2.3.0? This looks a lot like https://github.com/CDrummond/cantata/issues/1301

**Comment by TheScrawl** [comment]
uh I this is awkward, but I just broke my manjaro install and am in the process of reinstalling

I just installed whatever installed when I ran `pacaur -S cantata`

sorry for the inconvenience
