### ISSUE TITLE
[Feature request] Mixcloud support

### ISSUE THREAD

**Issue by kolya-ay** [CDrummond/cantata#1309]
It seems that Mixcloud has [pretty straightforward API](https://www.mixcloud.com/developers/) which can be utilized to interact with. Actually, this is the only feature which stops me from using Cantata exclusively.   I have used Cantata as a simple MPD client long time ago and didn't know how far it was involved since then. Awesome work!

BTW, Are any "social" features planned (e.g. favorite Soundcloud/Mixcloud tracks, etc)?

**Comment by CDrummond** [comment]
Never heard of MixCloud. I have no problem with adding support. However, then API you pointed to mentions that it cannot be used to obtain the stream URLs. If this is correct, then I'm not sure how to obtain the streams to pass to MPD.

**Comment by CDrummond** [comment]
Closing. API does not provide access to stream URLs, so mot much use. If you have a (legal) way to access these, then I'll reconsider.
