### ISSUE TITLE
No systray icon under GNOME dispite Topicons gnome shell extension

### ISSUE THREAD

**Issue by vasyugan** [CDrummond/cantata#1311]
As said in the subject line. What is strange is that I can't seem to find the setting in the preferences, where one could toggle the systray icon. Is it not there because I am running GNOME?

**Comment by CDrummond** [comment]
Cantata uses 'status notifier item' - and sys tray support is only enabled if the "org.kde.StatusNotifierWatcher" service is registered.

This is working for me with Ubuntu's modified GNOME session.
