### ISSUE TITLE
"Add Local Files" to play queue not available

### ISSUE THREAD

**Issue by moretocome** [CDrummond/cantata#1312]
First of all thanks for a great MPD client! :)

Forgive me if this is a configuration problem, but I have MPD 0.20.19 running on my small music server and use Cantata 2.3.1 on my laptop, and I am unable to add local files to the play queue.

The option is grayed out in the "Play Queue" view, and nothing happens if I try to add files through "Folders > Home" view.

The server is running fully updated Raspbian "Stretch" (with MPD from the "Buster" repos), and the client machine is Linux Mint 18.3.

My output of mpd --version is:
```
Music Player Daemon 0.20.19

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un
```
Any assistance will be greatly appreciated! Thanks in advance :)

**Comment by CDrummond** [comment]
Enable "Local file playback: [x] Via in-built HTTP server"

**Comment by moretocome** [comment]
Forgive me for being a complete n00b @CDrummond but where do I find that setting? I feel I have looked everywhere, but I obviously haven't :)

**Comment by CDrummond** [comment]
Its in the collection settings - its per MPD connection.

**Comment by moretocome** [comment]
Thanks for the reply @CDrummond 

But that setting does not seem to be available in my settings:
![cantata collection settings 2018-06-15 10-46-25](https://user-images.githubusercontent.com/2301256/41468907-beaba238-70ab-11e8-9914-a1fe4fd80576.png)

Could it be a dependency issue?

**Comment by CDrummond** [comment]
Then who-ever built your Cantata package has disabled the in-built HTTP server functionality. File a bug report with them.

Some distro's don't like Cantata having this in-built server, hence there is a compile flag to remove it, and a check box to disable it in the UI. However, this server only runs if there are local files in MPD's queue, and it will only server files that are i that queue.

**Comment by moretocome** [comment]
Oh that's a pity.
I am using the unofficial ppa: `ppa:ubuntuhandbook1/cantata-qt`
Thanks a lot for all of your help and this sweet piece of software. I use it every day :+1:

**Comment by moretocome** [comment]
I reached out to the maintainer at ubuntuhandbook, and and he rebuilt Cantata with the http server enabled, so now playback of local files is available :)
