### ISSUE TITLE
[Feature Request] Add the option in Podcasts to automatically download episodes marked as "New"

### ISSUE THREAD

**Issue by chrlsnchrg** [CDrummond/cantata#1313]
Please add the option in Podcasts to automatically add all podcast episodes marked as "New" to the download queue. Alternatively, when "Show Unplayed Only" is on, and the user left clicks on the folder and selects "Download Episodes", please _don't_ add episodes marked as _listened_ to the download queue.

**Comment by CDrummond** [comment]
Not sure I like the auto-download. However, the second suggestion makes sense - and I think that is the way it should be, so this is a bug for me.

**Comment by chrlsnchrg** [comment]
I agree that many people wouldn't like the autodownload all unlistened episodes feature - which is why I think it should be optional and off in config that ships with the program but available for those that want it.
