### ISSUE TITLE
[Feature Request] "Copy Songs To Device" through KDE Connect

### ISSUE THREAD

**Issue by Nocifer** [CDrummond/cantata#1314]
As title says. Would it be possible?

**Comment by CDrummond** [comment]
Hmmm.... Interesting idea, never played with KDE connect, but I don't see why it could not be added. Will think about this for 2.4

**Comment by hmpf** [comment]
I'm having trouble "copying to device" via usb (not cantata's fault) so this suddenly became very relevant.

**Comment by CDrummond** [comment]
Sorry, but my time on Cantata is now very limited. This is not a feature I would use, so I will not be implementing. As always, please feel free to implement and submit a pull request. Until then I'm closing as wont-fix.
