### ISSUE TITLE
[Feature Request] A couple of "Rating" tag fixes and improvements

### ISSUE THREAD

**Issue by Nocifer** [CDrummond/cantata#1315]
Right now it's pretty cumbersome to change the Rating of a song. As far as I can tell you can't do it directly from the Play Queue, so you have to either have the song playing in order to change it from the Toolbar widget, or right-click on it and select either "Set Rating" or "Edit Track Information" from the menu, but both of those come with their own issues.

1) "Set Rating" does not allow you to use half-star ratings.
2) "Edit Track Information," besides complicating things without reason (compared to the other two methods), is also a bit unreliable - I've found that if you select multiple songs in the Play Queue and simultaneously update their Rating through "Edit Track Information", some of them don't update their Rating and won't no matter what until you deselect the ones that already did update (i.e. select only the ones which haven't updated). This could be a more general issue with multi-editing song tags, sorry but I haven't tested.

**Comment by CDrummond** [comment]
Just tried changing the rating via the track info dialog, and its working just fine. I set ratings for three songs, applied OK. Closed dialog, and changed ratings for 2 songs, and added a rating for another, still applied OK.

**Comment by CDrummond** [comment]
What about the rest? I see no issue. Unicode (AFAIK) has only just added support for 1/2 stars - so currently I could not add (using the star approach) half-star ratings to the menu.

**Comment by Nocifer** [comment]
Alright, fair enough, didn't know about Unicode lacking support. But what about editing the ratings directly within the Play Queue? Would that be possible?

**Comment by CDrummond** [comment]
Possible, but more work than I have time for, and I've never personally used ratings.
