### ISSUE TITLE
change output-devices

### ISSUE THREAD

**Issue by bendschs** [CDrummond/cantata#1316]
i am using cantata on osx together with forked-daapd (on my raspberry pi). in genreal it works pretty well but i noticed, that i am not able to enable/disable the airplay-output devices through the menu of the web-interface (for local audio-output it is working properly). as i am not sure where the problem is a ticket is also opened here:
https://github.com/ejurgensen/forked-daapd/issues/533

cheers,
bendsch

**Comment by CDrummond** [comment]
Cantata is an MPD client, not forked-daap, Output switching works with MPD.

Please, before raising issues, at least test with MPD.

**Comment by CDrummond** [comment]
Ah, perhaps I spoke to soon! Cantata is using an unsigned byte for output IDs - so a max of 255. Looking at libmpdclient's output.h, an unsigned in is used.

I'll update Cantata to allow larger IDs.

**Comment by bendschs** [comment]
yes, forked-dappd has (limited) mpd functionality. since change of local output is working, i think it is a minor issue.

cheers bendsch
