### ISSUE TITLE
[Feature Request] Shuffle album playback

### ISSUE THREAD

**Issue by laichiaheng** [CDrummond/cantata#1318]
Add more modes for playing musics, not only random tracks, but also random albums (After playing this album, jump to another random album)

Not sort the albums in shuffle mode, but play it in shuffle mode, just like how deadbeef player does.

**Comment by CDrummond** [comment]
Sorry, can't do. MPD controls how items are shuffled during playback, and it has (AFAIK) no album shuffle mode.

**Comment by jraygauthier** [comment]
@CDrummond / @laichiaheng : What about a "next album" over an already shuffled playlist. Would it be possible?

**Comment by jraygauthier** [comment]
There is also this [f0rki/mpd-album-shuffle: Randomly play or sort the albums in the current mpd playlist](https://github.com/f0rki/mpd-album-shuffle) project.
