### ISSUE TITLE
WinOS: Proxy exception defined in internet explorer is ignored by Cantata

### ISSUE THREAD

**Issue by alpha-97** [CDrummond/cantata#1319]
I tried to put the mpd server address in the proxy exception field with the proxy option on , Cantata failed to connect to the mpd server.

I  put the proxy option off, Cantata can connect to the mpd server.

Problem existed in version 2.3.1 and previous versions.

Please help to look into it. Thanks.

**Comment by CDrummond** [comment]
Sorry, but this is not a tech support forum. Cantata makes a connection to MPD on the chosen port (usually 6600). I don't use Windows, so have no time to look into what is an issue with your setup on your system.

**Comment by alpha-97** [comment]
It's not about my setup, but the Cantata proxy configuration not working fine.
Possible solution is to have its own proxy setting, or simply not support proxy.
Thanks.
