### ISSUE TITLE
[Feature Request] Option not using system proxy

### ISSUE THREAD

**Issue by alpha-97** [CDrummond/cantata#1323]
Cantata is now using the system proxy value without catering its exception list which causing problem while the MPD is not expected to be accessed through proxy.

I really like Cantata, and wish it could be better and more useful.

I am not good at programming, but tried to see if anything could help. As referred to the source code segment below, Cantata is hard code to use system proxy (mode 0), but later I found the proxy mode setting related coding (proxy setting is not found in GUI) . May I know if it's under development or withdrawn ?

For me , the simplest request to add an check box to toggle between "system proxy" (mode 0) and  "no proxy" (mode  1).  Many Thanks.

preferencesdialog.cpp line 84-86
    #ifdef ENABLE_PROXY_CONFIG
    proxy = new ProxySettings(0);
    proxy->load();

networkproxyfactory.h line 34-40
public:
      // These values are persisted
      enum Mode {
        Mode_System = 0,
        Mode_Direct = 1,
        Mode_Manual = 2
    };

proxysettings.cpp line 28-36
ProxySettings::ProxySettings(QWidget *parent)
    : QWidget(parent)
{
    setupUi(this);
    proxyMode->addItem(tr("No proxy"), (int)NetworkProxyFactory::Mode_Direct);
    proxyMode->addItem(tr("Use the system proxy settings"), (int)NetworkProxyFactory::Mode_System);
    proxyMode->addItem(tr("Manual proxy configuration"), (int)NetworkProxyFactory::Mode_Manual);
    connect(proxyMode, SIGNAL(currentIndexChanged(int)), SLOT(toggleMode()));
}

**Comment by CDrummond** [comment]
You will need to re-build Cantata, and pass -DENABLE_PROXY_CONFIG=ON to the cmake call. This will enable proxy settings in the preferences dialog.
