### ISSUE TITLE
"Edit Track Information" does not work when files are dropped in the playlist 

### ISSUE THREAD

**Issue by xbug42** [CDrummond/cantata#1328]
Cantata 2.3.1
Server protocol 0.20.0
Ubuntu 18.04
mpd is running in localhost

"Edit track information" playlist context menu does nothing if the file was dropped in the playlist from another app (Dophin in my case). 
If I add the same file in the playlist using the library, it works.

I think it worked fine in 2.2.0.

**Comment by CDrummond** [comment]
Its only designed to edit MPD files.

**Comment by xbug42** [comment]
In this case, the files are MPD files too. Cantata knows where the MPD root
folder is so it should be possible to "promote" a local file to a MPD file
if the local path match the MPD root folder + MPD file path, don't you
think ?

Cantata is the default music player in Kubuntu 18.04 LTS. I don't know if
you wanted it or not but this is a fact. And from a user perspective, it
should be possible to drop something in the default player and then to edit
it afterwards...

**Comment by CDrummond** [comment]
If the files are dropped on, then they are served from Cantata to MPD. Cantata then treats then as external files.

If you want this behaviour changed, feel free to write a patch to fix this.
