### ISSUE TITLE
Stream playback broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [CDrummond/cantata#1329]
Very happy to have found cantata! Best mpd client by far!
Unfortunately stream playback is broken, at least on Ubuntu 18.04 fresh install.
Tried prebuilt binaries from Ubuntu repos, Ubuntu Handbook ppa and building myself.
When using libvlc cantata crashes immediately when stream playback is enabled in menu, this error message is printed to the terminal:
```
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x3ef20
  /lib/x86_64-linux-gnu/libpthread.so.0 : pthread_mutex_lock()+0
  /usr/lib/x86_64-linux-gnu/libvlc.so.5 : libvlc_retain()+0x15
  /usr/lib/x86_64-linux-gnu/libvlc.so.5 : libvlc_media_new_location()+0x118
  ./bin/cantata : HttpStream::streamUrl(QString const&)+0x2bc
  ./bin/cantata : HttpStream::setEnabled(bool)+0x9c
  ./bin/cantata : ()+0x1638b6
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QObject::event(QEvent*)+0xe2
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0x903
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QMainWindow::event(QEvent*)+0x15b
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x9c
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x2a4
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x118
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x1ed
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2e42c3
```
Doesn't matter if stream url is configured or not, it just crashes as soon as you click on the menu item.

Also, building without libvlc works, but only in debug mode. If built in release mode, cantata doesn't crash, but there's no audio and gstreamer prints error message to the terminal several times:
```
GStreamer; Unable to pause - ""
Error: "Invalid URI \"\"."
```
Seams that in release mode streamUrl contains empty string even if it's configured.

I tried mucking around in the source but as I only speak python and plain C that wasn't productive at all.
Still, cantata is fully usable when built without libvlc and in debug mode, so I'm quite satisfied.
If you need any additional info, do tell. Very eager to help, as cantata is essential to my current setup.

P.S. I've browsed through the issues and saw that you're considering removing stream playback. I implore you to reconsider, as this feature combined with the very nice interface not only makes cantata the best mpd client, but possibly the only usable one, not counting web clients and other things that work but utterly fail to integrate with the system.

**Comment by CDrummond** [comment]
not sure how you get am empty URL - the code checks for URL being empty, so very odd. I tried creating a URL of spaces, but still Cantata is fine - and recognizes this as invalid.

Can you try the following? Edit mpd-interface/httpstream.cpp  change line  159 from

--------8<---------
if (!url.isEmpty() && !player) {
--------8<---------

to:

--------8<---------
QUrl qUrl(url);
if (!url.isEmpty() && qUrl.isValid() && qUrl.scheme().startsWith("http") && !player) {
--------8<---------

Then re-build. This adds checking to ensure the URL itself is a valid URL. I was able to get crashes if I set the URL to "a  b", and this change fixes the issue (as the URL is not valid).

**Comment by OzymandiasTheGreat** [comment]
Yup, this fixes it.

**Comment by CDrummond** [comment]
Thanks for checking. And VLC?

**Comment by CDrummond** [comment]
Hmmm.... If you run cantata as follows: `/cantata --debug http-stream` what is the output?

**Comment by OzymandiasTheGreat** [comment]
The streamUrl is set alright, but libvlc still crashes:
```
2018-07-19 22:33:37 - HttpStream streamUrl "http://192.168.0.102:8000"
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x3ef20
  /lib/x86_64-linux-gnu/libpthread.so.0 : pthread_mutex_lock()+0
  /usr/lib/x86_64-linux-gnu/libvlc.so.5 : libvlc_retain()+0x15
  /usr/lib/x86_64-linux-gnu/libvlc.so.5 : libvlc_media_new_location()+0x118
  ./bin/cantata : HttpStream::streamUrl(QString const&)+0x1b9
  ./bin/cantata : HttpStream::setEnabled(bool)+0x9c
  ./bin/cantata : ()+0x1639e6
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QObject::event(QEvent*)+0xe2
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0x903
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QMainWindow::event(QEvent*)+0x15b
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x9c
  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x2a4
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x118
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x1ed
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2e42c3
```

**Comment by CDrummond** [comment]
Then this must be a VLC issue. A valid URL is passed.

You stated GStreamer works OK? If so, then I think I'll switch to QtMultiMedia by default for Linux builds.

This code is not code that I wrote. And is not a feature I use...

**Comment by CDrummond** [comment]
Please update to git/master - and see if issue now 'fixed'? This should be using QtMultiMedia by default - for all variants.

**Comment by OzymandiasTheGreat** [comment]
Yup, with the new master I can do a Release build with default flags and everything works as expected.

Thank you! This has been the quickest response I've ever seen and the bugs actually fixed.

**Comment by CDrummond** [comment]
Thanks for the confirmation.
