### ISSUE TITLE
Feature Request: make it easier to delete low-ranked tracks from playlists

### ISSUE THREAD

**Issue by ReaperX** [CDrummond/cantata#1332]
Here's a brief description of the problem. Say I have a large playlist where I have set ratings for individual tracks and I want to weed out the low-ranked ones, i.e. delete them from the playlist.

The only way I see the ratings is in the play queue, but doing Remove there only removes the track from the play queue, not the playlist. In the playlist view, it's the opposite: I can remove tracks from the playlist, but I don't see the ratings. 

I imagine that Cantata doesn't keep an association between songs in the play queue and how they came to be there, so a "Remove from playlist" context menu in the play queue would not make sense if the playlist of origin is not available. A "remove from all playlists" option would be nice though. 

Alternative, you could show the ratings in the playlist view.

**Comment by CDrummond** [comment]
I never use ratings myself, so I have no time/motivation for this - sorry. (As always, patches / pull-requests welcome).

However, you can always load the playlist into the play queue, remove whatever songs you want, and then re-save. Cantata should produce the name of the last loaded playlist as the default name to save as.
