### ISSUE TITLE
Synchronize dynamic playlists from two cantata installations

### ISSUE THREAD

**Issue by ascomycota** [CDrummond/cantata#1335]
Hello,

I have a laptop and a normal PC and both run Cantata and control the mpd on a RaspberryPi. I have created some dynamic playlists on one instance but the second instant doesn't show them. Normal static playlists I can see on every client - also on Android mpd apps.

Is it because there is no dynamic playlist support in mpd - so Cantata fakes it by just adding a new song to the current playlist once another one was played?

If thats the case, we have no chance. But isn't there a kind of "message channel" in mpd for the clients to exchange "messages" - or a specific storage location in mdps database which both instances can access. Thus you could send the dynamic playlists to the other instances. Would be an even more transparent fake of dynamic playlists ;-)

Thanks
Ascomycota

**Comment by CDrummond** [comment]
Dynamic playlists are indeed Cantata specific. Cantata uses a small perl helper app (cantata-dynamic) to read the playlist file, and dynamically populate the cue. So, by default the playlists are per-user specific.

However, the script can be installed in server-mode. In this mode, dynamic playlists are stored on the server, and are shared between all users of MPD (as per standard MPD playlists). When Cantata starts, it will check if the dynamizer is active on the MPD instance, and will then (only) list and use playlists that are there.

See section 12 in https://raw.githubusercontent.com/CDrummond/cantata/master/README
