### ISSUE TITLE
Can't set stars or scrobble songs as "favorite" from radio.

### ISSUE THREAD

**Issue by Winterwolf** [CDrummond/cantata#1336]
I used to put a heart on liked songs when listening radio from Clementine to be able to browse my musical preferences on LastFm. Cantata unfortunately does not allow me to do this.

**Comment by CDrummond** [comment]
Sorry not supported, as you found out. Scrobbling is not something I use, so I have no motivation to change. Feel free to submit a patch, or pull request, to fix if you like.

**Comment by Winterwolf** [comment]
@CDrummond Excuse me, but why in this case did you make the ability to connect to LastFM? :( Scrobbling works absolutely fine at current moment, just one button is unfortunately not available for radio by some strange reason.

**Comment by CDrummond** [comment]
Cantata has lots of features I do not personally use - HTTP streaming, rating, soundcloud, jamendo, etc. These were implemented a while ago, when I had more spare time. Some, such as HTTP streaming, were originally implemented by others.

Sorry, but I work on Cantata in my spare time - and I'll implement features if/when I get the time. As stated, this is not something that particularly bothers me. If it bothers you, feel free to implement - just as I feel free to close feature-requests that I have no time to implement.

To implement scrobbling of radio tracks is not so easy. The last.fm spec stats that you should have played a certain % of the track before scrobbling. Also, radio stations place the song title, song artist, etc, in different fields.

**Comment by bjoernv** [comment]
May be, it would be better to re-open this issue. With an open issue, other developers may be better motivated to submit a merge request.

**Comment by CDrummond** [comment]
@bjoernv This is a 3 year old issue! Nothing has changed, and no changes will be made with regard to this. If you want it resolved, feel free to submit a pull request. I personally stopped using Cantata and MPD over 4 years ago - switched to LMS.
