### ISSUE TITLE
Replaygain scan result in lower volume than other implementations.

### ISSUE THREAD

**Issue by 38github** [CDrummond/cantata#1337]
I am using Cantata in Solus and I noticed that when I replaygain scan songs in Cantata they play with lower volume compared to songs scanned in other pplayers/scanners. Is it that Cantata follows ebu128r reference volume and not replaygain v2's reference?

**Comment by CDrummond** [comment]
Yeah, Cantata uses libebur128. And the reference value used comes from this. In `replygain/trackscanner.cpp` `RG_REFERENCE_LEVEL` is set to `-18.0` - I'm guessing you'd prefer another value? Perhaps you could try with different values, and see which value causes the level to match others? If, so then I could add a setting for this (in 2.4, as it'd need new strings).

But for 2.3.2 I could add a non-gui config option.

BTW, I seem to recall that foobar2000 produces the same tag values as Cantata. At least when I did the initial implementation and testing.

**Comment by 38github** [comment]
I have to apologise for taking up your time because I noticed that the files that are louder are opus files compared to FLAC files. They have both been scanned with Cantata and are not played at the same volume. I am sorry for starting out this issue totally incorrect. However, opus files does play a lot louder than FLAC files which I am guessing is because of opus using the lower reference level of EBU 128r internally compared replaygain.

**Comment by CDrummond** [comment]
Ah, so I'll close this? I'll leave the code change as is - as it _might_ be useful...

All Cantata is doing is decoding the samples, and calculating the tags. I see no reason why this should be different between formats.

**Comment by CDrummond** [comment]
Also, the code change I mentioned is broken. I'll revert the change.

**Comment by 38github** [comment]
I started thinking about the following today; does cantata read the replaygain tags in opus? I wonder since opus files are played louder than flac.

**Comment by 38github** [comment]
I have tried a couple of songs, both flac and opus, and flac files are lower in volume compared to opus. I have scanned them using Cantata but also scanned with other programs and the problem appears every time.
