### ISSUE TITLE
Replaygain: incorrect album peak when adding a song to an already tagged album

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1338]
I have an album that's already been tagged with replaygain, then I add a song to it (same artist and album in the tags) and launch replaygain selecting the whole album. When the dialog asks me if I want a partial or full scan, I select the partial scan. I expect that the new song will have the same album peak as the others, but instead it obtains a separate album peak: the same as the song peak.

When doing the full scan, everything works as expected.

**Comment by CDrummond** [comment]
Fair point. I guess the existing values for the other tracks should be used.

**Comment by CDrummond** [comment]
Hmmm.... Looked into this, and the libebur code that calculates the album gain needs access to some 'sate' info for each track (this is calculated when scanning the track). Therefore, to properly calculate the album gain all tracks need to be scanned. => cod eis working the best it can,

**Comment by Tichy** [comment]
A foolproof check could be useful? If in the same album there's some track with the replaygain tag and others without, force the full scan or prompt the user.
