### ISSUE TITLE
[Feature request] 'Sort by...' functionality in playlists

### ISSUE THREAD

**Issue by thecountoftuscany** [CDrummond/cantata#1340]
As mentioned, it would be nice to have a 'sort by...' (artist, or album, or track number, or title) option in playlists. Currently, the only way to sort songs in playlists is by manually dragging.

**Comment by CDrummond** [comment]
For now - load into playqueue, sort, then re-save.

**Comment by althogalbor** [comment]
This will require a clean solution. I would suggest this:

Don't provide ability to sort playlists. Instead, add this ability to sort the playqueue. In this case, the playqueue, just like a file manager, will have namy fields at the top ('artist', 'album', 'manual order', 'year'..). If you press on the top field, songs will be sorted accordingly.

This will avoid adding any complexity to playlists.

If you like the new order, just resave the playlist.

**Comment by CDrummond** [comment]
As stated  - you can load into the queue and sort from there. Sorry, but my time for Cantata is now very limited - and this is not a critical feature. However, please feel free to implement and submit a pull request.
