### ISSUE TITLE
[Feature request] read offset value when ripping

### ISSUE THREAD

**Issue by 38github** [CDrummond/cantata#1341]
A box to set the offset value when ripping would be great!

**Comment by CDrummond** [comment]
Why? What is this for? How would a user know what the offset value would be? Is this for all CDs? CD specific? Track specific?

**Comment by 38github** [comment]
It is used so that cdparanoia knows where what offset to use to rip complete tracks and not lose beginning or end of tracks. a comprehensive list of offset values for most CD-ROM and DVD drives is available at http://www.accuraterip.com/driveoffsets.htm .

**Comment by 38github** [comment]
One value is used for all CD's.

**Comment by CDrummond** [comment]
Ah, so its a offset specific to the drive? Is there any API that can be used to auto-detect this? e.g. query the accuraterip list?

**Comment by CDrummond** [comment]
It's been a **long** time since I looked at Cantata's CD-ripping code. Having looked at it, Cantata gets the first and last sector for a track, use cdparanoia (library) to seek there, and then reads last-first number of sectors. Should this offset set value be added to the seek position? I.e. instead of seking to the location of the track's first sector, it should be this location + offset?

**Comment by CDrummond** [comment]
I've made a config-only change for 2.3.3 to allow setting this. In the `General` section of `~/.config/cantata/cantata.conf` set `paranoiaOffset` to the desired value. (All whilst Cantata is NOT running). e.g.

```
[General]
paranoiaOffset=234
```

Does this help? (You will need to checkout and compile git/master)

**Comment by CDrummond** [comment]
Any updates? I have you had a chance to try this change?

**Comment by 38github** [comment]
I apologise for not trying it out already. I will stay up my computer and
compile it.

**Comment by CDrummond** [comment]
Thanks for the confirmation. I'll leave the issue open, so as to remind me to add a UI setting for 2.4

**Comment by CDrummond** [comment]
GUI setting in 2.4 branch
