### ISSUE TITLE
[Feature Request] Addition of seek and set rating shortcuts to KDE global shortcuts

### ISSUE THREAD

**Issue by thecountoftuscany** [CDrummond/cantata#1343]
It would be great to have global shortcuts for seek forward, backwards 5 sec and set rating 0-5 stars in the Cantata component in the KDE System Settings Global Shortcuts since a lot of times these actions are desirable with the window minimized or in the tray, specially the seek operations.

Also, one could be added to show/hide the cantata window.

**Comment by CDrummond** [comment]
Cantata is a Qt app, and does not support KDE's global shortcuts.

However, most (all?) of Cantata's actions can be access via DBus. There is a helper script (`/usr/share/cantata/scripts/cantata-remote` that can be used to invoke these. Refer to Section 10 in [README](https://raw.githubusercontent.com/CDrummond/cantata/master/README)

**Comment by thecountoftuscany** [comment]
There is a cantata component present in the KDE global shortcuts as shown in the screenshot below:
![cantata-shortcuts](https://user-images.githubusercontent.com/14308382/43893536-ee51edd2-9bec-11e8-9318-69491aefad30.png)

**Comment by thecountoftuscany** [comment]
Thanks, the `seekfwd5` and `seekrev5` options in `cantata-remote` work perfectly.

However, the `rating0` to `rating5` options seem to not work and there is no dbus call to show/hide the window.

**Comment by CDrummond** [comment]
Don't use KDE - so not sure why they are there. Older Cantata releases supported (and some defaulted to) KDE builds. Perhaps this is where they are from? Cantata does support GNOME media keys dbus interface - so again perhaps from here? Or they might be just the MPRIS actions.

Ratings only work on selected playqueue items.

The action list exported is just the internal actions - and those that can be assigned a keyboard shortcut.
