### ISSUE TITLE
[Feature request] Google Drive access.

### ISSUE THREAD

**Issue by 38github** [CDrummond/cantata#1344]
This one amazing feature that Clementine has that I miss in all other players I had tried. I have all my music as small opus files on my Google Drive so that I can stream them.

**Comment by CDrummond** [comment]
The problem I see with this is that the streams will probably be protected, as you will need to login to access them. This would be OK for Cantata, but would nit be OK for MPD. How would MPD be able to login? MPD itself would need support for this.

Alternatively Cantata could proxy the stream to MPD, as it does for local files and AudioCDs.

However, this is more hassle than I have time for. I don't store my music on any cloud services, so this is not a feature I would use. Should you wish to implement this yourself, then I'll gladly accept a patch or pull-request.

**Comment by trmdi** [comment]
@38github 
Did you try using https://github.com/astrada/google-drive-ocamlfuse ?

**Comment by CDrummond** [comment]
How does that help MPD read the files? Cantata would need to proxy them to MPD.

However, you could mount your google drive using this, and the use Cantata 2.3.2's local folder browsing to add the files to the playqueue. They will then be treated as local, non-MPD files, and served to MPD via Cantata's simple HTTP server.
