### ISSUE TITLE
[feature request] Control cantata with the macOS media keys 

### ISSUE THREAD

**Issue by dhharris** [CDrummond/cantata#1347]
By default, cantata does not support this, but with the help of [this python tool](https://github.com/pushrax/osxmpdkeys), I can at least play/pause (fast-forward/backward does not work). It would be nice if this was a built in feature inside of cantata.

**Comment by glensc** [comment]
I wonder why i can't even bind the play/pause button. as for example when spotify is running, it is able to capture play pause. if it's not running default itunes is launched.

**Comment by CDrummond** [comment]
Sorry, but I have decided to no longer produce mac and windows builds - as I use neither OSs. Therefore, features/issues that specific to these are not on my list of priorities. However, please feel free to implement and submit a pull request.

**Comment by dhharris** [comment]
Why did you close this? We should leave it open for visibility in case someone wants to work on it.
