### ISSUE TITLE
Feature Request: Auto Reconnect to Server

### ISSUE THREAD

**Issue by okennedy** [CDrummond/cantata#1348]
Cantata puts up a "Disconnected" bar on the screen whenever the MPD connection fails.  This happens even for transient failures like restarting the system MPD or switching networks (e.g., wired/wireless) when connected to a remote MPD.  It would be helpful if Cantata attempted to automatically reconnect (e.g., immediately and then with an exponential backoff) rather than waiting for the user to manually indicate that MPD was back up.

**Comment by CDrummond** [comment]
Cantata does reconnect if a command fails. However, it reconnects immediately.
I have no intention of adding delayed reconnects - as that would mean queuing up and commands that are to be sent, etc. Too much hassle for a scenario that does not affect me. Sorry, if this is not the answer that you were looking for - but my spare time is limited. Feel free to work on the code, and submit a pull request if you wish to implement this. The code in `sendCommand(...)` within `mpd-interface/mpdconnection.cpp` is what you will need to change.
