### ISSUE TITLE
Group multiple disc albums as one album 

### ISSUE THREAD

**Issue by NilsHult** [CDrummond/cantata#1349]
Request:
Group multiple disc albums as one album.

The problem:
Add a multiple disc album to the play queue using style - grouped albums.
The songs will be grouped into multiple albums, one per disc number.
When the play queue is shuffled by album then each disc will be shuffled around as if they where separate albums.

Suggestion:
Group all songs under one album header, display the disc number before track number (e.g. like 1:01, 1:02, ... ) and order songs in disc and track number order.

<img width="169" alt="interface 2018-08-23 15-40-21" src="https://user-images.githubusercontent.com/42644582/44529244-e5ef7100-a6eb-11e8-917c-44021611cb15.png">

<img width="253" alt="cantata hemma 2018-08-23 15-41-32" src="https://user-images.githubusercontent.com/42644582/44529269-f30c6000-a6eb-11e8-939d-a8bb5c40103c.png">

<img width="292" alt="cantata hemma 2018-08-23 15-43-45" src="https://user-images.githubusercontent.com/42644582/44529279-f99ad780-a6eb-11e8-8224-fd2866a5a0df.png">

**Comment by CDrummond** [comment]
Yeah, good idea. Will be in 2.3.3
