### ISSUE TITLE
[Feature request] Allow to refresh database when starting Cantata

### ISSUE THREAD

**Issue by rptx** [CDrummond/cantata#1350]
Hello,
- What do you think about trigger "Refresh Database" when Cantata is started ?
- This behavior would be optional.

Best regards.

**Comment by CDrummond** [comment]
I assume you mean as a command-line option? But Cantata is a GUI client. And why would I want that?

**Comment by rptx** [comment]
Hello,
I was thinking of a trigger completed by the GUI itself, when started, (modifiable option in the preferences).
It would be convenient to have an up to date database after starting Cantata.
Best regards.

**Comment by CDrummond** [comment]
MPD is where the real DB is connected, and MPD needs to update when this changes. Cantata **will** automatically notice any MPD db changes, as MPD informs Cantata of its DB version. Therefore, Cantata **is** always up to date with MPDs DB.

It is MPD that you need to configure to auto-update when files change. Now I guess Cantata could always send an update command - but this will cause MPD to refresh its listing. I'm not 100% sure how this would affect an MPD DB of (e.g.) 50000 tracks - I'd imagine there would be at least some time/cpu-load penalty to this. Therefore, not worth it.

**Comment by rptx** [comment]
Thanks for the information.
