### ISSUE TITLE
Unicode searching

### ISSUE THREAD

**Issue by trmdi** [CDrummond/cantata#1351]
For example, I have some songs named/titled: "à", "ắ", "a", "b", "c",...
When I search for "a", the result should be ["à", "ắ", "a"] rather than just ["a"]

**Comment by CDrummond** [comment]
Cantata uses
1. On Library page - searches are handled by SQLite, this should handle some (but not all) diacritics
2. On Search page - searches are handled by MPD

See https://github.com/CDrummond/cantata/issues/1217

Either way, not much else I can do.
