### ISSUE TITLE
No icon in system tray

### ISSUE THREAD

**Issue by carlospgmat03** [CDrummond/cantata#1352]
At home, with Ubuntu, and previously with Gentoo, both running FVWM and stalonetray, when I launch Cantata I get an icon in the system tray that lets me minimize Cantata and keep it out of the way. However, I do not get any more this behaviour. With vlc, which uses QT, I do get an icon. I am not an expert in window managers, so I cannot easily diagnose problems. Is it a bug? Is it a problem with my window manager? Please help! This is getting a bit annoying.

**Comment by carlospgmat03** [comment]
Inspired in a previous issue #1311 , I looked for statusnotifierwatcher.so. It is there:
``
[I] 13:0430~> locate statusnotifierwatcher
/usr/lib64/qt5/plugins/kf5/kded/statusnotifierwatcher.so
``

**Comment by CDrummond** [comment]
As stated, this is an issue on your system. My system is a bit messed up, in that even vlc does not show an icon for me. But using `QT_QPA_PLATFORMTHEME=gtk2 cantata` **does** result in a system tray icon.

Sorry, nothing else I can do. As stated multiple times, Cantata uses Qt5's `QsystemTrayIcon` - if something is not working, then the issues is a missing dependency, or an error there. I do not have time to debug issues on other peoples systems - sorry, but my time is limited.
