### ISSUE TITLE
Access to listen Internet Radio from Community Radio Browser

### ISSUE THREAD

**Issue by emersoncavalcanti1972** [CDrummond/cantata#1353]
Community Radio Browser (http://www.radio-browser.info)  is a community with the aim of collecting as many internet radio stations as possible. Many media player software like Rhythmbox, RadioDroid, Musicbox, Gradio and Kodi have support for this platform. I loved Cantata and would very much like to have a plugin or feature to access radio stations by searching the Radio-Browser. is this possible?

**Comment by CDrummond** [comment]
Will look into for 2.4

**Comment by CDrummond** [comment]
I've added searching of Community Radio for 2.4.0. I was going to add browsing, but the browse API seems very limited - and it would only have been country/language.

**Comment by culebrasolida** [comment]
> I've added searching of Community Radio for 2.4.0. I was going to add browsing, but the browse API seems very limited - and it would only have been country/language.

Hi, I'm sorry but where can I find that option?

**Comment by CDrummond** [comment]
@culebrasolida Internet -> Streams -> Click search icon bottom right of view

**Comment by culebrasolida** [comment]
> @culebrasolida Internet -> Streams -> Click search icon bottom right of view

Thanks, found it, too bad it's not finding anything at all under Community Radio Browser.
