### ISSUE TITLE
SQLite driver missing from Windows setup

### ISSUE THREAD

**Issue by ArKay74** [CDrummond/cantata#1355]
As soon as you hit Connect in the setup wizard, there's an error message.

![untitled](https://user-images.githubusercontent.com/12251023/44949136-cd89ff80-ae2b-11e8-8394-455f8bcc827d.png)

**Comment by CDrummond** [comment]
Just tried a clean install of 2.3.2. The SQLite driver **is** installed, and Cantata works - the wizard is shown, connection made, and library loaded in main window.

Sorry, but this looks like an issue on your system.
