### ISSUE TITLE
Codec issue

### ISSUE THREAD

**Issue by genericgym** [CDrummond/cantata#1357]
Hi
I am having an issue with Cantata -- I am not sure if its a bug or just me being dumb.
I put an audio CD into my CD player. Cantata recognizes the audio CD and I can play it no problems in Cantata. Works perfectly.
I then try to import the CD into my Cantata music library and I get an error message "selected codec is not available". I must be misunderstanding something -- Cantata can play the music but not import it?
thanks
graham

**Comment by CDrummond** [comment]
When Cantata _plays_ and AudioCD - what it does is read the data from the CD, and send it to MPD via its in-built HTTP server as a WAV file. WAV files are raw, uncompressed audio.

When importing into your library (i.e. ripping the CD) Cantata converts the WAV into your selected codec. To do this, it uses ffmpeg/avconv, lame, faac, oggenc, opusenc command line tools. Not all are required (ffmpeg/avconv can handle most audio types), but the more of these you have the more options Cantata will show. By default, Cantata selects 'lame' - and I'd guess you do not have this installed on your system. So, to resolve this issue - either install lame, or select another codec. To change codec, in the `Copy Songs` dialog, select the gears icon next to `Copy songs to: Local Music Library`

**Comment by genericgym** [comment]
Thanks for the reply. That was exactly the problem. Installed all the codecs from ubuntu-restricted-extras and its all working now. Thanks for a great media app and keep up the good work
