### ISSUE TITLE
[Feature request] Dark Mode theme for MacOS Mojave

### ISSUE THREAD

**Issue by nadstaky** [CDrummond/cantata#1358]
Hello,

It would be very nice to have a new option in Cantata for Mac in order to get "Dark Mode" theme for MacOS Mojave.

Been using Cantata in Linux for a decade, and now since 4 years as I have Mac(s), never found better !

Please consider my request !

Best,

Eric

**Comment by CDrummond** [comment]
Sorry - I don't use macOS. The port was originally done a few years ago, when I had a mac for a few weeks. Now, I only use a mac to create builds - nothing more.

So, I have no time to implement this. However, I will gladly accept a pull request to implement this feature. Hence, I will mark as 'wontfix'
