### ISSUE TITLE
[Enhancement] Pls add ability to import/export podcast subscriptions as opml files

### ISSUE THREAD

**Issue by shad90** [CDrummond/cantata#1359]
Hi there!
I love the work with cantata, is a very useful and nice application!
I think adding support to import/export podcast subscriptions as opml files will be useful to sync it with my android.

**Comment by CDrummond** [comment]
Current master (for 2.4.0) allows reading of local OPML files, and exporting current subscriptions to an OPML file - so this should now cover this use case.

**Comment by marcorichetta** [comment]
Is there a 2.4.0 release somewhere (2.3.3 here on GH) or should I build it to use this feature?

Anyway, thank you for your effort Craig.
