### ISSUE TITLE
[Enhancement] Create bug reporting template in github

### ISSUE THREAD

**Issue by althogalbor** [CDrummond/cantata#1360]
```
Cantata version number=2.3.3
Cantata build type=Linux
cmake options (other than defaults)=-DENABLE_LIBVLC=ON
MPD version=0.20.18
```

The template should contain as mentioned [here](https://raw.githubusercontent.com/CDrummond/cantata/master/README): 

> \```
> Cantata version number=
> Cantata build type=Linux, Windows, Mac (omit as necessary)
> cmake options (other than defaults)=
> MPD version=
> \```

(i.e. the quoted text above should be automatically inserted when pressing the 'New Issue' button in github).

**Comment by CDrummond** [comment]
Done.
