### ISSUE TITLE
[Enhancement] Option to play .mp4 files in VLC instead

### ISSUE THREAD

**Issue by althogalbor** [CDrummond/cantata#1361]
```
Cantata version number=2.3.3
Cantata build type=Linux
cmake options (other than defaults)=-DENABLE_LIBVLC=ON
MPD version=0.20.18
```

My library contains lots of `mp4` files. It would be nice if Cantata could play them internally (with video). An easier option would be to use VLC instead: add option to open `VLC` externally when a `.mp4` file is double clicked in Cantata.

This can be an option in settings like this:
![screenshot from 2018-09-02 21-42-17](https://user-images.githubusercontent.com/21196400/44960528-3f7c4a80-aef9-11e8-9555-6531adc2ac1e.png)

**Comment by CDrummond** [comment]
No.
