### ISSUE TITLE
[Bug] Searching for a file name does not work

### ISSUE THREAD

**Issue by althogalbor** [CDrummond/cantata#1362]
```
Cantata version number=2.3.3
Cantata build type=Linux
cmake options (other than defaults)=-DENABLE_LIBVLC=ON
MPD version=0.20.18
```

Reproducing information:
1. Add an `.mp4` item to the library, that has no metadata at all other than the file name. Name the file `'SomeNewArtistName - RandomAlbum - whateverwhatever.mp4'`.
2. Refresh the library.
3. Search for `'SomeNewArtistName'`.
4. You'll get no results.

**Comment by CDrummond** [comment]
Search in `Library` page is on meta-data only. Search in `Search` page is via MPD - so if this is failing, error is there.
