### ISSUE TITLE
[Enhancement] Add option to export a playlist to .m3u file

### ISSUE THREAD

**Issue by althogalbor** [CDrummond/cantata#1363]
```
Cantata version number=2.3.3 (built 30 mins ago)
Cantata build type=Linux
cmake options (other than defaults)=-DENABLE_LIBVLC=ON
MPD version=0.20.18
```

Right click a playlist. You should see an option to export the playlist to an m3u file. Clementine has this feature.

**Comment by CDrummond** [comment]
Cantata is not clementine. Your playlists are already M3U files, in MPD's playlists folder.
