### ISSUE TITLE
Opening large music folder fails

### ISSUE THREAD

**Issue by diracsbracket** [CDrummond/cantata#1364]
I just built the latest Cantata master on Debian 9 and Qt 5.10.1.
When trying to open a large, structured music folder on a USB drive via the Folders tree, Cantata seems locked busy accessing the disk and irresponsive to any other user interaction.

**Comment by CDrummond** [comment]
Which folders tree? I assume you mean "Root" (as in "Browse files on your computer"). If so, then this is using Qt's `QFileSystemModel`.

If not, then the listing is coming from MPD. (I doubt this is the case you are referring to, but just checking).

Either way, I can't see this as a Cantata specific issue. The local browsing is deliberately simple, as its not Cantata's main use case and was only implemented at the request of a user. The listing of items from here is handled by Qt - so any slowness (I assume) is in there.
