### ISSUE TITLE
[Feature request] Artist & song on KDE task manager

### ISSUE THREAD

**Issue by petr-nehez** [CDrummond/cantata#1366]
I would really appreciate if Cantata could show currently played artist and song on task manager button.
![image](https://user-images.githubusercontent.com/1265990/45356628-0b252000-b5c4-11e8-8e2f-2655d6b9408e.png)

It would be perfect if Cantata would mimic the same behavior Spotify app does.
![image](https://user-images.githubusercontent.com/1265990/45356680-3d368200-b5c4-11e8-90cf-bf5626ccab8b.png)

Manjaro + KDE 5.13.5

**Comment by CDrummond** [comment]
Sorry, don't use KDE - and even if I did I would not use this style taskbar. There are plenty of other ways to show the current track - e.g. MPRIS

AFAIK, the taskbar button gets its information from the window titlebar. Cantata (many versions ago) used to update the titlebar with this information. However, it duplicates the information that is shown in the toolbar - and I didn't like this look, so I remove it.

If there is some other property that the taskbar code uses, then I'll gladly update that when the track changes. But, I'm not going to update the titlebar -  as it leads to duplication, as already stated. Perhaps (and this would be more generic), the KDE taskbar itself should use the MPRIS into to update the taskbar button. This would then work for all apps.

**Comment by CDrummond** [comment]
Having said that... Perhaps (for 2.4) I might add an option to show the info in the titlebar and not toolbar.

**Comment by petr-nehez** [comment]
Thank you for reconsidering it :+1:

**Comment by StrangeSeasOfThought** [comment]
> However, it duplicates the information that is shown in the toolbar - and I didn't like this look, so I remove it.

An alternative would be to change the layout by moving the toolbar to the bottom... v0v

**Comment by Nick-Elliott-UK** [comment]
What happens if there are many items on the taskbar or, as I do, the taskbar is positioned on the side of the screen and doesn't have the width to display this information?

**Comment by petr-nehez** [comment]
> the taskbar is positioned on the side of the screen
This case is of course problematic so if we keep this feature optional then you would be able not to use this feature.

**Comment by Thaodan** [comment]
The taskbar applet is based on mpris (disable mpris and see).
Looking at the preview (using Plasma myself) you'll the everything that exposed is shown.

For example on my pc here:
https://i.imgur.com/uYpC5US.png

To verify you can call dbus to show you the properties of the mpris player instance of cantata:
`~/:dbus-send --dest=org.mpris.MediaPlayer2.cantata --print-reply=literal /org/mpris/MediaPlayer2`
The result:
```
 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata
   variant       array [
         dict entry(
            mpris:artUrl            variant                file:///home/bidar/.cache/cantata/covers/Led Zeppelin/Physical Graffiti.jpg         )
         dict entry(
            mpris:length            variant                int64 273000000
         )
         dict entry(
            mpris:trackid            variant                /org/mpris/MediaPlayer2/Track/7         )
         dict entry(
            xesam:album            variant                Physical Graffiti         )
         dict entry(
            xesam:artist            variant                array [
                  Led Zeppelin               ]
         )
         dict entry(
            xesam:contentCreated            variant                1975d         )
         dict entry(
            xesam:discNumber            variant                int32 2
         )
         dict entry(
            xesam:genre            variant                array [
                  Rock               ]
         )
         dict entry(
            xesam:title            variant                Black Country Woman         )
         dict entry(
            xesam:trackNumber            variant                int32 8
         )
         dict entry(
            xesam:url            variant                file:///home/bidar/Musik/Led Zeppelin/1975 - Physical Graffiti/08 - Black Country Woman.mp3         )
      ]


```

So no bug here.

**Comment by petr-nehez** [comment]
Yeah, it might not be clear from my description that it is the window title thing.

> The only real KDE/Plasma thing going on is displaying a speaker icon next to the title

Good point here, I haven't realized this :wink:

**Comment by CDrummond** [comment]
Closing, as I'm not going to implement this. Repeating the toolbar text on the titlebar looks awful. I thought about (optionally) removing the text from the toolbar (therefore making it smaller_, and just having the text in the titlebar. But then where do rating, technical info, last-fm love, etc. go? Sorry, but too much hassle.

Changed label to 'wontfix' - as these are the issues I have no time to implement, and don't affect me. But, as always, I'm glad to accept pull requests.

**Comment by petr-nehez** [comment]
And what if you would make it as an option under Interface->External->"Show track info in window title"?
It could be OFF by default. I understand you don't like duplicating of info but someone else can have a different taste.

I don't know C++ at all, if I would code in it then it wouldn't be a big problem for me to make a PR but this way I can only ask you :pray:.
