### ISSUE TITLE
opus - Unable to add local files. No suitable files found.

### ISSUE THREAD

**Issue by hrvoj3e** [CDrummond/cantata#1370]
**Describe the bug**
Unable to add local files. No suitable files found.

**To Reproduce**
Drag and drop an `.opus` file to Cantata playlist.

**Expected behavior**
Start playing.

**Version Info**
 - OS: Manjaro Linux	17.1.12	Hakoila
 - Cantata Version: 2.3.2
 - MPD Version: 0.20.21

**Additional context**
Opus files were made by youtube-dl .
E.g. `youtube-dl -x https://www.youtube.com/watch?v=VUb450Alpps`
It plays ok in **deadbeef** player.

**Comment by CDrummond** [comment]
Please, before raising new feature requests, check the ChangeLog / other issues - to see if its already been done! Which in this case, it has (for 2.3.3)

https://raw.githubusercontent.com/CDrummond/cantata/master/ChangeLog

**Comment by hrvoj3e** [comment]
I looked at change log, searched all issues but dod not see my problem resolved.
I looked the changelog first and spotted opus support but failed to notice version `2.3.2` vs `2.3.3`.
Sorry.

**Comment by hrvoj3e** [comment]
Tried `cantata-git-2.3.2.r25.g8f7f4c8c-1` - it works OK now.

But it doesn't show track progress (time seek).

`youtube-dl -x https://youtu.be/hTWKbfoikeg`
![screenshot 2018-09-13 23-16-07](https://user-images.githubusercontent.com/4988133/45516365-2b630380-b7ab-11e8-94e8-556c76471fb8.png)


`youtube-dl -x --audio-format mp3 https://youtu.be/hTWKbfoikeg`
![screenshot 2018-09-13 23-16-35](https://user-images.githubusercontent.com/4988133/45516366-2b630380-b7ab-11e8-942f-40752bef19ac.png)

**Comment by CDrummond** [comment]
Cantata does not play any files, this is handled by MPD. When you add local (i.e. non-MPD files) Cantata serves them to MPD via a simple in-built HTTP server. 

MPD is responsible for determining the duration of the track, and for decoding and playing the music. Cantata's seek bar will only be enabled if MPD supplies Cantata with a valid duration.
