### ISSUE TITLE
Album titles ending in brackets

### ISSUE THREAD

**Issue by pavethem** [CDrummond/cantata#1373]
Album titles ending in brackets blend together with the year of the album in library view.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/847563/45816311-7d3fe800-bcdb-11e8-9e83-d5a8de7e7f45.png)

In the screenshot the entry should read: "Boombox 3 (Early Independent Hip Hop, Electro And Disco Rap 1979-83) (2018)". I think this makes it pretty clear.

**Version Info**
 - OS: Arch Linux
 - Cantata Version: 2.3.2
 - MPD Version: 0.19

**Comment by CDrummond** [comment]
That's by design to save having `Album Name (Re-Release) (1990)` - I think `Album Name (Re-Release,  1990)` looks nicer.
