### ISSUE TITLE
Feature request for Mac users (the developer won't do this) : Add a "Dark Mode" option for macOS Mojave

### ISSUE THREAD

**Issue by nadstaky** [CDrummond/cantata#1374]
Been using Cantata for Mac for years. Tried many other audio players, none of them are better to me.

In a near futur, Mac users will install macOS Mojave (I will). Mojave include the new aqua style, the "Dark Mode". I'd like a Mac developer to add this feature to Cantata, as the Cantata dev won't do that.

The "Dark Mode" looks very nice, I really hope Cantata will have this option in a next release.

Thanks for very much,

Eric

**Comment by trmdi** [comment]
Can you do like this on macOS? https://wiki.archlinux.org/index.php/qt#Qt_Style_Sheets

**Comment by CDrummond** [comment]
Why open a **NEW** issue for the issue you **ALREADY** reported? Madness.

**Comment by trmdi** [comment]
Maybe he thinks others need an opening issue instead of a closed one. :D
