### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#1380]
/home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.cpp: In member function ‘void HttpStream::bufferingProgress(int)’:
/home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.cpp:194:19: error: invalid use of incomplete type ‘libvlc_media_player_t {aka struct libvlc_media_player_t}’
             player->play();
                   ^~
In file included from /usr/include/vlc/vlc.h:43:0,
                 from /home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.h:30,
                 from /home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.cpp:24:
/usr/include/vlc/libvlc_media_player.h:43:16: note: forward declaration of ‘libvlc_media_player_t {aka struct libvlc_media_player_t}’
 typedef struct libvlc_media_player_t libvlc_media_player_t;
                ^~~~~~~~~~~~~~~~~~~~~
/home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.cpp:196:19: error: invalid use of incomplete type ‘libvlc_media_player_t {aka struct libvlc_media_player_t}’
             player->pause();
                   ^~
In file included from /usr/include/vlc/vlc.h:43:0,
                 from /home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.h:30,
                 from /home/parkmino/Downloads/mpd/cantata-svn/mpd-interface/httpstream.cpp:24:
/usr/include/vlc/libvlc_media_player.h:43:16: note: forward declaration of ‘libvlc_media_player_t {aka struct libvlc_media_player_t}’
 typedef struct libvlc_media_player_t libvlc_media_player_t;
                ^~~~~~~~~~~~~~~~~~~~~
CMakeFiles/cantata.dir/build.make:310: recipe for target 'CMakeFiles/cantata.dir/mpd-interface/httpstream.cpp.o' failed
make[2]: *** [CMakeFiles/cantata.dir/mpd-interface/httpstream.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Version Info**
 - OS: Ubuntu 18.04
 - Cantata Version: git
 - MPD Version: 0.21git
 - CMake options (other than default): -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_AVAHI=OFF -DENABLE_LIBVLC=ON

**Comment by mbouron** [comment]
Sorry for the regression. I will be more careful to test both backends next time.
