### ISSUE TITLE
Remember that dynamic playlist was enabled in old session, resume in new session

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [CDrummond/cantata#1385]
**Is your feature request related to a problem? Please describe.**
- Currently, I have to manually reenable dynamic playlist when starting a new session.
- Enabling dynamic playlist clears queued tracks first, instead of just adding new tracks to the current list.

**Describe the solution you'd like**
I'd like Cantata to resume dynamic playlist from last session and without clearing the old queue/playlist.

**Comment by CDrummond** [comment]
Dynamic playlists are controlled via a separate `cantata-dynamic` perrl script. You can run this as a system service - see section 12 of [README](https://raw.githubusercontent.com/CDrummond/cantata/master/README). When run this way, the script is still functional when cantata terminates. Cantata will detect when this script is run in server mode, and act accordingly. 

Cantata does not persist any MPD state between runs, so it does not know the name of the loaded playlist. Also, `cantata-dynamic` itself clears the playlist upon start - and I don't feel like changing this.
