### ISSUE TITLE
Album titles are cut on certain characters

### ISSUE THREAD

**Issue by Cybolic** [CDrummond/cantata#1386]
**Describe the bug**
For album titles such as `Edge | Sweet Music from the Game` or `Iron Sky | The Original Film Soundtrack` the album is listed as `Sweet Music from the Game` and `The Original Film Soundtrack` respectively. This also applies to the playlist, the cover art search dialogue and the sort order so the issue seems to be in reading the tag.
I haven't experienced it with other characters than `|`, so it might only apply to this case.

The issue also doesn't appear in ncmpcpp, so doesn't appear to be an issue with mpd.

**To Reproduce**
1. Add a track with an album tag containing `|`
4. See the wrong album title in the browser, playlist, etc.

**Expected behavior**
The full tag should be shown.

**Version Info**
 - OS: Linux (Arch)
 - Cantata Version: 2.3.2
 - MPD Version: 0.20.21

**Comment by CDrummond** [comment]
Works for me. I just used kid3-qt to change a FLAC's album name to `Wibble | Wobble` - and that is what I see in the Library and Queue.

Cantata get's its song details (album, artist, track, etc.) from MPD - so if there is an error, its more than likely there.
