### ISSUE TITLE
import ratings

### ISSUE THREAD

**Issue by labatts** [CDrummond/cantata#1387]
Is there a way to import ratings?  I have a rather large library, and it is not realistic for me to change them one at a time.  I tried (from clementine) both dragging lists of songs over and importing playlists via the folders tab.  This worked in that I could play the songs, but **I could not change / add a rating.**  The rating field is un-clickable.  I can only do this if I find the song through the Cantata library. 

Hope this makes sense.

**Comment by Thaodan** [comment]
You would need to import the clementine ratings into the mpd stickers db. Cantata doesn't do anything with the stickers db of mpd except read/write when the user changes the "rating" in the ui.

**Comment by labatts** [comment]
> You would need to import the clementine ratings into the mpd stickers db.

Okay, thanks.  Can you point me to documentation for how to do that? (Or tell me lol)

**Comment by CDrummond** [comment]
Cantata can read ratings from the files - and then add to the sticker DB. So you could; get clementine to save ratings to file; have Cantata read the ratings. Probably not the best method though, and quite slow I would have thought.

Another user queried about importing Amarok ratings - and he created a script to read from the Amarok DB and write to MPD's sticker DB. See https://github.com/CDrummond/cantata/issues/1333
