### ISSUE TITLE
Cantata library misses entries from MPD library

### ISSUE THREAD

**Issue by Dougal66** [CDrummond/cantata#1389]
I am running Cantata in "Personal mode", so Cantata controls MPD. I did not setup MPD myself. Also I have a very large music collection (122k songs). MPD seems to have added all of my songs to its database. I can access all songs from my collection with Cantata via the "Folders" view, also I seem to be able to find all songs via the "Search" view. However in the "Library" view Cantata has not included all songs that are accessible via the other views. It appears that some Folders from my collection are missing here. So the "find" function in "Library" view misses a lot of entries that the "Search" view actually does pick up.

When I refresh the MPD database manually, Cantata passes on an error message: "MPD reported the following error: No such directory". However as far as I can tell the MPD library does get fully updated, it is only Cantata's internal Library view that is incomplete.

I should add that all Folders in my collection have exactly the same permissions.

**Version Info**
 - OS: Fedora 28
 - Cantata Version: 2.3.1 (installed from official repository)
 - MPD Version: 0.20.16

**Comment by CDrummond** [comment]
I'm sorry, but I'm 99.999% sure this is an issue with your system - filenames, or tags. Cantata gets its music listing from MPD. The Library view is a view based upon tags (with limited tag guessing if some are missing). If tags are incorrect, then this will be incorrect.

Which songs are missing? Please find **one** specific example of a song that is not in the library, but is in the search. The music file of the song - does it have correct tags?

You say the "find" in Library misses it - but is the song **listed** in the Library? If not, then of course find will not find it.

You say you see it in Folders view - but not which view. the MPD folders, or your home folders?

**Comment by Dougal66** [comment]
Thanks for the quick answer and sorry for expressing myself inaccurately. The songs that are missing in the Library view are not listed there. The problem isn't with the search there. In the Folders view, I see the songs in the MPD folders. The problem really is that they exist in the MPD library, but not in the Cantata "Library" view. I have added two screenshots to demonstrate. The Cantata Library only lists one Black Keys album, while the Search view shows two others in the visible part of the screen (5 in all). 

A third screenshot shows that there is nothing wrong with the tags. Actually I have another setup on a different machine running exactly the same software (Fedora 28) where this problem doesn't occur the difference being that on that other machine, I set up mpd myself. The mp3 library that is causing the problem is just copied from that other machine onto my laptop where things don't work when using this "personal mode". Therefore my guess is it must have something to do with the way that Cantata sets up MPD... Also there is the issue of this strange MPD error message... 
![screenshot_20181009_234735](https://user-images.githubusercontent.com/43905421/46701465-0a61c700-cc20-11e8-89c3-d57663df39e3.png)
![screenshot_20181009_234824](https://user-images.githubusercontent.com/43905421/46701473-1188d500-cc20-11e8-9d9a-ac8be9ba2bf1.png)
![screenshot_20181009_235250](https://user-images.githubusercontent.com/43905421/46701479-164d8900-cc20-11e8-874e-8ff9c8834dec.png)

**Comment by Dougal66** [comment]
Here's another screenshot. You can see it is the MPD virtual file system that contains the album that the Cantata Library view does not list.

![screenshot_20181010_000810](https://user-images.githubusercontent.com/43905421/46701641-b0adcc80-cc20-11e8-836e-09487b99bf83.png)

**Comment by Dougal66** [comment]
Finally: I can't be 100% sure, because my mp3 db is so large. However it looks very strongly as though the Cantata Library view is missing all mp3 out of a certain top level directory in my file system. In the screenshot below it would be the "Incoming" directory as well as a subdirectory under downloads. There is absolutely no reason why _all_ mp3 in these directories would be tagged wrongly, while in other directories they would all be tagged correctly. Also it is always whole albums that are missing, which also makes the "tags are the reason" explanation unlikely.

![screenshot_20181010_001635](https://user-images.githubusercontent.com/43905421/46701953-c8398500-cc21-11e8-9d3a-f824c5f9d426.png)

**Comment by Dougal66** [comment]
Even before I noticed about the missing entries in the Cantata Library view, I wondered about the error message below. It only appears as a consequence of a manual refresh, not during the initialization of the mpd library. The only directories that I am responsible for myself here are the music library directories. These have permission for everybody to do everything. I double checked that and did another chown  -R just to stay safe. 
Initially I thought I could find out why this is happening myself by looking at the mpd.log. But Cantata sets it up to write to /dev/null/ and when I changed that to a file on the filesystem, Cantata "couldn't connect to Personal" or some such was the error message.

![screenshot_20181010_083628](https://user-images.githubusercontent.com/43905421/46717450-57698b80-cc68-11e8-8f48-bbcfe247a2eb.png)

**Comment by CDrummond** [comment]
Usually the "No such directory" error comes when MPD has a playlist_directory configured that does not exist. In this 'Personal' instance, Cantata _should_ be setting this to `~/.local/share/cantata/mpd/playlists` Does this directory exist? It should be created by Cantata. Does `~/.local/share/cantata/mpd/mpd.conf` specify `/home/USER/.local/share/cantata/mpd/playlists` for `playlist_directory` ??

---

Cantata's Library view comes from an internal SQLite cache of MPD's listing. You can inspect this by using (e.g.) sqlitebrowser. The DB file is located in `~/.local/share/cantata/library` and will be named something like `_home_USER_.local_share_cantata_mpd_socket.sql`

Replacing DBFILE (with path to sqlite DB, as above) and PATH (to part of path to missing file), what does the following return:

```
sqlite3 -column -header DBFILE "select file,artistId,album,albumId from songs where file like '%PATH%'"
```

e.g.
```
sqlite3 -column -header _home_dougal66_.local_share_cantata_mpd_socket.sql "select file,artistId,album,albumId from songs where file like '%Incoming%'"
```

**Comment by Dougal66** [comment]
Thanks again. I am travelling at the moment and don't have access to the machine until tomorrow evening. I will do what you suggest and post the results then.

I can say though that I had already noticed your response to someone else in the past who complained about the "No such directory" error. Therefore I did carefully check that Cantata created the playlists directory and a correct corresponding entry in the mpd.conf. This is the case, so in this instance there must be another reason for the "No such directory" error message.

**Comment by CDrummond** [comment]
Yeah, I was thinking that too - as the playlists directory should automatically be created. When you do run on your system, please run with debug - this might tell where that error is coming from.

The following will cause Cantata to log MPD comms, and response parsing, to `~/.cache/cantata/cantata.log` After you have run, and seen the "No such directory" error, stop Cantata, edit this file to remove anything personal, and attach to this bug report.

```
cantata --debug=mpd,mpdparse --debug-to-file
```

**Comment by Dougal66** [comment]
So I ran Cantata with the debug options and my interpretation of the log is that there seems to be an inconsistency in how MPD and Cantata treat zip files...? In (at least) one of the subdirectories in my music collection, I failed to delete the zip file that originally contained the mp3s after extracting them. This is where the database refresh gets interrupted with an error message. I will remove all zips from my collection and see if that changes anything.

[cantata-modified.log](https://github.com/CDrummond/cantata/files/2469549/cantata-modified.log)

**Comment by Dougal66** [comment]
Yes, that did solve the problem. After removing the zips the database refresh no longer stops with an error and the Cantata library view then also has all entries that MPD does.
Maybe Cantata should set up MPD to ignore zip files?

Anyway thanks for helping me with this.

**Comment by CDrummond** [comment]
Think I _might_ have spotted the issue. Can you build cantata/master yourself? And place the ZIP files back? If so, edit `mpd-interface/mpdconnection.cpp` and change line 2126 from:

```
        for (const QString &sub: subDirs) {
            if (!recursivelyListDir(sub, songs)) {
                return false;
            }
        }
```

to:

```
        for (const QString &sub: subDirs) {
            recursivelyListDir(sub, songs);
        }
```

...and then rebuild cantata, refresh DB

**Comment by Dougal66** [comment]
I am not a developer and have very rarely built an application myself. If you can point me to a howto, so that I don't have to re-google the necessary steps, I'd be happy to give it a try over the weekend.

**Comment by CDrummond** [comment]
The [INSTALL](https://raw.githubusercontent.com/CDrummond/cantata/master/INSTALL) should contain the required info.

But, if its going to be a hassle, don't bother - I can try myself this weekend.
