### ISSUE TITLE
Add option to show notification when starting or pausing playback 

### ISSUE THREAD

**Issue by nvllsvm** [CDrummond/cantata#1391]
**Is your feature request related to a problem? Please describe.**
When logging into my machine, I will often use a keyboard shortcut to start playback (standard play/pause key). Since some of my music contains silent parts, it's not clear whether playback has started or if the playlist is empty.

**Describe the solution you'd like**
Like the existing option to enable notifications when changing tracks, I would like the ability to enable notifications when starting, stopping, and pausing playback.

**Describe alternatives you've considered**
On Linux, I'm currently using [eworm-de/mpd-notification](https://github.com/eworm-de/mpd-notification) to handle all notifications.

On macOS, I have no alternative.

**Additional context**
Example of what I get on Linux with mpd-notification
![pause](https://user-images.githubusercontent.com/6550543/46923007-a0f70500-cfdf-11e8-9f8c-782c7352c906.png)
![starting](https://user-images.githubusercontent.com/6550543/46923008-a0f70500-cfdf-11e8-9eac-7f12cb52dbcd.png)
![stopped](https://user-images.githubusercontent.com/6550543/46923009-a0f70500-cfdf-11e8-861b-a42cd37646cf.png)

**Comment by CDrummond** [comment]
Not 100% convinced of its usefulness, but should not be too hard to do. Will think about this for 2.4

**Comment by CDrummond** [comment]
Sorry, but I have decided to no longer produce mac and windows builds - as I use neither OSs. Therefore, features/issues that specific to these are not on my list of priorities. However, please feel free to implement and submit a pull request.
