### ISSUE TITLE
Covers are loaded only for first few albums

### ISSUE THREAD

**Issue by drtebi** [CDrummond/cantata#1395]
I am having trouble with cantata 2.3.2, installed through Arch Linux packages.

Once I have my connection setup, and configure album grid view, cantata will load album covers for the first 40 albums or so, and then stop loading any further albums. 

This happens with a locally installed mpd server (0.20.21) as well as with my raspberry based streamer (runeaudio). 

I tried to uninstall cantata and remove all traces (sql DB, cache files etc.), and re-install, but without luck.

I ran cantata with the `cantata --debug=covers-verbose` command, and results look like this for all covers that are not showing up:
```
2018-10-20 02:28:19 - MpdLibraryModel "GUI" data "Struttin (1970)" 3 365
2018-10-20 02:28:19 - ActionItemDelegate "GUI" paint Cover song "Meters" "Struttin" "NAS/Sedna/M/Meters - Struttin/Meters - 01 - Chicken Strut.flac" "Struttin (1970)" true
2018-10-20 02:28:19 - Covers "GUI" get "Meters" "Struttin" "" "" false false 312 false
2018-10-20 02:28:19 - Covers "GUI" get Use default pixmap
```
All music is located on a network share, e.g. a network share is mounted in `/mnt/NAS` on the Raspberry, and on `~/Music` on the laptop. I can access the missing covers from the Raspberry directly by URL.

Any help would greatly be appreciated.

**Comment by CDrummond** [comment]
I have just tried, with a clean cache, etc. and Cantata **does** load all covers.

However, I have added extra debug to the code. Please checkout git/master and try again - with same --debug flag.

**Comment by drtebi** [comment]
I will try it now.
Using the "git" version from [Arch Linux AUR](https://aur.archlinux.org/packages/cantata-git/) uses the latest git/master, correct? Or do I need to do a manual install?

**Comment by drtebi** [comment]
I have made an interesting discovery... I checked the nginx access logs, and I see a lot of failed requests like this:
```
10.0.0.31 - - [20/Oct/2018:14:09:20 -0700] "GET /covers/NAS/Sedna/A/ACDC%20-%20Back%20In%20Black/folder.jpg.png HTTP/1.1" 200 8599 "-" "cantata 2.3.3"
```
or:
```
10.0.0.31 - - [20/Oct/2018:14:09:20 -0700] "GET /covers/NAS/Sedna/A/ACDC%20-%20Back%20In%20Black/folder.jpg.jpg HTTP/1.1" 200 8599 "-" "cantata 2.3.3"
```

I now opened `~/config/cantata/cantata.config` and changed `coverFilename` to `folder` (note: no extension). And now the covers are slowly pouring in!

My problem is solved... but I wonder if this is a work-around for my specific problem, or if there is an extra "jpg" extension added in the code somewhere... something you may want to check.

**Comment by CDrummond** [comment]
No. `coverFilename` should have no extension. Cantata (for HTTP urls) will try both .jpg and .png. Also, when downloading it will detect the filetype and add an extension.

**Comment by drtebi** [comment]
I understand, but at first I did not have anything in `coverFilename`—by default the config file just has:
```coverFilename=```
... and that is what I had, but what apparently caused the errors posted above. This is why I mentioned this—to me it looks like accidentally there is a "double-extension" somewhere produced in the code. But I could be wrong. I am just pointing out the possibility.

Thank you for all your prompt responses, I am very happy with cantata now, excellent MPD client.

**Comment by drtebi** [comment]
Me once again... 
You see, I didn't even realize that there is a place in the UI to configure the name for cover files. But if I understand correctly, the "Filename" value in the UI will end up as the "coverFilename" value in the config file, correct? Well, when I was not able to get any covers, this value was blank (which, I assume, was then also blank in the UI).
By the way, I assumed that the "Filename" value in the UI only applied to downloaded covers... not to the covers to look for within the album directory.

I honestly don't know how it went wrong with my install at first. I am just reporting what happened... please don't feel like I am criticizing anything... If you like, I can start from zero again and report exactly what happens... what the "coverFilename" value is, the UI value, and when it works and when it doesn't.
