### ISSUE TITLE
Revisit: Use of ...sort metadata tags in libray view

### ISSUE THREAD

**Issue by 111MilesToGo** [CDrummond/cantata#1396]
Hi Craig, Thanks a lot for Cantata and for continuing to maintain it. Marvellous!

I should like to understand more about Cantata's library view, in particular in the Artist -> Album -> Tracks view. (I don't use the Composer grouping yet.)

Wrt mpd, I understand from the documentation that mpd is reading a lot of tags, a.o. albumartist, albumartistsort, artist, artistsort, album, albumsort, composer. I guess all of them are passed to a client. I don't have a metadata-to-use line in my mpd.conf, so the default behavior isn't altered.

Could you please explain in detail how Cantata arrives at its library view? What tags are used, in what order of precedence, and what is displayed in the GUI? From my tests, I think to see it this way:
(1) albumartistsort > albumartist > artistsort > artist, or is it albumartistsort > artistsort > albumartist > artist? If one of the artist...sort is present, it is what is used for sorting, but the display shows the artist... tag. Great!
(2) I was not successful with my albumsort tags. In fact, I could not see Cantata using them, it seems to just use album. When I have albumsort only, Cantata gives me an unknown album; when I have both album and albumsort, Cantata shows album.

However, I do see a great use for both album and albumsort tags. For a single-disc album, the album tag is fully sufficient. For a multi-disc box set, I am using album to contain the overall album name, e.g. "The Complete Columbia Recordings" by Miles Davis. My albumsort tags would indicate the disc number within the box set, e.g. "The Complete Columbia Recordings (Disc 1)". Similarly, I am handling live recordings, e.g. by the Grateful Dead: album would be s.th. like "1977-05-08 Barton Hall, Cornell, Ithaca, NY", and albumsort would be "1977-05-08 Barton Hall, Cornell, Ithaca, NY (1st Set)" and "1977-05-08 Barton Hall, Cornell, Ithaca, NY (2nd Set)". I admit, though, that this use of albumsort differs from the typical use of artistsort and albumartistsort (Bach, Johann Sebastian for Johann Sebastian Bach).

Thus, I would like to ask whether and how Cantata uses the albumsort tag as compared to the album tag. And I would like to propose an extension to the library viewer of Cantata: Would you consider introducing another level of fold-out's, i.e. Artist -> Album -> Tracks for single-disc albums, and Artist -> Album -> albumsort -> Tracks for multi-disc box sets?

Sorry, if this is too long or unclear a write-up, and sorry if this is asking a lot from you. I am happy to clarify and explain as well as to discuss with you.

Again, I love Linux and I love Cantata! And whatever other audio apps I will have, Cantata will stick. Here is what I am up to right now: I do dislike Windows (even hate the Big M from time to time). But I am giving the new kid on the block Roon a try, and it looks darn good. I am currently looking for a best practice to get my music library tagging, Cantata and Roon aligned. In that respect, how to display multi-disc box sets is an issue.

Thanks a lot in advance for feedback, happy to discuss with you!

**Comment by 111MilesToGo** [comment]
Thanks for your immediate feedback. I will return by tomorrow, so please keep this thread open. I am e-mailing you since I have no access to github at this moment. I will get to github tomorrow.

What I can say right away is: mpd has all relevant tags, and Cantata does get them. Cantata works fine wrt the ...sort tags, i.e. just according to the rules. I understand things better now in that the three ...sort tags (albumsort, albumartistsort, artistsort) really are just "behind the scenes“, i.e. they are used only for sorting and not for any display. I was thinking of bending the rules by looking for albumsort to be shown in the case of multi-disc box sets, but that‘s illegal.

However, I find that at least some if not all of the ...sort tags seem to be truncated (last character[s] missing) in Cantata‘s data base. I will look at this in more detail and give you examples tomorrow.

Just some remarks with respect to Roon:
- Yes, it is awfully expensive, and the 14-day test drive is too short. The one thing that captivated me at once is: The audio setup is a breeze, and it seems to be flawless for all PCM and DSD (native and DoP); resampling sticks to the 44.1 versus 48 kHz ladders when downsampling for a DAC with limited bitrate capability. Whether all the browsing bells and whistles are worth the price remains to be seen. I claim my music collection to be meticulously tagged, and I know more about my (jazz) artists and (classical) composers than the Roon texts have; but for areas less known to me (rock) they are some point of entry. In the future, Roon would be greatest if both Quobuz and Tidal get integrated - more expenses...
- foobar2000 works well when set up properly, but it takes a lot of manual switching between different DACs and between PCM vs. DSD.
- mpd works great for PCM and DoP (my Chord Hugo 2 is not taken care of yet in the quirks.c kernel piece for native DSD); and - too bad - downsampling for my AudioQuest DragonFly Red does not follow the 44.1/48 ladders.

I‘ll return to github!

Am 23.10.2018 um 09:08 schrieb CraigD <notifications@github.com<mailto:notifications@github.com>>:


Been a LONG time since this was coded, but...

  1.  Cantata only 'caches' one artist sort; if album artist sort is set this is used, if artist sort is set then this is used, otherwise the 'Artist & Album Sorting' from the UI is used. By 'set' I mean passed from MPD to Cantata
  2.  Likewise, for albums if album sort is set this is used, otherwise the 'Artist & Album Sorting' from the UI is used.

These 2 are stored in Cantata's SQL cache of the MPD listing.

When the list of artists is requested (either all, or under a Genre group), Cantata will sort via the sort tags (if present), falling back to the albumartist (if set) or artist. eg. Order of precedence is sort value from SQL cache, album artist, artist

Albums have multiple sort options (Album/Artist,/Year, Album/Year/Artist, etc). Album/Artist,/Year would first sort on album sort from SQL cache (if set), album name otherwise. If these are the same, it would then sort via artists (using rules above).

I'm not sure, but I think you need to configure MPD's metadata_to_use so that it sends all of these. To check what values Cantata has, you can query its SQL cache.

You can inspect this by using (e.g.) sqlitebrowser. The DB file is located in ~/.local/share/cantata/library and will be named something like home_USER.local_share_cantata_mpd_socket.sql

Replacing DBFILE (with path to sqlite DB, as above) and PATH (to part of path to missing file), what does the following return:

sqlite3 -column -header DBFILE "select file,artistSort,albumSort from songs where (artistSort is not null or albumSort is not null"


________________________________

Roon is hideously expensive, why not try Logitech Media Server? It's what I've personally being using for the last year (I'm even working on a mobile friendly skin for it)

**Comment by 111MilesToGo** [comment]
Back again. I wanted to give you examples of metadata (1) as mpd has them, and (2) as Cantata has them.

One (somewhat artificial) track as mpd sees it:
`nc -N localhost 6600`
`OK MPD 0.20.0`
`currentsong`
`file: XTest/Maier, Anton/Maier - Test Album BoxSet [2010 CD]/Disc 1/03 - Brandenburg Concerto No. 1 in F major, BWV 1046 - 3. Allegro.flac`
`Last-Modified: 2018-10-23T08:27:58Z`
`Title: Brandenburg Concerto No. 1 in F major, BWV 1046 - 3. Allegro`
`Album: Maier - Test Album BoxSet [2010 CD]`
`AlbumArtist: Anton Maier`
`AlbumArtistSort: Maier, Anton`
`AlbumSort: Maier - Test Album BoxSet [2010 CD] (Disc 2)`
`Artist: Anton Bela Maier`
`ArtistSort: Maier, Anton Bela`
`Composer: Johann Sebastian Bach`
`Disc: 1`
`Genre: Classical`
`Performer: Concentus Musicus Wien; Nikolaus Harnoncourt (conductor)`
`Date: 1964`
`Track: 3`
`Time: 280`
`duration: 280.306`
`Pos: 230`
`Id: 231`
`OK`

And this is how it shows up in Cantata's cached sql database:
`sqlite3 -column -header 0.0.0.0_6600.sql "select * from songs where (file is 'XTest/Maier, Anton/Maier - Test Album BoxSet [2010 CD]/Disc 1/03 - Brandenburg Concerto No. 1 in F major, BWV 1046 - 3. Allegro.flac')"`
`file         XTest/Maier, Anton/Maier - Test Album BoxSet [2010 CD]/Disc 1/03 - Brandenburg Concerto No. 1 in F major, BWV 1046 - 3. Allegro.flac`
`artist       Anton Bela Maier`
`artistId     Anton Maier`
`albumArtist  Anton Maier`
`artistSort   Maier, Anton`
`composer     Johann Sebastian Bach`
`album        `
`albumId      Maier - Test Album BoxSet [2010 CD]`
`albumSort    Maier - Test Album BoxSet [2010 CD] (Disc 2)`
`title        Brandenburg Concerto No. 1 in F major, BWV 1046 - 3. Allegro`
`genre1       Classical`
`genre2       -`
`genre3       -`
`genre4       -`
`track        3`
`disc         1`
`time         280`
`year         1964`
`origYear     0`
`type         0`
`lastModified 1540283278`

Hope I did edit the outputs nicely enough... I am attaching two text files with the original outputs:
[text1.txt](https://github.com/CDrummond/cantata/files/2515459/text1.txt)
[text2.txt](https://github.com/CDrummond/cantata/files/2515461/text2.txt)

Now, the metadata seem to have transferred correctly (without truncation) from mpd to Cantata. Please take a look. I particular, Cantata's album tag is empty.

I don't know how I got to observe that there were truncations in Cantata two days ago: I have two Linux installations, openSUSE Tumbleweed and Manjaro. Both have mpd/Cantata installed with identical mpd.conf, and both do access the same audio collection stored on one partition on my disk. Two days ago, I looked at my Manjaro Cantata; today I looked at my Tumbleweed. I might look again in Manjaro when I find the time.

I summary, for the time being, my question regarding those ...sort tags is answered. I shouldn't want to bend the rules...

**Comment by 111MilesToGo** [comment]
As we were talking about mpd + Cantata versus Roon, there is an idea that came to my mind. I mentioned that Roon does the audio part out of the  box, automatically and (at least as much as I could see until now) perfectly.

There is this one issue that I and others have with mpd. It can use various resamplers ("internal", soxr, libsamplerate). But it does not adhere to the 44.1 versus 48 kHz ladders when downsampling for a DAC that cannot do all samplerates. I posted about this in the mpd forum, cf. [https://forum.musicpd.org/viewtopic.php?f=7&t=7297](url) and got an answer by Max Kellermann (mpd maintainer) stating that this is a feature request, cf. [https://github.com/MusicPlayerDaemon/MPD/issues/220](url), but there is not enough time on his side and there were no volunteers.

My idea is ... would you mind considering to contribute to mpd by making the resamplers chose target bitrates within the 44.1 vs. 48 kHz ladders, i.e. by powers of 2? I think many people out there would be happy since (1) the correct choice of resampling factors is positive under audiophile aspects, (2) resamplers should be much faster then, i.e. decreasing the computer load, and (3) it would bring mpd + Cantata up to the level of Roon in this respect.

Finally, just as a side remark, let me mention that there is another item missing in mpd, which would lift it above Roon wrt audio quality: mpd can't decode the infamous HDCD format - you know, this late 1990's format of cramming 20-bit into 16-bit 44.1k by Prof. Keith Johnson / Pacific Microsonics. Those Pacific Microsonics A-to-D converters are used still today since their sound quality is just great even without HDCD. And SO many Grateful Dead fans and many others would love to get HDCD decoded on-the-fly by a great audio player (foobar2000 is the only one except for Windows Media Player). Just thought to mention this here, please forget about it as soon as you've read it...

**Comment by CDrummond** [comment]
Cantata uses the "albumId" column. Only if albumId!=album name is there a value for album. i.e. If an albums has musicbrainz albumid, then this is used for albumId and album will have its name. This is just to save duplicating data.

Sorry, but I'm no mpd developer - I do not know the codebase. I suggest you file an issue there.

Closing this 'issue' now, as its not an issue.

**Comment by 111MilesToGo** [comment]
Thanks a lot, your help and responsiveness are gratefully appreciated. Of course, I fully understand your not being an mpd developer.
