### ISSUE TITLE
Pixel always seeing zero available free space

### ISSUE THREAD

**Issue by tbohaning** [CDrummond/cantata#1397]
Hi,

I'm trying to use Cantata to update my Pixel's music library. The Pixel has 15G of free space but Cantata always reads it as Zero free space. It's running Android 9...

What other information would help???

**Comment by CDrummond** [comment]
No idea. Cantata uses libMTP to talk to MTP devices. Just tried with my Android, and it can't connect. Probably a libMTP or Android issue - Cantata's MTP code has not been touched in quite a while.

**Comment by tbohaning** [comment]
Found the issue... It's not Cantata... I'm running Kubuntu 18.10... It required uncommenting user_allow_other in /etc/fuse.conf and rebooting...

Sorry to bother you...

**Comment by CDrummond** [comment]
No problem, glad you resolved it. And it did at least make me re-look at the code, and fix an issue :-)
