### ISSUE TITLE
Where is the Main Menu in Windows 10 64 bit?

### ISSUE THREAD

**Issue by merlinuwe** [CDrummond/cantata#1399]
I use Cantata 2.3.2 and the former available menu is lost. Please see screenshot.

![cantatawithoutmenu](https://user-images.githubusercontent.com/4138869/47620239-5057cf80-dae8-11e8-9f67-bbcfe3f7b707.jpg)

**Comment by Thaodan** [comment]
Its in the hamburger menu (the 
three vertical lines in the 
corner).
