### ISSUE TITLE
[Feature Request] Normalize as ReplayGain alternative after transcoding

### ISSUE THREAD

**Issue by Tichy** [CDrummond/cantata#1401]
**Is your feature request related to a problem? Please describe.**
Some audio players, especially car infotainment systems, doesn't support ReplayGain. That causes a mess with volumes when using playlists and random.

**Describe the solution you'd like**
There's a tool called normalize-audio http://normalize.nongnu.org/ which can be used as an alternative for replay gain. When called with the -b (batch) option, it uses the average value of all audio files passed, and that could also be an alternative for the album replay gain tag.
Another solution that don't require another package, is by using ffmpeg https://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg
Having his, you could configure your car's usb drive as a device to transcode files in MP3 using normalize instead of replaygain.

**Comment by CDrummond** [comment]
No. Sorry. The transcoding code is single track, changing to be aware of albums is too much hassle. Therefore, I'm not to sure on the usefulness of this. Either way, its not a feature I'd use, or want to spend time on. So closing.

However, as always, feel free to create a pull request.
