### ISSUE TITLE
[Feature Request] Append and Play button

### ISSUE THREAD

**Issue by kmontag** [CDrummond/cantata#1402]
"Append and Play" is usually the action I'm looking for when adding tracks to the queue. However, this currently requires right-clicking and going into the context menu (or configuring a keyboard shortcut).

Would it be possible to add an Append and Play button next to the current play/append popups? Or alternately, to make the default append and/or double-click actions on library items configurable?

Thanks for an excellent client!

**Comment by CDrummond** [comment]
The two buttons that show on mouse-over have been that way since (I think) the 1st release, and I have no intention of adding any more. Changing the behavior would be possible, but I'd worry that I'd miss one place, more bugs, etc. So, sorry for now I'm happy to leave as is.
