### ISSUE TITLE
Soundcloud Property based search

### ISSUE THREAD

**Issue by Frozen-byte** [CDrummond/cantata#1403]
**Is your feature request related to a problem? Please describe.**
I would like to listen to specific Soundcloud Playlists/Artists/Stations in Cantata

**Describe the solution you'd like**
Improve the search bar for Soundcloud as implemented in the Search-Tab: 
![image](https://user-images.githubusercontent.com/3965439/48353638-35f92680-e690-11e8-81ba-523bf17b60fc.png)

**Describe alternatives you've considered**
also im fine with syntax search like: "Artist:foo;Playlist:bar"

**Additional context**
My intention was the following Id like to hear everything to the User "auvic" (https://soundcloud.com/auvicmusic)
When I search for "auvic" or "auvicmusic" I do not find his work but random other tracks.

**Comment by CDrummond** [comment]
Should be possible. SoundCloud supports search on ;  /users, /tracks, /playlists  Currently Cantata always searches on /tracks.

**Comment by CDrummond** [comment]
I tried with playlists - and decoding these, etc, is just more work than I have time for. So, sorry - I'm closing this as wont-fix (as I won't be doing this). But, please feel free to implement and send a pull request.
