### ISSUE TITLE
Podcast stop after a few minutes

### ISSUE THREAD

**Issue by buntupana** [CDrummond/cantata#1405]
**Describe the bug**
Podcast streaming stop after a few minutes playing even if I download it.

**To Reproduce**
1. Add podcast subscription "https://fapi-top.prisasd.com/podcast/playser/1_playser/itunestfp/oh_my_lol_la_noche_de_ortega/audios.xml"
2. Play any podcast

**Expected behavior**

**Version Info**
 - OS: KDE Neon
 - Cantata Version: 2.2.0
 - MPD Version: 0.20.18-1build1

**Comment by CDrummond** [comment]
Podcast playback is handled my MPD. All Cantata does is pass the stream URL to MPD. I have tried the above podcast, and see the same behaviour. I tried with VLC, and whilst this plays it reports:

```
[00007f07cc001870] http stream error: local stream 1 error: Cancellation (0x8)
[00007f07cc001870] http stream error: peer error: No error (0x0)
[00007f07cc192fc0] gnutls tls client error: The TLS connection was non-properly terminated.
[00007f07cc001870] http stream error: peer stream 1 error: Cancellation (0x8)
```

So, perhaps MPD does not like these issues. If you use Cantata's time slider, and slide past the time where the issue occurs - it seems to play OK from then on. Didn't play the whole stream, as my Spanish is not that great.

Still not a Cantata issue.
