### ISSUE TITLE
Ability to copy the current "artist - track" to the clipboard

### ISSUE THREAD

**Issue by dtcyganok** [CDrummond/cantata#1409]
Often when I hear a song on the radio that I like, I want to save the track name, but I could not find a convenient way to do it.

Ability to select the current "artist - track" with mouse and then copy with ctrl-c.
Alternatively add button which inserts the current "artist - track" to clipboard.

P.S. Thanks for the great mpd client!

**Comment by CDrummond** [comment]
Right click on artist/song label in toolbar.
