### ISSUE TITLE
Add search box in library tab

### ISSUE THREAD

**Issue by buntupana** [CDrummond/cantata#1411]
I think is much better for usability to have a search box in the library tab instead to change tab each time

I would like to have a search box in the library tab, and show the results in a tree like the library tab shows the information. Artist -> Album -> Song. Like Amarok does.

If for some reason is not possible it would be great have the tree in the Search tab.

**Comment by CDrummond** [comment]
There already is one.

**Comment by buntupana** [comment]
I can't find the search box in the library tab, I can see just the tab Search.

**Comment by thechitowncubs** [comment]
You can search the library by just typing but i would agree a filter like clementine would be sweet.

**Comment by afoh92** [comment]
Indeed, with a tree view, as a filter within library list or as a tree view in its own search panel, displaying albums and tracks. Because the current search view only displays tracks as items, not ordered or anything, and that makes it difficult to search.

**Comment by buntupana** [comment]
Clementine and Amarok filter solutions are great. It would be awesome having that in Cantata. No need for a search tab, just a search box in library tab and showing result as tree view so no need to change tabs for searching :)

**Comment by cpchan** [comment]
I totally agree with afoh92's comment (https://github.com/CDrummond/cantata/issues/1411#issuecomment-470212673).
