### ISSUE TITLE
[Feature Request] Add support for ListenBrainz scrobbling

### ISSUE THREAD

**Issue by Seqularise** [CDrummond/cantata#1412]
https://listenbrainz.org/

**Comment by CDrummond** [comment]
Reading the docs, supporting this _might_ be trivial. I think all you need to do is edit `scrrobbling/scrobblers.xml` and add `<scrobbler name="ListenBrainz" url="http://proxy.listenbrainz.org"/>` and then using your username and auth token as described in https://listenbrainz.org/lastfm-proxy

Please give this a try, and let me know it it works.

**Comment by Seqularise** [comment]
Can`t sign in.

**Comment by CDrummond** [comment]
Please try with `http://proxy.listenbrainz.org/2.0`

**Comment by Seqularise** [comment]
Can`t sign in again.

**Comment by CDrummond** [comment]
Well, not much I can do then. I'm not about to re-write the code to handle this. I was under the impression it supported the same API, just different URL. If that is not the case, then I'm sorry but I have no time or motivation to implement.

**Comment by Seqularise** [comment]
Nvm, i`ll just import listens from last.fm as usual, thanks for attention.
