### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by tsujan** [CDrummond/cantata#1414]
**Describe the bug**
This is related to https://github.com/CDrummond/cantata/issues/1390 but, in that time, I didn't know that Cantata really crashed because,  unlike other apps, it didn't create a coredump (in `/var/lib/systemd/coredump`).

**To Reproduce**
The crash is random and I can't describe steps to reproduce it. This time, I started Cantata from terminal (`gdb cantata`) and waited:

```
#0  0x00007ffff6f00ca4 in ?? () from /usr/lib/libQt5Network.so.5                                                     
#1  0x00007ffff6eff59b in ?? () from /usr/lib/libQt5Network.so.5                                                     
#2  0x00007ffff5c5e352 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5                                   
#3  0x00007ffff65ade14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5  
#4  0x00007ffff65b56e1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5                
#5  0x00007ffff5c33c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5      
#6  0x00007ffff5c36ccc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()                  
   from /usr/lib/libQt5Core.so.5                                                                                     
#7  0x00007ffff5c879d4 in ?? () from /usr/lib/libQt5Core.so.5                                                        
#8  0x00007ffff3d6c3cf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0                                  
#9  0x00007ffff3d6df89 in ?? () from /usr/lib/libglib-2.0.so.0                                                       
#10 0x00007ffff3d6dfce in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0                                 
#11 0x00007ffff5c86fc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()              
   from /usr/lib/libQt5Core.so.5                                                                                     
#12 0x00007ffff5c328cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5   
#13 0x00007ffff5a7beb9 in QThread::exec() () from /usr/lib/libQt5Core.so.5                                           
#14 0x00007ffff5a85f65 in ?? () from /usr/lib/libQt5Core.so.5                                                        
#15 0x00007ffff6ac0a9d in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ffff5730b23 in clone () from /usr/lib/libc.so.6
```
I don't understand this (poor) trace.

**Version Info**
 - OS: Manjaro Testing (up-to-date)
 - Cantata Version: git-2.3.2.r63.g6e8faee32 (but it happened with some older versions too)
 - MPD Version: 0.21.3
 - CMake options (copy/pasted from Arch's PKGBUILD):
```sh
    cmake ../${pkgname} \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Debug \
        -DENABLE_LIBVLC=OFF
```
Happens with `-DCMAKE_BUILD_TYPE=Release` too.

**Additional context**

See my mistake about systray icon in https://github.com/CDrummond/cantata/issues/1390 -- it was really about a crash (also, it would be nice if Cantata created coredumps).

**Comment by tsujan** [comment]
> Well, not sure what you want me to do about that.

I've encountered such poor traces a few times in some apps I work on. In all cases, the problem was in the app but, in one case, it took me 3 months to find and fix it. So, I don't expect a fix soon.

I just wanted to tell you about it, especially because I'd made a mistake in another report.

**Comment by tsujan** [comment]
> perhaps I should just remove that.

NO, please!

**Comment by CDrummond** [comment]
To be honest, I have no time to look into this. I'm considering dropping Cantata altogether - I no longer actively use it. In fact, all I realy use it for now is the replaygain code.

I've switched from MPD to LMS, which I find much nicer (currently creating a Material HTML5 UI for this).

**Comment by tsujan** [comment]
> To be honest, I have no time to look into this.

I understand. I found a very similar report here: https://github.com/qbittorrent/qBittorrent/issues/9667

> I'm considering dropping Cantata altogether

Oh, I had no idea. Thanks for telling me about that!

**Comment by CDrummond** [comment]
Closing. I'm sure there are issues - but a random crash with no useful info? Sorry, not interested until it can be fixed, or a way to recreate. I'm 100% Cantata is not bug free - but cannot do much with this report.
