### ISSUE TITLE
[Feature request] Play/stop shortcut

### ISSUE THREAD

**Issue by 942u3895hjf** [CDrummond/cantata#1415]
Hello,

Since the demise of Amarok i use Cantata for playing streams. Cantata cannot resume a paused stream, #1058 and #1074, so instead, i would like to have a shortcut for Play/Stop, next to Play/pause. Using that shortcut i can once again use my space bar for pausing and resuming playback of a stream.

How do you think?

Thanks!

**Comment by CDrummond** [comment]
No, sorry.

**Comment by 942u3895hjf** [comment]
Alright.

Do you have another suggestion for a one button shortcut for handling stream pause/stop and play?

Thanks!
