### ISSUE TITLE
[Feature Request] Crop title and artist string or center album cover in notification

### ISSUE THREAD

**Issue by Detoxify92** [CDrummond/cantata#1418]
First of all, thank you developers for this amazing piece of software, I use it everyday. Now, I'm a KDE user and I noticed that when the title + artist + album string is too long, the notification pop up will have more than two lines. This will result in the album covered displayed not being vertically centered in the popup. Here I attach a picture of the issue I describe:
![long](https://user-images.githubusercontent.com/45732251/49696768-b3448800-fbb7-11e8-8f74-99dbfbfe5680.png)
Ideally, there should be only two lines, the one with the "Now playing" and the other containing the song information, which should only be one line long, like this:
![short](https://user-images.githubusercontent.com/45732251/49696783-e5ee8080-fbb7-11e8-810a-57d73ab7185f.png)
So my suggestion is to add an option to crop the second string so it is never longer than one line or to vertically center the album cover (I don't know if this last thing is more related to the KDE notification settings side rather than to cantata). Other music players like Spotify, use the first bold line "Now playing" to show the title of the song, and the second to only display the artist and album. If it is still longer than one line, it will be cropped. Thanks in advance and keep up the good work!

**Comment by CDrummond** [comment]
No. Any cropping should be handled by KDE.
