### ISSUE TITLE
better pausing/resuming of radio

### ISSUE THREAD

**Issue by rkitover** [CDrummond/cantata#1419]
I listen to various internet radio streams like di.fm and ah.fm.

When I resume the station after pause, it plays a minute of buffered audio and then stops. Pressing play again will start the stream at it's current location.

This is all somewhat annoying.

When resuming radio, just restart the stream.

This could be configurable, but most people would not likely want the current behavior.

**Comment by CDrummond** [comment]
Playback is handled by MPD.
