### ISSUE TITLE
MPD Timeout after track was played

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1420]
**Describe the bug**
After playing a track cantata hits a timeout and stops playing.
Its wont continue playing unless I click play.

**To Reproduce**
1. Play track
2. Wait for it to end
3. Hit timeout

**Version Info**
 - OS: Arch Linux
 - Cantata Version: 2.3.2.r62.gc746f2218-1
 - MPD Version: 0.21.3-1

**Logs**
mpd log: https://paste.kde.org/pr2pilotv
cantata debug log: https://paste.kde.org/pjz8jbhdj

**Comment by Thaodan** [comment]
MPD config:
https://paste.kde.org/p6i7vo13m

**Comment by CDrummond** [comment]
What timeout? Cantata does not play songs, MPD does.

**Comment by Thaodan** [comment]
Timeout in cantata Connecting to mpd.

Am 15. Dezember 2018 19:09:27 MEZ schrieb CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
I see no timeout error messages from Cantata in the logs. Even if it did, this would not stop MPD from playing the next (or current) track - MPD is responsible for that.

The "Timeout" messages in cantata's log are stating what the timeout is set to, not that a timeout has occured.

**Comment by CDrummond** [comment]
Closing. No updates for 3 days, and no Catata timeout in logs
