### ISSUE TITLE
Order by second time will reverse it

### ISSUE THREAD

**Issue by Pimmetje** [CDrummond/cantata#1423]
**Is your feature request related to a problem? Please describe.**
I have a ordered playlist. I would like to play in reverse order. Selecting order by track will not reverse it when selecting it a second time. 

**Describe the solution you'd like**
Show the last order state, when selecting reverse the order. 

**Describe alternatives you've considered**
Show both ASC and DESC in sort order

**Comment by CDrummond** [comment]
No, sorry. Cantata does not store the current sort-order, so would have no idea how to reverse. It _could_ do a sort, and if this results in more changes, then do a reverse-sort. However, I have no need for this, and do not wish to spend time on it.

Cantata is open source, so you are free to implement this yourself and submit a pull request.
