### ISSUE TITLE
Strange code

### ISSUE THREAD

**Issue by shlyakpavel** [CDrummond/cantata#1431]
https://github.com/CDrummond/cantata/blob/61b078e67c891d98afa25bd9e7249d04b78b39e9/context/artistview.cpp#L357
This aborts the function so it is not executed. I'd suggest either a cleanup or deleting abort() call

**Comment by CDrummond** [comment]
Submit a pull request - no interested in these 'issues'

**Comment by shlyakpavel** [comment]
@CDrummond just left an issue to understand if this is an intentional behavior or a mistake. I am not familiar enough with the code to get this out

**Comment by CDrummond** [comment]
Then why ask? I'm not going to review every line of the code that I wrote years ago. Sorry for closing so soon (being a bit grumpy today!). I no longer use Cantata, and it is in maintenance mode only.

And how is it strange code? This view works. The abort() is a function a few lines down - it does not abort the function.

**Comment by shlyakpavel** [comment]
@CDrummond there is an `abort()` function in standard library... I thought it is being called, but not the class method
http://www.cplusplus.com/reference/cstdlib/abort/
