### ISSUE TITLE
Odd indentation

### ISSUE THREAD

**Issue by shlyakpavel** [CDrummond/cantata#1433]
https://github.com/CDrummond/cantata/blob/61b078e67c891d98afa25bd9e7249d04b78b39e9/mpd-interface/song.cpp#L316
It looks like either `else` is missing here or the indentation is wrong. Consider checking this :)

**Comment by CDrummond** [comment]
No.

**Comment by shlyakpavel** [comment]
@CDrummond why? :)

**Comment by CDrummond** [comment]
Because I'm being an arse! Sorry, I really need to read things properly - and not look at bug reports when I'm not in a good mood.

Thank you for these reports, and the pull requests. I'll try to be more polite in future,

Once again, sorry.
