### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by shlyakpavel** [CDrummond/cantata#1434]
https://github.com/CDrummond/cantata/blob/61b078e67c891d98afa25bd9e7249d04b78b39e9/playlists/smartplaylistspage.cpp#L432-L436
`RulesPlaylists::constArtistKey` is checked twice (lines 432 and 435)
It is possible that something else should be there instead. Consider reviewing this :)
Have a nice day!

**Comment by CDrummond** [comment]
Code changed to use `RulesPlaylists::constSimilarArtistKey`
