### ISSUE TITLE
Technical Info - Show 16/24/32 Bit info

### ISSUE THREAD

**Issue by Utini2000** [CDrummond/cantata#1435]
**Is your feature request related to a problem? Please describe.**
The technical info already shows bitrate, Hz and file type. Could you also please add the bit depth (16,24 or 32 bit)?

**Comment by CDrummond** [comment]
Added for 2.4.0. Although info seems to be incorrect, showing 24-bits for me - whereas I'm sure my MP3s are 16bit. But MPD is returning `audio: 44100:24:2` which is 44.1Khz, 24bit, stereo

**Comment by ronalde** [comment]
MP3's do not have a (per sample) fixed bit depth. The decoder decides on a per sample bit depth for the decoded PCM audio.
