### ISSUE TITLE
Support loading covers from archives

### ISSUE THREAD

**Issue by bb010g** [CDrummond/cantata#1436]
Currently, Cantata's local cover loading only works for directories, but MPD can [play from archives](https://github.com/MusicPlayerDaemon/MPD/tree/1862a98a44d75d7b48f97612cd19483d2636f8de/src/archive), currently supporting `.bz2` (via libbz2), `.iso` (via libiso9660), and `.zip` (via libzzip). As `.zip` is a common archive format for downloaded music, it'd be nice if cover art was also displayed for at least that format via detection and decoding of those archives. (To reach parity with MPD's detection, only checks for those specific extensions are needed.)

Alternatives would be to continue not supporting covers from archives, to start using the albumart command introduced in MPD version 0.21(MusicPlayerDaemon/MPD#86) as another source for art, or to completely switch over to the albumart command and drop support for older MPD versions.

**Comment by CDrummond** [comment]
I'm not going to add archive handling to Cantata. Too much hassle for a use case I do not have, nor see the need for. Please feel free to implement and send a pull request.

However, Cantata does already support the new albumart command - as implemented by another user.
