### ISSUE TITLE
Cantata version doesn't match git-tag

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1437]
**Describe the bug**
Cantata version doesn't match git-tag (2.3.3 vs 2.4).

**Expected behavior**
Cantata ver should match git-tag.
**Version Info**
 - Cantata Version: 2.3.3-git

**Comment by CDrummond** [comment]
Not sure what 2.3.3-git is - but I have just checked the 2.3.3 release tarball, and it has 2.3.3 as its version.

**Comment by Thaodan** [comment]
Can you please don't close issues so fast?
Anyway: -git I meant I build cantata from git master.
In the about dialog the version is 2.4

**Comment by Thaodan** [comment]
![screenshot_20190107_084556](https://user-images.githubusercontent.com/1747359/50755248-c1d69b80-1258-11e9-88ff-72da12b02281.png)

**Comment by CDrummond** [comment]
git master *is* 2.4
