### ISSUE TITLE
Cantata not remembering Dirble API key

### ISSUE THREAD

**Issue by fajard01** [CDrummond/cantata#1438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
 - OS: [e.g. Linux, macOS, Windows]
 - Cantata Version: [e.g. 2.3.2]
 - MPD Version: [e.g. 0.20.1]
 - CMake options (other than default):

**Additional context**

**Comment by fajard01** [comment]
I'm using Archlinux with the latest mpd. Cantata and mpd are running just fine. I use Dirble so I requested for an API key. I insert the key in Cantata and I then can use Dirble without problem. However every time I close and reopen Cantata, the key is gone and I have to reenter it every time. Is this a Cantata bug? Is there any configuration file I can plug this API key, either in Cantata or mpd?

**Comment by CDrummond** [comment]
Ah! Oops! Saving and loading were **totally** broken! Fixed for 2.4.0
