### ISSUE TITLE
xfce4-notifyd doesn't like unescaped ampersands

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#1439]
Hi, I'm getting errors like this in my log: 

`xfce4-notifyd[835]: Failed to set text 'Jack Parnell & His Orchestra – The Sound Gallery Vol. 2' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;`

I still get the notifications, so this is a minor issue, but I thought I'd pass it along anyway.

**Comment by brendan-pike** [comment]
+1 here, OSSEC constantly sending me emails about it, so rather annoying.
