### ISSUE TITLE
MacOS installation error

### ISSUE THREAD

**Issue by Old-Geek** [CDrummond/cantata#1440]
make install error:

-- 19/34: fixing up '/usr/local/cantata.app/Contents/PlugIns//libqjpeg.dylib'
install_name_tool: string table not at the end of the file (can't be processed) in file: /usr/local/cantata.app/Contents/PlugIns//libqjpeg.dylib
CMake Error at /Macports/share/cmake-3.13/Modules/BundleUtilities.cmake:910 (message):
  Command failed:

   'install_name_tool' '-id' '@executable_path/../Frameworks/libqjpeg.dylib' '/usr/local/cantata.app/Contents/PlugIns//libqjpeg.dylib'
Call Stack (most recent call first):
  /Macports/share/cmake-3.13/Modules/BundleUtilities.cmake:984 (fixup_bundle_item)
  /Volumes/Travail/QTcode/cantata-2.3.3/cmake/DeployQt5.cmake:193 (fixup_bundle)
  cmake_install.cmake:146 (FIXUP_QT5_EXECUTABLE)

make: *** [install] Error 1

**Version Info**
macOS 10.14.2
Cantata Version: 2.3.3
QT Version: 5.12.0 (LTS)
cmake Version: 3.13

**Comment by CDrummond** [comment]
Sorry, but I'm no longer actively supporting non-Linux builds. However, that message looks like an issue on your system - libjpeg.dylib is not a Cantata provided lib.
