### ISSUE TITLE
Remove songs from queue by dragging

### ISSUE THREAD

**Issue by timokoesters** [CDrummond/cantata#1446]
**Problem**
When you have a two panes setup: One with the library and one with the queue, you can add new songs by dragging them into the queue; You can change the order of the songs in the queue by dragging them around; But you can't remove songs by dragging them.

**Solution**
Dragging a song with the mouse out of the queue section into the anywhere in the library section removes it from the queue.

**Alternative solution**
Dragging it out of the queue section to anywhere else, not just in the library section (or even out of the window).

**Comment by CDrummond** [comment]
No, sorry don't like this idea.
