### ISSUE TITLE
xfce4-notifyd not able to show greyscale images

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#1447]
In xfce4, color cover images display fine in notifications, but greyscale covers just display the generic Cantata icon. I get this error in my log: "gdk_pixbuf_new_from_data: assertion 'bits_per_sample == 8' failed". The odd thing is that I'm getting this error even when it's a 24-bit image, as long as the image data itself is greyscale. It's as if Cantata is detecting that the image is greyscale even if it's a color image of greyscale data, and accounting for that when building the icon for the notification. Am I understanding this correctly, or am I completely offbase? If I'm right, is there anything that can be done about this? It seems to me that short of adding a single colored pixel to every one of my black-and-white covers, there's no way I can get them to display in the notifications.

**Comment by CDrummond** [comment]
To be honest, I have no idea - I borrowed the code from (I think) Clementine. However, The code seems to always convert images to ARGB32, then it sets num channels=1 if greyscale. But if its ARGB32, then I dont see how this could be true - so I have removed that.

Can you checkout git/master and see if this fixes the issue?

**Comment by chowbok** [comment]
Sure did! Thanks so much for the quick fix!
