### ISSUE TITLE
Middle click a playlist to "just" replace playque with the contents of the clicked playlist

### ISSUE THREAD

**Issue by AcarBurak** [CDrummond/cantata#1449]
It would be a very fine convenience to be able to navigate playlists (contents) by just one (middle) mouse button click on playlists, in other words, to be able to just replace playque with any playlist by just middle mouse click, just like navigating side pane bookmarks on a file manager or Miller columns.

That is, I want to middle click on a playlist to "just" replace the playque with that playlist's contents –no play back, just replacement.

Yes, there's already a one click solution for this, the ▶ button, but it has two drawbacks:
1. It replaces the playque, but starts playing back as well which is not the wanted behaviour here. It is not like bookmarks navigation or Miller columns behaviour.
2. As you can see from the screenshot attached, those buttons are far away from the playlists and it's not easy to click the right one corresponding to the intended playlist.

Another option is the Ctrl+R hotkey, but it's extra hand travel between keyboard and mouse and it too starts playing back after playque replacement.

Same with the third option, right clicking on playlist and choosing the option.

![cantatapls](https://user-images.githubusercontent.com/47071810/52619213-274e2580-2eb2-11e9-923e-71b095f1f316.jpg)

**Comment by CDrummond** [comment]
No, sorry. There are already way to many play, add, etc, options. If I add this, someone else will ask for it to be configurable, etc.
