### ISSUE TITLE
Allow the editor to change a value (genre, comment) of multiple selected tracks (from queue, playlist) without replacing the old values

### ISSUE THREAD

**Issue by kyriakosbrastianos** [CDrummond/cantata#1451]
Allow the editor to change a value (genre, comment, album artist, whatever else) of multiple selected tracks (from queue, playlist) without replacing the old values.
This is easily done at the moment but only if you do it one by one track.
Pick one track right click > edit track information > change the value by adding a new one separated by a comma, but to do it all one by one is so time consuming and cumbersome.

![screenshot_20190220_012023](https://user-images.githubusercontent.com/1457653/53054724-fcfdf880-34ad-11e9-98da-1009c97715ed.png)
![screenshot_20190220_012221](https://user-images.githubusercontent.com/1457653/53054760-1acb5d80-34ae-11e9-95a3-a955d6e9d8f8.png)

**Comment by CDrummond** [comment]
Sorry, buy Cantata's tag editor is only meant to be a simple editor. For advanced tagging, setup an external command to run kid3 or easytag, etc.

Also, Cantata (AFAIR) only supports multiple Genres - so I _could_ add the feature there. e.g. if ", Rock" was added to "All Tracks" then "Rock" would be appended to a track's list of genres. However, this feels a bit odd - and I'm not sure most users would expect that. And if they did, they'd expect for other fields. This would be a major change to the tag editor, and its simply not worth my time - as I'd never use this.

So, sorry for me its a "wontfix". 

As stated on other Issues, I no longer actively use Cantata/MPD (switched to LMS years ago), so my time for adding features is limited.

**Comment by kyriakosbrastianos** [comment]
Can you at least add the option right click > open with so i can open the selected tracks from playlist or queue with another editor like kid3?
Open with option is also commonly used for other use cases too like open track with audacity etc

**Comment by CDrummond** [comment]
You already can - look at the "Custom Actions" section in the prefences dialog. This will allow you to add custom actions - but these don't work on the queue.

**Comment by kyriakosbrastianos** [comment]
Custom actions looks like what i was looking for!
What is the proper way to do it?
i tried the kid3 %F
and the kid3 options but nothing is starting
![screenshot_20190220_170424](https://user-images.githubusercontent.com/1457653/53101327-2e200c80-3532-11e9-8c38-7d2b0211d1bf.png)
