### ISSUE TITLE
Metadata not displayed on some internet radio streams

### ISSUE THREAD

**Issue by TLeconte** [CDrummond/cantata#1456]
**Describe the bug**
Metadata not displayed on some internet radio streams

**To Reproduce**
add the internet radio stream : 
http://direct.fipradio.fr/live/fip-midfi.mp3
play it and try to see metadata in info panel

**Version Info**
 - OS: Linux fedora 29
 - Cantata Version: 2.3.1
 - MPD Version: 0.21.4

**Additional context**
-  it works for others radio stream like : 
http://stream.radioparadise.com/mp3-192
 - It does not seems to be mpd related as the status command give a normal result 
- The only particularity is that the not working  radio stream  don't give artist/album information.

**Comment by CDrummond** [comment]
Stream info comes from MPD. Just tried via mpc, and using telnet to connect to MPD, no metadata for this stream.

```
> mpc status
http://direct.fipradio.fr/live/fip-midfi.mp3
[playing] #1/1   0:20/0:00 (0%)
volume: 70%   repeat: off   random: off   single: off   consume: off

```

```
> telnet localhost 6600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.20.0
playlistinfo
file: http://direct.fipradio.fr/live/fip-midfi.mp3
Pos: 0
Id: 11
OK
```

**Comment by TLeconte** [comment]
Yes, it's what I wrote in my report : this stream don't send artist/album, but  mpd status command give at least : 
bitrate: 192
audio: 44100:24:2
cantata call this command regularly  so these info could be displayed  in metadata menu
