### ISSUE TITLE
Non-destructive songs queuing 

### ISSUE THREAD

**Issue by mikrosk** [CDrummond/cantata#1457]
I'm using 2.3.3 from Arch Linux. I don't know if I'm dreaming this but I could swear there was an option (maybe 6-7 months ago) to add songs into a playlist and then dynamically change the order of playback with an option like "Queue as next". Now I can't find it at all -- there is only "Play next" but that feature is rather boring, it just moves the song below the currently played one.

The feature I remember worked differently: say there was song A, B, C, D, E in the playlist. I'd listen to, say, B. Now I like B so much so I queue it again as next. Then I realise I loved E even more than C and D and queue E as next. Then I queue C as next. What happened was that next to B I'd see (1), next to E (2) and next to C (3). Playback would start again on B and then E -> C -> D -> E. There were basically unlimited possibilities to combine and repeat song sequences and still have the playlist untouched. Now if I want to change the order I either have to do the change manually after each song with "Play next" or manually (re)create new playlist.

I'm 100% sure this feature was present in Amarok but I've been using Cantana for a couple of years (it's default in Arch Linux) so it seems odd to me I wouldn't notice this to this day.

If I'm really that senile and this feature has never been implemented in Cantana, feel free to consider it as a feature request otherwise as a question why it has disappeared. :)

**Comment by CDrummond** [comment]
If you mean "add from library to queue" - then there are multiple options. Right click, select "Add to Play Queue >" and you'll see the options.

If you mean the context menu in the queue - this has the "Play Next". What you are proposing is to duplicate tracks. That's a pretty odd use case, and not one I feel inclined to spend time on. Sorry, my time for Cantata is severely limited.

**Comment by mikrosk** [comment]
> What you are proposing is to duplicate tracks

No, not at all. See my description - tracks stay as they are, just the queue is modified (i.e. playback doesn't happen according the order of songs but according to user's preferences).

This was my all time favourite feature in Amarok, perhaps I really saw it only there. But I'm pretty sure many users would love it, too.

I of course understand you want to work on things you consider nice, up to you.
