### ISSUE TITLE
Can I ask cantata to not connect to the internet? (Or: when does Cantata fetch album info from the internet?)

### ISSUE THREAD

**Issue by cpitclaudel** [CDrummond/cantata#1459]
**Is your feature request related to a problem? Please describe.**

If I understand correctly, cantata downloads album covers, artist info, and lyrics from the internet.

**Describe the solution you'd like**

I'd like to understand when Cantata fetches that information, and how to prevent this.

**Describe alternatives you've considered**

I could use a firewall instead.

**Comment by CDrummond** [comment]
Use the commandline option.

**Comment by cpitclaudel** [comment]
Hmm, which command line option?

**Comment by CDrummond** [comment]
`--no-network`
