### ISSUE TITLE
Strange behavior in the *'Info'* (now playing) view

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1460]
Hi

I would like to report a behavior in the *'Info'* (now playing) view that seems to be incoherent; not sure if it is related to a bug or how the feature is implemented.

The left panel shows the Artist info, but in some circumstances this could be wrong. Maybe this could be related with the *'Compose support'* tweak interface setting (which I use with 'Classical').

Let me explain with the examples below.

It is all ok when (see: screenshot1):

- AlbumArtist:    not present
- Artist:         present
- Composer:       not present
- Genre: Jazz

![info1](https://user-images.githubusercontent.com/35839588/53556393-089f8e00-3b44-11e9-8d75-2816a2a724a1.png)
*(screenshot1)*

and also with (see: screenshot2):

- AlbumArtist:    present and is same of Artist
- Artist:         present and is same of AlbumArtist
- Composer:       present and NOT the same of Artist=AlbumArtist
- Genre: Rock

![info2](https://user-images.githubusercontent.com/35839588/53556404-0f2e0580-3b44-11e9-8093-20af64e7bdb0.png)
*(screenshot2)*

But something is wrong when (see: screenshot3):

- AlbumArtist:    present and NOT the same of Artist
- Artist:         present and NOT the same of AlbumArtist
- Composer:       present (also if the same of AlbumArtist)
- Genre: Classical

![info3](https://user-images.githubusercontent.com/35839588/53556415-135a2300-3b44-11e9-83b4-8d91a62d9f8c.png)
*(screenshot3)*

Perhaps, in the latter situation the left panel should show the AlbumArtist (or Composer) info, instead of the Artist.

If I can afford to suggest a possible approach, maybe the AlbumArtist (and not the Artist) should be always used in the left panel.

More and better, when the album/sorg genre is one of the composer genres listed with the *'Compose support'* tweak interface setting, then the left panel should show the AlbumComposer (if present) otherwise the AlbumArtist.

Please note:

- MPD Version: 0.20.0
- Cantata Version: 2.4.0 (build downloading master)
- *'Compose support'* tweak set to: Classical

Thank you
Regards

**Comment by CDrummond** [comment]
In your second screenshot, is that big long string the "Composer"? If so, them this is as expected. But perhaps it should always be "Artist"? This should be trivial to change. Perhaps also always "Artist" in the toolbar? I think this and the toolbar should be the same.

As to always using "AlbumArtist" - no, this would break for "Various Artists" albums. Cantata has (and will not have) and knowledge of "AlbumComposer". This "now playing" is track specific, not album specific, hence "Artist" and not "AlbumArtist"

**Comment by nousernouser** [comment]
The long string in *(screenshot3)* is the track's Performer, not the Composer. The Metadata view shows AlbumArtist (Giuseppe Verdi) and Composer (Giuseppe Verdi) as expected; Artist here is set with the track's Performer which could be right being different from AlbumArtist and Composer.

The "issue" is in the left panel of the 'Info' (now playing) view: when genre is "Classical" (more generally one of the genres listed the 'Compose support' tweak interface setting) the Composer (or AlbumArtist) should be displayed... 

Maybe a trick could be: when genre is "Classical" (more generally one of the genres listed the 'Compose support' tweak interface setting) AND album not is a "Various Artists" albums, the call the 'Info' (now playing) using the track's Composer in place of the track's Artist???

**Comment by nousernouser** [comment]
For further information, the following screenshot is what I have in the "Play Queue" view (the yellow box has the metadata of a track of a Classical album).
![schermata a 2019-03-01 20-52-31](https://user-images.githubusercontent.com/35839588/53663143-3af4dc80-3c65-11e9-8c95-ac6ebd0d6380.png)

**Comment by CDrummond** [comment]
So, the left hand pane **is** correct. It is listing the **artist** info.

**Comment by nousernouser** [comment]
Yes it si correct in the sense that it is displaying the Artist (which is set with Performer) info.

But, when genre is "Classical" (more generally one of the genres listed the 'Compose support' tweak interface setting), displaying the Artist=Performer info (which often is  filled in the most disparate ways also in CDDB databases) could not be appropriate (as in this case): the left hand pane should display the Composer info...

**Comment by CDrummond** [comment]
Well, I disagree. The left hand pane is for the **artist**, it even says _Artist_ when collapsed. Just because your tags do not have the artist correct, is not a Cantata issue

**Comment by nousernouser** [comment]
Sorry if I can not explain well ...

I try to clarify.

In the case of the "Classical" genre, Artist is usually the Performer which is something like *"Wiener Philarmonics, C. Abbado (director)"* or *"Maria Stader (soprano), RIAS-Kammerchor; RIAS-Symphonie-Orchester Berlin, Ferenc Fricsay (director)"* and so on...; moreover, the most varied forms are found on the CDDB databases.

For this reason, while in general it is obviously correct to show information on the Artist in "Now Playing", this is not suitable in the case of genres such as "Classical" for which it should be relevant to show information on the Composer.

Please also note that my tags are correct: the tracks of the "Classical" albums have set Artist = Performer and Composer with their actual values.

**Comment by CDrummond** [comment]
Well, if "Artist=Performer", then that is what should be shown on the left - as in details of who is performing the current work. But, I don't have many classical albums, so this is not an issue for me.

As a compromise, I suggest in the artist info page I use Composer for any genre set in the "Composer Support" tweak. Now, if I do that - what about the toolbar? Should this also use the Composer? I'm guessing it should...

**Comment by CDrummond** [comment]
Seeing as you are using a git version, can you checkout branch `1460-composer-info` Does this work as expected?

**Comment by nousernouser** [comment]
You said:
*As a compromise, I suggest in the artist info page I use Composer for any genre set in the "Composer Support" tweak."

Great!

 Now, if I do that - what about the toolbar? Should this also use the Composer? I'm guessing it should...

Me too. I suggest the toolbar using the Composer, showing both Composer - Artist.

Something like:
~~~.text
---------------
|             |  Title
| cover image |
|             |  Composer - Artist
---------------
~~~

Thank you a lot (also for your patience)
Regards

**Comment by CDrummond** [comment]
...try branch now.

**Comment by nousernouser** [comment]
building...

**Comment by nousernouser** [comment]
Tested: seems to be just perfect now!!! Great!

Screenshot (Classical):
![schermata a 2019-03-01 23-32-36](https://user-images.githubusercontent.com/35839588/53670426-00963a00-3c7b-11e9-92bd-a4dec933442f.png)

Screenshot (Rock - not Classical):
![schermata a 2019-03-01 23-33-51](https://user-images.githubusercontent.com/35839588/53670457-186dbe00-3c7b-11e9-87a4-85e756f3b8a0.png)

Thank you a lot!!!

**Comment by nousernouser** [comment]
Just a little detail that I noticed just now ...

With the "Classical" albums (see previous screenshot), only the track Title would be sufficient in the track list, without adding the Artist (=Performer) ...

But I know it's just a detail ... do not worry... (I'm overly perfectionist) 

And thanks again

**Comment by CDrummond** [comment]
I think I'll leave as it is now. I've merged these changes into master.
