### ISSUE TITLE
Search box within library

### ISSUE THREAD

**Issue by afoh92** [CDrummond/cantata#1462]
It would be great if a filter was added to library list, so that you could search for albums, songs or artists and not have to scroll through the whole list, and get your results sorted just like in the list by Artist -> Album -> Song, because the current search field only displays the tracks or artists all in disorder and with no filters, which makes it difficult, like, for example if I search for "Queen" I don't get the albums sorted, only an endless list through which it's tedious to browse.

**Comment by CDrummond** [comment]
There already is! Focus the library, Ctr+F
