### ISSUE TITLE
Why drop windows support?

### ISSUE THREAD

**Issue by Newbrict** [CDrummond/cantata#1463]
**Is your feature request related to a problem? Please describe.**
Hi I was just reading through the patch notes and saw that you dropped windows support as of 2.3.3, I am wondering why you made this decision.

**Comment by CDrummond** [comment]
Because I use neither windows nor macOS - in fact, I don't really use MPD anymore (switched to LMS). My time is limited, I'm working on an LMS HTML UI, so have no time for windows and mac builds.
