### ISSUE TITLE
Downloaded podcast episodes overwrite previous episodes

### ISSUE THREAD

**Issue by cryzed** [CDrummond/cantata#1467]
**Describe the bug**
There are podcast feeds where the filename of every episode is the same, causing Cantata to overwrite previous episodes.

**To Reproduce**
1. Subscribe to [The Magnus Archives' RSS Feed](http://rustyquill.com/category/podcast/the-magnus-archives/feed/).
2. Download 2 episodes.
3. Check the specified download directory and see only a single file, "media.mp3" -- The file that was downloaded first was overwritten.

**Expected behavior**
Cantata should rename the episode and internally map the episode to the file.

**Version Info**
 - OS: Linux (Arch Linux)
 - Cantata Version: 2.3.3
 - MPD Version: 0.21.5
 - CMake options (other than default):

EDIT: Also slightly related: if two podcasts have the same name, the downloaded episodes will just appear in the same folder. If a podcast is unsubscribed from, and then resubscribed to, the already downloaded episodes are assumed to be not downloaded. I mention this here, because it seems like a related problem: Cantata should rely on using unique identifiers for the podcasts and episodes.

**Comment by cryzed** [comment]
Thanks for the quick fix, but wouldn't this create issues with previously downloaded podcast episodes? Should I create new issues for my EDIT?

**Comment by CDrummond** [comment]
No. How about you try a fix before complaining about it? The local path is stored in ~/.local/share/cantata/podcasts/<hash>.xml.gz So, any old names are preserved.

**Comment by cryzed** [comment]
I didn't complain. Thanks for the fix!
