### ISSUE TITLE
Podcasts with the same name store downloaded episodes in the same folder

### ISSUE THREAD

**Issue by cryzed** [CDrummond/cantata#1469]
**Describe the bug**
Podcasts with the same name will download episodes to the same folder. This is an issue for example when subscribing to podcasts like the "NoSleep Podcast", where certain full-length seasons can be bought and subscribed to -- these feeds will have the same name as the free podcast.

**To Reproduce**
1. Subscribe to podcast X with the name Y
2. Subscribe to podcast Z with the name Y
3. Download episodes for podcast X
4. Download episodes for podcast Z
5. See episode files from podcast X and Z appear in download folder with name Y

**Expected behavior**
Cantata should uniquely identify podcasts based on the feed GUID or alternatively based on the feed URL (possibly hashing it and appending it to the podcast title, e.g. "The NoSleep Podcast (d9fcbbb6bf5e1aaf0765c48545046f4e)".

**Version Info**
 - OS: Linux (Arch Linux)
 - Cantata Version: 2.3.3
 - MPD Version: 0.21.5

**Comment by CDrummond** [comment]
I as about to commit a change for this - e.g. "Podcast Name (podcast-hash)" - but, this would look awful for most users. How often do users subscribe to Podcasts with the same name? 

With the change for #1467, each podcast download will have a unique name. So for me, this is a non-issue.

**Comment by cryzed** [comment]
Why do you think that each podcast episode will have a unique name? Wouldn't it be easily imaginable that the domain/subdomain for the "premium" podcast (described in #1467) feed changes, but the path stays the same? For example consider:

* `https://freepodcast.com/episode1/media.mp3`
* `https://premium.freepodcast.com/episode1/media.mp3`

Both feeds specify the same title, and the generated filename from the path (`episode1_media.mp3`) would be the same.
