### ISSUE TITLE
Interface > Tweaks > Single Tracks feature not working

### ISSUE THREAD

**Issue by qwertycian** [CDrummond/cantata#1471]
I'm having a problem with the "single tracks" feature. It seems to be broken.
I have found another issue on this subject, but it was closed: https://github.com/CDrummond/cantata/issues/1155
I have followed your instructions there to double check, but I cannot get it to work correctly.

MPD music folder: /home/tm/music/
Single tracks folders set to: 1950,1980,1990,2000,2010
These folders are direct subfolders of /home/tm/music/ , which is the MPD music folder, and only contain separate music files; no subfolders.
For example, the folder /home/tm/music/1980/ is still displayed in the grouped view, even though it shouldn't be.

![screenshot](https://user-images.githubusercontent.com/29917401/54690918-b2aa7e80-4b22-11e9-89ad-568e8735e20c.png)

**Comment by CDrummond** [comment]
This setting **only** applies to the **library** view. As is obvious by the text statnig that it will group them under a "Various Artists" entry in the list of **artists** . The MPD folder structure shows your folder structure!

**Comment by qwertycian** [comment]
Thank you for your quick reply. It takes some very careful reading to understand that this only applies to the Library view. I had expected it to (also) apply to the playlist view.
As you can see now, a playlist with songs by many different artists looks kind of ridiculous. For this you need the table view mode. However, the table view mode on the other hand is poorly suited for viewing albums. So how can Cantata properly display a music collection containing both albums and individual songs? This is a problem for many players unfortunately. Anyway, for the rest the program works very well, so thank you very much for making it. :)

**Comment by CDrummond** [comment]
I've updated the code (for 2.4.0) to apply this tweak to the queue items. Not yet tested!

**Comment by qwertycian** [comment]
Very cool! Will check it out as soon as 2.4.0 is available in my distro. Thanks!
