### ISSUE TITLE
"Use original year to tag and display..." option is ignored?

### ISSUE THREAD

**Issue by DarkSwan86** [CDrummond/cantata#1472]
I have a similar problem described on #1470, under Tweaks->Miscellaneous i have selected "Use original year to tag and display..." but still Cantata show me the Year (2003) instead of the original year (1979) on the example below. I'm missing something about that option?

From the metadata page on Cantata (FLAC tagged with Picard):

Artist: | The Police
-- | --
Album artist: | The Police
Album: | Reggatta de Blanc
Track number: | 1
Disc number: | 1
Date: | 2003
**Original date:** | 1979-10-05
Label: | A&M Records
Catalogue number: | 493 653-2
Artist sort: | Police, The
Album artist sort: | Police, The
Media: | CD
Tracktotal: | 11
Totaltracks: | 11
Totaldiscs: | 1
Script: | Latn
Releasetype: | album
Releasestatus: | official
Releasecountry: | XE
**Originalyear:** | 1979

Is the tagging wrong somehow? What is the correct tag for Cantata to use with that option?

Manjaro Linux, Cantata 2.3.3, MPD 0.21.6

Thanks!

**Comment by CDrummond** [comment]
Have you configured MPD for this? Cantata gets its tags from MPD. You will also need to have Cantata refresh its DB before it will be used.

**Comment by DarkSwan86** [comment]
@CDrummond the problem is that from MPD documentation on tags ([here](https://www.musicpd.org/doc/html/protocol.html#tags)), originalyear is not supported. 

This is my conf file:

music_directory "/home/leonardo/Musica/"
playlist_directory "/home/leonardo/.local/share/cantata/mpd/playlists"
sticker_file "/home/leonardo/.local/share/cantata/mpd/sticker.sql"
bind_to_address "/home/leonardo/.local/share/cantata/mpd/socket"
db_file "/home/leonardo/.cache/cantata/mpd/tag_cache"
pid_file "/home/leonardo/.cache/cantata/mpd/pid"
state_file "/home/leonardo/.cache/cantata/mpd/state"
log_file "/dev/null"
metadata_to_use "artist,album,title,track,name,genre,date,disc,albumartist,composer,musicbrainz_albumid,**originalyear**"
audio_output {
  type "pulse"
  name "Output"
}
mixer_type "software"

If i save with the added **originalyear** tag, when i open Cantata it says "Failed to send command to Personal - Not connected" and the "refresh database" is grayed out. Any idea?

**Comment by chowbok** [comment]
@DarkSwan86 : The MPD tag is **originaldate**, not originalyear. Dunno why it's not documented, they must have forgotten.

**Comment by DarkSwan86** [comment]
@chowbok Works perfectly now!!! Thanks!
@CDrummond can you add the originaldate tag to the mpd.conf of Cantata by default so it works out of the box when installed? Thank you!
