### ISSUE TITLE
Scrollbar doesn't work when window is maximized and mouse is hugging right side of the screen.

### ISSUE THREAD

**Issue by jazztickets** [CDrummond/cantata#1474]
**Describe the bug**
The scrollbar doesn't register when you click on the very right side of the window. It's as if there's a 1 pixel border around the window that blocks the scrollbar. The left side of the window works fine though when clicking the Library or Search buttons.

Video:

![new](https://user-images.githubusercontent.com/425930/56082556-768fd400-5dd7-11e9-9a45-3709462e3f1a.gif)

**To Reproduce**
1. Maximize Cantata
2. Move the mouse to the absolute right side of the screen.
3. Click and drag down.
4. The scrollbar should register but it doesn't.

**Version Info**
 - OS: Arch Linux with XFCE and greybird theme (changing themes doesn't help)
 - Cantata Version: 2.3.3

**Comment by CDrummond** [comment]
Must be your window manager. Just tried with GNOME shell, and I can put pointer far right and scroll.

**Comment by jazztickets** [comment]
It's interesting because QtCreator doesn't have this problem, though VLC does. There must be some small difference in how the window's being set up in the code...
