### ISSUE TITLE
Technical info - WavPac

### ISSUE THREAD

**Issue by B1tl0rd** [CDrummond/cantata#1476]
file format .wv "WavPac"
Missing Bit depth in technical info.

example output mediainfo
Audio
Format                                   : WavPack
Format profile                           : 4.07
Format settings                          : Lossless
Duration                                 : 40 min 12 s
Bit rate mode                            : Variable
Bit rate                                 : 5 912 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 192 kHz
Bit depth                                : 32 bits
Compression ratio                        : 2.078
Stream size                              : 1.66 GiB (100%)
Encoding settings                        : -m

**Comment by CDrummond** [comment]
This info comes from MPD, Cantata just shows what its given.
