### ISSUE TITLE
cue sheet, multiples tracks/files

### ISSUE THREAD

**Issue by B1tl0rd** [CDrummond/cantata#1479]
Hello, there is an error with the artists with the cue files, for example only shows the artist for the first 3 tracks, the following shows them as unknown and orders them apart only recognizes the album, also happens with the albums of iron maiden, the cue file links all the tracks well, directly selecting the cue. excuse the most English
.cue -> https://hastebin.com/ihoyadocix

![cantata](https://user-images.githubusercontent.com/12401985/56839967-22630600-6853-11e9-9b2a-6a0af4eccbcd.png)

![cantata1](https://user-images.githubusercontent.com/12401985/56840217-512dac00-6854-11e9-9f44-cfaa607e695a.png)

![cantata2](https://user-images.githubusercontent.com/12401985/56839974-2b53d780-6853-11e9-8dc8-3e7c61cddf4f.png)

**Comment by CDrummond** [comment]
Yes, I can see why that might be a problem. Pretty sure the cue file parsing expects either 1 audio file for all tracks, or 1 audio file per track. This has multiple audio files, with multiple tracks.

Sorry, but I have no such files - and really, can't see the need for such files. MPD does gapless, so why not just split the flac into multiple files? I also have no time to spend on this, so if you want it fixed you'll have to do it yourself. The code is in mpd-interface/cuefile.cpp

**Comment by CDrummond** [comment]
Changes applied from #1461 _might_ have helped with this. Can you checkout git/master and see if it has helped?

**Comment by B1tl0rd** [comment]
thank you, it worked

**Comment by CDrummond** [comment]
Thanks for checking.
