### ISSUE TITLE
Doing nothing no wayland

### ISSUE THREAD

**Issue by newincpp** [CDrummond/cantata#1481]
hello,
I just switched to wayland (with sway) and when I tried to open cantata it just did nothing.
By nothing I mean really nothing: no windows, no error message, nothing wrong in the strace, nothing displayed in `-d all`. It's just like I were running /bin/true.
I have other programs with QT5 that run with no problems.
When I run other QT5 program I just have to pass `QT_QPA_PLATFORM=wayland` and QT does job. not sure what's happening here.
It was running perfectly fine with X11. I also tried to delete my cache and config files but that changed nothing.
I wish I could provide more information but I don't know where to look.

**Comment by CDrummond** [comment]
Just tried `QT_QPA_PLATFORM=wayland ./cantata` under GNOMEShell/Wayland. Initially Q reported:

```
$ QT_QPA_PLATFORM=wayland ./cantata
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
```

So I installed Qt5 wayland via `sudo apt install qtwayland5` Re-ran and received

```
QT_QPA_PLATFORM=wayland ./cantata
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
Using the 'xdg-shell' shell integration
qt.qpa.wayland: Non-toplevel surfaces can't request window states
```

Cantata window showed, with awful window decoration - so was using Wayland. Sorry, but Cantata is working for me under wayland - but pretty poor titlebars (and no shadows). Sorry, but looks like an issue on your system.
