### ISSUE TITLE
Create a recently played playlist?

### ISSUE THREAD

**Issue by cmdcolin** [CDrummond/cantata#1482]
**Is your feature request related to a problem? Please describe.**
I thought it would be great if there was a "Recently played (in the last N days)" similar to how there is a File Date smart playlist

**Describe the solution you'd like**
The smart playlist would be sorted by last played for the last N days

**Describe alternatives you've considered**
I have not tried very much, I looked up "recently played" mpd on google and did not find anything

**Additional context**
N/A

**Comment by CDrummond** [comment]
Cantata does not save when tracks were played, so sorry not possible.

**Comment by cmdcolin** [comment]
What would you recommend? I see you have an aggressive policy of closing issues but I find this function pretty lacking

**Comment by CDrummond** [comment]
Sorry about closing issues quickly, but it is really only me working on Cantata - and I no longer actively use it. At the moment I'm just fixing bugs - not adding new features. Even if I did, I have no need of a DB to track when I played tracks - not something I'm interested in, so not something I would spend time on.

**Comment by cmdcolin** [comment]
Ok thanks for the explanation. I have been pretty happy with using cantata so far, so thank you for developing :) I could probably find a workaround by autogenerating the playlist
