### ISSUE TITLE
Enhancement for the File Age Smart Playlist

### ISSUE THREAD

**Issue by cmdcolin** [CDrummond/cantata#1483]
**Is your feature request related to a problem? Please describe.**
The File Age smart playlist is a pretty good option, but I'd like it to track a file "last modified" which gives me a better idea of "Recently added" files to my music library (e.g. downloaded files last modified time is sometimes preserved)

**Describe the solution you'd like**
I can echo the files in my music directory in the order I'd like them in with something like this

find -type f -exec stat --printf "%Z %n\n" {} +|sort -n|tail -n 5000

The existing  File Age smart playlist setting appears something more like this (e.g. %Y instead of %Z)

find -type f -exec stat --printf "%Y %n\n" {} +|sort -n|tail -n 5000

**Describe alternatives you've considered**
I considered generating the playlist on the file system and intentionally modifying my files to update the last modified date but if %Z can be used that would be great

**Comment by CDrummond** [comment]
Last-Modifed-Date comes from MPD, Cantata does not stat the files. And for some users, MPD will be running on a different machine to Cantata, so it could not even access the files.
