### ISSUE TITLE
Artist images replaced with stars

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/cantata#1485]
Last.fm have changed API to block artist images. See https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq

**Comment by CDrummond** [comment]
For now, artist image support has been commented out  in the code.

**Comment by B1tl0rd** [comment]
Hello everyone, friend and if we use another api like the one of discogs, Musicbrainz, itune api, or simply leave the option to add the artist's image manually in case the api does not work,

**Comment by CDrummond** [comment]
The code is still there, just surrounded by a "ifdef ARTIST_IMAGE_SUPPORT" All that needs doing is to change the code in `covers.cpp` to use a new API, and then add `#define ARTIST_IMAGE_SUPPORT` to `config.h.cmake` However, I personally have no time to look into this at the moment - hence, for now, this feature is disabled.

**Comment by nousernouser** [comment]
Maybe someone could be interested in this (said to be) "easy-to-implement" workaround by [lawrencenull](https://getsatisfaction.com/lastfm/people/lawrencenull):

https://codepen.io/lawrencenull/pen/NVWWwR

Regards

**Comment by CDrummond** [comment]
Cantata already has a FanArt API, and I believe the context background already does a lastfm call to get the musicbrainz id, and then calls fanart. So, it'd jsut be a matter of adding this to covers.cpp. Which I might do when I get time...

**Comment by barkingbandicoot** [comment]
ok! Thanks for an awesome music player anyway! : )
