### ISSUE TITLE
cantata is not able to connect to an abstract unix socket.

### ISSUE THREAD

**Issue by crocket** [CDrummond/cantata#1486]
**Describe the bug**

`mpd` can bind to an abstract unix socket

```
bind_to_address "@mpd"
```

`mpc` supports connecting to an abstract unix socket as below.

```
env MPD_HOST="@mpd" mpc
```

cantata can't connect to `@mpd`.

**Version Info**
 - OS: Gentoo Linux
 - Cantata Version: 2.3.3
 - MPD Version: 0.21.8
- libmpdclient Version: 2.16

**Comment by CDrummond** [comment]
`bind_to_address "@mpd"` does not work for me on Ubuntu 19.04. MPD complains:
```
exception: Failed to listen on @mpd (line 4)
exception: nested: Failed to resolve '@mpd': Name or service not known
```

However, I have updated the code to accept a hostname stating with @ - and treat as a local socket. Can you checkout git/master and see if this now works for you?

**Comment by crocket** [comment]
The latest git commit of cantata cannot connect to `@mpd`.

![2019-05-16_Thu_00:07:20](https://user-images.githubusercontent.com/748856/57817424-3b0f6d80-77ba-11e9-8742-186fbc6a4291.png)

**Comment by CDrummond** [comment]
Ah! I missed a change. Can you edit `mpd-interface/mpdconnection.cpp` and change line 2545 from:

```
    if (hostName.startsWith('/') || hostName.startsWith('~')) {
```
to:
```
    if (hostName.startsWith('/') || hostName.startsWith('~') || hostName.startsWith('@')) {
```
..recmpile, etc. Does that help?

**Comment by crocket** [comment]
No. Right now, the error is

![2019-05-16_Thu_11:01:56](https://user-images.githubusercontent.com/748856/57849145-886cf880-7815-11e9-868a-877f0b3e800f.png)

**Comment by CDrummond** [comment]
Sorry, I have no time to build a custom mpd just for this. Do ANY other Qt5 apps work with these sockets?

**Comment by crocket** [comment]
Is there any qt5 app that I can test?

**Comment by crocket** [comment]
Is there any qt5 app that I can test? I haven't tested any other qt5 apps with abstract unix sockets, yet.

By the way, you might have to replace `@` with the value 0. libmpdclient replaces `@` with 0 internally.

**Comment by crocket** [comment]
Is there any qt5 app that I can test? I haven't tested any other qt5 apps with abstract unix sockets, yet.

By the way, you might have to replace `@` with the value 0. libmpdclient replaces `@` with 0 internally.

If you use qt5 sockets instead of libmpdclient, you definitely want to try replacing `@` with 0.

**Comment by CDrummond** [comment]
I've changed the path to replace @ with \0 - can you update and try again? Thanks,

**Comment by crocket** [comment]
Connection to `@mpd` still fails.

**Comment by CDrummond** [comment]
Well, I give up. Sorry, I have no need for this and no more time to spend on it. Feel free to look for a fix and submit a pull request.

**Comment by crocket** [comment]
I tracked the issue down to https://bugreports.qt.io/browse/QTBUG-16090
It seems QLocalSocket doesn't yet support abstract unix socket.
