### ISSUE TITLE
[CUE files] Better handling for GENRE when parsing cuesheets (with proposed patch)

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1487]
Hi

- If a CUE files has a genres list defined using the 'REM GENRE' comment, as in this example:
~~~.text
REM GENRE "Classical,Symphonic"
~~~
then the genres list is currently assigned _as it is_ in the local DB of Cantata (to the field 'genre1'): and this leads to breaking the _composer tweak_.

- If a CUE files does NOT have any genre definition, then 'genre' should not let empty and "Not Defined" should be used as fallback (see: [CD-TEXT standard genres list](https://www.gnu.org/software/libcdio/cd-text-format.html#table_003agenres)).

Here attached is a proposed patch to overcome these problems.

Regards

[cuefile.cpp.patch.zip](https://github.com/CDrummond/cantata/files/3184731/cuefile.cpp.patch.zip)

**Comment by CDrummond** [comment]
I won't use the patch for 2 reasons:

1. Splitting the genre is good, and up to the 1st 4(?) should be used - not just the 1st
2. "Not Defined" will NOT be used - its not translated and is different to how genre is treated elsewhere.  If genre needs to be set, then Song::unknown will be used istead.

**Comment by nousernouser** [comment]
> 1. Splitting the genre is good, and up to the 1st 4(?) should be used - not
> just the 1st 

I can try to do it. I also thought about it, but I wasn't sure how to assign
the fields to a song.

Which is the right way? Is there a fn with which to assign the whole list once
populated? Or each genre (1 to 4) should be assigned separately, and how?


> 2. "Not Defined" will NOT be used - its not translated and is
> different to how genre is treated elsewhere.  If genre needs to be set, then
> Song::unknown will be used istead.

Ok. So should I use Song::unknown or let the value(s) empty?

Regards

**Comment by CDrummond** [comment]
I'll make the changes later - pretty trivial, so don't bother with a patch, etc. As to the genre handling, I'll look at the code to see what happens if an MP3, etc, does not have a genre.

**Comment by nousernouser** [comment]
> I'll make the changes later - pretty trivial, so don't bother with a patch, etc. 

I read just now ... But in the meantime I had already worked on it ... So I attach the patch anyway :)

It is less trivial than it might seem because there are several possible exceptions: in the CUE file GENRE may not be present, or contain a list of more than 4 genres ...

I did tests and the attached patch works fine in all these cases.

> As to the genre handling, I'll look at the code to see what happens if an MP3, etc, does not have a genre.

I have looked at the Cantata local DB for single track flac with embedded tags which does not have a genre: genre1 result to be set to 'unknown' , genre2-3-4 appears to be empty. So I did the same for CUE without a genre definition...

Best regards

[cuefile.cpp.patch.zip](https://github.com/CDrummond/cantata/files/3186794/cuefile.cpp.patch.zip)

**Comment by nousernouser** [comment]
Il giorno Thu, 16 May 2019 09:13:43 -0700
CraigD <notifications@github.com> ha scritto:

> Closed #1487.

Nice. Works greatly.
Thank you.
