### ISSUE TITLE
Sometimes tracks are not shown in the Album View area of the Info/NowPlaying view

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1489]
When the library is grouped by 'Album' and you select and load certain albums to the play queue, then all or some of the album tracks are not shown in the Album View area inside the Info/NowPlaying view.

This happens ONLY:
- in the Album View area inside the Info/NowPlaying window (the Library view and the Play Queue view are ok, with all the tracks and tags info correctly shown)
- when the library is grouped by 'Album' (instead, tracks are shown as expected when albums are grouped by 'Artist')
- for albums whose tracks do NOT have all the same 'artist' AND genre IS NOT listed in the "Composer Support" tweak list --OR-- albums whose tracks do NOT have all the same 'composer' AND genre IS listed in the "Composer Support" tweak list

Note that:
- this behaviour happens both for separate flac files with embedded tags AND with single flac with a related cue playlist: so the issue do not seems being related with cue files
- this behaviour happens both for albums having genre listed or not listed in the "Composer Support" tweak list: so the issue do not seems being directly due to the "Composer Support" tweak

Based on the above, it seems to me that I can guess that *every time* you add an album listed in the Library view (both if grouped by 'Artist' or 'Album') to the play queue, then there is somthing in the code "filtering" the tracks to display based on ArtistOrComposer: while this mechanism works well if the Library is grouped by 'Artist', maybe it leads to an issue instead when the Library is grouped by 'Album'.

In this last case, that is when an album taken from the Library grouped by 'Album' is inserted in the play queue, then _all the tracks associated with the album should be shown_ (without any filter): if I guessed the cause of the problem, this should solve the issue (and also correspond to the user intent when it groups by 'Album').

Please, sorry if I haven't analyzed the code (it is also because I'm not sure I understand enough exactly how it works with regard to this aspect). Anyway, I hope I managed to explain the issue well (some screenshots showing the issue attached below). Tell me if more clarification or testing is needed.

Thank you for your attention.

Regards

- Library (all is ok):
![01](https://user-images.githubusercontent.com/35839588/57949765-9f7b1b80-78e5-11e9-8b3c-162bda7483dc.png)

- Play Queue (all is ok):
![02](https://user-images.githubusercontent.com/35839588/57949778-aace4700-78e5-11e9-8c0d-37e13b636452.png)

- Info/NowPlaying view -- Only _2 tracks are shown but 9 are in the queue_...
![03](https://user-images.githubusercontent.com/35839588/57949784-b02b9180-78e5-11e9-8d54-177ed8ca65bf.png)

- Info/NowPlaying view -- Playback of the queue has gone ahead: _now playing track no. 4 which is not listed_...
![03b](https://user-images.githubusercontent.com/35839588/57949792-b4f04580-78e5-11e9-9c6c-e9c915b62848.png)

**Comment by CDrummond** [comment]
I _think_ the issue is that the code that checks if the view should update is using 'albumArtist' but the code that fetches the track list is using 'albumArtistOrComposer' I've now made both use 'albumArtistOrComposer' The track listing should then change. Can you update and confirm?

**Comment by nousernouser** [comment]
Indeed, now the track listing changes as expected. 

ADDITIONAL NOTE: Also I have noticed (consider I have set #define ARTIST_IMAGE_SUPPORT in albumview.h) that sometimes, when entering the Info/NowPlaying view, the cover image is not initially shown being updated only when changing the playing track... Not sure, maybe this could be related to line 258 where there is:

~~~.text
QString cachedFile=cacheFileName(Covers::fixArtist(currentSong.albumArtist()), currentSong.album, prefix, false);
~~~

instead of:

~~~.text
QString cachedFile=cacheFileName(Covers::fixArtist(currentSong.albumArtistOrComposer()), currentSong.album, prefix, false);
~~~

However it seems that the issue can be considered solved.


Anyway, I would like to ask you to consider trying another possible approach in determining which tracks to show in the Album View area inside the Info / NowPlaying view: that is to show in any case all the tracks (songs) that are present in the play queue and that belong to the same album as the track (song) that is playing. This approach should always work consistently to the user intent both when he groups by 'Album' and when he groups by 'Artist'. 

If you want to try this, I'm available for help and testing.

Thank you.

Regards

**Comment by CDrummond** [comment]
I've made that change.

As to showing all the tracks. No. An album is identified by AlbumArtist+AlbumName. As many artists have "Geatest Hits" you cannot use the alum name alone to group tracks. So, to fully resolve your issue, just give all tracks in the album the same album artist. Track artist can be different, of course.

**Comment by nousernouser** [comment]
> I've made that change.

Ah ok. Thanks.


> As to showing all the tracks. No. An album is identified by AlbumArtist+AlbumName. As many artists have "Geatest Hits" you cannot use the alum name alone to group tracks. 

You're right. Agree.

> So, to fully resolve your issue, just give all tracks in the album the same album artist. Track artist can be different, of course.

This is what I already have but do not fully resolve the issue: please note how regarding the album in the screenshot, Cantata has:

~~~.text
$ sqlite3 -column -header $HOME/.local/share/cantata/library/localhost_6600.sql "select albumId, albumArtist, artist, composer, genre1 from songs where albumId IS 'Opera Gala'"
albumId     albumArtist      artist                                                                                                             composer           genre1    
----------  ---------------  -----------------------------------------------------------------------------------------------------------------  -----------------  ----------
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Gaetano Donizetti  Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Gaetano Donizetti  Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Giuseppe Verdi     Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Giuseppe Verdi     Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Giuseppe Verdi     Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Jacques Halévy    Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Giacomo Meyerbeer  Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Georges Bizet      Classical 
Opera Gala  Placido Domingo  Placido Domingo (tenor), Roger Wagner Chorale, Los Angeles Philharmonic Orchestra, Carlo Maria Giulini (director)  Georges Bizet      Classical 
~~~

Hum... So now I am back in dubt... 

You said: 

> ... An album is identified by AlbumArtist+AlbumName. ... 

and regarding the commit 791a673:

> ... but the code that fetches the track list is using 'albumArtistOrComposer'  ...

so, since an album is identified by AlbumArtist+AlbumName, then maybe the code that fetches the track list should simply use albumArtist() and not albumArtistOrComposer() ?

If you want I can test this, but I need to know which the code changes should be...

Thanks again

Regards
