### ISSUE TITLE
Cantata fetches wrong URLs from some tunein stations.

### ISSUE THREAD

**Issue by crocket** [CDrummond/cantata#1490]
"Internet > TuneIn > By Location > Asia > South Korea > CBS 뮤직 FM" hands mms://widget.cbs.co.kr/cbs939_live to MPD.

However, mms://widget.cbs.co.kr/cbs939_live is a wrong URL. The right URL is http://aac.cbs.co.kr/cbs939/_definst_/cbs939.stream/playlist.m3u8

**Comment by CDrummond** [comment]
Cantata gets the URLs from TuneIn. The search/browse returns a TuneIn URL, in this case:

```
http://opml.radiotime.com/Tune.ashx?id=s14584&locale=en_GB
```

If you fetch that URL with curl/wget you will see that it ONLY contains:

```
mms://widget.cbs.co.kr/cbs939_live
```

No much else Cantata can do.

**Comment by crocket** [comment]
https://tunein.com/radio/CBS-Music-FM-939-s14584/ makes a request to

```
https://opml.radiotime.com/Tune.ashx?audience=%3Ball%3B&id=s14584&render=json&listenId=1558253913&formats=mp3,aac,ogg,flash,html,hls&type=station&serial=81c3df7e-a638-460c-aceb-901473ef22f5&partnerId=RadioTime&version=3.2202&itemUrlScheme=secure&reqAttempt=1
```

which contains http://aac.cbs.co.kr/cbs939/_definst_/cbs939.stream/playlist.m3u8

**Comment by CDrummond** [comment]
Thanks! That info would have been nice to start with :-) I've updated the TuneIn code to add some of those params.
