### ISSUE TITLE
Support browsing songs by grouping.

### ISSUE THREAD

**Issue by crocket** [CDrummond/cantata#1493]
Recently, MPD exposed grouping tag upon my request. The tag is called TIT1 in ID3.

https://github.com/MusicPlayerDaemon/MPD/commit/319c9699fb09e7c35e2aafa022ff8e1f0dcfcd8b

**Comment by CDrummond** [comment]
Sorry, I have no time nor need for this. I no longer actively use Cantata (only CD ripping and ReplayGain calc), having moved over to logitech media server. So, Cantata is in a mainly bug-fix state. Even if it wasn't, not sure I see the need for this, or even where it would be placed in the UI. 

Cantata only support Composer browsing if set in on tweaks page, so composer is used for artist. It does not support browsing by Performer, so I cannot envisage supportnig browsing by grouping.

So, I'm going to close this as 'wontfix' which is what I do for all features, etc,, that I will not personally look into. However, I'll happily accept pull requests.

**Comment by crocket** [comment]
What is good about logitech media server?

**Comment by CDrummond** [comment]
That's up to you to decide. However, I like its separation of music server and music player, as well as its audio sync between players. I have an airplay compatible speaker, a piCorePlayer on a Pi ZeroW, SB player on my Android phone, a squeezebox radio, and even a local-player plugin on my laptop. LMS can play to all of these in sync. It can also play to DLNA/UPnP and ChromecastAudio players. LMS has bult-in support for TuneIn, can support Spotift/Deezer/Tidal (although I use none of these), and has a YouTube plugin (allowing to play YouTube music to all players, etc). you can configure its browsing menus - so can list Composers, or Performers - but I'm unsure if it supports the "Grouping" tag.

I'm currently writing a [google-material theme'd skin](https://github.com/CDrummond/lms-material) for its UI, which allows me to control my music from any device without needing to install an app.
