### ISSUE TITLE
Some times, with cue file albums, the playing track is not highlighted in the Now Playing / Album view [+ solving patch]

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1495]
Some times the playing track is not highlighted in the _Now Playing / Album view_ (as an example, please see the attached screenshot: track 5 is playing... but it is not highlited (bold) in the album view).

This should happen because sometimes, with cue files albums/tracks, the `sameMetadata()` check in `AlbumView::getTrackListing()` [file `albumview.cpp`] fails.
The proposed patch solves the problem with minimal modification.

Thank you
Regards

[albumview.cpp.patch.zip](https://github.com/CDrummond/cantata/files/3213133/albumview.cpp.patch.zip)

![cantata-difficulttoread](https://user-images.githubusercontent.com/35839588/58252566-b64ac380-7d66-11e9-9d15-0587ccb82144.png)

**Comment by CDrummond** [comment]
Thanks once again!

**Comment by nousernouser** [comment]
Il giorno Thu, 23 May 2019 09:46:15 -0700
CraigD <notifications@github.com> ha scritto:

> Thanks once again!


You're welcome, thanks to you!
