### ISSUE TITLE
Some album string indications maybe not consistent in top and play queue views

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1496]
When albums have tracks with different _AlbumArtist_ from _Artist_ or _Composer_, it often happens that string indications are not consistent in TopView and PlayQueue views.

Please have a look at following screenshots, which are related to this album:

- album: Horowitz in Moscow
- albumartist: Vladimir Horowitz
- track 1:
    + artist: Vladimir Horowitz (piano)
    + composer: Domenico Scarlatti
- tracks 2-4:
    + artist: Vladimir Horowitz (piano)
    + composer: Wolfgang Amadeus Mozart
- ...    
NOTE: Tracks have **different** Artist and/or Composer (here we have: Scarlatti, Mozart, etc.)...

**LIBRARY VIEW**    
All right here: `Horowitz in Moscow (Vladimir Horowitz) (1986)`
![c1-library](https://user-images.githubusercontent.com/35839588/58281166-c1234980-7da2-11e9-9270-44519eae888a.png)

**TOP VIEW (& TOOLTIP)**    
- In the Top View, the 1st track Composer (note: the Genre is in the _Composer Tweak_ list) is shown, followed by the track Artist and the album Title: that's not appears to be consistent. Should be as in the Library view. 
- In the Top View ToolTip, are shown the track Composer, the Artist and the album Title. Again, be as in the Library view.
![c2-topview](https://user-images.githubusercontent.com/35839588/58281195-d4361980-7da2-11e9-83d5-e64d65a41361.png)

**PLAYQUEUE VIEW**    
The highlited album string indication appears to be inconsistent, the same way as in the Top View.
![c3-playqueue](https://user-images.githubusercontent.com/35839588/58281203-dc8e5480-7da2-11e9-8289-37091c74e3b0.png)

If I can suggest it, I believe that, either in Top View, or in the Top View ToolTip and in the PlayQueue View, _**the album string indications to use in these views should always be the same as in the Library View**_, namely: Album, AlbumArtist, Year (or originaYear depending on the user preferences setting).

Indeed, since **tracks can have different Artist AND/OR Composer**, it should be preferable to **use Album and AlbumArtists** aonly, that **do not (should) change from track to track**.

I think it's a simple change to make, but sorry if I don't attach a proposed patch because I'm not entirely sure where code should be changed.

Thank you.
Regards

**Comment by CDrummond** [comment]
This _should_ be easy enough to fix. Thanks for the tags - I'll create some dummy files with those settings, so I can see the issue and then fix.

**Comment by nousernouser** [comment]
Hello

do you want me to test the changes?

**Comment by CDrummond** [comment]
Most should be fixed - but a quick check would not hurt :-)

**Comment by nousernouser** [comment]
Il giorno Mon, 27 May 2019 07:34:43 -0700
CraigD <notifications@github.com> ha scritto:

> Most should be fixed - but a quick check would not hurt :-)

In fact ... at first glance it seems that now there is something else
strange (maybe a regression in the grouping by album, I think maybe related to
the d23f426 commit) ... Furthermore, it is possible that there is something
wrong with albums Various Artists also .

But please, I need more time (in the coming days I have work commitments) to
better test and identify this ...

Best regards

**Comment by CDrummond** [comment]
No. That commit is fine. I know it splits the album, but you have chosen to group via composer and there are multiple. So, multiple albums

**Comment by nousernouser** [comment]
Hi, I had very little time but I managed to do some tests, although probably not exhaustive...

Unless may be there are particular or hidden situations that did not result, I believe that the changes made have actually solved the issue.

Just to ensure Cantata is working as expected, please have a look to the following screenshots, which show what I have.

![0101](https://user-images.githubusercontent.com/35839588/59098924-05295900-8922-11e9-990f-48e86391586e.png)

![0201](https://user-images.githubusercontent.com/35839588/59098929-09ee0d00-8922-11e9-8665-7ff086aded03.png)

The Library view (grid viewing, album grouping, album sort, composer trick enabled) has no duplication (the apparently doubled covers you can see are in fact of 2 CDs albums). 

In the Play Queue view:

- tracks in the 1st album (classical genre, in composer trick) have all the same composer: no split
- tracks in the 2nd album (classical genre, in composer trick) have different composers: split by composer
- tracks in the 3rd album (rock, NOT in composer trick) have different composers: no split

For me it is ok... Is that what was expected?

---
ALBUM SELECTION FROM NOW PLAYING VIEW

During testing, I have noticed the following, which is probably something different and not connected with this issue (please tell me if you prefer I open a separate issue).

In the left section of the now playing view are listed the albums in which a certain artist is present, which is the composer when the genre is listed in the composer trick. Clicking on one of the albums on this list opens the Library view and the album is selected.

But it happens that (I imagine they are disjointed things):

- if the album you click on has tracks with different composers (whatever the genre), it does not appear to be selected in the Library view;

- sometimes, when an album you clicked on is selected, the previous selection in the Library view remains active (so you can have 2 or more selected albums...)

Please tell me if I need to open a separate issue and if more information and / or testing is needed.

Thank you a lot

Best regards

**Comment by CDrummond** [comment]
OK, so this issue is closed. As for the "selection" issue, I guess the quickest fix is just not to select items.

Sorry, bu tmy time for Cantata is very limited, so I have no desire to look into every single little niggle.
