### ISSUE TITLE
Refresh data-base subtree

### ISSUE THREAD

**Issue by arximboldi** [CDrummond/cantata#1497]
MPD supports refreshing only a subtree (subfolder) of the data-base. This is particularly important for users that have simlinks to external hardware in their music folder, and would not like to prune those when refreshing without the external hardware connected.

Both Sonata and GMPC support this by right-clicking on the folder in the file browser and clicking _"Update"_ or similar. It would be nice to have such option in Cantata too.

Thanks!

**Comment by CDrummond** [comment]
Sorry, but Cantata's code is designed to update when the DB changes. This is not a 'problem' I have ever had. Sorry, but I no longer actively work on Cantata, and have no time for such a change as this.  I've now switched to logitech media server for music playback, and Cantata is really in bug-fix mode.

So, I'm going to close this as 'wontfix' - which is what I'm doing for all features I have no time to implement. However, I will gladly accept a pull request.

**Comment by arximboldi** [comment]
Hi Craig!

I think I did not make myself clear enough. My request was not about
Cantata updating when the DB changes (this is expected and good!) but
about triggering an MPD server update for just one subtree, instead of
for the whole data-base.

Anyways, I do understand that you are no longer implementing new
features.  I will try find some time to do it myself.

And thanks a lot for your fast reply and for making this nice piece of
software!

CraigD <notifications@github.com> writes:

> Sorry, but Cantata's code is designed to update when the DB
> changes. This is not a 'problem' I have ever had. Sorry, but I no
> longer actively work on Cantata, and have no time for such a change as
> this.  I've now switched to logitech media server for music playback,
> and Cantata is really in bug-fix mode.
>
> So, I'm going to close this as 'wontfix' - which is what I'm doing for
> all features I have no time to implement. However, I will gladly
> accept a pull request.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CDrummond/cantata/issues/1497#issuecomment-498616731

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es
