### ISSUE TITLE
Flickering problem with library view in 4k resolution fullscreen

### ISSUE THREAD

**Issue by aqua36** [CDrummond/cantata#1498]
Since switching to a 4k screen(for some months now) I have encountered continued flickering in the artist pictures in the left part of the screen when in library view. This can be seen in the mp4 file contained in this [zip](https://github.com/CDrummond/cantata/files/3256052/cantata4kbugmp4.zip). (The flickering is actually *significantly* faster, I couldn't get the proper setting for ffmpeg to capture it properly). The cpu usage of cantata also goes insanely high while this happens( htop is showing 180% cpu usage on a beefy 4core i5).

Ways to reproduce:
If you don't have a 4k screen(assuming you have an 1080p one) you could get xrandr to render your desktop in 3840x2160 and then display it downsampled at 1920x1080 
`xrandr --fb 3840x2160 --output YOURDISPLAYNAME --mode 1920x1080 --scale 2x2` should do the trick

Version info:
    OS: Fedora 30
   Cantata 2.3.1
   Desktop Environment: None
   Compositor: None 
   Window Manager: i3

**Comment by CDrummond** [comment]
If you edit `gui/covers.cpp` and change line 1250 from:

```
    cache.setMaxCost(15*1024*1024*devicePixelRatio);
```

to (e.g.):
```
    cache.setMaxCost(50*1024*1024*devicePixelRatio);
```

Does this help? I'm guessing is that the cache used to store scaled coves is too small to gold om your displayed covers.

**Comment by chm-gh** [comment]
I figured that was the problem after seeing #1248 
Your solution works

**Comment by CDrummond** [comment]
Guess the real issue is determing what the figure should be. 2.3.1 (which you have) has the fix for #1248

**Comment by CDrummond** [comment]
Can you try a lower value? e.g. `25*1024*1024*devicePixelRatio` 50Meg is quite high!

**Comment by aqua36** [comment]
21 was the lowest I could get to work with library maximized so 25 would be a safe/good choice for 4k resolutions. Now if you want to futureproof this value, you would have to consider the utlrawide high resolution monitors that are already on the market. I assume that 25 won't be enough for someone who runs the library view almost full screen with that setup. I don't know if that edge case is worth considering at the moment, it's your decision

**Comment by CDrummond** [comment]
Thanks for that. Can you checkout git/master and see if that helps? I've changed the code to use 8x screen size.

**Comment by aqua36** [comment]
Refactoring the code to use the window size was a good call. The latest commit works for me. 
I could also get `maxCost = sz.width() * sz.height() * 3 * 1;` to work, but I can only say that about my setup
