### ISSUE TITLE
Save podcast playback marks.

### ISSUE THREAD

**Issue by rn2208** [CDrummond/cantata#1499]
Hi, I love listening to conversational podcasts through the cantata. But it is not always possible to listen to it completely. Is it possible to make the program memorize the place where I took off, and then every time I have to scroll and search. Thank you

**Comment by CDrummond** [comment]
I did consider this. However, it would need a lot of special casing in the code. Cantata is an MPD client, and does not have 10% control. Saving the last position when playback stopped would be easy enough. However, restoring it once playback had started would be more fiddly. All doable, but a lot of edge cases just for podcasts.

So, sorry, for me this is a wontfix. As it'll take more time then I have spare for Cantata. I no longer actively use MPD, having switched to logitech media server. Therefore, Cantata is mainly in a bug-fix mode. I will galdy accept pull requests though.

I'm marking all feature requests that I have no time to implement as wontfix.

**Comment by Thaodan** [comment]
Can you mark those were you have no time with help 
wanted or pull request wanted?
Instead those that are not right in cantata but in mpd 
or aren't possible in a client should be wontfix I think.

**Comment by rn2208** [comment]
Of course, this is not the functionality that requires priority intervention. If it ever appears it will be great.

**Comment by rn2208** [comment]
Supplement about podcasts. The long description is not fully displayed.
![Рабочее место 1_017](https://user-images.githubusercontent.com/42857944/59292581-cdf6d700-8c96-11e9-89ce-968a40305641.png)
