### ISSUE TITLE
Compilation fails under Windows 10

### ISSUE THREAD

**Issue by nadstaky** [CDrummond/cantata#1500]
I have used mingw under Windows 10 to firstly build Zlib (fine) and TagLib (fine).
Then, as regards cantata, it fails when creating the .exe

**To Reproduce**
1 ) run cmake with those arguments
cmake ../src -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_TAGLIB=OFF -DTAGLIB_FOUND=1 -DTAGLIB_INCLUDES=c:/dev/taglib/include -DTAGLIB_LIBRARIES=c:/dev/taglib/lib/libtag.a -DTAGLIB_MP4_FOUND=1 -DTAGLIB_ASF_FOUND=1 -DTAGLIB_CAN_SAVE_ID3VER=1 -DZLIB_INCLUDE_DIR=c:/dev/zlib/include -DZLIB_LIBRARY=c:/dev/zlib/lib/libzlib.dll.a -DCMAKE_INSTALL_PREFIX=c:/cantata/install -DCANTATA_WINDOWS_INSTALLER_DEST=c:/cantata -DCANTATA_MINGW_LIBS=c:/dev/MinGW/bin/mingwm10.dll;c:/dev/MinGW/bin/libgcc_s_dw2-1.dll -DCANTATA_SSL_LIBS=c:/dev/ssl/libeay32.dll;c:/dev/ssl/ssleay32.dll

Error 
[ 97%] Linking CXX executable cantata.exe
CMakeFiles\cantata.dir/objects.a(jamendoservice.cpp.obj):jamendoservice.cpp:(.text+0x13c4): undefined reference to `_imp___ZN6TagLib5ID3v15genreEi'
CMakeFiles\cantata.dir/objects.a(jamendoservice.cpp.obj):jamendoservice.cpp:(.text+0x13d3): undefined reference to `_imp___ZNK6TagLib6String9toCStringEb'
CMakeFiles\cantata.dir/objects.a(jamendoservice.cpp.obj):jamendoservice.cpp:(.text+0x141a): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
CMakeFiles\cantata.dir/objects.a(jamendoservice.cpp.obj):jamendoservice.cpp:(.text+0x1495): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\cantata.dir\build.make:2975: cantata.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:78: CMakeFiles/cantata.dir/all] Error 2
mingw32-make: *** [Makefile:151: all] Error 2

**Expected behavior**
Cantata should compile fine

**Screenshots**
None

**Version Info**
 - OS: Windows 10
 - Cantata Version: git
 - MPD Version: not installed yet
 - CMake options 
cmake ../src -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_TAGLIB=OFF -DTAGLIB_FOUND=1 -DTAGLIB_INCLUDES=c:/dev/taglib/include -DTAGLIB_LIBRARIES=c:/dev/taglib/lib/libtag.a -DTAGLIB_MP4_FOUND=1 -DTAGLIB_ASF_FOUND=1 -DTAGLIB_CAN_SAVE_ID3VER=1 -DZLIB_INCLUDE_DIR=c:/dev/zlib/include -DZLIB_LIBRARY=c:/dev/zlib/lib/libzlib.dll.a -DCMAKE_INSTALL_PREFIX=c:/cantata/install -DCANTATA_WINDOWS_INSTALLER_DEST=c:/cantata -DCANTATA_MINGW_LIBS=c:/dev/MinGW/bin/mingwm10.dll;c:/dev/MinGW/bin/libgcc_s_dw2-1.dll -DCANTATA_SSL_LIBS=c:/dev/ssl/libeay32.dll;c:/dev/ssl/ssleay32.dll

**Additional context**
I've had an error to build jamendoservice.cpp : makegw32-make complained about not finding testing.h (though it is in C:\dev\taglib\include\taglib). I had to copy all include files to C:\dev\taglib\include and, to be sure, to C:\dev\taglib in order to solve the issue.

I can compile cantata-git under macOS without any issue.

Thanks for your help

**Comment by CDrummond** [comment]
The compilation has worked, what you have is a linker error. This error seems to imply there is something wrong with your TagLib build.

Sorry, but as stated in the main github page, Windows and macOS builds are no longer actively supported. I have no time to look into this. Cantata itself is mainly in a bug-fix state, as I have switched from MPD to logitech media server.
