### ISSUE TITLE
solid-lite requires udev on non-Linux

### ISSUE THREAD

**Issue by 0-wiz-0** [CDrummond/cantata#1503]
I've just packaged cantata for pkgsrc, the package will get a webpage in the next day at http://pkgsrc.se/audio/cantata
I have only one issue: `rdparty/solid-lite/CMakeLists.txt` assumes that everything but Windows and macOS has udev support. Actually, I think it's the other way round - only Linux has that.
Perhaps replace the check `if (NOT WIN32 AND NOT APPLE AND WITH_SOLID_UDISKS2)` with something like `if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux" AND WITH_SOLID_UDISKS2)`?

**Comment by CDrummond** [comment]
Can't you just pass `-DENABLE_UDISKS2=OFF` Does your system have udisks2 but not udev?

**Comment by CDrummond** [comment]
I've updated git/master to set `ENABLE_UDISKS2=OFF` for non-Linux builds. Does that help?

**Comment by 0-wiz-0** [comment]
That looks fine, thanks!
