### ISSUE TITLE
Notifcation module for KDE

### ISSUE THREAD

**Issue by coldspark29** [CDrummond/cantata#1506]
There are no notifications in KDE Plasma. I tried several mpd notification packages and none of them works.

**Comment by CDrummond** [comment]
Cantata uses freedesktop dbus notifications.

**Comment by coldspark29** [comment]
Installed that, but it doesn't work. Can you please help me?

**Comment by CDrummond** [comment]
Sorry, I don't use KDE. All Cantata does is create a notification on the relevant DBUS interface, and its up to the desktop to show.
