### ISSUE TITLE
HTTP stream problem

### ISSUE THREAD

**Issue by mihapiha** [CDrummond/cantata#1507]
**Describe the bug**
During HTTP streaming from remote MPD instance sometimes the sound stops.
I haven't observed any particular pattern when does it happen, sometimes it happens at the beginning when I have just openned Cantata and sometimes after long session of listening. Restarting Cantata resolves the issue.

**To Reproduce**
1. Play HTTP stream from MPD
2. Sound stops, going to next song doesn't help, duration bar is still progressing.
3. Close Cantata and reopen and sound comes back on.
**Expected behavior**
No need to close & reopen Cantata

**Version Info**
 - OS: KDE Neon, updated
 - Cantata Version: 2.2.0 installed from Ubuntu repo
 - MPD Version: 0.19.0 on Raspberry Pi 3

**Comment by CDrummond** [comment]
Sorry, this not an area of code that I personally wrote, use, or maintain.

**Comment by vpxyz** [comment]
Your mpd version it's quite old (2016 release) . You should try to use the latest mpd release (0.21.10) . There are many bug fix fixes related to http.

**Comment by CDrummond** [comment]
Just noticed your on Cantata 2.2.0! That's over 1.5 years old! There have been fixes to HTTP stream playback since then. Please, try the latest **before** raising issues!
