### ISSUE TITLE
Have "previous track" button restart the current song

### ISSUE THREAD

**Issue by medakk** [CDrummond/cantata#1509]
A lot of other music players have the following behaviour for the "previous track" button:

1) If we're less than 4 seconds into the track, go to the previous track
2) else replay the current track

Is it possible to do the same within Cantata? I find this very useful when using other music players.

Thanks for the great work on Cantata!

**Comment by CDrummond** [comment]
Yup, that sounds like a very good idea. Should have done this a long time ago, and should be trivial to implement.
