### ISSUE TITLE
Windows (or OS X) support and binaries

### ISSUE THREAD

**Issue by SethosII** [CDrummond/cantata#1510]
I just read the release note of 2.3.3 and there it's stated that binaries for Windows and OS X won't be created anymore. Is there a general plan to drop suport for Windows or OS X?

I would like this to be continued and also the binaries, as this will have the benefit of only one who needs to do it and in case you do this, this would also be authoritive (instead of someone else building it and claiming it is the original, but maybe something malicious was added).

**Comment by CDrummond** [comment]
Sorry - but I have no time to keep windows and macOS binaries up to date. I use neither of these OSs, and never actively used nor tested the builds.

Cantata is very much in a bug fix only state, I will not be adding any major feaures. I no longer actively use Cantata or MPD, having switched to LMS for my music server needs.
