### ISSUE TITLE
Export currently playing song in a text file

### ISSUE THREAD

**Issue by MartyLake** [CDrummond/cantata#1513]
**Is your feature request related to a problem? Please describe.**
As a twitch streamer, I rely on the current song name being written to a file to add this information to OBS overlay.

**Describe the solution you'd like**
An option in cantata where I can specify the path of the file where cantata would writes tag info according to the music you are listening.

**Describe alternatives you've considered**
I don't have considered coding it myself, but it may be simple enough to create a python script/app that checks with mpd for this information and replace the file on disk, even on windows ?

**Comment by CDrummond** [comment]
Sorry, but this is way too niche - not something I'm goin gto add to Cantata. As you correctly state, you could get this info directly from MPD (perhaps via mpc or a little python script, or if you were on Linux via the MPRIS dbus messages).

**Comment by MartyLake** [comment]
I understand :)

I hacked together an ugly bat file, here it is for posterity

```batch

:loop
mpc.exe > mpc_now_playing_raw.txt

:: keep the first two lines only
:: set counter
setlocal ENABLEDELAYEDEXPANSION
set /A counter=0
for /f "delims=" %%i in (mpc_now_playing_raw.txt) do (
:: increment counter for each line read
  if !COUNTER!==0 set line1=%%i
  if !COUNTER!==1 set line2=%%i
  if !COUNTER!==2 goto timeout
  set /A counter=counter+1
)

:timeout
set now_playing_text=%line1%   %line2%
echo %now_playing_text% 
echo %now_playing_text% > mpc_now_playing.txt
timeout 2
endlocal
goto loop

pause
```
