### ISSUE TITLE
Complex rules for Smart Playlists

### ISSUE THREAD

**Issue by JerwuQu** [CDrummond/cantata#1514]
**Is your feature request related to a problem? Please describe.**
I want to be able to create smart playlists for the compilation album series that I have, that at the same time excludes any songs that has a rating below 3.
The albums themselves all have similar names, like "Cool Album 1" and "Cool Album 2". I know there is a wildcard rule for the genre field, but currently, it seems I cannot write `Cool Album *` as a rule for the Album field, it only seems to exist for the Genre field.

**Describe the solution you'd like**
EDIT: A simpler solution is described [in the comment below](https://github.com/CDrummond/cantata/issues/1514#issuecomment-513455408).

~I'd like wildcards for all fields if reasonable, but even better would be the ability to write more complex rules by hand similar to what foobar2000 allows in their auto-playlists, which eliminates the need for specific functionality for each field by instead having a minimal language for defining playlist rules.
Here's a foobar2000 auto-playlist rule example:~
```
(%album% HAS eurobeat OR %path% HAS eurobeat) 
  AND 
(%rating% MISSING OR %rating% GREATER 3) 
  AND 
%length_seconds% GREATER 180
```

~If this is to be done, it could (and should) probably be more simplified and strict. The previous ruleset could, for example, also be written like this:~
```
(and 
  (or 
    (contains $album "eurobeat") 
    (contains $path "eurobeat")) 
  (or 
    (empty $rating) 
    (greater-than $rating 3)) 
  (greater-than $length 180))
```

I'm of course open to other ideas. 
I simply suggest what I am used to. If there's a better solution, I'm all ears!

**Describe alternatives you've considered**
It would be to manually throw all the album songs into a regular playlist and then keep it updated myself.

**Comment by CDrummond** [comment]
Try unchecking "Exact match" in the rule dialog.

**Comment by JerwuQu** [comment]
Ah, my bad, I must have misunderstood what that did since that solved the album problem.
(I actually had it unchecked but I also had an `*` in the field which made it not work)

Then, is there a way to exclude songs in a rating range? Aka. have a rating range but _also_ include songs without a rating. I suppose all that complex stuff I was going on about could be skipped and there could instead be a checkbox right next to the existing rating range if a solution doesn't already exist.
Example:
![image](https://user-images.githubusercontent.com/3710677/61577484-2916b780-aae8-11e9-9924-13a12d1c7ac9.png)

**Comment by CDrummond** [comment]
Code has been updated for "Include unrated." However, I have no rated tracks, so am unable to check at the moment. Any chance you could checkout git/master, compile, install, and try?

**Comment by JerwuQu** [comment]
Awesome! Unfortunately, I will be busy for the rest of today, but I'll give it a try first thing tomorrow.

**Comment by CDrummond** [comment]
Hey, there is no rush! As stated, its not tested - so probably has bugs :)

**Comment by JerwuQu** [comment]
Hey, I had some time left over tonight to try it out, and it seems to work! I can't vouch for the dynamic playlists since I don't use them, but for smart playlists it works as expected. Thanks a lot!
