### ISSUE TITLE
Artists don't separate

### ISSUE THREAD

**Issue by superluig164** [CDrummond/cantata#1516]
I use the / character to separate fields in my music library.  I'm not sure how it's supposed to act when there are multiple artists on a song, but it doesn't handle it properly.  In the lists, there are multiple entries for collaborations and songs by only one artist.  In the info panel, it just won't find info for the collaboration songs because it searches with the /.  Oddly, genres do separate correctly, but artists don't.

**Comment by CDrummond** [comment]
Cantata gets its tags from MPD.
