### ISSUE TITLE
complex dynamic playlist by stars

### ISSUE THREAD

**Issue by private-lock** [CDrummond/cantata#1518]
I want to add items from a dynamic playlist by ratio: e.g.

20 % of 0 star - non rated so far
30 % of 3 stars
40 % of 4 stars
10 % of 5 stars

So whenever a new songs has to be chosen, first the percentage distribution has to decide, which group to chose from. This should not overuse the few really outstanding songs and totally avoid known sad/unwanted songs, but still encourage me from time to time to add ratings.

If you cannot come up with the distribution, I could also live with saying: I want 3 to 5 stars inclusive unrated songs (adding just a single checkbox to the UI, each star would get an equal chance). Another way of seeing this would be to explicitly exclude 1 and 2 stars.

In contrast to #1334 it would not only be necessary to include 0 rating, but also to restrict e.g. to unrated songs only! That is currently 0-0 stars is taken to mean don't care for stars.

Thanx

**Comment by CDrummond** [comment]
Sorry, but that is not something I have any interest in implementing. But, please feel free to implement abd submit a pull request.

Also, please note that Cantata is mainly in a bug-fix only state. I no longer actively use Cantata nor MPD - having switched to Logitech Media Server.
