### ISSUE TITLE
rock* matches anything on Genre in the Smart Playlists

### ISSUE THREAD

**Issue by nemonein** [CDrummond/cantata#1519]
**Describe the bug**
(It's weird I reported this yesterday, but it's gone..)
'string with an asterisk' matches anything.

**To Reproduce**

1. Set Genre in the Smart Playlists, set rock* (Type it, not selecting it from the dropdown menu.)
![Cantata-Smart-playlist-0](https://user-images.githubusercontent.com/5688288/62835458-c3a38a00-bc93-11e9-8ead-92b7eb1fb9a5.png)

2. Append it to Play Queue
![Cantata-Smart-playlist-1](https://user-images.githubusercontent.com/5688288/62835465-de75fe80-bc93-11e9-87a6-4440ab17e7ed.png)

You can see 'Voyage to India' is selected, of which genre is 'Pop', not related with 'rock'.
I appended the smart playlist after Kenny Wayne Shepherd - The Place you're in.
If the genre is set 'Rock*', or 'Blues*', it works fine. There is Rock, or Blues on the Genre Dropdown menu, but not rock or blues. 

**Expected behavior**
Only *rock* has to be selected.

**Version Info**
 - OS: Linux KDE Neon
 - Cantata Version: 2.3.3
 - MPD Version: 0.20.18

**Comment by CDrummond** [comment]
Yeah, I can see the bug. I'm checking for genres's begging with the specified string - but case sensitively. If no match is found, I don't add a genre filter. So, I should be checking case-insensitively, and if none found, don't bother searching for tracks.

**Comment by CDrummond** [comment]
I've updated the code - yet to test, hence I've not closed this yet.

Until the next release, I suggest you use "Rock*" not "rock*" - so that the case matches,

**Comment by nemonein** [comment]
Thank you very much!

**Comment by CDrummond** [comment]
Checked code, and confirmed change works.
