### ISSUE TITLE
Random bugs

### ISSUE THREAD

**Issue by shlyakpavel** [CDrummond/cantata#1526]
Hello. 
Here's something that can cause real pain. https://github.com/CDrummond/cantata/blob/daff2b37427f69912889ee3f69650553ac18e635/tags/tags.cpp#L1564
The `encodedName` reference [becomes invalid](https://doc.qt.io/qt-5/qbytearray.html#constData) when temporary object returned by a function is destroyed. Sometimes it may remain in memory for a while so everything is okay. However, in other cases the object is destroyed before encodedName is used... That may lead to *impossible-to-catch* bugs. I hope this helps. Have a nice day!

**Comment by CDrummond** [comment]
Not sure this is really an error, depends on how TagLib uses the const char * - my guess is it will take a copy, therefore no harm.

Do you have a crash to indicate this is an error? Or are you simply scanning the code?

**Comment by shlyakpavel** [comment]
> Not sure this is really an error, depends on how TagLib uses the const char * - my guess is it will take a copy, therefore no harm.

The pointer becomes invalid right after that line. There is no time to make copies...
> Do you have a crash to indicate this is an error? Or are you simply scanning the code?

In fact, it is stored in ram for loooong time so everything is okay here most of the times.

**Comment by CDrummond** [comment]
No. The pointer does not become invalid right after that line. It becomes invalid when the QString created from the QFile::encodeName is destroyed (when it goes out of scope). But this is not destroyed until after the oggMimeType() function is complete.

**Comment by shlyakpavel** [comment]
> No. The pointer does not become invalid right after that line. It becomes invalid when the QString created from the QFile::encodeName is destroyed (when it goes out of scope). But this is not destroyed until after the oggMimeType() function is complete.

Yes, you're right. Sorry for troubling here
