### ISSUE TITLE
Folder view

### ISSUE THREAD

**Issue by phggrue** [CDrummond/cantata#1527]
The folder view does not act as expected.
Seems to be a little strange metadata view (wav and flac files)
Expected is a view as from a file manager. Folder/filenames sorted by name.

**Comment by CDrummond** [comment]
Folder view has 3 sub-items; one MPD view - where listing is from MPD, so it controls order, etc. The other 2 (Home and Root) are regular file manager style listts (with files filtered via extension - so as to, attempt to, show music files only)

**Comment by phggrue** [comment]
Sorry, I have to look at the settings.

Am Mi., 21. Aug. 2019 um 10:14 Uhr schrieb CraigD <notifications@github.com

**Comment by phggrue** [comment]
Sorry, I checked the folder views sub-items, but it's not what I expect from an folder view.
My cue sheets are very well sorted at the end of the view.
But all other files seems to be sorted by tags and mine are not very well tagged.
What I would like to have is a sorting only by filenames, of course it would be perfect if all not playable files are sorted out. If it's easy to implement.....
Thankx for your efforts.
