### ISSUE TITLE
Cantata crashing with xfce, qt5ct

### ISSUE THREAD

**Issue by alan12345678** [CDrummond/cantata#1528]
The message in my /.xsession-errors asked me to post the following bug report, so I hope this is appropriate.

`and include the following stack trace:

  /usr/lib/libc.so.6 : ()+0x3a7e0
  /usr/lib/libgdk-x11-2.0.so.0 : gdk_display_open()+0x62
  /usr/lib/libgdk-x11-2.0.so.0 : gdk_display_open_default_libgtk_only()+0x52
  /usr/lib/libgtk-x11-2.0.so.0 : gtk_init()+0x13
  /usr/lib/qt/plugins/styles/libqgtk2style.so : ()+0x2592b
  /usr/lib/qt/plugins/styles/libqgtk2style.so : ()+0x27242
  /usr/lib/libQt5Widgets.so.5 : QStyleFactory::create(QString const&)+0x12e
  /usr/lib/libQt5Widgets.so.5 : QApplication::setStyle(QString const&)+0x8
  cantata : Application::init()+0x5b
  cantata : main()+0x2026
  /usr/lib/libc.so.6 : __libc_start_main()+0xf3
  cantata : _start()+0x2e`

**Comment by CDrummond** [comment]
And that crash is in qgtkstyle - not a Cantata issue.
