### ISSUE TITLE
question, not an issue

### ISSUE THREAD

**Issue by alan12345678** [CDrummond/cantata#1529]
Pls excuse asking here but I see no links anywhere to any form of docs - feel free to correct!

Simple question: does Cantata support any form of sorting for "album artist" e.g. `albumartistsort` or `sort album artist`?

Very happy with album pane display but need to know if I'm wasting my time updating all my library tags. If not supported then no point, if supported I'd like to know which kind? Using id3v2.4, have read those docs. Can I use TXXX fields? TPE2?

Please advise, many thanks.

p.s. FANTASTIC player. Very very well thought out :)

**Comment by cpchan** [comment]
Yes. Cantata does support "Album Artist" sort. It using "Album Artist" then Artist (for albums with no "Album Artist". You can also sort by composer with a tweak. Please see "Preferences" -> "Interface"-> "Tweaks".

**Comment by alan12345678** [comment]
Thank you :)

Not entirely what I meant though. FYI and to be clear, I was not asking does it recognise the `album artist` tag but does it allow one to set how that actual sorting is applied. If I may, a short demonstration should help clarify:

Let's say I have a lot of albums by ZZ Top. No problem at all that they're correctly grouped. But I have two albums - compilations by `Various Artists` that are re-interpretations of ZZ Top's songs. In all other players I've used one is able to set a tag of a form `albumartistsort` or `Sort Album Artist` and which means that when the tag for `Album Artist` is set to `Various` the `Sort Album Artist` tag (and indeed `Sort Artist` tag) can be set to ZZ Top, allowing (in this case) a compilation to be sorted into but not *by* the chosen album artist (or artist).

Of course I could label the above compilations album artist as ZZ Top, but being a bit of a music nerd I find that difficult and slightly illogical.

The described level of sorting has always struck me as a very sensible feature. Doesn't appear to be enabled in Cantata, great player that it is :)

**Comment by CDrummond** [comment]
Yes, Cantata reads, and uses, the AlbumArtistSort, ArtistSort, and AlbumSort fields from MPD.

You cold have easily confirmed this by just updating the tags of 1 album...

**Comment by alan12345678** [comment]
Thank you for confirming. I cannot seem to get these tags set/read? They're included in my `mpd.conf` but DO NOT show up in Cantata. Obviously I have been testing this. Sorry to post here but since there's no docs I can find.

Not sure where to go from here. Local build? (I used the community package). Will keep trying... could be my tagger `Kid3-qt` doing something wrong.

**Comment by alan12345678** [comment]
Have posted on super_user, so trying to get help elsewhere. I have reset/redone my `mpd.conf` and verified with log files etc. that all is correct.

Using
    mpc find '(albumartistsort == "Bob Marley")'
returns expected result. Tags are set and read.

The prefs panel in `cantata` offers me this in "server information"
    

    Server
    --
    Protocol: | 0.21.11
    Uptime: | 0:03:58
    Playing: | 0:00:00
    Handlers: | alsa, cdda, file, gopher, http, https, mms, mmsh, mmst, mmsu, nfs, rtmp, rtmps, 
    rtmpt, rtp, rtsp, smb
    Tags: | Album, AlbumArtist, Artist, Composer, Date, Disc, Genre, MUSICBRAINZ_ALBUMID, 
    Name, Title, Track

my `mpd.conf` contains this line

    metadata_to_use	 
   "artist,album,artistsort,albumartistsort,title,track,name,genre,date,composer,performer,disc"

I have NO idea what's going on or why. I see that the tags are set, I've asked MPD to serve them (?) but this config is not reflected in "server information".

**Comment by alan12345678** [comment]
Yep, the problem was the fact that it writes its own version of `mpd.conf` locally, thus ignoring the options actually set within mpd.

Sorted that out now, finally working as desired/expected

**Comment by CDrummond** [comment]
No, it doesn't. The only mpd.conf written is for local/basic mode. This starts it's own mpd instance, and is for simple usage. No over writing occurs, as this mode cannot use the system's mpd.conf

**Comment by alan12345678** [comment]
Okay, understood. However, I have just pointed everything at my mpd. Was that wrong? It works as desired now. I'd assumed "out of the box" was fine, but again with no docs that I can find, the only options I've ever seen are those inside the gui itself.

I don't understand the idea of local vs ? I may be misunderstanding, but I thought this was a client, and mpd the 'server'? I'm running a per-user instance of mpd as per Arch-wiki. I know of no other way of setting all this up, particularly since I'm neither a programmer nor wrote any of the code.

How else are we supposed to learn optimal setup? How am I supposed to know whether resorting to hacking about is making things better or worse?

Either way, my point was that whatever it wrote in its local mpd.conf DID NOT include the `albumartistsort` tags until I added them manually.

I'm pleased that the player is so well thought out, just frustrated that it should take me days to figure out how to configure everything properly.

**Comment by CDrummond** [comment]
Yeah, sorry. The 'Basic' mode - is where Cantata starts its own MPD instance.  I'll add `albumartistsort,artistsort,albumsort` to its tag list.

**Comment by alan12345678** [comment]
Nice!

Do please just keep in mind that - certainly based on other  players I've used - they will sort albums or artists differently if they do/do not have the `MUSICBRAINZ` tag(s) used anywhere.

For those of us who have accumulated digital music across the years and different devices and Oses tags can be a bit messy. Some apps (like Windows Media Player) will never query Musicbrainz but instead use their own referrers. Music added later or via another OS may indeed use `Picard` or similar. The results can be a little surprising when one sees albums, artists or even tracks separated out in a collection. Usual culprit is because an earlier tagging didn't include a field like `ReleaseType` or `MUSICBRAINZ_artist`.

Might be nice to offer the user a choice of which tags to include/exclude, rather than set defaults (beyond the obvious `album`, `track`, `title`,`artist` of course)

**Comment by CDrummond** [comment]
No. Basic mode is named "Basic" for a reason. If you want a more advanced mode, then use the standard MPD mode.

**Comment by alan12345678** [comment]
Oh! Ah...

So, I have to do what? Delete all the configs, and restart it, and do it in 'advanced mode' or something? I'd COMPLETELY forgotten it asked me all that during setup. My apols.
