### ISSUE TITLE
Default setting for replaygain and maybe others...

### ISSUE THREAD

**Issue by thenktor** [CDrummond/cantata#1531]
Hi,

on Cantata startup my audio volume has changed and I've wondered why? I've then found the replaygain settings and noticed that Cantata turns off replaygain on startup.
But I've preconfigured replaygain to "album" in mpd.conf and IMHO a client should not change this until I explicitly want it to do so.
Therefore I suggest a "Do not change" entry for the replaygain drop-down menu and use this as default.
Maybe other settings (crossfade?) are affected, too.

Cantata 2.3.2

**Comment by CDrummond** [comment]
No, Cantata does not reset the the replaygain to off - I have just confirmed. Cantata gets the initial MPD setting from MPD, and stores this in its own config file (different setting per server). Then when Cantata connects its sends its stored reaplygain setting to MPD. The reason for this is that MPD allows the user to change this setting, but does not persist any changes (see #1041) - so Cantata works-around this. MPD persists the crossfade settings in its 'state' file, so this is OK - but it does not do the same for replaygain. IMHO, this is the real bug - MPD should persist this setting.

I've added a checkbox to the playback settings page to control this behaviour. Can you update to git/master and confirm this is OK?
