### ISSUE TITLE
Option to automatically calculate replay gain on CD import

### ISSUE THREAD

**Issue by aardy1** [CDrummond/cantata#1532]
Hi
When I import a CD into my library in Cantata it asks me if I want to caculate the replay gains. That's good since I do. But I was wondering if we could have an option in the preferences to always calculate the replay gains (which is what I do, I always click YES), and if set just calculate them, rather than popping up the dialog.
thanks
graham

**Comment by CDrummond** [comment]
I can see why this would be a nice idea. Unfortunately the 2 pieces of code are in separate areas, and use diferent dialogs, etc. Automatically opening the replaygain dialog after CD ripping might look a bit odd. So, for now,I'm leaving as is.
