### ISSUE TITLE
Unified Library

### ISSUE THREAD

**Issue by aardy1** [CDrummond/cantata#1533]
Hi
For various reasons I have my music in multiple different folders. 
I can currently see all this music in Cantata of course by setting up different collections with different music folders.
What I am requesting is a "unified collection" option which shows me all music in all collections -- sort of a super-collection (a collection of collections). Or alternately a collection which can have more than one folder of music in it.
thanks
graham

**Comment by Thaodan** [comment]
Cantata doesn't handle any collections. 
Thats an mpd thing.

**Comment by aardy1** [comment]
So it seems I can set up a unified/virtual collection using an mpd.conf file in MPD.
But in cantata the only way I have of specifying a collection is to chose a folder (Settings -> Configure -> Collections).
What happens if my MPD collection is not a folder, but some sort of MPD virtual collection, or database, etc?

**Comment by cpchan** [comment]
One way of doing this is to use a virtual file system like unionfs[1] (if your platform support a file system like this). I have been unifying my video collection on various disks under one mountpoint for years.

[1] https://www.wikiwand.com/en/UnionFS

**Comment by cpchan** [comment]
sorry, her is a more direct url:

https://en.wikipedia.org/wiki/UnionFS

**Comment by CDrummond** [comment]
This is not a Cantata issue.
