### ISSUE TITLE
Return binaries

### ISSUE THREAD

**Issue by majkinetor** [CDrummond/cantata#1534]
I noticed [chocolatey package](https://chocolatey.org/packages/cantata) I created doesn't have latest version tat grabs binaries from the releases page. Then I saw:

> NOTE There are no windows or mac binaries, as I will no longer be creating these.

Would you consider returning those ? It will certainly help with discoverability.

**Comment by CDrummond** [comment]
Sorry, not going to happen. My time for Cantata is severly limited - and I don't use windows. The compilation instructions, however, should stil be valid -  so you are free to create your own binaries. If compilaiton fails, feel free to send a pull request with a fix - but I have no time to look into windows/macOS specific issues myself.
