### ISSUE TITLE
A stand out search bar.

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [CDrummond/cantata#1535]
**Is your feature request related to a problem? Please describe.**
When having a large music library, navigating to search bar is quite cumbersome.

**Describe the solution you'd like**
Having a sticky search bar in the toolbar would be very helpful.

Thank you for the great program!

**Comment by CDrummond** [comment]
Each view (even queue) has its on search - and this will remain persistent if you don't close it.

**Comment by CDrummond** [comment]
No. Each view (apart from Folders, etc) has its **own** search field - use menu item, or Ctrl-F will bring up seach field. This will remain until closed.

**Comment by GreatBigWhiteWorld** [comment]
Ah... I got it. Great. That's what I needed. Thanks.
