### ISSUE TITLE
cannot edit favorites in cantata, what happened ?

### ISSUE THREAD

**Issue by JohanvdS** [CDrummond/cantata#1537]
I try to add or to edit a new url in favorites, but the editing etc screen is in grey display. cannot do anything at al. what is this ?

**Comment by CDrummond** [comment]
Works for me - just tried.

**Comment by JohanvdS** [comment]
Yes but here it isn't working. I could only ad to favorite from shoutcast/ tunein and ofcourse can edit this one. But a free url adding from the internet to add in fovorite is not possible. It refuse to add these. I was also finding out if i can use pulse and choose a chromecast audio. but even pulse is working In pulse itself i cannot change the audio (music) to a another hardware like chromecast. 
maybe some misconfiguration which i do not see ? I have included mpd  conf and a pic of these favorite thing :)

Hopefully you can help me a bit to understand what is wrong ?

yours

Johan

-- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com


15 sep. 2019 10:48 door notifications@github.com:

**Comment by CDrummond** [comment]
I'd guess you have no "playlist_directory" (or an invalid one) defined in mpd.conf Favourites are stored in a file named "[Radio Streams].m3u" within that directory.

Can't help with hardware device - that's an MPD issue.

Sorry, but my time for Cantata is **severely** limited. I no longer use Cantata or MPD - having switched to the open-source logitech media server. I'm develping a material-themed, browser-based, UI for this. LMS also handes chromecast, DLNA, and AirPlay devices.

**Comment by JohanvdS** [comment]
Great, thank you for so far I will not border you anymore ;)
Btw i used a very long time squeeze logitech mediaserver which it works great. Even had a logitech internetradio? but they stopped with 'logitech' thats why i don't use it anymore. They switched over to eusmartradio, but I never liked this. 

If you like to test the opensource mediastreamer  I am in for it if you like. I ike to test such things.

yours

Johan
-- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com


16 sep. 2019 08:28 door notifications@github.com:

**Comment by CDrummond** [comment]
You do not need a real squeezebox to use LMS. You can use Chromecast, UPnP/DLNA, AirPlay (I use 2 devices), squeezelite (on Windows, mac, and linux, there is even a dedicated in-memory raspberry pi solution (piCorePlayer). I do have 1 squeezebox radio - but I was using AirPlay and piCorePlayer for over a year before I bought a second had one. With my devices i can play in sync, move the queue from one to another, play YouTube, internet radio, etc, all controlled from a web page on my phone or laptop.

**Comment by JohanvdS** [comment]
Hi i downloaded the logitech mediaserver installed it and play, but i wonder where can i play and send files to chromecast ? Or did i even set something wgrong ?

i am having plenty time to find things out since i have a burn-out lol better then arue with other problems ;)

thanks

Johan
-- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com


16 sep. 2019 09:01 door notifications@github.com:

**Comment by CDrummond** [comment]
You need to install the chromecast bridge plugin. in LMS, go to the plugins page, it should be listed there (I'm pretty sure is an officially supported 3rd party plugin). Anyhow, for LMS questions your best bet is the slimdevices forum - [https://forums.slimdevices.com](https://forums.slimdevices.com)
