### ISSUE TITLE
'Failed to send command to "New Collection 1" (127.0.0.1:6602) - not connected'

### ISSUE THREAD

**Issue by iconoclasthero** [CDrummond/cantata#1538]
**Describe the bug**
Cantata will not connect to alternate MPD instance control port (6602):
'Failed to send command to "New Collection 1" (127.0.0.1:6602) - not connected'

**To Reproduce**
1. Go to 'Connection Settings'
Enter Host 127.0.0.1 Port 6602
Enter correct password (unnecessary for this server as the relevant MPD default permissions line is:  default_permissions             "read,add,control,admin"
Specify correct music folder on local machine ('/library3/music')

**Expected behavior**
Connect to localhost:6602 or 127.0.0.1:6602.  GMPC will connect with the same connection info (e.g., same machine state, parameters...)

**Screenshots**
I don't see how this is helpful

**Version Info**
 - OS: Ubuntu 18.04.3 LTS
 - Cantata Version: 2.2.0 (from Ubuntu repo) and 2.3.3 (self-compiled)
 - MPD Version: 0.21.14
 - CMake options (other than default):  none

**Additional context**
I can't think of anything else.  This is pretty elemental and I'm not sure why GMPC works and Cantata does not.

**Comment by CDrummond** [comment]
Works for me - just tried.

**Comment by iconoclasthero** [comment]
![Selection_534](https://user-images.githubusercontent.com/535962/64995093-5c877f80-d8a8-11e9-8d6e-fb49f5195a70.png)
![Selection_532](https://user-images.githubusercontent.com/535962/64995094-5d201600-d8a8-11e9-8295-a2a129fd86dc.png)
![Selection_531](https://user-images.githubusercontent.com/535962/64995095-5d201600-d8a8-11e9-8625-7666a1d10822.png)
![Selection_530](https://user-images.githubusercontent.com/535962/64995096-5d201600-d8a8-11e9-8110-2262b8cca3ec.png)
Well, it isn't working for me.  Is there any other way to get more support than "Works for me - just tried."?

**Comment by iconoclasthero** [comment]
![Selection_535](https://user-images.githubusercontent.com/535962/64995254-ba1bcc00-d8a8-11e9-8dbe-30377a5ee195.png)

**Comment by CDrummond** [comment]
Sorry - I have no time for this. I no longer actively use Cantata or MPD (switch to logitech media server). So, my time for Cantata is **very** limited. Perhaps its a password issue.

**Comment by trmdi** [comment]
@CDrummond

Excuse me. Is there a good client with a nice UI like Cantata for Logitech on Linux and Android? First time I've heard it from you.

I really like Cantata and it's a pity when you no longer develop it.

**Comment by CDrummond** [comment]
You coud always use my [material skin](https://github.com/CDrummond/lms-material). This is what I use, and allows me to control my setup on my phone, laptop, etc. All via browser (or web-app) without needing to install any other software.

**Comment by iconoclasthero** [comment]
I believe it had something to do with the "max_output_buffer_size" specified in mpd.conf.  Raising it from the default to, in my case, "70000," and uncommenting the line seems to have solved the problem.  This indicates that it is related to the limitations on MPD, perhaps because Cantata uses MPD's resources differently than GMPC.  The clue lies in the mpd.log:
`Sep 20 13:45 : exception: error on client 2: Output buffer is full
Sep 20 13:46 : exception: error on client 3: Output buffer is full`

I should mention that this may be related to my increasing the maximum playlist size to 70000 which was done before installing Cantata.  When attempting to connect both GMPC and Cantata with a 12-song playlist and the following commented out in mpd.conf, everything plays well together.

`# Resource Limitations ########################################################
#
# These settings are various limitations to prevent MPD from using too many
# resources. Generally, these settings should be minimized to prevent security
# risks, depending on the operating resources.
#
#connection_timeout		"60"
#max_connections		"10"
max_playlist_length		"70000"
max_output_buffer_size		"70000"
#max_command_list_size		"2048"
#
###############################################################################
`
