### ISSUE TITLE
New colums for play queue and visualizer bar

### ISSUE THREAD

**Issue by Akrai** [CDrummond/cantata#1539]
I'm trying to migrate from clementine (not maintained and starting to be buggy) to another player that gives me my needs. I've tested a lot of ones and cantata so far has almost all I need, but there are a few things i miss:
-  In the play queue, columns for the bitrate, for the sample rate and for the file size
-  A visualizer of the current track (this is just decoration)
-  The moodbar clementine has, this is a bar that analyzes the whole current track "mood" and makes a graph with it, i really use this one a lot for basically having a look of the different parts with different styles in the same song and this saves me a whole lot of time for analyzing whole albums quickly...

I haven't found a better alternative (for me) to clementine than cantata but specifically the moodbar is a musthave for me unfortunately... Do you think it could be recreated in some way?

**Comment by CDrummond** [comment]
Sorry, not going to happen. I see no need for these extra fields in the queue, and definitely have no interest in a moodbar -plus Cantata does not always have access the the music files.

As stated on may issues - I no longer actively use Cantata nor MPD, and Cantata is in a bug-fix only state. I switched from MPD to logitech media server about 2 years ago.

**Comment by trmdi** [comment]
Can you say something about why LMS is better than mpd? Just curious.

**Comment by CDrummond** [comment]
That's up to you to decide. However, I like its separation of music server and music player, as well as its audio sync between players. I have 2 airplay compatible speakers, piCorePlayer on a Pi ZeroW, SB player on my Android phone, a squeezebox radio, and even a local-player plugin on my laptop. LMS can play to all of these in sync. It can also play to DLNA/UPnP and ChromecastAudio players. LMS has bult-in support for TuneIn, can support Spotift/Deezer/Qobuz/Tidal (although I use none of these), and has a YouTube plugin (allowing to play YouTube music to all players, etc).

I'm currently writing a [google-material theme'd skin](https://github.com/CDrummond/lms-materia) for its UI, which allows me to control my music from any device without needing to install an app.
