### ISSUE TITLE
Cantata crashes when you update podcast before/after you filter out the played podcasts

### ISSUE THREAD

**Issue by YamiYukiSenpai** [CDrummond/cantata#1540]
**Describe the bug**
Whenever I click the update button on Cantata (before and after click the button that shows unplayed episodes only), it crashes, though audio is still playing.

**To Reproduce**
1. Open Cantata
2. Go to the Internet tab
3. click the update button
4. Click the button that shows unplayed podcast episodes
5. App crashes

*Note*: 3 & 4 can be inverted

**Expected behavior**
Podcast feed should update without the window closing

**Screenshots**

**Version Info**
 - OS: Kubuntu 19.04
 - Cantata Version: 2.3.3
 - MPD Version: 0.21.4
 - CMake options (other than default):

**Additional context**
Here's the stack trace:
```
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x43f60
  cantata : PodcastService::Proxy::filterAcceptsRow(int, QModelIndex const&) const+0x5d
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x24f258
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x25181d
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x252379
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x766
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal)+0x5e
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QAbstractItemModel::endInsertRows()+0x55
  cantata : PodcastService::rssJobFinished()+0x1467
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x766
  cantata : NetworkJob::jobFinished()+0x4ad
  cantata : ()+0x3dbcd5
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x766
  /lib/x86_64-linux-gnu/libQt5Network.so.5 : ()+0xacfc4
  /lib/x86_64-linux-gnu/libQt5Network.so.5 : ()+0x157e99
```

**Comment by CDrummond** [comment]
Hmmm... Not crashing for me. odd. Does it crash if you do not use the filter? i.e. if just showing all podcasts? Not sure what you mean by "update before/after" - seems to imply crashes all the time. Or only when you have used this filter???

**Comment by YamiYukiSenpai** [comment]
If I simply use the filter, app doesn't crash.  However, it crashes if I use the filter before I click the update button, and if I click the update then use the filter.

Both scenarios involve clicking both update AND filter buttons
