### ISSUE TITLE
Feature: add color marker to folders

### ISSUE THREAD

**Issue by supersexy** [CDrummond/cantata#1541]
I really like Cantata, great software! Thank you very much for this!

One feature request: I would like to add color markers to folders while browsing a large collection of files in the "Folders" part of the gui as a quick orientation help. Just a very simple thing that could help set some visual markers, maybe just coloring the folder icons.

**Comment by CDrummond** [comment]
Sorry - Cantata is in a bug-fix only state. I no longer actively use Cantata nor MPD, having switched to logitech media server.
