### ISSUE TITLE
On the Mac, running the make process results in a working app, but no MacOS theming.

### ISSUE THREAD

**Issue by jhclare** [CDrummond/cantata#1543]
**Describe the bug**
Building using MacOS Mojave, resulting .app is not themed to MacOS. 

Strangely, running the .app created in the build directory, _before_ "sudo make install", results in a fully themed app! 

**To Reproduce**
1. Build application using instructions in INSTALL file.
2. Go to "/usr/local" and run Cantata.app
3. App is not properly themed. Under Preferences...Interface...General, Style is set to System Default. 
4. Go to build directory and run Cantata.app
5. App is themed!

**Expected behaviour**
Expect a MacOS themed application in /usr/local.

**Version Info**
 - OS: MacOS Mojave 10.14.6
 - Cantata Version: 2.4.0
 - MPD Version: 0.21.7
 - CMake options (other than default): default
- Using QT5 installed using Homebrew with suggested environment variables set.

**Comment by CDrummond** [comment]
Sorry, I'm no longer actively supporting macOS or Windows. I also no longer have access to macOS. However, the build should work as documented in Cantata's README - that's the only way I ever built it.
