### ISSUE TITLE
Flickering album covers

### ISSUE THREAD

**Issue by JurisMajors** [CDrummond/cantata#1544]
**Describe the bug**
The music covers are flashing from the default disk to the actual cover constantly.

**To Reproduce**
Have a 32 inch screen.

**Expected behavior**
Clearly, the covers should just stay still

**Screenshots**
 https://hostmystuff.xyz/a84b0c5.gif

**Version Info**
 - OS: Arch-Linux
 - Cantata Version: cantata 2.3.3
 - MPD Version: 0.21.15

**Additional context**
If i clear the cache, it will stop flickering for a few seconds but then get at it again. it does not happen on my other, smaller 27 inch screen.
Moreover, the flickering that can be seen in the gif is not even representative of the one that I see with eyes, it is much faster and every annoying.

Also, it only happens when the cantata instance is more than like 90% of the screen

**Comment by CDrummond** [comment]
Please search for existing issues before creating new ones. Already reported, and fixed in git/master for 2.4.0 - https://github.com/CDrummond/cantata/issues/1498
