### ISSUE TITLE
Better position saving

### ISSUE THREAD

**Issue by metafarion** [CDrummond/cantata#1546]
I'd love to see Cantata have the option of saving my last location in the file browser more persistently.  Currently it survives only minimizing-to-tray and switching tabs (Playlists, Play Queue, etc).  It would be really nice if it could persist across server reconnects, relaunches of the program itself, system sleep (that's just a different server reconnect isn't it?), etc.  This would be super helpful for those of us who have to traverse really deep directory trees to get to the place in our library we were listening to last before rebooting or whatever.

**Comment by CDrummond** [comment]
Sorry, not going to happen. Cantata is not a file manager.
