### ISSUE TITLE
cantata should not modify URL fragment.

### ISSUE THREAD

**Issue by crocket** [CDrummond/cantata#1548]
https://github.com/MusicPlayerDaemon/MPD/commit/3f4437266bd4dc64a19a59d83cdca9be493b243a
cantata https://github.com/CDrummond/cantata/commit/0c399ce933b3c78ec16c567f8633a259ce38b6f7

```
> cat /mnt/data/mpd/playlists/Radio.m3u
#EXTM3U
#EXTINF:-1,최신가요 무멘트 Top100 방송
http://vviii.saycast.com#charset=cp949
#EXTINF:-1,편안한 발라드 방송국
http://youliyouli.inlive.co.kr#charset=cp949
#EXTINF:-1,뮤클캐스트
http://www.mukulcast.com#charset=cp949
```

If I play any from Radio playlist, I see the following error in log.

```
Nov 03 16:08 : player: played "http://vviii.saycast.com#charset=cp949/#StreamName:최신가요 무멘트 Top100 방송"
Nov 03 16:09 : exception: Failed to decode http://vviii.saycast.com#charset=cp949/#StreamName:최신가요 무멘트 Top100 방송; Failed to initialize charset 'cp949/#StreamName:최신가요 무멘트 Top100 방송': U_FILE_ACCESS_ERROR
```

If you want to modify URL fragment, you should work with mpd developers.

**Comment by CDrummond** [comment]
**NO** Cantata has bee doing this for **YEARS** - I'm not changing now. Perhaps the MPD developers should have checked with clients????

**Comment by crocket** [comment]
MPD developers cannot know what every MPD client does.
You can work with MPD developers to make it work seamlessly.

**Comment by CDrummond** [comment]
I look forward to your pull request

**Comment by crocket** [comment]
I don't know how to write C++. So, I cannot write pull requests. But, I can facilitate communication and help develop a standard for URL fragment by creating new issues on cantata and MPD.
