### ISSUE TITLE
Always asking for MPD configuration on startup

### ISSUE THREAD

**Issue by hugoconh** [CDrummond/cantata#1550]
Any time I try to start cantata I have to configure the "first run" dialog.

Tried to install manually and from repositories, always same behavior.

It's not an error or crash itself, but it's quite anoying to configure it everytime.

1) I run cantata (no matter if superuser or user).
2) It run the "cantata first run" dialog.
3) I choose the correct directory (it is in an external USB HDD).
4) It runs fine.
5) I restart the program and then again point 2.

It's expected to be a consistent behavior with the MPD and don't ask for it everytime.

 - OS: Kubuntu 18.04
 - KDE plasma 5.12.9
 - KDE frameworks 5.47.0
 - Kernel 4.15.0-66-generic
 - Cantata Version:  2.3.3-obuild1~ubuntu18.04
 - MPD Version: 0.20.18-1build1

If I choose the music directory in the main hdd in the user folder I have the same thing

**Comment by CDrummond** [comment]
Cantata uses Qt's config mechanism to save its config. Sorry, but there is an issue with your system. Works fine for everyone esle.

Sorry, but I have no time to debug issues on every user's system.

**Comment by tye-shutty** [comment]
I also had this issue with Ubuntu 18.04, cantata 2.4.0.

darekdeo's solution here: https://github.com/cdrummond/cantata/issues/600#issuecomment-447624189 worked for me.
