### ISSUE TITLE
Cantata creates a second local mpd.database. Could be me??

### ISSUE THREAD

**Issue by alan12345678** [CDrummond/cantata#1552]
Noticed you'd updated Cantata fairly recently - very nice!

Wondering if the following is simply me having again made a wrong selection? I started fresh with the last version of Cantata, went through the basic setup, chose what I believed was the correct simple single-user setup.

I notice though that while Cantata appears to read the mpd database as configured there (`~/.config/mpd/database`), in fact it writes a new version in `~/.cache/mpd.db` I tested this by deleting this latter file, and when I relaunch Cantata I get the "updating" message and animation. Once it's recreated this second version of `mpd.db` the library is again restored.

Is this simply me again choosing some wrong option when I set Cantata up? I'm very happy that it now reads the full tag information, but I note that unlike previously when Cantata always remembered where I was in the music library, it now starts up in a default directory view, and while the last playing album or track is loaded, the position is not saved, neither is the location. These did previously work.

My previous "faulty" install, which you were kind enough to help me with, wrote a bunch of stuff in `~/.local/share/cantata/` such as `state` `pid` etc. whereas now there's just a config file.

Should I have configured mpd itself to create `mpd.db` as opposed to calling this file simply `database`? Or is this behaviour now default for Cantata?

**Comment by CDrummond** [comment]
Cantata does not create ~/.config/mpd or ~/.cache/mpd* - these are created by MPD. You must be running a per-user MPD instance, not created by Cantata. Which is fine, no issue with that.

But, this is not a Cantata issue.

I'm sorry but I do not have time to look into issues such as this. I no longer actively use Cantata nor MPD (switch to logitech media server about 2.5 years ago). Therefore, Cantata is in a bug-fix only state.

**Comment by alan12345678** [comment]
sure okay, if you don't have time no problem. But I feel you slightly misunderstood me.

AFAIK Cantata is an mpd client correct? So if I'm using Cantata then by default I have mpd running? And since mpd's own instructions suggest a 'per user' config that's what I did.

My post wasn't talking about mpd per se, I was referring to the fact that I'd assumed that Cantata looked at that same database as is defined within mpd's own config. And since mpd itself writes out a state and sticker file, I'd rather hoped that Cantata would read this too.

I'm not at all suggesting there are issues with mpd, merely that Cantata was creating its own local copy. However, since posting I have answered part of my question by renaming my mpd database to "mpd.db" and indeed Cantata now finds it and doesn't write a second one!

But... in a previous installation Cantata would always remember the file/song location etc. and would thus always relaunch or restore to that same position. It no longer does this.

However, since you've just said it's no longer actively maintained, it looks like I'll have to go and find yet ANOTHER music player :(

A real shame, as this is one of the very best I've come across.

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by CDrummond** [comment]
Cantata has never read MPD's database - it only uses MPD's API.

**Comment by alan12345678** [comment]
okay, again no problem.

But the only reason I ever got to Cantata is because even now as I write it's listed both on the mpd man page as "front end client for mpd" and Cantata is mentioned everywhere as "for those who want to use a front end for mpd" ... suggesting Cantata.

Not a complaint just an observation. But it would seem that everyone who ever reviews music players on Linux wants to insist yours is "a front end" or "client".

If I don't need mpd running then great! one less service. However, not sure how/where Cantata will get its library.

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by Thaodan** [comment]
The default setup creates an extra mpd 
instance just for cantata.
If you don't use the default setup (cantata 
creates and starts mpd) then you have to 
do it on your own.

**Comment by alan12345678** [comment]
Yes.

But...

Having used what you describe as 'default setup' (apologies but I can't remember the two options presented, and I'm disinclined to delete settings and start again just to find out) was what I used to use. Indeed there was an entire set of parameters stored alongside its own mpd.db in ~/.local/share/cantata and in which (previous) configuration it would remember its state, display, recent file location etc. and then just like any other player, once restarted it goes directly back to last location.

When I installed the most recent version of Cantata, and the wizard suggested a different 'deafult' option, I followed that. And it's fine that Cantata does indeed refer to my per user instance of mpd. But what Cantata no longer does in this configuration is to write any other information about its state, location, last played etc. Despite it's clearly capable of doing so, for some reason there are no config options to store or reference this information when using an existing instance of mpd. So, when restarted it simply shows a default file view at the root of the music directory, and restores NO information at all, despite it would do in its other configuration.

Seems highly redundant to write a second database, write out a whole bunch of other files, in its own location, yet NOT read that exact same information in when referring to an existing instance of mpd.

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by CDrummond** [comment]
Cantata has a 'personal' mode in which it starts an instance of MPD, and supplies it a simple config file. But even here, all Cantata does is supply MPD with the config and start/stop MPD. All other interaction is through sending messages (the API) to MPD. Cantata has never read, or written, directly to and MPD file.

Also, the default mode is the server-setup, not the 'Personal' ('Basic single user') setup.

Cantata, many years ago, started as a fork of QtMPC. QtMPC cached a trimmed down verison of the MPD music listing to an XML file. Cantata, similarly, used to cache this to an XML file, but now caches to an SQLite database instead. The reason for this, at least initially, was MPD's (IMVHO) bad handling of the 'Album Artist' tag. If a track had 'Artist' set but no 'Album Artist', MPD would just return an empty string when asking for 'Album Artist'. So, Cantata works-around this by using 'Artist' if a track has no 'Album Artist' Similary, when asking MPD for a list of albums, MPD woulkd group by name. So, if you have 'Greatest Hits' by two different artists, MPD would still only return 1 'Greatest Hits' Cantata uses the 'Album Artist' + 'Album Name' (or MusicBrainz ID) to group tracks into albums.

I'm not 100% sure, but I'm pretty sure most of this has been resolved in MPD itself. So, in theory Cantata's local DB could be removed. However, it is deeply embedded in the code and I have no time to make this change myself. Patches are, as always, welcome.

Please dont assume you know what is 'redundant' or not without knowing why something is the way it is. I don't appreciate snide remarks like that. Cantata is open source, developed in my own time, and developed for **my** needs. It's great that others might see some use in it, but I will use my time and my code to develop it the way I like. Don't like that, or don't like the way Cantata works, then use something else - or try and fix it in a positive manner. (Cantata is not, and will most certainly never be, perfect)

As to saving 'state' - Cantata has never stored the current browse level. It will (and should) restore the previously active view (Library, Folders, Online, etc) But it will not (and has never) remembered the location within these (so will not show the contents of Album X by Artist Y if it was shwoing this when closed). It wil also show the curent play queue and current track as detailed to it **from** MPD - as it is MPD that stores this information.

As stated, any issues are issues with your setup. And I'm sorry, but I have no time to provide generic MPD setup support and advice.
