### ISSUE TITLE
quickly show large cover image

### ISSUE THREAD

**Issue by dicktyr** [CDrummond/cantata#1553]
it would be useful to view a larger album cover
by simply clicking one of the thumbnail images
(rather than loading the whole info page)

**Comment by CDrummond** [comment]
Try 'Set Image' As to adding a generic, show large cover - sorry, have no time for this. Cantata is, and has been for a while, in a bug-fix only state. I no longer actively use Cantata nor MPD - switched to logitech media server years ago.
