### ISSUE TITLE
Clipped podcast texts

### ISSUE THREAD

**Issue by rripio** [CDrummond/cantata#1556]
Hello,

When listening to podcasts, we have the nice feature of reading the podcast comment just by hovering the pointer over the list entry.

The problem is that the text is limited in size, and I frequently access podcast that have their comments clipped.

It would be nice that this information could appear in song info panel, similarly to what happens with file metadata, etc., without size limitations.

Maybe some auto resizing (to a certain extent) of the pop-up text in the podcast list would made the trick also.

Thank you!

**Comment by CDrummond** [comment]
I've updated the tooltip to show 1000 characters. As to showing in song info, this would be possible but will be a lot of work. More than I have time for, seeing as I no longer use Cantata nor MPD - Cantata is in a bug-fix only state.

**Comment by rripio** [comment]
Thank you very much!

**Comment by CDrummond** [comment]
Changed my mind. Done for 2.4.0

**Comment by rripio** [comment]
Thank you. I'm eager to try it.
