### ISSUE TITLE
Importing station "Soma FM" into Cantata

### ISSUE THREAD

**Issue by onnotasler** [CDrummond/cantata#1560]
I attempted to create a new station in Cantata, Soma FM, but I cannot import it. When I try, I always get a message "Invalid data". I either misunderstood how to import data or created the file wrong.

Here is the file I created:
https://c.gmx.net/@324910416335473622/lbH7n6JSRueZWvLukRaXpA

Here is what I tried:
Go to "Internet" in Cantata
Clicked on the three lines
In the context menu, opened "options"
Chose "install" -> "from file"
Selected the file
=> I get an error message saying "invalid data".

By the way: If you find the radio station interesting, feel free to include it in Cantata!

**Comment by CDrummond** [comment]
The contents of the stream fie should not be in a folder. However, SomeFM is already in cantata - `Streams -> Menu -> Configure -> Install -> Download`  When installed, this verison will download the list of channels from the website.

Your file has:

soma.fm/icon.png
soma.fm/streams.xml

But these two files should be in the top level, with no soma.fm folder. Just tried, and with these changes your file works.
