### ISSUE TITLE
Question about album covers

### ISSUE THREAD

**Issue by univrsal** [CDrummond/cantata#1562]
First of all, thanks a lot for your work on Cantata, it's an amazing mpd client.
I don't have an issue with it but rather a question about how it grabs the cover art from mpd (if it does that get it from mpd at all). I'm working on a plugin for obs-studio which displays song information and I added support for mpd and I'd like to also like add support for album art, but I'm unsure if there's a way to get that information.

Seeing that Cantata does somehow get that info, I tried looking through the source code but had a hard time finding anything, so I was wondering if you'd be able to help me out a bit.
Thanks in advance!

**Comment by CDrummond** [comment]
`void MPDConnection::getCover(const Song &song)` at line 1511 of `mpd-interface/mpdconnection.cpp` is where Cantata uses the MPD `albumart` API call to ger covers from MPD.

**Comment by univrsal** [comment]
okay thanks a bunch! That does need the file path of the song though is there also a command to get the path for the currently playing song?

**Comment by CDrummond** [comment]
The `status` command wil tell you the current index. `listplaylistinfo` will list all tracks in the current playlist (what Cantata refers to as the play queue) - this will include metadata such as the filepath.

**Comment by univrsal** [comment]
alrighty, I think that's enough to get me going, thanks
