### ISSUE TITLE
Allow surround of variables of custom actions with quotes

### ISSUE THREAD

**Issue by aleixq** [CDrummond/cantata#1563]
**Describe the bug**
Custom actions format specifiers cannot be surrounded by quotes so it cannot be used to work with directories or files with spaces...

**Expected behavior**
use "%d" to escape spaces.

**Screenshots**

**Version Info**
 - OS: Linux 
 - Version: 2.3.3

**Comment by CDrummond** [comment]
The `%d` is programatically replaced - and the command is called by starting a process, so no quotes are required. i.e. `nautilus %d` causes Cantata to call `nautilus` passing a directory name - e.g. `some/dir with/spaces in name/` -- just tried this, and confirmed it works. Also, Cantata does allow you to use the quotes.

What are you trying to do? What is actually failing?

**Comment by aleixq** [comment]
You are right, it's working as it should, I just tried to run  

> echo -e "%d"  Music-to-transfer/

and it outs:

>  "%d"  Music-to-transfer/


but a simple cp is working. So it works!
I was trying to transfer to mtp via  `aft-mtp-cli` .


Thank's !
