### ISSUE TITLE
Issues with cue sheets

### ISSUE THREAD

**Issue by vtnpp** [CDrummond/cantata#1564]
**Version Info**
 - OS: Arch Linux
 - Cantata Version: [`cantata-git`<sup>AUR</sup>](https://aur.archlinux.org/packages/cantata-git/)
 - MPD Version: [0.21.18-1](https://www.archlinux.org/packages/extra/x86_64/mpd/)

I'm having several issues with cue sheets.

## Albums with tracks + .cue

Some of my cue sheets aren't properly parsed when appended to the current playlist.

E.g.:

<details>
    <summary>Not working cue sheet</summary>
    
```
REM GENRE "Technical Brutal Death Metal"
REM DATE 2008
REM DISCID 8E0A830B
REM DISCNUMBER 1
REM DISCTOTAL 1
PERFORMER "Decrepit Birth"
TITLE "Diminishing Between Worlds"
FILE "01 - The Living Doorway.flac" WAVE
  TRACK 01 AUDIO
    TITLE "The Living Doorway"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Reflection of Emotions"
    PERFORMER "Decrepit Birth"
    INDEX 00 04:21:40
FILE "02 - Reflection of Emotions.flac" WAVE
    INDEX 01 00:00:00
  TRACK 03 AUDIO
    TITLE "Diminishing Between Worlds"
    PERFORMER "Decrepit Birth"
    INDEX 00 04:14:42
FILE "03 - Diminishing Between Worlds.flac" WAVE
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    TITLE "Dimensions Intertwine"
    PERFORMER "Decrepit Birth"
    INDEX 00 03:50:16
FILE "04 - Dimensions Intertwine.flac" WAVE
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    TITLE "The Enigmatic Form"
    PERFORMER "Decrepit Birth"
    INDEX 00 03:43:11
FILE "05 - The Enigmatic Form.flac" WAVE
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    TITLE "A Gathering of Imaginations"
    PERFORMER "Decrepit Birth"
    INDEX 00 03:13:65
FILE "06 - A Gathering of Imaginations.flac" WAVE
    INDEX 01 00:00:00
  TRACK 07 AUDIO
    TITLE "Through Alchemy Bound Eternal"
    PERFORMER "Decrepit Birth"
    INDEX 00 04:05:64
FILE "07 - Through Alchemy Bound Eternal.flac" WAVE
    INDEX 01 00:00:00
  TRACK 08 AUDIO
    TITLE "...and Time Begins"
    PERFORMER "Decrepit Birth"
    INDEX 00 04:27:41
FILE "08 - ...and Time Begins.flac" WAVE
    INDEX 01 00:00:00
  TRACK 09 AUDIO
    TITLE "Await the Unending"
    PERFORMER "Decrepit Birth"
    INDEX 00 03:50:03
FILE "09 - Await the Unending.flac" WAVE
    INDEX 01 00:00:00
  TRACK 10 AUDIO
    TITLE "Essence of Creation"
    PERFORMER "Decrepit Birth"
    INDEX 00 05:17:74
FILE "10 - Essence of Creation.flac" WAVE
    INDEX 01 00:00:00
  TRACK 11 AUDIO
    TITLE "The Morpheus Oracle (Outro)"
    PERFORMER "Decrepit Birth"
    INDEX 00 06:32:30
FILE "11 - The Morpheus Oracle (Outro).flac" WAVE
    INDEX 01 00:00:00

```
</details>

Gives me this:

![Decrepit Birth - Diminishing Between Worlds (not working)](https://user-images.githubusercontent.com/59181811/71590447-d1658900-2b28-11ea-8db9-e050b309afb8.png)

As you can see, tracks lengths are incorrect.

Now, after I removed all `INDEX 00` lines and placed `FILE "XX - Track XX.flac` before `TRACK XX AUDIO`:

<details>
    <summary>working cue sheet</summary>

```
REM GENRE "Technical Brutal Death Metal"
REM DATE 2008
REM DISCID 8E0A830B
REM DISCNUMBER 1
REM DISCTOTAL 1
PERFORMER "Decrepit Birth"
TITLE "Diminishing Between Worlds"
FILE "01 - The Living Doorway.flac" WAVE
  TRACK 01 AUDIO
    TITLE "The Living Doorway"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "02 - Reflection of Emotions.flac" WAVE
  TRACK 02 AUDIO
    TITLE "Reflection of Emotions"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "03 - Diminishing Between Worlds.flac" WAVE
  TRACK 03 AUDIO
    TITLE "Diminishing Between Worlds"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
  TRACK 04 AUDIO
FILE "04 - Dimensions Intertwine.flac" WAVE
    TITLE "Dimensions Intertwine"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "05 - The Enigmatic Form.flac" WAVE
  TRACK 05 AUDIO
    TITLE "The Enigmatic Form"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "06 - A Gathering of Imaginations.flac" WAVE
  TRACK 06 AUDIO
    TITLE "A Gathering of Imaginations"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "07 - Through Alchemy Bound Eternal.flac" WAVE
  TRACK 07 AUDIO
    TITLE "Through Alchemy Bound Eternal"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "08 - ...and Time Begins.flac" WAVE
  TRACK 08 AUDIO
    TITLE "...and Time Begins"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "09 - Await the Unending.flac" WAVE
  TRACK 09 AUDIO
    TITLE "Await the Unending"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "10 - Essence of Creation.flac" WAVE
  TRACK 10 AUDIO
    TITLE "Essence of Creation"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
FILE "11 - The Morpheus Oracle (Outro).flac" WAVE
  TRACK 11 AUDIO
    TITLE "The Morpheus Oracle (Outro)"
    PERFORMER "Decrepit Birth"
    INDEX 01 00:00:00
```

</details>

![Decrepit Birth - Diminishing Between Worlds (working - edited)](https://user-images.githubusercontent.com/59181811/71590448-d1658900-2b28-11ea-8c7a-8aa5094627ac.png)

The tracks lengths are now correct.

Some albums also return no length at all for some tracks:

<details>
    <summary>cue sheet with tracks without length</summary>

```
REM GENRE "Metalcore"
REM DATE 2005
REM DISCID 980B2C0C
REM DISCNUMBER 1
REM DISCTOTAL 1
PERFORMER "August Burns Red"
TITLE "Thrill Seeker"
FILE "01 - Your Little Suburbia Is in Ruins.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Your Little Suburbia Is in Ruins"
    PERFORMER "August Burns Red"
    PREGAP 00:00:10
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Speech Impediment"
    PERFORMER "August Burns Red"
    INDEX 00 03:58:26
FILE "02 - Speech Impediment.flac" WAVE
    INDEX 01 00:00:00
FILE "03 - Endorphins.flac" WAVE
  TRACK 03 AUDIO
    TITLE "Endorphins"
    PERFORMER "August Burns Red"
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    TITLE "Too Late for Roses"
    PERFORMER "August Burns Red"
    INDEX 00 03:10:10
FILE "04 - Too Late for Roses.flac" WAVE
    INDEX 01 00:00:00
FILE "05 - Barbarian.flac" WAVE
  TRACK 05 AUDIO
    TITLE "Barbarian"
    PERFORMER "August Burns Red"
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    TITLE "The Reflective Property"
    PERFORMER "August Burns Red"
    INDEX 00 03:45:40
FILE "06 - The Reflective Property.flac" WAVE
    INDEX 01 00:00:00
FILE "07 - A Wish Full of Dreams.flac" WAVE
  TRACK 07 AUDIO
    TITLE "A Wish Full of Dreams"
    PERFORMER "August Burns Red"
    INDEX 01 00:00:00
  TRACK 08 AUDIO
    TITLE "Consumer"
    PERFORMER "August Burns Red"
    INDEX 00 02:58:22
FILE "08 - Consumer.flac" WAVE
    INDEX 01 00:00:00
FILE "09 - A Shot Below the Belt.flac" WAVE
  TRACK 09 AUDIO
    TITLE "A Shot Below the Belt"
    PERFORMER "August Burns Red"
    INDEX 01 00:00:00
FILE "10 - Eve of the End.flac" WAVE
  TRACK 10 AUDIO
    TITLE "Eve of the End"
    PERFORMER "August Burns Red"
    INDEX 01 00:00:00
  TRACK 11 AUDIO
    TITLE "The Seventh Trumpet"
    PERFORMER "August Burns Red"
    INDEX 00 03:09:23
FILE "11 - The Seventh Trumpet.flac" WAVE
    INDEX 01 00:00:00
```
</details>

![August Burns Red - Thrill Seeker - blanks](https://user-images.githubusercontent.com/59181811/71590446-d1658900-2b28-11ea-9497-0b7ef0590f56.png)

## Albums with image + .cue and a single track

When appending a single track album that comes with image + .cue, Cantata appends the track twice, once correctly and a second time as "Unknown":

<details>
    <summary>cue sheet | image + .cue | "Unknown"</summary>

```
REM GENRE "Technical Death Metal"
REM DATE 2016
REM DISCID 0207BB01
REM DISCNUMBER 1
REM DISCTOTAL 1
CATALOG 0822603138528
PERFORMER "Gorguts"
TITLE "Pleiades' Dust"
FILE "Gorguts - Pleiades' Dust.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Pleiades' Dust"
    PERFORMER "Gorguts"
    ISRC FR33T1638601
    INDEX 01 00:00:00
```

</details>

![Gorguts - Peiades' Dust (not working)](https://user-images.githubusercontent.com/59181811/71590452-d1fe1f80-2b28-11ea-9fc1-79a7741c9c6f.png)

## Albums with image + .cue or tracks +.cue and separate .mp3 bonus tracks

I have a few folders with albums in FLAC (either image + .cue or tracks + .cue) with additional bonus tracks in mp3 which are not part of the disc.

- When appending such an album with **tracks + .cue** to a playlist, Cantata appends the album twice  + the bonus tracks:

![HateSphere - To the Nines (doublon)](https://user-images.githubusercontent.com/59181811/71590453-d296b600-2b28-11ea-9480-5d37d74fc301.png)

- When appending such an album with **image + .cue**, Cantata appends the album but doesn't append the .mp3 bonus tracks 

## Drag'n'drop not working

Sometimes I'd like to drag'n'drop an album which isn't in my `mpd` database.

I cannot append any album with image + .cue, be it .flac, .ape, or .wv.

- When trying to drag'n'drop the .cue:

![Drag'n'drop - cue sheet - error](https://user-images.githubusercontent.com/59181811/71590450-d1fe1f80-2b28-11ea-9c82-68a227c95d54.png)

- When trying to drag'n'drop the .flac ; .ape or ; .wv:

![Drag'n'drop - APE - Unknown](https://user-images.githubusercontent.com/59181811/71590915-8ea4b080-2b2a-11ea-9f46-60cb5ccea39c.png)

No issue when appending the same album from the database:

![Drag'n'drop - APE from database](https://user-images.githubusercontent.com/59181811/71590916-8ea4b080-2b2a-11ea-9388-c27b1699ad7c.png)

I don't have any of these issues with `DeaDBeeF`, cue sheets are correctly parsed, I can drag'n'drop either .cue or single file with embedded cue sheet in tags. `mpv` also parse cue sheets just fine.

Any idea?

Thanks.

**Comment by CDrummond** [comment]
Cue files in the queue are parsed by MPD - so errors, I assume, would be in there.

As to "When appending a single track album that comes with image + .cue, Cantata appends the track twice" how are you adding this to the queue? From which view? Library or Folders?

**Comment by vtnpp** [comment]
> Cue files in the queue are parsed by MPD - so errors, I assume, would be in there.

Ok, so it would be an issue with mpd rather than Cantata?

> As to "When appending a single track album that comes with image + .cue, Cantata appends the track twice" how are you adding this to the queue? From which view? Library or Folders? If its from the Folders view, this does not associate cue+source file - so you need to add each separately.

From Library view. Here's another screenshot including the album details in Library view. As you can see, the first album is image + .cue but consists of multiple tracks. The second one is also image + .cue but is a single track album.

![Gorguts](https://user-images.githubusercontent.com/59181811/71594106-d3364900-2b36-11ea-9f6e-1d2f31d5f49e.png)

> Drag'n'drop of cue files also will not work, not supported.

What about images which have embedded cue sheet in tags?

If I drag'n'drop a folder with image + cue (embedded cue sheet in the image),  I only get the FLAC file displayed as "Unknown - Unknown". The FLAC file can still be played entirely in one go but cuesheet isn't parsed so the FLAC file isn't splitted in tracks.

**Comment by CDrummond** [comment]
To be honest, I have no time nor enthusiasm to look into this. The Cue sheet code has been there for years, and works in the simple 1 file + 1 cue sheet use case that I envisioned and is the only use case I've ever used it for. However, there have been changes for 2.4.0 that might resolve some of this, if it does not, then you'll have to look into this yourself.

Drag'n'drop was only ever implemented as a quick and simple use case. Cantata is primarily an MPD client, and other features are simple extras - and will never be fully featured.

Cantata also is now in a bug-fix only state, as I no longer use Cantata or MPD - having switched to logitech media server some 2 years ago.

So, all that said, I'm closing this as 'wontfix' - as I have no time to look into it.
