### ISSUE TITLE
Option to customize track display (in album tree and playlist)

### ISSUE THREAD

**Issue by ilohmar** [CDrummond/cantata#1565]
**Is your feature request related to a problem? Please describe.**
As described in #1177, originaldate (or its year part) is taken as track-related info (as it also seems to be intended in MPD), and we have the option to sort by and display the originaldate's year for albums as well.  Cantata displays the original year behind each track if it differs from the "standard" year.

For those of us that use automated tagging from MusicBrainz, that's unfortunate, because the year and the originaldate tag there always relate to *albums*.  So if the two differ, it is usually because of a reissue, and it's the same originaldate tag for all tracks of an album.  I then see the original year behind the album, but I see the same original year behind each of the individual tracks --- this is very noisy and I find it visually annoying.

**Describe the solution you'd like**
An option to either fully customize the track display (in both the album view and the playlist), or to at least disable the display of years for the individual tracks.

**Describe alternatives you've considered**
See #1177 again: the alternative would be to offer a different interpretation of the originaldate tag, which would break its use as a track-related date in compilations and the likes.

**Comment by CDrummond** [comment]
Sorry, have no time for this. Cantata is, and has been for a while, in a bug-fix only state. I no longer actively use Cantata nor MPD - switched to logitech media server years ago.
