### ISSUE TITLE
Multiple Artists Not Displayed

### ISSUE THREAD

**Issue by g4x86** [CDrummond/cantata#1566]
**Describe the bug**
Any music files in the FLAC format that contains multiple artist names in any type of tags only display the first artist name in Cantata.

**To Reproduce**
1. Add a FLAC music file to the Play Queue
2. Move the mouse pointer to the song in play and a floating window pops up showing the information tags of current song.
3. Right click the song and select "Edit Track Information", so that a dialogue pops up to let users edit the tag information.
4. Only the first artist name is shown for all the tagging fields that contain multiple artist names.

**Expected behavior**
All artist names should be displayed and editable.

**Screenshots**

**Version Info**
 - OS: Red hat Enterprise Linux 8.1
 - Cantata Version:2.4.0 (checked out from GitHub in November 2019)
 - MPD Version: 0.21.18-1.el8
 - CMake options (other than default):

**Additional context**

I have a big collection of music files in the FLAC format and many of them are tagged with multiple artists / composers / album artists by using the feeature of multiple entries of the same tag provided by the VORBIS_COMMENT block of FLAC. An example, the song Do-Re-Mi from the soundtrack of the movie The Sound of Music has the following information:

TITLE: Do-Re-Mi
ARTIST: Julie Andrews, Charmian Carr, Heather Menzies, Nicholas Hammond, Duane Chase, Angela Cartwright, Debbie Turner, Kym Karath
ALBUMARTIST: Richard Rodgers, Oscar Hammerstein
ALBUM: The Sound of Music (50th Anniversary Edition)
DATE: 2005
TRACKNUMBER: 08
TRACKTOTAL: 27
DISCNUMBER: 01
DISCTOTAL: 01
GENRE: Soundtrack
COMPOSER: Richard Rodgers, Oscar Hammerstein
PERFORMER: Julie Andrews
COPYRIGHT: Rodgers & Hammerstein Organization Production
CONTACT: https://www.rnh.com/

In the VORBIS_COMMENT block of this song, there are 8 ARTIST entries, 2 ALBUMARTIST entries, and 2 COMPOSER entries, each of which contains the name of a single artist. However, cantata (the version of 2.4.0 checked out from GitHub in November 2019) only displays the first artist, composer and album artist, as shown in both the Play Queue and the dialogue of Edit Track Information.

In the meantime, ncmpcpp (a console client of MPD) and Flacbox (an iOS app for FLAC music) have no problem in displaying all multiple artists. Moreover, some popular music tagging software programs, which can process FLAC format, are able to handle this, including MusicBrainz Picard, Kid3, and EasyTag.

In general, numerous music artworks are composed, performed and copyrighted by multiple artists (e.g. pop songs, musicals, movie soundtracks, and stage play recordings) and can be categorized into multiple genres (e.g. classic rock and hard rock). Therefore, the feature of multiple entries for the same tag offerred by the VORBIS_COMMENT block naturally and perfectly meets the realistic requirement for maintaining the original tagging information of music artworks. Such a solution contrasts with the awkward situation of the ID3v2 tagging method where the names of multiple artists have to be squeezed into one tag field and must be separated by artifical and random separation character.

Hope this problem can be fixed soon in the future release.

**Comment by CDrummond** [comment]
Cantata's tag editor is only basic, and only supports multiple entries for the 'Genre' field. As stated in the main gthub page - Cantata is in a bug-fix only state, and I'm not adding new features. Pull requests welcome.
