### ISSUE TITLE
Setting CD/DVD speed

### ISSUE THREAD

**Issue by PacoPemo** [CDrummond/cantata#1569]
**NOTE** Cantata is now in a bug-fix only state. Therefore feature requests will usuaully be rejected. Pull requests, however, will still be accepted - so, if you desire a new feature this would be the route required.

I know, but I'll try anyway.

I've created a Custom Action using eject -x # to change cd speed, and it would be nice to have Context Menu also in Devices, so you can silent CD while playing.
Thanks
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CDrummond** [comment]
Not something I'd ever have a need for - so not something I'mm willing to spend time on. As stated I await your pull request.
