### ISSUE TITLE
Can't find lrelease on Fedora 31.

### ISSUE THREAD

**Issue by oyvinds** [CDrummond/cantata#1570]
It's there as /usr/lib64/qt5/bin/lrelease on Fedora (provided by the "qt5-linguist" package).

Since I'm lazy, I did

ln -s /usr/lib64/qt5/bin/lrelease /usr/bin/lrelease

and cmake in Cantata finds it. Perhaps Cantata could look for it in /usr/lib64/qt5/bin/lrelease ?

Anyway, thank you for a new release. I'll probably update 
https://linuxreviews.org/Cantata
later today or tomorrow.

**Comment by CDrummond** [comment]
Sounds like a Fedora issue. Just place lrelease in your path.

**Comment by CDrummond** [comment]
I've updated the CMake code (for 2.4.1) to look in /usr/lib64/qt5/bin/ for lrelease. THis works on my Fedora install.

**Comment by cornelisbb** [comment]
This solution does not work for 32bits. In openSUSE we long carried a patch that looked for lrelease-qt5 instead of lrelease. That is probably an openSUSE thing, but the additional path works on 64bits openSUSE, but not on 32bits. The latter is still supported on Tumbleweed.
