### ISSUE TITLE
Unnecessary colour clamping

### ISSUE THREAD

**Issue by Tar-Dingens** [CDrummond/cantata#1573]
Cantata currently restricts the colour of monochrome icons and of the main toolbar text. Therefore Cantata can look out of place compared to other applications. I removed the colour clamping from icons and did not find any bugs that would make it necessary to restrict the colour values. Depending on the used colour scheme deviating from the default text colour might also make the toolbar text harder to read.

Upstream version:
<img width="978" alt="withclamping" src="https://user-images.githubusercontent.com/8679753/74783801-bd2b4600-52a6-11ea-9e9c-1128cb9f58a3.png">

Without colour clamping:
<img width="978" alt="withoutclamping" src="https://user-images.githubusercontent.com/8679753/74783811-c2889080-52a6-11ea-92ee-3ae7984f6d8e.png">

[A patch I created for my own usage](https://gist.github.com/Tar-Dingens/bab09c6e0fa3fa27ce4eb6b20edf5a86)

**Comment by CDrummond** [comment]
The colours are that way on purpose.
