### ISSUE TITLE
Saved lyrics file doesn't save to the intended music folder 

### ISSUE THREAD

**Issue by farahnur42** [CDrummond/cantata#1576]
After enabling "Save downloaded lyrics to music folder" it doesn't save to the intended music folder, instead opting for the default ~/.cache/cantata/lyrics

**To Reproduce**
1. Go to settings, enable "Save downloaded lyrics to music folder" 
2. Play any song 
3. 

**Expected behavior**
The lyrics to be stored as "filename" + .txt/.lyrics in the folder where the file is 

**Version Info**
 - OS: OpenSUSE Tumbleweed 20200228
 - Cantata Version: ~~999.git.20200222.8ac641cb0-45.4 [Using an user repo here that gets updated more often]~~ 2.4.1-1.1 [Problem still persists and is reproducible on my end, even after removing all cantata-related files and reinstalling]
 - MPD Version: 0.21.20-42.1
 - CMake options (other than default): N/A

**Additional context**
At first I thought it was a permission issue, but it doesn't seem to be fixed even after adding write  permissions for all, for the folder.

**Comment by CDrummond** [comment]
Ah! Oops! The UI is setting the wrong  config item. If you edit `~/.config/cantata/cantata.conf` and add:
```
storeLyricsInMpdDir=true
```
into the `[General]` section - do the lyrics then get saved correctly?

**Comment by CDrummond** [comment]
...or try the git/master version...

**Comment by farahnur42** [comment]
They're still not getting saved correctly, even after a full configuration reset and then enabling the right config item. And trying to build the git version is showing me dependency errors, ffmpeg, mpg123 and udev errors no less [and I have all of the dependencies installed as lined out in the main README].

**Comment by farahnur42** [comment]
I should note that I'm using the Basic setup and not the Standard one, could that have anything to do with it?

**Comment by CDrummond** [comment]
I have just tried, git/master with Basic setup - and lyrics are saved in the MPD music folder. So, working as expected.

git/master compiles just fine in Fedora 31.

Closing, as feature is now working.
