### ISSUE TITLE
Volume slider not working

### ISSUE THREAD

**Issue by PersephoneXaris** [CDrummond/cantata#1577]
Fresh Install of version 2.40. Fantastic program and very enjoyable to use. I just wanted to ask whether I am doing something wrong. I can't seem to get the volume icon to respond. Moreover, on my KDE connect (android) app I can move the slider, but not control the volume. Strange or?
I am using Kubuntu Linux 18.04 

Thanks in advance!

**Comment by CDrummond** [comment]
Sorry, I have no time to debug MPD installations. I have tried, and Cantata's volume control is working.

As stated in the main page - Cantata is in a bug-fix only state.

**Comment by PersephoneXaris** [comment]
Okay, thanks Craig for your speedy answer. I'll look into my mpd config. I
just thought it might have been something obvious. Thanks again. Have a
nice weekend. Best regards from Germany.

**Comment by xTpx** [comment]
In your mpd.conf
`````
audio_output {
        mixer_type "software"
}
`````
