### ISSUE TITLE
Enhancement: Horizontal lines between discs of the same album

### ISSUE THREAD

**Issue by deriv** [CDrummond/cantata#1579]
Should files of same the album, consisting of many discs, whether residing in separate folders, CD1, CD2, CD3 ... or all in same directory, Cantata will display all the songs, even while id3tags and disc # have the proper data, in the same segment, not divided into own segments with horizontal line and name of the of the album and year in question, like it would should the album name have differ.

My question and request for enhancement is, could this please be implemented?

Example A: 
If id3tag has different album, all files have disc 1:
```
Album 2020 CD 1____
01. First song
02. Second song

Album 2020 CD 2____
01. First song, long version
02. Second song, long version
```

Example B:
If id3tag has same album, all files have disc 1 and disc 2 correctly like in example A

```
Album 2020 ________
01. First song
02. Second song
01. First song, long version
02. Second song, long version

```

**Comment by CDrummond** [comment]
Sorry, but as stated on the main github page (and should have been when you created this issue) Cantata is in a bug-fix only state. I no longer actively use Cantata nor MPD - having switch to logitech media server about 3 years ago. (And I've just implemented this feature in my Material Skin for LMS)

So, closing as wont-fix - as I have no time, nor need, for this. However - I will accept a pull request that implements this.
