### ISSUE TITLE
Bitrate filter search

### ISSUE THREAD

**Issue by jtbgroup** [CDrummond/cantata#1587]
Hi!

I tried a pull request for a new feature, but as i'm not a C++ programmer, it seems a little bit too complicated for me to request this feature this way.

I wondered if it would be possible to have an additional search filter in the criterias. I used to use amarok before and this feature was very nice for me to clean some old files having a too low bitrate. 

Thansk in advance!
Gautier

**Comment by CDrummond** [comment]
As stated in the main README.md, and the template when you created this issue, I am not adding new features.
