### ISSUE TITLE
No sound output on local workstation

### ISSUE THREAD

**Issue by joshuasorkin** [CDrummond/cantata#1588]
I'm running Cantata 2.3.2 on Windows 10.  I downloaded and installed it through the Chocolatey package manager.  I am using it to control an instance of MPD that's running on a FreeBSD server, so that MPD can broadcast the stream at "myUrl.com:[port number]".

At first when I was using it, I could hear the stream's sound output on my workstation.  Then at some point I stopped being able to hear the stream, and the only way I can now hear that stream is to open the MPD-broadcasted stream.

I can't find anything in the settings about managing audio devices for Cantata's local output.  What could be causing this?

**Comment by CDrummond** [comment]
Sorry, that is an old build - and I'm no longer creating Windows builds.
