### ISSUE TITLE
Play Command isn't Executed

### ISSUE THREAD

**Issue by mbrandis** [CDrummond/cantata#1589]
A very strange phenomenon: 

Connecting Cantata to a Raspberry Pi 2 with Raspbian 10 and mpd 0.21.5-3. Connection works and the library/playlists/etc. are visible. As soon as I add a song to the playlist and play it, nothing happens and then after a while Cantata disconnects. I can connect again, but the same happens. No error messages in the mpd log.

Connecting via gmpc works and also choosing and playing music, also with ncmpc.

On a Raspberry Pi 4 with Raspbian and mpd (same versions as above) Cantata works flawlessly.

Any idea what the problem could be?

TIA,
Mark

**Comment by CDrummond** [comment]
Sorry, but my time for Cantata issues is very limited - as I no longer actively use it. I have tested, and as expected play is working. Some issue with your system.
