### ISSUE TITLE
Occasional garbled UTF-8 tags in side pane

### ISSUE THREAD

**Issue by zoqaeski** [CDrummond/cantata#1593]
**Describe the bug**
Some of the artists and tracks in my library display non-ASCII characters with a "�" despite being properly encoded with UTF-8 in the tags. MPD displays the tags correctly, as do other applications with access to the same files / music library. The tags are also correctly displayed in the playlist and main controls.

The tracks with malformed tags cannot be added to the playlist by clicking the "+" or "▶" buttons that hover on the side.

**Expected behavior**
The artist name and track titles should be correctly displayed in the sidebar.

**Screenshots**

![cantata_utf8_display_issue](https://user-images.githubusercontent.com/172912/80776295-6777f180-8ba5-11ea-800d-b75b3700b545.png)

**Version Info**
 - OS: Linux
 - Cantata Version: 2.4.1
 - MPD Version: 0.21.22

**Comment by CDrummond** [comment]
Can you please provide an example file with these corrupt tags? I have files with UTF-8 and have never seen this. Use ffmpeg to create a dummy silent file, and then use a tagger to copy the tags over, and confirm via Cantata that this dummy file also shows the tags corrupted, and the post a link to the file here. Thanks.

**Comment by zoqaeski** [comment]
This is going to turn out to be a [_Heisenbug_](https://en.wikipedia.org/wiki/Heisenbug). I did what you suggested: created some dummy files with the tags copied across via `ffmpeg`, and then made a new MPD instance locked to Cantata (so as to not interfere with my primary MPD instance). 

The tags display properly in both the dummy instance and in my main one :open_mouth: :confused:

**Comment by CDrummond** [comment]
Hmmm.... Well sorry, but I have no time to look into this. I stopped actively using MPD and Cantata about 3 years ago (switched to LMS)

**Comment by trmdi** [comment]
@CDrummond
Just tried LMS with the squeezelite client, I still can't understand why you like it, maybe because you have Squeezebox? Just curious.

**Comment by CDrummond** [comment]
@trmdi Server & client are different. I can play to Squeezeboxes, Airplay, DLNA, Chromecast, piCorePlayer (squeezelite) - all (apart from Chromecast) in sync. LMS has an in-built HTTP server which I use to serve my Material-skin - so I have the same UI on phone, desktop, etc.

**Comment by uhle** [comment]
It looks like an ISO LATIN-1 encoded string treated as being UTF-8 encoded. I am not quite sure whether copying ID3 tags using ffmpeg will retain the original encoding of the ID3 tags. You may check the encoding using an application like [Kid3](https://kid3.kde.org/) for instance.

**Comment by zoqaeski** [comment]
> It looks like an ISO LATIN-1 encoded string treated as being UTF-8 encoded. I am not quite sure whether copying ID3 tags using ffmpeg will retain the original encoding of the ID3 tags. You may check the encoding using an application like [Kid3](https://kid3.kde.org/) for instance.

The tags are correctly encoded with UTF-8 — I used MusicBrainz to retag them all a few months ago. No other application displays the tags incorrectly, not even other MPD clients like `ncmpcpp`.

**Comment by CDrummond** [comment]
As stated before, without example files there is not much I can do. I don't doubt there is an issue - hence leaving this open. But without a way to recreate the issue, I'm not sure what to do. Its _possible_ this is a Qt issue (unlikely, but possible), what is your Qt version?

I have UTF-8 tags in my files, and they all show OK - hence not being able to recreate this issue.

**Comment by afromanDAN** [comment]
I'm running into this issue now after having to reinstall arch. It was fine before on the old install and I was up to date on everything.

**Comment by CDrummond** [comment]
@afromanDAN So, what has changed between installs? Cantata versions? Qt versions? Locale? If Cantata has *not* changed version, then it points to somewhere else. Which Qt version are you on now, and what version before?

**Comment by afromanDAN** [comment]
My locale on both installs is en_US.UTF-8 and I am on Qt 5.15 on both too. The version of Cantata is the latest stable on both.

**Comment by zoqaeski** [comment]
I figured out how to make the issue go away: ensure your MPD instance auto-updates, and then check "Server detects changes automatically" option in the Preferences. When both Cantata and MPD try to update the database at the same time, something messes up Cantata's own copy.

**Comment by CDrummond** [comment]
But Cantata only asks MPD to udpate the DB, and then gets the track listing from MPD. If this does not work, then it sounds like an MPD issue.

**Comment by afromanDAN** [comment]
Yeah, that did not fix it. Must be an mpd issue.

**Comment by zoqaeski** [comment]
Perhaps there are multiple issues overlapping here, as that fixed the issue for me? As you're running Arch, @afromanDAN , I assume you'd also be using the latest version of MPD as well? Are the tracks tagged correctly in another MPD client, like `ncmpcpp`?

**Comment by afromanDAN** [comment]
> Perhaps there are multiple issues overlapping here, as that fixed the issue for me? As you're running Arch, @afromanDAN , I assume you'd also be using the latest version of MPD as well? Are the tracks tagged correctly in another MPD client, like `ncmpcpp`?

Decided to try again today and yes I am having issues in ncmpcpp aswell. 

Also, How do you tell if your tags are utf-8? I do not see any option in puddletag or Kid3.

**Comment by CDrummond** [comment]
So, not a Cantata specific issue then.
