### ISSUE TITLE
how to export my settings to another machine (playlists and streams)

### ISSUE THREAD

**Issue by verajosemanuel** [CDrummond/cantata#1595]
I want to move all my cantata streams and favourites to a new machine
is there any way to do so?

**Comment by CDrummond** [comment]
Streams are stored with in an MPD playlist named `[Radio Streams].m3u` - just copy that file.

**Comment by verajosemanuel** [comment]
I could not find such file. Any suggested location?

**Comment by CDrummond** [comment]
It all depends on your MPD setup. If you are using Cantata's 'basic' user-MPD mode, then it'll be in `~/.local/share/cantata/mpd/playlists/[Radio Streams].m3u` Otherwise depends on your MPD settings. Might be `/var/lib/mpd/playlists/[Radio Streams].m3u`

**Comment by verajosemanuel** [comment]
No such directories in both cases, and commands as "locate" or "find" are unable to get any .m3u file in my system

**Comment by CDrummond** [comment]
Sorry, but not much I can do. If your MPD is on another machine, so will the m3u file.

**Comment by verajosemanuel** [comment]
Found as [Radio Streams].m3u8
