### ISSUE TITLE
Unable to edit track information without forced rename dialog

### ISSUE THREAD

**Issue by ackstorm23** [CDrummond/cantata#1596]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
When editing track information,  I am forced to open the rename dialog or my changes are not saved.  If I click cancel, changes are not saved.

Worse yet, about half the time I click cancel within the file rename dialog, the changes are not saved either.

**To Reproduce**
1. Go to 'Library'
2. Right-Click on any items in the list
3. Select 'Edit Track Information'
4. Edit tags to your liking (I chose to edit Genre)
5. Click 'Save'
6. You should be prompted with a new dialog 'Would you also like to rename your song files, so as to match your tags?'
7. Click Cancel
8. Observe tag change was not saved

**Expected behavior**
When prompted with 'Would you also like to rename your song files, so as to match your tags?' you should be able to choose 'Cancel' and still have your tags saved.

OR

There would be a way to avoid the 'Would you also like to rename your song files, so as to match your tags?' from coming up at all. 

**Version Info**
 - OS: Manjaro Linux
 - Cantata Version: [2.4.2]
 - MPD Version: [0.21.11]
 - CMake options (other than default): Default

**Additional context**
I am only trying to save tag changes.  I am not given an option to avoid file rename dialog, and the only choices given for file rename dialog are 'Yes' or 'Cancel'.

**Comment by CDrummond** [comment]
Select 'Cancel'
