### ISSUE TITLE
Crush on Selecting Interface

### ISSUE THREAD

**Issue by BobRawr101** [CDrummond/cantata#1598]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
After selecting a theme (forgot the exact one, can no longer check), the overflow menu is now hidden, selecting interface after clicking 'settings' (by randomly clicking) will cause Cantata to crash. 

**To Reproduce**
1. Select a certain theme
2. Go to settings from overflow menu
3. Click interface

**Expected behavior**
You find the interface menu to select themes / change UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/6691735/80900454-2d0e7180-8cd7-11ea-8f5a-1b2362da240b.png)

**Version Info**
 - OS: Linux

**Additional context**
**Stack Trace**
```
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /usr/lib/libc.so.6 : ()+0x3bd70
  /usr/lib/libQt5Widgets.so.5 : ()+0x150910
  /usr/lib/qt/plugins/styles/libbb10styleplugin.so : ()+0x82df
  cantata : ProxyStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const+0x4b
  /usr/lib/libQt5Widgets.so.5 : QCommonStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const+0x1430
  /usr/lib/qt/plugins/styles/libbb10styleplugin.so : ()+0x82df
  cantata : ProxyStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const+0x4b
  /usr/lib/libQt5Widgets.so.5 : QCommonStyle::drawControl(QStyle::ControlElement, QStyleOption const*, QPainter*, QWidget const*) const+0x54dc
  /usr/lib/libQt5Widgets.so.5 : QPixmapStyle::drawControl(QStyle::ControlElement, QStyleOption const*, QPainter*, QWidget const*) const+0x252
  /usr/lib/qt/plugins/styles/libbb10styleplugin.so : ()+0x80ed
  /usr/lib/libQt5Widgets.so.5 : QStyledItemDelegate::paint(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const+0x210
  cantata : BasicItemDelegate::paint(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const+0x33a
  /usr/lib/libQt5Widgets.so.5 : QListView::paintEvent(QPaintEvent*)+0x4c4
  /usr/lib/libQt5Widgets.so.5 : QWidget::event(QEvent*)+0x27e
  /usr/lib/libQt5Widgets.so.5 : QFrame::event(QEvent*)+0x1f
```

**Comment by CDrummond** [comment]
As you can see the trace does not end in a Cantata function. So, probably a Qt5 issues. Anyhow, as you can see by your screenshots the BB10 styles are broken - don't use them.
