### ISSUE TITLE
Cantata can not add stream with hash at the end

### ISSUE THREAD

**Issue by AndriiZ** [CDrummond/cantata#1601]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**

MPD 0.22 added option to provide charset for internet radio for proper tags decoding. This looks like 
http://eradio.cc.colocall.com:8000/eradio#charset=cp1251
However, Cantata can not add such streams to queue. Ympd/mpc can add 
**To Reproduce**
1. Add http://eradio.cc.colocall.com:8000/eradio#charset=cp1251 to playlist using mpc/ympd
2. Save playlis
3. Open playlist in Cantata
4. Click on stream

**Expected behavior**
Stream not adding

**Screenshots**
![зображення](https://user-images.githubusercontent.com/820269/81497750-1795da80-92c9-11ea-894e-0105d4d43264.png)

**Version Info**
 - OS: Windows 10
 - Cantata Version: 2.3.2
 - MPD Version: 0.22

**Comment by CDrummond** [comment]
This is fixed in Cantata 2.4.x - however, this is not released for Windows as I'm no longer creating builds.
