### ISSUE TITLE
Is cantata supported in Windows?

### ISSUE THREAD

**Issue by xiaohaoxiang** [CDrummond/cantata#1603]
**NOTE** Cantata is now in a bug-fix only state. Therefore feature requests will usually be rejected. Pull requests, however, will still be accepted - so, if you desire a new feature this would be the route required.
---
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CDrummond** [comment]
How about you read the main page.
