### ISSUE TITLE
Lyrics fetch goobered up, Cantata 2.4.0

### ISSUE THREAD

**Issue by Durhammer3111** [CDrummond/cantata#1604]
**Describe the bug**
Got this weird output when Cantata was switching between streams on a radio station:

Drive@@@@@mode=updinfo,Dermot Kennedy - Glory@@@@@mode=updinfo,R.E.M. - Drive

And of course, didn't get any lyrics. 

ALSO, whilst listening to the Dixie Chicks' "Gaslighter" song, the lyrics come up embedded in unformatted HTML or markdown characters.

**To Reproduce**
1. Not sure how it can be reproduced! I'm streaming an internet radio station (WCLY).
2. I leave the "Info" window open and the above stuff just happens!

**Expected behavior**

Get the lyrics and display them nicely!

**Screenshots**

**Version Info**
 - OS: Linux Mint 19.3, Cinnamon (4.4.8), kernel 5.3.0-53-generic
 - Cantata Version: 2.4.0
 - MPD Version: 0.20.18
 - CMake options (other than default): N/A

**Additional context**
Also wondering if newer lyrics sources would help? MusicBee gets good results with just LyricWiki, ChartLyrics.com, and LoloLyrics. The last one seems to the the only one Cantata has available.

**Comment by CDrummond** [comment]
What lyrics provider were you using?

**Comment by CDrummond** [comment]
Where is `Drive@@@@@mode=updinfo,Dermot Kennedy - Glory@@@@@mode=updinfo,R.E.M. - Drive` shown? Is that what is shown for the lyrics?

**Comment by Durhammer3111** [comment]
Probably too many, but what do I know? Here's the list of selected:

lyrics.wikia.com

lololyrics.com

lyricsreg.com

lyricsmania.com

azlyrics.com

songlyrics.com

elyrics.net

lyricsdownload.com

lyrics.com

directlyrics.com

loudson.gs

teksty.org

===

I have no idea which ones should work better than others. As I commented 
in the opening post, MusicBee seems to get by splendidly with just those 
three. I'd probably do better with fewer in the selected list, but 
again, I don't know which are the best. At least lololyrics seems to be 
one to keep, as it's the second in MusicBee's search list.

Thanks for all you do to keep this wonderful piece of software going! I 
only mentioned MB because I spent a lot of time getting it running 
thinking it was so great and such but under Wine, it's an insane 
resource hog. Plus, I hadn't really even done anything much with the 
Cantata Info window, which I just hadn't configured to pull the neat 
stuff about the songs and artists (but again, MB has a nice, short, but 
very effective list of art sources to search from that I wish Cantata 
had -- sigh).

**Comment by Durhammer3111** [comment]
Ah, sorry I didn't note that originally. Looking back at the Info 
window, it seems to have occupied the TITLE real estate. At least it was 
at the top, and with a much larger font than the lyrics would have.

The radio streaming service was switching from Dermot Kennedy's "Glory" 
song to R.E.M.'s "Drive" at the time of the crime. Maybe some string 
overwrote part of the search? Wish I had taken a screen shot at the 
time, and wish I knew how to find out just which lyrics provider was 
queried last.

Thanks, Craig!

**Comment by Durhammer3111** [comment]
Ha! Just managed to capture the other reported issue, with specific 
song's lyrics ("Gaslighter" by Dixie Chicks). Here's what shows up:

<br/><p class='verse'>Gaslighter, denier<br/>Doin' 
anything to get your ass farther<br/>Gaslighter, big timer</p><p 
class='verse'>Repeating all of the mistakes of your father</p><p 
class='verse'>We moved to California and we followed your dreams<br/>I 
believed in the promises you made to me<br/>Swore that night 'til death 
do us part<br/>But you lie-lie-lie-lie-lied<br/>Hollywood welcomed you 
with open doors<br/>No matter what they gave you, you still wanted 
more<br/>Acting all above it when our friends divorced<br/>What a 
lie-lie-lie-lie-lie<br/>You're such a—</p><br/><br/><div 
class="driver-related"><br/><h4>Related</h4><br/><div 
class="related-container"><br/><ul><br/><li><br/><div 
class="bt-container"><br/><div id='div-gpt-ad-strnative' data-ad='strnative'

**Comment by Durhammer3111** [comment]
Ach! NOW, for some reason, Cantata isn't pulling ANYTHING -- no artist, 
album, or lyrics. Just a blank screen with the headers, that's all. I'll 
do a restart but really shouldn't have to do that.

BTW, for the record, I was running 2.2.0 until yesterday when i got 
interested in what might be new and was able to install 2.4.0 as a 
package install. That being said, I really hadn't tried fiddling with 
lyrics and art prior to then....

**Comment by Durhammer3111** [comment]
So sorry to be harping on MusicBee, but just noted an instance where 
Cantata gets NO lyrics but MB does: "The Needle and the Damage Done" by 
Neil Young. That should be easy to find! (Obviously not in lololyrics, 
though!)

**Comment by CDrummond** [comment]
I meant which service was returning incorrect lyrics. Cantata will stop at the first one. You can either use Cantata's logging or only enable 1 lyrics provider until you find the bad one.

For the logging, start Cantata from a commandline `cantata --debug network-access`. When lyrics are fetched you should see something like:
```
2020-05-23 07:15:33 - NetworkAccessManager get "https://lyrics.wikia.com/api.php?artist=ABBA&song=Mamma Mia&func=getSong&fmt=xml" true
2020-05-23 07:15:33 - NetworkJob NetworkJob 0x314fe20 0x2e32d60
2020-05-23 07:15:33 - NetworkJob jobFinished 0x314fe20 0x2e32d60
2020-05-23 07:15:33 - NetworkJob jobFinished "https://lyrics.wikia.com/api.php?artist=ABBA&song=Mamma Mia&func=getSong&fmt=xml" redirected to "https://lyrics.fandom.com/api.php?artist=ABBA&song=Mamma Mia&func=getSong&fmt=xml"
2020-05-23 07:15:33 - NetworkJob cancelJob 0x314fe20 0x2e32d60
2020-05-23 07:15:34 - NetworkJob handleReadyRead 0x314fe20 0x7f8924043560
2020-05-23 07:15:34 - NetworkJob jobFinished 0x314fe20 0x7f8924043560
2020-05-23 07:15:34 - NetworkJob jobFinished "https://lyrics.fandom.com/api.php?artist=ABBA&song=Mamma Mia&func=getSong&fmt=xml" QNetworkReply::NoError "OK"
2020-05-23 07:15:34 - NetworkAccessManager get "http://lyrics.wikia.com/api.php?action=query&prop=revisions&rvprop=content&format=xml&titles=ABBA%3AMamma_Mia" true
2020-05-23 07:15:34 - NetworkJob NetworkJob 0x314e320 0x3145200
2020-05-23 07:15:34 - NetworkJob ~NetworkJob 0x314fe20 0x7f8924043560
2020-05-23 07:15:34 - NetworkJob cancelJob 0x314fe20 0x7f8924043560
2020-05-23 07:15:34 - NetworkJob jobFinished 0x314e320 0x3145200
2020-05-23 07:15:34 - NetworkJob jobFinished "http://lyrics.wikia.com/api.php?action=query&prop=revisions&rvprop=content&format=xml&titles=ABBA%3AMamma_Mia" redirected to "https://lyrics.fandom.com/api.php?action=query&prop=revisions&rvprop=content&format=xml&titles=ABBA%3AMamma_Mia"
2020-05-23 07:15:34 - NetworkJob cancelJob 0x314e320 0x3145200
2020-05-23 07:15:34 - NetworkJob handleReadyRead 0x314e320 0x1fb9cb0
2020-05-23 07:15:34 - NetworkJob jobFinished 0x314e320 0x1fb9cb0
2020-05-23 07:15:34 - NetworkJob jobFinished "https://lyrics.fandom.com/api.php?action=query&prop=revisions&rvprop=content&format=xml&titles=ABBA%3AMamma_Mia" QNetworkReply::NoError "OK"
```
Here `lyrics.wikia.com` is the provider used, but a redirect was made to `lyrics.fandom.com`

You will need to delete any cached lyrics first. Either `~/.cache/cantata/lyrics` or in the same file is the music track (if you have enabled `Save downloaded lyrics into music folder`

------------------------

MusicBee is probably using a different lyrics provider, so finds more lyrics. I will not be adding more providers, as I do not have time for this. However, you can always submit a pull request.

**Comment by CDrummond** [comment]
I've added chartlyrics to list of providers - it was easy enough. LyricWiki seems to be `https://lyrics.fandom.com` which `lyrics.wikia.com` redirects to anyway.

**Comment by Durhammer3111** [comment]
Found one issue with Tyler Childers' "House on Fire" -- kinda like the 
issue with the Dixie Chix song. Lyrics display shows:

<br/><br/><div 
class="driver-related"><br/><h4>Related</h4><br/><div 
class="related-container"><br/><ul><br/><li><br/><div 
class="bt-container"><br/><div id='div-gpt-ad-strnative' data-ad='strnative'

Log shows only:

2020-05-23 10:06:38 - NetworkAccessManager get 
"http://www.musicbrainz.org/ws/2/artist/?query=artist:Tyler Childers" 
true 2020-05-23 10:06:38 - NetworkJob NetworkJob 0x563b623553d0 
0x563b610b6530 2020-05-23 10:06:39 - NetworkJob handleReadyRead 
0x563b623553d0 0x563b610b6530 2020-05-23 10:06:39 - NetworkJob 
jobFinished 0x563b623553d0 0x563b610b6530 2020-05-23 10:06:39 - 
NetworkJob jobFinished 
"http://www.musicbrainz.org/ws/2/artist/?query=artist:Tyler Childers" 
redirected to "http://musicbrainz.org/ws/2/artist/?query=artist:Tyler 
Childers" 2020-05-23 10:06:39 - NetworkJob cancelJob 0x563b623553d0 
0x563b610b6530 2020-05-23 10:06:39 - NetworkJob handleReadyRead 
0x563b623553d0 0x563b60dfb360 2020-05-23 10:06:39 - NetworkJob 
jobFinished 0x563b623553d0 0x563b60dfb360 2020-05-23 10:06:39 - 
NetworkJob jobFinished 
"http://musicbrainz.org/ws/2/artist/?query=artist:Tyler Childers" 
QNetworkReply::NetworkError(NoError) "OK" 2020-05-23 10:06:39 - 
NetworkAccessManager get 
"http://webservice.fanart.tv/v3/music/9947e874-ddd0-4e1a-b0d4-a76f6532fe45?api_key=ee86404cb429fa27ac32a1a3c117b006" 
true 2020-05-23 10:06:39 - NetworkJob NetworkJob 0x563b6297e8d0 
0x7fa5f0187700 2020-05-23 10:06:39 - NetworkJob ~NetworkJob 
0x563b623553d0 0x563b60dfb360 2020-05-23 10:06:39 - NetworkJob cancelJob 
0x563b623553d0 0x563b60dfb360 2020-05-23 10:06:39 - NetworkJob 
handleReadyRead 0x563b6297e8d0 0x7fa5f0187700 2020-05-23 10:06:39 - 
NetworkJob jobFinished 0x563b6297e8d0 0x7fa5f0187700 2020-05-23 10:06:39 
- NetworkJob jobFinished 
"http://webservice.fanart.tv/v3/music/9947e874-ddd0-4e1a-b0d4-a76f6532fe45?api_key=ee86404cb429fa27ac32a1a3c117b006" 
QNetworkReply::NetworkError(ContentNotFoundError) "Error transferring 
http://webservice.fanart.tv/v3/music/9947e874-ddd0-4e1a-b0d4-a76f6532fe45?api_key=ee86404cb429fa27ac32a1a3c117b006 
- server replied: Not Found" 2020-05-23 10:06:39 - NetworkJob 
~NetworkJob 0x563b6297e8d0 0x7fa5f0187700 2020-05-23 10:06:39 - 
NetworkJob cancelJob 0x563b6297e8d0 0x7fa5f0187700

**Comment by Durhammer3111** [comment]
Way cool, thanks! I've got a package install -- is there any way to 
incorporate this into that, or do I just have to wait until 2.4.2 (or 
.3?) is eventually packaged up?

And yes, I noticed that about LiricWiki at some point. Looks like most 
of the successes are with that one, azlyrics, and lyricsdb. Don't really 
think I've seen any other successes. Paring the list down should help in 
some way, I know.

I do see that the station I listen to plays a lot of live recorded stuff 
(much of it at a local studio) and that's in the name, so no lyrics are 
fetched (MB is no different in that respect). I was also dismayed that 
Cantata did not find any art for "Arcadian Driftwood" by The Band. MB 
did, but I noticed it was some bogus random band picture. Looked at the 
artist info and it was just "Band" -- DUH! So MB just serves up some 
pretty generic band picture from FanArt. Pretty, fills up a blank space, 
but totally bogus. Yours is more honest!

I was mildly surprised that neither music player found lyrics to Steely 
Dan's "Bodhisatva" (it's really obscure, but then again so is stuff by 
Primus, which did get found) until I did a Google search and found out 
the title was misspelled. So we suffer from stupid human errors when the 
stations (?) encode track info. Lesson learned!

Thanks for all you do, sir!

-Jim-

**Comment by CDrummond** [comment]
Please, concentrate on the issue of garbage lyrics - not lyrics not found (that is a different, but related, issue).

As to the messed up lyrics - as stated you need to:

1. **Delete** the cached lyrics for a track - stored in either Music folder or cache folder
2. Have a **single** provider enabled
3. Play track
4. Check if lyrics are messed up

Do this **for each** of your lyrics providers.

**Only** in this way will you know what the bad provider is. Your logging showed no lyrics access - fanart.tv is for backdrops, etc. If you do not delete the cached version, Cantata will use the cache - hence no network access.

Also, I no longer use MPD nor Cantata - so my time/enthusiasm for this is **very** limited.

**Comment by Durhammer3111** [comment]
No dice. I'm thinking it's not a "bad provider."

I played "Drive" over and over, deleted the cached lyrics file when it 
was created  (3 times -- only lyrics.wikia.com, azlyrics, and lyrics.com 
found them). Nothing ever got messed up on the Info page.

Thanks for pointing me to the cache files. I DID find a "Dermot Kennedy" 
folder with Glory.lyrics in it, found just fine. However, under the 
"R.E.M" folder, I found this file containing the "Drive" lyrics:

"Drive@@@@@mode=updinfo,Dermot Kennedy - Glory@@@@@mode=updinfo,R.E.M. - 
Drive.lyrics"

Also, since the "Drive" lyrics should have been found on first try, with 
lyrics.wikia.com at the top of the search list, and with the lyrics 
actually captured, I can't see that it's a lyrics provider issue per se, 
at least for "Drive." What produces those "@@@@@" strings?

I'll try this again in a little bit with "Glory." Should I also fiddle 
around with the two songs that got the HTML/markdown coded blocks? 
(Never mind, I'll probably do it anyway.)

**Comment by Durhammer3111** [comment]
Most curious. Clearly, Cantata returned the lyrics for "Glory" by Dermot 
Kennedy, but in a one-at-a-time test, NONE of them returned the lyrics 
(and yes, I deleted the Glory.lyrics file).

**Comment by Durhammer3111** [comment]
Okay, another "focused" test. I tried running Dixie Chix "Gaslighter" 
against each lyrics provider one at a time. Only azlyrics returned the 
lyrics. All others returned nothing.

Prior to this, in my cached Dixie Chix folder, Lyrics folder, there was 
a "Gaslighter.lyrics" file that contained the markdown code. After 
deleting (moving, actually) this, only the one instance noted above 
produced a file.

**Comment by CDrummond** [comment]
Sorry but text comes from the lyrics providers. If you cannot find the bad one, and lyrics (when found) are OK I'm tempted to just close this. As stated, I have no time for this. I've reduced the set of default enabled providers to azlyrics.com, chartlyrics.com, and lyrics.wikia.com

If others sometimes work, and sometimes not, then it is up to the user to determine whether to use or not.

**Comment by Durhammer3111** [comment]
So riddle me this: does the *file name* come from lyrics providers? The 
file name for the "Drive" lyrics is the same goobered mess that showed 
as the title (with no lyrics displayed). I can't imagine getting the 
lyrics back from a "song title" like that.

BTW, I'm curious as to what you're using now if not Cantata+MPD. I'd 
love to know and be able to move forward. Don't feel like going back to 
lowering the pickup arm onto a hunk of vinyl on my old AR turntable.

And sure, if you just want to close this, sure. If it happens again, I 
can reopen the issue with hopefully more evidence.

**Comment by CDrummond** [comment]
The filename is from Cantata - from the song title. Perhaps this is related to #1593 ???

I switch to Logitech Media Server (despite its name, it is open source) about 3 years ago. I'm currently writing a Material-themed HTLM5 web ui for this.

**Comment by Durhammer3111** [comment]
I dunno. I've tried renaming the song file to have that weird file name, 
but it must get the correct one from the tags. (Guess I could try 
editing them, but that's getting ridiculous!) Go ahead and close the 
ticket if you'd like.

You seem to like tilting at windmills, Craig. :-) MPD couldn't be tamed 
nicely until Cantata (and thanks for the Windows ports for those!). Hope 
you can do the same for LMS. I'm still trying to sort out what to do 
with it as it stands. With Squeezebox dead, looks like homebrew RPi 
heaven, if that's your thing. Or Sonos/Alexa/Echo/Bluethingy. More oppos 
to spend $$$ !!!

Thank you for taking the time to try to fix my serendipitous problem. 
I've learned a lot about Cantata at the expense of your time -- sorry! 
Best wishes on your project(s)!

-Jim-

**Comment by CDrummond** [comment]
LMS/squeezelite is as homebrew as MPD. But, I'm not here to persuade others, MPD is a great application. I just prefer LMS.

Anyhow, I'll close this for now.
