### ISSUE TITLE
bad version number of mpd in server info

### ISSUE THREAD

**Issue by ibn-gazhi** [CDrummond/cantata#1605]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
I notice that the version number of mpd is incorrect in the windows "server information"

**To Reproduce**
![Capture d’écran de 2020-05-23 15-43-59](https://user-images.githubusercontent.com/61145707/82732453-8f262980-9d0d-11ea-904d-39849444d091.png)
![Capture d’écran de 2020-05-23 15-40-22](https://user-images.githubusercontent.com/61145707/82732457-9a795500-9d0d-11ea-9ee3-a8783596897d.png)

**Expected behavior**

**Screenshots**

**Version Info**
 - OS: loloarch 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux

 - Cantata Version: Last commit
 - MPD Version: 0.21.23
 - CMake options (other than default):

**Additional context**

**Comment by CDrummond** [comment]
Version number comes from MPD.

**Comment by rripio** [comment]
Just as a sidenote, protocol version and mpd version are different things, and that is correctly reported by the server. You get the same result with `mpc version`.
