### ISSUE TITLE
Unexpected but consistent library sort order

### ISSUE THREAD

**Issue by AlbinoDrought** [CDrummond/cantata#1607]
**Describe the bug**

The artists in the library pane on my machine are sorted in a consistent weird order. 

I'm not too familiar with MPD, and I'm not sure if the sorting occurs from within Cantata or MPD. I can provide more information (full config dump?) as requested.

Subset of displayed artists, from top to bottom, unexpected artists are bolded:

1. **Horace Andy**
2. Buju Banton
3. The Beatles
4. Black Uhuru
5. **Michael Bolton**
6. Boosie Badazz
7. **Dennis Brown**
8. **DJ Burn One & Gucci Mane**
9. Burning Spear
10. **Pimp C**
11. Capital STEEZ
12. Chance the Rapper

Sometimes I think it is sorting by last name, but then I'm not sure why `Black Uhuru` or `Burning Spear` are still with the other `B*` artists. I have included a full library screengrab in the screenshots section.

**To Reproduce**

I am not sure how to reproduce this exact issue - I don't remember it happening to a previous machine I used.

My library view seems to be configured as:

- `View` is set to `Detailed Tree`
- `Group By` is set to `Artist`
- `Sort Albums` is set to `Name`

**Expected behavior**

Artists should be sorted by the beginning of their name.

- `Horace Andy` should appear with other `H*` artists
- `Dennis Brown` should appear with other `D*` artists
- `Pimp C` should appear with other `P*` artists
- `Bob Marley & The Wailers` should appear with other `B*` artists
- `John Denver` should appear with other `J*` artists

Alternatively: All artists should be sorted by their last name?

**Screenshots**

![image](https://user-images.githubusercontent.com/852873/83808779-38ecab00-a66a-11ea-86f4-327ffc499fee.png)
![image](https://user-images.githubusercontent.com/852873/83808813-46a23080-a66a-11ea-80ce-6c7e903ff97c.png)
![image](https://user-images.githubusercontent.com/852873/83808831-4d30a800-a66a-11ea-8545-2241d25e760c.png)

**Version Info**
 - OS: Linux, 5.6.12-1-MANJARO
 - Cantata Version: 2.4.1
 - MPD Version: 0.21.23
 - CMake options (other than default): Unknown

**Comment by AlbinoDrought** [comment]
I believe everything is working as expected. Went on a code journey and ended up here: https://github.com/CDrummond/cantata/blob/e6610c1/db/librarydb.cpp#L77

```cpp
static bool albumsSortAlArYr(const LibraryDb::Album &a, const LibraryDb::Album &b)
{
    const QString &an=a.sort.isEmpty() ? a.name : a.sort;
    const QString &bn=b.sort.isEmpty() ? b.name : b.sort;
    int cmp=an.localeAwareCompare(bn);
    if (cmp!=0) {
        return cmp<0;
    }

    const QString &aa=a.artistSort.isEmpty() ? a.artist : a.artistSort; // this line
    const QString &ba=b.artistSort.isEmpty() ? b.artist : b.artistSort; // and this one
    cmp=aa.localeAwareCompare(ba);
    if (cmp!=0) {
        return cmp<0;
    }
    return a.year<b.year;
}
```

Turns out that some of my files have `ALBUMARTISTSORT` metadata. Here are some samples:

Properly sorted:
```
    comment[3]: ALBUM ARTIST=Black Uhuru
    comment[4]: ALBUMARTIST=Black Uhuru
    comment[5]: ALBUMARTIST_CREDIT=Black Uhuru
    comment[6]: ALBUMARTISTSORT=Black Uhuru
```

Unexpectedly sorted:
```
    comment[4]: ALBUM ARTIST=Dennis Brown
    comment[5]: ALBUMARTIST=Dennis Brown
    comment[6]: ALBUMARTIST_CREDIT=Dennis Brown
    comment[7]: ALBUMARTISTSORT=Brown, Dennis
```

Sorry for opening the issue! I'll try and make the `.artistSort.isEmpty()` check configurable in my local copy and always use `.artist` instead. I'll reference this issue from a fork if I get it up and running myself.

**Comment by CDrummond** [comment]
Thanks for looking into this yourself. Instead of hacking Cantata, which of course you are free todo, why not just set metada_to_use in MPD's config file. If you remove these 'sort' fields from there, then Cantata will not see them (you will, probably, need to refresh Cantata's DB).

**Comment by AlbinoDrought** [comment]
That looks like it will work best, thanks!

This seems to work perfectly: `metadata_to_use "-artistsort,albumsort,albumartistsort"`
