### ISSUE TITLE
Stream cover support?

### ISSUE THREAD

**Issue by barolo** [CDrummond/cantata#1612]
As it is now, streams always use placeholder image which is slightly annoying visually, with mpris populating it everywhere else.
For example SomaFM's channels.xml contains links for each channel's cover why not use it? 
Other issue is with streams which provide per track dynamic covers I guess but my main concerns is with getting anything to replace the placeholder.

**Comment by CDrummond** [comment]
Whilst I can see the use-case for this, its not a trivial code change. Sorry, but I no longer use Cantata nor MPD - switched to Logitech Media server about 3 years ago. (And this would provide what you are looking for...)

So, closing as 'wontfix' - as I have no time for this. pull requests welcome.

**Comment by barolo** [comment]
oh... sorry to hear that. I'll try to switch to something else. I'm already using something for my multimedia streaming needs but I've found that Cantata worked really well for my radio streaming/podcast usage
