### ISSUE TITLE
Needed possibility to re-index single folder

### ISSUE THREAD

**Issue by iamthevoid** [CDrummond/cantata#1618]
At first - thanks! Cantata is the best of linux music players i've met. I want to request a feature

On my computer i have "Temp" music folder. All downloads places there until they will be listened and after listening they can go to collection or be deleted. 

But after changes cantata show same state that was when last "refresh database" was applied

I want possibility to refresh folder by select an option, for example, in dropdown options list (for avoid full resync). Or make scheduled sync for any folder (for example every 10 minutes)

**Comment by CDrummond** [comment]
As stated when you opened this - Cantata is a **bug fix only** state. I will **not** be adding new features. I no longer use Cantata nor MPD - switch to logitech media server over 3 years ago.
