### ISSUE TITLE
Random Playlist not really random

### ISSUE THREAD

**Issue by wjg57** [CDrummond/cantata#1621]
**Describe the bug**
When "random play" is selected the sequence of titles played is much less than random

**To Reproduce**
- Create a dynamic playlist that selects many (in my case 500) titles from your library.
- start that playlist and select "random order"

**Expected behavior**
Titles should be played in random order, occasional repetition is ok, but not necessary.

**Observed behavior**
Titles are played "in cycles", i.e. some titles are repeated frequently with titles from the rest of the play list thrown in from time to time and also the cycles change from time to time (i.e. been running for two weeks now and not all title have come up yet).

**Version Info**
 - OS: Ubuntu 18.04
 - Cantata Version: 2.2.0
 - MPD Version: 0.20.0
 - CMake options (other than default): - (binary taken from the repos)

**Remark**
It looks to me, as if the next title to play were dynamically determined when one title has finished with a (pseudo) random number generator that has relatively short cycles, thus producing the observed behavior.
I've seen other implementations that  randomize the playlist once by swapping pairs of entries and then play the resulting list in order. This procedure is much less susceptible to bad PRNGs and assure that all the titles in the play list are played once.

**Comment by CDrummond** [comment]
Sorry - but random is random. 3 songs, 1, 2, and 3 - order 3333333 is still random. 1,2,3 is still random. Anyhow, I get your point that it needs to be more human acceptable 'random' Currently a smart playlist (not dynamic) gets its list of tracks - and if 'random' order is selected it calls the C++ random_shuffle routine to shuffle a list.

Sorry, but I have no time to increase the randomness - I no longer use Cantata nor MPD. I now use Logitech Media server with MusicIP used to create my random mixes. I've also created a google Material themed UI for this...

I know you don't want to hear this - but pull requests welcome.

**Comment by wjg57** [comment]
Thanks for the fast reply & no problem with the "won't fix" at all. It's a minor bother after all.

**Comment by CDrummond** [comment]
To be honest, not sure there is much that could be done with the current design. For 'smart' playlists Cantata gets the all items from MPD (using the 'smart' criteria) and then shuffles all returned items. There should be no duplicates in that. But if you then add the 'smart' playlist again, it runs the whole process again. This process does not take into account what is already on the queue.

Perhaps it could, but it'd be more work than I have time for. For me 'wontfix' issues are valid issues, just ones that I have no personal need for or have no time/desire to fix.

I **strongly** suggest looking into LMS.
