### ISSUE TITLE
Random playback (first song always played)

### ISSUE THREAD

**Issue by peterLaurence** [CDrummond/cantata#1623]
**Describe the bug**
When shuffled mode is active (random playback), the first song is always played.

**To Reproduce**
Click on the small icon "Play now and replace the current playlist", with the random mode active.

**Expected behavior**
The first played song should be truely random

**Version Info**
 - OS: Linux
 - Cantata Version: 2.4.1
 - MPD Version: 0.20.1

**Comment by CDrummond** [comment]
Playback is controlled by MPD - so the issue is there.
