### ISSUE TITLE
Configure Podcasts Folder

### ISSUE THREAD

**Issue by RandomUnknown** [CDrummond/cantata#1624]
**Is your feature request related to a problem? Please describe.**
All my folders in my home folder are lowercase, the only folder I have uppercase is Podcasts which is created by Cantata, I have created a lowercase podcasts folder and set up a symbolic link so Cantata can access the folder. 

**Describe the solution you'd like**
An option in the config file to allow you to define the podcast folder so I can change it to lowercase.

**Describe alternatives you've considered**
I have a symbolic link, I could compile cantata myself with a lowercase p for the Podcasts folder but this seems messy.

**Comment by CDrummond** [comment]
As stated, Cantata is in a bug-fix only state.

**Comment by RandomUnknown** [comment]
Will this eventually be added once it's out of this state?

**Comment by CDrummond** [comment]
Not unless you want to implement it yourself. Its not a matter of just changing a name - need to handle copying previous items over, renaming, etc. I have no use, or time, for this.

Cantata is in a bug-fix only state as I no longer use it nor MPD - switched to logitech media server over 3 years ago.
