### ISSUE TITLE
don't touch /boot

### ISSUE THREAD

**Issue by thelounge-zz** [CDrummond/cantata#1626]
i can't think of a single reason why cantata has a business to touch /boot at all

Jul 28 17:50:33 srv-rhsoft systemd[1]: boot.automount: Got automount request for /boot, triggered by 6111 (cantata)
Jul 28 17:50:33 srv-rhsoft systemd[1]: Mounting /boot...
Jul 28 17:50:33 srv-rhsoft kernel: EXT4-fs (md0): mounted filesystem without journal. Opts: (null)
Jul 28 17:50:33 srv-rhsoft kernel: ext4 filesystem being mounted at /boot supports timestamps until 2038 (0x7fffffff)
Jul 28 17:50:33 srv-rhsoft systemd[1]: Mounted /boot.

**Comment by CDrummond** [comment]
Not sure where that is comming from. Cantata does not mount anything - unless you set it up to mount a filesystem via SSHfs.

So, sorry no idea where you are getting this from, but its not Cantata. No mention of "/boot" in Cantata's source code.

**Comment by thelounge-zz** [comment]
where did i say cantata is mounting anything directly? sorry i have expected you understand a simple syslog line
https://www.freedesktop.org/software/systemd/man/systemd.automount.html

triggered by 6111 (cantata) is pretty clear and it's not about cantata mouting anything, it's about trigger AUTOMOUNTING by stat/ls the directory at startup! i can repdoduce that 100% by manually unmount /boot followed by close and open cantata again

**Comment by CDrummond** [comment]
Please, stop with the insults. Sorry, but Cantata was started as a FUN project. Which I now nolonger use, but still spend time trying to fix bugs. Insulting someone is not going to make then want to help.

Cantata itself does not stat/ls /boot - you can check the source code yourself, and I have. Its possible udisks is causing this, as solid-lite has some references, but no actual calls. If so, compile Cantata with device support disabled - pass`-DENABLE_DEVICES_SUPPORT=OFF` to cmake.

**Comment by thelounge-zz** [comment]
where do you see any insult? the first line of the report clearly states cantata as root cause and i find it insulting that you just close a report as first reaction!

cantata is built with -DENABLE_DEVICES_SUPPORT:BOOL=OFF and would it be udisks than udisks would be the process name, for whatever reason you seem to search for local files and trigger a stat on every folder of the rootfs

just don#t do that for stuff flagged with autofs

[root@srv-rhsoft:~]$ mount | grep /boot
systemd-1 on /boot type autofs (rw,relatime,fd=37,pgrp=1,timeout=60,minproto=5,maxproto=5,direct,pipe_ino=16924)

**Comment by CDrummond** [comment]
Sorry but this "i have expected you understand a simple syslog line" **is** insulting. Sorry that I'm not a systemd expert.

As stated Cantata does not **explicitly** do this, now perhaps some library is triggering this, I don't know. Just checked with strace, and I cannot see Cantata accessing /boot

```
strace -t -ff -o log -e trace=open,stat,lstat cantata
```

**Comment by thelounge-zz** [comment]
no need to be a systemd expert for "Got automount request for /boot, triggered by 6111 (cantata)" but anyways, you seem to do some sort of filesearch, inotify stuff or whatever

worked around it by just make /boot and /efi (for the future) completly hidden for any process starting in any GUI session

[root@srv-rhsoft:~]$ cat /etc/systemd/system/display-manager.service.d/security.conf | grep -P  "boot|efi"      
SystemCallFilter=~@clock @cpu-emulation @reboot @swap @obsolete
InaccessiblePaths=-/boot
InaccessiblePaths=-/efi
