### ISSUE TITLE
Show track information on read only items

### ISSUE THREAD

**Issue by ascomycota** [CDrummond/cantata#1629]
I use MPD on a read-only directory tree for MPD. This is no problem for playing. But in the context menu I can only see "Edit track information" which is disabled. (I guess due to this issue)

It would be nice to open the dialog anyways and just disable the save button in that dialog (if there is any - I can not see right now in my setup *g*)

Should be a simple change. What do you think?

Cheers & Thanks - great app anyways!
Andreas

**Comment by CDrummond** [comment]
You can see track info when playing.

Whilst what you are asking for seems trivial - it means new strings ('Show information', not 'Edit information') and breaks the use-case of the dialog. This is then a new feature, and I have no time to implement these - I stopped using Cantata and MPD over 3 years ago (switched to logitech media server (open source)).

Sorry, wont-fix for me.
