### ISSUE TITLE
KDE mute/unmute speaker icon taskbar integration

### ISSUE THREAD

**Issue by jansuX2** [CDrummond/cantata#1631]
Hi, the very handy small speaker icon for muting/unmuting the sound when playing -available in audio/video related applications in KDE plasma- is missing from Cantata. Without it Cantata is not complete, please do an exception for this tiny feature request :) Thanks again for the wonderful program. 

screenshot attached for futher clarification:
![Screenshot_20200819_175537](https://user-images.githubusercontent.com/67695932/90651742-12401880-e246-11ea-8aa3-f7a2baf5a87a.png)

**Comment by CDrummond** [comment]
Sorry - Cantata is in a bug-fix oly state, as clearly stated. I no longer use Cantata, or MPD, and have not used KDE in years.

**Comment by jansuX2** [comment]
Thanks for the immediate response and the direct answer. Maybe some other contributor could fix this if it was more visible? Here's to hoping.

**Comment by Thaodan** [comment]
Maybe do some research and show the API for that.

**Comment by CDrummond** [comment]
It is **not** a bug - this is a new KDE feature. Why does it not just use the MPRIS interface?

**Comment by Thaodan** [comment]
I know but if its I maybe add that.
The feature works by mapping pulseaudio streams to an X11/Wayland window.
Thats something that of course not works for cantata as its playing no music.
But if there is a way to map the mpd stream to the cantata window for that thing why not.
