### ISSUE TITLE
copy to device queue

### ISSUE THREAD

**Issue by starenka** [CDrummond/cantata#1632]
It would be awesome if the "copy to device" would have one queue one can add things being copied to device. Now you have to wait until one item is copied and only after that you can copy another item. It's quite cumbersome when copying a lot of stuff. Cheers.

**Comment by CDrummond** [comment]
As stated when you created this issue, Cantata is in a bug-fix only state. So, unless you are going to code this yourself, its not gonna happen.

As a work-around, add files to a temporary playlist, then copy the tracks from that playlist to the device.

**Comment by starenka** [comment]
Oh, that is a clever workaround. Thank you

Unfortunatelly, I'm not so cpp proficient to tackle this. Thank you for
your time. I love cantata!

---
aknerats[::-1]
