### ISSUE TITLE
Cantata won't start

### ISSUE THREAD

**Issue by anthony-beckett** [CDrummond/cantata#1634]
**Describe the bug**
Cantata won't start through either the GUI or the CLI. When starting with the GUI, a black square appears and then quickly disappears. The CLI does the same, however it provides an error.

**To Reproduce**
1. Open terminal
2. `~$ cantata`
3. See error

**Expected behavior**
As stated before, a black square appears for a short time before disappearing. The errors given are as follows:

1. _I don't have the exact wording, because I cleared the terminal and then the new error message appeared_ However, the error was regarding incorrect handling of a pointer.

2. 
```
~$ cantata
corrupted size vs. prev_size
Aborted (core dumped)
```

**Version Info**
 - OS: GNU/Linux Pop!_OS 20.04 (Nvidia)
 - Cantata Version: 2.4.1
 - MPD Version: 0.21.20

**Additional context**
I installed through apt yesterday, rather than building from source. It worked perfectly then.

**Comment by CDrummond** [comment]
Not sure what you expect me to do about this? No debug info, so no idea where the 'crash' is. And it works when you install from apt. I build Cantata from source, Ubuntu and Fedora, and it works fine for me. Sorry, but to progress this, if it is even an issue, I'll need **much** more info.

Which Qt theme are you using? As, AFAIK, Ubuntu uses the Gtk theme engine. Try with `cantata --style Fusion`

**Comment by anthony-beckett** [comment]
Sorry, the issue seems to have fixed itself for whatever reason within the time of me posting and you replying. But I have the style set to Fusion.
