### ISSUE TITLE
Cantata silently die on Debian

### ISSUE THREAD

**Issue by AndriiZ** [CDrummond/cantata#1635]
**Describe the bug**
I have built and install cantata on Debian with kernel 4.19.104

When I run Cantata, I just get a message 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-andriy'

and cantata silently stop without any logs

**Comment by CDrummond** [comment]
Sorry, but it works for me. Not sure what you expect me to do with such limited info. Tried running it in a debugger??

**Comment by AndriiZ** [comment]
Is is possible to add switch --verbose and redirect all messages to stdout?

**Comment by AndriiZ** [comment]
Also, I have tried to build on Debian only because can not find precompiled binary for Debian. Do you have 2.4.1 for Debian? I was able to find for ubuntu only

**Comment by AndriiZ** [comment]
But for some reason my ubuntu 18.04 also silently stop without any logs (installed from ppa)

**Comment by CDrummond** [comment]
I don't provide **any** builds, sorry. Again, have you run in it a debugger? Cantata **does** work - if its not starting for you, then its an issue on your system. Which theme is it using? Try `cantata --style fusion`

**Comment by CDrummond** [comment]
I have now installed Cantata (2.4.0) from `ppa:ubuntuhandbook1/cantata-qt` on an 18.-04 VM, and it starts just fine.

**Comment by AndriiZ** [comment]
(gdb) run
Starting program: /usr/bin/cantata
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffefe99700 (LWP 1830)]
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-andriy'
[New Thread 0x7fffef440700 (LWP 1831)]
[Detaching after fork from child process 1832]
[Thread 0x7fffefe99700 (LWP 1830) exited]
[Thread 0x7fffef440700 (LWP 1831) exited]
[Inferior 1 (process 1826) exited normally]

**Comment by CDrummond** [comment]
Hmmm... odd. Sorry, I have no idea. It works for me in Fedora32, Ubuntu 18.04, Ubuntu 20.04, and works for others Must be something odd abut your system. Have you ever run Cantata sucessfully? Does ~/.config/cantata/cantata.conf exist? If so, does it help if you remove it? (Perhaps take a copy befoe removing, in case that is the error - then you could attach that here)

Have you tried setting the style? `cantata --style fusion` ???

**Comment by CDrummond** [comment]
As stated, works for me - and **many** others. The PPA I installed also works fine. I don't create **any** binaries, so if there is an issue with one of theose then its a packaging issue.
