### ISSUE TITLE
Copy/Transcode files to library

### ISSUE THREAD

**Issue by Gfurst** [CDrummond/cantata#1639]
**Is your feature request related to a problem? Please describe.**
Currently we organize and arrange files already present in the library, or copy/transcode them into the library from an external media like a CD.

**Describe the solution you'd like**
The same method used for the external media would be perfect for those files still outside the library, or for when you to transcode into a different format.

**Describe alternatives you've considered**
Currently no other way of doing this without third parties, and considering when you also have to rearrange tags, organize and cleanup. Considering Cantata already does a great job partly at this, just extending that functionality to local files otherwise not on external media would be a great addition.

**Comment by CDrummond** [comment]
As clearly stated when you raised this issue, cantata is in a bug-fix only state. Sorry, but I no longer use Cantata nor MPD (switched to LMS/Squeezelite about 4 years ago). If you want this, then you will need to implement yourself.

**Comment by Gfurst** [comment]
I could try and implement it myself with a little hand holding, since I'm not that familiar with the codebase.

**Comment by CDrummond** [comment]
If you want, then great. As you have seen there is code to transcode when copying to devices, so most of the work is done. `devices/encoders.cpp` has the interface to ffmpeg, etc, for transcoding, and `devices/transcodingjob.cpp` is where the transcode occurs. I _think_ there is a _CopyJob_ currently used to copy files to MPD, this would (optionally) need replacing with a `TrancodingJob`

**Comment by Gfurst** [comment]
I will look these up, but where does the hook happens from the gui tooltip?
