### ISSUE TITLE
Not all tags shown for Matroska file

### ISSUE THREAD

**Issue by greenvorbisfan** [CDrummond/cantata#1640]
Hello. I'm not sure if it depends on the Cantata, but the tags from the Matroska audio files of (*.mka) are not fully read — e. g. the tags «Album Title» and «Date» are missing. For comparison, foobar2000 and AIMP 4 show tags correctly.
![Screenshot](https://user-images.githubusercontent.com/7892693/94362154-fdb33380-00c1-11eb-88ff-f46cd3668908.png)
[MKA file for example](https://greenserver.tk/index.php/s/Z6gNJTDXQqcCA4z)

**Version Info**
 - OS: Linux (Ubuntu 18.04.5 x64)
 - Cantata Version: 2.4.2 git
 - MPD Version: 0.22 git
 - CMake options: -DCMAKE_INSTALL_PREFIX:PATH=/home/user/.local -Wno-dev

**Comment by CDrummond** [comment]
Sorry, file format not supported by Cantata's tag reading/writing code, and I have no motivation to add support for every format under the sun. To me, this is not a bug but a missing feature - and I am no longer adding new features. I no longer use MPD nor Cantata.
