### ISSUE TITLE
'CUE files - Do not list' not working

### ISSUE THREAD

**Issue by tyke2** [CDrummond/cantata#1642]
**Description**
CUE files - Do not list option is not being respected; cue files which represent albums or songs are still shown, no matter whether the files the cue file is pointing to are there or not. Issue did not appear until the latest update, v2.4.2, came out 19 days ago.

**To Reproduce**
Go into settings - Interface - Tweaks, set CUE files option to 'Do not list', hit ok. 
Click on burger menu, hit 'Refresh Database' and wait for scanning to finish.
Check library to see double listings of albums/singles (one for the actual files, one for the cue file), and hover over individual track to see specifically the cue pointed to.

**Expected behavior**
Only actual audio files (.flac, .mp3, etc.) should be listed and be accessible in/from the library.

**Screenshots**
https://freeimage.host/i/2gaaHl
https://freeimage.host/i/2ga7S4
https://freeimage.host/i/2ga5lf
https://freeimage.host/i/2gacR2
https://freeimage.host/i/2galNS

**Version Info**
 - OS: Arch Linux
 - Cantata Version: cantata 2.4.2-1 (from Arch community repository)
 - MPD Version: mpd 0.22-1 (from Arch extra repository)
 - CMake options (other than default): None, package not edited

**Extra Info**
A friend which uses mpd/Cantata on a linux system faces the same issue of cue file not being ignored, so I don't believe that the problem is specific to me, or just a simple usage error.

**Comment by CDrummond** [comment]
That extra track is **not** comming from Cantata - it does not name cue tracks that way. They would be named "cue://xxxx.flac?pos=<number>" Looks like MPD is listing the track twice.

**Comment by AlbinoDrought** [comment]
@tyke2 It's related to this change in [MPD 0.22](https://raw.githubusercontent.com/MusicPlayerDaemon/MPD/v0.22/NEWS):

```
ver 0.22 (2020/09/23)
* playlist
  - cue: integrate contents in database
```

See also https://github.com/MusicPlayerDaemon/MPD/issues/992#issuecomment-723122088
