### ISSUE TITLE
Podcasts: Mark episodes as...

### ISSUE THREAD

**Issue by anarchotaoist** [CDrummond/cantata#1643]
**Describe the bug**
In podcasts right clicking gives the options;
Mark episodes as new
Mark episodes as listened

but clicking either option makes no noticeable change.

**To Reproduce**
1. Go to Internet - podcasts
2. Right Click on podcast episodes
3. Mark as listened
4. No indication showing episode has been 'listened to'.

**Expected behavior**
Right click podcast episode, click 'Mark as listened to'
and see a symbol or indication showing episode has been played through.

**Version Info**
 - OS: Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-25-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

 - Cantata Version: 2.4.1
 - MPD Version: 0.21.22-1build3

Thanks.

**Comment by CDrummond** [comment]
Just tried, and it does work. New episodes are in bold, and the number of new episodes shown in podcast title. Clicking mark as listened changes to non-bold and reduces the number. Marking as new makes the title bold and increases the number.

However, marking a new item as new has no effect, as it already is. Likewise as listened. The popup menu does not relect an items current state.

**Comment by anarchotaoist** [comment]
Yes, the bold is true.
The font I have makes it hard to distinguish.
Sorry for the interruption.
Thanks for the investigation
