### ISSUE TITLE
Podcast 'Universal Inbox' playlist option

### ISSUE THREAD

**Issue by anarchotaoist** [CDrummond/cantata#1644]
**Describe the solution you'd like**
To currently view new podcasts one must go into each separate podcast feed.
A 'universal inbox' view which displays all new podcasts in one feed regardless of the source feed would be convenient.
eg. The view feed experienced with Cpod podcatcher.

Thanks.

**Comment by CDrummond** [comment]
Sorry, as stated when you opened this report, Cantata is in a bug fix **only** state. Want this implemented, then you will need to do this yourself and create a pull request. I stopped actively using Cantata and MPD over 3 years ago, when I switched to LMS.
