### ISSUE TITLE
last.fm Scrobbling ignore proxy settings.

### ISSUE THREAD

**Issue by IlyaIndigo** [CDrummond/cantata#1645]
**Describe the bug**
Today I noticed that my audio scrobbling stopped working.
As it turned out later, the auth ( https://secure.last.fm ) and API ( https://ws.audioscrobbler.com ) pages lead to a 403 page with the Google logo. Google in Crimea has now blocked last.fm. :-(
I found in the cantata Proxy settings, indicated a working socks5 proxy (in firefox and telegram-desktop work), but I still cannot log into last.fm with the correct username and password (checked in firefox with the same proxy). From this, I conclude that, at least, autintification on last.fm, and even the scrobbling itself, ignore the proxy settings.
Cantata does not write anything to the log -f option does not work, it even displays a strange message, strace, for some reason, did not display anything with the entry of audioscrobbler or last.fm, so I have nothing to attach.

**To Reproduce**
1 Find or create a working socks5 proxy with port 1080.
2 Specify its cantata settings.
3 Log out of last.fm if you were logged in before, and log in again with your username and password.
4 In some way, unknown to me, determine that the request was sent not from this socks5 proxy.
5 In the same unknown way, check through what is sent to the last.fm API (https://ws.audioscrobbler.com) through the socks5 proxy or not?

**Expected behavior**
Authentication and scrobbling for last.fm must go through the cantata socks5 proxy specified in the settings, if it is specified.

**Version Info**
 - OS: openSUSE Tumbleweed
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.2
 - CMake options: -DENABLE_REMOTE_DEVICES=OFF -DENABLE_CATEGORIZED_VIEW=OFF

**Comment by CDrummond** [comment]
Sorry, but Cantata's proxy settings are not in default build for a reason - as I don't think they belong in a music app. The network code uses the Qt routines, so any proxy handling should be handled by this. Are you using Cantata's proxy settings? Or system proxy settings?

**Comment by IlyaIndigo** [comment]
> Are you using Cantata's proxy settings? Or system proxy settings?
Cantata's proxy settings only.

**Comment by CDrummond** [comment]
As stated, Cantata's proxy settings are not in the default biulds - and for a good reason. Sorry, but this is not supported. My time for Cantata is **very** limted (as I stopped using it and MPD over 3 years ago), and I have no time to debug issue in non default builds.

**Comment by IlyaIndigo** [comment]
It's okay, last.fm had a crash when switching to google services.
Through socks5, the proxy perfectly authenticates and scrobbles bypassing Google bans.
