### ISSUE TITLE
/usr/share/cantata/config/lyrics_rhsoft.xml no longer works

### ISSUE THREAD

**Issue by thelounge-zz** [CDrummond/cantata#1646]
originally years ago i removed the lyric providers and add only my own one vecause i grabbed over the past 20 years all lyrics and added them to a private database - now it seems the are a) hardcoded and b) my shipped one is ignored

`[root@srv-rhsoft:~]$ cat /usr/share/cantata/config/lyrics_rhsoft.xml
<?xml version="1.0" encoding="UTF-8"?>
<lyricproviders>
 <provider name="rhsoft.net" title="LYRICS DATABASE - {artist} - {title}" charset="ISO-8859-1" url="****/lyrics.php?q={artist}+{title}">
  <urlFormat replace=" ._@,;&amp;\/&quot;" with=""/>
   <extract>
    <item tag="&lt;p id='lyricsContent'&gt;"/>
   </extract>
 </provider>
</lyricproviders>`

**Comment by thelounge-zz** [comment]
it would make so much more sense when you just could add "http://***/lyrics.php?q={artist}+{title}" from the userinterface where you enable/disable and order lyrics providers

**Comment by CDrummond** [comment]
Cantata is in bug-fix only state, I am not adding new features - as you were made aware of when you created this issue.

**Comment by thelounge-zz** [comment]
> Cantata is in bug-fix only state, I am not adding new features

so why did you recently *remove* support of /usr/share/cantata/config/ to place lyric providers there

**Comment by CDrummond** [comment]
That change was made in May 2018 - hardly recent.

You should still be able to use ~/.local/share/cantata/lyrics_*.xml

**Comment by thelounge-zz** [comment]
no, i tried that long before writing the report at all, besides it's braindead to move a software into "no-longer-miantained" mode and have things hardcoded that way i could puke when somone argues with "you should"

what was the point to remove that to begin with?
and no after having everything cached i didn't realize the breakage over two years

luckily my php script updating my database is feeding ".cache/cantata/lyrics/" directly because i try to depend as less as possible on people out there as i learned what with cantata seems to happen is the norm these days

[harry@srv-rhsoft:~]$ cp /usr/share/cantata/config/lyrics_rhsoft.xml ~/.local/share/cantata/
[harry@srv-rhsoft:~]$ ls ~/.local/share/cantata/
insgesamt 32K
drwxr-x--- 2 harry verwaltung 4,0K 2013-12-24 12:28 bookmarks
drwxr-x--- 2 harry verwaltung 4,0K 2020-11-05 10:00 config
drwxr-x--- 2 harry verwaltung 4,0K 2013-12-24 12:28 dynamic
drwxr-x--- 2 harry verwaltung 4,0K 2020-10-23 23:24 library
drwxr-x--- 2 harry verwaltung 4,0K 2016-06-05 23:48 online
drwxr-x--- 2 harry verwaltung 4,0K 2013-12-24 12:28 podcasts
drwxr-x--- 2 harry verwaltung 4,0K 2013-12-24 12:28 streams
-rw-r----- 1 harry verwaltung  376 2020-11-06 12:27 lyrics_rhsoft.xml
[harry@srv-rhsoft:~]$ cd ~/.local/share/cantata/
[harry@srv-rhsoft:~/.local/share/cantata]$ mv lyrics_rhsoft.xml config/
[harry@srv-rhsoft:~/.local/share/cantata]$ cd config/
[harry@srv-rhsoft:~/.local/share/cantata/config]$ ls
insgesamt 4,0K
-rw-r----- 1 harry verwaltung 376 2020-11-06 12:27 lyrics_rhsoft.xml
