### ISSUE TITLE
AlbumView::getTrackListing/updateDetails can take a very long time for large databases

### ISSUE THREAD

**Issue by ccoors** [CDrummond/cantata#1647]
**Describe the bug**
I have a rather large MPD database with 411217 songs. 386065 of them are listed as "Unknown" for Artist and Album. `AlbumView::updateDetails` takes about 30 seconds after a song change, during which Cantata is completely frozen - [`setHtml(pic+trackList);`](https://github.com/CDrummond/cantata/blob/master/context/albumview.cpp#L320) and `trackList` is a `QString` with size 53157168 (!). This string obviously takes Qt quite some time to process.

**To Reproduce**
1. Have a huge mpd library with all songs set to the same Album/Artist
2. Play a song

**Expected behavior**
No idea. Maybe limit the list length? Or just skip all of that while the `AlbumView` is hidden?

**Screenshots**

**Version Info**
 - OS: Arch Linux
 - Cantata Version: 2.4.2 (29e8851862ad52439abe668ea6d35946d4e1af49)
 - MPD Version: 0.22.2
 - CMake options (other than default):

**Additional context**
I realize Cantata is not under active development anymore (which is really sad btw.). I'd be willing to give a fix a try, if you can tell me which behavior would be acceptable.

**Comment by CDrummond** [comment]
At a guess, I'd assume its the shear number of tracks. So, I'd start by:

a. Add a maxTracks parameter to `getAlbumTracks` in sqlibrarymodel.h (both versions) - e.g.
```
    QList<Song> getAlbumTracks(const QString &artistId, const QString &albumId, int maxTracks=-1) const;
    QList<Song> getAlbumTracks(const Song &song, int maxTracks=-1) const { return getAlbumTracks(song.albumArtistOrComposer(), song.albumId(), maxTracks); }
```
b. `SqlLibraryModel::getAlbumTracks` needs to pass maxTracks onto `LibraryDb::getTracks`
c. In `LibraryDb::getTracks` id maxTracks!=-1 then alter the SQL to only retrive up to that caount
d. in `AlbumView::getTrackListing` call `getAlbumTracks` with maxTracks set to (e.g.) 500

**Comment by CDrummond** [comment]
Thanks for the pull request, much appreciated. I've added an entry (and credited you) to the ChangeLog for 2.4.3
