### ISSUE TITLE
CUE file with multiple source files producing duplicate tracks.

### ISSUE THREAD

**Issue by Utini2000** [CDrummond/cantata#1650]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
I noticed that in each album all my songs are twice. Once with a working file and once with a non working file which also shows no track duration. I then realized that it must be related to the .cue file. So I removed a .cue file from a folder and suddenly everything gets displayed correctly. 

**To Reproduce**
1. Add folder which includes a whole album of tracks + a .cue file
2. View that album in library view and you will see each track twice (once working, once not working)
3. Add that album to the playlist and you will have again each track twice (once working, once not working)
4. Remove the .cue file from the folder
6. Refresh database
7. Everything will be fine

**Expected behavior**
Parse .cue files correctly

**Screenshots**
![cantata1](https://user-images.githubusercontent.com/14877663/99114155-aaa12b80-25f0-11eb-8efa-b7fd5b8469e2.png)

**Version Info**
 - OS: Arch Linux 5.9.8.a-1-hardened
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.3

**Additional context**
As an example, here is the content of the .cue file from the screenshot above:

`
REM GENRE Alternative
REM DATE 2016
REM DISCID 850A290A
REM COMMENT "ExactAudioCopy v1.1"
CATALOG 0602547950864
PERFORMER "Glass Animals"
TITLE "How to Be a Human Being"
FILE "01 - Life Itself.wav" WAVE
  TRACK 01 AUDIO
    TITLE "Life Itself"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600018
    INDEX 01 00:00:00
FILE "02 - Youth.wav" WAVE
  TRACK 02 AUDIO
    TITLE "Youth"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600029
    INDEX 01 00:00:00
FILE "03 - Season 2 Episode 3.wav" WAVE
  TRACK 03 AUDIO
    TITLE "Season 2 Episode 3"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600026
    INDEX 01 00:00:00
FILE "04 - Pork Soda.wav" WAVE
  TRACK 04 AUDIO
    TITLE "Pork Soda"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600025
    INDEX 01 00:00:00
FILE "05 - Mama's Gun.wav" WAVE
  TRACK 05 AUDIO
    TITLE "Mama's Gun"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600023
    INDEX 01 00:00:00
FILE "06 - Cane Shuga.wav" WAVE
  TRACK 06 AUDIO
    TITLE "Cane Shuga"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600057
    INDEX 01 00:00:00
FILE "07 - The Other Side Of Paradise.wav" WAVE
  TRACK 07 AUDIO
    TITLE "The Other Side Of Paradise"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600028
    INDEX 01 00:00:00
FILE "08 - Take A Slice.wav" WAVE
  TRACK 08 AUDIO
    TITLE "Take A Slice"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600027
    INDEX 01 00:00:00
FILE "09 - Poplar St.wav" WAVE
  TRACK 09 AUDIO
    TITLE "Poplar St"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600024
    INDEX 01 00:00:00
FILE "10 - Agnes.wav" WAVE
  TRACK 10 AUDIO
    TITLE "Agnes"
    PERFORMER "Glass Animals"
    ISRC GB2DY1600021
    INDEX 01 00:00:00

`

**Comment by CDrummond** [comment]
CUE files are not something I use, but I know they **do** work. Not sure what's wrong in the scenario. My guess is that MPD is also listing the cue contents. You could try changing Cantata's setting to not list cue files.

**Comment by Utini2000** [comment]
I already set cantata to not list .cue files but that seems to be completely ignored:

![Screenshot_20201115_200421](https://user-images.githubusercontent.com/14877663/99194127-d43b8d80-277d-11eb-9322-35db22e7ffae.png)

I tried to google but couldn't find any way to set mpd to ignore .cue files?

**Comment by CDrummond** [comment]
Odd. Have you tried other MPD clients? Sonata, MPC?

**Comment by Utini2000** [comment]
Okay, could be that ymuse simply displays the "album" as a kind of a "file viewer".
I also installed "ario" now. This app seems to have the same troubles as cantana.

**Comment by CDrummond** [comment]
This _might_ be due to MPD's new (configurable) behaviour of treating a CUE file as a folder. I've just made a change for this, can you build a version from git/master and see if this is now resolved?

**Comment by Utini2000** [comment]
I am pretty newbie to this but I guess if I install this AUR package, then I will have the latest git package installed?
https://aur.archlinux.org/packages/cantata-git

This will most likely remove my currently installed cantata. Will this also mean that my settings/configuration is going be lost? 

Thanks!

**Comment by Thaodan** [comment]
> This will most likely remove my currently installed cantata. Will this also
> mean that my settings/configuration is going be lost?
No settings/userdata are independent of the package.

**Comment by CDrummond** [comment]
@Utini2000 I doubt AUR updates that quickly! Infact that link states Cantata 2.3.3 - which is a bit old!

**Comment by Utini2000** [comment]
Oh crap, I thought that AUR package would always build the latest from git and is just an "easy" shortcut on installing latest git package.
Uhm I will try to figure out with the arch-wiki on how to manually install something from git :-)

**Comment by vermeeren** [comment]
@Utini2000 Based upon sources https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cantata-git it should indeed use latest git and automatically update the package version. Check the resulting installed version after building, it should **not** be the `2.3.3.r35.g4c1b8fd49` currently on the page.

Also keep in mind you need to `Refresh Database` in Cantata after setting the Cantata `CUE files` to `Do not list`. After this all of my duplicate tracks are gone.

**Comment by Utini2000** [comment]
I just tried the git version. Now it only lists the tracks from the .cue file. Meaning all my tracks are "unknown length" and source is the .cue file.

It does not matter if I ignore or show .cue files in setting. I did refresh the database :-)

**Comment by CDrummond** [comment]
So, issue of duplicate tracks is fixed. Durations come from MPD.

**Comment by Utini2000** [comment]
@CDrummond No it is not fixed. 

Yes there are not two tracks anymore (in some cases, not in all).
But the tracks that are shown in Cantata do not work. I can't play them.

**Comment by CDrummond** [comment]
If you are not using Cantata's CUE parsing, then the tracks are from MPD. If they don't play its an MPD issue.

**Comment by CDrummond** [comment]
...and this issue was about duplicate tracks - so yes, it is fixed.

**Comment by CDrummond** [comment]
Sorry to sound harsh - but I stopped using MPD and Cantata over 3 years ago, so my time for issue is **very** limited. I have fixed this as best I can.

**Comment by Utini2000** [comment]
I am parsing .cue and original files according to cantata (git version) but I only see the not working tracks?

Anyway, it just seems like I have to live with the issue.

May I ask to which app you have switched so that you stopped using mpd/cantata?

**Comment by CDrummond** [comment]
Logitech media server. 

---------------

As you are using a recent MPD, you can disable Cantata's CUE file (set to 'Do not list') - then CUE tracks come from MPD, and any errors will lie there.

**Comment by vermeeren** [comment]
@Utini2000 Can you try searching with `mpc` utility? Search for any album you have that uses CUE file.

Here is some example-ish output from my end.

```console
$ mpc search any 'Miscellaneous'
.../2008.05.25 [NTCD-0002] Miscellaneous Fragement [例大祭5]/Miscellaneous Fragement.cue/track0001
...
```

You should get results like this with `/track0001` `/track0002` etc at the end.

**Comment by Utini2000** [comment]
@vermeeren this is the output:

`
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/01 - Life Itself.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/02 - Youth.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/03 - Season 2 Episode 3.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/04 - Pork Soda.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/05 - Mama's Gun.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/06 - Cane Shuga.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/07 - The Other Side Of Paradise.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/08 - Take A Slice.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/09 - Poplar St.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/10 - Agnes.flac
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0001
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0002
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0003
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0004
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0005
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0006
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0007
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0008
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0009
AA High Quality/Alben/Glass Animals - How to Be a Human Being (2016) [FLAC]/How to Be a Human Being.cue/track0010

`

**Comment by vermeeren** [comment]
@Utini2000 Yeah that looks good. Adding the tracks from the cue file to the playlist should just work then. You mention thought the tracks don't work. I am guessing it plays them "instantly" which just skips to the next file right away.

In the CUE file contents you posted above https://github.com/CDrummond/cantata/issues/1650#issue-742742078 I see a lot of this:

```
FILE "01 - Life Itself.wav" WAVE
```

But the real filename is `01 - Life Itself.flac`, not `.wav`, so it's not gonna work! Probably whoever ripped this album forgot to update CUE file after converting to FLAC format.

Can you try changing all the `FILE` entires in CUE file so that they are like this:

```
FILE "01 - Life Itself.flac" WAVE
```

Then refresh database and try adding them again.

**Comment by Utini2000** [comment]
@vermeeren Yes I noticed that already as well but didn't focus on it because so far it has always worked and I didn't change anything.

Anyway, changing .wave to .flac in the .cue file makes the files playable. How ever, the tracks still have "unknown playtime/duration". And then ofcourse every track is in the library a second time with working playtime/duration.

Basically all I need it cantata to completely ignore the .cue file.

**Comment by vermeeren** [comment]
@Utini2000 The problem here is you have both split FLAC files and a CUE sheet for the split makes, so there is no reason for the CUE sheet to exist assuming the FLAC files themselves also have metadata tagged properly.

Typical usage for CUE file is if you have a single `Album/cd.flac` containing the entire ripped CD, then `Album/cd.cue` contains the per-track metadata and song position within the single audio file.

I suggest you delete CUE file after confirming the individual FLAC files have metadata set properly.

> Basically all I need it cantata to completely ignore the .cue file.

MPD parses both FLAC file and CUE file, as the output of `mpc search` above shows, it is not Cantata. If you really don't want to delete CUE file you can disable MPD CUE parser for **all files** instead https://www.musicpd.org/doc/html/user.html#configuring-playlist-plugins.

**Comment by Utini2000** [comment]
Thank you. That is a perfect fix for my usage :-)

Although mpd is running, I got this error after restarting it with "systemctl restart mpd.service --user":

`● mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-11-19 19:57:26 CET; 1min 4s ago
       Docs: man:mpd(1)
             man:mpd.conf(5)
   Main PID: 183193 (mpd)
     CGroup: /user.slice/user-1000.slice/user@1000.service/mpd.service
             └─183193 /usr/bin/mpd --no-daemon

Nov 19 19:57:25 S2000 systemd[2889]: Starting Music Player Daemon...
Nov 19 19:57:26 S2000 systemd[2889]: Started Music Player Daemon.
Nov 19 19:57:26 S2000 systemd-coredump[183192]: Process 2908 (mpd) of user 1000 dumped core.
                                                
                                                Stack trace of thread 2908:
                                                #0  0x00006073756b7615 raise (libc.so.6 + 0x3d615)
                                                #1  0x00006073756a0862 abort (libc.so.6 + 0x26862)
                                                #2  0x00006073756a0747 __assert_fail_base.cold (libc.so.6 + 0x26747)
                                                #3  0x00006073756afbf6 __assert_fail (libc.so.6 + 0x35bf6)
                                                #4  0x000007b5cad14279 n/a (mpd + 0xae279)
                                                #5  0x000007b5cad142d1 n/a (mpd + 0xae2d1)
                                                #6  0x000007b5cad46b35 n/a (mpd + 0xe0b35)
                                                #7  0x000007b5cad46b7e n/a (mpd + 0xe0b7e)
                                                #8  0x000007b5cad46b7e n/a (mpd + 0xe0b7e)
                                                #9  0x000007b5cad46b7e n/a (mpd + 0xe0b7e)
                                                #10 0x000007b5cad46b7e n/a (mpd + 0xe0b7e)
                                                #11 0x000007b5cad46c46 n/a (mpd + 0xe0c46)
                                                #12 0x000007b5cacc9757 n/a (mpd + 0x63757)
                                                #13 0x000007b5cacb6bb7 n/a (mpd + 0x50bb7)
                                                #14 0x000007b5cacb7afd n/a (mpd + 0x51afd)
                                                #15 0x000007b5cacae25c n/a (mpd + 0x4825c)
                                                #16 0x00006073756a2152 __libc_start_main (libc.so.6 + 0x28152)
                                                #17 0x000007b5cacae55e n/a (mpd + 0x4855e)
                                                
                                                Stack trace of thread 2972:
                                                #0  0x000060737577a5de epoll_wait (libc.so.6 + 0x1005de)
                                                #1  0x000007b5cace856d n/a (mpd + 0x8256d)
                                                #2  0x000007b5cace2954 n/a (mpd + 0x7c954)
                                                #3  0x00006073779f43e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #4  0x000060737577a293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 2971:
                                                #0  0x000060737577a5de epoll_wait (libc.so.6 + 0x1005de)
                                                #1  0x000007b5cace856d n/a (mpd + 0x8256d)
                                                #2  0x000007b5cace2954 n/a (mpd + 0x7c954)
                                                #3  0x00006073779f43e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #4  0x000060737577a293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 37236:
                                                #0  0x00006073779fa6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                                #1  0x0000607375a6ec11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                                                #2  0x000007b5cad1e717 n/a (mpd + 0xb8717)
                                                #3  0x000007b5cace2954 n/a (mpd + 0x7c954)
                                                #4  0x00006073779f43e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #5  0x000060737577a293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 37237:
                                                #0  0x00006073779fa6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                                #1  0x0000607375a6ec11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                                                #2  0x000007b5cad1e717 n/a (mpd + 0xb8717)
                                                #3  0x000007b5cace2954 n/a (mpd + 0x7c954)
                                                #4  0x00006073779f43e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #5  0x000060737577a293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 37238:
                                                #0  0x000060737576f46f __poll (libc.so.6 + 0xf546f)
                                                #1  0x0000607377a6e674 n/a (libpulse.so.0 + 0x33674)
                                                #2  0x0000607377a579a9 pa_mainloop_poll (libpulse.so.0 + 0x1c9a9)
                                                #3  0x0000607377a622a1 pa_mainloop_iterate (libpulse.so.0 + 0x272a1)
                                                #4  0x0000607377a62351 pa_mainloop_run (libpulse.so.0 + 0x27351)
                                                #5  0x0000607377a7281e n/a (libpulse.so.0 + 0x3781e)
                                                #6  0x00006073704ea5fc n/a (libpulsecommon-13.99.so + 0x565fc)
                                                #7  0x00006073779f43e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #8  0x000060737577a293 __clone (libc.so.6 + 0x100293)
`

**Comment by vermeeren** [comment]
@Utini2000 That looks like MPD bug, you may want to try updating MPD or double checking configuration. Otherwise likely best to report this on MPD issue tracker with details https://github.com/MusicPlayerDaemon/MPD/issues.

You may also wanna try it with stopping the service and manually running `mpd --no-daemon --stderr --verbose` in terminal to see if you can find the issue. Either way though this is not Cantata issue.
