### ISSUE TITLE
playlists do not save in RuneAudio+R e6

### ISSUE THREAD

**Issue by pppov** [CDrummond/cantata#1651]
I can save playlists in RuneAudio+R e6 in the WebUi, but I cannot save playlists in Cantata.

Also, playlists saved in RuneAudio+R e6 WebUi do not show up in Cantata.
![Screenshot from 2020-11-15 16-49-09](https://user-images.githubusercontent.com/18084725/99189671-9b41ef80-2762-11eb-8dee-2c8ec9cb9335.png)

See screenshot.
 - OS: [Ubuntu 20.04]
 - Cantata Version: [2.4.2]

**Comment by CDrummond** [comment]
Playlists are saved by MPD - Cantata just sents the command. I have confirmed and playlist saving **does** work. Sorry, but I have no time to debug issues on user's systems - I no longer use Cantata nor MPD.
