### ISSUE TITLE
NTFS? "&" character in file path

### ISSUE THREAD

**Issue by Mr-Figs** [CDrummond/cantata#1655]
**Description**
I imported a few new albums, none of which would play in Cantata. They showed up properly—one didn't have album art and was sorted wrong, but otherwise normal—but wouldn't play or queue. The audio files were in a folder containing the "&" character, and removing the character fixed all issues.

The albums could be played via mpc before applying this workaround, so mpd itself is not at fault here. Other music players (non-mpd) had no issues. The files are stored on a drive formatted NTFS.

I haven't tried other characters besides "&", nor have I tried on other filesystems. I would attach a log, but the `--debug` options did not work.

**To Reproduce**
1. Create a new folder within library, or choose one to edit
2. Add the "&" character to the chosen directory's name
3. Refresh database (or `mpc update`)

**Expected behavior**
Files play as normal regardless of path name.

**Version Info**
 - OS: Kubuntu 20.10
 - Cantata Version: 2.4.1
 - MPD Version: 0.21.22
 - CMake options (other than default): [unsure, installed from repo]

**Comment by CDrummond** [comment]
Just tired and it works fine for me - but this is on an ext4 partition, not ntfs. But, the file list comes from MPD, so I see no reason why it should not work. To play track all Cantata does is pass back the filename given to it by MPD - it does not play the files itself. Cover fetching, maybe as Cantata reads them directly (if setup correctly) so an NTFS encoding issue could cause problems.

`--debug` **does** work. If its not working for you, then its probably an issue with your build.

Can you try on an ext4 partition?

**Comment by Mr-Figs** [comment]
Sorry—turns out this issue isn't as reproducible as I had assumed. Even on ntfs, even in my real library with the exact filenames that triggered it initially, I can't get it to happen again.

When the issue occurred, deleting mpd's `tag_cache` had no effect, so it was persistent and Cantata-related. But if it's not reproducible, there's no point trying to troubleshoot.

Again, apologies for the nuisance issue. Should have done my homework first, before filing a report ;-)
