### ISSUE TITLE
Player crashes on launch

### ISSUE THREAD

**Issue by thasharath** [CDrummond/cantata#1657]
Getting this on the terminal

```
/usr/lib/libc.so.6 : ()+0x3d6a0
/usr/lib/libQt5Sql.so.5 : QSqlDatabase::QSqlDatabase(QSqlDatabase const&)+0
cantata : LibraryDb::insertSong(Song const&)+0x9b5
cantata : LibraryDb::insertSongs(QList<Song>*)+0x80
/usr/lib/libQt5Core.so.5 : QObject::event(QEvent*)+0x292
/usr/lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x82
/usr/lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x12a
/usr/lib/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x173
/usr/lib/libQt5Core.so.5 : ()+0x30d304
/usr/lib/libglib-2.0.so.0 : g_main_context_dispatch()+0x184
/usr/lib/libglib-2.0.so.0 : ()+0xa67d1
/usr/lib/libglib-2.0.so.0 : g_main_context_iteration()+0x31
/usr/lib/libQt5Core.so.5 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x61
/usr/lib/libQt5Core.so.5 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x12c
/usr/lib/libQt5Core.so.5 : QCoreApplication::exec()+0x94
```

Arch Linux
Kernel Version: 5.4.78-1-lts
Qt Version: 5.15.1
KDE Plasma Version: 5.20.3

**Comment by CDrummond** [comment]
Sorry, but works for me and others. As its crashing in QSqlDatabase looks like an issue there. You did not even specify Cantata version.

**Comment by CDrummond** [comment]
Looks like a duplicate of https://github.com/CDrummond/cantata/issues/793

**Comment by mathieujobin** [comment]
could this be an incompatibility with Qt 5.15 ?

**Comment by CDrummond** [comment]
@mathieujobin Honestly no idea. My build machine is Ubuntu 20.04 on Qt 5.12

Do you have this crash? Does this change help? All it should do is stop the crash, but Cantata will not work without SQLite.

**Comment by thasharath** [comment]
I am sorry for not replying soon. The version of cantata I tried is 2.4.2-1
I don't have much knowledge in programming. It seems like an incompatibility issue with Qt. I'll see what I can do to fix it.

**Comment by mathieujobin** [comment]
@thasharath Qt 5.15 is quite a Major update.
it should land in Ubuntu 21.04 next April
I think you are a little bit too much bleeding edge for the rest of us

I'm on Kubuntu 20.10 with Qt 5.14.2
and Cantata works fine

**Comment by thasharath** [comment]
Thank you for the responses.
