### ISSUE TITLE
Very loud noise when using Playback > Replay gain

### ISSUE THREAD

**Issue by hrvoj3e** [CDrummond/cantata#1658]
**Describe the bug**
Very loud noise when playing `opus` files.
`opus` files have been created with `youtube-dl` (if that matters).

Same settings with same files worked a month ago.
Not sure what changed - I have reinstalled my machine - but used same OS and DE and `.config/`.

I can understand that this is probably not a bug in Cantata but in MPD but would like to have a response if Cantata somehow affects MPD settings when playing.

**To Reproduce**
Setting `Playback > Replay gain > Track`

**Expected behavior**
Play without noise.

**Can be solved with**
Setting `Playback > Replay gain > None`

**Version Info**
 - OS: Manjaro 20.2 Nibia x86_64 Linux 5.9.11-3-MANJARO
 - Cantata Version: 2.4.2-1 (arch community repo)
 - MPD Version: 0.22.3-1 (arch extra repo)

**Additional context**
Maybe connected to this [issue on MPD](https://github.com/MusicPlayerDaemon/MPD/issues/542)

**Comment by CDrummond** [comment]
Cantata does not playback files, it onlky asks MPD to do so. Any such issues are with MPD.
