### ISSUE TITLE
Cannot connect back and forth between various mpds

### ISSUE THREAD

**Issue by synthnassizer** [CDrummond/cantata#1659]
**NOTE** Cantata is now in a bug-fix only state. Therefore feature requests will usually be rejected. Pull requests, however, will still be accepted - so, if you desire a new feature this would be the route required.
---
---

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to find a specific song in the current playlist. I would like to have a "Ctrl+F" like functionality but dedicated to the songs loaded in the current playlist (RHS in Cantata)

**Describe the solution you'd like**
I want to Search for songs that are already loaded in the current playlist. If a match is found , it should be selected and the current playlist should be scrolled to bring it in focus. Perhaps a couple of "previous"/"next" buttons could also help navigate to the previous/next match.

**Describe alternatives you've considered**
I temporarily store the current playlist, then I can close-reopen Cantata, bring that playlist in focus in the LHS and do a "Ctrl+F" there.

**Comment by CDrummond** [comment]
Use `Ctrl+Shift+F` - or focus the queue and `Ctrl+F` -- there is a config setting to control this.

And the title of thi bug report has nothing to do with the contents!
