### ISSUE TITLE
No audio with remote server added.

### ISSUE THREAD

**Issue by Magicrafter13** [CDrummond/cantata#1660]
**Describe the bug**
When setup 'basic' through the wizard, Cantata plays local files fine, but as soon as I add my mpd server on my local network all playback is silent. Even local files are no longer audible.  
That aside, there doesn't appear to be any other issue. The progress bar continues moving as if the music is playing.

**To Reproduce**
Outlined above. Also happens if you select 'standard' when running the setup wizard.

**Expected behavior**
*Expect to be able to hear my music*

**Version Info**
 - OS: Manjaro Linux
 - Cantata Version: 2.4.2-1
 - MPD Version: 0.22.3
 - CMake options (other than default): n/a - installed via `pacman`

**Additional context**
The mpd server is running on an Ubuntu 20.04 server (this is where all my music is stored).

**Comment by CDrummond** [comment]
MPD plays audio, not Cantata.

**Comment by Magicrafter13** [comment]
Oh...

So I can't use Cantata to listen to a remote library then (aside from playing the files through a samba share or something of the sort of course)?

**Comment by Thaodan** [comment]
You can but you have to use a http stream [1]

Add a new collection and set the http-stream URL and set locale play http-
stream.

---

[1] https://wiki.archlinux.org/index.php/Music_Player_Daemon/
Tips_and_tricks#Configuration
