### ISSUE TITLE
Last.fm authentication Error/Failure

### ISSUE THREAD

**Issue by mojolo** [CDrummond/cantata#1661]
First of all, thank you for creating and continuing to maintain this great app!

**Describe the bug**
Scrobbling does not function since last.fm is unable to authenticate.

**To Reproduce**

In the scrobbler settings, i enter my username and password and click "Login". Instead of being logged in, I receive the following error and the status remains "Not Authenticated".

"Last.fm error: Invalid method signature supplied"

**Screenshots**

![cantata-lastfm](https://user-images.githubusercontent.com/46645666/103471081-4406d700-4d30-11eb-8f24-614d448ecc65.png)
Note: Username and Password obviously removed from screenshot

**Version Info**
 - OS: Kubuntu 20.04
 - Cantata Version: The same error occurred using the following 2 versions:
    1) v2.4.2 installed from the ubuntuhandbook ppa: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata-qt
    2) Personal build from source on 2021-01-01
 - MPD Version: 0.21.20 (installed from official ubuntu repo)
 - KDE Frameworks: 5.68.0
 - Qt Version: 5.12.8
 - CMake options (other than default):

**Additional context**

Thanks for your help!

**Comment by mojolo** [comment]
I compiled a debug build of cantata and launched with the following command:

`$ cantata --debug network-access,scrobbler`

Here are the relevant debug events in the console:

```
2021-01-02 20:11:29 - Scrobbler mpdStateUpdated false 2 2
2021-01-02 20:11:30 - Scrobbler setDetails details changed
2021-01-02 20:11:30 - Scrobbler saveCache "/home/XXXX/.cache/cantata/scrobbling/tracks.xml.gz" 0 0
2021-01-02 20:11:30 - Scrobbler loadCache "/home/XXXX/.cache/cantata/scrobbling/tracks.xml.gz" 0
2021-01-02 20:11:30 - Scrobbler format "api_key=XXXXXXXXX&api_sig=XXXXXXXXXXX&method=auth.getMobileSession&password=XXXXX&username=XXXXX"
2021-01-02 20:11:30 - NetworkAccessManager postFormData "https://ws.audioscrobbler.com/2.0/" true 145
2021-01-02 20:11:30 - Scrobbler authenticate "https://ws.audioscrobbler.com/2.0/"
2021-01-02 20:11:30 - Scrobbler authResp "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<lfm status=\"failed\">\n  <error code=\"13\">Invalid method signature supplied</error>\n</lfm>\n"
2021-01-02 20:11:30 - Scrobbler authResp authenticated: false
2021-01-02 20:11:34 - Scrobbler mpdStateUpdated false 2 2
```

**Comment by mojolo** [comment]
so it seems this project is officially on its last legs as it's one of the only music players without basic scrobbling support.

**Comment by a-mair** [comment]
I'm using cantata (git build December, 1st 2020) on two Gentoo Linux PCs and both are still able to scrobble. So I really wonder why you think authentication doesn't work any longer. Where's the information that last.fm changed authentication?

**Comment by CDrummond** [comment]
@a-mair is the directed at me or @mojolo ? I have no last.fm account, never used it. If you say it works then I'll re-enable. I no longer use Cantata nor MPD, hence Cantata is in a bug-fix only state - and I have no time to re-write any new auth mechanism. Hence why I removed the last.fm code thinbking it was broken.

**Comment by a-mair** [comment]
sorry, I meant both of you but if you don't use cantata any longer I'd direct the questions at @mojolo

**Comment by CDrummond** [comment]
@a-mair Cantata stores a 'session key' to log into lastm.fm - this is saved into cantata's config file. If you have not logged out, and this has not expired, then it will use that. My guess is your session key is still valid, hence scrobbling still works. But, if you were to remove 'sessionKey' from Cantata's config file (~/.config/cantata/cantata.conf) restart Cantata, my guess is log-in to last.fm would fail.

p.s. I stopped actively using Cantata around 4 years ago!

**Comment by a-mair** [comment]
@CDrummond 
Cantata stopped, sessionKey removed, Canata started and logged in in Cantata settings:
> 2021-01-12 11:23:29 - Scrobbler format "api_key=...&api_sig=...&method=auth.getMobileSession&password=...&username=..."
> 2021-01-12 11:23:29 - NetworkAccessManager postFormData "https://ws.audioscrobbler.com/2.0/" true 184
> 2021-01-12 11:23:29 - Scrobbler authenticate "https://ws.audioscrobbler.com/2.0/"
> 2021-01-12 11:23:29 - Scrobbler authResp "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<lfm status=\"ok\">\n  <session>\n    <name>amair</name>\n    <key>...</key>\n    <subscriber>0</subscriber>\n  </session>\n</lfm>\n"
> 2021-01-12 11:23:29 - Scrobbler authResp authenticated: true

Cantata tells me "Status: Authentifiziert" (German locale).

**Comment by CDrummond** [comment]
@a-mair  Thanks. Perhaps it still works then. Odd. I'll re-enable the feature.
