### ISSUE TITLE
duration not reported in playlist for final album track from a cuesheet source

### ISSUE THREAD

**Issue by twojstaryzdomu** [CDrummond/cantata#1662]
**Describe the bug**
Cantata fails to report duration for any final album track when the music source is a single audio file with an accompanying cuesheet (external to the audio file).

Albums with individual files for each track are ok and display the correct duration for the final tracks.

Playing back a final album track, the right length is displayed in the player section, whereas the duration seen in the playlist stays empty. The duration track details when hovering over a final track are conspiciously missing. Re-ordering the playlist list does not update the duration details. Note the final album track does not necessarily need to be the final track in the playlist. The bug is also apparent when it is the only track added to the playlist.

The missing duration is not included in total album runtime calculation either.

To Reproduce**
1. Find an album with a single audio file and a cuesheet in the audio Library.
2. Add the entire album to the playlist or just the final track.
3. Review the duration of the final track, hover over it to see the tag details
4. No track duration is reported for any final track

**Expected behavior**
Report proper track duration for all the tracks of an album and the correct duration for an entire album.

**Screenshots**

**Version Info**
 - OS: Linux, openSuSE 15.2
 - Cantata Version: 2.4.3, git release
 - MPD Version: 0.22.3
 - CMake options (other than default): ENABLE_REMOTE_DEVICES=OFF ENABLE_CATEGORIZED_VIEW=OFF CMAKE_INSTALL_DO_STRIP:BOOL=ON

**Additional context**

**Comment by CDrummond** [comment]
Durations in the queue come from MPD

**Comment by twojstaryzdomu** [comment]
I have to agree to the statement. 

Whilst duration isn't strictly reported in the range response for the cuesheet, it is reported elsewhere for the audio file. 

Cantata seem to have some clever logic to ensure the cuesheet data and the audio file do not result in two entities, a single album-length track and a proper album carved up into individual track. 

Would it be too much to ask to have cantata collect the lsinfo derived (duration: or Time:) from the audio file before discarding it and using it to furnish the missing time end range value for the cuesheet?

**Comment by CDrummond** [comment]
This issue needs fixing in MPD, so that it works for all clients, not worked-around in Cantata.

New MPD's support listing CUE file contents, so it might already be resolved.
