### ISSUE TITLE
Label issues according to their intention and state

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1663]
**Is your feature request related to a problem? Please describe.**
Issues are often duplicated a cross the project and create additional work on all contributors and you.

**Describe the solution you'd like**
We should label issues that are:
+ Issues that are not caused/related to Cantata but mpd
+ Duplicates on existing issues 
+ Bug or feature request

Also it would be helpful to instruct users to especially look for these label before creating an issue.

**Comment by CDrummond** [comment]
Whilst I understand and agree wth this, I have really no time to go through old issues and add tags. Where issues are duplicates I do mark as so, but adding a tag I do not think will add much. Users should search for existing reports, even closed ones, before creating issues. If an issue is found, it being marked as a duplicate will not add much.

Features are no longer being implemented, and users are informed of this. Any feature requests are closed with 'wontfix'

**Comment by Thaodan** [comment]
>Whilst I understand and agree wth this, I have 
really no time to go through old issues and add tags.
If you want help, I can help you on this.

Maybe do that for newly created issues if you don't 
want help.

**Comment by CDrummond** [comment]
Its not so much that I don't want, or appreciate help, its just that I no longer use this software - so its very much on life support, and my time/enthusiasm for this is in very short supply.
