### ISSUE TITLE
Cantata adds numbers to song titles

### ISSUE THREAD

**Issue by officernice** [CDrummond/cantata#1664]
Hello there. First off, thank you for this amazing music player. It's my #1 choice! :) 

I've run into this problem with tracks that has the percentage symbol % in the title where it always adds 25 to it.
So songs like ...
100% Gangstaz >> 100%25 Gangstaz
#%!@ mig nu >> #%25!@ mig nu

I've tried putting such songs into all kinds of players but it only happens in Cantata. :(

OS: Arch Linux
Cantata V: 2.4.2-1

**Comment by CDrummond** [comment]
Sorry, but this is an issue on your system. I created 2 test MP3 files with those strings, and this works perfectly:

![Screenshot from 2021-01-14 19-01-10](https://user-images.githubusercontent.com/1141694/104636272-02b0e880-569b-11eb-909d-4411c7406d34.png)

**Comment by CDrummond** [comment]
...ah! You are adding files via drag'n'drop? I see the issue with that.

**Comment by officernice** [comment]
> ...ah! You are adding files via drag'n'drop? I see the issue with that.

Yeah I use drag'n'drop or well.. Click and it magically appears in Cantata. :) Doesn't occur in other players.

**Comment by officernice** [comment]
> ...ah! You are adding files via drag'n'drop? I see the issue with that.

What is the issue? Cantata didn't always do it.
