### ISSUE TITLE
Update mpd database on specified directory

### ISSUE THREAD

**Issue by xuijuthub** [CDrummond/cantata#1666]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Bigger mpd db update takes 20+ minutes. Though only adding few albums at a time.

>**Describe the solution you'd like**
>A clear and concise description of what you want to happen.

In server folders view right clicking a folder would have extra option that would say update folder
it would issue mpc update "$DIR" command

>**Describe alternatives you've considered**
>A clear and concise description of any alternative solutions or features you've considered.

$ mpc update path/music/dir in terminal

>**Additional context**
>Add any other context or screenshots about the feature request here.

CDrummond, I do not demand or expect you to implement this feature. But it would be great to keep it open so that any possible future contributors would see it.

**Comment by CDrummond** [comment]
Feature requests are not being implemented as you know, and I have no intention of leaving things open. `wontfix` issues are how I mark features that I have no time to implement.
