### ISSUE TITLE
Exporting playlists

### ISSUE THREAD

**Issue by officernice** [CDrummond/cantata#1668]
I saw an earlier post from 2015 where exporting a playlist was not featured. Is that still the case? That would be quite odd, and suck a bit. Absolutely love this player but I have a playlist of 326 tracks, needless to say I'd rather not re-do it again.
There is nothing in my MPD directory or Cantata. Wouldn't it be possible to just export to .m3u like in Audacious?

Another thing about the playlists. Sometimes when I open Cantata it'll say Playlist  tracks (example) and then it lasts for 0:00 minutes, and doesn't show album covers. My music is not on the same drive as Cantata but is pointed towards it in the settings. If I add a track to a playlist it suddenly updates.

OS: Arch Linux
Cantata: 2.4.2-1
MPD: 0.22.4-1

**Comment by CDrummond** [comment]
As you are aware when openning this, features are NOT being implemented.
