### ISSUE TITLE
devices -identified but Not Connected

### ISSUE THREAD

**Issue by anarchotaoist** [CDrummond/cantata#1669]
Hi Craig

**Describe the bug**
Device category: device registers as present but does not bring up the music library on the phone.
There is no connection either by right clicking and sending to device.

**To Reproduce**
Load Cantata and plug in Android phone
or
Plug in phone and load Cantata
Click on devices
Get phone icon and correct identity of phone displayed 
and message Not Connected

 See error
Open Cantata in Konsole:

Device 0 (VID=18d1 and PID=4ee2) is a Google Inc Nexus/Pixel (MTP+ADB).
error returned by libusb_claim_interface() = -6LIBMTP PANIC: Unable to initialize device

**Version Info**
Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-40-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
 - Cantata Version: 2.4.1

**Additional context**
Connection appears to work fine without android-sdk-platform-tools-common installed
but uninstalling android-sdk-platform-tools-common breaks MTP connection in Dolphin file manager.

**Comment by CDrummond** [comment]
```
 error returned by libusb_claim_interface() = -6LIBMTP PANIC: Unable to initialize device
```

Looks like an MTP issue to me. I have not touched Cantata's MTP code in years. If it works without `android-sdk-platform-tools-common` then perhaps the issue is there? Looks like something has already connected to the device, so Cantata's connection fails.

Must admit MTP is awful, so I'd suggest using other methods.

**Comment by CDrummond** [comment]
Lots of issues reported about this on libmtp site - e.g. https://sourceforge.net/p/libmtp/bugs/1868/

**Comment by anarchotaoist** [comment]
ok, thanks.

**Comment by anarchotaoist** [comment]
> Looks like something has already connected to the device

Update FYI

It would seem Dolphin (or Plasma) does not like to share mtp with more than one application.
Cantata can use mtp no problem if I close out Dolphin, reboot then open Cantata. If Cantata has mtp control I then need to close Cantata and reboot in order to have connection with Dolphin. Opening Gwenview for photos is affected also.
Unlike plugged in usb devices their is no option to unmount mtp in Plasma - well, no GUI way,
I have placed a bug report with KDE as this looks to be an issue for Plasma and not Cantata.

Thanks again for looking at the issue Craig! Hopefully KDE sort it out!

**Comment by vermeeren** [comment]
@anarchotaoist Could you post the link to the issue you have reported?
