### ISSUE TITLE
Crash with Plasma 5.21 Beta (5.20.90)

### ISSUE THREAD

**Issue by tilgovi** [CDrummond/cantata#1670]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
Under the latest Plasma, Cantata crashes with a traceback from Qt.

``` shell-session
❯ cantata          
QWidget::repaint: Recursive repaint detected
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x41770
  /lib/x86_64-linux-gnu/libQt5Gui.so.5 : ()+0xefe24
  /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/breeze.so : ()+0x45f1b
  /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/breeze.so : ()+0x54ca0
  cantata : ProxyStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const+0x4e
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QWidgetPrivate::paintBackground(QPainter*, QRegion const&, QFlags<QWidgetPrivate::DrawWidgetFlag>) const+0x1f9
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)+0xf7b
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : ()+0x17cada
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : ()+0x17d31b
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : ()+0x1c8c1f
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x83
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x12a
  /lib/x86_64-linux-gnu/libQt5Gui.so.5 : QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*)+0x91
  /lib/x86_64-linux-gnu/libQt5Gui.so.5 : QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0xac
  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 : ()+0x6fe7e
```

**To Reproduce**
1. Start Cantata

**Expected behavior**
Cantata starts :).

**Version Info**
 - OS: Ubuntu Linux 21.04
 - Qt: 5.12.2
 - Plasma: 5.20.90
 - Cantata Version: 2.4.2

**Additional context**
I understand that I'm working with beta framework releases, and that I haven't compiled this myself, but in case the traceback made sense to those more familiar, I figured I should report it here. I initially suspected that maybe packages hadn't finished uploading to the Ubuntu archives and that I had a version mismatch, but I've checked as much as I could and don't see anything like that, and I haven't experienced similar issues with any other applications. I'll take this downstream if it seems inapplicable, but in case it's early warning I'm here to do my part as a user of beta stuff and let maintainers know about issues I encounter! :smile:

Please let me know if there's any other info I can provide.

**Comment by CDrummond** [comment]
Does Cantata crash if you use any style other than breeze? e.g. Fusion?

Looking at Cantata's `ProxyStyle::drawPrimitive(...)` the **first** thing it does is call the base style (in this case Breeze). I assume its this call into Breeze that is crashing. There is nothing Cantata can change in that line.

**Comment by tilgovi** [comment]
Yeah, working fine with other application styles. I'll close for now and look about for reports to breeze itself. If I find anything that I should raise up over here I'll post back. Sorry for the noise.
