### ISSUE TITLE
Cantata crashes with breeze 5.20.90

### ISSUE THREAD

**Issue by Mel34** [CDrummond/cantata#1672]
**Describe the bug**
Cantata crashes on launch with breeze 5.20.90
**To Reproduce**
1. install KDE beta
2. make sure breeze is QT style
3. launch cantata
4. error as seen in terminal:
```
~ ▶ cantata
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /usr/lib/libc.so.6 : ()+0x3d6a0
  /usr/lib/libQt5Gui.so.5 : ()+0xe7640
  /usr/lib/qt/plugins/styles/breeze.so : ()+0x41bd8
  /usr/lib/qt/plugins/styles/breeze.so : ()+0x50be1
  cantata : ProxyStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const+0x4b
  /usr/lib/libQt5Widgets.so.5 : QWidgetPrivate::paintBackground(QPainter*, QRegion const&, QFlags<QWidgetPrivate::DrawWidgetFlag>) const+0x205
  /usr/lib/libQt5Widgets.so.5 : QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*)+0xfd5
  /usr/lib/libQt5Widgets.so.5 : ()+0x16b31c
  /usr/lib/libQt5Widgets.so.5 : ()+0x16bb8e
  /usr/lib/libQt5Widgets.so.5 : ()+0x1b78e9
  /usr/lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x82
  /usr/lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x12a
  /usr/lib/libQt5Gui.so.5 : QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*)+0x90
  /usr/lib/libQt5Gui.so.5 : QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0xb5
  /usr/lib/libQt5XcbQpa.so.5 : ()+0x5f16c
```
**Expected behavior**
Cantata window appears normally
**Screenshots**
N/A

**Version Info**
 - OS: Linux (archlinux)
 - Cantata Version: 2.4.2-1
 - MPD Version: N/A
 - CMake options (other than default): N/A

**Additional context**
I've also rebuilt cantata from master with the breeze 5.20.90 libs in hopes it would help, but it still crashes.
I've ran distro packaged cantata successfully with `QT_STYLE_OVERRIDE=fusion cantata`
PS:
I am aware this is beta quality software on the KDE side, consider this an early heads up for incoming breakage.

**Comment by tmtvl** [comment]
Yeah, it's already been addressed: at #1670

**Comment by Mel34** [comment]
Ok, closing then and will reoppen on KDE side. Thanks!

**Comment by Mel34** [comment]
Filed as https://bugs.kde.org/show_bug.cgi?id=432246
