### ISSUE TITLE
Error: "ASSERT: "block.firstIndex.isValid()" in file /build/cantata/src/cantata-2.4.2/3rdparty/kcategorizedview/kcategorizedview.cpp, line 569:

### ISSUE THREAD

**Issue by falstaff1288** [CDrummond/cantata#1673]
**Describe the bug**
Cantata crash a couple of second after being opened.

**To Reproduce**
1. Open Cantata
2. Wait
3. Watch it close

**Version Info**
 - OS: Linux (Distribution: ArchLinux)
 - Cantata Version: 2.4.2-1
 - MPD Version: Music Player Daemon 0.22.3 (0.22.3)
 - CMake options (other than default):

**Additional context**
Error message that I get when opening the app from the command line:
```
ASSERT: "block.firstIndex.isValid()" in file /build/cantata/src/cantata-2.4.2/3rdparty/kcategorizedview/kcategorizedview.cpp, line 569
Aborted (core dumped)
```

**Comment by CDrummond** [comment]
For the next release (2.4.3) Categorized view is disabled as it already has a crash report against it - #1530
