### ISSUE TITLE
Can not start cantata first time over X11 forwarding

### ISSUE THREAD

**Issue by AndriiZ** [CDrummond/cantata#1675]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
First time launch works only on desktop environment, running Cantata over X11 forwarding does not work

**To Reproduce**
1. Install Cantata 2.4+
2. Setup X11 forwarding
3. Run Cantata using ssh
4. Nothing happens

Workaround:
1. rdp to remote host
2. run Cantata from desktop and complete wizard
3. run Cantata over X11 forwarding - works!

**Version Info**
 - OS: host Ubuntu 18.04, client Windows 10, XServer vcxSrv
 - Cantata Version: 2.4.0
 - MPD Version: 0.22.4

**Additional context**

**Comment by CDrummond** [comment]
Just tried: `ssh -X localhost /path/to/cantata` and the startup screen was shown. So, Cantata works - issue is on your system.
