### ISSUE TITLE
File is not open with utf8 chars

### ISSUE THREAD

**Issue by pprchal** [CDrummond/cantata#1676]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
Cannot open file from samba-mounted folder.
There is no error on mount, vlc player works fine

**To Reproduce**
Maybe to open file with some utf-8  (ěščřž)

**Expected behavior**
OGG file should be played

**Screenshots**
![image](https://user-images.githubusercontent.com/2689929/107792351-532c6c00-6d55-11eb-9d6f-c60260882d79.png)

Looks like there is wrong url encoding - maybe

**Version Info**
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.15-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3 CPU M 350 @ 2.27GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics

Cantata 2.4.2

**Additional context**

**Comment by CDrummond** [comment]
Any chance you can checkout the code from git an re-try? I think this is an encoding issue like https://github.com/CDrummond/cantata/issues/1664 - and if so its already fixed.

**Comment by pprchal** [comment]
> Any chance you can checkout the code from git an re-try? I think this is an encoding issue like #1664 - and if so its already fixed.

Sorry, but I run it on old notebook - for audio only(small ssd without gcc)
But I will try to figure out more info and dig into #1664 
Is there any --verbose mode?

And my idea: try to add some unit-tests with uri open (ěščř.ogg)

**Comment by CDrummond** [comment]
I will try creating a path with utf8 chars, and infact I already have "Queensrÿche" - but I'm 100% Linux so have no Samba mounts to test with.

**Comment by tmtvl** [comment]
Can confirm that Linux-local files with UTF-8 paths load correctly on Cantata 2.4.2. I'll try it with a Samba mount if I can get Samba working correctly.

**Comment by CDrummond** [comment]
Well, if local giles are working, then the issue would be elsewhere and not in Cantata.

**Comment by pprchal** [comment]
So drag drop - as mentioned in #1664 works.

Samba is not the problem, trying to open file from desktop (local drive)
Encoded output also looks good.

![image](https://user-images.githubusercontent.com/2689929/107982044-a3a90100-6fc3-11eb-9c23-2874b904b662.png)

**Comment by CDrummond** [comment]
@pprchal So, d'n'd from outside Cantata works, but adding from folder view fails?

**Comment by CDrummond** [comment]
Just tried with `~/tmp/ěščř/ěščř.mp3` And playing this via adding from 'Home' folder view worked just fine. Perhaps its an NTFS issue?

**Comment by CDrummond** [comment]
@pprchal If you create `~/tmp/ěščř/ěščř.mp3` does it also work for you? I cannot fix an issue I cannot recreate.

**Comment by pprchal** [comment]
hmm.. this is so weird. If you can open it...

Maybe some bug in manjaro package?
Or what do you have in **metadata** of mp3?
Try ěščřžý..

![image](https://user-images.githubusercontent.com/2689929/109330850-6ca4dc00-785c-11eb-803c-8d6bc482bbff.png)

**Comment by CDrummond** [comment]
@pprchal **How** are you loading the track? Drag'n'drop from outside of Cantata (e.g. from Dolphin)? Drag'n'drop from **within** Cantata (e.g. from 'Home foder')? By pressing play (>) or add (+) button in Cantata's folder view?? And yes, I have UTF8 tags (used same strings).

**Comment by CDrummond** [comment]
As stated, I cannot recreate this. I asked for more info, no more details give. Closing.
