### ISSUE TITLE
Global keys

### ISSUE THREAD

**Issue by peter099** [CDrummond/cantata#1679]
It will be great if there is option to setup global keyboard shortcuts for controling the player.

**Comment by tmtvl** [comment]
The KDE multimedia controls should work for Cantata. Don't they work for you?

**Comment by CDrummond** [comment]
As you were made aware when opening this report, features are not being implemented.

**Comment by peter099** [comment]
I am using MX Linux with XFCE desktop. Don't see options for multi media controls.

I am sorry to hear features are not been implemented. This is the best music player for linux i found, and i have tried all.

**Comment by CDrummond** [comment]
Cantata supports gnome's media keys dbus daemon. So, if XFCE supports something similar it will work there, if not, then no.

**Comment by vermeeren** [comment]
@peter099 It's up to the desktop environment to provide this integration.

As it's just MPRIS over session D-Bus you can also things like `playerctl`, packaged in most distros. https://github.com/altdesktop/playerctl

If everything else fails you can also call dbus directly. Use a tool like `qdbusviewer` to find all the methods available.

```sh
dbus-send \
	--dest=org.mpris.MediaPlayer2.cantata \
	--type=method_call /org/mpris/MediaPlayer2 \
	org.mpris.MediaPlayer2.Player.Play
```

**Comment by CDrummond** [comment]
You can also invoke many of Cantata's actions via DBUS. See "DBUS Actions" in https://raw.githubusercontent.com/CDrummond/cantata/master/README

**Comment by peter099** [comment]
> `playerctl`



> @peter099 It's up to the desktop environment to provide this integration.
> 
> As it's just MPRIS over session D-Bus you can also things like `playerctl`, packaged in most distros. https://github.com/altdesktop/playerctl
> 
> If everything else fails you can also call dbus directly. Use a tool like `qdbusviewer` to find all the methods available.
> 
> ```shell
> dbus-send \
> 	--dest=org.mpris.MediaPlayer2.cantata \
> 	--type=method_call /org/mpris/MediaPlayer2 \
> 	org.mpris.MediaPlayer2.Player.Play
> ```

Thanks, `playerctl` worked fine.
