### ISSUE TITLE
Lyrics plugins not working

### ISSUE THREAD

**Issue by peter099** [CDrummond/cantata#1680]
I have tried all available lyrics plugins, with different artist, and none of them is fetching any lyrics.

**Comment by CDrummond** [comment]
Jsut tried, and they do work. Not all - but that's becasue sites change. But, Lyrics fetching does work.

**Comment by beglort** [comment]
I have the same bug.
KDE Plasma 5.20.5; KDE Frameworks 5.79.0
After I deleted cantata files in .config .cache .local/share it worked just once. When I closed and reopened Cantata it didn't work anymore, even if I manually create lyrics files in the proper directory.
This behaviour happens with an album but not with another single I have, maybe it's some conflicts with the files metadata? 
I also tried to un-check the box "fetch missing covers" but the result was the same: the plugin works just at first launch.

**Comment by beglort** [comment]
I have the same bug.
KDE Plasma 5.20.5; KDE Frameworks 5.79.0
After I deleted cantata files in .config .cache .local/share it worked just once. When I closed and reopened Cantata it didn't work anymore, even if I manually create lyrics files in the proper directory.
This behaviour happens with an album but not with another single I have, maybe it's some conflicts with the files metadata? 
I also tried to un-check the box "fetch missing covers" but the result was the same: the plugin works just at first launch.

**Comment by beglort** [comment]
> I have tried all available lyrics plugins, with different artist, and none of them is fetching any lyrics.

I had the same problem, but as you can see in my comment above it happened just with some tracks. 
I suggest you to download a Music tagger (i.e. Picard) and check/correct the metadata of your music. In my case the lyrics tag was already edited with some symbols. Probably this prevent the Cantata plugin to fetch or edit the lyrics section. After I cleared the lyrics section and other sections with unreadable characters the plugin works again.
