### ISSUE TITLE
Support smaller screens

### ISSUE THREAD

**Issue by fenuks** [CDrummond/cantata#1682]
**Is your feature request related to a problem? Please describe.**
I wanted to use cantata on PinePhone, but unfortunately it doesn't work well. Initial wizard window is too large, it doesn't fit on the screen. I couldn't go through it, because buttons are off the screen, and I cannot resize window, nor scroll it.

**Describe the solution you'd like**
Make cantata GUI adapts to smaller screens. I've been playing a bit with this idea, but I'm not very familiar with Qt. After removing `setMinimumSize` calls, wizard window can be made smaller a bit, but not enough to be able to fit PinePhone screen.

**Describe alternatives you've considered**
Trying other Linux MPD clients.

**Additional context**
PinePhone screen resolution is 1440x720, 18:9, 274 DPI.

**Comment by CDrummond** [comment]
Sorry, but as you were made aware when opening this, I am no nolonger implementing new features for Cantata. I switch to LMS a few years ago.

The main UI will adapt for smaller screens, but the intro wizard and config UI will not - and altering these is a non-trivial amount of work.

**Comment by fenuks** [comment]
Yes, I knew that, and I understand your decision. I will further try to fix that (I could also create config file by hand, if main UI scales well, then it should be usable for me). Could you give me a hint why wizard window cannot be resided horizontally below what is seen on screen? 
![obraz](https://user-images.githubusercontent.com/1249829/108039243-c2df7700-7033-11eb-8a23-d32ba4740513.png)

I've removed all minimal size constraints (including ones in ui file).

**Comment by CDrummond** [comment]
I'd imagine is QWizard making space for all buttons. Even if you get this working, the settings dialog will be a **lot** of work.

Perhaps you should look into using LMS/SqueezeLite? This is what I have switched to, and have created a Material-themed skin which works on mobile and desktop. See https://github.com/CDrummond/lms-material

**Comment by fenuks** [comment]
Thank you, I never heard of LMS/SqueezeLite. I'll look into that, but I don't know if it will be suitable for me (I see that server is written in Perl; I run mpd on my router running OpenWRT, therefore server needs to be light on resources).

Even if tweaking cantata will require plenty of work, it's opportunity to learn something new. If main GUI works reasonably well, I suppose I could do all the configuration in text file, or connect phone to monitor (PinePhone ships with dock that has HDMI port, but I haven't tested it yet) to do all required configuration. I really like cantata, it's wonderful piece of software, and one of the most configurable music player. The fact it uses Qt is a nice bonus, because I use plasma mobile.
