### ISSUE TITLE
Playback continues after restart

### ISSUE THREAD

**Issue by fn-ix** [CDrummond/cantata#1685]
Even after checking 'Stop playback on exit' in the settings, the playback continues after closing and starting Cantata. Fiddling with the `restore_paused` setting in the mpd config didn't affect anything.

 - OS: Arch kernel 5.10.16-arch1-1
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.6

**Comment by CDrummond** [comment]
Does playback stop when closing? Or are you saying it continues?

**Comment by fn-ix** [comment]
It stops after closing, but when I start Cantata up again, it automatically starts playing where it previously left off with the play queue intact.

**Comment by CDrummond** [comment]
Is this with a standard MPD, or wit Cantata's own MPD? i.e. did you set up Cantata in Basic mode (where it starts/stops its own MPD instance), or is it controlling MPD system-wide or on another machine?

**Comment by fn-ix** [comment]
I'm using the basic mode with its own mpd instance.

**Comment by CDrummond** [comment]
Ah! This is standard MPD behaviour. You can set `restore_paused "yes"` in `~/.local/share/cantata/mps/mpd.conf` to prevent this for Basic mode. As this is standard behaviour, and others might want it this way, I cannot change. "Basic" is named that was as it only has basic features/config, even the initial settings wizard states that if you want non-standard config to not use this mode.

Sorry, software is working as designed.

**Comment by fn-ix** [comment]
You're right, that fixed it, thanks. One quick (off-topic) question: is it possible to change the double-click action from 'add to queue' to 'replace & play'? I used Cantata a couple of years ago and remember it having such an option in the settings...

**Comment by CDrummond** [comment]
Nope, sorry not possible to change - well there is no option for such, and I'm not adding new features.
