### ISSUE TITLE
Library disappear after cleaning the system with BleachBit

### ISSUE THREAD

**Issue by peter099** [CDrummond/cantata#1688]
Library disappear every time after i clean my system with BleachBit. After that if i try to refresh the database it doesn't import all audio files for some reason. I see that Cantata save art covers in .cache folder, which is not a good thing because this folder is cleaned  often, but library data is in .local/share. Any idea why this is happening with my library? I am using MX Linux.

**Comment by CDrummond** [comment]
Sorry, but this is an issue with BleachBlit removing stuff it should not.

Covers are **cached** hence in the cache folder - where they belong.

**Comment by peter099** [comment]
I get why it removes the covers, but why removes artists from the library? It should remove only the artists covers.
