### ISSUE TITLE
Image search is using only one provider

### ISSUE THREAD

**Issue by peter099** [CDrummond/cantata#1694]
When i search for artists cover art image search function is searching only one provider - Deezer, though all providers are enabled.

**Comment by CDrummond** [comment]
Update code to always search all providers. Removed Spotify and Google as they no longer work.

**Comment by peter099** [comment]
I am on MX Linux. How to update Cantata? The version i am using is 2.3.3.

**Comment by CDrummond** [comment]
There is no new release yet.
