### ISSUE TITLE
<br> in multiline file tags

### ISSUE THREAD

**Issue by ping-floyd** [CDrummond/cantata#1698]
Starting from 2.4, Cantata when displaying multiline tags in the "Metadata" side panel shows \<br> instead of new line and ignores the new line symbol.

To reproduce:
1. Play a track with embedded Lyrics tag.
2. Open Info—Track—Metadata in the side panel.

Expected behaviour:
Showing tag contents as is, with new lines where necessary.

Screenshots:
Bugged:
![Cantata bugged](https://user-images.githubusercontent.com/80914039/111800577-27188380-88dd-11eb-8363-ef3981060cb5.png)

Fixed:
![Cantata fixed](https://user-images.githubusercontent.com/80914039/111800580-2849b080-88dd-11eb-9b37-6265f9ddd99e.png)

Version info:
OS: Debian Bullseye/Sid
Cantata 2.4.2
MPD 0.22.6

Additinal info:
the possible culprit is the "createRow" in line 477 of context/songview.cpp
`static QString createRow(const QString &key, const QString &value, bool htmlEscape = true)`
And the quick and dirty solution is to change "htmlEscape" to "false". That fixes the issue and doesn't seems to break anything else — don't quote me on that however.

**Comment by CDrummond** [comment]
Thanks for the analysis. The HTML escaping is required due to another, obscure, issue. However, I think the escaping should be **before** replacing newlines with BR tag, not after. Which is what my fix does.

**Comment by ping-floyd** [comment]
> Thanks for the analysis. The HTML escaping is required due to another, obscure, issue. However, I think the escaping should be **before** replacing newlines with BR tag, not after. Which is what my fix does.

Thanks!
