### ISSUE TITLE
"Edit track information" only lets you rename your file to match your tags 

### ISSUE THREAD

**Issue by kiwifb** [CDrummond/cantata#1700]
When editing track information when you click save, a screen displaying "Would you also like to rename your song files, so as to match your tags?" with two choices "rename" or "cancel" is displayed. Effectively, if you just want to make a minute change to the tag without changing anything else, you cannot.
This is a bug, because when I hit "save" I expect to be able to, which is not the case right now.

**To Reproduce**
1. Select a track
2. right click on the track and select "edit track information"
3. change the artist name
4. click "save"
5. Two choice "rename" or "cancel" - effectively not "save"

**Expected behavior**
Two possibilities
1. plain "save" no new choice window.
2. New window with three choices "rename", "save as is" and "cancel" - although the last one is redundant and wouldn't be missed.

**Version Info**
 - OS: linux
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.3

**Comment by CDrummond** [comment]
Tags are saved. The dialog is askign your **also** like to rename.

**Comment by kiwifb** [comment]
Oh, I see, the change do not appear in any way in the interface or the tag editor before a database refresh. At least to me, but it seems to be immediate when "renaming".
