### ISSUE TITLE
Search for ratings

### ISSUE THREAD

**Issue by s7m0n** [CDrummond/cantata#1702]
Problem statement:
I'd like to search for for files based on the rating I've assigned. 

Solution proposal:
enable an additional search field (like artist, title, any) where one can input numbers representing the rating with comparataors <>=. Ideally it could be combined to with the other search options so i could search for genre:rock with rating:>3

Sorry to hear that Cantata is in bug-fix and this request is really more a feature request although it would be the part which makes ratings useful (besides this filter in dynamic playlist). And thanks for this great software!

**Comment by CDrummond** [comment]
Sory - but as you have noted, I'm not implemeting new features. Patches/pull equests welcom.
