### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by Marcool04** [CDrummond/cantata#1704]
New functionality was added for macOS in 730bf0672a4066cd60feccb2dcaf1e86cb1fd971, 93f5aebab90103a344afe40a6e28ec4c3727ead5, and 398474fa1b5bde176f1f5a5480983c0c4885b38d for instance, and the last tagged version is from Sep 9, 2020.

I'm trying to get a homebrew formula together to build Cantata "automatically" on macOS (currently there is a homebrew cask, but that uses the last .dmg which is from 2018). For this a tagged release is needed.

Do you feel it would make sense / be possible to create a new release tag at this point? I'd be grateful if you'd consider it in any case.
Thanks in advance.
Mark.

See also: discussion about homebrew cask/formula creation: https://github.com/Homebrew/discussions/discussions/1370

**Comment by CDrummond** [comment]
I will be releasing a new version soon, just not sure when. I no longer use Cantata, so its not a priority for me.

**Comment by Marcool04** [comment]
Sure I understand. No rush whatsoever. Very grateful for your continued maintenance. 👏

**Comment by kmontag** [comment]
Hi @CDrummond, just pinging re: a new release tag. There's now a PR up to add Cantata to homebrew core: https://github.com/Homebrew/homebrew-core/pull/86834. Would be great to include the more recent MacOS updates in the build (ideally including https://github.com/CDrummond/cantata/pull/1746 :) ).

It was also suggested that we could potentially contribute a GitHub CI workflow to automate Cantata `.dmg` builds. Would you consider accepting such a workflow and including the `.dmg` in releases? Then we wouldn't have to migrate Cantata from `homebrew-cask` to `homebrew-core`.

**Comment by kmontag** [comment]
Thanks @CDrummond! Appreciate you keeping up with this sort of stuff after the project is out of active development. Hopefully https://github.com/CDrummond/cantata/pull/1747 is sufficiently low-maintenance :)

**Comment by vermeeren** [comment]
@CDrummond Would it be possible to tag and release a version soon-ish? As Windows/MacOS etc are (afaik) no longer built/released formally I believe this is just the tarball. Distros are still in 2.4.2 and there are a lot of really nice changes and fixes made in the past 1.5 year.

Cheers for still maintaining this!
