### ISSUE TITLE
Cannot copy to device

### ISSUE THREAD

**Issue by realSConway** [CDrummond/cantata#1705]
Hello experts,

Recently started using Cantata to manage music between mpd and my device (mp3 player). 
Playing,  downloading podcasts and play everything works.

However I'm not able to copy tracks to my device, it is plugged in and I see under devices; showing 31.9Gb free.
The option to copy to device is grayed out when selecting tracks from either podcasts, playlist or library.

What am I doing wrong/did not configure.

**To Reproduce**
1. Go to library/playlist or podcast
2. Right-click on a track
3. Attempt to click on copy to device
4. Nothing happens

**Expected behavior**
Track is copied to device

**Version Info**
 - OS: Opensuse tumbleweed
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.6

**Comment by CDrummond** [comment]
If  'Copy to device' is greyed out it implies Cantata cannot access the MPD folder where your music is stored.

MPD only informs clients of the relative music path. e.g. If you have `/var/lib/mpd/music/Artist/Album/Track.mp3` and MPD's `music_directory` is set to `/var/lib/mpd/music/` then all MPD passes to the client is `Artist/Album/Track.mp3` This is why Cantata has a setting for the music folder as it needs to prepend this to MPD supplied paths to get the full path.

**Comment by realSConway** [comment]
Thanks for the reply!

This worked.
I changed `/var/lib/mpd/music/` to `~/Music` which is my music dir. After restarting Cantata I was able to sync music to my device.

**Comment by realSConway** [comment]
Would this also cause issues with copying podcasts since podcasts are stored in a different dir. 
`~/Podcasts` and not `~/Music`?

**Comment by CDrummond** [comment]
`music_directory` is an MPD setting. MPD does not handle Podcasts. Are you stating you cannot copy podcasts to devices? Must admit I don't, and never have, used podcasts.

**Comment by realSConway** [comment]
Ok, thanks for the explanation.

Correct, I am not able to copy Podcasts to devices.

**Comment by CDrummond** [comment]
There is no 'Copy to device' action for podcasts

**Comment by CDrummond** [comment]
I assume you are using this from the queue. The action is enabled if MPD dir is readable and there are some items in the queue - but no check is made on the type of items. When you invoke the action, it filters out the non MPD tracks, as there is nothing left nothing happens. Perhaps a dialog indicating this would make sense - but I am no longer adding new strings.

Same thing with 'Edit track information'

Basiclly, Cantata cannot copy podcasts to devices - it never could.

**Comment by realSConway** [comment]
Ok, understood, a bit unfortunate, but thanks for clarification!
