### ISSUE TITLE
Cantata does not update currently played song metadata in the toolbar when playing a radio stream

### ISSUE THREAD

**Issue by renkenn** [CDrummond/cantata#1707]
**Describe the bug**
When listening to a radio stream, the first song is displayed as the currently played song but is never updated again after radio changes to another song. However, the playlist view does update the later properly.

**To Reproduce**
1. Go to 'Internet'
2. Click on 'Play now' on any radio stream, I used ogg/opus-based one.
3. Open 'Playlist view'
4. Track the metadata of the radio stream on both 'Playlist view' and 'Toolbar'
5. Wait for the song to end and see error

**Expected behavior**
Currently played song metadata gets updated in the toolbar the same way it does in playlist view.

**Screenshots**

Toolbar displaying the radio stream's first song while playlist view shows the latest song.

![image](https://user-images.githubusercontent.com/26164156/116828548-47ec1e00-ab97-11eb-9163-48c5dee4b322.png)

**Version Info**
 - OS: GNU/Linux Debian testing bullseye
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.6
 - CMake options (other than default): Debian package.

**Additional context**

In case you need a radio stream to test, you can use the attached opus file. I zip'ed it because GitHub wouldn't allow me to upload it otherwise.

[stream.zip](https://github.com/CDrummond/cantata/files/6412302/stream.zip)

https://www.musicpd.org/doc/html/plugins.html#id24
opustags
https://tools.ietf.org/html/rfc7845.html

**Comment by CDrummond** [comment]
`stream.opus` is a file, not sure why you expect this to be a stream??? I'd need the URL you used to look into that. I tried playing your file and it only has a few seconds of audio, all "Inventive City" - and queue and toolbar showed same data. Even checked with GMPC

Also, I have checked with other stations and the queue and toolbar both change to show the current song.

**Comment by renkenn** [comment]
> `stream.opus` is a file, not sure why you expect this to be a stream??? 

The file contains a recorded snippet from the stream, it contains 2 songs which `mpv` displays properly as follows.

![image](https://user-images.githubusercontent.com/26164156/116926440-44699d00-ac52-11eb-8ef8-36c3c117a12c.png)

The first track is track 4 titled Inventive City which lasts about 20 seconds and the second track is track 5 titled Infinite Corridor which also lasts about 20 seconds. I thought that it's proof enough to reproduce the bug.

> I'd need the URL you used to look into that. I tried playing your file and it only has a few seconds of audio, all "Inventive City" - and queue and toolbar showed same data. Even checked with GMPC

The radio stream I use(d) isn't up 24/7, https://listen.moe/opus seems to reproduce this behavior as well.
I ran `watch mpc` while the radio stream was on and I think mpd is behaving correctly which is why cantata playlist view behaves correctly.

![image](https://user-images.githubusercontent.com/26164156/116928156-99a6ae00-ac54-11eb-843c-599b6fb7bf88.png)

![image](https://user-images.githubusercontent.com/26164156/116928173-9dd2cb80-ac54-11eb-9a69-77b1d0ad15ab.png)


> 
> Also, I have checked with other stations and the queue and toolbar both change to show the current song.

I believe it's specific to stream that use opustags as I stated before. Can you share the ones you've checked? Thank you.

**Comment by CDrummond** [comment]
I have no doubt there is an issue, just could not recreate it. I'll try with your stream URL later.

As for the streams I checked they were; Planet Rock and Heart radio - both UK stations.

**Comment by renkenn** [comment]
I tried Heart radio's London channel and I noticed they use AAC not Opus. The issue is specific to streams using opus, specifically opustags I believe.

**Comment by CDrummond** [comment]
Yeah, I know. However, Cantata _should_ not care about the stream type - it does not decode the stream, just handles status updates from MPD. I have no idea what is going wrong but will investiage with your stream URL.

**Comment by CDrummond** [comment]
The issue was your streams transmit a track number, most radio streams do not. Nothing wrong with that, but Cantata tries to display upmpdcli tracks nicely - and uses the presence of a track number to detect this. (Hacky, I know). When checking if now-playing should update Cantata was checking it was a standard stream - and ignoring upmpdcli streams. Cantata thought your streams were from upmpdcli, so the check failed. Hopefully this is now fixed. Can you checkout git/master and confirm?

**Comment by renkenn** [comment]
Unfortunately the change did not fix it.

**Comment by CDrummond** [comment]
Hmmm... What if you edit `gui/mainwindow.cpp` and change line 1781 from:

```
} else if (wasEmpty || Song::Stream==current.type) {
```

to 

```
} else {
```

**Comment by renkenn** [comment]
I tried it but still no. I even eliminated removed the if statement inside it and made the changed unconditional just in case the song wasn't treated as different but with no success.

```cpp
         // if (wasEmpty || pqSong.isDifferent(current) ) {
            updateCurrentSong(pqSong, wasEmpty);
             songChanged=true;
         //}
```

**Comment by renkenn** [comment]
I don't think `MainWindow::updatePlayQueue()` is ever called, I added `assert(0);` as a check and nothing. I'm assuming asserts make it to the post-`make` cantata binary.

Does `MPDConnection::playListChanges()` emit `playlistUpdated(songs, true);` if *the song itself is changes*? Does such a change cause cantata to treat the playlist as changed? I'm not familiar with cantata's code base, just some thoughts I have.

**Comment by CDrummond** [comment]
Sorry, I can't check at the moment. The queue does update, so Cantata is getting the message from MPD. MainWindow::updatePlayQueue receives the update from MPD, and passes it onto the queue. So we know that part must work. MainWindow::updatePlayQueue calls MainWindow::updateCurrentSong if the current has changed - and MainWindow::updateCurrentSong updates the toolbar.

I need to add more debug and try your URL again, but can't right now.

**Comment by CDrummond** [comment]
Well, I played your URL and all changes to queue were refelcted in toolbar. So, seems to work for me. (The stream seems to stop playback after a while though?)

**Comment by CDrummond** [comment]
Also, I used python's HTTP server to setup a stream for your `stream.opus` file, added this as a stream to Cantata, and during playback both queue and toolbar updated. So for me, this is now resolved.

**Comment by renkenn** [comment]
I apologize for the unintended false information, I closed cantata thinking it quit but instead it kept running in the background meaning I was testing the same old binary all the time.

I proper launched the locally compiled cantata binary and it worked like charm, thank you. I too consider this issue resolved and will close this issue.
