### ISSUE TITLE
Cantata doesn't remember the last opened folder in the Folders section.

### ISSUE THREAD

**Issue by arch-btw** [CDrummond/cantata#1708]
Hi,

Thank you so much for your hard work. I've been using cantata for years!

I wasn't sure if I should post this as a feature or a bug, but when I click on Folders in Cantata and proceed to navigate to my music folder and then close Cantata, then when I open it again I have to do that whole process over again because it doesn't remember the last opened folder. This is especially time consuming when the music folder has a long path.

I was wondering if this can be fixed or added?

Thank you so much!

**Comment by CDrummond** [comment]
No, Cantata does not remember any of the navigation levels - neither folders not library. Sorry, but I'm not going to implement this as its all dynamically loaded.

Its not an invalid use-case, just I have no time for this. Hence I'm closing as 'wontfix' as I do for all features, etc, that I have no intention of implementing. Pull requests are always welcome though.
