### ISSUE TITLE
fails to build complete package, MacOS Big Sur - master and release 2.4.2

### ISSUE THREAD

**Issue by ellul-ezra** [CDrummond/cantata#1709]
Build process completes but package resulting from make install is missing 'cantata' in MacOS/Contents.

CMake Error at cmake_install.cmake:61 (file):
  file INSTALL cannot find
  ".../Cantata.app/Contents/MacOS/cantata":
  No such file or directory.
 make: *** [install] Error 1

./create-dmg.sh shows:

dmg/Cantata/Cantata.app: bundle format unrecognized, invalid, or unsuitable
Creating hybrid image...

Contents of CMakeError.log:

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this an issue with the version of Xcode installed on my machine? (mac mini 2018, big sur 11.3)

**Comment by CDrummond** [comment]
Sorry, no idea. As stated in the main github page only Linux is acrively supported. I have no access to macOS, and don't use Windows.

**Comment by ellul-ezra** [comment]
Hi, thanks for offering this software for use. It's excellent and I have a working version of 2.4.2 compiled when I was on Mojave. I did see that MacOS is not supported but also noticed Mac-specific contributions from other developers, and recent changes to the build instructions for Mac. Thought this might be for their eyes.

**Comment by ellul-ezra** [comment]
Hello Craig,

Thanks for offering this software for use. It's really excellent and I have a working version of 2.4.2 compiled when I was on Mojave. I did see that MacOS is not supported but also noticed recent Mac-specific contributions from other developers, and changes to the build instructions for Mac. Thought this might be for their eyes. I'm not expecting a resolution!

Kind regards

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by CDrummond** [comment]
I no longer use Cantata or MPD - switched to LMS years ago - so my time for Cantata is very limited, and is mainly used to fix bugs.

**Comment by ellul-ezra** [comment]
I use that too, with your Material skin, which I should also be very thankful for

:)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
