### ISSUE TITLE
HTTP stream playback not working

### ISSUE THREAD

**Issue by fn-ix** [CDrummond/cantata#1714]
Clicking "Play HTTP output stream" does not produce any audio in Cantata. There is no sound even after several minutes of leaving it on, making it unlikely that it's a buffering issue. It's also not an issue with the MPD server, since I can listen to the stream on a web browser. 

 - OS: arch
 - Cantata Version: 2.4.2
 - MPD Version: 0.21.5
 - Stream type: vorbis

**Comment by CDrummond** [comment]
Just tried, and its working for me. Sorry, this is an issue on you system.

**Comment by fn-ix** [comment]
Well it's common that bugs don't replicate on all systems, but it's still a bug in Cantata for the end-user. I realize that you're just keeping this app on life-support, but I would be grateful if you could spare the time to look into it.

**Comment by CDrummond** [comment]
As stated, this is **not** a bug. I have no idea how you have compiled Cantata on your system or what multimedia libraries your Qt supports. Sorry, but I have no time for this. This is not a feature I implemented, and not one I ever used. However, I spent time to configure mpd to use a HTTP output, compiled Cantata, added the URL - and it worked.
