### ISSUE TITLE
Cantata 2.3.2 for Windows x64, some windows exceed available viewport

### ISSUE THREAD

**Issue by neiljt** [CDrummond/cantata#1719]
**Describe the bug**
Some windows exceed the height of the desktop (minus taskbar). All controls are at the very bottom, and it's impossible to get at them without setting the taskbar to autohide eg: the 1st run wizard and settings.  however that doesn't suit everybody's way of working, so every time i need to tweak cantata, i need to first fiddle with the taskbar. 

**To Reproduce**
1. Run cantata
2. Select settings (or wait for the 1st run wizard)

**Expected behavior**
All apps create windows with vertical scrollbars when they have content that exceeds the available viewport.

![Cuntata](https://user-images.githubusercontent.com/9955107/120552872-b2d78180-c3ef-11eb-90f0-4cfad1795068.png)

**Version Info**
 - OS: Windows 10 x64, v 20H2
 - Cantata Version:  2.3.2
 - MPD Version: 0.22.4
 - CMake options (other than default): unknown

**Additional context**

**Comment by CDrummond** [comment]
Something is wrong with the sidebar icons in your screenshot - they are too large.

However, as stated in the main page, I only support Linux as of 2.3.3 - I have no wndows install.

**Comment by remipp** [comment]
This looks like a windows scaling issue to me (4k screenshot). You can try playing around with the scaling options windows gives you. You can also try changing the icon style in the interface settings

**Comment by neiljt** [comment]
Hi

thank you for replying. The scaling in the screenshot was set to windows
automatically, it sets it according to the monitor's resolution. my tv has
a native res of 3840x2160 so the scaling is set to 300% (Recommended). I
followed your advised at tweaked it, but immediately reverted as below 300%
i'd need a telescope to read anything.

i also tried tweaking the interface, as you also suggested, but unless you
know different - in which case please let me know exactly what settings you
were thinking of - the 1st run wizard and the preferences icon size are
unaffected by changes made in Preferences/Toolbar, which only changes the
main window icons. I couldn't see anything else, but it's 2:17am and i can
barely keep my eyes open, so it's possible that i might have missed
something.

finally, if it would help, i recently bought two windows 10 pro licenses, i
could gift you one if it means you supporting windows as well.

all the best
neil

**Comment by CDrummond** [comment]
Thanks for your kind offer, but I have no time/enthusiasm to look into Windows specific issues. I no longer actively use Cantata nor MPD - having switch to LMS about 4 years ago.
