### ISSUE TITLE
Connecting to MPD via a socket file

### ISSUE THREAD

**Issue by SpaceshipOperations** [CDrummond/cantata#1722]
I'm unsure whether to file this as a bug report, mere question, or a feature request. Probably a hybrid of all three, or at least the last two.

I have set up a per-user MPD instance that listens via a socket file only, without a net address + port. I want Cantata to connect to MPD via using socket file, without having MPD listen on (and use up) a port.

Upon installing Cantata and launching it the first time, it appears that it does not have an option to specify a socket file, only fields for specifying a host and port.

So first of all, is there a way to make it accept a socket file as an option? I did try pointing to the file by specifying its path (including as a URL by prefixing it with "file:///"), but as one would think, that did not work.

In the case Cantata does not have this capability, I would like to request adding it.

Thank you.

**Comment by CDrummond** [comment]
Cantata does support socket paths, use the hostname field for the path.
