### ISSUE TITLE
Releases are no longer being tagged

### ISSUE THREAD

**Issue by peterhoeg** [CDrummond/cantata#1724]
**Describe the bug**

d61ca874081311844526ab13cd40348421f89097 mentions a version 2.5.0 but the most recent tagged release is still 2.4.2

**Comment by CDrummond** [comment]
2.5.0 will be the **next** release. All that commit did is change the version from 2.4.3 to 2.5.0 - 2.4.3 itself was never released. 2.4.3 was going to be the next release, but another user added a feature change hence 2.4 -> 2.5

I will tag Cantata when I think it's ready for release.

**Comment by peterhoeg** [comment]
Gotcha'. Thanks!
