### ISSUE TITLE
Crash upon export attempt

### ISSUE THREAD

**Issue by anarchotaoist** [CDrummond/cantata#1728]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
When attempting to export either Radio Favourites or Podcasts a save dialog appears briefly but Cantata crashes before it can be saved.

**Version Info**
 Operating System: Kubuntu 21.04
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-25-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
 - Cantata Version: 2.4.2
 - MPD Version: 0.22.6-1
 - CMake options (other than default):

**Additional context**
cantata
libpng warning: iCCP: known incorrect sRGB profile
Unfortunately Cantata has crashed. Please report a bug at 
https://github.com/CDrummond/cantata/issues/ and include the following stack trace:

  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x41040
  /lib/x86_64-linux-gnu/libKF5Solid.so.5 : Solid::StorageAccess::isEncrypted() const+0x4
  /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5 : ()+0xec64c
  /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5 : ()+0xec786
  /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5 : KIO::PreviewJob::slotResult(KJob*)+0x19d
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2f05c7
  /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5 : KJob::result(KJob*, KJob::QPrivateSignal)+0x50
  /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5 : KJob::finishJob(bool)+0x5b
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2f05c7
  /lib/x86_64-linux-gnu/libKF5KIOCore.so.5 : KIO::SlaveInterface::dispatch(int, QByteArray const&)+0x3a3
  /lib/x86_64-linux-gnu/libKF5KIOCore.so.5 : KIO::SlaveInterface::dispatch()+0x5d
  /lib/x86_64-linux-gnu/libKF5KIOCore.so.5 : KIO::Slave::gotInput()+0x62
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : ()+0x2f05c7
  /lib/x86_64-linux-gnu/libQt5Core.so.5 : QObject::event(QEvent*)+0x2ac
  /lib/x86_64-linux-gnu/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x83

**Comment by CDrummond** [comment]
As you can see, from the backtrace, the crash is in KDE code - not Cantata code. Cantata does not even link to KDE. I've just tried both export functions under GNOME, and no cash with Gtk or Qt file dialogs.

Sorry, but this is not a Cantata issue.
