### ISSUE TITLE
Gentoo install, all cache files are at /tmp/

### ISSUE THREAD

**Issue by alan12345678** [CDrummond/cantata#1730]
Can I please just ask whether this is intended behaviour, or do I have something on my installation I need to sort out?

Comparing with Cantata installed on Arch, where it works fine, I emerged it on Gentoo recently and notice that instead of having all the album thumbnails cached locally, instead EVERYTHING is in

/tmp/<user>/.cache/cantata

and which means that every time I reopen the player, it has to rediscover all the image thumbnails.

Also, the player position is never stored, it always reopens in the 'wrong' place.

Is this me? Did I miss some configuration setting? Nothing in emerge suggests an option.

Many thanks :)

**Comment by CDrummond** [comment]
Cantata uses the XDG desktop folder structure for cache and config, etc. This is all accessed via Qt functions. Something is broken on your system and Qt is returing invalid values. Sorry, but this is an issue with your system, or your build of Qt, not Cantata.

**Comment by alan12345678** [comment]
thank you so much, your response helped me find the issue, which was indeed as you said.

I'd already asked on the forum days ago but had no response. All sorted now, thanks again :)
