### ISSUE TITLE
When playing HTTP streams through Cantata on Plasma, the mute icon appears for all pinned applications in the task bar instead of only Cantata

### ISSUE THREAD

**Issue by psy-q** [CDrummond/cantata#1735]
**Describe the bug**
On KDE/Plasma (tested with 5.22.4), as soon as Cantata starts playing a HTTP stream, all application icons pinned to the task bar will display the "mute" icon in the shape of a speaker. Whether Cantata itself has been pinned or not doesn't matter.

When playing audio from other pinned applications, only the icon of the playing application displays the mute toggle.

**To Reproduce**
1. On Plasma 5.22.4, have some applications pinned to the taskbar (right-click application -> Pin to Task Manager) 
2. Have Cantata configured to play HTTP audio streams from MPD
2. Play a song, wait until you can hear the audio
3. Observe that all application you pinned to the taskbar receive the mute/speaker icon

**Expected behavior**
No application icon except Cantata's should display the mute/speaker icon. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87557/130356222-03ad4352-dfdb-4688-8f61-e2bb573c6fe2.png)

**Version Info**
 - OS: openSUSE Tumbleweed 20210817
 - Cantata Version: 2.4.2
 - MPD Version: 0.21.5-3 (Debian)
 - CMake options (other than default):

**Additional context**

**Comment by CDrummond** [comment]
Sounds like a problem with plasma to me.

**Comment by psy-q** [comment]
Hmm, it seems to affect only some applications and only when using Pipewire: https://bugs.kde.org/show_bug.cgi?id=438565
