### ISSUE TITLE
Can't run compiled Cantata app on MacBook with M1 processor

### ISSUE THREAD

**Issue by korandcom** [CDrummond/cantata#1737]
Compiled and launched successfully on Intel processor based MacBook, but can't do it on M1. Compilation process finished but when trying to launch the app - error message appears immediately.

Here is the debug error log on app launch:

Process:               cantata [98668]
Path:                  /Users/USER/*/Cantata.app/Contents/MacOS/cantata
Identifier:            mpd.cantata
Version:               2.4 (???)
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           cantata [98668]
User ID:               501

Date/Time:             2021-08-29 18:53:52.932 +0300
OS Version:            macOS 11.5.2 (20G95)
Report Version:        12
Anonymous UUID:        6FFA00F5-F7A9-3C9A-8DF6-23BA38E47A4A

Sleep/Wake UUID:       7FC87D99-3EFD-4AF9-BC1A-95E5579D4376

Time Awake Since Boot: 53000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x00000001032dc000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x1032dc000:
    __LINKEDIT                  1031b0000-1032dc000    [ 1200K] r--/r-- SM=COW  /Users/*/Cantata.app/Contents/MacOS/cantata
--> mapped file                 1032dc000-1032e0000    [   16K] r--/r-x SM=PRV  Object_id=db0ef787
    __TEXT                      103490000-103510000    [  512K] r-x/r-x SM=COW  /usr/lib/dyld

Application Specific Information:
dyld: launch, loading dependent libraries
@executable_path/../Frameworks/QtMultimedia.framework/Versions/5/QtMultimedia

Thread 0 Crashed:
0   dyld                          	0x00000001034ee1e0 memcmp + 16
1   dyld                          	0x00000001034ae7fc ImageLoaderMachO::validateFirstPages(linkedit_data_command const*, int, unsigned char const*, unsigned long, long long, ImageLoader::LinkContext const&) + 136
2   dyld                          	0x00000001034b578c ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) + 268
3   dyld                          	0x00000001034ad3ec ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) + 172
4   dyld                          	0x0000000103494588 dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) + 668
5   dyld                          	0x000000010349dbd0 dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 1368
6   dyld                          	0x000000010349d5f4 dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 208
7   dyld                          	0x000000010349d10c dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 600
8   dyld                          	0x000000010349cac4 dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 252
9   dyld                          	0x0000000103494104 dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 468
10  dyld                          	0x0000000103493ca8 dyld::load(char const*, dyld::LoadContext const&, unsigned int&) + 196
11  dyld                          	0x000000010349e574 dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*, unsigned int&) + 56
12  dyld                          	0x00000001034a8970 ImageLoader::recursiveLoadLibraries(ImageLoader::LinkContext const&, bool, ImageLoader::RPathChain const&, char const*) + 344
13  dyld                          	0x00000001034a7128 ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&, char const*) + 160
14  dyld                          	0x0000000103496a08 dyld::link(ImageLoader*, bool, bool, ImageLoader::RPathChain const&, unsigned int) + 328
15  dyld                          	0x0000000103499208 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7964
16  dyld                          	0x0000000103491258 dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 476
17  dyld                          	0x0000000103491038 _dyld_start + 56

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001032dc000   x1: 0x000000016d099ae0   x2: 0x0000000000000a50   x3: 0x0000000000040001
    x4: 0x0000000000000003   x5: 0x0000000000000000   x6: 0x0000000103518280   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x000000016d09a148  x10: 0x0000000000000001  x11: 0x0001803000000000
   x12: 0x0000000000000032  x13: 0x0004000000000000  x14: 0x00000000000ca858  x15: 0x000000016d09a0c8
   x16: 0x00000000000000c5  x17: 0x000000016d09a0e0  x18: 0x0000000000000000  x19: 0x000000010351d630
   x20: 0x0000000000000a60  x21: 0x000000016d099ae0  x22: 0x00000001032dc000  x23: 0x0000000000000003
   x24: 0x000000016d09a530  x25: 0x000000016d0a1bf8  x26: 0x000000016d0a1d70  x27: 0x000000016d099ae0
   x28: 0x000000000000000b   fp: 0x000000016d0994e0   lr: 0x00000001034ae7fc
    sp: 0x000000016d0994a0   pc: 0x00000001034ee1e0 cpsr: 0x20000000
   far: 0x00000001032dc000  esr: 0x92000007

Binary Images:
       0x102d5c000 -        0x103173fff +mpd.cantata (2.4 - ???) <00D3D37D-BB2A-3734-92F2-90C2B01311E0> /Users/USER/*/Cantata.app/Contents/MacOS/cantata
       0x103490000 -        0x10350ffff  dyld (852.2) <17D14D9B-B6B2-35DC-B157-4FD60213BE99> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=6176K resident=0K(0%) swapped_out_or_unallocated=6176K(100%)
Writable regions: Total=8384K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8384K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                        1.0G        1 
__DATA                             320K        3 
__DATA_CONST                       176K        2 
__LINKEDIT                        1488K        3 
__TEXT                            4704K        2 
mapped file                         16K        1 
===========                     =======  ======= 
TOTAL                              1.1G       14 

Model: MacBookAir10,1, BootROM 6723.140.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Jul  7 2021 00:48:27 version 18.50.40.10.7.8.121 FWID 01-f5ad2691
Bluetooth: Version 8.0.5d7, 3 services, 25 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: Hub
USB Device: USB Receiver
USB Device: USB Controls
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by CDrummond** [comment]
Sorry, but as stated on main github page: "Only Linux actively supported as of 2.3.3" ...and the stack trace does not end in Cantata's code.

**Comment by korandcom** [comment]
Very sorry... Working for me compiled for Intel processor by Rosetta emulator but want to run it native for M1. Maybe some thoughts about why it not working?

**Comment by CDrummond** [comment]
Sorry, I really have no idea. I'd suspect its a Qt issue - not even sure if Qt5 officially supports M1.

But, I have no mac. When I did the original mac port I had a loan laptop, which I no longer have access to.

**Comment by korandcom** [comment]
Understand. Will try to fix by myself but it will be hard - I'm a web developer :) Thank you for you work!

**Comment by CDrummond** [comment]
Personally, I stopped using Cantata and MPD over 4 years ago. I've switched to Logitech Media Server (LMS), which (despite its name) is fully opensource. My main concentration is now on a google-material themed skin/web-app that I have written for this - see  [https://github.com/CDrummond/lms-material](https://github.com/CDrummond/lms-material)  This is a HTML5/Javscript app written with Vue.js. However, unlike yourself I am no web-developer!

**Comment by korandcom** [comment]
Having old Zyxel Keenetic router and custom firmware for it with MPD installed. For listening music using EMU 0204 USB sound card and ADAM studio speakers. Thank you for telling about LMS - will look on it. But need another device to install it and connect my external USB sound card. What hardware are you using?

**Comment by CDrummond** [comment]
I use a Pi4 for LMS server, amongst other things. I then have airplay speakers, bluetooth speakers, and  1 SqueezeBox radio. All controlled by my webapp :)

**Comment by korandcom** [comment]
Ok, will look on it. Thank you very much! Maybe help you in web client development if needed.

**Comment by korandcom** [comment]
Installed and tried to use LMS. Looks good but can't find native applications like Cantata to control the playback on laptop with hot keys support and etc. Your web skin looks good comparing to native but not as convenient as application. Maybe it is possible to update Cantata to work with LMS?

**Comment by CDrummond** [comment]
By "hot keys" I assume you mean media keys (prev/play/next etc)? I tried that before by using MediaSession. This was mainly for android so that controls would appear on the lockscreen. This initially worked, then broke in later versions of Chrome. I _think_ the problem is that the webapp itself does not actually play any media. My initial attempts faked the playback state, then I hacked it to play/pause a silent ogg file. However, this became brittle and I removed the code. So, seeing as you _are_ a web develper perhaps you have a better idea how this could be added? If so, please open an issue at [lms-material](https://github.com/CDrummond/lms-material) to discuss further.

**Comment by korandcom** [comment]
Found an old Android TV Box and flashed Armbian firmware on it. With Squeezelite it works well with my USB sound card. Looking more deep on LMS and all stuff and want to say you did a huge work with your Material skin. Will go to lms-material and look what I can do. My specialisation is more backend but having some skills in front. Thank you for your work.

**Comment by CDrummond** [comment]
Just to let you know, in the 2.7 branch of lms-material I have initial support for MediaKeys. This requires the skin to play a 10 second silent audio clip in repeat. For this to start playing the user needs to interact (i.e. click) on the page, but then the controls are shown. You can configure Chrome to allow your LMS server to autoplay, in which no clicks are required. Still, its a start...

**Comment by korandcom** [comment]
Ok, thanks. I will definitely look on it and try to implement the full MediaKeys support.
