### ISSUE TITLE
Cancelling a “Save as” action overwrites the pre-selected playlist

### ISSUE THREAD

**Issue by alterNERDtive** [CDrummond/cantata#1739]
**Describe the bug**
Hitting “Save as”, then “cancel” will not cancel, but save as the pre-selected playlist name.

**To Reproduce**
1. Go to the Play Queue
2. Right click on any item
3. Select “Save as”
4. (optional) Change / remove the pre-selected playlist name
5. Hit “cancel”

**Expected behavior**
Saving the playlist is cancelled.

**Version Info**
 - OS: Linux (Fedora 34)
 - Cantata Version: 2.4.2 (cantata-2.4.2-2.fc34.x86_64)
 - MPD Version: 0.22.10 (mpd-0.22.10-1.fc34.x86_64)
 - CMake options (other than default): N/A

**Comment by CDrummond** [comment]
Oops! Should be fixed now. Will release 2.5.0 soon...

**Comment by alterNERDtive** [comment]
That was fast! Thank you very much <3

**Comment by CDrummond** [comment]
No probs. That bug must have been in there for a _long_ time, and was really silly!

**Comment by alterNERDtive** [comment]
I noticed right away. I’ve been using xfmpc for years and was specifically looking for a client that could manage playlists, so I ran into it about 5 minutes in.
