### ISSUE TITLE
Mac OS 2.4.2 built

### ISSUE THREAD

**Issue by Badsheep** [CDrummond/cantata#1743]
Hello,

I know it's not the right place where to ask, but I don't know where else I could go ?

First of all thank you for your amazing job ! 
I use Cantata with much pleasure on my Mac OS.

But the last version I could find on the web is the 2.3.2, and I'd like to know if anyone has (or could) built a Mac OS version of the 2.4.2 ? Unfortunately I'm not sure to be able to dot that...

Thank to anyone that could help !
And once again thanks to Craig for that great software.
Badsheep

**Comment by CDrummond** [comment]
An issue is not the place for this. I have no mac, so cannot create builds. However, there are instructions in the README.
