### ISSUE TITLE
Cantata disconnects on add smart playlist

### ISSUE THREAD

**Issue by coacharnold1** [CDrummond/cantata#1755]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
SO .... when I go to smart playlist,  I can add 1 smart playlist with whatever rules.  When I add a second mpd and cantata disconnect.

**To Reproduce**
1. Add smart palylist
2. add a second smart playlist. attemt to add second playlist while the first is playing.  Cantata disconnecs
3. do the same in "dynamic" playlist and it works fine Whats the difference?
4

**Expected behavior**
Add playlist #2 and not crash

**Version Info**
 - OS: Manjaro 21
 - Cantata Version: 2.5.0
 - MPD Version: Music Player Daemon 0.22.11 (0.22.11)

**Comment by CDrummond** [comment]
Sorry, but works fine for me.

Does cantata **crash** ??? Disconnecting from MPD is different to crashing. If cantata crashes a backtrace should be shown. If a disconnect occurs, perhaps it is MPD that is closing the connection?

**Comment by CDrummond** [comment]
Closing, asked for info more than 3 weeks ago and no repsonse. As stated, works for me.
