### ISSUE TITLE
[Feature request] continue releasing cantata for windows

### ISSUE THREAD

**Issue by twojstaryzdomu** [CDrummond/cantata#1756]
**Is your feature request related to a problem? 
No.

**Describe the solution you'd like**
Canata used to be compiled for windows until version 2.3.2. I'd also like the recent release to be compiled for windows, which I use occasionally.

**Comment by CDrummond** [comment]
No, I do not have any Windows dev environment. As stated in the main github page, **only** Linux is actively supported.
