### ISSUE TITLE
MPD doesn't quit gracefully

### ISSUE THREAD

**Issue by Dr-Escher** [CDrummond/cantata#1761]
**Describe the bug**
MPD doesn't quit gracefully (not saving state) when closing Cantata.

Upon Cantata exit:
~/.cache/cantata/mpd/pid is not removed
~/.cache/cantata/mpd/state is not saved

**To Reproduce**
1. Start Cantata
2. Add items to the Play Queue *(change state)*
3. Quit and restart Cantata
4. See empty Play Queue *(state lost)*

**Expected behavior**
MPD should be shut down gracefully to save the current state and remove its PID file

**Workaround**
1. Stop MPD by `pkill -INT mpd` in advance to gracefully exit and save state
2. Stop Cantata (now reporting 'Connection failed') afterwards
3. State gets preserved for the next launch of Cantata

**Version Info**
Distro: Manjaro KDE
linux515 5.15.12-1
cantata 2.4.2-1
mpd 0.23.5-1

**Additional context**
The issue still persists after completely purging Cantata and MPD data.

**Comment by CDrummond** [comment]
Works for on Unbuntu with MPD 22.6 (which I know is not the latest). When stopping I invoke `mpd --kill` which should cause MPD to save its state. According to the MPD docs SIGTERM should be used to stop MPD, and then it can save its files. https://mpd.readthedocs.io/en/stable/user.html

**Comment by Dr-Escher** [comment]
Both TERM and INT signals seem synonymous (see [https://mpd.readthedocs.io/en/stable/user.html#signals](https://mpd.readthedocs.io/en/stable/user.html#signals))
```
MPD understands the following UNIX signals:
    - SIGTERM, SIGINT: shut down MPD
    - SIGHUP: reopen log files (send this after log rotation) and flush caches
```

**Comment by Dr-Escher** [comment]
In fact, it's also working if I invoke `mpd --kill ~/.local/share/cantata/mpd/mpd.conf` manually (same as `pkill` mentioned above), but not when closing Cantata regularly.
