### ISSUE TITLE
Cantata v2.3.2 for Windows & Dynamic Playlist

### ISSUE THREAD

**Issue by inukaze** [CDrummond/cantata#1763]
Hi there i want to know how i should configure Folders/Files to enable and make work "Dynamic Playlist" inside "Cantata" v2.3.2 for Windows

i open "cmd" like administrator and use the follow commands : 
```
mkdir %LocalAppData%\mpd\cantata\dynamic
cd %LocalAppData%\mpd\cantata\dynamic
type nul > "pid"
type nul > "Dinamica.rules"
mklink "rules" "Dinamica.rules"
```

Well i don't have any clue how i should edit the "file.rules" in this case "Dinamica.rules" for do something, you can give me an example ? 

![Cantata - Dinamic Playlist](https://user-images.githubusercontent.com/1647332/151111046-5e1bf820-f518-408a-9c8b-06d8a786ded2.png)

i try before "11. Dynamic Helper Script - Local Mode" from "https://raw.githubusercontent.com/CDrummond/cantata/master/README" but i don't make it work

Thank for any help you can give me.

**Comment by CDrummond** [comment]
The dynamic scripts use a PERL helper script, I have never run this under windows and I'm 99% certain it will not work.

The README even mentions this:

```
Server mode is currently the only way for dynamic playlists to be used under
Windows.
```

To use dynamic playlists on windows you would need to run the helper script on a Linux system (e.g. a raspberry pi). When this script starts Cantata should detect this, and use remote dynamic playlists.

Also, sorry but I no longer support windows or mac.

**Comment by inukaze** [comment]
Dunno 1 : You don't have idea if using cygwin or CoLinux can be possible to do that ?
Dunno 2 : The dev team never think on make a built-in perl interpreter for windows release ?

Well Thanks for the answer

**Comment by CDrummond** [comment]
There is no 'dev team' - Cantata is, and always has been, a personal project. If you want this implemented feel free to create a pull request, etc. However, it is not something I have time or motivation to work on.

As stated in the main github page, Windows and macOS are no longer actively supported - and Cantata itself is in maintenance mode. I stopped using MPD and Cantata over 4 years ago.

**Comment by inukaze** [comment]
Thanks for the answer.
