### ISSUE TITLE
When editing information of mp3, empty TCON frame is added to id3v2 tag

### ISSUE THREAD

**Issue by tutebatti** [CDrummond/cantata#1765]
Screenshots:
![grafik](https://user-images.githubusercontent.com/7239968/152680358-3c634572-438c-47e4-8b24-b95478abb51a.png)
![grafik](https://user-images.githubusercontent.com/7239968/152680379-6772e165-d9a4-4acb-9d37-5f9992d03954.png)

The metadata was displayed using id3v2. Kid3 shows an empty field as well.

**Comment by CDrummond** [comment]
Ah! Yes, its always writing 4 genres. Will fix. Sorry.

**Comment by CDrummond** [comment]
I've updated the code to now to not write empty genres. However, for me, it only saves the last genre. How did you get id3v2 to list all?

Can you rebuild cantata from git and confirm this is fixed?

**Comment by tutebatti** [comment]
> Sorry.

There's nothing to be sorry about. Your software is awesome, thank you.

> How did you get id3v2 to list all?

This worked for me simply using the `-l` flag. I'm using id3v2 version `0.1.12`.

May I ask how exactly Cantata writes the tags to a file? I would prefer to use the command line for tagging the genres instead, but all command line tools I tried so far simply override the `TCON` frame instead of adding (different from `metaflac` for flac files).

**Comment by tutebatti** [comment]
> Can you rebuild cantata from git and confirm this is fixed?

I am not too firm on certain things, so maybe you can help me with this error when executing `cmake ..` during the installation process documented in the file `installation.md`:

> CMake Error at CMakeLists.txt:196 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.
  Could not find a package configuration file provided by "Qt5" (requested version 5.11) with any of the following names:
>
> Qt5Config.cmake
qt5-config.cmake
>
> Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR" to a directory containing one of the above files.  If "Qt5" provides a separate development package or SDK, be sure it has been installed.

**Comment by CDrummond** [comment]
Same ID3v2 version here:

```
id3v2 --version
id3v2 0.1.12
Uses id3lib-3.8.3

This program adds/modifies/removes/views id3v2 tags, 
and can convert from id3v1 tags
```

I've used cantata's debug to confirm its _trying_ to write t2o genre tags  `cantata --debug=tags`

Log shows:
```
2022-02-06 13:54:22 - Tags writeID3v2Tags add genre "Metal"
2022-02-06 13:54:22 - Tags writeID3v2Tags add genre "Rock"
```

But id3v2 only shows last:
```
TYER (Year): 1980
TCON (Content type): Rock (17)
01 Prowler.mp3: No ID3v1 tag
```

Cantata uses TagLib to update tags. The exact code is:

```
                for(int i=0; i<Song::constNumGenres; ++i) {
                    QString genre = to.genres[i].trimmed();
                    if (!genre.isEmpty()) {
                        TagLib::ID3v2::TextIdentificationFrame *frame = new TagLib::ID3v2::TextIdentificationFrame("TCON");
                        tag->addFrame(frame);
                        DBUG << "add genre" << genre;
                        frame->setText(qString2TString(genre));
                    }
                }
```

**Comment by CDrummond** [comment]
You need to install Qt5 developer headers. e.g. for Fedora:

qt5-qtbase-devel
qt5-qtsvg-devel
qt5-qttools-devel
qt5-qtx11extras-devel.

**Comment by tutebatti** [comment]
I'm on Linux Mint. Installing `qttools5-dev` still brings me errors.

**Comment by CDrummond** [comment]
Either install `qt5-qtmultimedia-devel` or pass `-DENABLE_HTTP_STREAM_PLAYBACK=OFF` when calling cmake.

**Comment by tutebatti** [comment]
Ok, I got it installed and running. However, most options, including "edit track information" are not shown when right-clicking on a track.

I uninstalled and installed from the repros again. Here, the options are shown but disabled, i.e., not clickable.

I'm lost.

**Comment by CDrummond** [comment]
You will also need taglib headers installed.

**Comment by tutebatti** [comment]
Thank you for providing help. I managed to install everything on a vm running the same OS that I'm usually working on. The tagging seems to work now.

When will this be available in the regular repos?

**Comment by CDrummond** [comment]
Great, so you get multiple tags. Odd that I do not. Still, thanks for the confirmation.

I intend to release 2.5.0 soon - when I get the time. I no longer use Cantata nor MPD (switched to LMS over 4 years ago), so it's not a priority for me. But will release probably sometime this month - depending upon bug reports.
