### ISSUE TITLE
Can't fetch songs from Soundcloud

### ISSUE THREAD

**Issue by jinmax100** [CDrummond/cantata#1766]
Hello Team,
I am trying to stream songs in cantata from Soundcloud, but when I type name of the song or album or anything , it always says "No Track Found". However if I go to website and search for same track I can find it there. What could be the probable cause? 

Help is much appreciated. Thanks

**Comment by CDrummond** [comment]
Please look for existing issues, even closed ones, before opening new ones. SoundCloud support has been removed.

Duplicate of #1745

**Comment by jinmax100** [comment]
> Please look for existing issues, even closed ones, before opening new ones. SoundCloud support has been removed.
> 
> Duplicate of #1745

> Please look for existing issues, even closed ones, before opening new ones. SoundCloud support has been removed.
> 
> Duplicate of #1745

Sorry, I should've seen the Issues first. Thanks for clearing this out.
