### ISSUE TITLE
Group albums

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CDrummond/cantata#426]
```
Currently albums are grouped by album/artist in the albums view and in the 
playlist. This doesn't work well with compilations. It would be nice, if there 
was an option to group by album title only, so albums containing different 
artists would only appear once.

It would also be cool to have a minimum number of tracks that needs to be 
exceeded for an album to show up in the albumview. This way the album view 
stays clean and does not show up single unsorted tracks (gmusicbrowser does 
this for example).

```

Original issue reported on code.google.com by `aepel...@gmail.com` on 28 Feb 2014 at 1:00

**Comment by albel727** [comment]
>please either update your tags, or properly configure MPD.
That's a bit of a harsh choice. Have you considered that files can't be updated, e.g. being part of a torrent?

**Comment by asi14** [comment]
I second that -- is there any particular reason why Cantata cannot sort by album and year _only_? I imagine adding it would be a trivial feature.
