### ISSUE TITLE
OS X media keys support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CDrummond/cantata#614]
```
Which version of Cantata?
1.5.1

Which build? KDE, Qt4, Qt5, Windows, Ubuntu, Mac?
Mac 

What steps will reproduce the problem?
1. Press media key

What is the expected output? What do you see instead?
Playback should react. It does not
```

Original issue reported on code.google.com by `mutantco...@gmail.com` on 11 Jan 2015 at 12:05

**Comment by CDrummond** [comment]
Closing as I have no real mac access, so not much chance of me fixing/implementing this. Still, Cantata is open source so patches welcome!
