### ISSUE TITLE
issue to compile it on OpenBSD

### ISSUE THREAD

**Issue by william-os4y** [CDrummond/cantata#666]
Hello, 

FYI, I've been forced to make few changes in order to have cantata running on OpenBSD-current with QT5. 
(I used the master branch of today)

in the CMakeLists.txt, I add the following to identify OPENBSD:

```
if(CMAKE_SYSTEM_NAME MATCHES "kOpenBSD.*|OpenBSD.*")
     set(OPENBSD TRUE)
endif()
```

on line 584-588
I replace this:
```
    include_directories(${TAGLIB_INCLUDES})
    if (APPLE)
        # for some reason under osx we get full path ino include/taglib?
        include_directories(${TAGLIB_INCLUDES}/..)
    endif (APPLE)
```
by this:
```
    if (APPLE OR OPENBSD)
        # for some reason under osx we get full path ino include/taglib?
        include_directories(${TAGLIB_INCLUDES}/..)
    else (APPLE OR OPENBSD)
        include_directories(${TAGLIB_INCLUDES})
    endif (APPLE OR OPENBSD)
```

The compilation went perfect. 
Now I'll play with my mpd server :-)

ps:
Sorry I did not forked the project because the change is very limited.

**Comment by CDrummond** [comment]
Added to master now. To be honest, I'm pretty new to git (Cantata was at Google code because it could use svn :-) ) - so, I'm happy with patches :-)
