### ISSUE TITLE
Cantata does not report any accessibility things on OSX

### ISSUE THREAD

**Issue by Ahti** [CDrummond/cantata#667]
On OSX, one can inspect the accessibility elements reported by an application by using the Accessibility Inspector contained in Xcode.

Cantata does not report any accessibility information beyond being an application.

This is unfortunate for the obvious reason of the application being unusable for people relying on accessibility tools to use their Mac. It is also bad in another respect: Many window/desktop management helpers on OSX use the Accessibility API to find windows to move around etc. This is my specific use case.

This might be a restriction of the underlying framework, but I wanted to bring this issue to your attention nevertheless.

I might look into wether this is fixable if I find the time for it in the next days.

**Comment by CDrummond** [comment]
I don't have access to an OSX machine for development, just for creating builds. So, if you want more OSX features you will have to provide a patch.

**Comment by CDrummond** [comment]
Closing as I have no real mac access, so not much chance of me fixing/implementing this. Still, Cantata is open source so patches welcome!
