### ISSUE TITLE
Sefault when I start both Magnatune & Jamendo downloading

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#668]
The first time I tried to use Magnatune & Jamendo, I set them both to download at the same time. After the download had reached 100%, cantata crashed. Unfortunately I can't find any relevant material in my GNOME session log.

I restarted cantata from the command line (incidentally discovering some errors in my XCompose settings, thanks Qt!) and set each to download separately: this worked fine.

I'm running cantata 1.5.50, compiled from then-current git on April 3rd; I can't see any commits since then that mention Jamendo or Magnatune.

**Comment by CDrummond** [comment]
Odd, just tried with latest 'master' and no crash for me. However, I'm considering making some drastic changes to Cantata (using a SQL db), which should make the Jamendo support *much* better.

**Comment by CDrummond** [comment]
master has now been updated with the SQL version of Jamendo and Magnatune. I still cannot recreate this, could you please try?

**Comment by rrthomas** [comment]
This seems to work fine now, thanks. (Who knows what rare conjunction of circumstances, hopefully in now-deleted code, triggered the crash before?)

**Comment by CDrummond** [comment]
Not sure. The download code should still be pretty similar - and they were separate classes/threads. And, as I said, I could not recreate.

I'll close this for now. Feel free to re-open if it occurs again.
