### ISSUE TITLE
Tag past releases

### ISSUE THREAD

**Issue by Fuuzetsu** [CDrummond/cantata#669]
Would it be possible to put tags on some recent past releases? This would help with packaging.

PS: Glad to see move to git.

**Comment by CDrummond** [comment]
To be honest, this seems like a lot of hassle - and I'm not 100% sure how to do this. However, if you can come up with a simple shell script with the appropriate git commands then I'll apply it. Otherwise, sorry I don't have the time.

**Comment by Fuuzetsu** [comment]
If you know which commits you made the releases out of in the past, simple `git tag` on that commit should do. Then just `git push --tags`.

Even just the latest release would be OK, something to point at from package manager.

**Comment by ff2000** [comment]
Currently there seems to be no (obvious) way to download any releases. code.google.com redirects to this github repo, so every info from code.google.com isn't available anymore, though it seems download links still work - My Gentoo ebuild downloads the last (1.5.2) release just fine.

**Comment by Fuuzetsu** [comment]
Download links were on Google Drive because Google Code stopped file hosting so they should still work. But yes, there's no way to download any past releases which is what this ticket is about.

**Comment by ff2000** [comment]
Ah, didn't get the essence of this issue ;) Thought this was just about tags.
In the meantime I found out that one can go on the "Releases" page and manually mark a certain commit as versioned release. Probably this is easier than tagging previous commits/releases.

**Comment by CDrummond** [comment]
I copied over the old google-code download page to the wiki on github. See https://github.com/CDrummond/cantata/wiki/Previous-%28Google-Code%29-Downloads

This still seems to allow downloads of the google-code hosted releases 0.7.0 - 1.2.2 If I get time I /might/ copy these onto google drive. But, not sure I see the real need for this.

**Comment by Fuuzetsu** [comment]
@ff2000 A named tag automatically puts stuff in the Releases tab

@CDrummond IMHO you don't have to bother with such old releases. I'm just after *something* to point at as a packager. So until next release, that page you just posted should do fine.

**Comment by CDrummond** [comment]
Shall I close this issue then?

**Comment by Fuuzetsu** [comment]
Well, it'd be nice to have tags regardless but seeing as the release page has been replicated, packagers can make do with that for now. For future release I hope you'll be able to tag the relevant commits though!

As usual thanks for great software.
