### ISSUE TITLE
On application opening, window is not maximized [Windows 7 x64]

### ISSUE THREAD

**Issue by edster69** [CDrummond/cantata#672]
Not an important bug, but one that's annoying for me at least. When opened in Windows 7 x64 on my system, the Cantata window is not maximized and is shifted to the left, obscuring many of the controls.

This would not normally be a problem, but on my 16:10 display, I have the taskbar on the left-hand side to maximize screen space, and it's the taskbar that obscures some of the Cantata controls. (See screenshot)

Therefore, on each opening I have to maximize the window. Not sure if this is unique to my setup or common for everyone, but I thought I'd mention it as just takes the shine of an otherwise excellent product.

![grab](https://cloud.githubusercontent.com/assets/12415838/7594330/c3020a2e-f8d7-11e4-948e-a5811cb54221.png)

**Comment by CDrummond** [comment]
Odd. I'll try to look into this before the next release. However, I don't actively use Cantata under windows.

**Comment by edster69** [comment]
Thanks!

**Comment by CDrummond** [comment]
It's been a while, but I think this is now fixed. Can you compile under windows? If so, checkout git/master

**Comment by edster69** [comment]
I'm afraid I have no clue how to compile. Sorry.

**Comment by CDrummond** [comment]
Thought that might be the case :-) I'll try to upload a test build in a couple of days (got some rough edges to iron out first).

**Comment by CDrummond** [comment]
Can you try the version here: https://temp-share.com/f/olcxfrjiuo

...this is a pre-2.0 release, so don't expect it to be 100% bug free :-)

**Comment by edster69** [comment]
Yep, that works fine! It seemed to remember the bad position settings from the previous install on first startup, but after maximizing the window it now no longer overlaps the taskbar.

(quickest test ever eh?) ;¬p

Thank you!

**Comment by CDrummond** [comment]
Yeah, that was quick! As to the wrong size initially - yup, that was expected. If the window is maximised when closing, I store the size as 1x1. Then when starting, if 1x1 is the stored size, the window is shown maximised. Hence, with your initial settings the stored size would not have been 1x1, so it would not have been set maximised.

Anyway, thanks for the confirmation.
