### ISSUE TITLE
Remember song last played in a playlist

### ISSUE THREAD

**Issue by notargets** [CDrummond/cantata#674]
I'm using Cantata 1.5.2 and mpd 0.19.9 under Manjaro Linux, with customized mpd settings (because I can't select a specific Pulseaudio output sink from Cantata).

Is there a way to remember both the playlist and the song that was last played in it, so that I don't have to select it manually every start-up?

**Comment by Fuuzetsu** [comment]
This is the job for MPD, you need to set a state file and it will do just that:

http://mpd.wikia.com/wiki/How_To_Create_a_State_File

**Comment by notargets** [comment]
I've taken a look and it turns out I already had such a file. Now the problem is that the queue is remembered only when I exit and restart mpd *while* Cantata is running. If Cantata is restarted while mpd is running, the queue becomes empty and tracks are playable only if they are readded from the playlist three times in a row.

I don't think it's Cantata's fault because I have the same problem with ncmpc. Still, I have no idea what's wrong.

**Comment by Fuuzetsu** [comment]
>If Cantata is restarted while mpd is running, the queue becomes empty and tracks are playable only if they are readded from the playlist three times in a row.

Sounds like something is seriously wrong with your setup. It all just works with Cantata for me, after all, all it does is probe mpd for its state and display it accordingly. The chances that the fix should go into Cantata is rather low…

**Comment by CDrummond** [comment]
Are these tracks from MPD's database? Cantata will remove any non-MPD tracks from MPD when Cantata closes.

**Comment by notargets** [comment]
Thank you, @CDrummond, I didn't know that. I have set up a music directory and managed to get closer to solving the problem, but I'm still not there yet.

Now I can add files from the database from ncmpc to the queue, and those files appear and stay there in Cantata as well, even after I restart it. However, when I drag-and-drop the same files from the same directory from my file manager (Krusader) to Cantata, those ones still disappear after restart.

**Comment by CDrummond** [comment]
That is because when you add them via drag-n-dop, they are no longer MPD files - but are considered to be non-MPD files. Cantata uses an internal HTTP server so that MPD can access these files. Obviously, when Cantata terminates so does this server - hence they are removed from the playqueue.

Do you connect to MPD via a UNIX socket (i.e. /var/run/mpd.socket) or via a TCP socket (e.g. localhost:6600) ?

**Comment by notargets** [comment]
A TCP socket.

**Comment by CDrummond** [comment]
Then, to play local non-MPD files requires Cantata's inbuilt HTTP server. If you stop Cantata, MPD can no longer access these - hence Cantata removes them when it quits.

Not sure what else it can be expected to do...

**Comment by CDrummond** [comment]
Cantata is working correctly.
