### ISSUE TITLE
cantata-tags cannot be opened because of a problem.

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#675]
on mac os x, Cantata mostly works but often throws this error. 
when i went to go report the error i get this information: 
```
Process:               cantata-tags [24425]
Path:                  /opt/homebrew-cask/*/Cantata.app/Contents/MacOS/cantata-tags
Identifier:            cantata-tags
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        cantata [22577]
Responsible:           cantata [22577]
User ID:               501

Date/Time:             2015-06-15 23:07:33.010 -0400
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11



Time Awake Since Boot: 6400 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Users/craig/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /opt/homebrew-cask/*/Cantata.app/Contents/MacOS/cantata-tags
  Reason: image not found
```
note: my username is not craig

**Comment by CDrummond** [comment]
Is this a self build? Or is it from the released version? If its not the released version, can you try that?

**Comment by 3marcusw** [comment]
i got the build from brew cask, is there a designated binary download i can test?

**Comment by CDrummond** [comment]
The wiki page has the links to the old releases - https://github.com/CDrummond/cantata/wiki/Previous-(Google-Code)-Downloads

This is the one you should try: https://drive.google.com/uc?export=download&id=0Bzghs6gQWi60WmNlSDh6dTVzYTg

**Comment by 3marcusw** [comment]
Yeah, it has the same problem unfortunately. However, i constructed a ```/Users/craig``` folder and copied Qt (with all the libs and such in their original hierarchy) into that which got the message to stop showing up.
![screen shot 2015-06-17 at 11 48 39](https://cloud.githubusercontent.com/assets/3537909/8211953/1e8e93f0-14e7-11e5-9422-991104e0280c.png)

**Comment by CDrummond** [comment]
Oh. I thought the libraries were in the .app folder? No? Don't have access to a Mac right now...

**Comment by 3marcusw** [comment]
they are inside the app folder, but cantata-tags must me looking in the wrong place
![screen shot 2015-06-17 at 20 04 55](https://cloud.githubusercontent.com/assets/3537909/8221422/4bb8da62-152c-11e5-929a-f6de0873345c.png)

**Comment by CDrummond** [comment]
Hmmm... odd. An I take it cantata-replaygain has the same issue? Don'r have a great deal of access to a Mac at the moment, and busy elsewhere. But I will try to look at this issue soon.

**Comment by 3marcusw** [comment]
I haven't seen an error dialog box like this
![screen shot 2015-06-18 at 16 41 47](https://cloud.githubusercontent.com/assets/3537909/8242008/9079fa88-15da-11e5-9cb1-689aec83c9af.png)
 for cantata-replaygain, but i didn't think replaygain was supported for OSX. At least, the README says only linux supports it. I've never used replaygain in any music player before, but checking the "auto" box for replaygain in preferences doesn't seem to do anything.

**Comment by CDrummond** [comment]
The replaygain settings in the settings dialog affect how MPD will read and use the tags.

cantata-replaygain is used to scan your files, and write replay gain tags. But, you are right - it is only for Linux. It uses the libav/ffmpeg libraries - and I could not be bothered to install/test these on Win/OSX.

I'll try to look at these OSX issue in a few weeks.

**Comment by CDrummond** [comment]
Been a while, sorry! But I've finally got round to looking into this - and hopefully fixed it. Can you checkout the latest master, and build?

Also, cantata-replaygain does build for OSX - you need to brew install ffmpeg

**Comment by 3marcusw** [comment]
Yeah, i just built the latest master, and it builds ok with Qt Creator 3.4.1 (though with some warnings about deprecations). This problem seems like it is fixed.

**Comment by CDrummond** [comment]
Thanks for confirming.

**Comment by CDrummond** [comment]
What were the deprecations?

**Comment by 3marcusw** [comment]
it looks like its from ffmpeg 
```
/usr/local/Cellar/ffmpeg/2.7.1/include/libavcodec/avcodec.h:1139: warning: 'destruct' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/2.7.1/include/libavcodec/avcodec.h:1139: warning: 'destruct' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/2.7.1/include/libavcodec/avcodec.h:1139: warning: 'priv' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
/usr/local/Cellar/ffmpeg/2.7.1/include/libavcodec/avcodec.h:1139: warning: 'priv' is deprecated [-Wdeprecated-declarations]
typedef struct AVPacket {
               ^
```
