### ISSUE TITLE
Play queue not updated

### ISSUE THREAD

**Issue by Abramow** [CDrummond/cantata#676]
Hi,

I am using Cantata 1.5.2 on an Ubuntu 14.04. system. From time to time (havn't figured out when exactly yet) I encounter the following problem:

When I add to or replace the current play queue, the mpd behaves as wanted, meaning plays the new queue, but the shown queue does not change. It is only the queue which is not up-to-date, e.g. the current song and progress bar at the top are fine.

After a restart of cantata everything is fine again. 

Thanks for your help and thanks for a very good software!

**Comment by CDrummond** [comment]
Have you tried other clients? As Its working fine for me with Ubuntu 15.04

**Comment by Abramow** [comment]
Yes, I am using MPDroid on my Android smartphones to control the mpd without a problem. On ubuntu I tried sonata.... but I will test if the problem is there, too. But I think it is not an issue of the mpd...

**Comment by CDrummond** [comment]
Well, cantata listens for playqueue changes - and only updates the parts that have. (There is an MPD command to get jsut the changes, not the whole queue again) I think MPDroid just gets the whole queue again.

Anyway, as I said - its working 100% fine for me. Both on Ubuntu 15.04 (and earlier versions), and on a Pi with Raspbian.

Are you using a laptop? Has the laptop/computer been suspended whilst Cantata was running?

**Comment by CDrummond** [comment]
Which version of MPD are you using?

**Comment by CDrummond** [comment]
Well, works for everyone else - and no updates for 18 days.
