### ISSUE TITLE
Cant edit keyboard shortcuts in Cantata on OS X

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#678]
when i go to add a new or change an existing keyboard shortcut in Cantata's preference, it is broken. I try to select the "Custom" radio button, but it immediately deselects itself. 

[demonstration](https://gfycat.com/MildLittleJohndory)

**Comment by CDrummond** [comment]
Actually, just noticed this affects the Linux Qt builds too :-( Only seems to be some shortcuts - those that don't already have a shortcut.

I'll try to fix this for the next release.

**Comment by 3marcusw** [comment]
ok. also, im not sure if i should file this as a separate bug, but when assigning keyboard shortcuts it is impossible to have one without a modifier key. For example, if i want "a" to mean add the song to the play queue, i cant do it. I'm forced to use "alt a" or similar.

**Comment by CDrummond** [comment]
As for needing a modifier - that is the way it is. Sorry, but I'm not going to implement single key short-cuts,

**Comment by CDrummond** [comment]
Just played about with this, and I *can* add a shortcut to an action that did not already have one. The trick is you need to press the button next to 'Custom' and enter the short-cut. This feels a bit odd - but it does work.

The code for this was taken from the Quassel IRC client - and I've just checked that it also works this way (even the latest source).

So, can you try this again?

**Comment by 3marcusw** [comment]
Yeah, unintuitive but it does work.

**Comment by CDrummond** [comment]
I've updated the code now to leave the 'Custom' radio selected.
