### ISSUE TITLE
Double Click to play top view

### ISSUE THREAD

**Issue by lainlives** [CDrummond/cantata#679]
I cant seem to play an entire album via double clicking the album name.

**Comment by roberth1990** [comment]
+1 Also on the album art.

**Comment by CDrummond** [comment]
Yeah, fair point. Double click works on a track - so should work on albums/artists. Will try to implement for the next release.

**Comment by CDrummond** [comment]
This is sort-of related to https://github.com/CDrummond/cantata/issues/541

Anyway, as stated in that report you can easily add an entire album, or all albums by an artist, by using the + and |> icons. Therefore, double click does not provide much else.
