### ISSUE TITLE
Add option to prepend to play queue, "Play Next"

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#680]
It would be nice if there was an option to add an item to the beginning of the play queue("Play this now, but don't clear out my queue"). It would also be cool if one could insert an item right after the current item("Play this next, and keep my queue intact"). I know these things are technically possible with dragging and dropping, but having a menu item and an associated keyboard shortcut would make it a lot more efficient.

**Comment by CDrummond** [comment]
Not sure about this., The menu is already large enough as it is. Why is a menu item preferable to just drag'n'drop?

**Comment by 3marcusw** [comment]
mostly i'd just want a keyboard shortcut as i find it quicker to navigate without the mouse. The menu item i don't really care about but i thought it might be necessary for implementing the shortcut.

**Comment by carnager** [comment]
@CDrummond: Actually a proper "insert" option would be nice. This should always apply a priority so it works whatever mode mpd is in. mpc does it just like that in latest release, too.

**Comment by CDrummond** [comment]
Drag'n'drop **is** is proper insert. Cantata is a **graphical** client.

Anyway, why should a priority *always* be applied?

**Comment by CDrummond** [comment]
Implemented in git/master
