### ISSUE TITLE
"Clear "playlist" opens confirmation widget in completely different location

### ISSUE THREAD

**Issue by ff2000** [CDrummond/cantata#681]
It also doesn't get focus, which would enable me to just hit <ENTER> or <ESC>.
That makes clearing a harder task than it could be. I have to move over the whole screen (several times, because clearing usually is followed by selecting new songs from the media library, which sits on the left side)

**Comment by CDrummond** [comment]
Well clearing the playqueue is destructive, so should be 'hard'

Anyway, you can always disable the confirmation prompt - look in the settings dialog.

**Comment by ff2000** [comment]
CraigD wrote:
> Well clearing the playqueue is destructive, so should be 'hard'

Confirmations actually don't have to be hard. Making regular tasks harder might only make the user angry (and act without thinking ;) )
A "Popover" IMHO would be the best way. I already thought of swapping out bottom toolbar with confirmation widget.

> Anyway, you can always disable the confirmation prompt - look in the settings dialog.

I know about that option. But I actually want to confirm such destructive actions. If there was an undo/redo stack I probably would deactivate confirmation - probably confirmation could be disabled completely...

**Comment by CDrummond** [comment]
There is an undo/redo for the playqueue :-)

But, I do agree the message widget is NOT the correct place for this. But, I'm not sure a pop-over is correct either - as it would be inconsistent.

**Comment by CDrummond** [comment]
I think the confirmation should be disabled by default, but if it is enabled then I'll probably just use a regular messagebox.
