### ISSUE TITLE
Sort collection by date-added

### ISSUE THREAD

**Issue by eikehein** [CDrummond/cantata#682]
I'm not sure if this is possible - depends on whether mpd adds a timestamp to its db when it finds a new file - but I'd love to be able to sort the collection tree (quickly, temporarily) by date-added to easily find albums I've added to the collection recently.

**Comment by CDrummond** [comment]
Use the search page, you should (at least with newer MPDs) be able to search on date.

**Comment by eikehein** [comment]
Thanks, found that now, although the user experience is a bit inconvenient since you really have to write a date component as search pattern so you can't combine the sorting with other search criteria, nor with the grouping the collection tree can do for you.

**Comment by CDrummond** [comment]
For the next release I /might/ make it possible to sort the albums-view by date modified - does not make much sense for artists.

**Comment by CDrummond** [comment]
This (sorting albums via modified) is now in the devel branch. Please not, however, that this branch ,s under heavy development and is not ready for day to day use. But will be the next, 2.0, release.

**Comment by eikehein** [comment]
Thanks! Looking forward to future versions.

**Comment by CDrummond** [comment]
the devel branch has now been merged into master. code is still not 100% release ready...

**Comment by eikehein** [comment]
> code is still not 100% release ready...

Right now it doesn't even build I'm afraid, due to signature mismatches for MessageBox::questionYesNo in onlinedbwidget and podcastwidget :).

(And the usual problem with the KDE version not building due to KDE/KGlobal not being found, unless I patch the top-level CMakeLists.txt.)

**Comment by eikehein** [comment]
Where can I find the feature, btw? "Albums" isn't in the view list in the config dialog ...

**Comment by CDrummond** [comment]
What usual KDE issue? Please file bug reports for separate issues. A closed bug report will not be looked at often.

Is the build still failing?

Please understand master is under heavy development - and is *not* ready for an actual release.

To select the 'Albums' view, click on the button bottom left in Library view - this wil have a group by option. Select 'Album' then when you re-open the menu, the sort sub-menu will have 'Date Modified' (or something like that) which can be used to perform the required sort.

**Comment by NewbieSone** [comment]
> What usual KDE issue?

The KDE/KGlobal include not being found due to find_package/add_definitions for the KDE 4 stuff not being done early enough in all codepaths through the CMakeLists.txt - it's been going on for almost two years, I submitted the patch at some point. The version I have currently is an ad-hoc recreation I had to do at some point that doesn't insert it in the right place but just for all builds, so I'd have to put some work into doing it properly again.

> Is the build still failing?

No, seems fine now (other than the above) :)

> To select the 'Albums' view, click on the button bottom left [...}

Ah! Tried it, works very nicely. Thanks!

**Comment by eikehein** [comment]
> What usual KDE issue?

The KDE/KGlobal include not being found due to find_package/add_definitions for the KDE 4 stuff not being done early enough in all codepaths through the CMakeLists.txt - it's been going on for almost two years, I submitted the patch at some point. The version I have currently is an ad-hoc recreation I had to do at some point that doesn't insert it in the right place but just for all builds, so I'd have to put some work into doing it properly again.

> Is the build still failing?

No, seems fine now (other than the above) :)

 > To select the 'Albums' view, click on the button bottom left [...}

Ah! Tried it, works very nicely. Thanks!

**Comment by CDrummond** [comment]
Sorry if I missed, or did not apply, a patch. Please forward your updated CMakeLists.txt. Odd that it works fine for my KDE builds...

**Comment by eikehein** [comment]
Apologies for my unresponsiveness, I've been terribly busy with pre-vacation work crunch ...

Here's the diff I have: https://paste.kde.org/pt8cmugma/9aw725

As mentioned that's stupid and just me brute-force copy-and-paste'ing things to get it to build; I took the time to figure out where it needs to be exactly once but lost that version. Without it's never been building on Fedora KDE systems for ~two years though. Downloading the Fedora 22 KDE CD and doing 'dnf builddep cantata' and then trying to build a git clone manually should be enough to reproduce. Alternatively I can put the time into working it out and submitting a proper patch in September when I get back.
