### ISSUE TITLE
Add quick seach filter to Cantata playlist and other lists

### ISSUE THREAD

**Issue by MurzNN** [CDrummond/cantata#683]
Will be good to have "Quick filter" line for quick searching (filtering) current long list by keyword. It will be useful in Play queue, Tracks, Folders and other tabs too.

For example, typing "ions" will hide all other items without this line, so in window will stay items with "Scorpions", "Lions" and other match words.

Also good feauture will be filter not by full substring, but for each word, so typing "scorp wind" will show "Scorpions - Wind of Change".

Can you add this? Thanks!

**Comment by CDrummond** [comment]
Have you tried Find (Ctrl-F) ???

**Comment by MurzNN** [comment]
Ow, thanks! =) Will be good to see big button "Filter" or permanent line in interface.

**Comment by CDrummond** [comment]
Why? Leave it open when you close Cantata, and it will be there when you re-start.

I'ts not there by default as it clutters the UI, and is not something  use. Its not as if Ctr-F, etc, is non-standard.

**Comment by MurzNN** [comment]
I already try to keep it open, close cantata, open again and see that it is hidden.
For not clutters the UI - maybe add menuitem in Settings "Show search bar" like "Show menubar"? 

Before create this issue - I scan all menus, buttons and settings in Cantata inferface for find this search bar (I don't look Shortcuts table), but find nothing, so I decided that this function is absent.

Maybe other users have the same problem, so menuitem shows at least that this feature exists.

**Comment by MurzNN** [comment]
Also quick find (Ctrl+F hotkey) not work on "Play Queue" tab in version 1.5.2 :(
