### ISSUE TITLE
All external packages found, yet standard options disabled

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#684]
On an Ubuntu system I ran: `cmake .. -DCMAKE_INSTALL_PREFIX=$HOME_LOCAL`

I was told: `Congratulations! All external packages have been found.`

And then `The following STANDARD options have been DISABLED.`.

I'm a bit puzzled: I didn't ask for any option to be disabled; I supplied all the external packages. It seems to me that either those options should not be described as "standard", or they should be enabled.

I definitely did have all the build deps required, because when I tried again with:

`cmake .. -DENABLE_STREAMS=ON -DENABLE_DYNAMIC=ON -DENABLE_ONLINE_SERVICES=ON -DCMAKE_INSTALL_PREFIX=$HOME_LOCAL`

I got no message about options being disabled.

This was all with current master head as of the time of writing: c46bc090a67c

**Comment by CDrummond** [comment]
Oops! Should be fixed now.
