### ISSUE TITLE
System tray icon shows incorrect key shortcut

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#685]
Running on Ubuntu 14.04, the indicator icon's menu claims that "Ctrl+Q" is a shortcut for quit. It's not, of course, even if the menu is open when I press it. I guess it's showing the application's quit shortcut by mistake?

I built cantata from current master head: c46bc090a

**Comment by CDrummond** [comment]
Which desktop? Just tried under Unity on 15.04, and there are no shortcuts shown in the indicator menu.

Why is Ctrl-Q not valid? It is the default quit short-cut.

**Comment by rrthomas** [comment]
Using GNOME 3.10.

Ctrl+Q is not valid in the system tray menu because Cantata does not have the keyboard focus at that point (even if the menu is open), so pressing Ctrl+Q goes to whatever does. Only global shortcuts work at that point (and Ctrl+Q for quit is not one of those).

**Comment by CDrummond** [comment]
The Ctrl-Q comes from the short-cut assigned to the action - this is a Qt thing. As it does not appear in Unity, I'd suspect this is a GNOME issue.

What about other Qt apps with system tray icons? e.g. VLC and Clementine. Do they show the short-cut under GNOME?

**Comment by rrthomas** [comment]
VLC shows Ctrl+Q for quit on its main menu, and nothing on its systray icon, i.e. just what I'd expect.

**Comment by CDrummond** [comment]
Can you update, and try now? I've added some code to copy the action (without short-cut), this should work-around the issue.

**Comment by rrthomas** [comment]
You, sir, are a wonder-worker. (For avoidance of doubt: yes, it's exactly as expected now: shortcut visible in app main menu, nothing in systray menu.)

**Comment by CDrummond** [comment]
Thanks for the confirmation :-)
