### ISSUE TITLE
Cantata prompts to download catalogue it's already downloading

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#686]
While engaging in some fancy footwork with the mouse to try downloading both Jamendo and Magnatune's catalogs simultaneously, I tried going back into the Jamendo section after starting the download and was again given the prompt that this would necessitate a download, with a "Download now" button. On cancelling, I found that the download had in fact now completed.

Should this prompt not be disabled once downloading the catalog has started, and only re-enabled if the download does not complete?

**Comment by CDrummond** [comment]
Fixed now

**Comment by rrthomas** [comment]
@CDrummond thanks for doing an amazing job with all those issues I've posted!
