### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#687]
As of yesterday, and tested again with up-to-date master head, 9d8389839, search produces no results. I type a single common letter, such as "a", and get empty results.

Since my library is correctly displayed and since cantata caches the info it gets from mpd, I'm assuming it's not mpd that's the problem (but it was working fine before: Ubuntu 14.04's 0.18.7). At any rate, I couldn't see anything suggesting a newer version was required.

**Comment by CDrummond** [comment]
Tried more than 1 letter?

**Comment by rrthomas** [comment]
Sure, I started with looking for whole words, as normal. When that didn't work I tried shorter terms (which should get more results), in case it wasn't searching on the field I was looking for.

**Comment by CDrummond** [comment]
Just tried, and search is working for me - even just a single letter.

If you run cantata from the commandline as follows, it will log all MPD communications:

CANTATA_DEBUG=-1 cantata

When you search, you should see something like:

sendCommand: "search album "iron maiden"" true true

**Comment by rrthomas** [comment]
Thanks very much for your help with tracking down this problem.

I ran cantata as you said, and did a search: specifically, I focussed the search box, and typed some letters. I think Cantata has done a search, because the list of albums it was showing disappears (as if there are no hits).

However, when I look at the debug log, I see no search commands being sent (I can see plenty of other "sendCommand" entries in the log, so I think the logging is working.

I tried pressing Return in the search box, but that didn't seem to make a difference.

**Comment by CDrummond** [comment]
Where are you performing the search? In the Library view (which just does a filtered SQL select), or in the 'Search' view - which does a search using MPD?

If using the searchview, what type are you searching on? You can select the 'search type' by clicking on the label next to the field - this will produce a menu of the supported types.

**Comment by rrthomas** [comment]
I'm searching in the library view (hence why originally I thought it wasn't calling mpd, as indeed it's not!).

I can't see how to get the search view (other than the search function for the various Internet categories): I can't see any other way to search than the Find function (Ctrl+F) which seems to focus the search box in the library view, or the current internet category.

Sorry if I'm being dense; this part of the interface seems to have changed recently.

**Comment by CDrummond** [comment]
In the main settings dialog, go to the interface section - there you can control what views are shown.

As to the search in the library view - this indeed does not work for 1 character. not sure if it should or not, as it might be quite slow. But, it does wortk for me. All I can suggest is that you stop cantata, and delete its sql files in ~/.local/share/cantata/library Then restart cantata - this will cause it to recreate the DB's with the correct tables, etc.

**Comment by rrthomas** [comment]
OK, thanks for explaining how to get mpd search. I activated it, it works.

Back to Ctrl+F (library search). I stopped cantata, removed the one .sql file (whose name was localhost_6600.sql, which corresponds to my mpd server), started cantata again; a file of the same size (2.7Mb) was almost instantly created.

I tried searching for "winter". No results. If I try in the search panel, type "Any:", I get 32 tracks. I tried a number of other words, again, no results.

**Comment by rrthomas** [comment]
Actually, I'd be quite happy to just use mpd search instead (I've mapped Ctrl+F to that for the moment): it's fast, it works incrementally (this is why I mentioned typing a single letter). Is SQL search intended for when e.g. your mpd is on another machine? For me at least, mpd search returns within a fraction of a second after stopping typing. 

However, I'm happy to continue tracking down the bug with Find (at least, if you think there's a problem: since deleting the SQL file and letting it be recreated and then searching for known-to-exist words doesn't work!).

**Comment by CDrummond** [comment]
The search in the library view only filters on artist, album-artist, album, or song title. Just tried, and its still working fine.

starting cantata with:  CANTATA_DEBUG=-0x00040000 cantata

(Notice the -ve number) should produce something like:

MpdLibraryDb getArtists "SELECT distinct artistId, albumId, artistSort FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match ?"

This is with the Library set to group by Artist - what is your grouping set to?

**Comment by rrthomas** [comment]
I have it set to group by Album. I ran Cantata as you said, and typed "Winter" (which appears in at least one album title—a recording of Winterreise).

I can't see anything in the debug output that pertains to this search. At the end of the log it says:

    MpdLibraryDb getAlbums "" "" 
    MpdLibraryDb getAlbums "" 
    MpdLibraryDb getAlbums After select 0 
    MpdLibraryDb getAlbums After sort 0 

Before that is a number of lines starting `MpdLibraryDb getCoverSong" with an apparently random selection of album titles, some of which looks like this:

    MpdLibraryDb getCoverSong "Fernando Lagreca" "[APL041] Colpi Di Sole" 
    MpdLibraryDb getCoverSong coverquery "select * from songs where artistId=? and albumId=? limit 1;" -1 
    MpdLibraryDb getCoverSong "Charles Aznavour" "20 chansons d'or" 
    MpdLibraryDb getCoverSong coverquery "select * from songs where artistId=? and albumId=? limit 1;" -1 
    MpdLibraryDb getCoverSong "King's Singers" "40th anniversary Prom 5th August 2008" 
    MpdLibraryDb getCoverSong coverquery "select * from songs where artistId=? and albumId=? limit 1;" -1 

That is preceded by:

    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums "SELECT avg(year), count(track), sum(time) FROM songs WHERE artistId = ? AND albumId = ?" 
    MpdLibraryDb getAlbums After select 84 
    MpdLibraryDb getAlbums After sort 85 

Finally, I tried grouping by Artist and doing more searches. After a number of lines searching on apparently every artist in my collection, immediately after typing a name I get a number of lines like this:

    MpdLibraryDb getArtists "" 
    MpdLibraryDb getArtists "" 
    MpdLibraryDb getArtists "" 
    MpdLibraryDb getArtists ""

**Comment by CDrummond** [comment]
Looks like your sqlite DB does not have the songs_fts table. Which version of sqlite do you have installed?  fts is sqlite's 'full text search' - it is used to quickly search multiple fields.

Looking at /usr/include/sqlite3.h, I have 3.8.7.4

**Comment by rrthomas** [comment]
3.8.2, as supplied with Ubuntu 14.04. As far as I can tell, it has FTS3/4 (these are mentioned in changelogs for earlier versions).

**Comment by CDrummond** [comment]
Do you have sqlitebrowser installed? Or something to look at SQLite DBs? If so, have a look at one in ~/.local/share/cantata/library  

Does it have a songs_fts table?

**Comment by rrthomas** [comment]
No, it doesn't have the songs_fts table.

**Comment by CDrummond** [comment]
Then that is why the search is not working.  If you have sqlitebrowser, can you try typing the following in the SQL window?

create virtual table songs_fts using fts4(fts_artist, fts_artistId, fts_album, fts_title, tokenize=unicode61);

**Comment by rrthomas** [comment]
OK, I created the table, verified it's there, saved the database (reopening in sqlitebrowser shows it's still there). I restarted cantata, search produces no results.

**Comment by CDrummond** [comment]
I know. I just wanted to know if the above command worked for you. Working out why this is not working is why I asked. It could be that the syntax I was using only works in a later version of SQLite. I just wanted to know if the command, as used by Cantata, works for you.

Text search (in the Library view and Jamendo/Magnatune) will NOT work without this table.

The reason it did not work when you restarted cantata, as it was not populated after you created it. When Cantata gets the song list from MPD it will populate the songs and songs_fts tables..

**Comment by rrthomas** [comment]
Thanks for the explanation! As I don't have time right now to help actually dig in the code which in any case you obviously know far better, I'll continue as your remote control robot for the remainder of this investigation.

**Comment by CDrummond** [comment]
(This is just out of curiosity...)

What happens if you get Cantata to do a full DB refresh? This should clear the DB contents, fetch the data from MPD, and populate the DB. Which should also include filling the songs_fts table...

**Comment by rrthomas** [comment]
The songs_fts table is still there, but doesn't contain anything after the full refresh. I first updated cantata to git master HEAD again since there are a few more commits since last time (though nothing that looks pertinent to this problem).

**Comment by CDrummond** [comment]
I've added a bit of debug info if FTS creation fails. Can you delete the cantata SQL files and re-run with 

starting cantata with: CANTATA_DEBUG=-0x00040000 cantata

**Comment by rrthomas** [comment]
Bingo:

    MpdLibraryDb init 0x1b799a0 Failed to create FTS table "unknown tokenizer: unicode61 Unable to fetch row"

**Comment by CDrummond** [comment]
Getting there... please update and try again...

**Comment by rrthomas** [comment]
MpdLibraryDb init 0x3027050 Failed to create FTS table "unknown tokenizer: unicode61 Unable to fetch row" trying again with simple tokenizer 
    MpdLibraryDb init 0x3027050 Failed to create FTS table " "

**Comment by CDrummond** [comment]
Oops! Silly typo, please try again!

**Comment by rrthomas** [comment]
MpdLibraryDb init 0x1865240 Failed to create FTS table "table songs_fts already exists Unable to execute statement" trying again with simple tokenizer 
    MpdLibraryDb init 0x1865240 Failed to create FTS table "table songs_fts already exists Unable to execute statement"

**Comment by rrthomas** [comment]
I had to delete the SQL file once more, and now it works, great!

**Comment by CDrummond** [comment]
Cool. I've changed the code again, to only try to create the table if it does not already exist.

So, with this simple tokenizer does it match queensryche to Queensrÿche (I always forget the name of the letter with the dots, etc)

**Comment by CDrummond** [comment]
Closing, as this is now fixed.

**Comment by rrthomas** [comment]
Thanks so much for fixing the underlying bug. It does not match letters with diacritics as-is, sadly, which for me is highly desirable in search functions (obviously should be locale-sensitive, as in some locales (certain) letters with diacritics count as different letters, e.g. å in Swedish).

**Comment by CDrummond** [comment]
That's because its using the 'simple' tokenizer. To fix the diatrics you need to upgrade sqlite - or build it with that tokenizer enabled.

**Comment by rrthomas** [comment]
Great, so it will sort itself out eventually!

-- 
http://rrt.sc3d.org
