### ISSUE TITLE
Crashing when using Kvuantum qt style

### ISSUE THREAD

**Issue by cesasol** [CDrummond/cantata#689]
When using Kvuantum as qt style it inmediatly crashes
https://github.com/tsujan/Kvantum

$ cantata
[1]    27837 segmentation fault (core dumped)  cantata

**Comment by CDrummond** [comment]
Please recompile cantata with debug, and then run in gdb to find where the crash is.

**Comment by CDrummond** [comment]
So, bug was in style....
