### ISSUE TITLE
CMake compilation error 

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#691]
I have a compilation error using CMake with the QT5 option.
System : Debian Testing
GIT revision : commit 915b6294f604cdd09d3c0b571e47f2b08c3a72fd

Error :

/home/edhelas/Logiciels/cantata/gui/interfacesettings.cpp: In constructor ‘InterfaceSettings::InterfaceSettings(QWidget*)’:
/home/edhelas/Logiciels/cantata/gui/interfacesettings.cpp:134:12: error: ‘devicesView’ was not declared in this scope
     REMOVE(devicesView)
            ^
/home/edhelas/Logiciels/cantata/gui/interfacesettings.cpp:52:5: note: in definition of macro ‘REMOVE’
     w->setVisible(false); \
     ^
/home/edhelas/Logiciels/cantata/gui/interfacesettings.cpp:135:12: error: ‘devicesViewLabel’ was not declared in this scope
     REMOVE(devicesViewLabel)
            ^
/home/edhelas/Logiciels/cantata/gui/interfacesettings.cpp:52:5: note: in definition of macro ‘REMOVE’
     w->setVisible(false); \
     ^
CMakeFiles/cantata.dir/build.make:1895: recipe for target 'CMakeFiles/cantata.dir/gui/interfacesettings.cpp.o' failed
make[2]: *** [CMakeFiles/cantata.dir/gui/interfacesettings.cpp.o] Error 1
CMakeFiles/Makefile2:62: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CDrummond** [comment]
Your checkout is out of date, please update.
