### ISSUE TITLE
Crash on change of preferences

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#693]
I just went into Preferences→Interface, and under Views switched on both Folders and Info, thereby leaving everything switched on except Play Queue. I had never selected either of these before as far as I know. When I clicked OK, cantata crashed.

Unfortunately I wasn't running with debugging on, so I don't have any more information. I can't find a core dump either.

When I tried toggling those preferences again after restarting Cantata, I was unable to provoke further crashes, which is why I lay stress on the fact that I had never set these preferences before.

**Comment by CDrummond** [comment]
Yeah - I had a crash before, and could not recreate.

**Comment by CDrummond** [comment]
...and indeed, still can't recreate. Anyway, I will leave this open - as there is a bug in there somewhere!

**Comment by CDrummond** [comment]
Have you seen this again? Its been 2 months (with many changes) and I have not seen this again. I'm tempted to close for now...

**Comment by rrthomas** [comment]
No, but of course I haven't tried. I agree that it may as well be closed.

**Comment by CDrummond** [comment]
Closing for now. Feel free to re-open, or create a new report if it happens again.
