### ISSUE TITLE
Add to/replace play queue GUI controls should apply to selection

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#694]
When there's a selection, these controls should apply to the whole selection, no longer the current item. Or, or perhaps and/or, have a shortcut for Add to/Replace play queue by default.

**Comment by CDrummond** [comment]
The 'mouse-over' controls do indeed only apply to the item they are over. The reason being is that they are just painted there, and are not real widgets. So, when you click Qt sees it as 1 click on the item. I guess they should not really appear if there is a selection.

The add/remove elsewhere do apply to the selection. As to pre-defined shortcuts, please feel free to suggest appropriate ones - its easy enough to add to the code...

**Comment by rrthomas** [comment]
Ctrl+P seems already mapped to "add to play queue"; Ctrl+R seems good for "Replace play queue".

**Comment by CDrummond** [comment]
Ctrl+Shift+P / Ctrl+Shift-R

Alt-P / Alt-R ??

**Comment by rrthomas** [comment]
I suggested Ctrl+R because Ctrl+P seems already to be mapped to "add to play queue", but on looking again, I see that I customized it. Sorry!

Alt+Key is normally used for application menus (doesn't apply to Cantata, but would be strange to use, I think).

Why add an extra modifier key when these ones are free? They are pretty central functionality.

**Comment by CDrummond** [comment]
Perhaps. But Ctrl-P is standard for print... I know Cantata does not print, but...

**Comment by rrthomas** [comment]
I agree, and thought "well, Cantata doesn't print". And won't! But equally, I can see a reason not to use such a universal shortcut.

Another option would be to put both on one key, as one is a variant of the other, one with Ctrl and one with Shift+Ctrl.

I tried thinking of other English-mnemonic options, and came up only with equally CUA-ubiquitious ones: Ctrl+A(dd), Ctrl+Q(ueue), …

The GNOME Human Interface Guidelines say: "If your application uses any of the standard functions listed in the following tables, use the recommended standard keyboard shortcut for that function." Ctrl+P is listed in the table: https://developer.gnome.org/hig-book/unstable/input-keyboard.html.en#standard-shortcuts

However, this implies that if your application doesn't use that function, there's nothing to stop you using the combination for another function.

**Comment by CDrummond** [comment]
Default shortcuts added. Closing now, as the icon behaviour is as it has always been,
