### ISSUE TITLE
Find in library uses OR to connect terms, should use AND

### ISSUE THREAD

**Issue by mschuerig** [CDrummond/cantata#700]
Semantics of Find in library has changed more or less recently; after the switch to Github, I think.

Now terms are no longer connected by AND, but instead by OR. I think the older, conjunctive behavior was much more useful and Find in Play Queue still works this way.

**Comment by CDrummond** [comment]
Please, if you are going to use git master (which is under development), then please update before raising issues:

https://github.com/CDrummond/cantata/commit/94859b2a425ee9af6f6a70b862497716a27241b0

**Comment by mschuerig** [comment]
Oops, sorry.
