### ISSUE TITLE
Extremely slow library search, hangs for several minutes

### ISSUE THREAD

**Issue by vibee** [CDrummond/cantata#702]
Today, I rebuilt cantata from trunk. I previously used a trunk version from the old svn repo, rev. 56xx.
I found a major issue concerning the library search function. It became much worse compared to 1-2 months ago. My library is ~400GB large, and mpd is running in my local gigabit ethernet network. There is access to the file system via samba.

That's how you might reproduce the issue:
1. In album view, hit ctrl-F and type only a single letter (for instance 'e' or 'a') and wait shortly, such that the search is started.
2. Cantata completely hangs for several minutes, consuming 100% cpu. After this time, the search result is shown correctly and I can work with canata again. Mostly, I just kill cantata in order to avoid the waiting time.

In order to avoid this issue, I need to type my search request quickly, such that the search engine starts working for an input consisting of more than one or two letters. 

My system:
- Arch linux x64
- cantata-git package from AUR
- Core i7 (3,9GHz)

**Comment by CDrummond** [comment]
Cantata (in master) now uses SQLite to store its cached copy of the DB. The Ctrl-F search is performing a text search on the SQL db. This is currently run from within the UI thread - which will be causing the blocks you are seeing. Odd that they are taking minutes though.

How large is your collection? Even searching the Jamendo DB (which is very large) takes a fraction of a second here. Which version of SQLite have you compiled against?

[ The reason for switching to SQLite was to allow easier groupings - so that Cantata could group by genre ]

**Comment by vibee** [comment]
As said above, my collection is ~400GB, 40000 songs.
My sqlite has version sqlite 3.8.10.2.
This is the script used for buolding cantata:
https://aur.archlinux.org/packages/ca/cantata-git/PKGBUILD
I've also created a debug log file, can I send it to you via Email (if you need it)? When I enter a letter into the search box, there's a lot of the following out produced:
2015-07-20 21:28:41 - MpdLibraryDb getAlbums 0x28da590 "SELECT avg(year), count(track), sum(time) FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match ? AND artistId = ? AND albumId = ?"
2015-07-20 21:28:41 - MpdLibraryDb getAlbums 0x28da590 "SELECT avg(year), count(track), sum(time) FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match ? AND artistId = ? AND albumId = ?"
2015-07-20 21:28:41 - MpdLibraryDb getAlbums 0x28da590 "SELECT avg(year), count(track), sum(time) FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE songs_fts match ? AND artistId = ? AND albumId = ?"

**Comment by CDrummond** [comment]
The disk space used is irrelevant to the track count - 32kbps MP3's take a lot  less space than FLAC files. And it is the amount of tracks that will cause any slowdowns.

40000 songs is not much compared to the Jamendo listing. Is search on Jamendo also slow?

Which grouping are you using for the Library page? Genre, Artist, or Album? Is it slow for all 3?

**Comment by vibee** [comment]
I'm using the "group by album", and using group by artist or genre, there's no problem. Changing view from 'grid' to something else doesn't change anything.

Just downloaded the jamendo DB,  and there's no problem, as it only supports 'group by artists' or 'group by genre'. Reaction time maybe 500ms after typing a single letter.

**Comment by CDrummond** [comment]
I've added an index for the albums query. Please update master, and try again. Before you do:

1. Stop Cantata
2. Delete all files in ~/.local/share/cantata/library/
3. Restart Cantata

...this will cause the DB to be rebuilt, with an index this time.

**Comment by vibee** [comment]
I updateted cantata and deleted the library files, but unfortunately it didn't improve anything.

**Comment by CDrummond** [comment]
How slow is your system? I've managed to recreate the issue by hacking the code so that I can use an albums view with Jamendo. Now whilst the search is by no means quick - it's taking seconds, and not minutes.

**Comment by vibee** [comment]
Searching for 'e' took almost 2 minutes, searching for 'a' is even slower. 
My system is not slow at all, as mentioned above I got an i7, 8GB of RAM and an SSD. 
Just made a screencast, the response is at 1:57:
https://www.youtube.com/watch?v=cRxArSb82Gw

**Comment by CDrummond** [comment]
Ah, yes - forgot that I also hacked it to disallow single character searches. Your system should be *much* faster than mine - mine is also i7, but slow HDD. What about 2 character searches?

Anyhow, I have found a way to speed things up a little. Not ready for a commit - as its just hacked up at the moment. Will work on it more tomorrow.

**Comment by vibee** [comment]
2 letter search is faster, but still causes a lag (for instance 'en' takes ~3 sec, while 'zz' causes no lag).

**Comment by CDrummond** [comment]
Made some changes, can you update, remove your db, and try again...

**Comment by vibee** [comment]
As far as I can see, two things changed:
1. Search input containing one letter only are ignored (feels like a hack, but it's great for now)
2. Searches for two-letter inputs, as described in my previous post, became much faster.

**Comment by CDrummond** [comment]
I've re-enabled single character search - but not really sure how useful this is.

**Comment by vibee** [comment]
Great, one character search causes only ~1s delay now on my i7.

Also great that the search is done isn't run in the main thread any more.

Once again, thank you. :)

**Comment by CDrummond** [comment]
Search is, and always has (even in 1.x), run in the UI thread :-)

**Comment by vibee** [comment]
Oh, ok, I thought so because the very short delay for searching doesn't cause an UI freeze any more.

**Comment by CDrummond** [comment]
No the delay is the delay between the last character being entered and the search starting. It's there so that a new search is not started each time a character is entered, but only when there is a pause in typing.

Closing, as original issue is fixed.
