### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by syntheticpp** [CDrummond/cantata#704]
Have you ever tried to build Cantata for Android.
Would be a real improvement about MPDroid.

**Comment by CDrummond** [comment]
Years ago I did create a QtWidgets based android build, but with no touch scroll support, odd config dialogs, etc, it was not very usable. If I ever did a proper android port I would first need to convert the UI to use QML, but this would be a lot of work. Having said that there is support in the code for a QML based UbuntuTouch build - but I'm not sure this even compiles now. So, some of the work has been done.

I have started to play with creating a HTML5 UI on top of the Cantata code base. The idea is that a 'cantata-web' app would run on a PC that can access MPD (or even on the same machine), this then has a REST API and WebSocket interface. At the moment it's pretty raw, as my HTML5/Javascript is not up to scratch - however you can find the initial (not really usable) work at https://github.com/CDrummond/cantata/tree/master/web
