### ISSUE TITLE
No refresh menu for podcast listings

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#705]
and latest podcast is not available

**Comment by CDrummond** [comment]
I've now added a refresh button to the podcasts page. Is it because refresh is missing that 'latest podcast is not available' - or is this some other issue?

**Comment by parkmino** [comment]
Same issue and thanks for fixing this!
However podcast counts set to "0" when refreshed and latest episodes are added.

**Comment by CDrummond** [comment]
Oops! Sill typo. Fixed now.

**Comment by ultimoboulevard** [comment]
Sorry, CDrummond, I really don't know how to fix it! Could you please help? Posdcasting is really the strong point of your software...
