### ISSUE TITLE
Sorting of Files

### ISSUE THREAD

**Issue by PECgeo** [CDrummond/cantata#706]
On 1.5.2 the file sorting has changed again. I am not enjoying the new sort. My mind has been programmed for to many years to follow things alphabetically, I understand peoples concerns with "a" and "the" but when you go by the last name it really messes the flow. So how does get revert back to a standard file system including a's and the's. I went through great effort with beets to get thing right and I would like to follow that format. The operating systems are KaOS and Debian sid depending on machine
Many thanks

**Comment by CDrummond** [comment]
What are you talking about? Folders view? This code has not been changed for about 3 years.

If you are referring to the fact that "The Beatles" are sorted by "Beatles" - then this is pretty standard behaviour.

Anyway, 1.x is finished - and I have no plans to updated it. I'm currently working on 2.0.0 - and have added an option to control which prefixes will be ignored when sorting (e.g. 'The'). Setting this to empty should achieve what I think you are asking for.
