### ISSUE TITLE
Doubling with cue sheets

### ISSUE THREAD

**Issue by emacsomancer** [CDrummond/cantata#708]
I see a similar issue here: https://github.com/cdrummond/cantata/issues/256  - but that one seems to involve a .cue that references a non-existent file.  I have the problem that .cue seem to double tracks in general.  Is there any way to have an option for Cantata to ignore .cue's altogether?

**Comment by CDrummond** [comment]
I take it this is with git/master? If so, not surprised - I re-added the cue sheet support but did not get round to testing.

Or is it with 1.5.2?

Please supply the version number when creating bug reports.

----------------------

So, you have 1 cue file and a bunch of audio files. The cue file references these audio files? In Cantata's Library view are you seeing tracks listed from the cue file, and from the from the audio files? If you click the '+' or '|>' icon on the album entry - does it also add the tracks twice? (one from cue, and one plain audio)?

**Comment by emacsomancer** [comment]
Sorry. Yes, it's version  1.5.2-2 (From arch repo community/cantata).

Yes, the cues in question reference the audio files in the same directory. The way I add tracks is almost always via "Folders" (because that has an organisation that works for me, as opposed to Albums or Artists, where it can be harder for me to find what I want).

If I add an album using '+' in the Albums view, it only adds the tracks once.  

But when I add from Folders --- which, again, is how I almost always add --- it adds the tracks twice (so, for instance, tracks 1-12, followed by tracks 1-12 again).

Could Cantata just have an option to ignore .cues completely? (Obviously some people might use them for something.)

**Comment by CDrummond** [comment]
Ah, true. I see what you mean. I guess what I need to do is; if folder has a cue file, then use that, otherwise use the files.

**Comment by CDrummond** [comment]
Can you try git/master? Its not ready for full time use yet (at least its not release ready yet), but I have updated the folder view handling as described.

**Comment by emacsomancer** [comment]
I tried git/master. For the standard cases, it now seems to work as desired - i.e. even when there's a .cue in the folder, it still only adds tracks once.

I have at least one edge case with undesired behaviour though - For one directory (for some reason), I have multiple .cue files (it looks like one for a multitrack .wav, one for an individual tracks .wav, and one for an individual tracks .flac) and when I try to add that folder, *nothing* gets added to the play queue. (Although I can select the individual tracks from that directory and add them.)

**Comment by CDrummond** [comment]
Well cantata will be trying to add one of the cue files, probably one which references in valid files. Note sure exactly what to do in this scenario - parsing the CUE files each time you try to add does not seem like a good idea. And really the issue would seem to be that you have an invalid cue file on your system.

**Comment by emacsomancer** [comment]
OK, I have found that perhaps it isn't multiple CUEs, but just .cue files that don't reference existing files.  I have a number of directories that have "whole-albums-as-a-single-file" CUE files, where I have subsequently split into separate tracks.  And Cantata doesn't seem to want to add these directories.

I again come back to wondering if it would be possible to have a "completely ignore CUE files" toggle option somewhere. Since I never actually want to add via CUE files.

**Comment by CDrummond** [comment]
Cantata will ignore these invalid CUE files in the Library view - where it parses the files. In Folders view it just lists the files as sent from MPD.

The real issue is you have invalid files - just remove them. What are they need for if they no longer work?

**Comment by emacsomancer** [comment]
Unfortunately it's non-trivial to remove the invalid CUE files, as there are some CUE files I do want to keep for archival purposes, and no clear way of automating a way to distinguish between good and bad CUEs (and I have a large library).

**Comment by CDrummond** [comment]
In git/master you can now configure Cantata to ignore CUE files. Setting is in Interface/Tweaks page.
