### ISSUE TITLE
The Library view is empty

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#709]
![](http://i.imgur.com/JtloQHt.png)
The Library view is empty, I've shown GMPC on the screenshot to show that there's stuffs in the library.
Commit dcb6bc4eefe0eb38ce5050fd4925dc31c250c30e. 

It's working fine on the same version on an another computer. Any idea on how I can debug that ?

**Comment by CDrummond** [comment]
Is it there if you restart Cantata? What if you select refresh? 

Is there a .sql file in ~/.local/share/cantata/library/ ? Can you install sqlitebrowser, and look at the .sql file?

**Comment by edhelas** [comment]
The sqlite has empty tables (the structures where here but no content) I've removed the file and everything is fine now :)

**Comment by CDrummond** [comment]
Hmmm.... Not sure why the DB would not have been created. Next time you see a similar issue run from the commandline as:

CANTATA_DEBUG=-0x00040000 cantata

...this should log some of the DB transactions.

**Comment by CDrummond** [comment]
I have seen errors such as:

insert failed "UNIQUE constraint failed: songs.file Unable to fetch row" 1427497418 "blah.mp3"

and I will look into this eventually.

**Comment by edhelas** [comment]
Ok I'll keep an eye on this and keep you updated if I can reproduce it ;)

**Comment by CDrummond** [comment]
Closing for now, as this should no longer occur.
