### ISSUE TITLE
Add "description" or "comment" meta tag.

### ISSUE THREAD

**Issue by kovtunos** [CDrummond/cantata#710]
Please add "description" or "comment" field to audio metadata editor.
I use 1.5.2 version on Kubuntu 14.04.

**Comment by CDrummond** [comment]
It already is there. But, you need to enable COMMENT support in mpd's config file.

**Comment by kovtunos** [comment]
Thanks. Enabled it then restarted mpd. Now all changes I do in Cantata's comment field don't save. Tried on flac, ogg, mp3 files. All the same.

**Comment by CDrummond** [comment]
Just tried - works perfectly for me. Cantata uses an external helper app (cantata-tags) which needs to be installed for it to work (Cantata starts the app by using the complete path) /usr/lib/cantata/cantata-tags

**Comment by kovtunos** [comment]
Cantata-tags installed and running. Just updated mpd to recent version — all the same. Where more to look to make it work? Maybe some libs are missing or something.

**Comment by CDrummond** [comment]
1. Stop Cantata
 2. Start Cantata from the commandline as follows:

CANTATA_DEBUG=0x00008000 cantata

3. Attempt to edit tags, as before
4. Copy ~/.cache/cantata/cantata-tags.log here - or provide a link to it

Also, check with kid3 (or similar) to ensure tags are not written

**Comment by kovtunos** [comment]
1. Cantata starts with debug option and then in terminal returns only:

> QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.

Nothing informative. 

2. File cantata-tags.log don't create at all.

**Comment by kovtunos** [comment]
Just installed cantata from git-master. It works.
