### ISSUE TITLE
album covers

### ISSUE THREAD

**Issue by valius55** [CDrummond/cantata#713]
Hello,
I am new in Cantata and I have problem with showing album covers.
I play my music from QNap server via transport (MPD player) and DAC. Cantata on MacBook Pro works except showing the album covers which are saved in the each separate album file as Folder.jpg. Some covers are shown but they are taken not from my created directories in NAS but from internet. I tried everything (I mean "Music folder" option) but the problem is still there. Please help me, Cantata is the only option for me to control my music via computer. Thank you very much for your help !!!!

**Comment by CDrummond** [comment]
You need to set Cantata's music folder to point to MPDs. For example:

1. On your NAS you might have your music in /home/user/Music
2. On your Mac perhaps you have /home/user mounted as /Volumes/user
3. Cantata would need to have its music folder set to /Volumes/user/Music

If you were playing the following file on your NAS: /home/user/Music/Artist/Album/01 Track.mp3

...then MPD only tells Cantata that the file path is Artist/Album/01 Track.mp3

Cantata takes the folder part of this path (Artist/Album) and *adds* that onto the Cantata's configured music folder. So in the above example, Cantata would expect to find the cover in /Volumes/user/Music/Artist/Album

**Comment by valius55** [comment]
On MPD in my library share dialog I have following: Muzika/ValiausMuzika/
And everything works except showing album covers

EXAMPLE:
On the NAS the path is :  /Muzika/ValiausMuzika/Rock/BRITAI/Black Sabbath/Black Sabbath Sabotage/ 01 Black Sabbath - Hole in the Sky.flac

The picture/ cover file Folder.jpg is in the same folder and has following path:
/Muzika/ValiausMuzika/Rock/BRITAI/Black Sabbath/Black Sabbath Sabotage/ Folder.jpg

Currently in the preferences of cantata I have following configuration in 
"Music Folder": Muzika/ValiausMuzika/  (same as on MPD player)

I tried hundreds of other options but it doesn’t work. Can you please point out, where is my mistake ? 

If I use other programs like Kazoo they have no problems with showing the covers (but I can’t use them because because I need a player based on MPD).

**Comment by CDrummond** [comment]
I've just tested on a Mac with the following configuration:

1. Music stored on a raspberry pi 2 in folder /media/USB/Music
2. MPD on the pi has /media/USB/Music as its music_directory setting
3. Samba on the pi exports this folder as 'Music (MPD)'
4. On Mac the 'Music (MPD)' share is mounted at /Volumes/Music (MPD)
5. Cantata on Mac has /Volumes/Music (MPD) set as the Music folder

To see where Cantata is looking for covers:

1. Start cantata
2. Ensure view is set to Library (if using git/master) or Artists (if using 1.5.2)
3. Set that view to be using detailed tree
4. Clear the play queue
5. Use the Cache settings page of Cantata to remove any downloaded and scaled covers
6. Stop Cantata
7. Restart Cantata from the commandline as follows:

	CANTATA_DEBUG=-4 Cantata.app/Contents/MacOS/cantata

8. Now expand an artist that you know has just one album (to save having lots of debug). You should now see something like:

Covers "GUI" locateImage "Abba/Gold - Greatest Hits/02 Dancing Queen.mp3" "Abba" "Abba" "Gold - Greatest Hits" 0
Covers "GUI" locateImage Checking file "/Volumes/Music (MPD)/Abba/Gold - Greatest Hits/cover.jpg"
Covers "GUI" locateImage Got cover image "/Volumes/Music (MPD)/Abba/Gold - Greatest Hits/cover.jpg"

....
The first line above has the music path as sent from MPD to Cantata (Abba/Gold - Greatest Hits/02 Dancing Queen.mp3). As you can see the whole path is NOT sent, only the path that is under MPD's music_directory setting. Cantata takes the directory part of the path and appends it to the 'Music folder' setting (as set in Cantata's config dialog). This gives a FULL path of "/Volumes/Music (MPD)/Abba/Gold - Greatest Hits/" Now within this folder, Cantata will look for cover art. The first filename it looks for is that set in Cantata's 'Cover filename' config setting (which defaults to cover)
....

All I can suggest is for you to run the steps above, and see what debug you get.

**Comment by valius55** [comment]
After all 6 steps, when I trying to restart Cantata in Terminal with the command

CANTATA_DEBUG=-4 Cantata.app/Contents/MacOS/cantata 

I get this message

-bash: Cantata.app/Contents/MacOS/cantata: No such file or directory

(MPD player is installed on the transport of the DAC Versus Audio, but not on Mac. Versus Audio is a computer/ transport which feeds the DAC with data from NAS)

If I try to set the cover of an album manually from the NAS directory (in Album or Artist view) I am getting this message:

Could not copy file to '/Volumes/Muzika/netmusic/Rock/BRITAI/10cc Deceptive Bends/10cc Deceptive Bends/Folder.jpg‘!

"Volumes/Muzika" is set as Music Folder in Cantata
„netmusic" is the name of music collection on Cantata

**Comment by valius55** [comment]
One more thing: if I try to use options in Artists or Albums view
Organize files
Edit Track Informations
ReplayGain

There comes following warning:
Cannot access song files ! Please check Cantata's "Music folder" setting, and MPD's "music_directory" setting.

**Comment by CDrummond** [comment]
This is the same issue. Your settings are WRONG. "/Volumes/Muzika/netmusic/Rock/BRITAI/10cc Deceptive Bends/10cc Deceptive Bends/Folder.jpg‘" does not seem correct to me. "10cc Deceptive Bends" is duplicated.

When running:

CANTATA_DEBUG=-4 Cantata.app/Contents/MacOS/cantata 

...you need to do this from the SAME folder that Cantata.app is located - otherwise the command will not be found. Please re-run from the correct folder.

**Comment by CDrummond** [comment]
So, I'm assuming this is now 'fixed' for you seeing your feature request?

**Comment by valius55** [comment]
No, I can't solve the problem... When I try to run CANTATA_DEBUG=-4 Cantata.app/Contents/MacOS/cantata from  Cantata folder (MacOS >> cantata or cantata-replaygain or cantata-tags) there is no possibility to type. the same is is with canatata-dynamic folder

Craig, would it be possible to ask you to do me the favor and log in my pc using team viewer ?
I don't think I will be able to solve this problem by myself ...

**Comment by CDrummond** [comment]
'No possibility to type'??? Just open a Terminal window and cd into the correct folder. e.g. if Cantata.app is installed into /Applications then (from a Terminal window) you just need to type:

CANTATA_DEBUG=-4 /Applications/Cantata.app/Contents/MacOS/cantata 

As to connecting to your PC - that's a bit trusting of you! Not something I would really recommend.

As stated, the cover finding does work. You just need to have the correct settings. Using CANTATA_DEBUG would have help to find out what this would be.

Anyhow, lets the this:

1. Add a single song to the playqueue in Cantata
2. Place the mouse over the song in the playqueue, and a tooltip should appear. At the bottom of the tooltip will be the song path as passed from MPD to Cantata. e.g. in my Abba example above this is "Abba/Gold - Greatest Hits/02 Dancing Queen.mp3"
3. In a Terminal window cd into the location where you have mounted your NAS music folder. e.g. for my case this would be:

    cd "/Volumes/Music (MPD)"
4. From here we try to find the song that is in the playqueue. For this we find the filename, e.g.:

    find . -name "02 Dancing Queen.mp3"

5. Now if this produced something like:

    ./Collection/Abba//Gold - Greatest Hits/02 Dancing Queen.mp3

    then what Cantata needs is

    a. The mount point (/Volumes/Music (MPD))
    b. The part of the path above that is NOT in the playqueue tooltip - in this case Collection

  So, in Cantata's config dialog we set Music folder to:

      /Volumes/Music (MPD)/Collection

Now, when MPD tells Cantata that a songs path is"Abba/Gold - Greatest Hits/02 Dancing Queen.mp3" Cantata can then convert this into a FULL path of "/Volumes/Music (MPD)/Collection/Abba/Gold - Greatest Hits/02 Dancing Queen.mp3" To get the folder of the cover, it simply removes the filename part of the path, and we are left with "/Volumes/Music (MPD)/Collection/Abba/Gold - Greatest Hits/"

Make sense?

**Comment by valius55** [comment]
Hello Craig,
thank you so much for taking the time to help me !
Here are the results if I try to follow you instructions, sorry, I am very, very week in computers..

Last login: Mon Aug  3 22:22:01 on ttys000
MacBook-Pro:~ valerijusjasiulevicius$ /Volumes/Muzika
-bash: /Volumes/Muzika: is a directory
MacBook-Pro:~ valerijusjasiulevicius$ find . -name "01 David Bowie - Uncle ArthurDavid Bowie.flac"
MacBook-Pro:~ valerijusjasiulevicius$ 
MacBook-Pro:~ valerijusjasiulevicius$ 

I think it would be the easiest way if you could login into my Mac and look for the problem.
please send me your email address to valerijus.jasiulevicius@gmail.com

**Comment by CDrummond** [comment]
Ummm... In the above you need to change into the directory. e.g.:

1. **cd** /Volumes/Muzika
2. find . -name "01 David Bowie - Uncle ArthurDavid Bowie.flac"


-------
As to logging onto your machine, sorry but I am **not* going to do this. You don't know me - and encouraging someone to allow unknown people to log onto their machine is not something I want to encourage.

**Comment by CDrummond** [comment]
Closing this. Cover loading does work from NAS, etc. You just need to correctly set up your system. Sorry, but I don't have time for coding and user support.
