### ISSUE TITLE
Some podcast episodes from soundcloud are not listed in sequnce of date.

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#714]
A podcast's file hosting server has moved to soundcloud recently.
Episodes are not listed in sequence of date any more and the date information is not available in Cantata.
Is there any way to deal with this issue?

The URL feed is http://old.ddanzi.com/appstream/bunker1.
It was OK till http://soundcloud.com/ddanzi/z-63/download.mp3, but not from http://soundcloud.com/ddanzi/z-64/download.mp3.

**Comment by CDrummond** [comment]
Ah see the issue. The dates are wrong in the RSS

Wed, 01 jul 2015 16:20:00 +0900

should be

Wed, 01 Jul 2015 16:20:00 +0900

Notice the capitalisation of Jul

**Comment by CDrummond** [comment]
Should be fixed now - well worked-around really as its the RSS that is at fault! You might need to delete and re-add the subscription for the correct dates to appear - or edit the xml.gz file in ~/.local/share/cantata/podcasts to remove the episodes without date.

Can you please confirm the fix?

**Comment by parkmino** [comment]
Thanks for your work-around and fixed!

**Comment by CDrummond** [comment]
Thanks for the confirmation.
