### ISSUE TITLE
[Feature Request] Choose cover from folder

### ISSUE THREAD

**Issue by vibee** [CDrummond/cantata#716]
I would love to see the following feature, it would be very useful:

The function Set Image could be enhaced, such that images in the music file's folders are also selectable (beside the ones from itunes etc.).

Some of my folders contain several images (for instance back, front, cd, inlay,...), and cantata sometimes chooses the cd, back or inlay image. In this case it would be very nice to be able to simply select one of the others with one click. In some cases, there are no online images (so I need to manually rename the cover file to cover.jpg for proper display) or the local imaghe files are of much better quality than the 600*600 online ones.   

Maybe the best way to implement this feature is to collect all paths from the selected album's audio files (usually this is only one) and add previews of these images to the "Set Image" windows, besides the itunes ones.

**Comment by CDrummond** [comment]
Adding the list of other files to the 'Set Image' dialog is a reasonable request - and I'll leave this issue open so as to remind me to implement it.

However, you can use the 'Cover filename' setting in Cantata's config dialog to set the default name to use when looking for (and saving) covers. Set this to 'Folder' and it should already do what you need. (Cantata does look for 'folder.jpg' and 'folder.png' just not Folder)

**Comment by CDrummond** [comment]
I've implemented this, but not committed. I'm not sure its going to let you do what you want.

e.g. If you have an image called 'cover.jpg' and one called 'alt-cover.jpg' If you use 'alt-cover.jpg'  from the cover dialog it will OVERWRITE cover.jpg

So, I'm not sure whether this is a useful function or not. I'm thinking not...

**Comment by CDrummond** [comment]
As stated above, this would be a confusing change. It would make it appear as it you are setting the filename to use, but it would in fact overwrite one file with another.
