### ISSUE TITLE
No lyrics and backdrop for artist '+44' (problem with '+'?)

### ISSUE THREAD

**Issue by tinxx** [CDrummond/cantata#717]
I listened to the band '+44' and when switching to the info view it could load neither lyrics nor backdrop.
This is probably because of the leading '+' but it's merely an educated guess as the lyrics are available on wikia.

**Comment by CDrummond** [comment]
Yeah - did a quick hack, and it appears as if Cantata is converting the name '+44' into just '44' - will investigate more later.

Also, are you testing 1.5.2 or git/master ?

**Comment by CDrummond** [comment]
Hmmm... the +44 -> 44 conversion was an issue with the SQLite DB in git/master - this is fixed now.

The lyrics fetching, however, is still broken...

**Comment by CDrummond** [comment]
With git/master I can now get lyrics and a backdrop. Can you update and confirm?

**Comment by tinxx** [comment]
Sorry, can't confirm because of build error.
I tried building it using Arch User Repository package: https://aur4.archlinux.org/packages/cantata-git/
```
aur-cantata-git/src/cantata-git/context/ultimatelyricsprovider.cpp:341:15: Fehler: »class QUrlQuery« has no member named »addEncodedQueryItem«
         query.addEncodedQueryItem("titles", urlEncode(path.startsWith(QLatin1Char('/')) ? path.mid(1) : path).toLatin1());
               ^
```

**Comment by CDrummond** [comment]
Ah, need to fix for Qt5. Can you try a Qt4 build just for now?

**Comment by tinxx** [comment]
Thanks, I can confirm that the issue is solved for qt4 build.

**Comment by CDrummond** [comment]
Thanks for checking with Qt4. I've changed the code now, so that it compiles with both Qt4 and Qt5, and still seems to work. Can you rebuild with Qt5 and confirm?

To be sure the download is actually happening - you'll need to remove the previously downloaded lyrics. These will either be in a .lyrics file in the music folder (if you enabled that option), or in ~/.cache/cantata/lyrics

**Comment by tinxx** [comment]
I deleted the backdrop and lyrics which the qt4 build downloaded yesterday. 

Qt5 build works and downloads and displays lyrics. No backdrop is downloaded though.

**Comment by CDrummond** [comment]
That's odd - as the Qt5 changes were ONLY to do with the lyrics - not the backdrop. I'll look later...

**Comment by CDrummond** [comment]
Just tried, and backdrop is downloaded for Qt5 build.

**Comment by tinxx** [comment]
Not on my machine. Have you tried deleting it and then re-open qt5 version's info view?

**Comment by CDrummond** [comment]
Of course - and I enabled the logging to ensure it was redownloaded. As I said, the code for the Qt4 and Qt5 builds is **exactly** the same for the backdrop downloading.

**Comment by tinxx** [comment]
Hmm.. Strange.

**Comment by CDrummond** [comment]
...and just to prove that it works. The following is a log of:

1. Deleted Cantata's bacdrops cache folder
2. ldd on cantata exe to prove its the Qt5 version
3. Run cantata with context widget and network access enabled.

---------------------8<--------------------

craig@whitestar:~$ rm -rf .cache/cantata/backdrops/
craig@whitestar:~$ ldd ./stuff/build/cantata/qt5/cantata
	linux-vdso.so.1 =>  (0x00007ffd7efbc000)
	libtag.so.1 => /usr/lib/x86_64-linux-gnu/libtag.so.1 (0x00007f03750b3000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f0374b70000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f03744c9000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f0375423000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f0373f7c000)
	libQt5Svg.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5 (0x00007f03753ca000)
	libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f0373f3a000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f0373eb9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0373c9e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f037398f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0373687000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0373471000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f03730a7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0372e89000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007f0372a77000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007f03726f9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f03724f5000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f03721e6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0371fde000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f037538d000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f0371d8c000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f0371a53000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f037182d000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f03715d6000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f037133a000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f03710f2000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007f036f885000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f036f618000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f036f410000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f036f1f1000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f036ef49000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f036ed2d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f036eb04000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f036e8da000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f036e6c8000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f036e4c5000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f036e2bf000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f036e0bd000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f036dea6000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f036dca1000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f036da9e000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f036d89b000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f036d695000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f036d493000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f036d28d000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f036d080000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f036ce7c000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f036cc76000)
craig@whitestar:~$ CANTATA_DEBUG=-0x00001040 ./stuff/build/cantata/qt5/cantata
ContextWidget updateBackdrop "" "" "" false
ContextWidget updateBackdrop "+44" "" "+44/When Your Heart Stops Beating/01 Weatherman.mp3" false
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/When Your Heart Stops Beating/+44-backdrop.jpg"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/When Your Heart Stops Beating/+44-backdrop.png"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/When Your Heart Stops Beating/backdrop.jpg"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/When Your Heart Stops Beating/backdrop.png"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/+44-backdrop.jpg"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/+44-backdrop.png"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/backdrop.jpg"
ContextWidget updateBackdrop Checking file(1) "/var/lib/mpd/music/+44/backdrop.png"
NetworkAccessManager get "http://www.musicbrainz.org/ws/2/artist/?query=artist:+44" true
NetworkJob NetworkJob 0x34c4d80 0x1a4b2c0
ContextWidget getMusicbrainzId "http://www.musicbrainz.org/ws/2/artist/?query=artist:+44"
NetworkJob handleReadyRead 0x34c4d80 0x1a4b2c0
NetworkJob handleReadyRead 0x34c4d80 0x1a4b2c0
NetworkJob jobFinished 0x34c4d80 0x1a4b2c0
NetworkJob jobFinished "http://www.musicbrainz.org/ws/2/artist/?query=artist:+44" 0 "OK"
ContextWidget musicbrainzResponse status 0 "Unknown error"
NetworkAccessManager get "http://api.fanart.tv/webservice/artist/ee86404cb429fa27ac32a1a3c117b006/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/json/artistbackground/1" true
NetworkJob NetworkJob 0x33c42f0 0x285f450
ContextWidget musicbrainzResponse "http://api.fanart.tv/webservice/artist/ee86404cb429fa27ac32a1a3c117b006/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/json/artistbackground/1"
NetworkJob ~NetworkJob 0x34c4d80 0x1a4b2c0
NetworkJob cancelJob 0x34c4d80 0x1a4b2c0
NetworkJob handleReadyRead 0x33c42f0 0x285f450
NetworkJob jobFinished 0x33c42f0 0x285f450
NetworkJob jobFinished "http://api.fanart.tv/webservice/artist/ee86404cb429fa27ac32a1a3c117b006/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/json/artistbackground/1" 0 "OK"
ContextWidget fanArtResponse status 0 "Unknown error"
NetworkAccessManager get "http://assets.fanart.tv/fanart/music/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/artistbackground/44-4ea04943473a7.jpg" true
NetworkJob NetworkJob 0x1ba1a80 0x26e8e10
ContextWidget fanArtResponse "http://assets.fanart.tv/fanart/music/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/artistbackground/44-4ea04943473a7.jpg"
NetworkJob ~NetworkJob 0x33c42f0 0x285f450
NetworkJob cancelJob 0x33c42f0 0x285f450
NetworkJob handleReadyRead 0x1ba1a80 0x26e8e10
NetworkJob jobFinished 0x1ba1a80 0x26e8e10
NetworkJob jobFinished "http://assets.fanart.tv/fanart/music/c2a44e93-3a2b-44aa-bd8b-7a71bb76e3b5/artistbackground/44-4ea04943473a7.jpg" 0 "OK"
ContextWidget downloadResponse status 0 "Unknown error"
ContextWidget updateImage false true
ContextWidget downloadResponse Not saving to mpd folder - set to save in mpd? false isVa: false isNonMPD: false mpd readable: true
ContextWidget downloadResponse Saved backdrop to (cache) "/home/craig/.cache/cantata/backdrops/+44.jpg" for artist "+44" , current song "+44/When Your Heart Stops Beating/01 Weatherman.mp3"
NetworkJob ~NetworkJob 0x1ba1a80 0x26e8e10
NetworkJob cancelJob 0x1ba1a80 0x26e8e10

---------------------8<--------------------

As you can see backdrop downloaded, and saved to Cantata's cache folder.

**Comment by tinxx** [comment]
My fault. It did load the backdrop after I displayed another band's info page and then +44.

Thanks for fixing it :)
