### ISSUE TITLE
First Time Crash (but no crash afterward)

### ISSUE THREAD

**Issue by tsujan** [CDrummond/cantata#720]
First I apologize for this poor bug report, to which I couldn't add more info.

Cantata was compiled against Qt5 and installed without any problem under Debian Testing. The setting dialogs appeared correctly but after setting was finished and I clicked on the desktop file for the first time, Cantata crashed. However, no crash happened afterward and Cantata works OK now.

**Comment by CDrummond** [comment]
Which version of Cantata? git/master of 1.5.2? By 'Settings dialog' do you mean the initial settings wizard that asks for connection type, connection params, etc?

**Comment by tsujan** [comment]
I use the latest version, downloaded from here today. And yes, I mean the setting wizard. The setting wizard itself had no problem but Cantata crashed the first time. Sorry, I don't remember precisely whether Cantata was supposed to appear after that wizard (wasn't it?) but crashed instead, or it crashed the first time I ran it.

This was under Enlightenment. Also about a month ago, I compiled it under KDE but against Qt5 (to fix a Kvantum bug a user had reported) and the same thing happened.

If you want, I could restart to my KDE-based Debian later and try to reproduce the problem.

**Comment by tsujan** [comment]
I removed all Cantata settings a few minutes ago and ran it again. The wizard was completed and Cantata started showing but crashed instead. However, it worked OK afterward, like it did before.

**Comment by CDrummond** [comment]
Ah, excellent - you can recreate the crash, I can't!

Can you run Cantata under gdb? Try the following (from a commandline)

1. Remove cantata settings
2. gdb cantata
3. At the "(gdb)" type "run"
4. When Cantata crashes, type "where" - and post the results here

**Comment by tsujan** [comment]
Here you are:

(gdb) run
Starting program: /usr/bin/cantata 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8cdf700 (LWP 919)]
[New Thread 0x7fffe3d32700 (LWP 920)]
[New Thread 0x7fffe32b4700 (LWP 921)]
QPixmap::scaled: Pixmap is a null pixmap
[New Thread 0x7fffe0f76700 (LWP 976)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f6e070 in QSqlDatabase::transaction() () from /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5
(gdb) where
#0  0x00007ffff6f6e070 in QSqlDatabase::transaction() () from /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5
#1  0x00000000005e9076 in LibraryDb::updateStarted(long) ()
#2  0x00007ffff5c99e8a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6555adc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff655afb0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff5c683ab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff5c6a41b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff5cc0f33 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff39f7c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff39f7f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff39f7fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff5cc1347 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff5c65b62 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff5c6d7ac in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00000000005135d7 in main ()
(gdb) Quit

My installed Qt5 is v5.4.2.

**Comment by CDrummond** [comment]
Thanks for this, still can't recreate. But I've made some mods - can you update and try again?

**Comment by tsujan** [comment]
Sure! Here it's past midnight. I'll do that tomorrow and tell you about the result.

**Comment by tsujan** [comment]
Yes, the crash is fixed :) I checked twice.
