### ISSUE TITLE
How to save rating to files on git-master?

### ISSUE THREAD

**Issue by kovtunos** [CDrummond/cantata#722]
Just build the app from git-master. It works and I pleased with redesigned interface. But one thing I'm curious of how I can write rating to files? There is no such option as internal tag editor.

**Comment by CDrummond** [comment]
In the tag-editor, there is a 'Tools' button, click on this and you will get a menu - one of the options is to write ratings to file.

**Comment by kovtunos** [comment]
I just have no such option as Tag Editor. 
I build the program with default options where -DENABLE_EXTERNAL_TAGS=ON. Should I turn it off to get old Tag Editor?

**Comment by CDrummond** [comment]
Then I'm guessing you are missing that taglib devel packages on your system.

-DENABLE_EXTERNAL_TAGS=ON is on by default - and this causes cantata to create and use a small helper app to read/write tags. This protects Cantata from crashes due to TagLib.

**Comment by kovtunos** [comment]
Just installed libtag1-dev, libtag-extras-dev (on kubuntu 14.04) and rebuilded. It works. Thanks for help.
