### ISSUE TITLE
'Unknown' songs show a specific cover image and does not change dynamically.

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#723]
I think unknown songs without tags should show a blank CD icon image instead of a specific one in library and play-queue.
For now, the specific cover image does not change dynamically and just shows the previous cover after  refreshing unknown songs.

**Comment by CDrummond** [comment]
Can you update, and try again?

**Comment by parkmino** [comment]
Not fixed yet, and I can find Unknown.jpg under ~/.cache/cantata/covers-scaled/136/Unknown/ folder after removing all the scaled covers.

**Comment by CDrummond** [comment]
...and try again :-)

**Comment by parkmino** [comment]
Now fixed and thanks!
