### ISSUE TITLE
[Enhancement] Add option to improve cached cover image quality 

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#724]
I am not satisfied with the cached image quality and could you please add option to improve this?
Cached covers help a lot, however image qualities under ~/.cache/cantata/covers-scaled/136/ seems not to be good enough. when I refreshed all the cached covers, it is the only time when cover images look perfect.

**Comment by CDrummond** [comment]
Must admit I never really noticed. However, I've just tried with using PNG to save the scaled covers - and this is much better (but 3 times the size!) Anyhow, will now use PNG files...
