### ISSUE TITLE
Add to playlist doesn't respond

### ISSUE THREAD

**Issue by darkfeline** [CDrummond/cantata#725]
Right-clicking on a song and clicking Add to Playlist -> anything doesn't work.  Neither adding to an existing playlist nor creating a new playlist works.  The right click menu doesn't close, Cantata behaves as though no click was issued.

Running cantata from a terminal doesn't produce any relevant messages.

Version is 1.5.2 on Arch Linux.

**Comment by CDrummond** [comment]
Don't know what's wrong with your build - but this woks perfectly fine for me in 1.5.2 and git/master

**Comment by darkfeline** [comment]
Weird, it's working for me now too.  Sorry for bugging you.
