### ISSUE TITLE
Cantata won't successfully find substrings

### ISSUE THREAD

**Issue by vibee** [CDrummond/cantata#726]
I've found another issue regarding the search function (trunk). I'll use Aerosmith as an exmaple.

In earlier versions of cantata, I could enter a substring in the search function (for instance "Aerosmit") and canata was also returning "Aerosmith". This was very useful, as I didn't need to enter the full name (or rather: a complete word) of a track title / artist / album. 

However, the search function in trunk is less comfortable: Searching for "Aerosmit", it returns no search results. Entering a substring doesn't work, which is not nice if the title / artist I am looking for is pretty long (or if I can't remember the spelling or the full name). 

I had no time to look into the code, but I guess you are doing a comparison (maybe for performance reasons). I'd love to have the former functionality back.

Thanks in advance :+1:

**Comment by CDrummond** [comment]
In git/master Cantata now stores the music cache in an SQLite database. For searches, Cantata uses SQLite's full-text-search facility - but this only supports prefix searches. This was broken, and now fixed.

So Aerosmit will work, erosmit will not.
