### ISSUE TITLE
Music folder issues

### ISSUE THREAD

**Issue by hansheijmans** [CDrummond/cantata#730]
I try to organize files, edit track info or set images for albums but I get errors like "please check Cantata's "Music Folder" settings and MPD's "music_directory" setting".

The client Cantata is running on has direct access to the music folder i.e. "/media/Media/Music" but the machine MPD is running on (RPi with RuneAudio) accesses the directory using "/mnt/MPD/NAS/Music" where music_directory reads /mnt/MPD.

When I temporarily created the same mount point on the client Cantata is running on as on the RuneAudio machine and set Music Folder in Cantata to /mnt/MPD then all is fine.

Of course when MPD and Cantata are running on the same machine then there is no problem as they both use same mount point (or local directory) but when client and MPD are running on separate machines and use different mount points I need to tweak as described above.

I didn't have this problem when I used MPD on self-configured machine using same mount points on client and server.

**Comment by CDrummond** [comment]
Cantata itself does not care what mount point MPD uses.

When MPD is playing a track, it only sends Cantata the file path within its music folder. e.g.

- MPD's music_directory="/mnt/MPD/NAS/Music"
- Playing "/mnt/MPD/NAS/Music/SomeArtist/SomeAlbum/ATrack.mp3"
- Cantata *only* receives "SomeArtist/SomeAlbum/ATrack.mp3" from MPD

To know where this file actually is, Cantata prepend's the "Music folder" setting. e.g. if you set this to "/media/Media/Music" then Cantata will expect the full path to "ATrack.mp3" to be "/media/Media/Music/SomeArtist/SomeAlbum/ATrack.mp3"

Notice that Cantata does not see, nor care about, "/mnt/MPD/NAS/Music"

---

I know 100% for a fact that this works fine - as I have MPD on a raspberry pi (with the music stored on a usb stick). Cantata runs on my Ubuntu laptop, with the Pi's music folder mounted via Samba.

---

Looking at your report above, you have MPD's music_diretory set to "/mnt/MPD" - therefore when it plays "/mnt/MPD/NAS/Music/SomeArtist/SomeAlbum/ATrack.mp3" it will pass "NAS/Music/SomeArtist/SomeAlbum/ATrack.mp3" to Cantata. I suggest that perhaps you want MPD's music_directory set to "/mnt/MPD/NAS/Music/"

**Comment by hansheijmans** [comment]
Hi C,
Thanks for your comment! Tweaked a bit and now I got it working by setting the music folder to /media/Media, creating a directory NAS (within Media) on the same level as Music and inside the NAS directory a symlink to Music so the full path to any music file now reads:

"NAS/Music/SomeArtist/SomeAlbum/ATrack.mp3"
