### ISSUE TITLE
use keyboard for changing songs, play/pause

### ISSUE THREAD

**Issue by ochurlaud** [CDrummond/cantata#731]
I'm not able to use the multimedia keys of my keyboard on cantata. 

Is it due to my config ? If not, then it's a bug :)

I'm on Archlinux/KDE (5)

**Comment by CDrummond** [comment]
Kinda hard to diagnose without knowing the version - 1.5.x? git/master? Qt4? Qt5 ?KDE4?

KDE4 builds use KDE's global keyboard settings.

Qt4/Qt5 builds use either X11 or gnome-settings-daemon settings.

Just tried the gnome ones, and works just fine
