### ISSUE TITLE
Shortcut: Add music to the playlist

### ISSUE THREAD

**Issue by ochurlaud** [CDrummond/cantata#732]
Hi, I have a rather big collection and I was able with other apps to add (or replace) with, say CTRL+R, a random album to the playlist.

Is there such a feature here ?

thx for your awesome app.

**Comment by CDrummond** [comment]
Implemented in trunk now. Use context menu and select 'Add To Play Queue' -> 'Append Random Album'

No pre-defined short-cut - but you can set one in the shortcuts dialog.
