### ISSUE TITLE
Recently Added?

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#736]
Is there any way to sort by date added or make a playlist with, say the 50 songs that were most recently added to the library?

**Comment by CDrummond** [comment]
Library -> menu -> 'Group by' -> Album
Library -> menu -> 'Sort by' -> 'Date added'

... but I guess I could add a 'Smart' playlist to auto-add the last 50, etc, songs...

**Comment by 3marcusw** [comment]
thanks, although "Date Modified" is in the menu, not "Date added"

**Comment by CDrummond** [comment]
Well, I was not at my machine when writing the above :-)  Plus, 'Date Modified' is more accurate.

**Comment by CDrummond** [comment]
To be honest, not worth adding a 'smart' playlist functionality just for this. If MPD stored playcounts, etc - then perhaps this could be added (e..g most played, never played, latest, etc)

So, for now, closing.
