### ISSUE TITLE
Export Playlist

### ISSUE THREAD

**Issue by giuliano52** [CDrummond/cantata#737]
is there any way to export the cantata playlist in .m3u format (or other format) ? 
Thank you.

**Comment by CDrummond** [comment]
No. MPD does not support this

**Comment by giuliano52** [comment]
Thank you

**Comment by ssameer** [comment]
MPD saves your playlists in ~/.mpd/playlists in m3u format automatically.

**Comment by officernice** [comment]
> MPD saves your playlists in ~/.mpd/playlists in m3u format automatically.

As of 2021, it does not.

**Comment by cpchan** [comment]
> > MPD saves your playlists in ~/.mpd/playlists in m3u format automatically.
> 
> As of 2021, it does not.

You need to set the playlist directory in mpd.conf or else the playlists won't be saved:

,----[ According to mpd.conf (5) ]
| playlist_directory <directory>
|               This specifies the directory where saved playlists are stored.  If you do not configure this, 
| you cannot save playlists.
`----

**Comment by officernice** [comment]
> > > MPD saves your playlists in ~/.mpd/playlists in m3u format automatically.
> > 
> > 
> > As of 2021, it does not.
> 
> You need to set the playlist directory in mpd.conf or else the playlists won't be saved:
> 
> ,----[ According to mpd.conf (5) ]
> | playlist_directory
> | This specifies the directory where saved playlists are stored. If you do not configure this,
> | you cannot save playlists.
> `----

The playlist directory is by default set to "/var/lib/mpd/playlists" even when changing it to something within my home directory nothing shows up. My mpd.conf is within /etc and always has been, there is nothing within /.config and /.mpd does not exist. What exactly am I doing wrong?
