### ISSUE TITLE
Support KF5

### ISSUE THREAD

**Issue by wengxt** [CDrummond/cantata#738]
KDE 4 is more or less EOL. Plasma 5 is used by default in more and more distribution.

Maybe also consider drop KDE4 support if it is burden to maintain too much combinition of different Qt/KDE dependency.

**Comment by CDrummond** [comment]
And what features would KF5 bring over and above Qt5? All I can think of is global shortcuts, and to be honest I'm not sure its worth a port just for that - these /should/ work using the Qxt backend (well for media keys at least)

**Comment by wengxt** [comment]
kwallet ? :)

**Comment by wengxt** [comment]
And use kglobalaccel is kinds of a must on wayland based system in the future. install event filter trick only works on X11 based system.

**Comment by CDrummond** [comment]
So - no, no real reason. I'm pretty sure the wayland keyboard shortcut issue can be handled in a better way - e.g. by using a dbus service. Perhaps this is what KF5 uses? If so, then it'd be better for Cantata to just connect to that service - like it does for the GNOME media keys.

MPD's password is sent in plain text - so don't see the point in using kwallet. (Yes, I know Cantata already uses kwallet for KDE4 - but I'm thinking of turning this off by default for 2.x)
