### ISSUE TITLE
Add to playlist doesn't respond part 2

### ISSUE THREAD

**Issue by darkfeline** [CDrummond/cantata#740]
Reviving this issue (https://github.com/CDrummond/cantata/issues/725) since I've managed to reproduce it.

Right-clicking on a song in the left pane (Search, Artists, Albums, etc) and clicking Add to Playlist -> anything doesn't work. Note that this works fine in the right pane (the play queue), but having to add songs to the play queue before adding to a playlist is an annoying workaround.

Running cantata from a terminal doesn't produce any relevant messages.

Version is 1.5.2 on Arch Linux.

Can anyone else reproduce this?

**Comment by CDrummond** [comment]
As I said - this is working fine for me. Don't know what else you expect me to do.

**Comment by darkfeline** [comment]
This is different from my last report.  Adding to playlist works in the PLAY QUEUE, but does not work in any of the SIDEBAR views.  Can you still not reproduce it?

Here's my config: http://pastebin.com/yTDecEAx

**Comment by CDrummond** [comment]
Yes this works for both 1.5.2 and git/master

**Comment by darkfeline** [comment]
I'm on Qt 5.5.0 and not using KDE.  Does that raise any bells?

**Comment by CDrummond** [comment]
Code is the same. The DE does not matter. However, I only checked Qt4 builds, will check Qt5 later

**Comment by CDrummond** [comment]
Yup, as expected Qt5 work just fine.

**Comment by darkfeline** [comment]
That's odd.  I'd like to keep this open since I'm still experiencing this and it's such a strange UI bug, is that okay?  There are a few more things I'd like to try.

**Comment by darkfeline** [comment]
I tried compiling the git/master version with Qt5 and still experienced this bug.  I then tried compiling the 1.5.2 release with Qt4 which works.

For me, then, the problem is with Qt5.  You didn't mention a specific version, but I assume you tested Qt 5.5.0.  If this is the case, then it is a problem with Arch's packaging of Qt5.  If not, it may be a bug or regression in Qt 5.5.0, in which case it will probably be fixed in later releases.

Feel free to close this at your discretion (I'm not sure what your bug-tracking preferences are).

**Comment by CDrummond** [comment]
No, Ubuntu is only on 5.4. Still, not 100% convinced this is a Qt issue. Seeing as you raised a simialr issue before, which sorted itself out...

**Comment by darkfeline** [comment]
My last bug report was an oversight on my part.  I first encountered the bug in the sidebar, where add to playlist doesn't work, then when I tried again I did it in the play queue, where it does work, so I thought the issue went away.  I can consistently reproduce the bug now that I know it affects the sidebar and not play queue.

**Comment by CDrummond** [comment]
No, it works just fine from the sidebar.

**Comment by darkfeline** [comment]
Right, but it doesn't work at all for me, and I suspect that is either caused by using Qt 5.5.0 instead of Qt 5.4 or Arch's packaging.  I will try with Qt 5.4 to see if that's causing it.

**Comment by CDrummond** [comment]
Any updates?

Just tried a 5.5 build for OSX, and playlist creating/appending (from sidebar, and queue) works as expected.

**Comment by darkfeline** [comment]
I have upgraded to Qt 5.5.1 and am still experiencing this bug.  I have also created a thread on the Arch Linux forums to see if anyone else has run into this or can reproduce it: https://bbs.archlinux.org/viewtopic.php?id=204160

Unfortunately building with Qt 5.4 for testing will take significant work due to libraries, package management, etc.  Is there an easy way to compile a statically linked Cantata against Qt 5.4?

Qt 5.6 is scheduled for release in December, so when that reaches Arch's repository, I will try it out as well.

**Comment by ms6676749** [comment]
Confirmation on my end that I am unable to add any files to stored playlists from the library panel.

System:
Cantata-git (built today), Qt5 build
Qt 5.5.1

Steps to reproduce:
1) Click Library
2) Search for song, in my case "Born to Lose"
3) Right click song, select "Add to Playlist" and click on any options there: existing playlists or new playlist
4) None of the options respond to any click; the submenu just sits there failing to respond to any clicks.

I ran debug modes for MPD communication and parsing, threads and others.  I didn't see anything out of the ordinary in the respective logs.

**Comment by CDrummond** [comment]
Just used Qt's installer to download and install 5.5.1, and I can confirm this behaviour. Very odd, will look into it.

**Comment by CDrummond** [comment]
This should now be fixed in master. Can you please update and confirm?

**Comment by darkfeline** [comment]
Fixed for me.

**Comment by CDrummond** [comment]
Thanks for the confirmation!
