### ISSUE TITLE
Remove duplicates: Also compare tranck number

### ISSUE THREAD

**Issue by vibee** [CDrummond/cantata#741]
This one is related to #664 

One of my albums has two tracks named "Interlude", one with track number 4, one with track number 9. Cantata only keeps the track number 4, the first appearance. Also checking the track number could prevent such a behaviour.

**Comment by CDrummond** [comment]
Fair point :-)

**Comment by vibee** [comment]
Thanks :) At this point, I suppose that it might be easier to compare only the absolute filename (that's what I would call a duplicate in my playlist). I think that it's more likely to add the same file twice than adding exactly the same song from two different source files. Btw, that's also the way foobar2000 works (I mention this cause of the perfection of that tool) :-)

**Comment by CDrummond** [comment]
Its not really a feature I use. Anyhow, track number now taken into account. Not sure about complete filename,
