### ISSUE TITLE
Launching cantata in i3 leads to dbus socket exhaustion

### ISSUE THREAD

**Issue by exi** [CDrummond/cantata#742]
Hi, i just changed my desktop environment to i3 from KDE and upon starting cantata in the terminal i get this on stdout:

```
$ cantata
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
<repeated in infinite loop>
```

Cantata is _not_ starting up or opening any windows but it is stuck on an infinite loop.
Shortly after starting cantata, i get this when i try to open another konsole:

```
$ konsole
QCoreApplication::arguments: Please instantiate the QApplication object first
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
KUniqueApplication: Cannot find the D-Bus session server:  "Failed to determine seats of user \"1000\": Too many open files" 

KUniqueApplication: Pipe closed unexpectedly.
```

Inspecting /proc/[pid]/fd for the cantata process show me an excessive number of open sockets from cantata.

**Comment by exi** [comment]
Addition:
My environment variable XDG_DESKTOP_ENVIRONMENT is set to "kde".

Running 
```
$ XDG_DESKTOP_ENVIRONMENT=gtk+ cantata
```
does work, but it would be preferable to not be stuck in an infinite loop because i need XDG_DESKTOP_ENVIRONMENT=kde for dolphin and other tools to work properly.

**Comment by CDrummond** [comment]
What is i3??? So, you have set XDG_CURRENT_DESKTOP to KDE and it is not KDE?

Is this a Qt4, Qt5, or KDE build of Cantata?

------------
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
------------

this makes it look like a system issue. I'm guessing QSystemTray could not find the Cantata icon.

**Comment by CDrummond** [comment]
Sorry about the formatting of the above, I types lots of dashes - and forgot about github's markdown...

**Comment by exi** [comment]
i3: https://i3wm.org/

XDG_CURRENT_DESKTOP=kde is sadly necessary to be set or many kde apps die horribly (dolphin for example).

I'm not complaining that cantata does look ugly or anything when XDG_CURRENT_DESKTOP is set to "kde". Setting it to gtk+ is a workaround for me.

I just wanted to document the infinite-loop that makes my system unusable when starting cantata with XDG_CURRENT_DESKTOP=kde and kde is not in fact running.

Details:
Cantata build from arch linux:
```
community/cantata 1.5.2-2 [installed]
    Qt5 client for the music player daemon (MPD)
```
The arch build manifest contains this:
```
  cmake ../${pkgname}-${pkgver} \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_HTTP_STREAM_PLAYBACK=ON \
    -DENABLE_KDE=OFF -DENABLE_QT5=ON \
    -DENABLE_UDISKS2=ON
```

**Comment by CDrummond** [comment]
Do you have the system tray option enabled in Cantata? Its disabled by default. Looks like this just does not work for i3. If you have it enabled, try disabling it.

Sorry, but I fail to see what you expect me to do. I've just tried 1.5.2 and git/master compiled for Qt5 running under Unity with XDG_CURRENT_DESKTOP set to kde - no infinite loop for me.

However, both of these use the status-notifier-item classes. I guess setting the XDG env is confusing that. If that is the case, its not a Cantata issue - its an issue with the SNI library.

**Comment by exi** [comment]
You are right, i just disabled the notification area icon and the issue does not occur. I'll try to investigate myself whether this is a bug in the SNI library in general.

**Comment by exi** [comment]
I traced the function calls via gdb and found out that a simple call to trayItem->show() triggers an infinite recursion inside the qt library in my situation. I will open a bug upstream. Thanks for the patience.

**Comment by vladimir-lu** [comment]
This issue is the first hit in google for this problem - I believe the relevant bug is https://bugs.kde.org/show_bug.cgi?id=350785 FYI
