### ISSUE TITLE
playcount / simple statistics support

### ISSUE THREAD

**Issue by faemir** [CDrummond/cantata#743]
Is simple statistics (last played, playcount, first played) part of your direction for Cantata?

Playcount is of particular interest to me, and I noticed that Cantata now supports ratings through stickers, and wondered if similarly this would be added where other projects such as mpdcron and mpdfav have slowed/halted in development and felt semi superfluous ontop of cantata's already robust support for ratings.

**Comment by CDrummond** [comment]
I could add playcounts via stickers - this would be easy enough to implement. The problems then become:

1. Where to show this count? I'm guessing in the toolbar next to rating
2. How to effectively use this? I'm assuming you want something like "50 most played tracks", "50 least played tracks", "never played", "most recently played", etc?

**Comment by faemir** [comment]
If table view is used for the play queue then it could presumably be a column you can simply show/hide like the others - in grouped albums there's probably not enough space in the ui to place it sensibly, and so perhaps it would need to be either in the toolbar, perhaps the information pane or even in the info that shows when you hover over tracks.

Yeah - having playlist generation for all of those that you mentioned is quite powerful although keeping track even without playlist tools is something that some people do (last.fm logging etc.)

**Comment by CDrummond** [comment]
Still not convinced. Showing the ratings is slow enough - showing play counts, etc would be even worse. Also, I'm not sure I like the idea of the sticker DB being updated each time a song is played - my music is on a usb stick on a pi2, so I like to make writes as seldom as possible. Still, I guess I could add an option.

**Comment by Thaodan** [comment]
Amarok writes and shows playcount at the track info. I think a good way to display play count would be at the tooltip when poiting a track in the playlist or the library. So that the actual playcount is just queried when the tooltip is displayed.

**Comment by e-anima** [comment]
The comment from CDrummond about most played/least played is great. You coul make dynamically playlist to show music you never played or you play a lot.

**Comment by AlexT84** [comment]
yes, I'm all for expanding dynamic playlists ability to incorporate import date/time, last play date/time and so on.

**Comment by CDrummond** [comment]
Nearly a year with no updates. This is not something I'd use, and have no time to implement. No pull requests, so closing.
