### ISSUE TITLE
Update Cantata MPD client to 2.0 version in Ubuntu PPA

### ISSUE THREAD

**Issue by MurzNN** [CDrummond/cantata#746]
In https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata there are only 1.5.2 version of Cantata available, but in Changelog I see that 2.0 version is released https://github.com/CDrummond/cantata/blob/master/ChangeLog with many good new features.
Can you upload to ppa fresh 2.0 version of Cantata, or this release is not ready yet? Thanks!

**Comment by CDrummond** [comment]
No, it is not released - the ChangeLog only refers to what will be in the release. Also, I don;t create any Linux packages.
