### ISSUE TITLE
Does Cantata need to prompt for database refresh?

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#747]
Why is this is a serious thing to do that needs a confirmation prompt?

**Comment by CDrummond** [comment]
Yes.

Originally (v1.x) it was to prompt whether to do a partial update (i.e. just updating Cantata's cached copy) or full (MPD update and Cantata). Now it always does a full update - but on slow systems this can take sometime, hence the check. Anyhow, update is not going to be something you do repeatedly over a short time, so adding a confirmation causes no harm.

**Comment by rrthomas** [comment]
It can take some time, but it doesn't matter: both Cantata and mpd continue to operate in the mean time.
