### ISSUE TITLE
Suggestion: Group albums only by album.

### ISSUE THREAD

**Issue by Esux** [CDrummond/cantata#749]
I like to view my albums by the cover art. (Using the 'Albums' view)

However, I've noticed when an album has more than one artist it seems to be splitting them up. (Screenshot attached as an example)

I would like an option to ignore all tags and group only based on the Album tag.  Basically, so there is only one album instead of the 6 shown in the screenshot.

Thank you for providing a great client. 

![asdf](https://cloud.githubusercontent.com/assets/13018864/10643497/272499f0-781b-11e5-813a-f5768c6a2041.jpg)

**Comment by CDrummond** [comment]
Use "album artist" tag.
