### ISSUE TITLE
Musicbrainz compile error in Ubuntu 15.10

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#750]
I just upgraded to Ubuntu 15.10 cannot compile Cantata any more.
This issue seems to be musicbrainz related.

=====================================================
[ 95%] Building CXX object CMakeFiles/cantata.dir/qrc_cantata.cxx.o
[ 95%] Building CXX object CMakeFiles/cantata.dir/qrc_cantata_media.cxx.o
[ 95%] Building CXX object CMakeFiles/cantata.dir/qrc_cantata_menu.cxx.o
Linking CXX executable cantata
CMakeFiles/cantata.dir/devices/musicbrainz.cpp.o: In function `artistFromCreditList(MusicBrainz5::CArtistCredit*) [clone .constprop.73]':
musicbrainz.cpp:(.text+0x30): undefined reference to `MusicBrainz5::CArtistCredit::NameCreditList() const'
musicbrainz.cpp:(.text+0x59): undefined reference to `MusicBrainz5::CNameCredit::Name[abi:cxx11]() const'
musicbrainz.cpp:(.text+0xb1): undefined reference to `MusicBrainz5::CNameCredit::JoinPhrase[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x10b): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x120): undefined reference to `MusicBrainz5::CList::Item(int) const'
musicbrainz.cpp:(.text+0x132): undefined reference to `typeinfo for MusicBrainz5::CNameCredit'
musicbrainz.cpp:(.text+0x137): undefined reference to `typeinfo for MusicBrainz5::CEntity'
musicbrainz.cpp:(.text+0x14b): undefined reference to `MusicBrainz5::CNameCredit::Artist() const'
musicbrainz.cpp:(.text+0x15d): undefined reference to `MusicBrainz5::CNameCredit::Name[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x19f): undefined reference to `MusicBrainz5::CArtist::Name[abi:cxx11]() const'
CMakeFiles/cantata.dir/devices/musicbrainz.cpp.o: In function `MusicBrainz::lookup(bool)':
musicbrainz.cpp:(.text+0x1895): undefined reference to `MusicBrainz5::CQuery::CQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
musicbrainz.cpp:(.text+0x1b29): undefined reference to `MusicBrainz5::CQuery::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
musicbrainz.cpp:(.text+0x1baa): undefined reference to `MusicBrainz5::CMetadata::Disc() const'
musicbrainz.cpp:(.text+0x1bc4): undefined reference to `MusicBrainz5::CMetadata::Disc() const'
musicbrainz.cpp:(.text+0x1bcc): undefined reference to `MusicBrainz5::CDisc::ReleaseList() const'
musicbrainz.cpp:(.text+0x1be6): undefined reference to `MusicBrainz5::CMetadata::Disc() const'
musicbrainz.cpp:(.text+0x1bee): undefined reference to `MusicBrainz5::CDisc::ReleaseList() const'
musicbrainz.cpp:(.text+0x1c0c): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x1c27): undefined reference to `MusicBrainz5::CList::Item(int) const'
musicbrainz.cpp:(.text+0x1c39): undefined reference to `typeinfo for MusicBrainz5::CRelease'
musicbrainz.cpp:(.text+0x1c3e): undefined reference to `typeinfo for MusicBrainz5::CEntity'
musicbrainz.cpp:(.text+0x1da2): undefined reference to `MusicBrainz5::CQuery::SetProxyHost(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
musicbrainz.cpp:(.text+0x1e07): undefined reference to `MusicBrainz5::CQuery::SetProxyPort(int)'
musicbrainz.cpp:(.text+0x1ea5): undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
musicbrainz.cpp:(.text+0x1f1e): undefined reference to `MusicBrainz5::CQuery::~CQuery()'
musicbrainz.cpp:(.text+0x1fca): undefined reference to `MusicBrainz5::CQuery::~CQuery()'
musicbrainz.cpp:(.text+0x232c): undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
musicbrainz.cpp:(.text+0x24ff): undefined reference to `MusicBrainz5::CRelease::ID[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x255e): undefined reference to `MusicBrainz5::CQuery::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
musicbrainz.cpp:(.text+0x259c): undefined reference to `MusicBrainz5::CMetadata::Release() const'
musicbrainz.cpp:(.text+0x25b6): undefined reference to `MusicBrainz5::CMetadata::Release() const'
musicbrainz.cpp:(.text+0x2646): undefined reference to `MusicBrainz5::CRelease::MediaMatchingDiscID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
musicbrainz.cpp:(.text+0x268f): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x26bb): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x26dc): undefined reference to `MusicBrainz5::CList::Item(int) const'
musicbrainz.cpp:(.text+0x26ee): undefined reference to `typeinfo for MusicBrainz5::CMedium'
musicbrainz.cpp:(.text+0x26f3): undefined reference to `typeinfo for MusicBrainz5::CEntity'
musicbrainz.cpp:(.text+0x2796): undefined reference to `MusicBrainz5::CRelease::Title[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x2802): undefined reference to `MusicBrainz5::CRelease::MediumList() const'
musicbrainz.cpp:(.text+0x280a): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x2824): undefined reference to `MusicBrainz5::CMedium::Position() const'
musicbrainz.cpp:(.text+0x2903): undefined reference to `MusicBrainz5::CMedium::Position() const'
musicbrainz.cpp:(.text+0x291a): undefined reference to `MusicBrainz5::CRelease::ArtistCredit() const'
musicbrainz.cpp:(.text+0x2989): undefined reference to `MusicBrainz5::CRelease::Date[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x2a90): undefined reference to `MusicBrainz5::CMedium::TrackList() const'
musicbrainz.cpp:(.text+0x2ac9): undefined reference to `MusicBrainz5::CList::NumItems() const'
musicbrainz.cpp:(.text+0x2b0f): undefined reference to `MusicBrainz5::CList::Item(int) const'
musicbrainz.cpp:(.text+0x2b21): undefined reference to `typeinfo for MusicBrainz5::CTrack'
musicbrainz.cpp:(.text+0x2b26): undefined reference to `typeinfo for MusicBrainz5::CEntity'
musicbrainz.cpp:(.text+0x2b3a): undefined reference to `MusicBrainz5::CTrack::Recording() const'
musicbrainz.cpp:(.text+0x2b8f): undefined reference to `MusicBrainz5::CTrack::Position() const'
musicbrainz.cpp:(.text+0x2ba9): undefined reference to `MusicBrainz5::CTrack::Length() const'
musicbrainz.cpp:(.text+0x2c71): undefined reference to `MusicBrainz5::CTrack::ArtistCredit() const'
musicbrainz.cpp:(.text+0x2c85): undefined reference to `MusicBrainz5::CTrack::ArtistCredit() const'
musicbrainz.cpp:(.text+0x2cd7): undefined reference to `MusicBrainz5::CTrack::Title[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x2df5): undefined reference to `MusicBrainz5::CRecording::ArtistCredit() const'
musicbrainz.cpp:(.text+0x2e4b): undefined reference to `MusicBrainz5::CTrack::Title[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x2e85): undefined reference to `MusicBrainz5::CRecording::Title[abi:cxx11]() const'
musicbrainz.cpp:(.text+0x33ef): undefined reference to `MusicBrainz5::CMediumList::~CMediumList()'
musicbrainz.cpp:(.text+0x3401): undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
musicbrainz.cpp:(.text+0x34f5): undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
musicbrainz.cpp:(.text+0x372f): undefined reference to `MusicBrainz5::CMediumList::~CMediumList()'
musicbrainz.cpp:(.text+0x3803): undefined reference to `MusicBrainz5::CMediumList::~CMediumList()'
musicbrainz.cpp:(.text+0x3984): undefined reference to `MusicBrainz5::CMetadata::~CMetadata()'
collect2: error: ld returned 1 exit status
CMakeFiles/cantata.dir/build.make:9468: recipe for target 'cantata' failed
make[2]: *** [cantata] Error 1
CMakeFiles/Makefile2:65: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by CDrummond** [comment]
This is a LINK error not a compile error. You have updated, you need to clean your build folder and do a complete refresh.

**Comment by parkmino** [comment]
Thanks for your advice.
You're right and it is not an issue.
