### ISSUE TITLE
"Locate in Library" doesn't work when Library tab is grouped by album

### ISSUE THREAD

**Issue by eikehein** [CDrummond/cantata#751]
I have my Library view grouped by album and sorted by modified date. "Locate in Library" from a playlist item will raise and activate the Library view, but not jump to the corresponding library item. When the view is grouped by artist, the action is working fine.

**Comment by CDrummond** [comment]
Seems to work just fine for me. Is this with all albums?

**Comment by CDrummond** [comment]
It is expanding the album, but not highlighting the track. Is this what you mean?

**Comment by CDrummond** [comment]
Song selection now fixed. Can you update and try again?

**Comment by eikehein** [comment]
It's working now, thanks! It's possible I didn't notice the tree expanding before because, missing the selection, the view also wasn't scrolled to the item, and with my long, long tree it's usually out of view.

**Comment by CDrummond** [comment]
Thanks for the confirmation!
