### ISSUE TITLE
Consistency in sorting behaviour

### ISSUE THREAD

**Issue by roberth1990** [CDrummond/cantata#752]
As everyone knows, a lot of bands has a "the" in the start of the their names. So in the library view the "the" is ignored when sorting the bands after their names.

But in when sorting it this way in the play queue, it doesn't ignore the "the", could this be fixed to create more consistency in the behaviour? It is very confusing to when things are sorted differently and not ignoring the "the" is annoying in the first place.

**Comment by CDrummond** [comment]
Seems a reasonable request :-)

Note that 1.x is no longer being developed, so this will have to be in the next release (2.0)

**Comment by CDrummond** [comment]
Implemented in master - for 2.0

**Comment by roberth1990** [comment]
Thank you.
