### ISSUE TITLE
Windows version virus detected by Google

### ISSUE THREAD

**Issue by thuantran** [CDrummond/cantata#754]
Hi there,

Dunno why but if I try to download version 1.5.2 for windows on your download wiki page https://github.com/CDrummond/cantata/wiki/Previous-%28Google-Code%29-Downloads , it shows an error with virus detected in the binary and prevent me to download the file. Can you check that?

Best regards,
Thuan

**Comment by CDrummond** [comment]
This is just google drive being silly yet again...

https://github.com/CDrummond/cantata/issues/543
https://github.com/CDrummond/cantata/issues/505
