### ISSUE TITLE
Feature request: Possible for the backdrop image to be blank if none can be found?

### ISSUE THREAD

**Issue by ms6676749** [CDrummond/cantata#757]
After starting my dynamic playlist, I often like to stay in information view (F12).  For example, say after I finished listening to a Barbara Streisand song (stay with me here) and the following track is a Ramones song (say fanart.tv doesn't have a backdrop image of them), Barbara's visage continues to haunt the background until a backdrop image can be found for the subsequent artist.

Is there a way for the background to blank out once the context widget cannot find the backdrop image?

**Comment by CDrummond** [comment]
Ah, that is indeed a bug - it should clear the image.

**Comment by CDrummond** [comment]
Should be fixed in mast, please update and confirm.

**Comment by ms6676749** [comment]
Updated to b312cec and can confirm that this issue is fixed.  Thanks !
