### ISSUE TITLE
Files not tagued when extracting a CD

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#758]
I've extracted 2 audio-CD in OGG Vorbis using the internal Cantata feature. The files are correctly created and put in the correct folder but they are not tagged. I had to re-tag them properly using another tool.

**Comment by CDrummond** [comment]
Just ripped a CD using oggenc and ffmpeg - in both cases files were correctly tagged. I confirmed the tags using kids-qt

Perhaps its a TagLib issue on your system? Can you use cantata's tag editor to change the tags?

**Comment by edhelas** [comment]
I had a look, yes actually it seems that the TagLib is not properly setup on my system. I seems to come from a missing dependency during the Debian package setup. I have to complete the CMakeLists.txt file to add theses dependencies during the built.

**Comment by CDrummond** [comment]
So, its now working?

But, Cantata's device support should be disabled if it could not find taglib...

**Comment by edhelas** [comment]
No not yet, I'd like to fix the CMake script to force the dependency.

**Comment by CDrummond** [comment]
As stated, works for me. Please email and CMakeLists.txt changes. But this bug itself is invalid
