### ISSUE TITLE
cache.xml.gz is not take into account on devices

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#760]
Step to reproduce:
- Plug a device
- Synchronise some files with it
- Cantata will create a .cache.xml.gz file
- Unplug the device
- Plug-it again
- Cantata can't see the previously synchronized tunes

Maybe related:
When I do right click on an album and I select "copy them on the device", I can't click on my device that is displayed in the sub-menu.

**Comment by CDrummond** [comment]
Fixed.

**Comment by edhelas** [comment]
The "copy them on device" issue is fixed but Cantata still loose the .cache.xml file when it resynchronise after I re-plug the device to the computer.

**Comment by CDrummond** [comment]
How does it loose the cache file? I don't have any UMS devices at the moment - but have enabled remote devices and added a file-system device. This uses the same code as the UMS device. This *does* read and use the cache file.

What makes you think its lost? Does it re-scan?
