### ISSUE TITLE
Tagging one file results in a full library reload

### ISSUE THREAD

**Issue by frispete** [CDrummond/cantata#763]
Dear Craig,

I'm sure, this due to the mpd protocol regime, but if you could briefly describe roughly the current logic from Cantata POV, possibly with code pointers, and your opinion on ways to solve this, that would be great.

Setup: local MPD, running as user, proxy to server, files also accessible r/w via NFS.

**Comment by CDrummond** [comment]
That's the way it is. MPD only states that the DB has changed, not what the changes are. So, Cantata needs to reload everything.

Cantata 1.x stored the complete music list in memory, so when a new list was received it itself determined what was added, removed, or changed.

Cantata 2.x stores the info in an SQLite database. Now, this *could* be iterated over to determine changes, etc. But this would be a lot of work. Listing the music, and playing, is more frequent than tag editing - hence the code is not 'optimised' for that.

Also, the DB is populated bit by bit - Cantata gets the music listing from MPD folder by folder, and the DB is created step by step. To recreate the 1.x scenario, Cantata would need to wait until the complete DB has been received, and then check for changes. This would use more memory. Or, it could be more intelligent and use the 'Last-Modified' dates on folders.

**Comment by frispete** [comment]
Thanks for your notes, Craig.

I forgot to mention, why this is an issue: there's no visual feedback during the reload, other than Cantata appearing to be unresponsive for several minutes (42k tracks in database).
I found this by examining the (verbose) mpd logs. Some kind of busy notification would be nice.

**Comment by CDrummond** [comment]
Which cantata version 1.x? If so, then this will be due to the way it load *all* songs from MPD, then sends all of them to the 'music model'. This then checks for add/deleted/changes songs.

The newer 2.x should improve this, by the fact that it requests songs folder by folder, and send these folder by folder to the SQLite database. However, when this is happening the 'Library' view will be blank.

**Comment by CDrummond** [comment]
Also, there should be a 'spinner' in the artists/albums (for 1.5.2) view - as well as the text "Loading..." (or something like that)

**Comment by frispete** [comment]
Sorry for not mentioning the version: 2.x: I noticed the spinner for the album/artist view even for 2.x, but not in the play queue. You cannot interact with the play queue during that time.

**Comment by CDrummond** [comment]
Yeah, I suspect you are correct. The MPD comms happen in a separate thread, which will be busy listing the folders. I have an idea for a quick work-around. If I post some update instructions here, will you be able to update the code and check? (This will probably be tomorrow at the earliest though)

My DB only takes a couple of seconds to update, so probably not enough for me to verify any work arounds...

**Comment by frispete** [comment]
I take whatever you gave me, commits, branches, patches - make your choice.

If you commit to your master branch, it's just a matter of running 3 commands for me to be current.
And these builds are available to anyone: https://build.opensuse.org/project/monitor/home:frispete:mpd
who's running one of the current openSUSE releases (package cantata-git).

**Comment by CDrummond** [comment]
I've updated the code, so that other events are processed whilst loading the library. However, the library loading is quite intensive in the UI side, so not sure how much benefit this really is...

**Comment by frispete** [comment]
Will test and call back soon... 

Question is, why does it show the business in the library, but not in the play queue.

**Comment by CDrummond** [comment]
Because its updating the library, not the play queue.
