### ISSUE TITLE
Feature request: Local storage of artist art

### ISSUE THREAD

**Issue by mach-o** [CDrummond/cantata#768]
My Cantata setup connects to a remote mpd server, and I would like to be able to set artist art without having to network mount the remote server's drive that contains the Music directory. I believe that Cantata stores album cover art locally already, so it seems like a natural feature to allow, and it seems like it should not require any major changes.

I envision something like simply setting the existing "Music Folder" setting to some local folder, for example, ~/.cantata and to have the images stored there. If I try to do this now, when I attemt to set the artist image, I get a popup indicating "Failed to set cover! / Could not copy the file to ~/.cantata/{Artist}/{Album}/artist.jpg" (the relevant source seems to be at gui/conerdialog.cpp:1292–1322). What I propose is for mpd to simply create those parent directories and to store the image there, and retrieve it as necessary.

One detail to note, however: it's strange to me that {Album} comes into the error text here, because I'm just trying to set the artist image. In fact, if I manually create ~/.cantata/{Artist}/{Album} and try setting the cover, it works, and ends up at ~/.cantata/{Artist}/cover.jpg (without the {Album} level). But even this partial workaround isn't functional: although the image is successfully saved locally, Cantata doesn't display it.

Thanks for considering this!

**Comment by CDrummond** [comment]
When saving artist images, Cantata will only save if the hierarchy is at least two levels deep - as stated in the config dialog. it expects 'Artist/Album/Track.mp3' . It will then remove the first level, and save there - by calling QDir::cdUp. If the folder does not exist, then this will not work.

The only thing I can do is have the cover dialog save the image to the cache folder - Cantata should automatically look there.

**Comment by mach-o** [comment]
Thanks for the reply. I wonder if a more reliable and coherent solution would be just to add a line at gui/coverdialog.cpp:1294 to create the two-level hierarchy:

`QDir(mpdDir).mkpath(dirName) // create Artist/Album folder (untested code as illustration) `

As I mentioned, when I create the folder manually, Cantata will already properly save `artist.jpg` in the right place. Al that would be left is to retrieve and display the images at the appropriate time. What do you think?

**Comment by CDrummond** [comment]
If folder does not exist, then image is saved in cache folder.

**Comment by mach-o** [comment]
Great, thanks so much!
