### ISSUE TITLE
Internet connections

### ISSUE THREAD

**Issue by deshtop** [CDrummond/cantata#769]
Hello

Under Config -> Interface -> Artists it says that cantata automatically downloads missing album art.

Personally I like my software - including my mpd client - not to connect to any servers unless explicitly told to do so. Reason being that I see a privacy issue here, as i don't like amazon, last.fm, discogs or whom ever to have insights in my music library.

Is there an option to disable all connections to any foreign servers? I mean disabling of fetching album art, lyrics, guitar tabs or any such data, i don't mean a foreign mpd server.

Thanks.

**Comment by CDrummond** [comment]
Look at the config settings. Disable cover fetching from Last.fm (it's in the config dialog), remove all lyrics providers (in config dialog), and don't use the context view.

Alternatively, edit Cantata's config file and set "networkAccessEnabled=false" in the "[General]" section. This is described in the README. This does not affect the MPD connection.
