### ISSUE TITLE
Look for cover images in (certain) subdirectories.

### ISSUE THREAD

**Issue by melvinvermeeren** [CDrummond/cantata#771]
First of all, thanks a lot for creating and maintaining this awesome music player!

I really like the feature that shows the album cover as the background image. However, a bunch of my collection has the album covers in a separate "Scans" directory and Cantata only looks in the directory of the audio files at the moment.

Is it possible that subdirectories are automatically scanned? Probably only 1 level deep to prevent issues with big folder trees. The first image found could then be selected automatically.

Thanks,

Melvin.

**Comment by CDrummond** [comment]
Implemented in master for Cantata 2.0. When looking in sub-directories the standard names are checked first (cover, AlbumArt, folder, etc)

**Comment by melvinvermeeren** [comment]
Just recompiled from master and it's working great!
Thanks a lot for the insanely fast implementation! :+1:
