### ISSUE TITLE
Locate in Library doesn't work

### ISSUE THREAD

**Issue by darkfeline** [CDrummond/cantata#772]
The Locate in Library functionality isn't working.

To reproduce:

1. Right click song in Play Queue.
2. Click Locate in Library.

The sidebar will switch to the Library if it isn't there already, but it will not jump to or select the respective song.

This is on a fresh build on the master branch.

**Comment by CDrummond** [comment]
Can't check right now - but this did work. What is your library set to group by? Have you tried multiple different artists?

**Comment by CDrummond** [comment]
Just tried with all 3 groupings (genres, artists, and albums) - Locate in library worked just fine. So, gonna need more info.

**Comment by darkfeline** [comment]
Library settings:
- Group by Artist
- View Detailed Tree
- Sort Albums: Year

However, I have tried different groupings and views and still see this problem.

No error output when run from terminal.

- Qt 5.5.1, master branch: Bug happens.
- Qt 5.5.1, Cantata 1.5.2: Bug doesn't happen.
- Qt 4.8.7, master branch: Bug happens.
- Qt 4.8.7, Cantata 1.5.2: Bug doesn't happen.

Therefore, it looks like a regression between 1.5.2 and the master branch, at least for me.

One unusual thing that I'm doing is that my songs are all symbolically linked because I am using git annex, although I haven't had any issues with mpd or cantata with this before.  It looks roughly like this:

~~~
music
    .git/annex
        actual song.mp3
    song.mp3 (symlink to actual song.mp3)
    .mpdignore (ignores .git directory)
~~~

I'll try to do a bisect later to see which commit introduced this.

**Comment by CDrummond** [comment]
The whole library handling is different between 1.x and master. However, I have just tried your settings (they are what I use) and locate works just fine. Again, have you tried different artists?

Also, locating tracks will only work if the files are from MPD.

I've made a /slight/ modification, which will fix the issue if your files are tagged with music brainz alubm ids (and you have MPD configured for these). Please update.

**Comment by darkfeline** [comment]
Fixed now.

All my songs were tagged with MusicBrainz.  I did not have MPD configured for MusicBrainz's tags though.

I enabled all metadata tags in MPD (including MusicBrainz tags), refreshed MPD's database, rebuilt and restarted Cantata.  Now Locate in Library is working again.

**Comment by CDrummond** [comment]
If you did not enable music brainz in MPD, then these tags should not have been in Cantata's DB (as it gets the metadata from MPD), and the songs in the playqueue should not have had these tags either. How odd. Well, at least it is now working.

**Comment by darkfeline** [comment]
@CDrummond I'm sort of running into this issue again and decided not to create a new issue for now.  Warning: it's really odd.

I'm on a926fce.

When starting Cantata, Locate in Library works.  After some time, it stops working.  My library is set to view simple tree, group by album.  The other group bys work, just not album.

I switch view to detailed tree.  Now Locate in Library works in all group bys.  I switch view back to simple tree.  Now Locate in Library works in all group bys.

As far as reproducing, all I can say is that sometime after Cantata has been running, Locate in Library stops working for view simple tree, group by album.

This affects all of my songs regardless of artist or album when it manifests.

One thing that comes to mind is that I'm using Locate in Library to then delete unwanted songs.  It might be that the MPD database gets out of date and Cantata chokes on that?

I'll update if I get more info.

**Comment by darkfeline** [comment]
Okay, I think I've found a reproducible case of this happening.

The following song doesn't work with Locate in Library, with grouping by album:

https://musicbrainz.org/release/5aab3b62-d5d8-4059-8259-6991663a8807/disc/1#456c1474-4e1f-3fe1-b925-97e252bdc05c (last track)

Here's a metadata dump: http://pastebin.com/96CUhcPA

From the dump, I suspect the ID3v1 tags are causing the problem.

**Comment by CDrummond** [comment]
If you want me to investigate this further, please create a *dummy* mp3 with the same tags as above, and then add a link to it in this issue. I dont know how to use the tag dump to create a file with these tags. Not much I can do without having a source file with the correct tags.

There will be no "after some time" issue - time will not have an effect, just which songs you are looking for and their tags.

**Comment by CDrummond** [comment]
To create a silent mp3 with the same tags as your original:

1. Save the following as silence.pl:

------------------------8<-----------------------

#!/usr/bin/perl

$seconds = $ARGV[0];
$file = $ARGV[1];
if ((!$seconds) || ($file eq "")) {
        die "Usage: silence seconds newfilename.wav\n";
}

open(OUT, ">/tmp/$$.dat");
print OUT "; SampleRate 8000\n";
$samples = $seconds * 8000;
for ($i = 0; ($i < $samples); $i++) {
        print OUT $i / 8000, "\t0\n";
}
close(OUT);

# Note: I threw away some arguments, which appear in the original
# script, and which did not worked (on OS X at least)
system("sox /tmp/$$.dat -c 2 -r 44100 -e signed-integer $file");
unlink("/tmp/$$.dat");

------------------------8<-----------------------

2. Create silent wav file:   perl silence.pl 3 silence.wav
3. Convert wav to mp3: ffmpeg -i silence.wav silence.mp3
4. Copy tags from your original file: id3cp original.mp3 silence.mp3

Then post a link to silent.mp3 This way I have a file with the tags, but there is no copyrightable data to worry about. Perhaps doing this for all files from the album might help?

**Comment by darkfeline** [comment]
https://mega.nz/#!fFdziZoI!X0djt6OBJHVcs4L5_j42_ljwg97Hn_ksJlLuhueqgVQ

The first track works with Locate in Library, the last (41) doesn't.  I think all except the first do not work.

**Comment by CDrummond** [comment]
Thanks for this, I will download later when I'm at home. I take it these are just silent files? Or at least non-copyright files?

**Comment by CDrummond** [comment]
These files work fine for me - see: http://www.tempfiles.net/download/201512/378526/cantata.html

**Comment by darkfeline** [comment]
Link doesn't work for me.

Here's my cantata config: http://pastebin.com/FXSCu65j

I've made the following observations:

- So far the songs that do not work are part of an album with multiple artists.  For example track 1 has artist Foo, track 2 has artist Bar.
- The songs that do not work contain Unicode (Chinese/Japanese characters) in title, artist, and/or album.
- Songs with (but not limited to) artist field `<character name>(CV: <singer name>)` or `<character name> starring <singer name>` do not work.
- The songs that do not work don't show up in the Library (grouped by album) at all.  For example the library shows:

    ~~~
    Album
    01 Song
    08 Song
    ~~~

    I have tracks 2 through 7, but they don't show up in the library or work with Locate in Library.

**Comment by CDrummond** [comment]
(Yeah, that links not working for me either - try http://www.tempfiles.net/download/201512/378527/cantata.html

Your mpd.conf would be helpful.

**Comment by CDrummond** [comment]
Made a slight change - which fixes this for the special 'Single Tracks; case, which /might/ help you.

**Comment by CDrummond** [comment]
Tried your config - and still works for me.

**Comment by darkfeline** [comment]
mpd.conf: http://pastebin.com/VMFhQtA9

Updated to bd395cc, still experiencing.

**Comment by CDrummond** [comment]
Right, there was a slight bug in the code :-) Please update. When you do you will see that this album is now split into 5 albums - due to different artists. To resolve this, you need to configure MPD to use the albumartist tag.

**Comment by darkfeline** [comment]
Thanks, it's working now.

However, does it make sense to split an album up because of multiple artists?  For one, that seems to defeat the purpose of grouping by Album.

**Comment by CDrummond** [comment]
Yes, it makes sense. What would I use as the artist of the album? What if you have 2 albums called 'Greatest Hits' by two different artists? There is a reason why the album-artist tag exists...

**Comment by darkfeline** [comment]
~~The artist tag is not the same as the albumartist tag though.  Right now one unique album, with the same album tag and albumartist tag is being split up into multiple unique albums based on different artist tags.~~

I thought I had enabled the `albumartist` tag as I included all of the metadata values listed in `man mpd.conf`, but `albumartist` isn't listed there, so naturally I didn't have it enabled.

**Comment by daraul** [comment]
Shouldn't the `follow_inside_symlinks` option fix this? It fixed it for me in ncmpcpp.
