### ISSUE TITLE
Increase the quality of cover image for unknown song in library

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#773]
It is a low quality CD image at the moment like below.
![2015-12-08-120847_458x275_scrot](https://cloud.githubusercontent.com/assets/12131158/11646780/7f025b86-9da4-11e5-9dd3-6deaa806e9cf.png)

**Comment by CDrummond** [comment]
Not sure why you are seeing that - as the album icon is coming from the theme. On my system the icon is very sharp, and nothing like that. Looks like you are also using Unity, so it should be the same.

Anyway, I have now bundled 2 svgs from the CD icon - one for small sizes, and one for large sizes - this should resolve this issue.
