### ISSUE TITLE
File corruption during FLAC transfer to devices in Cantata

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#776]
I have an issue to play FLAC files that are transfered on my device (iPod Mini using Rockbox) using Cantata. I saw that the hashsum of the files were not the same.
With a "raw" transfert using a file explorer or cp I don't have this issue.

Is it possible that Cantata apply some modifications to the FLAC files during the transfers that causes corruptions ? This doesn't seems to be applied to the OGG files.

**Comment by CDrummond** [comment]
There must be some issue with your device. Cantata's copying is *very* trivial - it reads chunks of 32k from the source, and writes to the destination. That's it. The only changes it would make are to the tags - and only if embedding covers, or applying the 'Various Artists' fix.

Why do you think the files are corrupt? Do they not play?

**Comment by edhelas** [comment]
Rockbox just has an issue at the last second of each files and cannot reach the next one. During this 32k copy is the last chunk managed correctly ? I didn't put any parameters in Cantata so the file should be the same than on my hard drive but the checksum is different.

**Comment by CDrummond** [comment]
How large is the original file? I'll try to make a dummy FLAC of the same size, and test copying to a USB drive.

**Comment by edhelas** [comment]
Well I've tried with many different FLAC files but it's around 20-30mb.

**Comment by CDrummond** [comment]
Oops! there is indeed an error copying files! Sorry, will fix!

**Comment by edhelas** [comment]
Sure ! Thank you very much :)

**Comment by CDrummond** [comment]
Please update - should now be fixed. Very silly mistake...

**Comment by edhelas** [comment]
Same md5sum, and the playback is fixed on Rockbox. I'm closing the issue. Thanks again :)
