### ISSUE TITLE
Dynamically generated lists: can't create a playlist to play random songs from my entire music collection.

### ISSUE THREAD

**Issue by Aqa-Ib** [CDrummond/cantata#777]
Hello again Mister CDrummond. I have compiled the last git version of cantata in Debian 8 'Jessie' with KDE support. 

In the past, with a very old version of cantata I could create a dynamic playlist to play random songs from my entire music collection. To accomplish that, I create a dynamic playlist with just a simple exclude artist 'foo' rule. With only that rule, if I played the playlist, cantata would play random music from my entire music collection. 

The problem is that starting with some old version, a possible regression made that playlist to stop working. Could it be possible to have that functionality working again?

THANK YOU VERY MUCH SIR.
Sincerely,
Aqa-Ib.

**Comment by phantom-code** [comment]
Same here with Cantata 1.5.2 on Arch Linux. I'm unable to play a dynamic playlist. It doesn't add tracks in the play queue and just stops immediately.

**Comment by CDrummond** [comment]
Just tried git/master (1.5.x is no longer maintained - don't have time for 2 versions), and it is working just fine for me. 
#Do any dynamic playlists work for you? If not, where is cantata installed? And where is the cantata-dynamic script installed? e.g. on my Ubuntu system cantata is in /usr/bin/cantata and cantata-dynamic /usr/share/cantata/scripts/cantata-dynamic

Also, to randomise all tracks - just having a dynamic playlist with no rules should be sufficient. Tried wit this, and your setup - both working.

**Comment by phantom-code** [comment]
I have built cantata from git and still have the same result. An empty dynamic playlist rule doesn't add anything to the playing queue.
I have cantata binary in the /usr/bin/cantata
and cantata-dynamic script in the /usr/share/cantata/scripts/cantata-dynamic

Is there a way I can help you to solve this issue?

**Comment by phantom-code** [comment]
Just tried to run the cantata-dynamic script and got following:

Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /usr/share/cantata/scripts/cantata-dynamic line 33.
BEGIN failed--compilation aborted at /usr/share/cantata/scripts/cantata-dynamic line 33.

**Comment by phantom-code** [comment]
OK, I installed perl-uri package and now the issue is solved for me. It seems that archlinux package misses this dependency.

**Comment by Aqa-Ib** [comment]
GOOD! Thank you very much friends, it is solved now. I installed the program that phantom-code said and now it is working. In debian the package name is "liburi-perl". I will report a bug against cantata in the debian bug tracker to ask the maintainer to add that dependency or at least as recommendation to cantata.

CANTATA ROCKS!
Regards, 
Aqa-Ib

**Comment by phantom-code** [comment]
In the case of Arch Linux, cantata's package has a perl-uri dependency. But it's an optional dependency and to be honest, it's my fault that I didn't have installed it before.

**Comment by CDrummond** [comment]
Thanks for taking the time to resolve this. Not sure how perl modules can be marked as dependencies...
