### ISSUE TITLE
Sorting issue in library view sorted by %album artist%

### ISSUE THREAD

**Issue by ms6676749** [CDrummond/cantata#778]
Archlinux
Cantata-git e7ef5f6

Issue: `album artist` is not sorted correctly where there's different artists populating the album's `artist` tags and the artists have other albums in the database.  I will be referencing from the attached pic.  In one of my classical genres, I have the name of the performer as `album artist`, say a pianist, and the composers in the `artist` and `composer` tags of their respective songs.  In other genres, `album artist` will be "Various Artists" and Cantata sort those albums just fine.

From my picture, the top example is where the performer is named in the `album artist` tag and different composers she's performing are in their proper `artist` and `composer` tags.  Here, none of the composers are found on any other album in my library except for the one highlighted here and `album artist` is sorted appropriately.  

Below, in the lower box, the difference is that the composers in the `artist` tags have several other albums in the Library and now the `album artist` is now sorted where "Various Artists" would be rather properly than under "B".

This is just a minor issue that I happened to catch.

![cantata_snapshot37_edit](https://cloud.githubusercontent.com/assets/13208509/11990128/d9cafbd4-a9bd-11e5-8df7-cf46682c2c2c.jpg)

**Comment by CDrummond** [comment]
Cantata sorts artists using the following tags:

1. AlbumArtist sort
2. Artist sort
3. AlbumArtist
4. Artist

e..g if you have artist-sort but not album-artist sort, then that will be used. If a song has no explicit artist-sort, or album-artist sort then these are created by removing any of the 'ignore prefix' settings. e.g. if a track has no album-artist-sort but album-artist is "The Beatles" and "ignore prefixes" contains "The", then album-artist-sort is set to "Beatles, The"

I suspect, that "Balazs Szokolay" has either artist-sort or album-artist-sort set to "Szokolay, Balazs" - which would explain its position. Please check the song's tags in (e.g.) kid3 - also check if your MPD is configure for the sort tags.

**Comment by ms6676749** [comment]
>I suspect, that "Balazs Szokolay" has either artist-sort or album-artist-sort set to "Szokolay, Balazs" - which would explain its position. Please check the song's tags in (e.g.) kid3 - also check if your MPD is configure for the sort tags.

Ah, it was the latter, as I just started to use Picard and I forgot that it included `ALBUMARTISTSORT` and I somehow overlooked that field when looking at the tags in kid3 prior to opening this report.  Sorry, my bad.
