### ISSUE TITLE
Track ratings synchronization

### ISSUE THREAD

**Issue by phantom-code** [CDrummond/cantata#779]
Hi !
This is not an issue, just a question. I have my music library on a few computers. And it would be nice to have an ability to synchronize track ratings between my machines. I can try to do this with a help of a cloud service (Dropbox, Seafile, etc) for example. As far as I understand, I should sync the "${XDG_DATA_HOME}/cantata/mpd/sticker.sql" file. Could you please comment, is this a correct way to achieve what I want or maybe there is a better way? Thanks!

**Comment by CDrummond** [comment]
Not sure an 'issue' is the correct place for this!

You are correct, ratings are stored in MPD's sticker DB.

**Comment by phantom-code** [comment]
Thanks
