### ISSUE TITLE
It lacks some features

### ISSUE THREAD

**Issue by KOT040188** [CDrummond/cantata#780]
I apologize for the use of a translator google. I like the player cantata, but are lacking some functions. In the left column can be sorted by artist and album, but lacks the ability to sort by genres and composers. I really need these features. I would also like to be able to customize the look of the main playlist, as implemented in the player amarok. After adding these features cantata is the perfect player for me.

**Comment by CDrummond** [comment]
You can already sort by genre. I've now added explicit sort by Composer and sort by Performer.

As to making the grouped view configurable, like Amarok - not going to happen. Sorry, but I like the look as-is, and don't have time for changing. Patches/pull-requests welcome.

**Comment by KOT040188** [comment]
Thanks for the answer.
