### ISSUE TITLE
preferences->context unusable

### ISSUE THREAD

**Issue by glensc** [CDrummond/cantata#782]
![screenshot at 2016-01-05 11 20 06](https://cloud.githubusercontent.com/assets/199095/12111527/a48a3710-b39e-11e5-8ca8-5a5bdcf39f07.png)

i'm unable to figure out how to add/move items from "available" column to "selected" column. i tried
  - double clicking
  - dragging
  - opening context menu (mouse2 tapping)

none of them seemed to work.

my build is qt5 based,
whole rpm spec used for that build can be found [here](https://github.com/pld-linux/cantata/blob/2c1706ee64d8bdfd065abe8fe4028f56ba7ceba0/cantata.spec)

**Comment by CDrummond** [comment]
There should be some buttons to the left of each list - but they only have icons, no text. Looks like your icon theme is missing *lots* of icons.

Which build of Cantata is this?

**Comment by glensc** [comment]
i answered to "which build is this" in original bugreport:

> my build is qt5 based,
> whole rpm spec used for that build can be found here

**Comment by glensc** [comment]
and yes, icons are missing too, i haven't yet looked deeper into which icon theme is required.

i'm using MATE desktop 1.12, so candiates are https://github.com/mate-desktop/mate-themes and
https://github.com/mate-desktop/mate-icon-theme

**Comment by ms6676749** [comment]
Just chiming in here using the 87f711e build (archlinux, Qt5 build, no KDE integration), looks like to be a case of missing icons.
![cap](https://cloud.githubusercontent.com/assets/13208509/12133790/84561452-b3dd-11e5-8ea7-066f384111fa.jpg)

**Comment by CDrummond** [comment]
The build question was asking which version - 1.5.2 or master. As you can see from the above screenshots, the arrow icons are shown. In git/master I use font-awesome based icons for these, so will work even with no icon theme installed.

For your other icons - all I can say is that Cantata has these for Oxygen, Breeze, Gnome, and Humanity icon sets.

**Comment by glensc** [comment]
version is 1.5.2, as seen from .spec i linked to

**Comment by glensc** [comment]
installed [th](https://www.pld-linux.org/th)::[kde4-icons-oxygen](https://github.com/pld-linux/kde4-oxygen-icons)-4.14.3-1.noarch.rpm, so icons appeared now.

so, it's matter of MATE icon theme not supported? actually i'm wondering why not use some standard icons, all themes should be [hicolor theme compatible](http://freedesktop.org/wiki/Software/icon-theme/)

**Comment by glensc** [comment]
btw, i only installed oxygen icons, i did not change the default icon theme.

i don't know how icons work in linux, but sounds weird that icons are looked from any theme not just current one?

**Comment by CDrummond** [comment]
The icons are standard ones - at least in the above mentioned themes. And they are loaded from the current theme. However, Cantata checks if your current theme has a few specific icons, and if not it falls back to Oxygen or gnome.

**Comment by CDrummond** [comment]
This is an issue with your system - so I'm closing. For git/master I might use the same icons as supplied for Windows/Mac builds for non KDE environments.

**Comment by glensc** [comment]
i'm thinking maybe you should also fallback to MATE theme like you do for GNOME

MATE is basically GNOME 2.x being maintained.
as the icons that were missing were not just arrows, but basic play/stop buttons as well.

**Comment by glensc** [comment]
ps: is there ETA when master (2.x) being ready for getting release tagged?

**Comment by CDrummond** [comment]
As soon as all outstanding bugs are closed, I should be ready to release.

I assume you are using MATE? If so, you already had the same issue with the missing icons. However, I have updated git/master to use a bundled set of icons for non KDE environments that are not using gnome or humanity icons. I'm considering using these for *all* desktops...

**Comment by glensc** [comment]
yes, i'm using MATE. alright, using bundled icons should do, altho it likely increases size of cantata (distro) package.

**Comment by CDrummond** [comment]
Actually its only a few svgs, 104k in total :-)
