### ISSUE TITLE
Album art in library view and "top bar" does not correspond

### ISSUE THREAD

**Issue by roberth1990** [CDrummond/cantata#783]
The album artwork was automatically selected, and doesn't correspond until you manually select album artwork.

![screenshot_20160105_213954](https://cloud.githubusercontent.com/assets/2381082/12127033/1c748f2c-b3f5-11e5-9ce9-14c5d2aa4a3d.png)

EDIT: Running GIT version.

**Comment by CDrummond** [comment]
? automatically selected? you mean auto downloaded from last.fm? I can see that there are two covers, just not sure what you mean the issue is. Are you saying that:

a. You had no existing cover. Playing the album put one cover in the toolbar, and looking it the library added another?

b. You already had a cover, which is used in the library - but the toolbar is using another?
???

**Comment by roberth1990** [comment]
a. Yes, and as I said, when I right cliced on the album in library and selected the album cover which was allready there in the library, they both corresponded.

But when I quit cantata and started it again it went back to as shown in the screenshot.

![screenshot_20160106_212244](https://cloud.githubusercontent.com/assets/2381082/12155170/ab05a48a-b4bb-11e5-91dd-1d95fc4a0ef0.png)

One thing I noted that when I clicked on "set image", it doesn't correspond either.

![screenshot_20160106_212431](https://cloud.githubusercontent.com/assets/2381082/12155211/e89a0426-b4bb-11e5-8f82-7431dbfef9b9.png)

And that is whats happening when I try to set the second image which I want now. That didn't happen when I tried to do it right before reporting the bug.

**Comment by CDrummond** [comment]
Not sure what is happening - but it works fine for me. Perhaps clearing cantata's cover cache might help?

**Comment by roberth1990** [comment]
That helped, it immeaditly started to behave correctly after doing what I described and showed in the screenshots, it was only happening with that exact album. Thanks.

**Comment by CDrummond** [comment]
Hmmmm.... Still odd. When you set a cover via the cover dialog it should clear the cache, I guess I need to do the same if downloaded from last.fm.

**Comment by CDrummond** [comment]
Scaled covers removed if new cover downloaded from last.fm, etc.
