### ISSUE TITLE
Cantata has to be restarted if MPD has been stopped and started again

### ISSUE THREAD

**Issue by roberth1990** [CDrummond/cantata#784]
If you stop mpd and start it again(with systemd in my case) while cantata is connected to it, cantata is not able to connect to mpd again, untill you have closed cantata and started it again. This happens every single time.

EDIT: Running GIT version.

**Comment by CDrummond** [comment]
Oops! The 'connect' action was not actually being used! I removed 1 too many lines of code. Should be fixed now, please update and try again.

**Comment by roberth1990** [comment]
Fixed, thanks.
