### ISSUE TITLE
Large sized artist/album artwork when moving mouse over in library view

### ISSUE THREAD

**Issue by roberth1990** [CDrummond/cantata#785]
When you move the mouse over the artwork for either the artists(if it's enabled) and album artwork in library view, you get a large version of the image, like when you do it on album artwork in the top bar.
Instead of just artist name when moving mouse over artist and number of albums or move the mouse over the album you just get artist, album name and year.

**Comment by CDrummond** [comment]
I assume this is a feature request? Not sure I really like the idea of this, as the tooltips can be annoying anyway...

**Comment by roberth1990** [comment]
Yes. Thats why you have settings and not have enabled by default? And/or alternatively if possible only make it happen when moving the mouse over the image in library view.

**Comment by CDrummond** [comment]
Closing - I'd find this distracting, so not going to implement.
