### ISSUE TITLE
Cog icon too dark

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#786]
as following screenshot and hard to find it.

![2016-01-12-152539_243x225_scrot](https://cloud.githubusercontent.com/assets/12131158/12256523/0b03c46e-b941-11e5-8981-45609a109e27.png)

**Comment by CDrummond** [comment]
Hmmm.... it *should* be the same colour as the 'i' icon. What these is this with? Or is this really under windows? If so, which version? And which version of Cantata?

**Comment by parkmino** [comment]
I am using cantata git and ubuntu 15.10 32bit under windows nt theme.

2016-01-12 17:42 GMT+09:00 CraigD <notifications@github.com>:

**Comment by parkmino** [comment]
Compiled the latest git and it looks so from that.

2016-01-12 17:46 GMT+09:00 Min-Ho Park <parkmino@gmail.com>:

**Comment by CDrummond** [comment]
Just to be sure... Which theme is providing the widgets? Are you using Qt's windows theme (cantata -style windows) or some Gtk theme?

**Comment by parkmino** [comment]
Never mind my theme and  I am using sawfish wm. My config is unusial and if
there has been no change regardig this and just ignore this issue.
2016. 1. 12. 오후 9:17에 "CraigD" <notifications@github.com>님이 작성:

**Comment by CDrummond** [comment]
Never mind your theme? Its the widget theme that will affect the icon colours, not the WM theme.

**Comment by parkmino** [comment]
lxappearance  > Widget : Greybird > Icon Theme : elemetary XFCE

**Comment by CDrummond** [comment]
Actually I can recreate this issue if I start cantata as follows:

XDG_CURRENT_DESKTOP=lxde ./cantata

...will fix.

**Comment by CDrummond** [comment]
Should be fixed now - please update and confirm.

**Comment by parkmino** [comment]
Fixed and thanks!
