### ISSUE TITLE
Still requesting Qt5 linguist binaries even when disabling Qt5

### ISSUE THREAD

**Issue by M4he** [CDrummond/cantata#787]
Using Debian 8.2 I couldn't compile Cantata at first.
I was using `cmake .. -DENABLE_QT5=OFF` to compile the Qt4 version as stated in the INSTALL document. However, cmake was still looking for the Qt5 variants of `lconvert` and `lrelease`:
```
lconvert: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lconvert': No such file or directory
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
```

As a workaround I linked those paths to the Qt4 versions:
```
ln -s /usr/lib/x86_64-linux-gnu/qt4/bin/lconvert /usr/lib/x86_64-linux-gnu/qt5/bin/lconvert
ln -s /usr/lib/x86_64-linux-gnu/qt4/bin/lrelease /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease
```

The build process completed successfully and Cantata seems to be running fine.

**Comment by CDrummond** [comment]
What makes you think this is a Cantata issue? All cantata does is find the executables, and call them.

Did you perform a **clean** build - i,e,  **completely** clearing the build folder before running cmake?

**Comment by M4he** [comment]
> What makes you think this is a Cantata issue?

@CDrummond My apologies, if I was jumping to conclusions here.
I've been using Cantata for a long time now and do occasionally download and compile the latest version. However, this hasn't happened before.

I thought that since there actually is a `-DENABLE_QT5` switch, some logic might be missing for it to affect the calls of previously mentioned binaries. I've never developed for Qt before so excuse my lack of knowledge regarding compiling/linking Qt applications.

> Did you perform a clean build - i,e, completely clearing the build folder before running cmake?

Definitely. I extracted the `cantata-master.zip` and created the build dir using `mkdir build` and navigated into it before beginning the compile process, as instructed in the INSTALL document.

**Comment by CDrummond** [comment]
This sounds like you have both the Qt4 and Qt5 dev packages installed, but not the Qt5 linguistic packages.

Before you created the sym-links (or after you remove them) does 'lconvert' work from the commandline? e.g. 'lconvert --help' ???
