### ISSUE TITLE
Problem compiling OpenSuSE Leap 42.1

### ISSUE THREAD

**Issue by fonsocm** [CDrummond/cantata#788]
When git version of 12/01/2016 is compiled in OpenSuSE Leap 42.1 with -DENABLE_LIBVLC=ON using gcc 4.8 or 5, make gives the next error:

[ 96%] Building CXX object CMakeFiles/cantata.dir/qrc_cantata_menu.cpp.o
[ 96%] Linking CXX executable cantata
support/libsupport.a(combobox.cpp.o): En la función `ComboBox::ComboBox(QWidget*)':
combobox.cpp:(.text+0x13): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: En la función `SizeWidget::SizeWidget(QWidget*)':
sizewidget.cpp:(.text+0x4a): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: En la función `SizeWidget::~SizeWidget()':
sizewidget.cpp:(.text._ZN10SizeWidgetD2Ev[_ZN10SizeWidgetD5Ev]+0x3): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: En la función `SizeWidget::~SizeWidget()':
sizewidget.cpp:(.text._ZN10SizeWidgetD0Ev[_ZN10SizeWidgetD0Ev]+0x3): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTI10SizeWidget[_ZTI10SizeWidget]+0x10): referencia a `typeinfo for ComboBox' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x10): referencia a `ComboBox::metaObject() const' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x18): referencia a `ComboBox::qt_metacast(char const*)' sin definir
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x20): referencia a `ComboBox::qt_metacall(QMetaObject::Call, int, void**)' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: En la función `CompletionCombo::~CompletionCombo()':
dynamicruledialog.cpp:(.text._ZN15CompletionComboD2Ev[_ZN15CompletionComboD5Ev]+0x3): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: En la función `CompletionCombo::~CompletionCombo()':
dynamicruledialog.cpp:(.text._ZN15CompletionComboD0Ev[_ZN15CompletionComboD0Ev]+0x3): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: En la función `Ui_DynamicRule::setupUi(QWidget*)':
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x21cd): referencia a `vtable for ComboBox' sin definir
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x2258): referencia a `vtable for ComboBox' sin definir
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x22b1): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x230a): más referencias a `vtable for ComboBox' sin definir a continuación
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTI15CompletionCombo[_ZTI15CompletionCombo]+0x10): referencia a `typeinfo for ComboBox' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x10): referencia a `ComboBox::metaObject() const' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x18): referencia a `ComboBox::qt_metacast(char const*)' sin definir
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x20): referencia a `ComboBox::qt_metacall(QMetaObject::Call, int, void**)' sin definir
CMakeFiles/cantata.dir/tags/tageditor.cpp.o: En la función `CompletionCombo::CompletionCombo(QWidget*)':
tageditor.cpp:(.text._ZN15CompletionComboC2EP7QWidget[_ZN15CompletionComboC5EP7QWidget]+0x83): referencia a `vtable for ComboBox' sin definir
CMakeFiles/cantata.dir/devices/albumdetailsdialog.cpp.o: En la función `Ui_AlbumDetails::setupUi(QWidget*)':
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x10d8): referencia a `vtable for ComboBox' sin definir
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x1138): referencia a `vtable for ComboBox' sin definir
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x1198): referencia a `vtable for ComboBox' sin definir
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x11f8): referencia a `vtable for ComboBox' sin definir
collect2: error: ld returned 1 exit status
CMakeFiles/cantata.dir/build.make:10060: recipe for target 'cantata' failed
make[2]: *** [cantata] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

If  -DENABLE_LIBVLC=OFF, cantata compiles without problem.

**Comment by CDrummond** [comment]
This is a link error - as its complaining about missing symbols. Please try a **completely** clean build. e.g. create a **new** build folder, and run cmake/make within that.

**Comment by fonsocm** [comment]
I cloned again the source from git and created a clean build folder (I always use a clean folder), 

And the problem persist, I obtain the same error.

**Comment by CDrummond** [comment]
Just to be sure:

1. Clean checkout
2. New build folder
3. cmake -DCMAKE_INSTALL_PREFIX=/usr
4. make
5 ...error as above?

ENABLE_LIBVLC should be on by default, so no need to add.

Which Qt version? Which version of libvlc?

**Comment by fonsocm** [comment]
I follow of all the instructions and the result is the same.

The version of Qt is 5.5.1-3 from official repositories of Leap. The version of libvlc is libvlc5-2.2.1-305.1 and libvlccore8-2.2.1-305 from Packman.

**Comment by CDrummond** [comment]
Same VLC version as Ubuntu, but newer Qt. Sorry, but builds fine for me. And as I said your error log above is a link error - due to missing symbols, but not related to vlc.

Just tried a clean Qt5/VLC build under Ubuntu 15.10 - and builds just fine.

**Comment by fonsocm** [comment]
When I obtained the error, I went to software.opensuse.org in order to find a recent version in rpm. 

There is a version in Tumbleweed: https://build.opensuse.org/package/show?project=home%3Ascalpel4k&package=cantata and looking in the spec file, the option of VLC is disabled.

Thanks for your consideration.

Only one question the version of VLC in Ubuntu is from Ubuntu or Videolan? In OpenSuSE, the versions most used are Videolan and Packman because they support not free codecs. Perhaps Packman changed something in the construction of rpm.

**Comment by CDrummond** [comment]
Even if there is a difference in VLC - it does not explain your errors. Your errors have **nothing** to do with VLC. In the whole error log VLC is not mentioned even once. This is the odd part.

**Comment by xdarklight** [comment]
just a side-note (not sure if it's important):
I have just successfully built cantata on Arch Linux which also uses Qt 5.5.1

**Comment by CDrummond** [comment]
With VLC ?

**Comment by xdarklight** [comment]
it was disabled in my last build, thus I rebuilt cantata with vlc enabled: https://paste.kde.org/plttxjhaz

```
$ vlc --version
VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)
VLC version 2.2.1 Terry Pratchett (Weatherwax) (2.2.1-0-ga425c42)
Compiled by builduser on  (Dec  6 2015 12:31:40)
Compiler: gcc version 5.3.0 (GCC)
```

still compiles fine here

**Comment by CDrummond** [comment]
I'm guessing this is either an issue on the reporter's system, or with the openSUSE packages. If its compiling with libvlc 2.2.1 and Qt 5.5.1 on Arch then I'm not sure what I can do to fix this 'issue'

Thanks for the feedback.

**Comment by fonsocm** [comment]
No, thanks to you, you make great software for KDE.

I used for many years QtCurve.

**Comment by eikehein** [comment]
FWIW I experience the same build issue on Fedora 23 against Qt git 5.6 branch.

**Comment by eikehein** [comment]
[ 34%] Linking CXX executable cantata
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: In function `SizeWidget::SizeWidget(QWidget*)':
sizewidget.cpp:(.text+0x4a): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: In function `SizeWidget::~SizeWidget()':
sizewidget.cpp:(.text._ZN10SizeWidgetD2Ev[_ZN10SizeWidgetD5Ev]+0x3): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o: In function `SizeWidget::~SizeWidget()':
sizewidget.cpp:(.text._ZN10SizeWidgetD0Ev[_ZN10SizeWidgetD5Ev]+0x3): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTI10SizeWidget[_ZTI10SizeWidget]+0x10): undefined reference to `typeinfo for ComboBox'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x10): undefined reference to `ComboBox::metaObject() const'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x18): undefined reference to `ComboBox::qt_metacast(char const*)'
CMakeFiles/cantata.dir/widgets/sizewidget.cpp.o:(.data.rel.ro._ZTV10SizeWidget[_ZTV10SizeWidget]+0x20): undefined reference to `ComboBox::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: In function `CompletionCombo::~CompletionCombo()':
dynamicruledialog.cpp:(.text._ZN15CompletionComboD2Ev[_ZN15CompletionComboD5Ev]+0x3): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: In function `CompletionCombo::~CompletionCombo()':
dynamicruledialog.cpp:(.text._ZN15CompletionComboD0Ev[_ZN15CompletionComboD5Ev]+0x3): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o: In function `Ui_DynamicRule::setupUi(QWidget*)':
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x1825): undefined reference to `vtable for ComboBox'
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x18ba): undefined reference to `vtable for ComboBox'
dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x191d): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:dynamicruledialog.cpp:(.text._ZN14Ui_DynamicRule7setupUiEP7QWidget[_ZN14Ui_DynamicRule7setupUiEP7QWidget]+0x1976): more undefined references to `vtable for ComboBox' follow
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTI15CompletionCombo[_ZTI15CompletionCombo]+0x10): undefined reference to `typeinfo for ComboBox'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x10): undefined reference to `ComboBox::metaObject() const'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x18): undefined reference to `ComboBox::qt_metacast(char const*)'
CMakeFiles/cantata.dir/dynamic/dynamicruledialog.cpp.o:(.data.rel.ro._ZTV15CompletionCombo[_ZTV15CompletionCombo]+0x20): undefined reference to `ComboBox::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/cantata.dir/tags/tageditor.cpp.o: In function `CompletionCombo::CompletionCombo(QWidget*)':
tageditor.cpp:(.text._ZN15CompletionComboC2EP7QWidget[_ZN15CompletionComboC5EP7QWidget]+0x86): undefined reference to `vtable for ComboBox'
CMakeFiles/cantata.dir/devices/albumdetailsdialog.cpp.o: In function `Ui_AlbumDetails::setupUi(QWidget*)':
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x177f): undefined reference to `vtable for ComboBox'
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x183c): undefined reference to `vtable for ComboBox'
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x1896): undefined reference to `vtable for ComboBox'
albumdetailsdialog.cpp:(.text._ZN15Ui_AlbumDetails7setupUiEP7QWidget[_ZN15Ui_AlbumDetails7setupUiEP7QWidget]+0x1914): undefined reference to `vtable for ComboBox'
support/libsupport.a(combobox.cpp.o):combobox.cpp:(.text+0x13): more undefined references to `vtable for ComboBox' follow
collect2: error: ld returned 1 exit status
CMakeFiles/cantata.dir/build.make:9827: recipe for target 'cantata' failed
make[2]: *** [cantata] Error 1
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eikehein** [comment]
This fixes it for me:

`--- a/support/combobox.h
+++ b/support/combobox.h
@@ -36,9 +36,7 @@ class ComboBox
     : public QComboBox
     #endif
 {
-    #if QT_VERSION >= 0x050000
     Q_OBJECT
-    #endif
 
 public:
     ComboBox(QWidget *p);`

Apparently something in the libsupport buildsystem is broken and QT_VERSION doesn't work properly (including QtGlobal explicitly didn't help either). It's a Qt 5 build FWIW.

**Comment by fonsocm** [comment]
Compiled with VLC option on in OpenSuSE Leap with Qt 5.6 and plasma 5.6.1 without problem and working. I installed from rpm built by me.

I used the fix of the previous post and this other fix from CDrummond:

if (Qt5_POSITION_INDEPENDENT_CODE)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
else(Qt5_POSITION_INDEPENDENT_CODE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
endif (Qt5_POSITION_INDEPENDENT_CODE)

Thanks all.

**Comment by eikehein** [comment]
^ I used that patch too, but it didn't do the trick by itself. I also had to manually add -fPIC to the CXXFLAGS on top of that, plus the C++ changes. Something in the Cantata build system is very wonky.
