### ISSUE TITLE
cantata 2 grid view of library flat album view possibilities regression

### ISSUE THREAD

**Issue by Martin-S-Weber** [CDrummond/cantata#790]
The following grid view was possible before cantata 2:

* show albums
* group by artist
* sort albums by year

The albums were sorted by artist first, then by year. For the screenshot sample below, that meant that all the animals as leaders albums were grouped together in the (flat) album grid view, then they were sorted by year (and then by album title?). So in the flat view, you would see, in the "publishing order" of that artist, albums A1_1 A1_2 A1_3 ... A1_x, A2_1 ... where _1 ... _x symbolizes the publish order (i.e., sort by publish year)

Now it's no longer possible to globally display albums sorted by artists first and year afterwards. Instead there's a way to show albums and sort these globally by a single option. What you end up by grouping by album is not the same as before. Now you can only sort explicitly by one more option. I.e., group by album = flat display of albums, that are then sorted by a single parameter. One parameter is year, another is artist. Sorting by artist now sorts the albums secondarily by the album title alphabetically (suppose that's your secondary index somewhere). So now the best I can achieve for flat album view is A1_a, A1_b, A1_c, ... A1_z , A2_a .. where a..z symbolizes the alphabetical sort.

Please bring the capabilities of the old album + artist views back.

Sample visual of the regression: These three animal as leaders albums have been released 2009, 2014, 2011 (in the order they're displayed). There is NO option to have these three display in the correct order (first grouped by artist, i.e. all animal as leaders together, then by album year, i.e., 2009, 2011, 2014). Either I get all the animal as leaders albums together and in alphabetical order or I get the year right but the albums are no longer grouped.

![lib-view-regression](https://cloud.githubusercontent.com/assets/13536379/12546261/0634d72c-c349-11e5-9a25-6a8187c29a7f.png)

Another sample: Ideally, I would like to view these albums flat next to each other, grouped by artist (obituary) and sorted by year of publication. 
![obitsort](https://cloud.githubusercontent.com/assets/13536379/12548067/26528cd8-c354-11e5-9874-b914b6885e7a.png)

One could alternatively say: could you please NOT collapse to artists if I say group my albums by artist? Or ressurrect album + artist view? Or offer an option to not collapse groups in group by but remain at a flat album grid display grouped by group and sorted by option?

**Comment by CDrummond** [comment]
Separate Artists and Albums view is *not* coming back. For 2.1, however, I can re-add the extra album sort options (the code is actually already there, just commented out)

**Comment by CDrummond** [comment]
If possible, please checkout git/master (which will be 2.1). I've re-added the sort options.

As to the separate views -  as I said, not going to happen. However, I may add an easier way to toggle Genre/Artist/Album grouping. Perhaps as a combo, or 3 buttons...

**Comment by Martin-S-Weber** [comment]
I've tested master as of now, the sort capabilities of the 'group by album' view are making me happy, thanks! Looking forward to 2.1 hitting the release press.
