### ISSUE TITLE
cantata 2 library view gives no quick genre selection

### ISSUE THREAD

**Issue by Martin-S-Weber** [CDrummond/cantata#791]
Where's the drop down genre filter selection disappeared to? It's been way more practical than breaking your library display / sorting temporarily for a genre search. I'm either blind or this is a usability regression.

**Comment by CDrummond** [comment]
Must admit, I thought the genre combo as not liked due to it being different from other music players. I've seen multiple complaints about it. 

I'll see about adding it back in for 2.1 (for Artist and Album groupings only)

**Comment by Martin-S-Weber** [comment]
In that case count my "complaint" for the lack of the genre selection as just one single complaint. 
I'm not particular about it, I just noticed a regression in capabilities of the software (i.e., quick genre filter access) and the (sparse, hum hom) release notes weren't documenting whether or not this was intentional. 
If you believe/feel that thing isn't worth it, don't re-add it. Let this ticket be a documentation of the intentional removal of the capability.

**Comment by CDrummond** [comment]
The ChangeLog is much more detailed. As to the 'release notes' - I just wrote a few of the changes, as I didn't want the whole changelog to be there.

Re-adding the genre combo would not be too much work. I was thinking of having it hidden until Ctrl-G pressed (or menu item selected)

**Comment by a-mair** [comment]
I miss the genre filter, too and it would be nice to get it back.
Maybe this could be improved?
It used to show a simple dropdown where you can select *one* genre. Changing this to a multi select box that allows extended filtering would be great. Each entry should have three states: unselected, enabled, disabled.
Why would this be useful?
Let's say you have tracks tagged with multiple genres like "Rock; Unplugged", "Rock; Live", "Pop; Live", "Rock", "Pop", "Rock; Speech"
If you want to listen to Rock music you would enable "Rock". If you don't want to include any tracks of interviews of any band member you would disable "Speech". The same if you don't want any "Unplugged" or "Live" tracks.
The next day you prefer to listen to any "Unplugged" music you simply select it, no matter if it's Rock or Pop or anything else. The same if you want to listen to "Live" music.

I hope you get the idea and find it as useful as I do.

**Comment by hotvic** [comment]
+1 for adding it back, I've stopped using cantata because of the genre combo.

And +1 for improvement something as @a-mair said.

**Comment by drtebi** [comment]
+1 for adding it back. Any feature that will make filtering easy...

**Comment by AlexT84** [comment]
TBH I find the actual genre tree-view 'a la amarok style very comfy.

**Comment by CDrummond** [comment]
Genre combo now shown if grouping by artist or album. Will be in 2.1
