### ISSUE TITLE
How to setup Network Proxy?

### ISSUE THREAD

**Issue by dufferzafar** [CDrummond/cantata#794]
How do I setup Manual Network Proxy configuration in Cantata?

I need to proxy the requests through localhost:8080

**Comment by CDrummond** [comment]
Use your DE's proxy settings, or build Cantata with its proxy config enabled. See the INSTALL text file for details.

(NOTE: I *think* the icon will be missing in the preference dialog for this - will fix)

**Comment by psamim** [comment]
Cantana does not use KDE proxy.
