### ISSUE TITLE
No icon in notification area

### ISSUE THREAD

**Issue by vgnmnky** [CDrummond/cantata#795]
Just updated to 2.0.0, Linux Mint 17.3 Xfce.  Now no icon in notification area, though I have that option selected in preferences.  Have since completely purged and reinstalled, but no luck.  It is listed as a known application in the Notification Area properties, 'hidden' option is not ticked, but nothing showing, regardless of icon theme.  There is an icon visible if I install an older version of Cantata.

**Comment by CDrummond** [comment]
Which build of Cantata? KDE4? Qt4? or Qt5?

**Comment by CDrummond** [comment]
...anyway, think it was a mistaken commit to **not** install pre-rendered versions of the icon. I've changed the 2.0 branch and master to install these.

Any chance you can ckeckout the 2.0 branch, and see if this is fixed?

**Comment by vgnmnky** [comment]
Apologies for not including that.  It's Qt5.

Unfortunately, I'm 100% new to Github, so I'm picking my way through what I need to do.  I'll report back when I get somewhere.  Thanks for responding.

**Comment by CDrummond** [comment]
No probs :-)  You should just need to:

1. git clone https://github.com/CDrummond/cantata.git
2. cd cantata
3. Follow the instructions in INSTALL

**Comment by CDrummond** [comment]
Any updates?

**Comment by CDrummond** [comment]
If you can't compile the code, you could try manually copying the icon files. To do this, download cantata16.png, cantata22.png

**Comment by CDrummond** [comment]
If you can't compile the code, you could try manually copying the icon files. To do this:

1. download cantata16.png, cantata22.png, cantata24.png, cantata32.png, cantata48.png, and cantata64.png from https://github.com/CDrummond/cantata/tree/master/icons

2. copy cantata16.png to /usr/share/icons/hicolor/16x16/apps/cantata.png - then the same for the rest (e.g. copy cantata32.png to /usr/share/icons/hicolor/32x32/apps/cantata.png 

3. Refresh your system's icon cache. Not 100% sure how to do that - perhaps a restart would suffice.

Does that resolve the issue? (as this is all my code change does)

**Comment by vgnmnky** [comment]
Thanks for this.  I did try building it, but was getting an undefined symbol error after trying to run it (after it appeared to compile successfully), and I've not had the chance to have another go. Sorry for not providing an update, I just felt it was likely to be something I was doing wrong and so wanted to start again.

I've now started with a clean slate, installed as normal, and then copied over the icons, rebuilt caches, etc.  Now I'm getting a gap where an icon should be (if I copy them directly to the theme I'm using, otherwise still nothing), that I can at least interact with, it's just that the icon itself isn't visible.  This could very well be something specific to my set-up.  I'll play with it more in the week, and try on my laptop in a different and more freshly installed distro.

Thanks again for your time.

**Comment by CDrummond** [comment]
AFAIK, all icon themes should derive (either directly, or via another theme) from hicolor. So, if the cantata icon is installed to 'hicolor', and the icon cache updated - then it should work. You did copy them to */usr/share/icons/hicolor/??x??/* and rename to *cantata.png* ?

Did the notification icon show with 1.5.2?

**Comment by vgnmnky** [comment]
Yes, I followed those instructions, and only messed around with some other ideas when that didn't work.  Also tried on a fresh install of Mint Xfce on my laptop, same issue.  But then installed Manjaro Xfce, and it's completely fine without any tweaking.  Odd!

**Comment by CDrummond** [comment]
Just installed Mint Xfce into a VM, build Cantata, and notification icon appears. So this is working.
