### ISSUE TITLE
similar artist in dynamic rules don't work?

### ISSUE THREAD

**Issue by ikarus13** [CDrummond/cantata#796]
Hi,
if i understand cantata can play in dynamic playlist similar artists.
There is a button to choice this, but it do  not works for me. Only selected artists where played, no artists which are similar. My sytem is Linux Mint 17.3 64-bit, the script /usr/bin/perl /usr/share/cantata/scripts/cantata-dynamic start is running.
My Cantata: Cantata 2.0.0
Do i misunderstood something?, is there a way to check out why it isn't working for me?
Sorry for my badly english,
ikarus

**Comment by CDrummond** [comment]
The helper script uses a last.fm API to get simialr artists - looks like this no longer works.

**Comment by ikarus13** [comment]
Sad to hear this :-(
There is no other service like last.fm available and usable? I think, this feature is very usefull.
Thanks for your answer, so i can stop searching the error in my configuration.
Many greetings,
ikarus

**Comment by CDrummond** [comment]
I'll look into using an alternative - it could be that the API has been renamed, or moved. I jsut did a quick check last night to confirm that it no longer works.

**Comment by ikarus13** [comment]
Hi,
pleasure to hear that you will try to fix it!!!!
Cantata is a very good peace of software and i like it very much, you make a realy good job!!!
ikarus

**Comment by CDrummond** [comment]
Should be fixed in the 2.0 and master branches - can you build from git?

**Comment by ikarus13** [comment]
Never done before, but i will try it.
Thanks,
ikarus

**Comment by ikarus13** [comment]
Hi,
had some problems with compiling, but got it!!!
Works fine now again.
Really great, thanks a lot!!!!!!
It is very usefull with voluminous, in parts unknown collections.
Find so some fine tracks i never heared before ;-)

**Comment by CDrummond** [comment]
Thanks for the confirmation. Glad its working :-:
