### ISSUE TITLE
Cantata 2 Library View gives no way to group by albums and sort albums by artist-year

### ISSUE THREAD

**Issue by duairc** [CDrummond/cantata#797]
This is how I like my library view to look and it was possible in Cantata 1.x. The closest you can get is to sort by artist, which makes it so that each within each artist, the albums are sorted alphabetically by their title. I think this should either be configurable, or else default to sorting by year. Thanks!

**Comment by CDrummond** [comment]
Please, check for duplicates before posting.

https://github.com/CDrummond/cantata/issues/790
