### ISSUE TITLE
libvlc

### ISSUE THREAD

**Issue by f1u77y** [CDrummond/cantata#798]
why is libvlc set as default for http stream playback? isn't it strange for graphical client to a player to put another player in deps? yes, it could be easily customized, but package maintainers in some distributions(b.e. arch) think that default dependencies from upstream are preferred

**Comment by CDrummond** [comment]
Because it worked better for me. Not a feature I use, but I was fed up of dealing with bug reports abut playing back MPD HTTP stream - so I just enabled the option by default.
