### ISSUE TITLE
Music folder setting for remote mpd server?

### ISSUE THREAD

**Issue by nemonein** [CDrummond/cantata#802]
First of all I thank you for your great work.

I'm using Ubuntu 14.04 for Cantata-qt(ppa:ubuntuhandbook1/cantata-qt) 1.5.2 and Volumio(on CubieTruck) for mpd server.

My music(album) covers are stored with music files, in Volumio machine.
Volumio's IP is 192.168.0.10, and playing is perfect.

Here's my question.
I don't know how to set the Music folder appropriately.

In the 'Cantata First Run' window, I could find, 'If your MPD instance is on a remote host, you my set this to a HTTP URL.', but I don't know how.
Can you tell me how I set the music folder?

> Volumio's IP : 192.168.0.10
> Volumio's Music Directory : /var/lib/mpd/music/

Thanks in advance!

**Comment by CDrummond** [comment]
You need to either:

a. have a HTTP server on the remote machine - then set Cantata's music folder to the HTTP address where the music is served. e.g. http://192.168.0.1/music

b. mount the remote server's music directory to your local linux system - then set Cantata's music folder to somewhere in the mount point

**Comment by nemonein** [comment]
I took the b. option, and it works.
Thanks!
