### ISSUE TITLE
Allow folders to be included/excluded in dynamic playlists.

### ISSUE THREAD

**Issue by melvinvermeeren** [CDrummond/cantata#803]
Besides the generic music tags, I also sort a lot of my music in directories on disk. Sometimes, I want to listen to music from a certain folder or exclude music from a certain folder.

Is it possible to add a field "Folder" or something similar to the dynamic rule configuration window? 

Currently, manually creating a playlist from the "Folders" panel works, but using it isn't as easy, especially if excluding only some subdirectories. This method also means you cannot use any other of the dynamic rules.

**Comment by CDrummond** [comment]
Well, AFAIK you cannot filter on folders, but you can can on files. So, it would be possible to use the 'non-exact' match to filter using partial paths. e.g. If you have 'Artist/Album/01 Track.mp3' you can 'search file "Artist/Album"'  and MPD will return the tracks of that album.

So, in answer to your question - yup, this could be done, and relatively easily.

**Comment by melvinvermeeren** [comment]
Great news, this will also give me some motivation to sort more music locally, some parts are *cough* quite cluttered right now.

Looking forward to the feature!

**Comment by CDrummond** [comment]
in git/master (for 2.1) now.

**Comment by melvinvermeeren** [comment]
Working perfectly, thanks a lot! :)
