### ISSUE TITLE
Allow selecting whole albums with dynamic playlists instead of individual songs.

### ISSUE THREAD

**Issue by melvinvermeeren** [CDrummond/cantata#804]
Not sure if this is possible to implement without a lot of work, but since it is a feature I would really appreciate I'll try anyway ;)

Currently, the dynamic playlist randomly selects tracks that match the specified criteria. Is it possible to add an checkbox to the main dynamic playlist configuration so that albums that match specified criteria are selected?

This way you can still have the extreme ease of use of the dynamic playlists, but hear the tracks of an album in their chronological order.

Not sure how track selection within an album would work. Example:
- 1. Some song
- 2. Another song
- 3. Some song (instrumental)
- 4. Special song

1 and 2 should be included.
If I happen to specify "exclude title=instrumental" track 3 should be excluded.
Song 4 should be included too if there is no rule to exclude it.

This way, random albums can be played with their tracks in chronological order. But inside the album, exclude rules should still take effect.

An album should be included if one of the songs match the criteria. If no other songs within that album match criteria it will effectively be queued as one track.

Thanks in forward.

**Comment by CDrummond** [comment]
Whilst that would technically be possible - its a **lot** of work, and the current cantata-dynamic script is not geared around playing albums. Sorry, but if you want this then you're gonna have to implement it yourself.

**Comment by melvinvermeeren** [comment]
Yeah I figured this may be the case. Maybe I'll get around to hacking the code a bit one day, but chances are slim to be honest.

Thanks for the quick reply, feel free to close this to remove some clutter from your list. Or keep it open for one day™, your choice. :)

**Comment by CDrummond** [comment]
If you are interested, Cantata uses a small-ish perl helper script - cantata-dynamic - to actually select and play songs.

**Comment by melvinvermeeren** [comment]
For future reference, probably the easiest way to implement this is:
- Script selects one track that matches criteria (what is does now), puts it in temp list.
- All other tracks from same album are checked.
- If matches are found, add them to temp list.
- Sort temp list chronologically.
- Add final temp list to actual queue.

**Comment by CDrummond** [comment]
...actually that *might* not be that hard to do. Will think about for 2.1

**Comment by CDrummond** [comment]
Started to look into this, and even did the GUI changes, but its not going to work.

Cantata gets **all** songs that match the filters, then randomly chooses from that. To make t work with albums would need re-architecting for this. Still possible, but a **lot** of work - more than I have time for.

However, MPD itself has no real concept of albums. it only knows about album titles. So, if you have 3 "Greatest Hits" by different artists, the tracks would all get merged. This is part of the reason the Cantata UI caches the MPD listing - so it can correctly group album tracks. The cantata-dynamic script does **not** use Cantata's cache (as the script can also be run on remote hosts).

So, closing for now. However, if you should feel like working on the perl cantata-dynamic script to fix these issues, then I'll gladly accept a pull request or patch.

**Comment by melvinvermeeren** [comment]
Thanks for your effort. If it's a big architectural thing like this it probably isn't worth doing it, at least for now.

If I have time and motivation I'll try hacking the script, but chances are slim to be honest.

Until next time. :)
