### ISSUE TITLE
Missing files in library

### ISSUE THREAD

**Issue by greenvorbisfan** [CDrummond/cantata#806]
Cantata (git/master, Qt4, Ubuntu 14.04.3 x64) does not recognize TAK and OFR (OptimFROG) files.

**Comment by CDrummond** [comment]
I assume these are audio file formats? In what way does Cantata not recognise them? The music listing comes from MPD, the files are not scanned (or played) by Cantata. I'm at a loss as to how it could ignore files...

**Comment by cspiegel** [comment]
Neither format is supported by mpd.

I've just about finished writing an OptimFROG plugin for mpd. If all goes well I plan on submitting a pull request this weekend.  If it's accepted, presumably the next release of mpd will have OFR support.

FFmpeg supports TAK, so all it'll take for mpd support is adding the .tak extension to the FFmpeg plugin. I tested this and was able to play TAK files just fine.  As long as I'm submitting pull requests, I can put in a request for this update, too.

Once/if mpd supports these formats, they'll show up in Cantata like any other supported format.
