### ISSUE TITLE
AppImage for Cantata

### ISSUE THREAD

**Issue by unruhschuh** [CDrummond/cantata#807]
Hi,

this is not an issue, but I couldn't find another way to contact you. I created an [AppImage](http://appimage.org) for Cantata 2.0.0 which should run on most Linux Distros without any further dependencies.

You can download the AppImage here: https://bintray.com/unruhschuh/AppImages/Cantata/view#files
The GitHub Project for the AppImage is here: https://github.com/unruhschuh/Cantata.AppImage

Please let me know what you think.

Tom

**Comment by CDrummond** [comment]
Thanks for the effort. Not sure its for me though. It does not use the system Qt, therefore uses its own theme. Also, the font-awesome icons appear not to work :(

**Comment by unruhschuh** [comment]
Yes, there are some issues I need to iron out. Bundling Qt and all other dependencies is the point of AppImages. They are meant for people, who want up to date apps without updating the whole system all the time. Also Cantata 2 is not in the repositories yet, and not everyone is willing or able to compile it themselves. Thanks for Cantata btw. it's the best MPD client I could find.

**Comment by CDrummond** [comment]
Even if not using the system's Qt libraries, an app should still use at least the users style (if its an inbuilt Qt one - such as QGtkStyle) and font settings. Neither of these are currently respected.

Don't mean to sound negative - the were just the things that irked me a little :-)

**Comment by unruhschuh** [comment]
I understand. The number one priority for me is to make it run on as many LInux Distributions as possible, including very old ones like CentOS 6.7 and Ubuntu 12.04. QGtkStyle is not really inbuilt, as it uses the systems Gtk+ libraries to render the widgets. This leads to problems on the different systems I'm testing on, so I turned it off for now. This is a work in progress and your feedback is very much appreciated.

**Comment by unruhschuh** [comment]
I put up a new Version of the AppImage that includes the icons.

**Comment by CDrummond** [comment]
**Wow** looking **much** better! Any chance you could get it to read the user's font settings? The font looks a bit small here.

Also, if you'd like, I can add a link the the app image the releases tab.

**Comment by unruhschuh** [comment]
I will look into the font issue.
Sure I'd like you to put a link in the releases tab.
I couldn't reproduce the bug. Could you send a screenshot? Here is the AppImage using commit c8e9843. Let me know whether the problem is solved.
https://www.dropbox.com/s/azsr7v5w4ops8k0/Cantata-2.0.0-c8e9843-x86_64.AppImage?dl=0

**Comment by CDrummond** [comment]
Thanks for the new build - and the Cantata issue is fixed. It only occurred when run under Unity.

**Comment by unruhschuh** [comment]
I just replaced the AppImage on bintray.com with the new build. It is still called 2.0.0, even though it doesn't strictly derive from the 2.0.0 release, but I guess that's fine.

**Comment by CDrummond** [comment]
I'm going to close this - as it's not an issue. I have released Cantata 2.0.1 - which contains quite a few bug fixes - if you want to make a 2.0.1 appimage, then send me a link and I'll add it to the release page. My email address is in the AUTHORS file.

Once again, thanks for taking the time to do this.

**Comment by Lvaskz** [comment]
Hey there, no more appimage from cantata? I saw a old appimage version but the new version, they do not even exist. Some plan to provide one, or any other package as flatpack, snap?

**Comment by rn2208** [comment]
Flatpak this is not a bad idea.
