### ISSUE TITLE
Source file not aviable

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#808]
When coping a track that's inside a cue file Cantata asks if its not available.
Cantata should handle this case.
![screenshot_20160211_213203](https://cloud.githubusercontent.com/assets/1747359/12989787/256f20e0-d107-11e5-9c71-e20813734785.png)

**Comment by CDrummond** [comment]
Where are you copying from / to?

**Comment by CDrummond** [comment]
Well it does handle it - gives you the error :-) But I get your point.

**Comment by CDrummond** [comment]
'Fixed' now. When selecting songs to copy to device, cue tracks are ignored. Probably not the best solution, disabling the action when there are cue tracks in the selection would be better - but this would mean checking all files. But, good enough for me - and I don't actually have any cue files.

**Comment by Thaodan** [comment]
Would it be possible to parse the cue file and push the tracks as viewed in the library to the target? 

Am 11. Februar 2016 23:51:49 MEZ, schrieb CraigD <notifications@github.com>:
>Closed #808.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/CDrummond/cantata/issues/808#event-547869692

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Thaodan** [comment]
From my mpd library to an USB drive in this case or to an mtp connected phone however this won't worked cause of an libmtp related issue. 

Am 11. Februar 2016 23:18:46 MEZ, schrieb CraigD <notifications@github.com>:
>Where are you copying from / to?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/CDrummond/cantata/issues/808#issuecomment-183082411

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by CDrummond** [comment]
Nope, not if you have cantata parse the cue file and create separate tracks. At this point Cantata no longer keeps a reference to the source file.

I'm sure this *could* be worked around. However, I have not cue files (never seen the need for them, MPD does gapless), so it's not something I'm going to spend time on. patches / pull-requests welcome.

**Comment by Thaodan** [comment]
So reopen this issue at least? In my opuion just hiddding the cueed tracks when converting is not good so the user gets confused. Better tell the user that we don't convert cued tracks.
