### ISSUE TITLE
Add an ability to choose color of icons

### ISSUE THREAD

**Issue by phantom-code** [CDrummond/cantata#811]
I'm using Plasma 5 theme called [Papirus](http://kanorus.deviantart.com/art/Papirus-Plasma-5-Theme-539042938) and its gray icons are very inconsistent with black icons in the Cantata. Can you add an ability to choose a color for icons (if I understand it correct, you use just a special font for the icons)?

**Comment by CDrummond** [comment]
Icon colours should be coming from the font colour. However, if this is too dark, or too light, then Cantata will use other values. The reason for this is that if the font is black, the sidebar icons looked too harsh.

I'll investigate more later.

**Comment by CDrummond** [comment]
Icon colours are taken from font colour - just tried with a green font colour.

**Comment by phantom-code** [comment]
So you're suggesting changing the font color for all applications just to change the icons' color in cantata? Don't you find it strange? :-)
Anyway, please don't take this comment as offensive, I respect your decision and appreciate your great work. Thanks!

**Comment by CDrummond** [comment]
No, I expect Cantata's icons to follow the font colour - that's how it is designed.
