### ISSUE TITLE
Add rating filter to library view 

### ISSUE THREAD

**Issue by Tamriel** [CDrummond/cantata#814]
![rating_filter](https://cloud.githubusercontent.com/assets/5037153/13477255/de387602-e0cb-11e5-8fe3-ebd5e25186ff.png)

**Comment by CDrummond** [comment]
Not going to happen, sorry. Rating are stored in MPD's sticker DB - and to access these for all tracks would take too long.

**Comment by Tamriel** [comment]
I guess the performace would be ok, if the ratings were stored in the ID3 tag.

**Comment by Tamriel** [comment]
Other idea to improve performance: Calculate the average rating of each album. Show only albums above the specified threshold.
