### ISSUE TITLE
Current track accentuation

### ISSUE THREAD

**Issue by Tamriel** [CDrummond/cantata#815]
The current track is accentuated by a gradient background. Gradient backgrounds often create a 3D effect. I think this breaks with the rest of the UI, which has a flat design. How does a single-colored background look like?
![current](https://cloud.githubusercontent.com/assets/5037153/13480206/8dfe5970-e0dc-11e5-9ba4-2f3e659ed69f.png)

**Comment by CDrummond** [comment]
Well the rest of the UI is up to the theme ;-) But  get your point... I'll change for 2.1

**Comment by melvinvermeeren** [comment]
@CDrummond Do you mind making an option to use the old style?

With breeze dark + album cover as background image the blue glow looks really good in my opinion. It creates the illusion that the playlist truly lies on top of the dimmed background image.

Thanks!

**Comment by CDrummond** [comment]
Flat highlight in master (for 2.1) now. 

Sorry, but I can't add an option for every little thing.

**Comment by melvinvermeeren** [comment]
@CDrummond I was afraid it would look odd, but you did a stellar job on it! Looks great with Breeze Dark. :)
