### ISSUE TITLE
Build failure on Mageia Cauldron with latest 2.0.0 release

### ISSUE THREAD

**Issue by david-geiger** [CDrummond/cantata#816]
Hi,

I can't no more compile cantata 2.0.0, I get an compile error:

In file included from /usr/lib64/qt5/include/QtCore/qnamespace.h:37:0,
                 from /usr/lib64/qt5/include/QtCore/qobjectdefs.h:41,
                 from /usr/lib64/qt5/include/QtCore/qobject.h:40,
                 from /usr/lib64/qt5/include/QtCore/qthread.h:37,
                 from /usr/lib64/qt5/include/QtCore/QThread:1,
                 from /home/pterjan/rpmbuild/BUILD/cantata-2.0.0/build/support/../../support/thread.h:27,
                 from /home/pterjan/rpmbuild/BUILD/cantata-2.0.0/build/support/moc_thread.cpp:9:
/usr/lib64/qt5/include/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
support/CMakeFiles/support-core.dir/build.make:69: recipe for target 'support/CMakeFiles/support-core.dir/moc_thread.cpp.o' failed
make[2]: *** [support/CMakeFiles/support-core.dir/moc_thread.cpp.o] Error 1
make[2]: Leaving directory '/home/pterjan/rpmbuild/BUILD/cantata-2.0.0/build'
CMakeFiles/Makefile2:645: recipe for target 'support/CMakeFiles/support-core.dir/all' failed
make[1]: *** [support/CMakeFiles/support-core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Compilation is against gcc 5.3.1 and Qt5 5.6.0_rc

Regards,
David

**Comment by david-geiger** [comment]
Any comment?? :(

**Comment by CDrummond** [comment]
Have you tried making the changes mentioned above?

I don't use Mageia, and Cantata builds just fine. When I get some time to spend on this I will make the changes.

**Comment by david-geiger** [comment]
I just tried to compile adding <export CXXFLAGS="%{optflags} -fPIC" CFLAGS="%{optflags} -fPIC"> in spec file but same error.

Also tried another way adding <-DCMAKE_CXX_FLAGS="-fPIC"> as a cmake option and always this error.

**Comment by david-geiger** [comment]
Well! after some research I found a patch from Fedora:

<
diff -up cantata-2.0.0/CMakeLists.txt.CMAKE_CXX_FLAGS cantata-2.0.0/CMakeLists.txt
--- cantata-2.0.0/CMakeLists.txt.CMAKE_CXX_FLAGS	2016-01-24 09:05:16.000000000 -0600
+++ cantata-2.0.0/CMakeLists.txt	2016-01-25 10:43:48.806603515 -0600
@@ -279,7 +279,7 @@ if (ENABLE_QT5)
     set(QTINCLUDES ${Qt5Widgets_INCLUDE_DIRS} ${Qt5Network_INCLUDE_DIRS} ${Qt5Xml_INCLUDE_DIRS} ${Qt5Core_INCLUDE_DIRS} ${Qt5Concurrent_INCLUDE_DIRS}
                    ${Qt5Svg_INCLUDE_DIRS} ${Qt5Sql_INCLUDE_DIRS})
     add_definitions(${Qt5Widgets_DEFINITIONS} ${Qt5Network_DEFINITIONS} ${Qt5Xml_DEFINITIONS} ${Qt5Concurrent_DEFINITIONS} ${Qt5Svg_DEFINITIONS} ${Qt5Sql_DEFINITIONS})
"-    set(CMAKE_CXX_FLAGS "${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
"+   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
     if (NOT ENABLE_UBUNTU AND NOT APPLE AND NOT WIN32)
         # Does Ubuntu/Touch version need DBus?
         find_package(Qt5DBus)
>

Applying this patch + adding  " -DCMAKE_CXX_FLAGS='-fPIC' " as a cmake option fixes build.

**Comment by david-geiger** [comment]
http://pkgs.fedoraproject.org/cgit/rpms/cantata.git/plain/cantata-2.0.0-CMAKE_CXX_FLAGS.patch

**Comment by CDrummond** [comment]
Thanks for this. I'll add it to 2.0.1 when I get some spare time.

**Comment by CDrummond** [comment]
The above change was already made on 8th Feb - but this was after the 2.0 release. Still, wish packagers would send patches upstream!
