### ISSUE TITLE
Show rating in browsing view

### ISSUE THREAD

**Issue by rinne13** [CDrummond/cantata#817]
When browsing albums or artists and viewing the list of songs from the album/artist it would be nice to show the rating of the siongs. This way you can only add the (high) rated songs from that particular artists/album to  your playlist.

**Comment by CDrummond** [comment]
**Please** look for duplicates **before** creating issues... 

https://github.com/CDrummond/cantata/issues/814

**Comment by rinne13** [comment]
This feature does not require loading of all track-ratings in the library. Only of the ones that are shown in the current view need to be loaded.

Isn't there a possibility to load the ratings to cache? And load from there?

**Comment by CDrummond** [comment]
Reading ratings is **SLOW** Adding these to Cantata's cache would **drastically** slow down its population...

**Comment by rinne13** [comment]
Maybe it totaly different, but ratings are shown in the search pane. This is not slow at all.
