### ISSUE TITLE
Please bring back the sorting of folders

### ISSUE THREAD

**Issue by benjamindaines** [CDrummond/cantata#818]
Current implementation totally breaks the way I use Cantata & MPD.  I dump all new music into a folder, listen to what I've downloaded, and over time (couple weeks, maybe a month, depends.  Meaning that the folder grows over time) decide what I want to keep.  I the delete what I don't want and have Canata sort the rest, neatly into my library.  

Now I have to open each subfolder, manually select each track, then sort.  If I have a huge list selected and I accidentally forget to hold ctl when I click, I have to start all over.  Very frustrating.  

Even if I have to open each folder due to cantata no longer preloading folders, and then be able to run the organize function on the top directory, that would be fine.  It's truly awful the way it is.  

Thanks.

**Comment by CDrummond** [comment]
Folder list order comes from MPD. Sorry you think its **awful** - guess you should spend **your** time fixing it then. Works for me.
