### ISSUE TITLE
Missing sorting by tracknumber

### ISSUE THREAD

**Issue by quarckster** [CDrummond/cantata#819]
Many people like to listen whole albums and in this case sorting by tracknumber is important.

**Comment by CDrummond** [comment]
Missing where? In the library view tracks are sorted by number. If you mean in the playqueue then sort by album - this will sub-sort by track number. Sorting by track number alone makes **no** sense. e.g.2 albums in playqueue:

Original order:

1.     Album B Track 2
2.     Album A Track 1
3.     Album A Track 3
4.     Album B Track 1
5.     Album A Track 1

sort by album =

1.     Album A Track 1
2.     Album A Track 2
3.     Album A Track 3
4.     Album B Track 1
5.     Album B Track 2

Sort by track number would produce:

1.     Album A Track 1
2.     Album B Track 1
3.     Album A Track 2
4.     Album B Track 2
5.     Album A Track 3


I only ever listen to whole albums. Adding albums adds them in track order.

**Comment by quarckster** [comment]
Thanks for the answer. Yes, I mean the playqueue. It's unclear that sorting by album does sub-sort by track number. I think the issue can be closed.
