### ISSUE TITLE
mpv engine?

### ISSUE THREAD

**Issue by AcarBurak** [CDrummond/cantata#820]
Hi,

Please excuse me if it's absurd to ask, since you may heavily rely on MPD's capabilities, but MPV as an alternative (or default !!) engine would be very fine.

MPD is too prickly, after some system update or another it refuses to work. I know this new tokenizer issue will be solved too but...

MPD's advantage (at least for me) over others was a working gapless playback mechanism, but now MPV too has it. Besides, the majority of users wouldn't need a daemon-client scheme but love a hassle free and reliable player.

**Comment by CDrummond** [comment]
The **whole** point of Cantata is to be an **MPD** client. Cantata does not feature *engines* Many users, myself included, use MPD on a headless system (e.g. raspberry pi), and use a GUI client to control this. That is why *I* started with Cantata - to control an *always on* media player. mpv does not fit with this.
