### ISSUE TITLE
No Search in Folders View since 1.9.x or 2.x

### ISSUE THREAD

**Issue by felix-oertel** [CDrummond/cantata#821]
Hi,
thanks a lot for your work. I´ve a small but important problem since version 1.9.x. I´m on Manjaro Linux with KDE 5/Plasma. The Search-Operation has been included inline in the Folders view in former versions. This function is now gone since 1.9.x. Is it a bug or a feature? :)
Ahoi!

**Comment by CDrummond** [comment]
Folders view is dynamically loaded - so the old search cannot work. Activating the search will take you to the search view - this uses MPD to search.

**Comment by felix-oertel** [comment]
Thanks a lot!




Von:
CraigD
Gesendet:
�14.�03.�2016 13:08
An:
CDrummond/cantata
Cc:
Felix Oertel
Betreff:
Re: [cantata] No Search in Folders View since 1.9.x or 2.x (#821)



Folders view is dynamically loaded - so the old search cannot work. Activating the search will take you to the search view - this uses MPD to search.
�
Reply to this email directly or 
view it on GitHub.
