### ISSUE TITLE
Cantata won't play audio cd / does not show any device (Geräte)

### ISSUE THREAD

**Issue by maguggi** [CDrummond/cantata#823]
I installed cantata 2.0 on a Laptop running linux mint17.2. Cantata plays music but won't show any device, neither before or after inserting an audio cd into the drive. Even if I open an audio cd via file manager ,which offers me to open the tracks with cantata, cantata won't play any track or show any track or device.

Are there any known problems?

Thanks in advance 

maguggi

**Comment by CDrummond** [comment]
AudioCDs show up fine for me on Ubuntu 15:10 - but there was an issue with playback, this is now fixed (in master an 2.0 branch)

**Comment by CDrummond** [comment]
AudioCDs working for me.

**Comment by maguggi** [comment]
Hi Craig 

Sorry for being late. 

If i put an audi-cd in, the following window pops up: 

Next, if i say ok, Cantata starts: 

No audio CD is provided in "Geräte". If I connect for example an
audio-stick it shows up in "Geräte". 

Am 2016-03-25 22:05, schrieb CraigD: 

> Closed #823 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [2]

  

Links:
------
[1] https://github.com/CDrummond/cantata/issues/823
[2] https://github.com/CDrummond/cantata/issues/823#event-603501646

**Comment by maguggi** [comment]
Tied now to install full:

`cmake..
-- Set build type to Release
-- Could NOT find Taglib (missing:  TAGLIB_INCLUDES TAGLIB_LIBRARIES) 
-- Found LibVLC include-dir path: /usr/include
-- Found LibVLC library path:/usr/lib/libvlc.so
-- Found LibVLCcore library path:/usr/lib/libvlccore.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Building Qt5 version

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * Qt5DBus - DBus support.
   * libVLC - MPD HTTP stream playback.

-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
-----------------------------------------------------------------------------
   * TagLib  <http://taglib.github.io/>
     Tag editor, file organiser, etc.

-----------------------------------------------------------------------------

-----------------------------------------------------------------------------
-- The following STANDARD options have been DISABLED.
-----------------------------------------------------------------------------
    * Devices Tab - Media device support (UMS, MTP, AudioCD).

-- Configuring done
-- Generating done
-- Build files have been written to: /home/daria/Downloads/cantata-master/build`

Do you know, why the Media device support has been disabled?

**Comment by CDrummond** [comment]
You need to have taglib installed. 

> -- Could NOT find Taglib (missing:  TAGLIB_INCLUDES TAGLIB_LIBRARIES)
