### ISSUE TITLE
How can I run Custom Actions?

### ISSUE THREAD

**Issue by nemonein** [CDrummond/cantata#824]
I'm running Cantata 2.0.0 on Ubuntu 16.04.

I have added a Name and Command in Custom Actions, and I could find Custom Actions menu appears on the Library.
However, even I click the one I created, nothing happens.
I added a command like this. Actually I want to run some scripts with the music file's path & title.
```
Name : Open Nautilus
Command : /usr/bin/nautilus %d
```
I also tried to run Cantata with the debug logging. I tried with various mode (2048, 16384, 524288 etc), but there were no message( ~/.cache/cantata/cantata.log) for Custom Actions.
Did I do something wrong?

**Comment by CDrummond** [comment]
You need to ensure you have the correct MPD music path set in the settings. Cantata uses that, plus the sub-path sent from MPD, to determine the full path.

Just checked, and actions are working.

**Comment by nemonein** [comment]
Thank you for your answer, but I have a question.

I think it only works when mpd is local. When mpd is on the server side, actions don't run at all.
Hm..
I wish I could run actions even if mpd is running on other machines.
![cantata-info](https://cloud.githubusercontent.com/assets/5688288/14057598/01fcdcac-f348-11e5-85b9-4d16cf71c1c0.png)
For instance,
I want to do something with the info that Canata give. On the screen shot, 'Main_Collection/Jazz/Billie Holiday/1958 - Lady in Satin/01 - I'm a Fool to Want You.mp3' is the one that I need to do with.

Can I get this info when and only mpd is local?

**Comment by CDrummond** [comment]
Cantata needs to be able to access the files. Therefore, you need to have your remote filesystem mounted on your local machine - with Cantata's music folder set to the correct location.

What actions would you want to run if Cantata cannot access the files?
