### ISSUE TITLE
cantata-2.0.0 ignores MPD socket specified in config.

### ISSUE THREAD

**Issue by angryvincent** [CDrummond/cantata#825]
i have MPD set to run on unix socket rather than TCP/IP port. In .bashrc MPD socket is set to:
export MPD_HOST=/home/oleg/mpd/socket
I run it as my user. When i run mpd, by `mpd` i see correct socket used
netstat -lx | grep mpd
unix  2      [ ACC ]     STREAM     LISTENING     304557   /home/oleg/mpd/socket

Now, i have cantata config in .config/cantata/cantata.conf and set under [Connection]:

[Connection--]
coverName=
dir=/home/oleg/music
host=/home/oleg/mpd/socket
passwd=
port=
Starting cantata reveals that it using another independent socket in /home/oleg/.local/share/cantata/mpd/socket

netstat -lx | grep mpd

unix  2      [ ACC ]     STREAM     LISTENING     304557   /home/oleg/mpd/socket
unix  2      [ ACC ]     STREAM     LISTENING     308579   /home/oleg/.local/share/cantata/mpd/socket

Closing cantata, leaves running PID. which is still connected to /home/oleg/.local/share/cantata/mpd/socket, which is only cleaned after killing mpd instance. 
if is restart mpd and use for example ncmpc as client (and have it opened) i see only correct mpd socket i set in .bashrc. Quitting client, leaves working mpd instance, as expected, without interrupting socket and playback.

**Comment by angryvincent** [comment]
`bind_to_address "/home/oleg/mpd/socket"

audio_output {
        type                    "alsa"
        name                    "Intel HD"
        device                  "hw:0,0"
}

db_file            "~/mpd/database"
log_file           "~/mpd/log"
music_directory    "~/music"
playlist_directory "~/mpd/playlists"
pid_file           "~/mpd/pid"
state_file         "~/mpd/state"
sticker_file       "~/mpd/sticker.sql"`

my .mpdconf

**Comment by CDrummond** [comment]
If cantata is using /home/oleg/.local/share/cantata/mpd/socket the you are using Cantata's **Basic / Personal** mode. There is some text detailing how this works in the initial wizard, and in the prompt when adding a new collection in the setting dialog.

Please read the text before selecting an option

**Comment by angryvincent** [comment]
i'm seriously against closing this. If i edit cantata config and it still ignoring my socket specified it's a bug. If i need to change some modes, this has to be specified somewhere in man pages or else.

**Comment by CDrummond** [comment]
Cantata does not use your MPD conf file in personal/basic mode - in this mode it **ONLY** uses its locally generated and simple config.

What you want is to add standard Collection to Cantata, and put /home/oleg/mpd/socket as the server address.

**Comment by angryvincent** [comment]
ok, make sense.
