### ISSUE TITLE
trying to restore ratings from a backup file

### ISSUE THREAD

**Issue by labatts** [CDrummond/cantata#829]
I manually backup all my files, so that I can simply drag and drop them on a new install.  So, with that in mind, I have cantata successfully running (ratings and all) on my laptop.  I used the backup file from my laptop (the files are stored on an external hd) to make cantata work on my new desktop.  Everything was transferred **except for the ratings**.  

I have read that the ratings are stored in the mpd sticker db.  I assume that this is the **me/.local/share/cantata/mpd/sticker.sql **file?  If so, this is part of what I transferred over.  I might have made a mistake by not simply transferring the whole home directory over in the first place (i had my reasons), so perhaps there is another file somewhere that needs to be linked? 

I did also, btw, copy over the config file in the .config folder.

Anyway, any help is appreciated.

**Comment by CDrummond** [comment]
Ratings are stored in MPD's sticker file. Which file this is depends upon which MPD instance you were connected to. The system one is probably /var/lib/mpd/sticker.sql 

~/.local/share/cantata/mpd/sticker.sql is only relevant if you were using Cantata's Basic/Personal collection mode - where cantata starts, and controls, a minimal local MPD instance.

**Comment by labatts** [comment]
Okay, thank you.  Yeah, I am just using the personal collection mode.  So, I copied over the correct file then.  =/ .  Any ideas on why the ratings did not transfer?

**Comment by labatts** [comment]
Uh, okay, I guess I'll mark this as closed.  I just checked cantata and all the ratings are now there.  Perhaps it takes a while for them to register in the program?  Anyway, thanks for all the hard work.  It is a wonderful program.
