### ISSUE TITLE
Scroll amount in library view

### ISSUE THREAD

**Issue by cassava** [CDrummond/cantata#830]
When viewing the library in *Grid* mode (which then shows each artist or album as a thumbnail), scrolling moves 3 lines per tick. As the scrolling is not smooth, I find that moving 3 whole lines every tick very disorienting. Would it make sense to reduce this to 1 or maybe make it configurable?

**Comment by CDrummond** [comment]
Views are set to 'scroll per pixel' - and using the touchpad on my laptop, this is how it works. Dragging the scrollbar is not as smooth though - but this proportional to the size of the scrollbar. If it is small, then its jerkier - as a 1 pixel move is a higher percentage of the view.

**Comment by cassava** [comment]
So it's the setting on my scroll wheel then. Thanks.

**Comment by MageJohn** [comment]
This is still an issue for me. It's true it's smooth when I use the touchpad or when dragging the scrollbar, but when using the scrollwheel of my mouse it jumps about three items down. Maybe it's possible to set the scroll step?
