### ISSUE TITLE
Rating does not update for songs without rating

### ISSUE THREAD

**Issue by cassava** [CDrummond/cantata#831]
When a song plays that does not have a rating, the rating in the now playing widget (at the very top) retains the last set rating. So if I have a song list:

```
A  ★★★★
B
C
```

Then after `A` has finished playing normally, `B` will show with 4 stars. When I skip from `A`, then the rating is reset. As far as I can tell, C then has a reset rating.

So what I see will be this:

```
A  ★★★★
B  ★★★★
C
```

I am on latest master commit 491474c.

**Comment by cassava** [comment]
Actually, I'm seeing that C would also have 4 stars.

**Comment by CDrummond** [comment]
Can't see this exact issue - just tried with:

a **
b
c **

And it did clear between a anb b. However, I also noticed that its not always showing for a - so there is some issue with showing ratings in the toolbar.

**Comment by CDrummond** [comment]
The issue that I could see now appears to be fixed. Can you checkout either the master, or 2.0, branch and confirm?

**Comment by cassava** [comment]
Will do.

**Comment by cassava** [comment]
Ok, it seems to be fixed. Thanks!
