### ISSUE TITLE
Notifications not showing up

### ISSUE THREAD

**Issue by ms6676749** [CDrummond/cantata#832]
OS: Arch Linux
Version: git Qt5 build off of commit 491474c
Notification deps installed: knotifications, knotifyconfig, libevent, libnotify, lxqt-notificationd-git

I have all of the options on Interface Settings > External checked and the "On Start-up" subcategory I selected "Restore previous state".  However, notifications are not being shown upon track change.  For changing tracks while cantata is minimized, I have mpc set to shortcut keys.  This arrangement with respect to the current issue worked well before.  

The only time cantata's notification shows up is when I use lxqt's notification configuration.  There, when I change the window position of the notification window, it shows a sample notification window.  While this sample window is up, cantata is able to display its notification window upon track change.  However, once this sample notification window goes away, cantata's notification window no longer displays.

The reason I came here first, rather than lxqt's upstream, is that other apps such as konversation appear to pass their notifications through whichever notification subsystem they use to lxqt's notification daemon just fine.

Are there any debug values I can use that may provide you helpful information?

Thanks!

**Comment by CDrummond** [comment]
No idea what 'lxqts notification configuration' is. Cantata uses the freedesktop.org notification dbus spec. Just tried under Unity - minimised Cantata to system try, and used mpc to change tracks. Notifications were shown.

**Comment by ms6676749** [comment]
Is there any debug value that would allow me to see d-bus messages passed by cantata?

**Comment by CDrummond** [comment]
You can use [dbus-monitor](https://dbus.freedesktop.org/doc/dbus-monitor.1.html) - then you should see output such as:

```
method call time=1460276782.905383 sender=:1.130 -> destination=org.freedesktop.Notifications serial=83 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "cantata"
   uint32 0
   string "cantata"
   string "Now playing"
   string "The Angel And The Gambler by Iron Maiden on Virtual XI (1998) - 9:53"
....

```

**Comment by ms6676749** [comment]
Hmmm, I'm getting a similar output but no notification window:
```
method call time=1460419919.069102 sender=:1.71 -> destination=org.freedesktop.Notifications serial=109 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "cantata"
   uint32 0
   string "cantata"
   string "Now playing"
   string "10/3/79 by SIANspheric on Else (1999) - 11:46"
array [
   ]
   array [
      dict entry(
         string "image_data"
         variant             struct {
               int32 128
               int32 128
               int32 512
               boolean true
               int32 8
               int32 4
               array of bytes [
                  fe fe fc ff fe 
##[~3500 LINES]##
                  f4 f4 f2 ff f4 f4 f2 ff f3 f3 f1 ff f0 f0 ef ff
               ]
            }
      )
   ]
   int32 5000
method return time=1460419919.085646 sender=:1.55 -> destination=:1.71 serial=20 reply_serial=109
   uint32 5
signal time=1460419924.012753 sender=:1.55 -> destination=(null destination) serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 5
   uint32 1
```
Is there's anything strange here cantata-related?  If you answer no, then I'll open a ticket with lxqt.

**Comment by CDrummond** [comment]
To be honest, looks ok to me - but I'm no expert. I'm just calling the dbus API, and as I said its working fine under Unity.

**Comment by ms6676749** [comment]
I think it is either an upstream issue or that the packager missed a dependency.  A simple $notify-send 'foo' reproduces what I see in Cantata.  Thanks for pointing out dbus-monitor to me.  Please mark this as invalid.
