### ISSUE TITLE
Dark themes not applied properly

### ISSUE THREAD

**Issue by aouelete** [CDrummond/cantata#833]
Not sure if this is an issue for cantata, but it looks like it only affects cantata.
When using a dark theme, the top bar is dark text and buttons on a dark background, which clearly is not right. 
Here's a screenshot:
![screenshot_20160411_173119](https://cloud.githubusercontent.com/assets/12178067/14444491/dcfef72c-0013-11e6-9d07-2b3c7b568a40.png)

**Comment by CDrummond** [comment]
99.999% sure this is a Cantata issue. I don't have plasma5 installed. How did you get the dark theme? Are all apps dark, or is it per application? Cantata should be using the font colour to colour the icons.

**Comment by aouelete** [comment]
The theme is breeze-dark, and all other qt applications look right.
The screenshot is after I restarted cantata after changing the theme.

**Comment by CDrummond** [comment]
Hmmm... Odd. I've just compiled both a Qt5 and Qt4 verison under Kubuntu 15.10  - and for both of these the icons are correctly coloured - i.e. I see 'white' button icons with breeze-dark.

Cantata gets the monochrome icon colours from the themes text colour scheme.

Which version of Cantata?
Where did you get Cantata? From a repo, or self built?
What OS and version are you using? (e.g. Kubuntu 15.10, etc)
Which version of Qt (4, or 5 and release - e.g. Qt5.4)
What widget theme are you using?
Which desktop? (I assume plasma5 - but need to be sure)

**Comment by aouelete** [comment]
I'm using Arch Linux with KDE and Qt 5.6. I installed the latest cantata git version from the AUR, so it should be fully up to date. The widget version is also breeze.
I'm guessing Kubuntu has older packages, could this be the problem?

**Comment by CDrummond** [comment]
The only version differences will by KDE and Qt. Not sure why this should cause an issue. Note that Cantata if built with Qt5 is **NOT** a KDE application.

Looking at your screenshot - you can also see that the track info text is dark on a dark background. he icons will have the same colour as that text. This should all be set by the Qt palette - an is for me.

What about other pure Qt5 applications? i.e. not KDE apps. VLC? (think that's Qt5)

**Comment by aouelete** [comment]
I haven't noticed anything weird with any other application.
Here's what VLC looks like
![screenshot_20160413_114559](https://cloud.githubusercontent.com/assets/12178067/14499970/301d4e58-016e-11e6-92b4-97b5cb6ec76e.png)

**Comment by CDrummond** [comment]
Well, I have no idea what is wrong on your system. As stated, even the text colour is wrong - and this is set from the Qt palette.

**Comment by aouelete** [comment]
Hmm, weird. Well, thanks for your help, maybe I'll figure something out.

**Comment by CDrummond** [comment]
Just to be sure. Cantata is built as a Qt5 app, not KDE4? And VLC in your screenshot is using Qt5 not Qt4 ?

I did download the arch iso to install in VBox - but the install is way to convoluted!

**Comment by aouelete** [comment]
Oh wait, I just realized that VLC is built with qt4 on Arch. Cantata is definitely built as a qt5 app. 

If you want to try installing Arch, it might be better to use Antergos, I don't think there should be any difference, but the install process is much easier.

**Comment by CDrummond** [comment]
The please try with a pure Qt5 app.

**Comment by aouelete** [comment]
I still haven't been able to reproduce this with any other qt5 app. 
Also, just to clarify, this issue only occurs with the top bar (playback buttons and track title) of cantata, everything else has the right colors.

**Comment by CDrummond** [comment]
? Is the rest of the UI dark as well?

**Comment by aouelete** [comment]
Sorry, I should have made it more clear in the first post. The dark text on a dark background is only present in the top bar, the rest of the UI is fine. 

Here's a better picture:

![screenshot_20160419_112949](https://cloud.githubusercontent.com/assets/12178067/14645058/3baa02ee-0622-11e6-8f55-ef7bcb97cbd3.png)

**Comment by CDrummond** [comment]
What widget style is this? It does not look like breeze - as it (AFAIK) does not have the '+' to expand tree items, but has '>' instead.

**Comment by aouelete** [comment]
Wow! I just ran `cantata -style breeze` and the issue was fixed.

Do you have any idea why cantata would not be using the breeze style normally?

**Comment by CDrummond** [comment]
Nope, its probably A Qt5 issue - hence asking you to try another pure-Qt5 (i.e. not KDE5) app.

**Comment by BethAr** [comment]
I get the same thing on Manjaro Xfce, the toolbar is invisible unless I use the -style flag.

**Comment by Thaodan** [comment]
Setting Style=breeze also helps.
Is their a way to workaround this?

**Comment by medisun** [comment]
even now some issues with dark themes are exists with version 2.4.2.
you could set style permanently in config ~/.config/cantata/cantata.conf
`style=gtk2` - your GTK colors will be used

**Comment by officernice** [comment]
> even now some issues with dark themes are exists with version 2.4.2.
> you could set style permanently in config ~/.config/cantata/cantata.conf
> `style=gtk2` - your GTK colors will be used

This doesn't work for me. Cantata won't even launch with that setting, and I get the following error: 
`(cantata:1718): Gtk-WARNING **: 09:20:31.458: GTK+ module libxapp-gtk3-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:20:31.458: Failed to load module "xapp-gtk3-module"`
 It may be fixed soon as per this forum post: https://bbs.archlinux.org/viewtopic.php?id=263690
I can't for the life of me get either Audacious or Cantata to use adwaita-dark as theme with Xfce

**Comment by tmtvl** [comment]
Adwaita Dark has a Qt version, so you can launch Cantata with `-style=Adwaita-Dark`. Alternatively you could use the command `env XDG_CURRENT_DESKTOP=KDE /usr/bin/cantata $@` to force the use of whatever theme you have selected in KDE.
