### ISSUE TITLE
Multi-panel functionality

### ISSUE THREAD

**Issue by FrictionCow** [CDrummond/cantata#834]
Hello, thanks for the hard work on this MPD interface. Is there any way we could get an option to have multiple panels open at the same time? For example, I'd like to have my Library open, while at the same time having song lyrics available at all times. I certainly have enough horizontal space for that. Sorry if this can already be done in some way.

**Comment by CDrummond** [comment]
You can have lyrics and playqueue visible at the same time - just use the config dialog to place the context view in the sidebar.

Sorry, but I have no intention of making all the separate views draggable, and re-arrangeable.

**Comment by FrictionCow** [comment]
Ah, alright. Thanks for the quick response.
