### ISSUE TITLE
suggest some internet services

### ISSUE THREAD

**Issue by idmresettrial** [CDrummond/cantata#835]
Hi,

I suggest these internet services, because they have a lot of songs:
- youtube
- chiasenhac.com
- mp3.zing.vn

Thanks for your incredible app. :+1:

**Comment by CDrummond** [comment]
1. Youtube - no go. Tried, failed. Need to pass URL of just audio to MPD. This sometimes works, but for long songs there is a **long** delay. So, not really feasible

2. Never heard of the other 2. Are they legal? Do they have an API that can be used to query for songs, or download the library listing?

**Comment by idmresettrial** [comment]
1. Can you use youtube-dl, or something like that, for playing the youtube url?
2. Yes, they are legal. You may want to try at: http://j.ginggong.com/
You can have the API if you want.

**Comment by CDrummond** [comment]
I've tried integrating youtube-dl, but it (appears) to download the whole video before sending MPD the audio part - hence the too long delay.

**Comment by idmresettrial** [comment]
so what do you think of that ginggong? It has a lot of songs, right? ;)

**Comment by CDrummond** [comment]
It might do - but what I need is a set of APIs to call.

e.g. Call http://ginggong?search&artist=Abba which returns
<results>
<track>
<artist>Abba</artist>
<title>blah blah</title>
<url>http://a.b.c/x.mp3</url>
</track
<track>
...etc

If its a simple as that, then I can easily add it. However, I don't have the time to hunt out the API - so if you want this implemented you will need to track this down.

**Comment by idmresettrial** [comment]
certainly, here you are: http://j.ginggong.com/jOut.ashx?k=**abba**&code=3e5e0f33-3e56-44cf-8129-241cedc41fee
k is title, song, singer...
that will return a JSON object contains everything you need.

**Comment by CDrummond** [comment]
Where is the audio URL? The above seems to be:

   {
      "Id":"4e2f6d6d-1f9d-47b7-a2fa-adc2e4f4b985",
      "Title":"Happy New Year - ABBA",
      "Artist":"",
      "Avatar":"http://j.ginggong.com/JThumbnail.ashx?id=ZWZEC669\u0026h=mp3.zing.vn",
      "UrlJunDownload":"http://j.ginggong.com/jDownload.ashx?id=ZWZEC669\u0026h=mp3.zing.vn",
      "LyricsUrl":"http://j.ginggong.com/jLyrics.ashx?id=ZWZEC669\u0026h=mp3.zing.vn",
      "UrlSource":"http://mp3.zing.vn/bai-hat/Happy-New-Year-ABBA/ZWZEC669.html",
      "SiteId":"ZWZEC669",
      "HostName":"mp3.zing.vn"
   },

**Comment by idmresettrial** [comment]
UrlJunDownload, but you need unescape it first, so the audio URL is: http://j.ginggong.com/jDownload.ashx?id=ZWZEC669&h=mp3.zing.vn
( change \u0026 to & )

**Comment by CDrummond** [comment]
Great! I'll add this for 2.1

What about chiasenhac.com ?

**Comment by idmresettrial** [comment]
Nevermind, ginggong includes it.
Btw, it would be much more great if we could find a solution to the youtube problem. I think this could be done, because mpv, smplayer, bomi... has done that.

**Comment by CDrummond** [comment]
But all these playback the files themselves. Cantata needs to send **just** the audio URL to MPD. This is where the issue lies - it takes some time (for long videos) to extract this.

**Comment by idmresettrial** [comment]
How long does it take to start playing this video? https://www.youtube.com/watch?v=6Lq_0P39iLg

**Comment by CDrummond** [comment]
Just tried to implement this, but none of the songs play - I get a 302 error. Tried playing with vlc, ffplay, etc.

Also, seeing as I can see some pretty recent tracks I'm not convinced this is legal.
