### ISSUE TITLE
Playing albums from search results

### ISSUE THREAD

**Issue by putt1ck** [CDrummond/cantata#836]
I cannot see a way to add an album (or artist) from search results. I may be the only person who still listens to albums though...

Expected behaviour: having searched in collection for an artist or album, expect to be able to right click on any relevant track in search results and choose "play album" or "play artist".

Workaround: right click on relevant track, choose "Locate In Library", then right click on album or artist and select appropriate play action, or use mouse focus and Append/Play as appropriate.

**Comment by CDrummond** [comment]
Highlight all tracks - and use context menu? I have thought about grouping the search results into albums - just have not yet implemented this.

**Comment by cpchan** [comment]
I was just about to add this feature request. I listen to a lot of concept albums, so a tree view for a "one click adding" solution is highly appreciated. So far I have been using the "locate in library" workaround, but it is still annoying.
