### ISSUE TITLE
Shortcut for Ratings

### ISSUE THREAD

**Issue by drtebi** [CDrummond/cantata#837]
Unfortunately there does not seem to be a shortcut for setting a rating.

This would really be very useful; the more I can rate songs, the easier it will be to create playlists of favorite songs later on.

I often turn my monitor off when listening to Cantata in my workshop, and if I could just jump to the keyboard and press a key to rate a great song... that would be wonderful ☺.

I would suggest simply '1', '2', '3'... or Ctrl+1, Ctrl+2 etc.

**Comment by CDrummond** [comment]
Implemented in master (for 2.1) now. Default is Alt+0, etc. Ctrl+Num is used to selected between MPD instances.
