### ISSUE TITLE
Replace playlist without playing.

### ISSUE THREAD

**Issue by BethAr** [CDrummond/cantata#840]
Hey there,

Currently, there is no option to replace the queue with a stored playlist without playing it as well. To achieve this now, I have to clear the list and then add it. In essence, what I'm asking is a function to the `+` button that is similar to the play and replace for the play button, that is, simply to replace.

Thanks!

**Comment by BethAr** [comment]
Actually, I think what I'm thinking in fact is a view mode for the sidebar that is not expansible, that is, that allows you to simply click a playlist and have it immediately replace the queue, without having it expand, and without having to use either the plus button or the play button. I guess this is a much easier way of thinking.

**Comment by CDrummond** [comment]
Clear play queue, drag'n'drop playlist

**Comment by BethAr** [comment]
This doesn't work most of the time. If I drag a playlsit, clear it, and then drag another, it doesnt work, unless I expand the playlist and then close it.

It also doesn't work if I move from the playlists view to the folders view. I'm unable to clear the list and drag folders, and if I move back, I'm unable to drag playlists again.
