### ISSUE TITLE
random segfaults during Play queue clean-up.

### ISSUE THREAD

**Issue by angryvincent** [CDrummond/cantata#841]
This segfaults happening in random order. To reproduce: add all music in queue, let cantata work for several hours. Try clear queue with bottom right X button. Notice immediate cantata shutdown and segfaults in dmesg regarding MPDConnection.
This reproducible only with lot of entries in queue, neverm when loaded a single album.
This reproducible on cantata-2.0.0 release and with 2.0.50 (aka HEAD from git). Today i had a segfault and traps:

[ 6413.582634] MPDConnection[7570]: segfault at b8 ip 000000000057eafc sp 00007f5897ffe300 error 4 in cantata[400000+4d3000]
[16567.849297] traps: MPDConnection[7585] general protection ip:57eafc sp:7f382fbe6300 error:0 in cantata[400000+4d3000]

**Comment by CDrummond** [comment]
By a lot of entries - how many? 1000, 5000, 10000? Did you have any other clients connected? Dynamic playlist? Not really sure leaving it for hours should really matter.

**Comment by angryvincent** [comment]
currently i have 590 entries in playlist. But this happening only if number on entries (say unique songs) more than 30-50 (no exact correct number). I don't have any other clients connected during segfaults. I'm not sure what is dynamic playlist. I load entire music directory (all songs) or just add several albums to have at least few tens of songs.

**Comment by CDrummond** [comment]
OK, I'll try to recreate. But please, try to run in gdb

**Comment by angryvincent** [comment]
(gdb) file /usr/bin/cantata
Reading symbols from /usr/bin/cantata...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/cantata
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffec2c5700 (LWP 2592)]
[New Thread 0x7fffeb6b0700 (LWP 2593)]
[New Thread 0x7fffeaeaf700 (LWP 2594)]
[New Thread 0x7fffdbfff700 (LWP 2595)]
[New Thread 0x7fffdb487700 (LWP 2598)]
[New Thread 0x7fffda804700 (LWP 2656)]
[New Thread 0x7fffda003700 (LWP 2657)]
[New Thread 0x7fffd9802700 (LWP 2658)]
[New Thread 0x7fffd9001700 (LWP 2659)]
[New Thread 0x7fffd8800700 (LWP 2660)]
[Thread 0x7fffd8800700 (LWP 2660) exited]
[New Thread 0x7fffd8800700 (LWP 2670)]
[New Thread 0x7fffbbbe2700 (LWP 2671)]
[New Thread 0x7fffba436700 (LWP 2672)]
[Thread 0x7fffd8800700 (LWP 2670) exited]
[Thread 0x7fffba436700 (LWP 2672) exited]
[New Thread 0x7fffba436700 (LWP 2681)]
[Thread 0x7fffba436700 (LWP 2681) exited]
[New Thread 0x7fffba436700 (LWP 2687)]
[Thread 0x7fffba436700 (LWP 2687) exited]

Thread 5 "MPDConnection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdbfff700 (LWP 2595)]
0x000000000057eafc in QHash<QString, unsigned short>::findNode(QString const&, unsigned int*) const ()
(gdb)

**Comment by CDrummond** [comment]
Thanks. But, could you try again - and when it crashes type 'where' - this will print the backtrace, and print out the Cantata function that caused the segfault. Sorry, I should have mentioned this before.

**Comment by CDrummond** [comment]
Any updates? Still no crash for me.

**Comment by CDrummond** [comment]
Closing - works for me. Asked for more info 2 weeks ago, no response.
