### ISSUE TITLE
Can't bind shortcuts without using ctrl.

### ISSUE THREAD

**Issue by BethAr** [CDrummond/cantata#842]
I can't bind any shortcuts to any functions if I they don't use the Ctrl key, they are simply ignored by Cantata. At the moment I have to edit the config file to get the keys bound.

**Comment by CDrummond** [comment]
They work with Alt, and with just a function key - just tried. So, working as designed.

**Comment by BethAr** [comment]
So it is designed that the user can't bind a shortcut to a single letter or number? Ok then...
