### ISSUE TITLE
cantata-2.0.0 won't compile.

### ISSUE THREAD

**Issue by privacychain** [CDrummond/cantata#843]
I am not able to compile the 2.0.0 version on my Gentoo box. I feel this is related with last versions of Qt-5.6, Plasma-5.6.3, or kde-frameworks-5.21.0.

Attached the build log.
[build.txt](https://github.com/CDrummond/cantata/files/241049/build.txt)

Thanks!

**Comment by CDrummond** [comment]
This should already be fixed in master (and the 2.0 branch - for 2.0.1). Can you update and try?

**Comment by privacychain** [comment]
Successful compiled, Qt5 with default options.
I will wait the 2.0.1 version then. 

Thanks!

**Comment by CDrummond** [comment]
Thanks for the confirmation - I couldn't check as I'm only on Qt 5.4
