### ISSUE TITLE
High CPU usage when no cover image

### ISSUE THREAD

**Issue by selene-neko** [CDrummond/cantata#844]
If I choose "Interface -> Play Queue -> Background Image", select "Current album cover" and play musics (or pause / stop) without cover images, background images is blank, but cantata and xorg-server thread will keep consume at least 40% CPU time, I need to either play other musics with cover image or turn off background image to fix this.

**Comment by CDrummond** [comment]
Well, was only 4% CPU for me :-) Still, think this is now fixed. Can you checkout either mast or the 2.0 branch - and confirm?

**Comment by selene-neko** [comment]
Confirmed. Thanks for the fix!

**Comment by CDrummond** [comment]
Great! I'll try to release 2.0.1 soon...
