### ISSUE TITLE
MPRIS media-control notification not always working in gnome-shell

### ISSUE THREAD

**Issue by AlexT84** [CDrummond/cantata#845]
MPRIS notification in GNOME3 shell works only on Cantata startup.
After pressing play it disappears.
Don't know how to debug, but I'll do it if you tell me how.
Archlinux fully updated.

**Comment by CDrummond** [comment]
Work fine for me under Unity. What about other Qt apps? e.g. Clementine?

**Comment by AlexT84** [comment]
Clementine qt4: works.

2016-05-08 23:17 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Any Qt5 apps? Or have you tried compiling cantata for Qt4?

**Comment by AlexT84** [comment]
Actually I don't know of any other Qt5 app using mpris.

No, I haven't tried to compile Canatata in Qt4.



2016-05-09 13:31 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Well - don't think it'd make much difference anyway. Still - you did not answer my questions:

> Also "After pressing play it disappears." ?? What disappears? The notification should only be on screen for a few seconds. Do you mean that you don't get new notifications when changing tracks?

**Comment by AlexT84** [comment]
Sorry for both not seeing the latter questions and for not explaining
myself well enough.

Gnome-shell 3.20 introduced MPRIS media player controls in the notification
area (clock/calendar dropdown menu).
There, Cantata only shows them on startup, but after playing a song they
disappear until next app restart.

I absolutely have no idea about how to haunt down debug informations about
this issue.

Hope I've been clear enough this time.

2016-05-09 19:48 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Ah, I misread the title! I though this was about the dbus notification that happens when tracks change. Sorry.

However, I have just tired with Plasma5 (KDE5) - this has a MPRIS media control applet in the system tray. This shows up when an app with MPRIS is started - and shows next, play/pause, prev buttons as well as song details and progress. Tried with Cantata, and this worked perfectly - the controls were always shown, reflected Cantata's state, and could control Cantata.

Sorry, but I don't have a GNOME3 install to test on. (I did try, but could not get used to its way of working)

**Comment by AlexT84** [comment]
I see. It could be easy enough to try it in a Fedora 24 Beta live USB
session, or in a virtual machine.

At the end of the day Gnome3 is definitely not a champion in window
managing, but it has so much better system integration and coherent design
patterns and less bugs than KDE that I just preferred to get used to it,
even if I like KDE more.

2016-05-10 9:12 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Personally, I'm a fan of Unity. Just tried with Unity, and Cantata appears, and functions correctly, from its sound menu.

**Comment by CDrummond** [comment]
Don't have gnome shell - so can't do much from my side. As stated, works in KDE4/Plasma5 and Unity, so that's enough for me.
