### ISSUE TITLE
Duplicates in "configure streams" window

### ISSUE THREAD

**Issue by d7rk** [CDrummond/cantata#847]
Duplicates created at each opening of the "configure streams" window, but no impact in main stream window.

cantata 2.0.0-4
qt5-svg 5.6.0-1
libmtp 1.1.11-1
libcddb 1.3.2-4
libmusicbrainz5 5.1.0-2
mpg123 1.22.4-1
vlc 2.2.3-2
taglib-extras 1.0.1-4
cdparanoia 10.2-5
media-player-info 22-2
udisks2 2.1.7-1
hicolor-icon-theme 0.15-1
perl-uri 1.71-1
mpd 0.19.15-2
ffmpeg 1:3.0.2-2

![160517 - 17 40 20 - screenshot](https://cloud.githubusercontent.com/assets/16267092/15330863/81419ffc-1c56-11e6-9e76-5328446bd201.png)

**Comment by CDrummond** [comment]
Oops! Looks liek the list is re-downloaded each time. Will fix.

p.s. Sorry for the late reply - I've only just noticed this bug report!!!

**Comment by CDrummond** [comment]
Fixed in master (for 2.1) now.

**Comment by d7rk** [comment]
Works perfect with the git from AUR!
If that's not amazing reactivity, what is! Thanks.
