### ISSUE TITLE
More detailed format info

### ISSUE THREAD

**Issue by Blum** [CDrummond/cantata#848]
Hello, 
I think it would be nice if there is more detailed format information, with sample rate and etc, (triggered by some setting option maybe.)
Something like "FLAC 24bit/96KHz" or "MP3 256 Kbps". In the list track columns and also in the playlist.

I have many albums on different formats, now it is hard to recognize what is what.

Thanks for the good work, this client is awesome.

**Comment by CDrummond** [comment]
Not something I would use - please feel free to create a pull request though
