### ISSUE TITLE
Breeze icons for cantata

### ISSUE THREAD

**Issue by DarkknightAK** [CDrummond/cantata#849]
Hi,

I have a bug report for using breeze-icons in cantata (https://bugs.kde.org/show_bug.cgi?id=363784), but I don't know how the icons are called cause in the source code /icons folder there are some sidebar-xxx icons but when I add them to breeze, cantatat don't show them. 

Can you help me update the breeze icon set to have all needed icons for cantata in breeze.

**Comment by CDrummond** [comment]
You cannot change the sidebar icons in Cantata - the SVGs are embedded into Cantata, and it loads and recolours them.

For version 2.0.x, Cantata uses its own icons - some of which are copied from breeze. This was because it was becoming a pain when icons were not in all themes. The only icon that can be themed is the system tray icon - and cantata looks for "cantata-panel" in this case.

Fox 2.1, Cantata has a config item to allow usage of the user's theme - "useStandardIcons=true" needs to be set in Cantata's config file.

**Comment by DarkknightAK** [comment]
Hi,

I can theme cantata, when you change in configure -> Interface -> deactivate Use monochrome icons then the icons from system settings /user/share/icons/ was selected instead of the icons from the cantata source.

But I have problems to find out the icon names, where are the cantata icons from the source code be installed?

**Comment by DarkknightAK** [comment]
the system tray icons was changed in the breeze plasma theme yesterday. this is done.

**Comment by DarkknightAK** [comment]
my problem is that you have sidebar-xxx icons (the monochrome ones) in your source code but when you switch to deactivate monochrome icons the icons are called different. that confuse me. how is the radiostation icon called in the sidebar e.g.

**Comment by CDrummond** [comment]
Ah, this is Cantata 1.x you are talking about - as 2.x *always* uses the monochrome icons. For 1.x some icons are hard-coded, and some from the icon theme. Bit of a mess, hence 2.x always using the mono icons. The 1.x sidebar icons are:

play queue - media-playback-start
artist - embedded SVG
album - media-optical
folders - inode-directory
playlists - view-media-playlist
dynamic - media-playlist-shuffle
streams - embedded
online - applications-internet
info - dialog-information
search edit-find

**Comment by DarkknightAK** [comment]
so best would be to waite until 2.1 and talk than about icon names and new needed icons.

thank's for the replay.

**Comment by CDrummond** [comment]
2.0 is already out - but it has a few issues, which will be fixed in 2.0.1

As to when 2.1 will be released - no idea. My time for Cantata is severely reduced.

Anyhow, I'll close this.

**Comment by DarkknightAK** [comment]
ok when you need help with some icons, you can ask me always.

**Comment by varlesh** [comment]
@CDrummond Hi, will be cool add option for use system icons on Linux sytems. And  Breeze theme icon names as standard (for Amorok already exist more similar icons, why we can't use this icons?)
Or another solution - use hardcoded icons as fallback...
For example:
```
setIcon(
       QIcon::fromTheme("media-playback-start", QIcon(":/icons/media-play.svg")))
```
