### ISSUE TITLE
Playback from CDDA fails (readClient Not from valid host)

### ISSUE THREAD

**Issue by melvinvermeeren** [CDrummond/cantata#850]
Playback from CDDA fails, compiled from master branch commit 854eec9a08b3150c436d687ebb6d6d9eaf204c9b.

It seems like curl defaults to IPv6 nowadays on MPD's side causing the requests to be rejected. Also accepting localhost IPv6 connections will probably fix the issue.

I posted some of the log below (CANTATA_DEBUG=1024) with what I believe to be irrelevant bits removed. I also masked the song details and such.

```
2016-06-02 10:47:13 - HttpServer ifaceIp MPD interface ip "127.0.0.1"

... snip ...

2016-06-02 10:47:16 - HttpSocket handleNewConnection
2016-06-02 10:47:16 - HttpSocket readClient params ("Host: 127.0.0.1:41676", "User-Agent: Music Player Daemon 0.20", "Accept: */*", "Icy-Metadata: 1", "") tokens ("GET", "/[cantata-cdda]//dev/sr0/9.wav?album=...&artist=...&albumartist=...&title=...&year=...&time=234&track=9&id=9&cantata=song", "HTTP/1.1", "")
2016-06-02 10:47:16 - HttpSocket readClient peer: "::ffff:127.0.0.1" mpd: "" iface: "0.0.0.0" ok: false
2016-06-02 10:47:16 - HttpSocket readClient Not from valid host
2016-06-02 10:47:16 - HttpServer decodeUrl "/[cantata-cdda]//dev/sr0/9.wav" "Artist" "Album" "Title"
```

**Comment by melvinvermeeren** [comment]
I can confirm that the following patch resolves the issue. I haven't configured my SSH key on github since I host my own GitLab instance for personal projects.

Could you apply the following patch?

Thanks!

```patch
diff --git a/http/httpsocket.cpp b/http/httpsocket.cpp
index 122d85c..3359728 100644
--- a/http/httpsocket.cpp
+++ b/http/httpsocket.cpp
@@ -275,7 +275,7 @@ void HttpSocket::readClient()
 
             QString peer=socket->peerAddress().toString();
             QString ifaceAddress=serverAddress().toString();
-            bool hostOk=peer==ifaceAddress || peer==mpdAddr || peer==QLatin1String("127.0.0.1");
+            bool hostOk=peer==ifaceAddress || peer==mpdAddr || peer==QLatin1String("127.0.0.1") || peer==QLatin1String("::ffff:127.0.0.1");
 
             DBUG << "peer:" << peer << "mpd:" << mpdAddr << "iface:" << ifaceAddress << "ok:" << hostOk;
             if (!hostOk) {
```

**Comment by melvinvermeeren** [comment]
On a unrelated note: it seems that the playlist doesn't update properly when playing back a CD.
All features work (such as stop after track), but the GUI doesn't follow when a track change occurs.

When a new track starts playing it resets the play time but it doesn't move the track.

The easiest way to debug:
* Double-click track 5 (playback starts)
* Double-click track 3 (track changes, GUI stays at 5)

It's probably a simple thing like the GUI not being notified, although I don't know how the internals work.

**Comment by CDrummond** [comment]
Patch applied - thanks!

I've also fixed the GUI track advance - you were right, only occurred if there was no meta data.
