### ISSUE TITLE
Smart in-directory playlists

### ISSUE THREAD

**Issue by mutantcornholio** [CDrummond/cantata#852]
Sometimes people add .m3u playlists in the directory with files.
Adding that directory leads to adding all files twice.

How about excluding all separate files that are about to be added if they are adding by playlist as one action? 
Or, vice versa

**Comment by CDrummond** [comment]
Must admit I use neither in-folder m3u files, nor the folder view. But I see your point. Don't feel like adding parsing of m3u files (as Cantata might not have access if MPD is on another host). What I can do is to not automatically add playlists when adding a folder. e.g. if you drag a folder, only the songs will be added - to use the playlist you would need to manually select it.

**Comment by CDrummond** [comment]
Implemented in master (for 2.1.0), not in 2.0.x as its a behavioural change - even if it seems it is the correct behaviour :-)

**Comment by mutantcornholio** [comment]
Whoa, that was fast! Thanks!
