### ISSUE TITLE
Podcasts: MPD reported the following error: Missing closing '"'

### ISSUE THREAD

**Issue by d7rk** [CDrummond/cantata#853]
Hello Craig,

First, let me thank you for Cantata. it's really a great music player!

Using **Cantata 2.0.1:**
When trying to play some podcasts (at least all those from WNYC), the following is returned and the podcast remains unplayed: 
`MPD reported the following error: Missing closing '"'`

The feeds are read without issues: the episodes are listed in the panel.
The feeds and podcasts work with another program (clementine, which does not rely on mpd). 

The problem arises independently of the source selected to find them (url, itunes, etc.)
Some of the podcasts not working are the following:
On the media: http://feeds.wnyc.org/onthemedia
Radiolab: http://feeds.wnyc.org/radiolab
Snap Judgment: http://feeds.wnyc.org/snapjudgment-wnyc
Soundcheck: http://feeds.wnyc.org/wnyc_soundcheck
Studio360: http://feeds.feedburner.com/studio360/podcast
The New Yorker Radio hour: http://feeds.wnyc.org/newyorkerradiohour

Thanks!

**Comment by CDrummond** [comment]
I've only tried "On the media" - and the issue appears to be that the podcast titles have a "\n" (new-line) character in them. I've updated master (for 2.1) to remove these. The podcasts now load for me.

Can you try git/master?

**Comment by d7rk** [comment]
Works perfect with the git from AUR!
If that's not amazing reactivity, what is! Thanks.

**Comment by CDrummond** [comment]
Thanks for the confirmation.
