### ISSUE TITLE
Cantata cant connect to local connection if pid is wrong

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#855]
If the pid in the cache dir of canata is wrong it cant connect.
For example. The system isn't properly shutdown and cantata is started afterwards and says it cant connect.
Removing the pid file in this case is workaround.

**Comment by CDrummond** [comment]
This should now be fixed (in master). Can you update and confirm?

**Comment by Thaodan** [comment]
yes killed cantata and mpd startet cantata and its fixed.
