### ISSUE TITLE
Podcast "Listened" status not rememberd after closing

### ISSUE THREAD

**Issue by Llamatron2112** [CDrummond/cantata#860]
Podcasts properly mark as listened when I play them, but when I close and open cantata, all are back to unlistened status.

Running in Arch with XFCE desktop. I also tried using cantata-git from AUR without more luck.

EDIT: now it seems like podcasts don't set to listened after starting playing them, while I'm 100% positive they used to.

**Comment by CDrummond** [comment]
Should be fixed in master now. Can you update and confirm?

**Comment by Llamatron2112** [comment]
yes it works now, thanks a lot ! I was struggling finding a player with good support for radio streams and podcasts, now cantata does both very well.

Icing on the cake would be to have the unread count and bold text status changed on the podcast's title on the fly. Currently it refreshes only when launching the app. I can open another issue for this suggestion if you prefer.

**Comment by CDrummond** [comment]
Should be fixed now :-)

**Comment by Llamatron2112** [comment]
Awesome, thanks again ! :)

There's another  thing, but regarding radio streams, wasn't their name automatically created when being added or played before ? Or am I mixing with another player ? Again, I can open another thread if you prefer, as it's not related to the original issue.

**Comment by CDrummond** [comment]
Works for me. Just tried:

1. Add a stream from favourites to playqueue. Playqueue shows stream name as stored in favourites
2. Search for a station on TuneIn, click heart icon to add to favourites. Station is stored in favourites with correct name. I then add this to the playqueue, and again it has the correct name,

**Comment by Llamatron2112** [comment]
I ment when right clicking the playqueue, selecting "Add Stream URL", then "Add to play queue, and save to favourites"

**Comment by CDrummond** [comment]
Ah. What I see now is that the stream is saved to favourites with the title, but no title in playqueue. Is this the same as you are seeing?  Will fix. No need for a new bug report. But please, raise new reports for future issues, thanks.

**Comment by Llamatron2112** [comment]
That's not exactly what I ment, but it's a bug too ! I'll do a feature request and hopefully you'll understand what I mean with my limited english skills.
