### ISSUE TITLE
Automatic stream name from stream metadata when adding to favourites from URL.

### ISSUE THREAD

**Issue by Llamatron2112** [CDrummond/cantata#861]
Many radio streams have the radio's name/description in their metadata.

When right clicking the play queue, selecting "Add Stream URL", then selecting "Add to play queue, and save to favourites" in the dialog's drop down menu, it would be nice to be able to use this info in the metadata to have the Name field automatically set.

It could for example be a button on the "Add Stream URL" dialog to fetch the data from the provided url on demand, then fill the Name field automatically. But there's probably other ways this could be implemented.

**Comment by CDrummond** [comment]
If the stream has metadata, then MPD will pick this up when playing - and it should (after a while) appear in the playqueue.

As for the add stream dialog detecting this - not sure its worth the hassle. If you are adding a stream, you more than likely know the name. Also, this add dialog does not do anything with the URL apart from save in favourites and add to playqueue. While I could add a 'fetch name' button that would download a segment of the stream, it seems a bit too much hassle for now.

As always, patches  / pull-requests welcome.

**Comment by CDrummond** [comment]
Closing - as stated, if you're adding a URL manually you more than likely know the station name.
