### ISSUE TITLE
use Pulseaudio if available

### ISSUE THREAD

**Issue by SanKro** [CDrummond/cantata#862]
Cantata should configure mpd to use pulseaudio if its available on the system and supported by mpd.

right now it seems that it'll start in ALSA mode always (this leads here to crackling sounds)

you can change in
**~/.local/share/cantata/mpd/mpd.conf**

```
audio_output {
  type "alsa"
  name "output"
}
```

to something like this:
```
audio_output {
  type "pulse"
  name "Cantata"
}
```

in case you're using pulse, everything will finally work (:

**Comment by CDrummond** [comment]
I agree pulse audio makes more sense, implemented in master (for 2.1) now.
