### ISSUE TITLE
issues under Plasma 5.7 beta

### ISSUE THREAD

**Issue by AlexT84** [CDrummond/cantata#863]
Arch linux x64, 
cantata 2.0.1
plasma-desktop 5.6.95
qt 5.7
frameworks 5.23

- media controls in taskbar menu doesn't work
- MPRIS applet controls in system tray are very buggy with cantata, sometimes they simply don't work, sometimes they just repeat the song, etc..

a reference plasma-devl discussion
https://mail.kde.org/pipermail/plasma-devel/2016-June/055132.html

**Comment by CDrummond** [comment]
Well, if the controls worked in 5.6 then how is this a Cantata issue? Can't see anything relevant to MPRIS in that mail thread.

**Comment by AlexT84** [comment]
Then I'll wait for 5.7 final and see.
I've reported here MPRIS issues also in gnome shell a month ago.
Don't know what's wrong, but if you tell me how to debug I'll help you.

Ah, there's no old cache/config in my system, as I clean0 /home from time
to time.
I'll ask on Arch forums.


2016-06-29 9:04 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Having said that everything worked under Unity, I've just noticed the play/pause icon did not change to 'pause'. This is fixed now, and I've changed a couple of other bits.

Can you see if these changes have resolved this? Thanks.

**Comment by AlexT84** [comment]
I'm not under Unity, but Plasma.
That's weird because now I'm listening to music with Cantata and Back and
Forward buttons are disabled, Play and Pause work as expected and with
proper icons changes.

2016-07-02 17:11 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
I know you're not on Unity - hence asking for you to check. Odd that back/next are disabled - because they should always be enabled. The MPRIS CanGoNext/CanGoPrevious now always returns true.

Tested with KDE5.5, and its still working for me.

Did you do a complete rebuild and install? Restart KDE?

**Comment by AlexT84** [comment]
Ok, I've compiled it, restarted KDE, ran it, same mpris control problems
(which are quite random)
At the same time, VLC works as expected.
I'll poke to Plasma devs now.

2016-07-03 13:07 GMT+02:00 CraigD <notifications@github.com>:

**Comment by AlexT84** [comment]
This is a completely tangent post.
In plasma-devel devs are considering Cantata as the recommended KDE audio player https://mail.kde.org/pipermail/plasma-devel/2016-July/055497.html
Have you ever considered joining KDE Incubator and benefit from it? https://community.kde.org/Incubator

**Comment by CDrummond** [comment]
Not sure Cantata is really a suitable fit for a default KDE app.

I installed KDE neon - so as to try Plasma 5.7. I noticed that if I started Cantata, and then re-started plasma (kill plasmashell, and restart) then the MPRIS controls would work. So, looks like there is a timing issue. I've modified the code to delay the initialisation of MPRIS - and this seems to have worked around the issue for me.

Can you please update and try?

**Comment by CDrummond** [comment]
Any updates? Can you please try the latest git/master?

**Comment by AlexT84** [comment]
sorry, tomorrow morning

2016-07-14 17:42 GMT+02:00 CraigD <notifications@github.com>:

**Comment by lebarondemerde** [comment]
I do also experience some issues with Cantata + "Music Player" applet even before 5.7. Sometimes I need to _open-close_ cantata a few times before it be found by the applet, if I want the applet working.

*If it helps, Spotify work like a charm with that applet.

@CDrummond 

Is still valuable to test the git/master about this issue?

**Comment by CDrummond** [comment]
Well, if you are having issues that git/master might fix - then yes. 2.0 is not being developed, the next release will be 2.1. So, please check with that.

**Comment by CDrummond** [comment]
Closing - works for me
