### ISSUE TITLE
Play Queue Issue.

### ISSUE THREAD

**Issue by privacychain** [CDrummond/cantata#864]
Hi,

I do not know if this behavior is a bug or a feature, but I use Cantata by default but when I try to control what MPD is playing using something like MPDroid the queue between the two are not the same. It even play two different thing at same time.

**Comment by CDrummond** [comment]
MPD cannot play two things at the same time. What I think has happened is that you are using the 'Personal' or 'Basic' Cantata mode. This starts its own MPD instance, and cannot be accessed via other clients and is only local to the current machine. This is explained in the help text.

Anyway, I have just tested Cantata and GMPC controlling the same MPD instance - and works as expected. i.e. they have the same playqueue, current track, etc.

**Comment by privacychain** [comment]
Oh, thanks. I am using Cantata only for so many years I had never aware of it. Yes, I was using Personal mode.

Thanks.
