### ISSUE TITLE
Some albums are splitted in the Library view

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#865]
In the library view I have some albums that are splitted in several ones and not ordered correctly in the grid view.

![capture du 2016-06-30 21-28-44](https://cloud.githubusercontent.com/assets/3726886/16501427/a8afc700-3f09-11e6-8700-be10961157b4.png)

Theses albums are displayed properly in others clients like ncmpcpp

![capture du 2016-06-30 21-29-56](https://cloud.githubusercontent.com/assets/3726886/16501476/d860f154-3f09-11e6-97f2-8d8a237d9363.png)

**Comment by CDrummond** [comment]
Cantata uses the 'album artist' AND ( 'album name' or 'album musicbrainz id') to group tracks into an album. I assume in the above some of your tracks have different 'music brainz' ids.

**Comment by CDrummond** [comment]
To check what 'id' Cantata is using to group an album:

1. Install sqlitebrowser (or some other tool to look at an SQLite db file)

2. Open Cantata's sql file in this. The sql files will be in ~/.local/share/cantata/library - e.g. 
~/.local/share/cantata/library/localhost_6600.sql 

3. In sqlitebrowser, go to the 'Execute SQL' tab and type the following query:

select * from songs where artist like '%Connor%'

4. Press the play button - tooltip 'Execute SQL [F5, Ctrl+Return]'

5. All the songs with a matching artist should be returned. Look for the 'artistId' and 'albumId' values for the affected tracks. It is these values Cantata uses to group.

**Comment by edhelas** [comment]
I'll have a look, thanks.

**Comment by edhelas** [comment]
I had a look at the tags and you're true some albums only have some of theses tags correctly put.
It's actually a good thing that Cantata is sensible to this. Thanks for the explanation.
