### ISSUE TITLE
Mouse wheel for volume control

### ISSUE THREAD

**Issue by bosim** [CDrummond/cantata#866]
I just noticed the volume bar doesn't support mouse wheel control. Would be a nice feature.

Thanks for creating Cantata, really a joy to use. I use it with my Sonos device (I did a small proxy for supporting that https://github.com/bosim/socompd). For this purpose it could be nice to have output selection, is that something you plan to implement (from what I know the mpd protocol supports it?)

**Comment by CDrummond** [comment]
Cantata **does** support mouse wheel events on the volume slider - just tried, and it works.

Cantata also supports output selection. There should be an 'Outputs' menu in the toolbar gear menu. This will only appear if you have more than 1 output.
