### ISSUE TITLE
possible to launch a dynamic playlist from CLI (to bind to a key)

### ISSUE THREAD

**Issue by zeltak** [CDrummond/cantata#867]
Hi

is it possible to launch a dynamic playlist from CLI (to bind to a key). for example if i had a dynamic playlist called Z1 i would go 

```
cantata --load-dynamic z1
```

thx

Z

**Comment by CDrummond** [comment]
Not really. It is _possible_ to run the script manually -see 'Dynamic Helper Script - Local Mode' in README. But its not really designed for this.
