### ISSUE TITLE
cantata play/pause issues on ubuntu 16.04

### ISSUE THREAD

**Issue by adlh** [CDrummond/cantata#870]
After upgrading to 16.04, the play/pause button on the keyboard stopped working.

Also, the play button on the sound indicator doesn't change to 'Pause' during play.

I already commented on a similar bug on launchpad:

https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1576970/comments/5

**Comment by CDrummond** [comment]
Cantata uses Gnome media keys daemon for media keys. Or for **Qt4** it uses Qxt - but this only works with Qt4.

Just tried under Unity in 16.04 and media keys are working.

Indicator issue is also fixed in master - and is related to #863

**Comment by adlh** [comment]
Hey, thanks for the quick reply.

I updated the info on launchpad.

> Just tried under Unity in 16.04 and media keys are working.

I'm also using Unity and the play/pause media key stopped working for cantata after the upgrade to 16.04. Rhythmbox on the other side is still working. On 14.04 the media key was working as expected with cantata. Do you have an idea what could have gone wrong?

**Comment by CDrummond** [comment]
Which Qt version? Qt4 or Qt5 (Cantata as of 2.0 uses Qt5 be default). To interact with the media keys - Cantata is using GNOME's media keys demon - this code has not changed since Cantata 1.x

**Comment by adlh** [comment]
I have cantata 1.5.2 (installed per package manager) and I'm not sure, but I have appmenu-qt5 installed, so I suppose I'm using qt5. Maybe on 14.04 it was still qt4 and that's the problem now? Should I try to install cantata 2.0? Is there a PPA, or would I have to deinstall and git clone + install manually?

**Comment by CDrummond** [comment]
I would imagine 1.5.2 is built against Qt4. In that case it *might* be using Qxt - but I would have thought it'd be GNOME media keys. If you run:

CANTATA_DEBUG=-0x00040000 cantata

from a terminal window, it should print out some debug stating which media keys interface it is using.

Sorry, no idea about PPAs

**Comment by adlh** [comment]
Ok. The command `CANTATA_DEBUG=-0x00040000 cantata`

Outputs: `QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.` ... seems like there is a problem indeed.

I just found this PPA `sudo add-apt-repository ppa:ubuntuhandbook1/cantata-qt` and upgraded to 2.0...  the 'play/pause'-media key is working again... the problem with the notify icon is still there... but I hope the fix will arrive soon through this PPA.

Thanks for the help!

**Comment by CDrummond** [comment]
The notifier play/pause fix will only be in a 2.1 release. Whilst I could backport to a 2.0 release, my spare time is rather limited.

**Comment by adlh** [comment]
Don't worry. I'm happy enough, my play/pause button is working again! ... And also about the super-quick-help!!! Thanks a lot. Also for such a great application!
