### ISSUE TITLE
Wrong behaviour showing lyrics.

### ISSUE THREAD

**Issue by Aqa-Ib** [CDrummond/cantata#871]
Hello Mr. CDrummond. How are you? Here I come again with some problem x)

I am using Cantata version 2.0.1 from the Arch Linux community repository. When I try to read the lyrics of a song into cantata, if I scroll down the lyrics to read them (because the complete lyrics of a song doesn't fit into my screen), it scrolls automatically up, and it does not allow me to read them. Sometimes it happens when I scroll down (it scrolls up instantly and automatically), and sometimes it happens when I scroll up (it scrolls down instantly and automatically).

I don't know if I am explaining myself, if you can't understand what is happening, please, say it and I will try to explain it better.

Long live Cantata!

**Comment by CDrummond** [comment]
Right click on lyrics, and disable 'Scroll Lyrics'

**Comment by Aqa-Ib** [comment]
OMG!! Now I understand it.
Thanks you very much, and sorry for the incovenience!

Regards!
