### ISSUE TITLE
Mistake in handling playlist update when there're duplicate songs

### ISSUE THREAD

**Issue by yshui** [CDrummond/cantata#873]
Suppose I have a playlist containing "SongA SongB SongA"

I issue a command to swap entry 1 and 2, the result should be "SongA SongA SongB", but cantata shows it as "SongB SongA SongB". Restart cantata, and the playlist content become correct again.

The problem is in PlaylistsModel::playlistInfoRetrived(). When this function sees a new song item, it first check if it's already in the list, and if so, swap it. The problem here is when there're duplicates, this function failed to pick the correct one to swap with.

**Comment by CDrummond** [comment]
Just tried, and it is working OK for me. In the play**list** sidebar I have a playlist with 4 tracks:

Track A
Track B
Track A
Track C

I drag 1st Track A between B and 2nd A then I have

Track B
Track A
Track A
Track C

So, appears to work as expected. After Cantata moves a track, the MPDConnection class signals 'movedInPlaylist' - playlistInfoRetrived is not called.

Are you using another MPD client to move the tracks?

**Comment by CDrummond** [comment]
I still think Cantata is OK, but I've simplified the playlistInfoRetrived code - can you please unzip

[playlistsmodel.zip](https://github.com/CDrummond/cantata/files/380289/playlistsmodel.zip)

Into the 'models' folder, and rebuild (and install) Cantata. Does this resolve your issue?

**Comment by yshui** [comment]
@CDrummond I was sending 'playlistmove' command directly to mpd using nc

**Comment by yshui** [comment]
@CDrummond Your patch solve the problem for me. Thanks

**Comment by CDrummond** [comment]
I thought that might be the case (using another client). Thanks for the confirmation, I'll apply the patch later.
