### ISSUE TITLE
Cantata, Bleachbit and "Connection to "Personal" failed" in single user mode

### ISSUE THREAD

**Issue by FabioLolix** [CDrummond/cantata#879]
Cantata 2.0.1 on Manjaro Linux, single user mode

Sometime I clean the system with Bleachbit which delete /home/user/.cache/cantata/ folder entirely.

At a new launch Canata don't recreate the folder /home/user/.cache/cantata/mpd/ and relative files
thus showing error message "Connection to "Personal" failed" and preventing playback

**Comment by CDrummond** [comment]
Just tried with git/master (which will be 2.1) and seems to now work.
