### ISSUE TITLE
Commandline access for play, pause, next, prev etc...

### ISSUE THREAD

**Issue by Gibbz** [CDrummond/cantata#880]
1. Would love to see command line access to these so that I can bind global shortcut keys.

2. Also built in global shortcut keys would be great to see if thats possible to do?

**Comment by CDrummond** [comment]
Media keys can be used for these actions.

As for command-line access, not going to happen. But see the [cantata-remote](https://github.com/CDrummond/cantata/blob/master/cantata-remote.cmake) shell script for a way to use the MPRIS DBUS interface for this.

**Comment by mleko69** [comment]
Hello CDrummond, first of all thanks for such an awesome software.
I have a question - how to remotely control Cantata with this script? I'm interested in remotely turning on and off shuffling, repeating a playlist, and autostart of playback after running Cantata (if it's even possible do control such parameters with DBUS interface).
Kindest regards
