### ISSUE TITLE
Remove a track/album from a Device

### ISSUE THREAD

**Issue by edhelas** [CDrummond/cantata#883]
I can't find an easy way to remove a track/album from a device. 
Logically I would have found this action by right clicking an album/track in the device content list.
![device](https://cloud.githubusercontent.com/assets/3726886/17604047/464b5e9a-6014-11e6-8acc-11689b3c7ff3.png)

**Comment by CDrummond** [comment]
Preferences > Interface > General > Show delete action in context menus

**Comment by Upperholme** [comment]
That option doesn't appear to be available in the Mac OS version I'm running (2.0.1)
