### ISSUE TITLE
Feature request: More "advanced" search

### ISSUE THREAD

**Issue by samuraiii** [CDrummond/cantata#884]
Hello,
first I would like to thank for great MPD client....
And second, my request:
Would it be possible to implement more advanced search for Cantata (or am I whining on wrong grave?)?
Something like
```
filetype:flac AND NOT (artist:"Lousy guy" OR album:"my GF's disco")
```

Which would match all *.flac files but neither from "Lousy guy" artist or "my GF's disco" album.
With thanks 
S

**Comment by CDrummond** [comment]
I could add a 'raw' search type - where the string is sent as is to MPD. This would require you to know the MPD search protocol.

If you mean by extending the UI to have multiple search fields (e.g. with a +/- button), then probably not going to happen - unless you feel like implementing yourself.

**Comment by CDrummond** [comment]
If you want a more feature rich search you need to:

a. Respond to questions
b. Create a pull request

**Comment by samuraiii** [comment]
Hi,
I am sorry to respond so lately (other stuff got into way).

ad a. 
Yes this would be obviously easiest way (is there any good documentation for this?)

ad b.
If I was capable to create PR I would not bother You until it was ready, but my knowledge of coding is limited to other fields.


Again my apology for late reply
