### ISSUE TITLE
Adding Equalizer feature?!

### ISSUE THREAD

**Issue by Yanis-Boussad** [CDrummond/cantata#886]
It would be nice if you add equalizer feature to Cantata.

**Comment by CDrummond** [comment]
Sorry - but music is played by MPD - and it has no equalizer.

**Comment by RoestVrijStaal** [comment]
@Yanis-Boussad Try [PulseEffects](https://github.com/wwmm/pulseeffects#pulseeffects). 

Within PulseEffects, toggle the switch to set "Music Player Daemon"'s output to "PulseEffects (apps)", and activate the Equalizer function.
