### ISSUE TITLE
[Enhancement] Sort album in album view: random

### ISSUE THREAD

**Issue by lyndametref** [CDrummond/cantata#890]
Thank you for developing Cantata, it make my music listening experience better!

Is it possible to add the option to sort randomly the album in the "grouped by album" library view (currently Name, Artist, Year and Modified Date are available)? 

It is a bit boring to have always the same albums at the top of the list, and will encourage the hearing of all the library.

**Comment by CDrummond** [comment]
You can shuffle the albums in the play queue. But 'random' sort makes no sense in the library view.

**Comment by spectromas** [comment]
I would disagree that it makes no sense, if you have a large library sometimes it is nice to be given a selection of albums you might not have thought to scroll/filter down to
