### ISSUE TITLE
Request: View>Grid, Group By>Album, Sort Albums>Artist/Year

### ISSUE THREAD

**Issue by spectromas** [CDrummond/cantata#891]
Not sure if this is possible already but it would be great to be able to have the album art view with the above settings so that you can view the albums by an artist in the order in which they were released rather than only by alphabetical order.

**Comment by CDrummond** [comment]
git/master (for 2.1) has all the old 1.5.x album sorts - and this includes 'Artist/Year/Album'

Not sure when 2.1 will be released...

**Comment by spectromas** [comment]
Ok thanks, that's good to know.
