### ISSUE TITLE
Weird behaviour with internet radio streams

### ISSUE THREAD

**Issue by 1-eric** [CDrummond/cantata#892]
I notice 2 things when playing an internet radio stream with Cantata-2.0.1 and monitoring the network connection with the command 'netstat -tp':

1) When playing a stream I see that _both_ mpd and Cantata are connected to the stream URL.
`tcp        0      0 localhost:60288          atlantic301.de.un:10054 ESTABLISHED 7995/mpd`
`tcp        0      0 localhost:60286          atlantic301.de.un:10054 ESTABLISHED 9360/cantata`

2a) When I stop playing the stream, the sound stops and the mpd connection to the stream URL disappears... but the Cantata connection to the stream URL stays and the lights of my router keeps blinking as if Cantata is still "playing" the radio stream with the sound muted.

2b) When after stop playing the stream, I start playing the stream again, I see that Cantata is connected twice to the stream URL.
`tcp        0      0 localhost:60286          atlantic301.de.un:10054 ESTABLISHED 9360/cantata`
`tcp        0      0 localhost:60282          atlantic301.de.un:10054 ESTABLISHED 9360/cantata`

**Comment by CDrummond** [comment]
Odd that one. I'm using Qt's network code - and I'm closing all jobs. Looks like in this instance I need to abort the job before closing. This is what I have now done.

Any chance you can checkout git/master and see if this is resolved for you?

**Comment by 1-eric** [comment]
I've compiled yesterday's version and it is resolved. Thanks.

I normally compile with '-DENABLE_SIMPLE_MPD_SUPPORT=OFF', but yesterday's version failed compiling with this option:`
[ 56%] Building CXX object CMakeFiles/cantata.dir/mpd-interface/mpdconnection.cpp.o
/var/abs/local/cantata/src/cantata/mpd-interface/mpdconnection.cpp: In member function 'MPDConnection::ConnectionReturn MPDConnection::connectToMPD()':
/var/abs/local/cantata/src/cantata/mpd-interface/mpdconnection.cpp:448:41: error: 'maxConnAttempts' was not declared in this scope
     for (int connAttempt=0; connAttempt<maxConnAttempts; ++connAttempt) {
                                         ^
make[2]: *** [CMakeFiles/cantata.dir/build.make:1341: CMakeFiles/cantata.dir/mpd-interface/mpdconnection.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/cantata.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`
