### ISSUE TITLE
mpris2 export of coverart does not work

### ISSUE THREAD

**Issue by Tids** [CDrummond/cantata#893]
in all mpris controlls you can controll cantata perfectly. only the coverart is not shown in any of them. I dont know if this is a bug or just a missing feature but it would be nice to have.

i tried it with integrated coverarts and "cover.jpg" files inside the folders

**Comment by CDrummond** [comment]
Well, works just fine for me under Unity. Which DE is this? And which version of Cantata? Please try git/master if you have not already.

Just tried latest in Plasma5.7 - also showing covers.

**Comment by Tids** [comment]
i rebuild it dale from git so i'm always on latest code. (but its the same with the stable release)
curently tested with KDE Plasma 5.7.4 and GNOME .. uhm .. dont know the version (latest stable).

Cover is shown in as notification
![screenshot_20160919_181344](https://cloud.githubusercontent.com/assets/18744080/18639686/278b7d38-7e95-11e6-9436-1d0b43c2cfa8.png)

but missing in all mpris controlls
![screenshot_20160919_181436](https://cloud.githubusercontent.com/assets/18744080/18639702/37b664c0-7e95-11e6-96aa-6c6e241131f9.png)

i dont know if this cares much but i mostly just have *.flac audio formats.

**Comment by CDrummond** [comment]
Just tried under neon - which uses Plasma 5.7. Again working just fine. This is looking like a setup issue on your side.

Running Cantata from a terminal should provide debug as to where it is looking for covers:

CANTATA_DEBUG=-4 ./cantata

(a negative number means log to the terminal, "CANTATA_DEBUG=4 ./cantata" would log to ~/.cache/cantata/cantata.log)

**Comment by Tids** [comment]
log of cantata output
[output.txt](https://github.com/CDrummond/cantata/files/482371/output.txt)
start cantata
press "play"
look to my mpris controlls on plasma.

seems like it has found the integrated image. so i dont understand why it does not show up in the mpris controlls. 

could you try it again with manjaro kde? cantata and vboxextensions are pre-installed so it should be easy to test on virtualbox.
http://downloads.sourceforge.net/manjarolinux/manjaro-kde-16.08-x86_64.iso
i can not test in kubuntu neon because it seems that cantata version on there does simply nothing and seems to be a little outdated

**Comment by CDrummond** [comment]
Ah, MPRIS will need a local JPG file - embedded cover will not work. For MPRIS Cantata just sends a URL to the file. For notifications, Cantata will embed the cover if its not in a JPG/PNG file.

**Comment by Tids** [comment]
In this case, wouldnt it be better to cache all the covers at ~.cache/cantata/album/$albumname.jpeg and use them for both - notification AND MPRIS?
Because, for me, its OK to set a cover.jpeg to a folder, but take people like my gf. She has "one big folder" with 3000-4000 tracks and she really need cantata to find/manage tracks and playlists. In this case its impossible to set a coverimage in this one big folder.

**Comment by CDrummond** [comment]
git/master (for 2.1.0) will now save embedded covers to Cantata's cache folder. This path can then be used by MPRIS
