### ISSUE TITLE
buttons for controlling volume

### ISSUE THREAD

**Issue by glensc** [CDrummond/cantata#895]
i would like to have graphical buttons to control volume from the ui

mostly because i failed to find any global shortcut on osx that i was able to setup:
- unable to configure "volume" or "shift"-"volum" -- cantata did not receive those keys
- i was able to configure "shift"-"arrow up" or "control"-"arrow up", but then they were not respected, browser ui took them over and scrolled content instead

**Comment by CDrummond** [comment]
Cantata only supports the media keys as global shortcuts on Mac. Sorry, but I don't have much access to a Mac to do much more.

As for adding buttons in the UI - don't see the point. You can already slide, use mouse-wheel, context menu, or assign shortcuts (tried under linux and ctrl-up/down worked (but only when Cantata has focus)).

As always, though - I would accept a pull request.

**Comment by glensc** [comment]
Yet the global shortcuts do not work. I'm not much Mac user myself to be able to troubleshoot this. As my mpd server is remote i had to ssh to linux box to run `alsamixer` to cut volume down, i thought it be much convenient to adjust volume from Cantata GUI.

and i'm unable to locate where i can slide or use mouse wheel to adjust volume. can you share screenshot of the volume controls area? Or how to enable it if it's hidden block.

**Comment by CDrummond** [comment]
There should be a volume widget (a set  of bars going from small to large) on the right-hand side. If this is not there, then its because Cantata thinks MPD has no volume control. If MPD returns a volume less than zero (usually -1) then this indicates that MPD has no volume control - hence Cantata does not show the widget. If the widget is not visible, then shortcuts will also not work.

**Comment by Upperholme** [comment]
I see the volume widget on my install, and it works (which is nice). Not sure what's meant by 'global shortcuts' or indeed 'media keys'? My Mac isn't playing the music, merely controlling MPD via Cantata. MPD is playing through an external DAC and amp connected to the MPD server. I want the volume control keys on my Mac keyboard to control the volume of sounds on my Mac, and not the volume of MPD's playback.

To set some keystrokes to control volume, Cantata's 'Shortcuts' preferences allow this, with some apparent constraints. For example I can set ^] as an 'increase volume' shortcut, but not just ]. Not sure hat the rules might be there as to what is and is not allowable.

**Comment by CDrummond** [comment]
The older KDE4 builds supported KDE's 'global' shortcuts. These are shortcuts that can be assigned and used whilst Cantata does not have focus. For media keys - this refers to the play/pause, prev, next, and stop buttons that some keyboards have. Cantata only uses these - not the volume keys.

Also, Cantata's keyboard shortcuts do not support single keys - hence you need to also use Ctrl (or Cmd on a Mac), or Alt, etc.
