### ISSUE TITLE
Enhancing the "composer support" tweak with artist displaying

### ISSUE THREAD

**Issue by pagiraud** [CDrummond/cantata#896]
The composer support tweak is very useful, at least to me, as my music library is mainly composed of classical music. Nevertheless, I think there is one weakness : when activated, the artist / album artist (that is, the performer) is not displayed at all.
As I have multiple versions of the same piece of music with different performers (14 versions of Chopin's preludes, 7 of Vivaldi's Four Seasons, 4 of Beethoven's Sixth Symphony, etc.) it is sometimes difficult to find quickly one specific performance.
So, I think a checkbox named "Append artist at the end of album title inside brackets" under the composer support textbox (where you can enter a list of styles to handle) would be a good idea. I say brackets, but that's just an idea. I think it makes more sense to place the artist after the album title in this specific case, so that all performances of a piece of music are grouped together.

**Comment by CDrummond** [comment]
The annoying thing is the code was already there to do this - probably from 1.x - but wasn't used. I've re-added this, and made some other changes for this.

**Comment by pagiraud** [comment]
Thank you very much!
