### ISSUE TITLE
Titles not scrobbling to Last.fm if album title is Unknown

### ISSUE THREAD

**Issue by valeth** [CDrummond/cantata#900]
Last.fm doesn't scrobble music tracks that have no Album tag set in cantata.

That's the case for Cantata 2.0.1 from the Arch Linux repositories.

**Comment by CDrummond** [comment]
Don't actually use scrobbling. But do you mean Cantata does not send the scrobble message, or that Last.fm rejects it (due to missing Album field)??

Run Cantata from the commandlne as follows:

`CANTATA_DEBUG=-0x00010000 cantata`

This should produce some debug about scrobbling. Does this help?

**Comment by valeth** [comment]
Here's the debug output with 2 songs.
The first one without Album tag, the second with.

[cantata-scrobbling.log](https://gist.github.com/valeth/f9b353dc82d010921be4ca76b60ebca7#file-cantata-scrobbling-log)

**Comment by valeth** [comment]
Maybe the problem is that Cantata is sending `album[0]=Unknown`, not sure

**Comment by valeth** [comment]
On a side note, :heart:ing a track works as intended.

**Comment by CDrummond** [comment]
So, it was last.fm rejecting the scrobble. Can you checkout master and try now? I've made a change which _should_ resolve the issue.

**Comment by valeth** [comment]
Just tested it, but the song does still not show up during or after playing.

There is a `Unknown error` in the reply from Last.fm

[cantata-scrobbling2.log](https://gist.github.com/valeth/568ddb19bd5459e98c4509ed68a3b042#file-cantata-scrobbling2-log)

**Comment by valeth** [comment]
looks like the track name isn't sent

`track[0]=`

**Comment by CDrummond** [comment]
Oops! Slight error on my side. Can you try again?

**Comment by valeth** [comment]
It's working now

Thank you for the quick fix
