### ISSUE TITLE
CUE files: length of the last track

### ISSUE THREAD

**Issue by pagiraud** [CDrummond/cantata#901]
When parsing cue files, the length of the last track is always "unknown" in the library view. I guess this is because track n length is obtained by subtracting the index of track n from that of track n+1. Maybe, for the last track, length could be obtained by subtracting index of track n from the whole file length.

**Comment by CDrummond** [comment]
Personally I've never used CUE files. So, could you please attach an example CUE file? Then I'll make the changes for 2.1

**Comment by pagiraud** [comment]
[cue_example.tar.gz](https://github.com/CDrummond/cantata/files/555389/cue_example.tar.gz)
Ok, I've taken some random song from Dogmazic (licence similar to Creative Commons) and adapted some cue file to work with it.
To go further with this bug report : 
- Track length is correctly displayed in the current playlist
- Album length in library view (which should be equal to the file length) is actually equal to the sum of the calculated tracks lengthes (so doesn't take last track into account)
I hope this helps.

**Comment by CDrummond** [comment]
Thanks, I'll try to look into this in the next few days.

**Comment by CDrummond** [comment]
Fixed in master - for 2.1.0
