### ISSUE TITLE
Requesting release 2.0.2

### ISSUE THREAD

**Issue by hawken93** [CDrummond/cantata#905]
There are some bugfixes, in particular https://github.com/CDrummond/cantata/commit/cef4dd96379fb2c5de8b6d853790f645895339d4
these are pretty annoying to deal with at the moment. I was able to compile on linux, but I don't think I have the right environment to build master on windows. If you build and release master as 2.0.2 I would be very happy :)

**Comment by CDrummond** [comment]
If there ever was a 2.0.2 release it would come from the 2.0 branch. master is for 2.1.0 

However, I don't have the to make a 2.0.2 release. The next release will be 2.1.0 - and this _should_ be in the next month or so.

**Comment by hawken93** [comment]
Thanks :)
