### ISSUE TITLE
Play local file on remote mpd

### ISSUE THREAD

**Issue by rbraken** [CDrummond/cantata#907]
This will fail for me because (in debug 1024) I have a 
peer: "::ffff:x.x.x.x." and mpd: "x.x.x.x"
So the socket address is a mapped IP4, and the remote mpd has a real address.
Almost the same as issue 850, but with a remote MPD.

Greetings Rene

**Comment by CDrummond** [comment]
Fixed in master - for 2.1.0

**Comment by rbraken** [comment]
Thanks for the fix.
Its working for me.

Greetings Rene
