### ISSUE TITLE
Option to ignore .m3u files in "Folders" view

### ISSUE THREAD

**Issue by emacsomancer** [CDrummond/cantata#908]
This is actually similar to issue #708 [ https://github.com/CDrummond/cantata/issues/708 ], but concerning .m3u files. When adding entire folders, currently, if the folder contains an .m3u, the tracks end up being added twice.  It would be nice to have a global option similar to the one for .cue files concerning whether .m3u files are ignored or not.

**Comment by CDrummond** [comment]
Don't want to add yet another config option. What I propose is to only use a m3u file if it has been explicitly selected. Make sense?

**Comment by emacsomancer** [comment]
So selecting a directory that contains a m3u file won't automatically use that file? That sounds excellent.

**Comment by CDrummond** [comment]
Which version of Cantata are you using? I've just tried with master - and it already works as I described above.

**Comment by CDrummond** [comment]
As stated - it already works this way.
