### ISSUE TITLE
Strangeness on Haiku

### ISSUE THREAD

**Issue by miqlas** [CDrummond/cantata#909]
Hi Guys,

i'm on my way to get Cantata working on Haiku with QT5.
The actual state: it is compiled already, but there is some bugs:
Update: patched, now works.

OS : Haiku hrev 50670 x86 gcc2h
Qt: 5.5.1

Steps:
- configured cantata with : 
```
cmake .. -Wno-dev -DENABLE_LIBVLC=OFF -DCMAKE_INSTALL_PREFIX=/boot/
home/Desktop/cantata_inst -DSHARE_INSTALL_PREFIX=/boot/home/Desktop/cantata_inst
/share -DCMAKE_BUILD_TYPE=Debug -DENABLE_QT5=ON
```
- `make` and `make install` went without problems
- started cantata, got the follwoing output in Terminal:

```
 ~/D/c/bin ❯❯❯ ./cantata 
plainFont: Regular Regular 14
monoFont: DejaVu Sans Mono Book 14
menuFont: Noto Sans Regular 14
```

and then it just exited automatically.

- tried to compile it with DEBUG enabled, doesn't helps
- tried to put some printfs here and here, and found the following code:
https://github.com/CDrummond/cantata/blob/master/gui/main.cpp#L328

If i comment the return section out, i can get the GUI.

What's wrong with this code, and why does it required?

![a600b21286b2454cb6170e3c7c5b1add](https://cloud.githubusercontent.com/assets/5569059/20039744/6a203858-a449-11e6-8910-72ccb9636a50.png)

**Comment by miqlas** [comment]
BTW it was not enough to get cantata work, it crashing at start:

In debug log i see the following:

`MpdLibraryDb init 0x185c89e8 "/library/__config_settings_mpd_socket_6600.sql" "MPD"
MpdLibraryDb init 0x185c89e8 0x18727168
MpdLibraryDb init 0x185c89e8 Failed to open`

Ofc, there is no path like that.

**Comment by miqlas** [comment]
Btw, here is my HaikuPorts recipe: https://github.com/haikuports/haikuports/pull/860

**Comment by CDrummond** [comment]
Cantata is a single-instance application. i.e. there should be only 1 instance running at a time. For Linux builds, Cantata uses DBus to ensure this. For Windows/Mac builds it uses QtSingleApplication. Does Haiku use DBus? If notm then you probably need to use QtSingleApplication. To do this you need to:

1. copy (and modify) gui/application_mac.cpp (and .h) to gui/application_haiku.cpp (and .h)
2. Edit gui/application.h to something like:
```
#ifdef ENABLE_KDE_SUPPORT
    #include "application_kde.h"
#elif defined Q_OS_WIN
    #include "application_win.h"
#elif defined Q_OS_MAC
    #include "application_mac.h"
#elif defined Q_OS_HAIKU // ??? Not sure what the def is
    #include "application_haiku.h"
#else
    #include "application_qt.h"
#endif
```
3. Edit the top-level CMakeLists.txt to compile gui/application_haiku.cpp - look around line 929

As to the path to the SQLite files, etc. You probably need to edit support/utils.cpp. Look for the Utils::dataDir and Utils::cacheDir functions. these have a #if section - e.g. `#if defined Q_OS_WIN || defined Q_OS_MAC || defined ENABLE_UBUNTU` This probably needs changing to (e.g.) `#if defined Q_OS_WIN || defined Q_OS_MAC || defined ENABLE_UBUNTU || dfined Q_OS_HAIKU` But it is these functions that Cantata uses to locate user cache and data folders.

I look forward to a pull request :-)

**Comment by miqlas** [comment]
Thanks for the info!

1) Single launch:
We got Dbus, but i don't like the idea to have yet a layer in the game. As you can see here, it is already single-launch:
https://github.com/haikuports/haikuports/pull/860/files#diff-d695ad7febadcc29290e7da0cab5aedfR2
Haiku (as like BeOS) uses file attributes to control this feature.

Proposed solution: I think we can just ifndef this section out in Cantata source. It means hovewer only the HaikuPorts builds will have this feature.

2) Cantata already found the Haiku user config folder (XDG rulez), and uses it, so if it is the same codepath, then i'm not sure, why it doesn't use the same path for the musicdb. But lemme' check it later.

**Comment by CDrummond** [comment]
**No** I don't want a #ifdef for this case. Please create an application_haiku.cpp/h file - even if it just always returns true for start(). This way it is consistent. The application files are also used to pass any arguments from a second run attempt to the currently running instance. DBus is useful for this - and is what the Linux version uses.

**Comment by CDrummond** [comment]
Any updates?

**Comment by miqlas** [comment]
I am ill, sorry, will report back asap.

**Comment by CDrummond** [comment]
Oh, sorry about that! There's no rush - was just curious :-) Hope you feel better soon

**Comment by miqlas** [comment]
I checked the sources, and already hacked an application_haiku.{c|h} together based on the application_qt files, but as i'm not a software developer, i have no idea, how can i integrate it. :S

**Comment by miqlas** [comment]
So here is it: https://github.com/CDrummond/cantata/pull/921

**Comment by CDrummond** [comment]
No updates for nearly 3 months - so closing.
