### ISSUE TITLE
Add 'Smart Playlists'

### ISSUE THREAD

**Issue by dakkusingh** [CDrummond/cantata#912]
I have a simple genre filter with an 5 star rating, but I am only getting 10 tracks max. And the tracks seems to swap / change after playback of each track.

Is this a limit / bug / feature?

**Comment by dakkusingh** [comment]
is it related to this:

https://github.com/CDrummond/cantata/blob/master/dynamic/cantata-dynamic#L42

```
$PLAY_QUEUE_DESIRED_LENGTH=10;
$PLAY_QUEUE_CURRENT_POS=5;
```

**Comment by dakkusingh** [comment]
and this:

https://github.com/CDrummond/cantata/blob/master/dynamic/cantata-dynamic#L856
```

                if ($numMpdSongs>0) {
                    # fill up playlist to 10 random tunes
                    my $failues=0;
                    my $added=0;
                    while ($playQueueLength < $PLAY_QUEUE_DESIRED_LENGTH && $numMpdSongs>0) {
                        my $pos=int(rand($numMpdSongs));
                        my $origFile=${mpdSongs[$pos]};
                        my $file=$origFile;
                        $file =~ s/\\/\\\\/g;
                        $file =~ s/\"/\\\"/g;

                        if (&checkSongRatingInRange($file, $pos)) {
                            if ($failues > 100 || &canAdd($origFile, $numMpdSongs)) {
                                if (&sendCommand("add \"${file}\"") ne '') {
                                    &storeSong($origFile);
                                    $playQueueLength++;
                                    $failues=0;
                                    $added++;
                                }
                            } else { # Song is already in playqueue history...
                                $failues++;
                            }
                        }
                    }
```

**Comment by CDrummond** [comment]
This is how the dyamic playlists works. It adds 10 songs to the queue, removes song when its played and adds another.

**Comment by Upperholme** [comment]
That's interesting to learn. I've not come across that information before. As a consequence I don't use dynamic playlists as - to me at least - it looked like they didn't work properly as I was only getting 10 results listed when I would expect more.

Also I note that in a situation where less than 10 tracks meet the criteria for the dynamic playlist, they appear to be repeated in the playlist to fill the ten places, which seems somewhat nonsensical.

In my view this approach significantly constrains the usability of dynamic playlists. For example I would find it useful to see all the tracks in my library with (for example) 5 star ratings, and then play the ones I want from that sublist.

**Comment by dakkusingh** [comment]
@Upperholme ++
Thank you for summarising a feature request that would make Dynamic Playlist an immensely useful and invaluable feature.

**Comment by dakkusingh** [comment]
Can we keep this open so we can track it accordingly as a feature request?

**Comment by CDrummond** [comment]
Dynamic playlists, and other parts of Cantata, are documented in the README.

As to having items repeated in the playlist - don't see the issue with this. The dynamic playlists repeat anyway. So if you had 100 matching tracks, eventually a track would get replayed.

However, I guess what you're after is a 'auto-populate' switch. When set to true, the playlist would behave as it currently does. When set to false, it would just add all items, I guess the feature could also be extended to set the number to add.

**Comment by dakkusingh** [comment]
Thanks Craig. 
I  am looking exactly the feature you described where I can get a list ALL 5 star tracks so I can aadd them to a non dynamic playlist (for other controllers such as MPDrpoid)

**Comment by Upperholme** [comment]
Sorry, but I can't find any of this information about how dynamic playlists are designed to work in either the README.md or README files (although I did just find this in the UI - click the link 'About Rules when creating or editing a dynamic playlist):

> After the set of usable songs has been created, Cantata will randomly select songs to keep the play queue filled with 10 entries. If a range of ratings has been specified, then only songs with a rating within this range will be used.

Consequently I based my expectations on my experience of other 'smart' or dynamic search features that I've come across (and not just with music player tools). In general, as with Cantata, I find that they work by allowing the user to define a set of search criteria and the matching results are then dynamically updated. I expect to see all of the results of my search and not just an arbitrarily constrained handful, and I don't expect the results repeated in the listing (that got me worried that there were somehow multiple copies of my file sitting in the music directory), and I don't expect them to play repeatedly unless I specifically ask for that (it looks like there's little 'repeat' button in the bottom right of the window that might control this). That's my experience and my expectations - other people may well have a different view.

Personally I'm struggling to see the benefit of the 'auto populate' feature, or the fact that it repeats tracks, or why it defaults to only showing 10 tracks, but that's just my opinion. You wrote the thing, so you get to choose how it works, and that's fine by me. 

It's a fantastic piece of software that I use daily, and like many FOSS tools that I use it could benefit from better documentation (documentation can always be improved), to which I'd be happy to contribute as I do with other projects. Should I extend the github wiki, or would you prefer an alternate approach to building out documentation?

**Comment by dakkusingh** [comment]
> I expect to see all of the results of my search and not just an arbitrarily constrained handful, and I don't expect the results repeated in the listing (that got me worried that there were somehow multiple copies of my file sitting in the music directory), and I don't expect them to play repeatedly unless I specifically ask for that (it looks like there's little 'repeat' button in the bottom right of the window that might control this). That's my experience and my expectations - other people may well have a different view.

I used to use Smart playlists in iTunes for very similar functionality - so this expected behavour described above is completely valid.

Basically:
Implement limit (if needed) into the Dynamic playlist itself. This could be a feature similar to how the rating works. You build your criteria and set a limit if you wish.

No songs match criteria : show no songs
Songs match criteria : show all songs
Songs match criteria and limit is implied in playlist : show songs as per limits

I am also happy to work on this feature and contribute back.

**Comment by CDrummond** [comment]
If you want to work on the feature - that'd be great, as my spare time for Cantata is very limited (and it is only me working on it!). However, make all changes against master.

To implement this you need to:

a. Update the dynamic rules dialog to add the 'auto update' and 'limit' settings. 'auto update' should default to true, and limit to 10 - to be backwards compatible. Use 0 for no limit.
b. Update the perl cantata-dynamic script. Currently this already stores a list of all matching tracks - it justs adds a random 10 to the playqueue. Changing the limit should be east enough. If 'auto update' is off -  randomize the list of matching tracks, then add the required amount to the playqueue.

**Comment by CDrummond** [comment]
Thinking about this more. 'Dynamic' playlists are correct as they are - after all they are named 'dynamic' so should be.

What you want is more like 'Smart' playlists. e.g. Add X number of tracks filtering on a criteria. But this is not dynamically updated - hence the term smart. I don't think these should be in the same list of playlists. It would be confusing to have them mixed. I propose that a new 'Smart Playlists' section is added. This should be similar to what is described above, but would not need to use the dynamic helper script - all functionality should be in the main C++ app.

**Comment by Upperholme** [comment]
A smart playlist approach suits me fine as that's what I want. It would also seem to be the only way to be able to view complete lists of tracks that met given ratings as I can't find any way to search by ratings currently.

**Comment by CDrummond** [comment]
The problem with ratings is that they are stored in MPD's sticker DB file. Retrieving these is very slow. TO get all songs within a rating range requires getting the ratings of **all** rated songs, and then filtering the returned list. Not very nice.

**Comment by dakkusingh** [comment]
This might sound unrelated. But perhaps its worth mentioning here.

I am almost tempted to switch to a non MPD based solution. I am fairly technical and work as a developer - BUT i am not sure i can justify the amount of time i am spending on making MPD behave like a "full" media experience offered by other players / solutions. 

I am contemplating either of these 2:
- buy a second hand netbook and run itunes on it. All of the features I need are already enabled.
- use a PI and run Logitech Squeeze Server and client on the same machine.

Dont get me wrong, MPD is great player, but I wouldnt call it "complete" but its "fun" tinkering with it.

**Comment by CDrummond** [comment]
Have you thought about plex? I'm currently experimenting with plex media server on a Pi2 outputting to chromecast audio. Plex has smart playlists. I tried logitech media server, but was not overly impressed with any of the UIs.

I must admit that I almost never use playlists - I simple add albums to the queue, and play them.

**Comment by dakkusingh** [comment]
I finally switched to Logitech Media Server + Squeezelite - It works almost flawlessly, no issues with anything so far and very minimal faffing about.

I have used PLEX exclusively for videos, but not for mobile. Might give it a go too.

**Comment by CDrummond** [comment]
Closing, No updates, no pull requests, and not something I'm going to spend time on.

**Comment by hi2u** [comment]
Awesome software!  I've tried pretty much every other Linux music player, but none of them really suited how I navigate my music etc.  I can finally replace my highly customised and complex foobar2000 config that I had to run in wine.

Pretty much everything in Cantata works exactly like I'd like it to...  just with the exception of this.  I also thought something was broken until I came across this issue thread.

I've never heard of any other player putting a limit on your dynamic playlists.  Anyway, not whinging, I really appreciate such a great piece of software overall.  I just found this part really surprising and strange.  I wonder how many people actually find this useful?

I've simply changed it to...

```php
$PLAY_QUEUE_DESIRED_LENGTH=1000000;
```
Maybe this number could instead be taken from cantata.conf instead of being hard coded? (the code could fallback to 10 if there's no setting in the config file).   Would be handy even if there's no option in the GUI to set it for now.

Now I just need to figure out how to have the playlist automatically sorted by artist/album like it is in other areas (rather than being randomly ordered).  Is that possible, even if I need to edit some code?

**Comment by CDrummond** [comment]
For 2.2.0 you can configure the size of dynamic playlists

Also for 2.2.0 I have added 'smart' playlists. These are very similar to dynamic playlists, but do not auto update, and can the chosen tracks can be sorted.

**Comment by bajidu** [comment]
Hi there, just a little additional request: Might it be possible to add ALL files to the smart playlist by setting the number in the rules dialog to 0?

I think the corresponding lines should be 342 in smartplaylistspage.cpp:

```
for (int i=0; i<command.numTracks && !songs.isEmpty(); ++i) {
        files.append(songs.takeFirst().file);
    }
```
And just check for !songs.isEmpty() if numTracks is 0?

Hope that this is feasible; right now the behaviour is that it just resets to 10 tracks whenever it is set to 0.
Thanks for the awesome software!
