### ISSUE TITLE
Build instructions for OSX?

### ISSUE THREAD

**Issue by dakkusingh** [CDrummond/cantata#913]
Hi Guys, 
I am interested in making some enhancements and implementing some features. I will create a fork and with the hope that these can be merged to the main project if deemed worthwhile.

However, do you have any instructions on how I can compile the project on OSX so I can modify and test?

**Comment by dakkusingh** [comment]
I am assuming this is what I need to do?

https://github.com/CDrummond/cantata/blob/master/README#L965

**Comment by CDrummond** [comment]
Yup, that's all I do. What features do you want to add?

**Comment by dakkusingh** [comment]
I was going to extend the rating playlist feature in the 1.5x branch so I can implement the changes we discussed here https://github.com/CDrummond/cantata/issues/912

**Comment by CDrummond** [comment]
Why the 1.5 branch?

**Comment by dakkusingh** [comment]
https://github.com/CDrummond/cantata/blob/1.5/dynamic/cantata-dynamic

**Comment by dakkusingh** [comment]
this is the build I am currently running. Is there a higher version that is ready to compile on OSX?

**Comment by CDrummond** [comment]
Well there is the 2.0 branch, and master (which will be 2.1) Both should compile for OSX. If you are going to make changes, I'd prefer you to use master.

**Comment by CDrummond** [comment]
Closing - use master for future changes, this should build on OSX. It it does not then create an issue or pull request.
