### ISSUE TITLE
No more artist images?

### ISSUE THREAD

**Issue by a-mair** [CDrummond/cantata#915]
Hi,

I'm using current GIT release (qt 5.6.1) on Gentoo Linux. Since an update one or two weeks ago I'm having problems with artist images.

I'm using grid view, grouped by artists. I used to see the artists' image, which is located in the song's parent folder, named "artist.jpg". This stopped working and in that view I'll see the artist's first album's cover.

Best regards,
Andreas

**Comment by CDrummond** [comment]
Hmmm... Was seeing this, deleted my covers to investigage, and now it is working!

Can you please try clearing your Cantata cached images? Restart cantata. Does this help?

**Comment by CDrummond** [comment]
Should be fixed now, sorry!

**Comment by a-mair** [comment]
Works again, thanks!
