### ISSUE TITLE
Add support for embedded lyrics in mp4/aac/m4a

### ISSUE THREAD

**Issue by cornelisbb** [CDrummond/cantata#923]
Title says it all and if I am correct this is supported by taglib. I use kid3 to embed my lyrics in the tags.

**Comment by CDrummond** [comment]
Easy enough to add. What is the name of the tag?

**Comment by CDrummond** [comment]
Oops - didn't mean to close!!!

**Comment by cornelisbb** [comment]
It think it is "@lyr".

**Comment by cornelisbb** [comment]
Sorry, the at sign should be the copyright sign. The tag is "©lyr". (Or "\251lyr", as I found it in the kid3 source code [however, I am not a programmer], is it the same?, and googling also found "\xa9lyr").

The tags are also listed here:

https://code.google.com/archive/p/mp4v2/wikis/iTunesMetadata.wiki

Don't know how relevant this is.

**Comment by CDrummond** [comment]
Implemented in master for 2.1.0
