### ISSUE TITLE
Can't open cue album

### ISSUE THREAD

**Issue by evm501** [CDrummond/cantata#924]
CUE album can not be opened in cantata. It works in win7 with AIMP just fine, but in cantata on Linux, it doesn't seem be correctly recognized.
![error](https://cloud.githubusercontent.com/assets/10899302/20746885/ce4f5c98-b6f8-11e6-88c2-eda66ca302f7.png)

As you see second cue album recognized well, but the first one had only one track in it with full file length.
Cantata 2.0.1 and I built version 2.0.50 - same error here.

Cue file in archive.

[Faun - Acoustic · Buch Der Balladen.zip](https://github.com/CDrummond/cantata/files/621381/Faun.-.Acoustic.Buch.Der.Balladen.zip)

**Comment by CDrummond** [comment]
Not sure what's wrong on your system - but the CUE parses fine for me.

Running cantata from the commandline as follows should produce some debug:

CANTATA_DEBUG=-2 cantata

(A negative number causes Cantata to output debug to the screen, positive is logged to ~/.cache/cantata/cantata.log. Value 2 causes MPD parsing debug to be output)

**Comment by evm501** [comment]
I built a debug version, and found out that the file is parsed correctly, but QFile::exists could not find file, because of encoding in cue file ISO 8859-15. So I converted it to UTF-8 and problem's gone. 

Thank you, anyway.
