### ISSUE TITLE
Shuffle selected tracks

### ISSUE THREAD

**Issue by bb010g** [CDrummond/cantata#925]
It would be nice if there was a `context menu > Shuffle > Selected` feature that would shuffle only the tracks selected. This is useful for things like shuffling the tracks in an album while you have other albums already in the playlist and shuffling just the remaining tracks quickly (select start > shift+end > shuffle selected).

**Comment by CDrummond** [comment]
Whilst I can see the usefulness, its more hassle than its worth. The current shuffle code is in the model - and this has no access to the selection (which is part of the view).
