### ISSUE TITLE
Set a different color scheme

### ISSUE THREAD

**Issue by ntasos** [CDrummond/cantata#926]
I don't know if it's doable, but it would be nice to have the ability to select a different color scheme instead of the one set by the DE.
If not then maybe a dark theme (I think there are some QT apps that offer different themes).

**Comment by CDrummond** [comment]
Hate it when apps do this. Apps should respect users theme. Sorry, but I'm not going to do this. Pull requests welcome.

**Comment by ntasos** [comment]
When apps force different themes I agree with you, don't like it.
But for certain apps themes is something I like.
I hope someone can implement this, I don't have the coding skills required to do this.
