### ISSUE TITLE
connection drops in windows

### ISSUE THREAD

**Issue by EdwinKM** [CDrummond/cantata#927]
I am using a dual boot laptop (Windows 8 and Fedora). 
It is running Cantata 2.0.1 but i have connection drops in Windows only.
MPD is running on a raspberry pi 3 (raspberrypi02-w.local).

It begins with starting Cantata. It tries to connect to MPD. Get the error "Failed to send command to "raspberry" (raspberrypi02-w.local:6600) - not connected"
If i press "connect" again it works.
The "connection drop" ONLY happens at the end of the songs (switching to the next song).
I get the "Connection to "rasp
[cantata.txt](https://github.com/CDrummond/cantata/files/637849/cantata.txt)
berry" (raspberrypi02-w.local:6600) failed bar. I have to press "connect" two times to reconnect.
Included a debug.log of this session.

When i manually forward to almost the end of the song. And it switches to the next song i get no error. 
I get also a drop when i forward/rewind the track (only *after* a minute idle running; do not see anything logged about this)
So it seems a idle/timeout issue?

I tried a Wired en Wireless connection (laptop only). The same results.
Tried running Cantata in Virtualbox Windows XP. This has no issues.
Also tried running Cantata in Fedora using Wine. This has also no issues.

**Comment by CDrummond** [comment]
Looks like an issue with your system. The connection code is 100% the same for Linux, Windows, and Mac. If there is an issue, then its with Qt (which I doubt)

**Comment by EdwinKM** [comment]
You are probably right. I have some weird connection issues. Will investigate further.
