### ISSUE TITLE
Problem while dragging the main window

### ISSUE THREAD

**Issue by peterLaurence** [CDrummond/cantata#928]
Hi,

Thanks for your awesome player. I have a problem on Ubuntu 16.04, Cantata 2.0.1 installed with the AppImage you mention in the release page.

If i drag the window by clicking in the menu bar (see illustration below, the red dot is where is click), the window blinks and jumps at different positions of the screen. 
![ko](https://cloud.githubusercontent.com/assets/15638794/21072519/3373b77a-bec6-11e6-9a09-7d9de058c40b.jpg)

But if i click in the title bar (see below), there's no issue.
![ok](https://cloud.githubusercontent.com/assets/15638794/21072521/4d20ea26-bec6-11e6-8df2-442beadd894c.jpg)

**Comment by CDrummond** [comment]
Which version of Cantata? 1.5.x? 2.0.x? Qt4? Qt5? Running under Unity?

**Comment by peterLaurence** [comment]
Cantata 2.0.1, under Unity.
As of Qt, i'm not really sure as i have tested both the AppImage from Thomas Leitz, and a version from this [ppa](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata-qt).
I know this is Qt5.x but i don't know exactly the version.
Both had the issue described.
Hope that helps.

**Comment by CDrummond** [comment]
Then not sure why it affects you, 2.0.1 works fine under Unity 16.10 for me. Ho come your screenshot has the menubar in the Cantata window?

**Comment by peterLaurence** [comment]
The screenshot were made with Cantata from the AppImage, but the version from the ppa, which i am using right now, doesn't have the menu bar visible (its in the title bar and it appears only if i hover it).
But the issue is still happening if i drag the window with a click _under the title bar_.

**Comment by CDrummond** [comment]
Might be a X driver issue - I've seen it act odd under VirtualBox (but that also has other non-Cantata issues).

I'm thinking that perhaps the Gtk theming, and window dragging should be removed...

**Comment by peterLaurence** [comment]
> I'm thinking that perhaps the Gtk theming, and window dragging should be removed...

Yes, most softwares (at least on ubuntu) allow dragging only from the menubar.

**Comment by CDrummond** [comment]
Well, actually Ambiance originally allowed dragging from the toolbars as well - hence its unified look. Its only since the introduction of GtkHeaderBars that the drag from toolbars no longer works (which I think is a Gtk bug).

**Comment by CDrummond** [comment]
Removed window drag code for Gtk
