### ISSUE TITLE
More info about custom actions on OSX

### ISSUE THREAD

**Issue by EReckase** [CDrummond/cantata#931]
I've tried everything I can think of to get custom actions to work on OSX. I'm running Cantata 2.0.1, connected to my MPD server without problems and music plays fine. I've tried making custom actions like:

`echo "%f" > /tmp/foo.txt`

...but nothing seems to happen. Do I need to escape anything in the string used for the command?

**Comment by CDrummond** [comment]
To be honest, no idea when it comes to the Mac. Cantata is developed primarily for Linux - I ported to Windows/Mac just to see how easy it would be.

Your command above will not work as it redirects the output - this is not supported. Basically the **only** commands that will (probably) work are those that you can start from a commandline.
