### ISSUE TITLE
Crossfade button

### ISSUE THREAD

**Issue by frdrcv** [CDrummond/cantata#932]
It would be great to add a button enable/disable crossfade between songs. I only use this option when playing random songs; for exemple, it would be useful to desactivate crossfade when listening to a specific album. Opening the configuration panel just to activate the option is quite annoying for something that can is used only in specific contexts in my case. I guess others could find this option pertinent too. Thanks!

**Comment by CDrummond** [comment]
Nope, cross fade is not an on/off item
