### ISSUE TITLE
Problem connecting to a remote mpd server

### ISSUE THREAD

**Issue by manuvazquez** [CDrummond/cantata#933]
Hi,

I'm trying to use Cantata to play songs in a remote computer. In the "Collection settings" dialog, I set up the the host name, the port (to 6600) and left the rest of the fields blank. When I click apply, I get "Connection failed". I tried "ncmpc" and it works just fine, so it shouldn't be a problem with my server's setup.

Any clue? I'm using Cantata 2.0.1 in Gentoo Linux.

Cheers.

**Comment by CDrummond** [comment]
I always run remote - my MPD is on a Pi, and I connect from my laptop. Just tried, and is working for me. Sorry, but this looks like an issue with your system.

**Comment by manuvazquez** [comment]
Just for future reference...it's working now. You were right. The problem was that I was using a hostname without domain, and it seems Cantanta does not resolve it the same way ssh does. Using the IP did the trick.
