### ISSUE TITLE
Lyrics and undivided CUE files

### ISSUE THREAD

**Issue by zluca** [CDrummond/cantata#935]
Once lyrics loaded for one track from album, it will displayed for every song in this album. On this screen you can see text from "Do you want to know a secret":
<img src="http://imgur.com/HxRGtpQl.png" />

I found that it only work for undivided albums. And if option "Save downloaded lyrics in folder" is active.
This what happens in folder:
<img src="http://imgur.com/mQTxBxVl.png" />
And even after unchecking option, manual deletion of .lyrics file is needed to make all stuff work properly.

**Comment by CDrummond** [comment]
This is due (yet again) to cue files. Cantata uses the tracks filename (which changed extension) to save the lyrics. For cue file tracks, the easiest way is going to be to disable saving lyrics to music folder.

**Comment by zluca** [comment]
> it always uses the same name as the music file

But you can change this behavior, isn't u? For example: track# - track-name.lyrics

Or, if it takes too much work just add a few lines in readme. 😃

**Comment by CDrummond** [comment]
I'm not going to change the behaviour - as it works for me.
