### ISSUE TITLE
Rendering problems of Preferences under Wayland

### ISSUE THREAD

**Issue by KAMiKAZOW** [CDrummond/cantata#936]
Switching pages in the Preferences window sometimes does not draw the contents and moving the mouse causes heavy flickering.

Cantata is running as native Wayland application using
cantata -platform wayland

Setup: Fedora 25 with all available updates (GNOME Shell 3.22.2, Qt 5.7.1),

**Comment by CDrummond** [comment]
Well, I guess that'd be a Qt issue. Cantata is using Qt to draw the preferences window - the only custom code is in the left hand page selector.

**Comment by CDrummond** [comment]
Just installed Fedora 25 in a VM - and yup, pretty messed up. Main window also has similar issues when changing views.

However, I also tried QtCreator - and whilst not as bad, it also exhibited similar behaviour.

Looks like Qt is not full refreshing when a QStackedWidget changes. Anyway, Qt issue.
