### ISSUE TITLE
Cantata closes connection when song is changed

### ISSUE THREAD

**Issue by SethosII** [CDrummond/cantata#937]
The connection to the MPD server is lost when the next song is played. `Connection to ... failed - please check your proxy settings` is the message I get from Cantata. Trying to reconnect also fails but closing and opening Cantata lets me reconnect to the server until the next song is played. It also ocassionally loses the connection when doing other stuff.

The mpd.log only says `Dec 21 10:45 : client: [19] closed` and I couldn't find a Cantata log. I also tested with GMPC and it doesn't show this behaviour so I think it's a problem with Cantata.

MPD: 0.19.1 on Raspbian Jessie
Cantata: 2.0.1 on Windows 10

**Comment by CDrummond** [comment]
If you are seeing 'please check your proxy settings' then Qt is raising errors due to proxy usage. Are you using a proxy? Is MPD local? Do you need to use a proxy to access it?

**Comment by SethosII** [comment]
Yes, I'm using a proxy, but this is not needed to access the MPD server. I disabled the proxy and the issue is gone, so I added the address to the exception list. Is there a specific issue with proxy handling?

**Comment by CDrummond** [comment]
Cantata is just using Qt's socket classes - if there is an issue it /might/ be there. I've never used Cantata via a proxy. However, the code to detect proxy issues must have been added as another user was using proxies - and I assume now has it working.

Sorry, but not much I can do here.
