### ISSUE TITLE
Edit tags: track number in genre

### ISSUE THREAD

**Issue by a-mair** [CDrummond/cantata#939]
Hi,

I'm using latest GIT release and in the "Edit tag information" window the "Genre" text field shows for example "Classic Rock, 9". "9" is the song's track number. The MPD database entry for this song looks like this:
...
Track: 09/09
Date: 1970
Genre: Classic Rock
...

I guess that's a bug, can you confirm this?

Best regards,
Andreas

**Comment by CDrummond** [comment]
Oops! Thanks for reporting, fixed now!
