### ISSUE TITLE
Feature request: Middle button and mouse wheel over the tray icon

### ISSUE THREAD

**Issue by manuvazquez** [CDrummond/cantata#940]
I don't know how hard it is to do this but...it would be nice to play/pause the music just by middle clicking in Cantata's tray icon, and change the volume using the mouse wheel (I'm coming from good old Amarok and that was quite handy).

**Comment by CDrummond** [comment]
Cantata already supports this. However, this appears to be broken under Plasma/Unity.

Unity does not seem to generate the relevant signals.

Plasma - mouse wheel signals not emitted. Middle-click is generating a 'QSystemTrayIcon::Context' activation and not 'QSystemTrayIcon::MiddleClick' So, the middle-click appears to be a KDE issue.

**Comment by IlyaIndigo** [comment]
> Plasma - mouse wheel signals not emitted.
Sonata and kmix work in KDE4.

**Comment by CDrummond** [comment]
And? As I said the code did work, doesn't seem to now - no idea why. Its not a feature I use, if you are interested in bringing it up to date the code is in gui/trayitem.cpp

I no longer have a KDE4 setup - so no way I could check.
