### ISSUE TITLE
Feature Req: Filters in 

### ISSUE THREAD

**Issue by benjamindaines** [CDrummond/cantata#946]
Would be nice to have the ability to filter by genre from with in album grid library view.  I would like to be able to primarily by genre, which would give me the ability to only browse my classical music when that's all I want to see.  

Sorting by genre with the current implementation will not allow me to browse by albums, only by album artist under the genre.  This really doesn't work with classical music.  Browsing by composer tag would be much better, but the best would be to just show me all the album covers. 

Thanks

**Comment by notbinc** [comment]
I just started using cantata and this is the only feature I really miss from gmusicbrowser.

Not only genre but also limiting the gridview to a specific directory (say Classical/ or Jazz/ in the root of the mpd directory) would be immensely useful.

**Comment by CDrummond** [comment]
The Cantata 1.x genre combo is already back in for master (2.1.0). This allows you to filter artist and album views based on genre.

I have no intention of adding filter by directory - use the folders view for this.

**Comment by notbinc** [comment]
Is it ok if I do it and do a pull request?

It is very useful to create subcollections. Note that the search tab already does it so we only need to allow this filtering in the grid tab.

**Comment by CDrummond** [comment]
Well, you can certainly do a pull request. But, where would you put the filter? There's a search bar at the top, and the genre combo is now on the bottom of the view. Adding another filter would add visual clutter.

**Comment by notbinc** [comment]
Do it as in gmusicbrowser: use the same search bar which appears after hitting Ctrl+F and search specific fields with genre:Classical and file:Jazz/ etc. There's no need to have a bottom tab with genres/other filters.

**Comment by CDrummond** [comment]
Rather then having to type "genre:Classical" I'd prefer to have a drop down of all the fields, as per the search page. Having to type in the field name makes the list of names hidden.

As to the genre combo - this give an easy and quick way to know the list of genres available. It was added back due to user requests.
