### ISSUE TITLE
Preselect most used option

### ISSUE THREAD

**Issue by ShalokShalom** [CDrummond/cantata#947]
Cantata preselect currently the option, to setup it with a dedicated server instance, while the majority of users dont even know, what that means. They simply want to play music on their computer:

![screenshot_20170108_083632](https://cloud.githubusercontent.com/assets/6344099/21748160/b8683a50-d57d-11e6-8fe9-277088e0a6f4.png)

**Comment by CDrummond** [comment]
Most used option **is** pre-selected. MPD is mainly used system-wide, or on another machine.

**Comment by ShalokShalom** [comment]
And you know that why?

**Comment by CDrummond** [comment]
And you know otherwise why???? Because its the way **you** want it???

Cantata is **my** project - coded **solely** by **me**. Don't like it - then there are **plenty** of other clients.
