### ISSUE TITLE
Use a folder on a different partition

### ISSUE THREAD

**Issue by ShalokShalom** [CDrummond/cantata#948]
How to use a different folder/partition on the same hard drive?

Every time when i add a new collection, appears the dialog to setup a network connection:

![screenshot_20170108_094840](https://cloud.githubusercontent.com/assets/6344099/21748540/c2378284-d587-11e6-9205-2f27247de8d4.png)

**Comment by ShalokShalom** [comment]
This happens, when i try to connect via localhost:6600

![screenshot_20170108_095153](https://cloud.githubusercontent.com/assets/6344099/21748560/248168e2-d588-11e6-8708-93efe9c475be.png)

**Comment by CDrummond** [comment]
Please learn how to use and configure MPD

**Comment by ShalokShalom** [comment]
Learn how to offer a GUI, which is usable.
