### ISSUE TITLE
Add support for embedded lyrics in Opus

### ISSUE THREAD

**Issue by bb010g** [CDrummond/cantata#951]
Followup to #923. They're visible in the metadata view under Lyrics, but not in the Lyrics view proper.

**Comment by CDrummond** [comment]
I have no opus files - so cannot test. Which tag is used for lyrics?

**Comment by bb010g** [comment]
I'm currently using master (via `cantata-git` on the AUR). A decent test is to convert anything with ffmpeg & `-map_metadata 0` that already has lyrics, or use Kid3 to tag a fresh Opus file.

**Comment by CDrummond** [comment]
The issue was that Cantata's CMake files were not detecting if TagLib had opus support. Should be fixed now.
