### ISSUE TITLE
Play next action

### ISSUE THREAD

**Issue by padertux** [CDrummond/cantata#952]
I would like to add a play next action in the playlist context menu that moves a selection of songs from the playlist under the currently played song. I often want to play a certain song from my playlist next without stopping the current song. Having an action for that would make that much easier than using drag and drop and scrolling in the playlist.

Is that something you would accept a pull request for?

**Comment by padertux** [comment]
Just created pull request #953. Feature was easier to implement than expected.

**Comment by CDrummond** [comment]
Thanks implementing this :-)

**Comment by smirkybg** [comment]
Is there a way this feature could be improved in a way that works also with shuffle mode on?
