### ISSUE TITLE
support of downloading cover from http server running on machine with mpd server

### ISSUE THREAD

**Issue by mistepien** [CDrummond/cantata#954]
This is quite easy to set http server together with mpd server, just to serve covers. MPD pushed to clients tag "file" with relative path to music_directory. HTTP can serve music_directory and then client can demand from http server folder.jpg in "file" path. Any way it works great in android client, like mpdroid, mpc control or mupeace.

**Comment by CDrummond** [comment]
In Cantata's settings, specify the HTTP URL as the Music folder.  see: https://github.com/CDrummond/cantata/blob/master/README
