### ISSUE TITLE
support for avahi

### ISSUE THREAD

**Issue by mistepien** [CDrummond/cantata#955]
mpd can be (and usually is) built with avahi. it would be great to have in cantata, what for to manually set connection if it can be done automagically?

**Comment by CDrummond** [comment]
Sounds like a reasonable idea - I look forward to the pull request :-)

**Comment by CDrummond** [comment]
No pull request? Then closing.

**Comment by alphapapa** [comment]
Have you considered leaving feature requests like these up and tagging them "help wanted"?  It may help potential new contributors to see "low hanging fruit" ideas that they could work on.  It also helps avoid duplicates, as someone else may come along and make the same request in the future.

**Comment by mistepien** [comment]
On 03/04/17 20:43, CraigD wrote:
> No pull request? Then closing.
> 
I'm not programmer, just user so I can not write the code.

**Comment by bb010g** [comment]
I'm with @alphapapa on doing some sort of "external patch friendly" tag. It's still a valid issue, and one you'd appreciate a patch for.
