### ISSUE TITLE
Playlist with brackets not recognized

### ISSUE THREAD

**Issue by indiana-horst** [CDrummond/cantata#956]
Hello,

I'm using (static) playlists with brackets and empty spaces in their names. 

Example: [radio streams]

I'm doing this, because the android client MPDroid is using this format for his streaming section. 

Problem: Cantata doesn't show playlists starting with a bracket and a empty space in the name. All other tested mpd clients show this very playlist: GMPC, Ario, xfmpc, etc. 

Cantata does not.

Please fix this. Thanks!

**Comment by CDrummond** [comment]
[Radio Streams] is used to hold radio streams - and is shown in the internet section. This was implemented in Cantata and MPDroid by me :-)   This is a *special* playlist - and is not listed with the others, but in Internet/Streams/Favourites

Your problem statement "Cantata doesn't show playlists starting with a bracket and a empty space in the name" is incorrect. I have just created:

[One Tow]
(Three Four)
{Five Six}

...and all 3 are created and displayed.
