### ISSUE TITLE
Filter/search input field for current playlist

### ISSUE THREAD

**Issue by WiseLord** [CDrummond/cantata#958]
Currently search function allow either replace playlist with found item or append to current playlist. It would be nice to have one more option for found item - if it already exist in playlist, play it without appending the duplicate.

Also it could be implemented by adding one more input filter field at the top/bottom of playlist.

P.S. I've just switched to Cantata/MPD from Amarok and really miss this feature.

**Comment by CDrummond** [comment]
Your title and description seem to disagree. There is already a filter/seach for the playqueue (which is the current playlist). Ctrl-Shift-F by default.

As to adding another entry to the 'Add to playqueue' menu item - not sure about this. It is already overcrowded.

**Comment by WiseLord** [comment]
Thanks for Ctrl-Shift-F hint. It's really what I needed.
