### ISSUE TITLE
A podcast (Bad Voltage) won't play

### ISSUE THREAD

**Issue by Moondownr** [CDrummond/cantata#961]
Hi,

I've recently decided to replace gpodder with Cantata. All the podcasts I subscribe to seem to work fine, except for Bad Voltage, which wouldn't play (neither mp3 nor ogg feed). Steps to reproduce:

1. Subscribe to BV in Cantata via iTunes, gpodder or direct link (doesn't matter).
2. Try to play any episode.
3. Playback doesn't start.

Downloading an episode works and produces a file in ~/Podcasts, that can played by any player without problems.

**Comment by CDrummond** [comment]
Should be fixed now - and appears to be for me. Can you checkout git/master and confirm?

**Comment by Moondownr** [comment]
Yep, works in git version. Thanks, will be waiting for update in the ppa.

**Comment by CDrummond** [comment]
Thanks for the confirmation.
