### ISSUE TITLE
Edit track informaton grayed

### ISSUE THREAD

**Issue by majkinetor** [CDrummond/cantata#962]
This happen with every library track ? Am I missing something ? 

Running latest version on Windows.

**PS**: I created chocolatey package for cantata. See https://chocolatey.org/packages/cantata/2.0.1. It is automatic package and will follow your github releases within a single day. You can install cantata on Windows with `cinst cantata` and any future version with explicit `--version` tag.

**Comment by CDrummond** [comment]
If this item is disabled, then Cantata cannot access the music folder. In Cantata's 'Collection' section of the preferences dialog, there is a 'Music folder' setting. This should be set the the locally accessible folder. Not sure how you have MPD configured, the following example assumes you have MPD on a raspberry pi (or NAS):

1. Music stored in (e.g.) /home/pi/music  - with MPD's music_directory setting set to this.
2. On the windows PC, /home/pi/ is mapped to P:
3. Then in Cantata you would set 'Music Folder' to P:\music

What happens is that MPD only tells Cantata part of a music tracks path - the part under music_directory. e.g. If you had /home/pi/music/SomeArtist/SomeAlbum/Tack1.mp3 then Cantata only sees SomeArtist/SomeAlbum/Tack1.mp3 To get the absolute path, it takes what you enter in 'Music folder' and appends the path sent by MPD. So, 'Music folder' = P:\music MPD sends 'SomeArtist/SomeAlbum/Tack1.mp3' then Cantata would think the full path is P:\music\SomeArtist\SomeAlbum\Tack1.mp3 if P:\music\ is not accessible to Cantata, the menu item is disabled.

**Comment by majkinetor** [comment]
That works,  it was not obvious from the description bellow the field where it says it is used to get the cover art hence I didn't set it.

Thanks.

**Comment by CDrummond** [comment]
Fair point - note updated.
