### ISSUE TITLE
Youtube service

### ISSUE THREAD

**Issue by majkinetor** [CDrummond/cantata#963]
I was looking at the #835 and with `youtube-dl` it works for me, without any problem, both for longer and shorter videos.

Example song:

- Asha Puthli - Asha Puthli [FULL ALBUM] (36:17)  
https://www.youtube.com/watch?v=VD4SKAQ7fFM

```powershell
#Get the stream URL
PS> youtube-dl -g https://www.youtube.com/watch?v=VD4SKAQ7fFM 
```
https://r5---sn-uxax3vhgn-cxbz.googlevideo.com/videoplayback?ip=178.221.186.12&key=yt6&pl=18&mm=31&mn=sn-uxax3vhgn-cxbz&ipbits=0&ms=au&mt=1487535569&gir=yes&initcwndbps=1070000&upn=jjZ0FqzAG7w&lmt=1474102667452801&ratebypass=yes&clen=73153307&source=youtube&mv=m&mime=video%2Fmp4&itag=18&expire=1487557279&id=o-ABEXHvlBHQfHl503donQlPycibjreI5bvYGGy8aidsBC&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&beids=%5B9452307%5D&requiressl=yes&ei=P_6pWJeAFcu3Wa7inPgN&dur=2177.335&signature=2C2ABAFBE9D70483E424B77FA8CB1C63491D47AB.1B51353B573D4DD761703FED6CA4A9558FCD302B

When I add above URL via _Add Stream_ it works just fine:
![untitled](https://cloud.githubusercontent.com/assets/85767/23106167/9cca9bde-f6e9-11e6-88da-aa036d02da05.png)

Youtube-dl even gives array of streams for youtube playlists.

**Comment by majkinetor** [comment]
I do wonder tho why I can't add stream to favorites and give it a name AFTER it is already added. I thought perhaps drag&drop to Favorites icon would work seeing that there is no 'add to favorities' button.

**Comment by CDrummond** [comment]
Sorry, but that URL does not work for me - neither in Cantata nor GMPC.

Why would I want to add a stream to favourites without giving it a name? Favourites is for radio streams - not single song URLs.

Anyway, as stated this is not working for me. However, should you wish to add YouTube search and playback, feel free to create a pull request of your implementation.

**Comment by majkinetor** [comment]
> Sorry, but that URL does not work for me - neither in Cantata nor GMPC.

Maybe it is something location specific. Perhaps trying above command on your own system to get the stream ? Or it might be MPD version specific. I just tried in ympd and it also worked.

Here is my relevant MPD info shown in _Server Information_:

Protocol: 	0.19.16
Handlers: 	alsa, cdda, gopher, http, https, mms, mmsh, mmst, mmsu, nfs, rtmp, rtmps, rtmpt, rtp, rtsp, smb

**Comment by majkinetor** [comment]
The link stopped working for me too. I guess static stream URLs wont work and it needs to be determined on each play.

**Comment by CDrummond** [comment]
Closing - I have no intention of implementing this (pretty sure it's against YouTube terms), and I've yet to receive any pull requests...
