### ISSUE TITLE
Consume button

### ISSUE THREAD

**Issue by psamim** [CDrummond/cantata#966]
Hi,
What does the "consume" button do at the bottom of the screen?
Thanks,
Samim

**Comment by CDrummond** [comment]
This is for bug reports - not MPD general help. In future please consult the MPD documentation.

If consume is enabled, a song is removed from the playqueue after it is played.

**Comment by psamim** [comment]
Sorry I thought it was Cantana specific, not MPD, thanks for the answer. My
fault.
