### ISSUE TITLE
Enhancement Request: Center On Current Track should select current track

### ISSUE THREAD

**Issue by asdfffdsa** [CDrummond/cantata#970]
I like the "center on current track" shortcut but it would be nice if doing so selected the current track in the Play Queue UI.  I often use cantata purely with my keyboard (the mouse is attached to a VM) but I can't really interact with the current track in cantata UI unless there's a quick way to select it.  Also, the track that's selected in the UI gets reset to the first track in the play queue when I alt-tab away from the Cantata UI for a while.

**Comment by CDrummond** [comment]
Not sure I like the idea of this. Don't think UI should change selected. Also, selection does not change for me when I alt-tab.
