### ISSUE TITLE
Composer support doesn't work if track is tagged with multiple genres

### ISSUE THREAD

**Issue by pagiraud** [CDrummond/cantata#973]
Steps to reproduce : 
1. Add several genres in the composer support field (e. g. Classical,Romantic)
2. Add a track tagged with some of these genres in your library (Classical\\Romantic)

What happens : in the library view, the tag is listed under the artist field.

What should happen : the composer support tweak should apply.

Not sure what behaviour should prevail if the track is tagged with various genres (e. g. Classical\\Romantic\\Vocal) whose only some (e. g. Classical,Romantic) appear in the composer support field.

Thanks for this awesome software.

**Comment by CDrummond** [comment]
What is "Classical\Romantic" ??? I assume its two genre tags - does MPD report each tag? Cantata shuld support up to 4 (I think) genres per track. (This might only be in master). But the genres need to be sent separately from MPD.

Try: 

1. Open a terminal
2. Connect to MPD with telnet (assuming MPD is on localhost with socket 6600)
    `telnet localhost 6600`
3. Get MPD info for a track - e.g. MPD music_directory is /var/lib/mpd/music, and the track path is /var/lib/mpd/music/Artist/Album/Track.mp3, then type:
   `lsinfo 'Artist/Album/Track.mp3'`
4. MPD should respond with something like:
    > file: Arist/Album/Track.mpd
    Last-Modified: 2015-01-01T01:01:01Z
    Time: 123
    Title: Wibble
    Artist: Wobble
    Album: Blah
    Date: 2001
    Track: 1
    Genre: Rock
    Genre: Classic Rock
    OK

Here there are 2 genres. Does this match with what you see?

Which version of Cantata are you running? Can you try git/master?

**Comment by CDrummond** [comment]
Just tried creating 2 Genre tags in a set of MP3s, and composer grouping **does** work
