### ISSUE TITLE
Only last artist tag is displayed

### ISSUE THREAD

**Issue by pagiraud** [CDrummond/cantata#974]
Steps to reproduce : 
1. Tag a track with various artists (e. g. foo\\bar\\dead\\beef)
2. Add this track to your MPD database

Expected behavior : track appears with a list of artists (e. g. foo, bar, dead, beef or even better foo, bar, dead and beef)

Observed behavior : only last artist of the list is displayed but you can find track by searching for any of the listed artists.

**Comment by CDrummond** [comment]
Yup, that's the way it is
