### ISSUE TITLE
No shortcuts without media keys?

### ISSUE THREAD

**Issue by drtebi** [CDrummond/cantata#975]
Hello,

I am a big fan of Cantata and appreciate your hard work. But what has always irritated me is, that I cannot use familiar shortcuts, e.g. pausing a song with the space bar. I just read about the media key integration, well, my keyboard doesn't have media keys... I am on Arch Linux, running a non-Gnome, and a non-KDE system (Enlightenment), so I have to wonder... is there any hope for me to somehow get some keys to do some smart things? Any startup scripts, Qt settings, anything would really help...

Thanks,
DrTebi

**Comment by CDrummond** [comment]
The master branch of git (for 2.1.0) supports single key shortcuts - so space for play/pause now works.

Please look at previous issues (even closed) before reporting new ones - as this has been reported before (and now fixed).
