### ISSUE TITLE
Enhancement request: better support for dark desktop themes

### ISSUE THREAD

**Issue by rrthomas** [CDrummond/cantata#976]
I use Cantata under GNOME 3's Dark theme. Qt in general copes well, but some extra support is needed for custom widgets (at least, that's how it looks in various apps). Menus & dialogs are fine in Cantata, but the text color in the Library view, playlist &c. is fixed to black (so is barely readable on a dark-grey background) and the right-hand pane has a white background (which glares rather).

I'm using cantata 2.0.1.

**Comment by CDrummond** [comment]
Which theme? As the colours are **not** hard-coded. These colours 100% come from the theme. The **only** colours that *might* have issues are the toolbar text, volume control, and monochrome icons - as these are set initially - but again from the theme, if the theme delays the setting or later changes them then they will break.

Sorry, but issues with list item colours is a theme issue.

**Comment by rrthomas** [comment]
Thanks, I'll investigate. I'm using Adwaita with the GNOME "Global Dark Theme" setting. If I switch off my personal customisations, then Cantata simply doesn't go dark at all. (My customisations add a dark Adwaita theme for GNOME 2.)

**Comment by rrthomas** [comment]
Sorted (with a better configured Adwaita Dark gtk2 theme); thanks!

**Comment by CDrummond** [comment]
The adwaita I was mentioning is a pure-Qt theme - see adwaita-qt. I guess what you are using is a Gtk2 themve via Qt's QGtkSyle (this loads Gtk in the background, paints Gtk widgets off screen, and copies the pixmaps onto where the Qt widgets are). I'd highly recommend using Adwaita-Qt

**Comment by rrthomas** [comment]
Thanks for the tip. I'd never managed to get it to work, but maybe it's time to have another go.

**Comment by rrthomas** [comment]
Done. Thanks again!
