### ISSUE TITLE
Enhancement request: set length of dynamic playlists

### ISSUE THREAD

**Issue by IvanSanchez** [CDrummond/cantata#978]
I enjoy dynamic playlists quite a lot. But the length of the dynamic playlists is limited to 10 items (this seems to be [hard-coded in `cantata-dynamic.pl`](https://github.com/CDrummond/cantata/blob/2.0/dynamic/cantata-dynamic#L42).

I would like to be able to set the length of dynamic playlists, ideally on a per-playlist basis. I guess this would involve:

- [ ] Add UI for this in the dynamic playlist editor modal window
- [ ] Save the playlist length next to the playlist's rules
- [ ] Make the perl script use the supplied value

**Comment by CDrummond** [comment]
Why? What benefit would there be? Sorry, but not going to happen.

**Comment by IvanSanchez** [comment]
It just makes the playlist look half-empty when having the Cantata window maximized, and I would enjoy more options to jump to a "random" song when looking at it.

I understand that the benefits are marginal for other use cases, so no big deal.
