### ISSUE TITLE
Enhancement request: keybindings for song ratings

### ISSUE THREAD

**Issue by IvanSanchez** [CDrummond/cantata#979]
I used Amarok in the past, and there is one Amarok feature that I miss having in Cantata.

Currently, track ratings (0.5-5 stars) can only be set with the UI, clicking on the 5-stars in the upper-right corner.

I would like to have **global keybindings** for setting the track ratings. Allow me to change the rating of the track without having to switch windows. I can currently use my keyboard media keys for play/pause/next, so from a UX point of view it makes sense to use just the keyboard for other actions related to the currently playing track.

I suggest using the same behaviour as in Amarok: `Meta+1` (or `Win+1`) for cycling between `0.5` and `1` star, `Meta+5` for cycling between `4.5` and `5` stars (and idem for `Meta+2`, `+3` and `+4`).

**Comment by CDrummond** [comment]
Sorry, not going to happen. At least I have no intention of implementing this - and not 100% sure how it would be done anyway. Can't use Amarok's method - as Cantata is a pure Qt5 app. KDE is only supported for KDE4, and this is legacy.

Feel free to submit a pull requst though.
