### ISSUE TITLE
Enhancement: simple view

### ISSUE THREAD

**Issue by ikarus13** [CDrummond/cantata#981]
Hi,
it would be nice if cantata has a feature to show just a simple (with nice backgrounds) screen for example with cover, title and next title when playing.
The usecase: I am sitting 3 m from my Notebook away and would like to see what title is playing or just recognize the album cover.

Thanks,
ikarus

**Comment by CDrummond** [comment]
I'm sure there are other MPD clients that could achieve this - and you can use more than 1 client at a time.

Sorry, but this is not something I'm interested in spending time to implement. As always, patches / pull-requests welcome,

**Comment by ikarus13** [comment]
Thanks,
any suggestions for such a programm?
I searched for it, no results.
Greetings,
ikarus

**Comment by ikarus13** [comment]
Hi,
found it myself. Sonata supports a fullscreen-cover and title view.
So i have to run both, cantata (for using dynamic rules) and sonata for the full-screen view.

Greetings,
ikarus
