### ISSUE TITLE
Info Tab incorrectly displays Samplerate and Bitrate for high bitrate flac ( perhaps others )

### ISSUE THREAD

**Issue by mwk1000** [CDrummond/cantata#983]
Still present in latest git pull ... Been this way for years but I thought I would ask.

Here is a 192KHz flac  Bitrates should be in the 5K range Samplerate variable is not big enough maybe unsigned int .... just guessing.
Typical display 
Bitrate: 
6 kb/s
Sample rate: 
60928 Hz
Channels: 
2
Bits: 
24

**Comment by CDrummond** [comment]
Was using a 16-bit unsigned for this, changed to 32-bit. Can you update master and confirm if this fixes the issue? Thanks.

**Comment by mwk1000** [comment]
Wow that was fast Thx , Yes I will give it a go and let you know.

**Comment by mwk1000** [comment]
You the man !

 

Driving me nuts for years :)

**Comment by CDrummond** [comment]
Well, it was an easy fix! Perhaps in future, report issues earlier? :-)
