### ISSUE TITLE
Frequent disconnection with git version

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#986]
The other day I upgraded from 2.0.2 to 2.0.50, and ever since then I've been experiencing frequent disconnections from my MPD server, which is on the same LAN. It may be a coincidence, but it seems odd. My SSH connections to the same server aren't dropping, and I haven't seen any problems with my local network. Did anything with the networking code change? Lower connection timeouts or something like that?

**Comment by CDrummond** [comment]
There is no 2.0.2 - I assume you mean 2.0.1 :-)

There have been some changes, but the main change is that Cantata will communicate with MPD at least once every 5 seconds - to ensure the connection is still alive. The command time-out has also been lowered - perhaps this is your issue?

Try editing mpd-interface/mpdconnection.cpp and change line 67 from:

static const int constSocketCommsTimeout=250

to:

static const int constSocketCommsTimeout=1000

Does that help?

How often are you getting the disconnections? After X minutes? Every X seconds?

**Comment by chowbok** [comment]
It seemed to have been at random intervals. Since upgrading, I've not seen a disconnect. Perhaps it was just a coincidence? I'll close this and let you know if I start seeing it again.

**Comment by chowbok** [comment]
I was seeing it again... disconnections at seemingly random intervals but averaging around every ten minutes. I set "static const int constSocketCommsTimeout=1000" and this helped tremendously, but it still disconnects from time to time, usually when loading a large playlist.

**Comment by CDrummond** [comment]
What is a large playlist? Is your MPD on the same machine, on the same network, elsewhere?

Please create a log file showing when the error occurs. Run cantata from a commandline as follows:

CANTATA_DEBUG=1 cantata

Wait for the error to occur, and when it does stop cantata. The upload ~/.cache/cantata/cantata.log somewhere and add a link here.

**Comment by chowbok** [comment]
Typically my playlists are 1024 songs. MPD is on a different machine on my local network. Will do the log shortly.

**Comment by chowbok** [comment]
It hadn't been happening as often, but it is today. The first time I started it, it disconnected right away. Log is at [http://sprunge.us/UWaP](http://sprunge.us/UWaP).

I'll do another one after it's been running for a minute, think I figured out a way to trigger it.

**Comment by chowbok** [comment]
Guess not. It was disconnecting when I would select multiple files, right-clicking, and selecting "insert after current". But now it's working fine. Maybe I'll just set the shortcut to use debugging so I can get a capture whenever it happens.

**Comment by CDrummond** [comment]
The log file was pretty useless - didn't say much. Anyhow, I've increased the timeouts. Please update git/master and let me know if this helps.

**Comment by chowbok** [comment]
No disconnections in three days. I think this is fixed now. Thanks!
