### ISSUE TITLE
Build error with latest git

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#989]
Getting this error when I try to build the latest version:
`CMake Error at 3rdparty/solid-lite/CMakeLists.txt:290 (QT4_WRAP_CPP):
Unknown CMake command "QT4_WRAP_CPP".
`
Let me know what other information you need.

**Comment by CDrummond** [comment]
Qt4 no longer supported - please do a clean build (as in delete build folder, and re-run CMake)
