### ISSUE TITLE
Cantata sometimes stops playing from a stream when changing songs 

### ISSUE THREAD

**Issue by psy-q** [CDrummond/cantata#992]
I have mpd 0.19.19 running on my NAS and Cantata 2.0.1.ds1-2 streaming in FLAC format from there.

Sometimes I notice there have been several minutes of silence even though my playlist is full of songs. When I check Cantata, I notice it has advanced through the songs normally and is playing them correctly, but the stream audio does not play. The problem can be triggered by randomly selecting songs from the playlist via mouse. I have the issue on three different Debian 9 systems.

Clicking the headphone (stream) icon twice in this situation will bring back the stream and audio output resumes. 

mpd.log shows nothing suspicious, neither does Cantata's console output. What could I try to narrow down the problem?

**Comment by CDrummond** [comment]
To be honest, I have no idea. The stream playback code is very simple. Cantata just passes the MPD stream HTTP URL to libVLC (or QtMultimedia) and tells it to play. Which backend have you compiled Cantata to use? It should be using libVLC by default.

I guess Cantata could poll the backend to ensure playback is OK.

**Comment by psy-q** [comment]
Yes, it's using libVLC. I will test with VLC standalone vs. mpv vs. some web browser (maybe Firefox) to see if playback stops there as well. That would perhaps indicate some issue in mpd.

**Comment by psy-q** [comment]
It stops with any stream player. I think this is not a Cantata issue. I will follow this up as mpd issue, or maybe it has something to do with the FLAC libraries. Thanks a lot for the great mpd client, by the way :)

**Comment by psy-q** [comment]
It seems like the fix is to set a format (e.g. "44100:16:2") on your HTTP output.
