### ISSUE TITLE
Some problems with the new "duration" feature in dynamic playlists

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#993]
I feel really bad filing another bug on this when you were so cool as to put this feature in, but... the limits on the playlist duration parameters in the dynamic playlist actually aren't inclusive enough. I was hoping to do, say, "songs greater than 15 minutes", and I can't because the "shorter than" upper limit is 300 seconds and there's also a "longer than" limit. Also, since it's with the ratings rather than in a rule creation box, I have to come up with other rules to use it. It'd be much more flexible and useful if it could be part or all of a specific dynamic rule.

Again, sorry about this! Thanks again for a great program.

**Comment by CDrummond** [comment]
I'll change the limits, but not the positioning.

**Comment by CDrummond** [comment]
Changed both limits to 30mins

**Comment by chowbok** [comment]
Github doesn't let me reopen issues that I didn't close, though.
