### ISSUE TITLE
Custom default directory for lyrics (and others)

### ISSUE THREAD

**Issue by holytrousers** [CDrummond/cantata#995]
hello,
thank you for this great mpd client !
cantata already offers the choice whether to store downloaded lyrics inside the song's folder or in the default directory... but there is no possibility to change the latter's location (and btw the filename pattern).
that would improve resource sharing with other clients ( ncmpc default to ~/.lyrics with extension .txt )
cheers :)

**Comment by CDrummond** [comment]
Sorry, but not going to change this. I **hate** having my $HOME littered with more and more dot files/dirs.

**Comment by holytrousers** [comment]
that wouldn't lead to more dot files, on the contrary : if a user already has a directory where he stores his lyrics files, cantata could access them directly instead of downloading them again from the internet.
anyway thanks for the quick reply ;)

**Comment by CDrummond** [comment]
Freedesktop.org defines 3 locations apps should use. XDG_CACHE_HOME ($HOME/.cache), XDG_DATA_HOME ($HOME/.local/share) and XDG_CONFIG_HOME ($HOME/.config) These are the **only** hidden folders *I* believe an app should write to.

Now, if you wish to propose a new shared standard for the location of lyrics (e.g. $XDG_DATA_HOME/music/lyrics) and a format for the sub-folders and files - then once this is approved I'll happily adopt it.

But creating ~/.lyrics is just awful - and I will not support this.

**Comment by holytrousers** [comment]
nevermind, thanks you for your kind reply again :)

**Comment by bb010g** [comment]
You could probably use a symbolic link from ~/.lyrics to the proper XDG subdirectory.

**Comment by holytrousers** [comment]
that's a clever idea :)
any idea on how to deal with the naming pattern ? 
cantata filename pattern is "artist/title.lyrics" 
ncmpcpp's is "artist - title.txt"
they would still remain incompatible.
