### ISSUE TITLE
Maximum duration limit in dynamic playlists shouldn't equal minimum duration limit

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#996]
Thanks for increasing the limits of the durations in the dynamic playlists, but, unfortunately, I'm still not able to do what I want, which is to find songs longer than 15 minutes. The problem is that the maximum duration limit is set to 1800, the same as the minimum duration limit. This means I can only search for songs _less_ than 15 minutes. Would it be possible to have no ceiling, just like there's (effectively) no floor? Barring this, maybe the maximum could be increased, to, say, 3600 seconds? 

(By the way, I know you said to reopen the old ticket rather than open a new one, but GitHub doesn't let me reopen a ticket that I didn't close, even if I was the reporter).

**Comment by CDrummond** [comment]
No, you can search for songs from 15 minutes onwards. Set no max limit.
