### ISSUE TITLE
Compile error with -DENABLE_REMOTE_DEVICES=ON

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#998]
Could you advise me to try this option?

[ 45%] Building CXX object CMakeFiles/cantata.dir/devices/devicespage.cpp.o
/home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.cpp: In member function ‘void DevicesPage::forgetRemoteDevice()’:
/home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.cpp:506:108: error: no matching function for call to ‘DevicesPage::tr(const char [38], QString&)’
 ox::warningYesNo(this, tr("Are you sure you wish to forget '%1'?", devName))) {
                                                                           ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:45:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:40,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from /home/parkmino/Downloads/mpd/cantata-svn/models/musiclibraryitemroot.h:31,
                 from /home/parkmino/Downloads/mpd/cantata-svn/devices/device.h:27,
                 from /home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.h:27,
                 from /home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.cpp:24:
/home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.h:39:5: note: candidate: static QString DevicesPage::tr(const char*, const char*, int)
     Q_OBJECT
     ^
/home/parkmino/Downloads/mpd/cantata-svn/devices/devicespage.h:39:5: note:   no known conversion for argument 2 from ‘QString’ to ‘const char*’
CMakeFiles/cantata.dir/build.make:5161: recipe for target 'CMakeFiles/cantata.dir/devices/devicespage.cpp.o' failed
make[2]: *** [CMakeFiles/cantata.dir/devices/devicespage.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/cantata.dir/all' failed
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by CDrummond** [comment]
Fixed.
