### ISSUE TITLE
[Enhancement] Enable external device for the next window build

### ISSUE THREAD

**Issue by parkmino** [CDrummond/cantata#999]
I'd like to use external device in window if possible.

**Comment by CDrummond** [comment]
Sorry - don't have the time for this. Remove device support code is **very** Linux specific. I exclusively use Linux, and have no time for porting this (non-default) code to Win/Mac.

If you want this, then you'll need to code it yourself. Sorry, but Win/Mac support was only ever just to see if I could do it - I have never actively used Cantata on either.
